"""Write audio-data.js, MAP.md, credits.html, ASSETS.md for Cauldron Fair and append NEW rows to ../../audio/ASSETS.md.
Usage: python3 bundle_cauldron.py <workdir>   (workdir = build_cauldron.py output)"""
import os, sys, json, base64
HERE = os.path.dirname(os.path.abspath(__file__)); SHARED = os.path.join(HERE, '..', '..', 'audio')
W = os.path.abspath(sys.argv[1]); R = json.load(open(os.path.join(W, 'report.json')))
DATE = '2026-10-04'; CC0U = 'https://creativecommons.org/publicdomain/zero/1.0/'
b64 = lambda p: base64.b64encode(open(p, 'rb').read()).decode()
KEN = {'casino-audio': 'Casino Audio', 'interface-sounds': 'Interface Sounds', 'impact-sounds': 'Impact Sounds', 'rpg-audio': 'RPG Audio', 'ui-audio': 'UI Audio', 'music-jingles': 'Music Jingles', 'sci-fi-sounds': 'Sci-fi Sounds'}
OGA = {'100-CC0-SFX_0': ('100 CC0 SFX', '100-cc0-sfx'), 'water-splash-slime-sfx': ('40 CC0 water splash, slime SFX', '40-cc0-water-splash-slime-sfx'), 'sfx_loops': ('30 CC0 SFX loops', '30-cc0-sfx-loops')}
USE = {'click': 'buttons', 'draw': 'a chip leaves the bag', 'plop': 'a chip lands in the pot', 'splash': 'a bigger splash (orange chip, droplet moves)', 'boom': 'the cauldron overflows',
       'flask': 'flask used (glass + bubble)', 'ruby': 'a ruby is earned or spent', 'coin': 'coins gained', 'tick': 'score counting, rising `rate`', 'die': 'bonus die rolled',
       'page': 'day report / rules page turns', 'round': 'round ends', 'win': 'game over, winner', 'error': 'illegal move', 'buy': 'an ingredient is bought', 'bubble': 'a bubble pops (pot flavour)',
       'pass': 'hot-seat pass screen', 'bubbling': 'pot simmering loop (quiet, under music)'}
def src_row(sp):
    if sp.startswith('oga/'):
        d = sp.split('/')[1]; t, slug = OGA[d]; return ('`%s`' % os.path.basename(sp), '[%s](https://opengameart.org/content/%s)' % (t, slug), 'rubberduck')
    pk = sp.split('/')[0]; return ('`%s`' % sp.replace('/Audio/', '/'), '[Kenney %s](https://kenney.nl/assets/%s)' % (KEN[pk], pk), 'Kenney (Kenney Vleugels)')
srcs = lambda sp: [sp['src']] + [m[0] for m in sp.get('mix', [])]
parts = ['/* audio-data.js for Cauldron Fair - generated by audio/bundle_cauldron.py. Licences: see ASSETS.md */', 'const GA_DATA={sfx:{']
sb = mb = 0
for n in USE: p = os.path.join(W, 'sfx', n + '.mp3'); sb += os.path.getsize(p); parts.append('"%s":"%s",' % (n, b64(p)))
p = os.path.join(W, 'music', 'main.mp3'); mb += os.path.getsize(p)
parts += ['},music:{', '"main":"%s",' % b64(p), '}};']; js = '\n'.join(parts) + '\n'; open(os.path.join(HERE, 'audio-data.js'), 'w').write(js)
L = ['# Cauldron Fair: audio assets\n', 'All sounds are real CC0 recordings (Kenney packs, OpenGameArt), cut/layered/normalised by `build_cauldron.py` and bundled by `bundle_cauldron.py` (they import `../../audio/tools/dsp.py`, `sfx.py`). Checked %s. Licence snapshots: `licence-snapshots/` here. Nothing is synthesised; the browser synth in the game is only a fallback when a sample is missing.\n' % DATE,
     '## Sound effects (mono MP3 48 kbps; `bubbling` 32 kbps)\n', '| sample | source file(s) | pack | licence | length | size | use |', '|---|---|---|---|---|---|---|']
for n, v in R['sfx'].items():
    rows = [src_row(x) for x in srcs(v['spec'])]
    L.append('| `%s` | %s | %s | CC0 1.0 | %.2f s | %d B | %s |' % (n, ', '.join(r[0] for r in rows), ', '.join(sorted({r[1].split(']')[0][1:] for r in rows})), v['dur'], v['bytes'], USE[n]))
m = R['music']['main']
L += ['', '## Music (mono MP3 40 kbps, seamless loop)\n', '| name | track | author | source page | licence | loop cut | length | size |', '|---|---|---|---|---|---|---|---|',
      '| `main` | "Medieval: Market Day" (`Loop_Market_Day.wav`) | RandomMind | https://opengameart.org/content/medieval-market-day | CC0 1.0 | %.2f s-%.2f s, 1.5 s cross-fade (similarity %.3f) | %.1f s | %d B |' % (m['a'], m['b'], m['sim'], m['dur'], m['bytes'])]
L.append('\nTotals: SFX %d KB + music %d KB MP3; `audio-data.js` %d KB (base64). Licence: CC0 1.0 %s\n' % (sb // 1024, mb // 1024, len(js) // 1024, CC0U))
L.append('Rebuild: `python3 build_cauldron.py <raw> <work> && python3 bundle_cauldron.py <work>` (raw = Kenney zips unpacked + `oga/` rubberduck packs unpacked + `mus/Loop_Market_Day.wav`).\n')
open(os.path.join(HERE, 'ASSETS.md'), 'w').write('\n'.join(L))
M = ['# Cauldron Fair: sound map\n', "Load order: `gameaudio.js`, this `audio-data.js`, then the game. `GA.init({sfx:GA_DATA.sfx, music:GA_DATA.music, key:'cf'})`.\n", '| sample | length | suggested use |', '|---|---|---|']
for n in USE: M.append('| `%s` | %.2f s | %s |' % (n, R['sfx'][n]['dur'], USE[n]))
M += ['', "Music: `GA.music('main')`; `GA.loop('bubbling',{vol:.12,fade:1.5})`. The user has not auditioned these by ear: tune per-sound `vol` in the game's `SND_MAP`."]
open(os.path.join(HERE, 'MAP.md'), 'w').write('\n'.join(M) + '\n')
packs = sorted({KEN[x.split('/')[0]] for v in R['sfx'].values() for x in srcs(v['spec']) if not x.startswith('oga/')})
open(os.path.join(HERE, 'credits.html'), 'w').write('<!-- Credits snippet for Cauldron Fair. Generated %s. -->\n<section class="credits-audio">\n<h3>Audio</h3>\n<p>With thanks to these public-domain (CC0) creators:</p>\n<ul>\n<li>Music: &ldquo;Medieval: Market Day&rdquo; by RandomMind (<a href="https://opengameart.org/content/medieval-market-day">OpenGameArt</a>, CC0)</li>\n<li>Splashes, bubbles, pot and boil sounds: rubberduck (<a href="https://opengameart.org/content/100-cc0-sfx">OpenGameArt</a>, CC0)</li>\n<li>Sound effects: %s by <a href="https://kenney.nl">Kenney</a> (CC0)</li>\n</ul>\n<p><small>All sounds were trimmed, loudness-normalised and converted to MP3 for this game. Names, card text and art are original.</small></p>\n</section>\n' % (DATE, ', '.join(packs)))
p = os.path.join(SHARED, 'ASSETS.md'); t = open(p).read()
if 'cauldron-fair/' in t: print('shared ASSETS.md already has rows'); sys.exit()
uses = {}
for n, v in R['sfx'].items():
    for sp in srcs(v['spec']): uses.setdefault(sp, []).append('cauldron-fair/' + n)
rows = []
for sp, outs in sorted(uses.items()):
    f, pg, au = src_row(sp)
    rows.append('| %s | %s | %s | CC0 1.0 | %s | %s | trimmed silence, layered where noted, normalised, mono MP3 48 kbps | %s |' % (f, pg, au, CC0U, DATE, ', '.join(outs)))
rows.append('| `Loop_Market_Day.wav` | [Medieval: Market Day](https://opengameart.org/content/medieval-market-day) | RandomMind | CC0 1.0 | %s | %s | cut %.2fs-%.2fs, 1.5 s cross-fade; normalised; mono 40 kbps MP3 | cauldron-fair/music.main |' % (CC0U, DATE, m['a'], m['b']))
lines = t.split('\n'); last = max(i for i, l in enumerate(lines) if l.startswith('| `'))
lines[last + 1:last + 1] = rows
open(p, 'w').write('\n'.join(lines)); print('appended', len(rows), 'rows')
