// wb/shots.js <url> fra|ath <outdir> : chase-view shots (852x393, normal gfx) at the 3 ath/perf.js spots + 2 extra, with calls/tris in the name list
const enter=require('../../bc/enter.js');const fs=require('fs');const URL=process.argv[2],CITY=process.argv[3]||'fra',OUT=process.argv[4];fs.mkdirSync(OUT,{recursive:true});
(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:'normal',seed});const {p,errs}=E;p.setDefaultTimeout(900000);if(process.env.SET)await p.evaluate(v=>__g9ev(v),process.env.SET);await E.roamApi();await p.evaluate(()=>window.__wb&&window.__wb.fast&&window.__wb.fast());
 const F=(process.env.SPOTS||'0.1,0.3,0.5,0.7,0.9').split(',').map(Number);
 const spots=await p.evaluate(F=>{const N=__mho.HUB.nodes,ok=[];for(let i=0;i<N.length;i++){const a=N[i];if(a&&a.nb&&a.nb.length>=2&&!a.ab&&N[a.nb[0]])ok.push(i)}return F.map(f=>{const a=N[ok[Math.floor(f*ok.length)]],b=N[a.nb[0]];return[a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z)]})},F);const out=[];
 for(let i=0;i<spots.length;i++){const [x,z,h]=spots[i];await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+60);R.v=0;R.vh=h;R.h=h},[x,z,h]);await p.waitForTimeout(7000);
  const n=await p.evaluate(()=>{const r=__g9ev('renderer');r.info.autoReset=false;r.info.reset();__tick(1);const o={calls:r.info.render.calls,tris:r.info.render.triangles};r.info.autoReset=true;return o});
  await p.evaluate(()=>{for(const id of['roamCard','odChk','odPin'])if(document.getElementById(id))document.getElementById(id).style.visibility='hidden';for(const b of document.querySelectorAll('button,div,a'))if(/^CONTINUE/.test((b.textContent||'').trim())&&b.children.length<3){let q=b;for(let k=0;k<6&&q.parentElement&&q.parentElement!==document.body;k++)q=q.parentElement;q.style.visibility='hidden'}});const f=`${OUT}/${CITY}_${F[i]}.png`;await p.screenshot({path:f});out.push([f,n.calls,n.tris]);
  if(process.env.DRONE){await p.evaluate(()=>{const C=__g9ev('composer'),cam=__g9ev('camera');if(!window.__dr0){window.__dr0=C.render.bind(C);C.render=function(...a){if(window.__drone){const R=__mho.RO,h=R.h;cam.position.set(R.x-Math.sin(h)*70,R.y+75,R.z-Math.cos(h)*70);cam.lookAt(R.x+Math.sin(h)*500,R.y,R.z+Math.cos(h)*500);cam.updateMatrixWorld()}return window.__dr0(...a)}}window.__drone=1});await p.waitForTimeout(1500);
   const n2=await p.evaluate(()=>{const r=__g9ev('renderer');r.info.autoReset=false;r.info.reset();__g9ev('composer').render();const o={calls:r.info.render.calls,tris:r.info.render.triangles};r.info.autoReset=true;return o});
   const f2=`${OUT}/${CITY}_${F[i]}_drone.png`;await p.screenshot({path:f2});out.push([f2,n2.calls,n2.tris]);await p.evaluate(()=>{window.__drone=0})}}
 console.log(JSON.stringify(out));console.log('errors',errs.length,errs.slice(0,2).join('|').slice(0,200));await E.b.close()})();
