// wb/top.js <url> fra|ath : top draw-call/triangle sources at one street spot (frustum-visible), grouped by name/material/parent
const enter=require('../../bc/enter.js');const URL=process.argv[2],CITY=process.argv[3]||'fra',SPOT=+(process.env.SPOT||0.5);
const DET=process.env.DET;(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:process.env.GFX||'normal',seed});const {p,errs}=E;p.setDefaultTimeout(900000);await E.roamApi();await p.evaluate(()=>window.__wb&&window.__wb.fast&&window.__wb.fast());
 const s=await p.evaluate((f)=>{const N=__mho.HUB.nodes,ok=[];for(let i=0;i<N.length;i++){const a=N[i];if(a&&a.nb&&a.nb.length>=2&&!a.ab&&N[a.nb[0]])ok.push(i)}const a=N[ok[Math.floor(f*ok.length)]],b=N[a.nb[0]];return[a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z)]},SPOT);
 await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+60);R.v=0;R.vh=h;R.h=h},s);await p.waitForTimeout(7000);
 const out=await p.evaluate((DET)=>{const r=__g9ev('renderer'),sc=__g9ev('scene');__tick(1);
  // hook renderObject to count actual draws per object
  const g={},DETX=DET;const ro=r.renderBufferDirect.bind(r);r.renderBufferDirect=function(cam,scn,geo,mat,obj,grp){const ic=obj.isInstancedMesh?obj.count:1;if(!ic)return ro(cam,scn,geo,mat,obj,grp);const idx=geo.index?geo.index.count:(geo.attributes.position?geo.attributes.position.count:0);const dr=geo.drawRange;const n=Math.min(idx,dr.count===Infinity?idx:dr.count);const tri=(obj.isMesh?n/3:0)*ic;
   let path=[];let o=obj;for(let i=0;i<3&&o;i++){path.push((o.name||o.type)+(o.userData&&Object.keys(o.userData).length?'{'+Object.keys(o.userData).slice(0,3).join(',')+'}':''));o=o.parent}
   const k=path.join('<')+' |'+(mat.name||mat.type)+(mat.map?'+map':'')+(obj.castShadow?' cs':'')+(DETX==='b'?(()=>{const bs=obj.isInstancedMesh?obj.boundingSphere:geo.boundingSphere;const c=bs?bs.center.clone().applyMatrix4(obj.matrixWorld):null;const d=c?Math.hypot(c.x-cam.position.x,c.z-cam.position.z)-(bs.radius||0):0;return ' D'+(d<150?'<150':d<400?'<400':d<800?'<800':'800+')+(obj.isInstancedMesh?' I'+((geo.index?geo.index.count:geo.attributes.position.count)/3<1200?'s':'L'):' M')})():DETX?' id'+obj.id+' n'+ic+' t'+Math.round(n/3)+(obj.frustumCulled?'':' NFC')+' d'+Math.round(Math.hypot(obj.matrixWorld.elements[12]-cam.position.x,obj.matrixWorld.elements[14]-cam.position.z))+' r'+Math.round(geo.boundingSphere?geo.boundingSphere.radius:-1):'');const e=g[k]||(g[k]={k,calls:0,tris:0,sh:0});if(cam.isOrthographicCamera||cam.type==='OrthographicCamera'){e.sh++}else{e.calls++;e.tris+=tri}return ro(cam,scn,geo,mat,obj,grp)};
  r.info.autoReset=false;r.info.reset();__tick(1);r.renderBufferDirect=ro;const tot={calls:r.info.render.calls,tris:r.info.render.triangles};r.info.autoReset=true;
  const L=Object.values(g);const byC=[...L].sort((a,b)=>b.calls-a.calls).slice(0,40),byT=[...L].sort((a,b)=>b.tris-a.tris).slice(0,30);
  let shadowCasters=0;sc.traverse(o=>{if(o.isMesh&&o.castShadow&&o.visible)shadowCasters++});
  return {tot,sum:{calls:L.reduce((a,e)=>a+e.calls,0),tris:Math.round(L.reduce((a,e)=>a+e.tris,0)),sh:L.reduce((a,e)=>a+e.sh,0)},shadowCasters,byC,byT}},DET);
 console.log(JSON.stringify(out.tot),JSON.stringify(out.sum),'casters',out.shadowCasters);console.log('--- by calls');for(const e of out.byC)console.log(e.calls,e.sh,Math.round(e.tris),e.k);console.log('--- by tris');for(const e of out.byT)console.log(Math.round(e.tris),e.calls,e.k);console.log('errors',errs.length);await E.b.close()})();
