// every pilot and every upgrade gets forced into a battle; report errors and whether its effect shows up in the log
const {JSDOM}=require('jsdom');const fs=require('fs');const html=fs.readFileSync('nebula.html','utf8');
const probe=new JSDOM(html,{runScripts:'dangerously',url:'http://localhost/'}).window;const P=probe.eval('PILOTS'),U=probe.eval('UPGRADES'),S=probe.eval('SHIPS');
const which=process.argv[2]||'pilots';const reps=+(process.argv[3]||2);
const fac=k=>S[P[k].ship].fac;
function squadWith(pk,uk){const u=[];if(uk==='t_warden')u.push('t_warden','u_hplasma');else if(uk)u.push(uk);return [{p:pk,u}]}
function run(sq0,side){return new Promise(res=>{const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'http://localhost/'});const w=dom.window;const errs=[];
  w.addEventListener('error',e=>errs.push((e.error&&e.error.stack||e.message).slice(0,400)));w.console.error=(...a)=>errs.push(a.join(' ').slice(0,300));
  w.eval('ANIM=0;AIDELAY=0');const ex={w1:true,w2:true,w3:true};
  const f=fac(sq0[0].p);w.__sq0=sq0;w.eval(`(function(){const ex=${JSON.stringify(ex)};const mine=window.__sq0.concat(randomSquad(${f},55,ex));const foe=randomSquad(${1-f},100-squadCost(mine)+100-100+Math.max(60,squadCost(mine)),ex);
     newGame({fac:${f}===0?[0,1]:[1,0],players:[{human:false},{human:false}],squads:[mine,foe],ex})})()`);
  const t0=Date.now();const iv=setInterval(()=>{const G=w.eval('G');const inv=w.eval('checkInvariants()');if(inv.length&&errs.length<3)errs.push('INV '+inv[0]);
    if(G.winner||errs.length>2||Date.now()-t0>(+process.env.TLIM||25000)){clearInterval(iv);res({w:G.winner,round:G.round,errs,log:G.log.map(l=>l.t).join('\n'),fired:G.fired||{}});w.close()}},5)})}
(async()=>{const SH=+(process.env.SH||0),NS=+(process.env.NS||1);// the effect counters (mark(k) in the rules code) that show each card's ability actually happened; passive cards are checked by their stats
const EXPECT={kael:['dmod:kael'],brink:['PASSIVE target restriction'],knife:['knife'],hex:['hex'],nightjar:['nightjar'],wren:['wren'],garrick:['garrick'],brannoc:['brannoc'],horace:['amod:horace'],gutter:['amod:gutter'],shiv:['shiv'],wailer:['amod:wailer'],varn:['varn'],castigan:['castigan'],tamsin:['tamsin'],arlo:['arlo'],grudge:['grudge'],tarn:['tarn'],sorin:['sorin'],grawl:['grawl'],lark:['lark'],jax:['amod:jax'],kira:['kira'],bram:['bram'],krell:['amod:krell'],oren:['oren'],iveth:['amod:iveth','dmod:ibtd'],quill:['quill'],kellan:['kellan'],juno:['juno'],joren:['amod:joren'],rhane:['rhane'],kade:['kade'],varek:['varek'],orrin:['orrin'],
  u_plasma:['amod:f2c'],u_tinker:['tinker'],u_juke:['act:JK'],u_will:['will'],u_dead:['act:MK'],u_ionturret:['ion'],u_assist:['assist'],u_patch:['act:PA'],u_relock:['relock'],u_scrap:['scrap'],u_pack:['pack'],u_lead:['lead'],u_snap:['eh'],u_shock:['amod:b2h'],u_swarmm:['twice'],u_hairpin:['hairpin'],u_slip:['damod:slip'],u_seeker:['wpn:Seeker Missiles'],u_redline:['redline'],u_snapeye:['snapeye'],u_allin:['act:EX'],u_tailgun:['gunner'],u_ionlance:['ion'],u_beam:['wpn:Heavy Beam Cannon'],u_quake:['bomb:u_quake'],u_hired:['amod:hired'],u_burst:['splash'],u_oldinst:['PASSIVE +2 pilot skill'],u_mines:['mine'],u_fct:['we2'],u_heat:['heat'],u_rook:['gunner'],u_nib:['nib'],u_brakk:['brakk'],u_hplasma:['amod:b2f'],u_rapid:['wpn:Rapid Blaster'],u_track:['track'],u_twin:['wpn:Paired Bolt Turret'],u_scout:['scout'],u_sab:['sab'],u_spot:['intel'],u_pbomb:['bomb:u_pbomb'],u_adren:['adren'],u_early:['early'],u_jam:['damod:jam'],u_vell:['vell'],u_captive:['captive'],u_instr:['dmod:instr'],u_nav:['nav'],t_warden:['wpn:Heavy Plasma Torpedoes'],t_lucky:['act:E'],t_kite:['kite'],t_writ:['writ'],m_stealth:['stealth'],m_shield:['PASSIVE +1 shield'],m_engine:['act:BO'],m_apl:['apl']};
const never=[];
const keys=(which==='pilots'?Object.keys(P).filter(k=>P[k].ab):Object.keys(U)).filter((k,i)=>i%NS===SH).filter(k=>!process.env.ONLY||process.env.ONLY.split(',').includes(k));let bad=0,out=[];
  for(const k of keys){let pk=k,uk=null;if(which!=='pilots'){uk=k;const u=U[k];pk=Object.keys(P).find(p=>P[p].u.includes(u.slot)&&(!u.ship||u.ship===P[p].ship)&&(u.fac==null||u.fac===fac(p))&&(!u.small||S[P[p].ship].base!=='L')&&(!u.large||S[P[p].ship].base==='L'));if(!pk){out.push(k+': NO CARRIER');continue}}
    let errs=[],logs='',done=0,unfinished=0;const fired={};for(let r=0;r<reps;r++){const x=await run(squadWith(pk,uk));errs=errs.concat(x.errs);logs+=x.log;for(const k in x.fired)fired[k]=(fired[k]||0)+x.fired[k];if(x.w)done++;else unfinished++}
    const name=which==='pilots'?P[k].n:U[k].n;const exp=(EXPECT[k]||['?']).filter(q=>!q.startsWith('PASSIVE'));const miss=exp.filter(q=>!fired[q]);if(miss.length&&miss.length===exp.length)never.push(k+' ('+miss.join(',')+')');const seen=logs.includes(name)?(logs.split(name).length-1):0;if(errs.length)bad++;
    out.push(`${k.padEnd(10)} ${name.padEnd(26)} games ${done}/${reps}${unfinished?' UNFINISHED':''} mentions ${seen} fired ${JSON.stringify(Object.fromEntries(Object.entries(fired).filter(([k])=>!/^wpn:Primary|^act:(F|TL|E|BR|BO|skip)$|^amod:(focus|tl)$|^dmod:(focus|evade)$/.test(k))))}${errs.length?' ERR '+errs[0].replace(/\n\s+at /g,' @ ').slice(0,260):''}`)}
  console.log(out.join('\n'));console.log('with errors:',bad);console.log('expected counter never fired:',never.join('; ')||'none')})();
