# pART8 · roads always on top of the grass (refined road strips + polygonOffset), coarser grass away from roads (fps), crisp car-shaped
# sun shadows for every car (module art8.js; art7.js quadtree tolerance by road distance)
exec(open('P.py').read());exec(open('artlib.py').read())
RR("function abStrip(P,i0,i1,oa,ob,ya,yb,uvL){const pos=[],uvs=[],idx=[];for","function abStrip_v86(P,i0,i1,oa,ob,ya,yb,uvL){const pos=[],uvs=[],idx=[];for")
ART_mod('art8.js')
# stencil for the one-silhouette-per-car shadows (main framebuffer + the composer's render targets)
RR("renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'})","renderer=new THREE.WebGLRenderer({canvas,antialias:false,stencil:true,powerPreference:'high-performance'})")
RR("new THREE.WebGLRenderTarget(16,16,{type:THREE.HalfFloatType,samples:","new THREE.WebGLRenderTarget(16,16,{type:THREE.HalfFloatType,stencilBuffer:true,samples:")
save()
# smaller ground tiles so frustum culling skips the grass behind and beside the camera (city box 1000 → 500 m, outer land 2000 → 1000 m)
RR("uv:10,tile:1000,","uv:10,tile:500,")
RR("uv:14,tile:2000,","uv:14,tile:1000,")
save()
RR("const g=new THREE.PlaneGeometry(w,L,Math.max(1,Math.ceil(w/4)),Math.max(1,Math.ceil(L/4)));","const g=new THREE.PlaneGeometry(w,L,...ART8_ps(x0,z0,ux,uz,w,L));")
RR("const g=new THREE.PlaneGeometry(X.wa,X.wb,Math.max(1,Math.ceil(X.wa/4)),Math.max(1,Math.ceil(X.wb/4)));","const g=new THREE.PlaneGeometry(X.wa,X.wb,...ART8_pq(X.x,X.z,X.wa,X.wb));")
save()
# grass under roads dips (quadtree leaves); junction discs drape over the ground (flat discs sank up to 14 cm on Athens slopes)
RR("[lx+a*sx,o.y0+tH(lx+a*sx,lz+b*sz),lz+b*sz,0]","[lx+a*sx,o.y0+tH(lx+a*sx,lz+b*sz)-ART8_dip(lx+a*sx,lz+b*sz),lz+b*sz,0]")
RR("for(const J of JUNC){const g=new THREE.CircleGeometry(J.r,24);g.rotateX(-Math.PI/2);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,uv.getX(i)*J.r/8,uv.getY(i)*J.r/8);g.translate(J.x,groundY(J.x,J.z)+.056,J.z);bt.add(g,jm)}",
   "for(const J of JUNC){const g=new THREE.RingGeometry(.01,J.r,24,Math.max(2,Math.ceil(J.r/2)));g.rotateX(-Math.PI/2);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,uv.getX(i)*J.r/8,uv.getY(i)*J.r/8);g.translate(J.x,0,J.z);const ps=g.attributes.position;for(let i=0;i<ps.count;i++)ps.setY(i,groundY(ps.getX(i),ps.getZ(i))+.056);g.computeVertexNormals();bt.add(g,jm)}")
save()
# river cells: 25 m blocks; only blocks at the water keep the bank-snapped uniform grid (ART7_res), the rest use the quadtree
# (one road-side bank spot used to force a 3 m grid over the whole 200 m cell: ~70k triangles in view on the hill route)
RR("if(o.hilly){const m=ART7_res(ax,ax+dx,az,az+dz);if(m>n){n=m;f=dx/n}}}else if(o.hilly){Q=[];ART7_quad(ax,az,dx,dz,Q)}","if(o.hilly)Q=ART8_riv(ax,az,dx,dz,n)}else if(o.hilly){Q=[];ART7_quad(ax,az,dx,dz,Q)}")
RR("for(const[lx,lz,lw,lh]of Q||[[ax,az,dx,dz]]){if(Q){n=1;f=lw}","for(const[lx,lz,lw,lh,ln,sn]of Q||[[ax,az,dx,dz]]){if(Q){n=ln||1;f=lw/n}")
RR("V.push(n>1?gndVert(lx+a*sx,lz+b*sz,o.y0,f):[lx+a*sx,","V.push(n>1||sn?gndVert(lx+a*sx,lz+b*sz,o.y0,f):[lx+a*sx,")
save()
