# pART2 · brick trees (Frankfurt props + Athens street trees), studs on roofs/tops, plastic rim (module art2.js)
exec(open('P.py').read());exec(open('artlib.py').read())
ART_mod('art2.js')
RR("hboat:K('boat-house-a',3.2,5,10,.75,['#e8c090','#6b4a2a'])});","hboat:K('boat-house-a',3.2,5,10,.75,['#e8c090','#6b4a2a'])});ART_trees(D);")
RR("const athTreeGeo=()=>{const P=","const athTreeGeo=()=>ART_athTree();const athTreeGeo0=()=>{const P=")
RR("const athTreeBy=k=>{","const athTreeBy=k=>ART_athTreeBy(k)||athTreeBy0(k);const athTreeBy0=k=>{")
save()
