# OB · owner bugs part 1: phantom brick bursts (cause log, oriented contact tests, auto-switch hysteresis)
exec(open('P.py').read())
R('window.__mho={', open('ob.js').read()+'\nwindow.__mho={')
# props: the car's footprint must touch the prop (was a circle of r+2.1 m)
R('if(d>def.r+2.1||Math.abs(p.y-RO.y)>4)continue;','if(d>def.r+2.1||Math.abs(p.y-RO.y)>4||!OB_touch(p.x,p.z,def.r))continue;')
# traffic: oriented box overlap (was any car within 5 m, i.e. the next lane)
R('const d=Math.hypot(x-RO.x,z-RO.z);if(d<5&&Math.abs(c.y-RO.y)<3){','const d=Math.hypot(x-RO.x,z-RO.z);if(d<5&&Math.abs(c.y-RO.y)<3&&OB_car(x,z,dx,dz,c)){')
R('||Math.hypot(k.x-P.x,k.z-P.z)>=5)continue;','||Math.hypot(k.x-P.x,k.z-P.z)>=5||!OB_carP(k,P))continue;')
save()
