exec(open('P.py').read())
# OC: soft night lights, real-scale Acropolis, height fixes, props off the roads (module oc.js)
R('["akro","Acropolis",65,-490,125,70,55,"mesa",{"apron":3.2,"cliff":0.3}]','["akro","Acropolis",65,-498,123,86,55,"mesa",{"apron":3.2,"cliff":0.27}]')
R('const H0=A.H;for(let j=0;j<nz;j++)','top=OC_top(top);const H0=A.H;for(let j=0;j<nz;j++)')
R('TR_W={r,nx,nz,h};return TR_W}','OC_lyka(h,nx,nz,r);TR_W={r,nx,nz,h};return TR_W}')
R('if(A){const N=64,pt=t=>','if(A&&OC.ring0){const N=64,pt=t=>')
R('const have=id=>HUB.lmk.find(L=>L.id===id)','const have=id=>!OC.skip.test(id)&&HUB.lmk.find(L=>L.id===id)')
R('CT.push(performance.now());HUB.props=L;','CT.push(performance.now());OC_props(L,D);HUB.props=L;')
R('continue;out.push({t,x,z,y:y??groundY(x,z)','continue;if(OC_onRoad(t,x,z))continue;out.push({gp:y==null,t,x,z,y:y??OC_gy(t,x,z)')
R('MAT.pool.opacity=.38*m.lamps','MAT.pool.opacity=.24*m.lamps')
R('fl:3+Math.floor(rnd()*3),fh:3.1,nb:1}','fl:OC_ifl(3+Math.floor(rnd()*3),sty),fh:3.1,nb:1}')
R('fh:4.2}','fh:3.3}')
R('neo:athIM(BM.neo,4.2)','neo:athIM(BM.neo,3.3)')
R('const put=(U,x,z,ry,c,s,fr)=>{const{w,d,fl,fh,k}=U,','const put=(U,x,z,ry,c,s,fr)=>{U=OC_fix(U,x,z);const{w,d,fl,fh,k}=U,')
R('for(const L of LMX)cap(L.x,L.z,L.x,L.z,L.r+4,3);','for(const L of LMX)cap(L.x,L.z,L.x,L.z,L.r+4,3);OC_zone(cap);')
R('window.__mho={', open('oc.js').read()+'\nwindow.__mho={')
save()
