# Builds hollowbough.html (one self-contained file) and x.js (all our scripts, for node --check).
import re,os,sys,json,base64
D=os.path.dirname(os.path.abspath(__file__))
SP=os.path.abspath(os.path.join(D,'..','..'))   # games-src
HB=os.path.abspath(os.path.join(D,'..'))
def rd(p):return open(p,encoding='utf-8').read()
def art_js():
    # painted card art: art/<key>.webp (key = card role) -> HB_ART data URIs; kit.js turns them into blob URLs
    man=json.load(open(os.path.join(HB,'art','manifest.json'),encoding='utf-8'))['items']
    out,total={},0
    for k,name in man.items():
        f=os.path.join(HB,'art',name+'.webp')
        if not os.path.exists(f):print('NOTE: art missing',name,file=sys.stderr);continue
        d=open(f,'rb').read();total+=len(d);out[k]='data:image/webp;base64,'+base64.b64encode(d).decode('ascii')
    print('art: %d images, %d KB'%(len(out),total//1024),file=sys.stderr)
    return '// painted card art (generated by build.py from ../art)\nvar HB_ART = '+json.dumps(out,separators=(',',':'))+';\n'
parts=sorted((f for f in os.listdir(os.path.join(D,'src')) if re.match(r'ui\d+\.js$',f)),key=lambda f:int(re.findall(r'\d+',f)[0]))
ui=''.join(rd(os.path.join(D,'src',f)) for f in parts)
open(os.path.join(D,'ui.js'),'w',encoding='utf-8').write(ui)
audio=os.path.join(SP,'audio','hollowbough','audio-data.js')
SRC={'shell.js':os.path.join(SP,'shell','shell.js'),'gx-kit.js':os.path.join(SP,'shell','gx-kit.js'),'gx-viewport.js':os.path.join(SP,'shell','gx-viewport.js'),'gx-help.js':os.path.join(SP,'shell','gx-help.js'),'gx-tutor.js':os.path.join(SP,'shell','gx-tutor.js'),'gx-campaign.js':os.path.join(SP,'shell','gx-campaign.js'),'campaign-data.js':'','refdata.js':os.path.join(D,'src','refdata.js'),'perfhud.js':os.path.join(SP,'perf','perfhud.js'),'gameaudio.js':os.path.join(SP,'audio','gameaudio.js'),
 'art-data.js':'','kit.js':os.path.join(HB,'kit','kit.js'),'data.js':os.path.join(D,'src','data.js'),'engine.js':os.path.join(D,'src','engine.js'),'ai.js':os.path.join(D,'src','ai.js'),'ui.js':os.path.join(D,'ui.js'),
 'trystero.min.js':os.path.join(SP,'net','trystero.min.js'),'netroom.js':os.path.join(SP,'net','netroom.js'),'netstrip.js':os.path.join(D,'src','netstrip.js'),'net.js':os.path.join(D,'net.js')}
if os.path.exists(audio):SRC['audio-data.js']=audio
else:print('NOTE: audio-data.js missing, silent build',file=sys.stderr)
ORDER=['shell.js','gx-kit.js','gx-viewport.js','gx-help.js','gx-tutor.js','gx-campaign.js','campaign-data.js','perfhud.js','trystero.min.js','netroom.js','art-data.js','kit.js','data.js','refdata.js','engine.js','ai.js','netstrip.js','gameaudio.js','audio-data.js','net.js','ui.js']
h=rd(os.path.join(D,'head.html')).replace('/*SHELL_CSS*/',rd(os.path.join(SP,'shell','shell.css'))+'\n'+rd(os.path.join(SP,'shell','gx-kit.css'))+'\n'+rd(os.path.join(SP,'shell','gx-campaign.css'))+'\n'+rd(os.path.join(SP,'shell','gx-help.css'))+'\n'+rd(os.path.join(SP,'shell','gx-tutor.css')))
body=rd(os.path.join(D,'body.html'))
if 'audio-data.js' in SRC:body=body.replace('<script src="ui.js"></script>','<script src="audio-data.js"></script>\n<script src="ui.js"></script>')
for f in ORDER:
    tag='<script src="%s"></script>'%f
    if f not in SRC:continue
    assert tag in body,f
    src=(('window.CAMPAIGN = '+json.dumps(json.load(open(os.path.join(HB,'campaign.json'),encoding='utf-8')),separators=(',',':'),ensure_ascii=False)+';') if f=='campaign-data.js' else art_js() if f=='art-data.js' else rd(SRC[f])).replace('</script','<\\/script')
    body=body.replace(tag,'<script>\n'+src+'\n</script>')
out=h+body
open(os.path.join(D,'hollowbough.html'),'w',encoding='utf-8').write(out)
js='\n'.join(re.findall(r'<script>(.*?)</script>',out,re.S))
open(os.path.join(D,'x.js'),'w',encoding='utf-8').write(js)
print('hollowbough.html',len(out.encode('utf-8')),'bytes')
