#!/usr/bin/env python3
# Generates src/data.js from ../cards.json (display names = new_name, text = new_text).
import json,os,re
d=json.load(open(os.path.join(os.path.dirname(__file__),'..','cards.json')))
FIX={'theatre':'theater','cemetary':'cemetery','any critter':'any'}
cards=[]
for c in d['cards']:
    cards.append(dict(key=c['role'],name=c['new_name'],text=c['new_text'],copies=c['copies'],type=c['type'],color=c['color'],
        kind=c['kind'],unique=c['unique'],cost=c['cost'],pts=c['base_points'],linked=FIX.get(c['linked'],c['linked'])))
forest=[dict(key=f['role'],name=f['new_name'],text=f['new_text']) for f in d['forest_locations']]
bn=['Berry Patch','Dewberry Nook','Amber Weep','Pebble Bank','Twig Heap','Gossip Glade','Resin Pool','Kindling Glen']
bt=['Gain 1 berry. Shared.','Gain 1 berry and draw 1 card.','Gain 1 resin and draw 1 card. Shared.','Gain 1 pebble.','Gain 3 twigs.',
    'Draw 2 cards and take 1 point token. Shared.','Gain 2 resin.','Gain 2 twigs and draw 1 card. Shared.']
basic=[]
for i,l in enumerate(d['locations']['basic']):
    basic.append(dict(key=l['role'],name=bn[i],text=bt[i],gain={k:v for k,v in l['gain'].items() if k in('twig','resin','pebble','berry')},
        draw=l['gain'].get('draw',0),pts=l['gain'].get('point_tokens',0),shared=l['shared']))
be=[dict(key=e['role'],name=e['new_name'],need=e['requires'],pts=e['points'],text='Needs %s in your city. Worth %d points.'%(', '.join('%d %s'%(v,{'production':'production (green)','destination':'destination (red)','governance':'governance (blue)','traveler':'traveler (tan)'}[k]) for k,v in e['requires'].items()),e['points'])) for e in d['basic_events']]
se=[]
for e in d['special_events']:
    se.append(dict(key=e['role'],name=e['new_name'],text=e['new_text'],req=e.get('requires_cards',[]),colors=e.get('requires_colors'),pts=e['base_points'],score=e['end_game_scoring']))
def slug(n): return re.sub(r'[^a-z0-9]+','_',n.lower()).strip('_')
MAP={}
def rekey(lst,prefix):
    for x in lst:
        new=prefix+'_'+slug(x['name']); MAP[x['key']]=new; x['key']=new
rekey(forest,'forest'); rekey(basic,'basic'); rekey(be,'bev'); rekey(se,'sev')
for c in cards:
    if c['key']=='barge_toad': c['text']=c['text'].replace('Allotment (Farm-role card)','Bramble Allotment')
json.dump(MAP,open(os.path.join(os.path.dirname(__file__),'keymap.json'),'w'),indent=1)
D=dict(game='Hollowbough',cards=cards,forest=forest,basic=basic,
  haven=dict(key='haven',name='Barter Burrow',text='Discard any number of cards from your hand; gain 1 resource of your choice for every 2 discarded. Shared.'),
  journey=[dict(points=j['points'],discard=j['discard'],shared=j['shared'],name='Long Road %d'%j['points']) for j in d['locations']['journey']],
  journeyName='The Long Road',basicEvents=be,specialEvents=se,components=d['components'],
  soloName='Old Grimbeard',soloLevels=['Grumpy','Gruff','Ghastly'])
js=json.dumps(D,separators=(',',':'),ensure_ascii=False)
open(os.path.join(os.path.dirname(__file__),'src','data.js'),'w').write(
"// Generated by game/gen-data.py from cards.json. Do not edit by hand.\n// Internal `key` fields are for code only; show `name`/`text` to players.\n(function(g){var HB=g.HB=g.HB||{};HB.DATA="+js+";if(typeof module==='object'&&module.exports)module.exports=HB.DATA;})(typeof globalThis!=='undefined'?globalThis:this);\n")
print(len(js))
