// lv/shots.js <url> <outdir> [fra|ath] : free-roam look shots at fixed street spots (852x393, normal gfx) + frame-time probe
// spots = street nodes nearest to fixed fractions of the node list (same spots every build). Env SPOTS=n (default 5), MS=1 frame time.
const enter=require('../bc/enter.js');const fs=require('fs');const URL=process.argv[2],OUT=process.argv[3],CITY=process.argv[4]||'fra';fs.mkdirSync(OUT,{recursive:true});
(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:process.env.GFX||'normal',seed});const {p,errs}=E;p.setDefaultTimeout(900000);
 if(process.env.LIFE)await p.evaluate(v=>__g9ev('TUNE.life='+v),process.env.LIFE);await E.roamApi();const dis=async()=>{for(let i=0;i<4;i++){const l=p.getByText('CONTINUE',{exact:false}).first();if(await l.count()&&await l.isVisible()){await E.tapEl(await l.elementHandle());await p.waitForTimeout(800)}else break}};await dis();console.log('city',await p.evaluate(()=>__g9ev('CID')));
 const n=+(process.env.SPOTS||5);
 const spots=await p.evaluate(n=>{const N=__mho.HUB.nodes,out=[];const ok=[];for(let i=0;i<N.length;i++){const a=N[i];if(a&&a.nb&&a.nb.length>=2&&!a.ab&&!a.g&&N[a.nb[0]])ok.push(i)}if(!ok.length)for(let i=0;i<N.length;i++){const a=N[i];if(a&&a.nb&&a.nb.length&&N[a.nb[0]])ok.push(i)}console.log('ok',ok.length,N.length,JSON.stringify(N.find(Boolean)).slice(0,200));for(let k=0;k<n;k++){const i=ok[Math.floor((k+.5)/n*ok.length)],a=N[i],b=N[a.nb[0]];out.push([a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z)])}return out},n);
 for(let k=0;k<spots.length;k++){const [x,z,h]=spots[k];await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+60);R.v=0;R.yr=0;R.vh=h;R.h=h;R.stkT=0},[x,z,h]);
  await p.waitForTimeout(+(process.env.WAIT||9000));await dis();await p.screenshot({path:`${OUT}/${CITY}_${k}.png`});const vc=await p.evaluate(()=>__g9ev(`(()=>{camera.updateMatrixWorld();const fr=new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse)),v=new THREE.Vector3(),c={peds:0,cars:0},inV=(x,y,z)=>fr.containsPoint(v.set(x,y+1,z))&&v.distanceTo(camera.position)<120;for(const p of HUB.peds||[])if(p._x!=null&&inV(p._x,p.y,p._z))c.peds++;for(const k of HUB.cars||[])if(k.dead<=0&&inV(k.x,k.y||0,k.z))c.cars++;if(window.__lv){const w=__lv.view();c.birds=w.birds;c.boats=w.boats}return JSON.stringify(c)})()`));console.log('shot',k,Math.round(x),Math.round(z),vc)}
 if(process.env.MS){// frame cost: stop the auto ticker cadence effect by timing 120 explicit ticks (render on), then render stubbed
  const t=await p.evaluate(()=>{const C=__g9ev('composer');const f=n=>{const t0=performance.now();__tick(n);return (performance.now()-t0)/n};const a=f(60);const r=C.render;C.render=()=>{};const b=f(240);C.render=r;return{withRender:+a.toFixed(2),cpuOnly:+b.toFixed(2)}});console.log('frame_ms',JSON.stringify(t))}
 if(await p.evaluate(()=>!!window.__lv))console.log('lv',JSON.stringify(await p.evaluate(()=>__lv.n())));console.log('errors',errs.length,errs.slice(0,5).join(' | '));await E.b.close()})();
