// lv/su.js <url> <out> [ath]: street-racer traffic check: kinds built, counts, a low side shot of the nearest street racer in traffic (frozen on its lane)
const enter=require('../bc/enter.js');const fs=require('fs');const URL=process.argv[2],OUT=process.argv[3],CITY=process.argv[4]||'fra';fs.mkdirSync(OUT,{recursive:true});
(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:process.env.GFX||'normal',seed});const {p,errs}=E;p.setDefaultTimeout(900000);await E.roamApi();
 const dis=async()=>{for(let i=0;i<4;i++){const l=p.getByText('CONTINUE',{exact:false}).first();if(await l.count()&&await l.isVisible()){await E.tapEl(await l.elementHandle());await p.waitForTimeout(800)}else break}};await dis();
 const ev=c=>p.evaluate(c=>{try{return __g9ev(c)}catch(e){return 'ERR '+e}},c);
 console.log('kinds',await ev(`JSON.stringify(HCAR.map((nm,k)=>[nm,HUB.cim[k].count,!!CR_cityGeo(nm)]))`));
 const r=await ev(`(()=>{let j=-1,bd=1e9;HUB.cars.forEach((c,i)=>{if(c.dead>0||c.tr||!HCAR[c.k].startsWith('su:'))return;const d=Math.hypot(c.x-RO.x,c.z-RO.z);if(d<bd){bd=d;j=i}});if(j<0)return 'none';const c=HUB.cars[j];c.v=0;c.cv=0;c.route=[];c.hitT=99;
   const A=HUB.nodes[c.a],B=HUB.nodes[c.b],h=Math.atan2(B.x-A.x,B.z-A.z);__mho.warp(c.x-Math.sin(h)*9,c.z-Math.cos(h)*9,h,performance.now());RO.x=c.x-Math.sin(h)*9;RO.z=c.z-Math.cos(h)*9;RO.y=groundAt(RO.x,RO.z,RO.y+60);RO.v=0;RO.h=RO.vh=h;window.__suc=[j,h];return HCAR[c.k]+' '+Math.round(bd)})()`);console.log('racer',r);
 if(r!=='none'){await p.waitForTimeout(6000);await ev(`(()=>{const[j,h]=__suc,c=HUB.cars[j],g=groundAt(c.x,c.z,c.y+3),sx=Math.cos(h),sz=-Math.sin(h);__gnb.cam([c.x+sx*6.5,g+1,c.z+sz*6.5,c.x,g+.6,c.z]);return 1})()`);await p.waitForTimeout(3000);await p.screenshot({path:`${OUT}/${CITY}_racer_side.png`});await ev('__gnb.cam(null)');await p.waitForTimeout(2500);await p.screenshot({path:`${OUT}/${CITY}_racer_chase.png`})}
 console.log('errors',errs.length,errs.slice(0,4).join(' | '));await E.b.close()})();
