// t16/race.js: quick race on the phone layout, real touch: GAS, GAS+BRAKE+▶ drift, BOOST. Shots + B2K numbers. usage: node t16/race.js <url> <out>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs'),path=require('path');const OUT=process.argv[3]||'qa16/race';fs.mkdirSync(OUT,{recursive:true});
const INIT=`(()=>{const q=[];let t=0;window.__auto=true;window.requestAnimationFrame=cb=>{q.push(cb);return q.length};window.cancelAnimationFrame=()=>{};
 window.__tick=n=>{for(let i=0;i<n;i++){t+=1000/60;const c=q.splice(0);for(const f of c){try{f(t)}catch(e){setTimeout(()=>{throw e})}}if(window.__mon)try{window.__mon()}catch(e){}}return t};
 setInterval(()=>{if(window.__dbg&&!window.__fastR&&!window.__shooting){window.__fastR=__dbg.composer.render;__dbg.composer.render=()=>{}}if(window.__auto)window.__tick(1)},16)})();`;
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
 const ctx=await b.newContext({viewport:{width:852,height:393},deviceScaleFactor:2,isMobile:true,hasTouch:true});const p=await ctx.newPage();await p.addInitScript(INIT);p.setDefaultTimeout(600000);const errs=[];p.on('pageerror',e=>errs.push(String(e).slice(0,200)));p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text().slice(0,200))});
 const cdp=await ctx.newCDPSession(p);const tick=n=>p.evaluate(n=>__tick(n),n);const F={};const pts=()=>Object.values(F).map(f=>({x:f.x,y:f.y,id:f.id,radiusX:6,radiusY:6,force:1}));
 const center=s=>p.evaluate(s=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect();if(r.width<4)return null;return[r.left+r.width/2,r.top+r.height/2]},s);
 const down=async(n,xy)=>{if(!xy)return;let id=0;while(Object.values(F).some(o=>o.id===id))id++;F[n]={x:xy[0],y:xy[1],id};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts()})};
 const up=async n=>{if(!F[n])return;delete F[n];const P=pts();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});if(P.length)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:P})};
 const tapSel=async s=>{const xy=await center(s);if(!xy)return false;await down('t',xy);await p.waitForTimeout(80);await up('t');return true};
 await p.goto(process.argv[2]);await p.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:300000});
 await tapSel('[data-a="quick"]');await p.waitForTimeout(1500);for(const s of['#startBtn','#tGo']){if(await tapSel(s))break}
 await p.waitForFunction(()=>__mho.state==='race',null,{timeout:300000});await p.evaluate(()=>{window.__auto=false});const g=await center('#tG'),bk=await center('#tB'),r=await center('#tR'),n=await center('#tN');
 const st=()=>p.evaluate(()=>({v:+((__mho.pl.v||0)*3.6).toFixed(0),hb:__mho.pl.hbDir||0,b:__b2k.st()}));const res={};
 res.gasVisible=!!g;await down("st",r);await tick(3);await up("st");if(g&&!process.env.NOGAS)await down("gas",g);for(let i=0;i<40;i++){await tick(60);if((await st()).v>70)break}res.go=await st();await down('st',r);await tick(9);await down('brk',bk);await tick(54);res.drift=await st();
 await p.evaluate(()=>{window.__shooting=1;if(window.__fastR){__dbg.composer.render=window.__fastR;window.__fastR=null}__tick(1)});await p.screenshot({path:path.join(OUT,'race_drift.jpg'),type:'jpeg',quality:70});await tick(54);await up('brk');await up('st');await tick(24);res.after=await st();res.log=await p.evaluate(()=>__b2k.log.drift.slice());
 await down('boost',n);await tick(42);await p.evaluate(()=>{window.__shooting=1;if(window.__fastR){__dbg.composer.render=window.__fastR;window.__fastR=null}__tick(1)});await p.screenshot({path:path.join(OUT,'race_boost.jpg'),type:'jpeg',quality:70});res.boost=await st();await tick(150);res.boost2=await st();await p.evaluate(()=>{window.__shooting=1;if(window.__fastR){__dbg.composer.render=window.__fastR;window.__fastR=null}__tick(1)});await p.screenshot({path:path.join(OUT,"race_bash.jpg"),type:"jpeg",quality:70});await up('boost');
 res.proj=await p.evaluate(()=>{const T=__dbg.THREE,c=__dbg.camera,m=__mho.pl.mesh;const pr=v=>{const q=v.clone().project(c);return[Math.round((q.x+1)/2*innerWidth),Math.round((1-q.y)/2*innerHeight),+q.z.toFixed(3)]};const w=new T.Vector3();m.getWorldPosition(w);const g=m.parent.getObjectByName('b2kTurb');const o={car:pr(w),gvis:g&&g.visible,inScene:!!g,parts:[]};if(g)for(const k of g.children){const q=new T.Vector3().setFromMatrixPosition(k.matrixWorld);o.parts.push(pr(q))}o.scenes=[];let sc=m;while(sc.parent)sc=sc.parent;o.root=sc.type+':'+sc.uuid.slice(0,6);o.dbgScene=__dbg.scene?__dbg.scene.uuid.slice(0,6):null;return o});res.boxDbg=await p.evaluate(()=>{const T=__dbg.THREE,m=__mho.pl.mesh;m.updateMatrixWorld(true);const inv=new T.Matrix4().copy(m.matrixWorld).invert(),M=new T.Matrix4();const by={};m.traverseVisible(o=>{if(!o.isMesh||!o.geometry||o===m)return;if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();const k=o.material.type+(o.material.transparent?'T':'')+(o.isInstancedMesh?'I':'');const b=o.geometry.boundingBox.clone().applyMatrix4(M.multiplyMatrices(inv,o.matrixWorld));by[k]=by[k]?by[k].union(b):b});const out={};for(const k in by)out[k]=[by[k].min.toArray().map(v=>+v.toFixed(2)),by[k].max.toArray().map(v=>+v.toFixed(2))];return out});res.kidsDbg=await p.evaluate(()=>{const m=__mho.pl.mesh;const out=[];m.traverse(o=>{if(out.length<40)out.push([o.type,o.name,o.visible,o.layers.mask,o.parent===m?1:0,o.isMesh?(o.material.type+":"+(o.material.visible!==false)):""])});return{out,cam:__dbg.camera.layers.mask,par:m.parent&&m.parent.type}});res.turbDbg=await p.evaluate(()=>{const T=__dbg.THREE,m=__mho.pl.mesh;const g=m.getObjectByName("b2kTurb");const w=new T.Vector3();m.getWorldPosition(w);const o={car:w.toArray().map(v=>+v.toFixed(1)),scale:m.scale.toArray(),vis:m.visible,box:__b2k.box()};if(g){o.gvis=g.visible;o.kids=g.children.map(u=>{const q=new T.Vector3();u.getWorldPosition(q);return[q.toArray().map(v=>+v.toFixed(1)),+u.scale.x.toFixed(2)]})}else o.g=null;return o});res.state=await p.evaluate(()=>__mho.state);res.errs=errs;console.log(JSON.stringify(res));await b.close()})();
