"""Write <slug>/audio-data.js, MAP.md, credits.html, ASSETS.md for hollowbough/thornbound from build_real.py output,
copy OGA licence snapshots, and append rows to the shared audio/ASSETS.md.  Usage: python3 bundle_real.py <rawdir> <workdir>"""
import os, sys, json, base64, shutil
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.abspath(sys.argv[1]); W = os.path.abspath(sys.argv[2]); rep = json.load(open(os.path.join(W, 'report.json')))
DATE = '2026-10-02'; CC0 = 'CC0 1.0'; CC0U = 'https://creativecommons.org/publicdomain/zero/1.0/'
b64 = lambda p: base64.b64encode(open(p, 'rb').read()).decode()
KEN = {'casino-audio': 'Casino Audio', 'interface-sounds': 'Interface Sounds', 'impact-sounds': 'Impact Sounds', 'rpg-audio': 'RPG Audio', 'ui-audio': 'UI Audio', 'music-jingles': 'Music Jingles'}
MUS = {  # file -> title, author, page slug, download url
 'celtic.mp3': ('Celtic Loop', 'stereoscopic', 'celtic-loop', 'https://opengameart.org/sites/default/files/celtic_0.mp3'),
 'village_square.ogg': ('Medieval 5', 'Tozan', 'medieval-5', 'https://opengameart.org/sites/default/files/medievalvillagesquare_0.ogg'),
 'northumberland.mp3': ('Northumberland', 'Spring Spring', 'northumberland', 'https://opengameart.org/sites/default/files/northumberland_0.mp3'),
 'long_winter.mp3': ('Long Winter', 'Indieteur', 'long-winter', 'https://opengameart.org/sites/default/files/Long%20Winter_0.mp3'),
 'dark_forest.mp3': ('Dark Forest Theme', 'cynicmusic', 'dark-forest-theme', 'https://opengameart.org/sites/default/files/GameMusic_ForestTheme_24_0.mp3'),
 'dungeon002.ogg': ('Dungeon Ambience', 'yd', 'dungeon-ambience', 'https://opengameart.org/sites/default/files/dungeon002_0.ogg'),
}
SNAP = os.path.join(ROOT, 'licence-snapshots'); os.makedirs(SNAP, exist_ok=True)
for f, (t, a, slug, dl) in MUS.items():
    shutil.copy(os.path.join(RAW, 'pg', slug + '.html'), os.path.join(SNAP, slug + '.html'))
for k in KEN:  # Kenney pages + License.txt (already present for most; refresh if missing)
    for src, dst in ((os.path.join(RAW, k + '.html'), k + '.html'), (os.path.join(RAW, k, 'License.txt'), k + '-License.txt')):
        if os.path.exists(src) and not os.path.exists(os.path.join(SNAP, dst)): shutil.copy(src, os.path.join(SNAP, dst))

INFO = {
 'hollowbough': dict(title='Hollowbough', key='hb', desc={
   'click': 'UI click', 'place': 'card placed on the table', 'flip': 'card flip / turn over', 'twig': 'twig resource (two dry wood knocks)',
   'resin': 'resin resource (soft drip)', 'pebble': 'pebble resource (two stone clicks)', 'berry': 'berry resource (soft pluck)', 'worker': 'worker placed (wooden knock)',
   'season': 'season change chime (plucked-string jingle)', 'event': 'event achieved (plucked-string jingle)', 'tally': 'score tally tick: play repeatedly with rising `rate`',
   'score': 'score total confirm', 'turn': 'your turn', 'fanfare': 'end fanfare (plucked strings + sax jingle layered)', 'lose': 'low-score / lose sting', 'error': 'illegal move'},
   music={'spring': 'spring bed: Celtic folk loop', 'summer': 'summer bed: medieval village-square tune', 'autumn': 'autumn bed: Northumberland folk melody', 'winter': 'winter bed: hushed ambient'},
   wire="""```js
const SEASON_BED={spring:'spring',summer:'summer',autumn:'autumn',winter:'winter'};
GA.music(SEASON_BED[G.season]);   // cross-fades on season change; GA.music(null) to stop
```"""),
 'thornbound': dict(title='The Thornbound Throne', key='tbt', desc={
   'click': 'UI click', 'place': 'card placed face-down (shove + soft thud)', 'flip': 'card reveal / flip', 'clash': 'clash hit (heavy metal impact + punch)',
   'win': 'win sting (steel jingle)', 'influence': 'influence gained (coins)', 'herald': 'herald step (footstep + latch click)', 'bid': 'bid (coin handful)',
   'bell': 'round bell (heavy bell)', 'fanfare': 'end fanfare (steel + hit jingle layered)', 'lose': 'lose sting (steel jingle)', 'error': 'illegal move'},
   music={'main': 'dark brooding acoustic guitar and strings (main bed)', 'tense': 'dark dungeon ambient (use for clashes / late rounds)'},
   wire="""```js
GA.music('main');    // after the first user gesture
GA.music('tense');   // optional: cross-fade during the clash reveal or the last round
```"""),
}
def srcrows(spec):
    out = [spec['src']] + [m[0] for m in spec.get('mix', [])]
    return out
shared = []
for slug, I in INFO.items():
    d = os.path.join(ROOT, slug); os.makedirs(d, exist_ok=True); R = rep[slug]
    parts = ['/* audio-data.js for %s - generated by audio/tools/bundle_real.py. Licences: see audio/ASSETS.md */' % I['title'], 'const GA_DATA={sfx:{']
    sb = mb = 0
    for n in I['desc']:
        p = os.path.join(W, slug, 'sfx', n + '.mp3'); sb += os.path.getsize(p); parts.append('"%s":"%s",' % (n, b64(p)))
    parts.append('},music:{')
    for n in I['music']:
        p = os.path.join(W, slug, 'music', n + '.mp3'); mb += os.path.getsize(p); parts.append('"%s":"%s",' % (n, b64(p)))
    parts.append('}};'); js = '\n'.join(parts) + '\n'; open(os.path.join(d, 'audio-data.js'), 'w').write(js)
    # source -> outputs
    uses = {}; kinds = {}
    for n, v in R['sfx'].items():
        for sp in srcrows(v['spec']): uses.setdefault(sp, []).append('%s/%s' % (slug, n))
    # ASSETS.md (per game)
    L = ['# %s: audio assets\n' % I['title'], 'All sounds are real CC0 recordings (Kenney, OpenGameArt), processed with `tools/build_real.py` and `tools/bundle_real.py`. Checked %s; licence pages are snapshotted in `../licence-snapshots/`. Nothing is synthesised: no fallback synth sounds are shipped (the games keep their own built-in synth for any missing name).\n' % DATE,
         '## Sound effects (mono MP3 %s kbps, trimmed, loudness-normalised)\n' % ('48' if slug == 'hollowbough' else '64'),
         '| sample | source file(s) | pack | licence | length | size | use |', '|---|---|---|---|---|---|---|']
    for n, v in R['sfx'].items():
        files = srcrows(v['spec']); packs = sorted({KEN[f.split('/')[0]] if f.split('/')[0] in KEN else '?' for f in files})
        L.append('| `%s` | %s | Kenney %s | CC0 1.0 | %.2f s | %d B | %s |' % (n, ', '.join('`%s`' % os.path.basename(f) for f in files), ', '.join(packs), v['dur'], v['bytes'], I['desc'][n]))
    L += ['', '## Music (mono MP3, loudness-normalised, seamless loop)\n', '| name | track | author | source page | download | licence | loop cut | similarity | length | size |', '|---|---|---|---|---|---|---|---|---|---|']
    for n, m in R['music'].items():
        t, a, ps, dl = MUS[m['src']]
        L.append('| `%s` | "%s" | %s | https://opengameart.org/content/%s | %s | CC0 1.0 | %.2f s-%.2f s, 1.5 s equal-power cross-fade | %.3f | %.1f s | %d B (%d kbps) |' % (n, t, a, ps, dl, m['a'], m['b'], m['sim'], m['dur'], m['bytes'], m['kbps']))
        shared.append((m['src'], t, a, ps, dl, m, '%s/music.%s' % (slug, n)))
    L.append('\nTotals: SFX %d KB + music %d KB MP3; `audio-data.js` %d KB (base64). Licence: %s %s\n' % (sb // 1024, mb // 1024, len(js) // 1024, CC0, CC0U))
    L.append('Rebuild: `python3 tools/build_real.py <raw> <work> && python3 tools/bundle_real.py <raw> <work>` (raw = Kenney zips unpacked + `mus/` with the OGA tracks).\n')
    open(os.path.join(d, 'ASSETS.md'), 'w').write('\n'.join(L))
    M = ['# %s: sound map\n' % I['title'], "Load order: `gameaudio.js`, this `audio-data.js`, then the game. `GA.init({sfx:GA_DATA.sfx, music:GA_DATA.music, key:'%s'})`; guard each sfx with `if (window.GA && GA.has(name)) { GA.play(name); return; }` and keep the synth as fallback.\n" % I['key'],
         '| sample | length | use |', '|---|---|---|']
    for n in I['desc']: M.append('| `%s` | %.2f s | %s |' % (n, R['sfx'][n]['dur'], I['desc'][n]))
    M += ['', '## Music', '', '| name | length | track |', '|---|---|---|']
    for n in I['music']: M.append('| `%s` | %.1f s | %s: "%s" by %s |' % (n, R['music'][n]['dur'], I['music'][n], MUS[R['music'][n]['src']][0], MUS[R['music'][n]['src']][1]))
    M += ['', I['wire'], '', 'Ducking: pass `{duck:true}` for `win`, `fanfare`, `clash`, `bell`, `season`. Not yet auditioned by ear: tune per-sound `vol` in the game\'s `SND_MAP`.']
    if slug == 'hollowbough': M += ['', 'There is no `win` sample: map `win` to `fanfare`. `tally` is a tick: replay it with rising `rate` while counting points.']
    open(os.path.join(d, 'MAP.md'), 'w').write('\n'.join(M) + '\n')
    mus = ''.join('<li>Music: &ldquo;%s&rdquo; by %s (<a href="https://opengameart.org/content/%s">OpenGameArt</a>, CC0)</li>\n' % (MUS[m['src']][0], MUS[m['src']][1], MUS[m['src']][2]) for m in R['music'].values())
    packs = sorted({KEN[f.split('/')[0]] for v in R['sfx'].values() for f in srcrows(v['spec'])})
    open(os.path.join(d, 'credits.html'), 'w').write('<!-- Credits snippet for %s. Paste into the in-game Credits / Rules popup. Generated %s. -->\n<section class="credits-audio">\n<h3>Audio</h3>\n<p>With thanks to these public-domain (CC0) creators:</p>\n<ul>\n%s<li>Sound effects: %s by <a href="https://kenney.nl">Kenney</a> (CC0)</li>\n</ul>\n<p><small>All sounds were trimmed, loudness-normalised and converted to MP3 for this game. Names, card text and art are original.</small></p>\n</section>\n' % (I['title'], DATE, mus, ', '.join(packs)))
    print(slug, 'sfx', sb, 'music', mb, 'js', len(js))
    for sp, outs in uses.items():
        kinds[sp] = outs
    I['uses'] = uses
# shared ASSETS.md: append rows after the last table row of the main table
p = os.path.join(ROOT, 'ASSETS.md'); t = open(p).read()
if 'hollowbough/' in t: print('shared ASSETS.md already has rows; skipping'); sys.exit()
rows = []
allu = {}
for slug, I in INFO.items():
    for sp, outs in I['uses'].items(): allu.setdefault(sp, []).extend(outs)
lines0 = t.split('\n')
for sp, outs in sorted(allu.items()):
    pk = sp.split('/')[0]
    key = '| `%s` |' % sp.replace('/Audio/', '/')
    hit = [i for i, l in enumerate(lines0) if l.startswith(key)]
    if hit:  # already logged for another game: extend its "used as" cell
        lines0[hit[0]] = lines0[hit[0]].rstrip(' |') + ', ' + ', '.join(outs) + ' |'; continue
    rows.append('| `%s` | [Kenney %s](https://kenney.nl/assets/%s) | Kenney (Kenney Vleugels) | CC0 1.0 | %s | %s | trimmed silence, layered where noted, normalised (~-16 LUFS target, -1 dBFS peak limit), mono MP3 | %s |' % (sp.replace('/Audio/', '/'), KEN[pk], pk, CC0U, DATE, ', '.join(outs)))
seen = {}
for sp, t_, a, ps, dl, m, out in shared: seen.setdefault(sp, [t_, a, ps, dl, m, []])[5].append(out)
for sp, (t_, a, ps, dl, m, outs) in seen.items():
    rows.append('| `%s` | [%s](https://opengameart.org/content/%s) | %s | CC0 1.0 | %s | %s | cut %.2fs-%.2fs, 1.5 s equal-power cross-fade (similarity %.3f); normalised; mono %d kbps MP3 | %s |' % (os.path.basename(dl).replace('%20', ' '), t_, ps, a, CC0U, DATE, m['a'], m['b'], m['sim'], m['kbps'], ', '.join(outs)))
lines = lines0; last = max(i for i, l in enumerate(lines) if l.startswith('| `'))
lines[last + 1:last + 1] = rows
t = '\n'.join(lines)
t = t.replace('CC0 (optional thanks, shown in every game): Kenney;', 'CC0 (optional thanks, shown in every game): Kenney; Spring Spring, stereoscopic, Tozan, Indieteur, cynicmusic, yd (OpenGameArt music, Hollowbough / Thornbound);')
t = t.replace('- Medieval: Harvest Season:', ''.join('- %s: %s\n' % (v[0], v[3]) for v in seen.values()) + '- Medieval: Harvest Season:', 1)
open(p, 'w').write(t); print('appended', len(rows), 'rows')
