// t4/fx19drop.js (from g11drop.js, EARLY mode only, + follow-step state): default car (no template, fresh profile), story → HOT DROP P1, hold GAS (real touch) until the objective line reads
// "Deliver → ≤6 m", 852x393 shot. With the test-only __g9ev hook (local_dbg) it also names what sits between the camera and the car.
// usage: node t4/g11drop.js <url> <png>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const URL=process.argv[2],PNG=process.argv[3];
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});
 const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto(URL);await p.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:240000});const cdp=await ctx.newCDPSession(p);
 const tapXY=async(x,y)=>{const tp=[{x,y,id:1,radiusX:4,radiusY:4,force:1}];await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})]);await p.waitForTimeout(700)};
 const tapEl=async e=>{const bb=await e.boundingBox();if(bb)await tapXY(bb.x+bb.width/2,bb.y+bb.height/2)};
 await tapEl(await p.$('#hcStory'));for(let i=0;i<240;i++){await p.waitForTimeout(3000);if(await p.evaluate(()=>__mho.state+'|'+!!(__mho.LD&&__mho.LD.on))==='roam|false')break;for(const q of['#slotList .go','#m1Next']){const e=await p.$(q);if(e&&await e.isVisible())await tapEl(e)}}
 for(let i=0;i<14;i++){let hit=0;for(const l of[p.getByText('SKIP',{exact:false}),p.getByText('TAP TO CONTINUE'),p.locator('#m1Next')]){const e=l.first();if(await e.count()&&await e.isVisible()){await tapEl(await e.elementHandle());hit=1;break}}if(!hit&&i>3)break;await p.waitForTimeout(1500)}
 const obj=()=>p.evaluate(()=>{const t=[...document.querySelectorAll('body *')].filter(e=>e.offsetParent&&/Deliver/.test(e.textContent)&&e.children.length<4).map(e=>e.textContent.trim()).sort((a,b)=>a.length-b.length)[0]||'';return t});
 const g=await (await p.$('#tG')).boundingBox();
 if(process.env.EARLY){// like 08: GAS + BOOST right after the story start, while Hilde's tow truck still stands just ahead; frames every ~0.7 s
  const n=await (await p.$('#tN')).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g.x+g.width/2,y:g.y+g.height/2,id:2}]});await p.waitForTimeout(+(process.env.EARLY));
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g.x+g.width/2,y:g.y+g.height/2,id:2},{x:n.x+n.width/2,y:n.y+n.height/2,id:4}]});
  for(let k=0;k<14;k++){await p.waitForTimeout(700);const f=PNG.replace('.png',`_e${String(k).padStart(2,'0')}.png`);await p.screenshot({path:f});
   console.log('early',k,await obj(),JSON.stringify(await p.evaluate(()=>window.__g9ev?__g9ev('(()=>{const H=M1.hilde,ch=RO.ch,V=ch&&ch.v2,S=V&&V.L.st[V.si];return H?{camTruck:+H.position.distanceTo(camera.position).toFixed(1),carTruck:+Math.hypot(H.position.x-RO.x,H.position.z-RO.z).toFixed(1),kmh:Math.round(Math.abs(RO.v)*3.6),si:V&&V.si,t:S&&S.t,s:S&&S.s!=null?+S.s.toFixed(1):null,L:S&&S.R?+S.R.L.toFixed(0):null,cs:!!M1.cs,hs:+(H.userData.crHalf?H.userData.crHalf.L*2:0).toFixed(2)}:null})()'):Math.round(Math.abs(__mho.RO.v)*3.6))))}
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});console.log('ERR',JSON.stringify(errs.filter(e=>!/GPU stall|GL Driver/.test(e)).slice(0,5)));await b.close();return}await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g.x+g.width/2,y:g.y+g.height/2,id:2}]});
 let last='';for(let i=0;i<120;i++){await p.waitForTimeout(1500);last=await obj();const m=/Deliver\D*(\d+)\s*m/.exec(last);if(i%5==0)console.log(i,last);if(m&&+m[1]<=6)break}
 if(process.env.ENUM){console.log('ENUM',await p.evaluate(()=>__g9ev(`(()=>{const out=[],c=new THREE.Vector3(),b=new THREE.Box3(),R=RO;scene.updateMatrixWorld(true);scene.traverse(o=>{if(!o.isMesh||!o.visible)return;let v=1;for(let q=o;q;q=q.parent)if(!q.visible)v=0;if(!v)return;if(o.isInstancedMesh)return;
   b.setFromObject(o);if(b.isEmpty())return;b.getCenter(c);const d=Math.hypot(c.x-R.x,c.z-R.z);if(d>14)return;let isCar=0;for(let q=o;q;q=q.parent)if(q===R.mesh)isCar=1;if(isCar)return;const m=Array.isArray(o.material)?o.material[0]:o.material,sz=b.getSize(new THREE.Vector3());
   const path=[];for(let q=o;q&&path.length<4;q=q.parent)path.push(q.name||q.type);out.push({d:+d.toFixed(1),path:path.join('<'),col:m&&m.color&&'#'+m.color.getHexString(),op:m&&+(+m.opacity).toFixed(2),tr:m&&m.transparent,size:sz.toArray().map(v=>+v.toFixed(1)),geo:o.geometry.type})});
   const ch=RO.ch;return JSON.stringify({car:[+R.x.toFixed(1),+R.z.toFixed(1)],ch:ch&&{kind:ch.kind,tx:ch.tx,tz:ch.tz,step:ch.m&&ch.m.i},near:out.sort((a,b)=>a.d-b.d).slice(0,25)})})()`)))}
 // same as 08: GAS still held, add a BOOST touch for 1.5 s, then shoot
 const n=await (await p.$('#tN')).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g.x+g.width/2,y:g.y+g.height/2,id:2},{x:n.x+n.width/2,y:n.y+n.height/2,id:4}]});await p.waitForTimeout(1500);
 await p.screenshot({path:PNG});const id0=await p.evaluate(()=>window.__g9ev?__g9ev('(()=>{const H=M1.hilde;return H?{camTruck:+H.position.distanceTo(camera.position).toFixed(1),carTruck:+Math.hypot(H.position.x-RO.x,H.position.z-RO.z).toFixed(1)}:null})()'):'live');console.log('boost frame',JSON.stringify(id0),await obj());
 // burst: the tow truck (story NPC) drives on; frames every ~1.2 s, logging its distance to the camera, keep the frame where it is closest
 const hd=()=>p.evaluate(()=>{try{return __mho.RO&&window.__g9ev?__g9ev('(()=>{const H=M1.hilde;return H?+H.position.distanceTo(camera.position).toFixed(1):-1})()'):-1}catch(e){return -1}});
 for(let k=0;k<+(process.env.BURST||0);k++){await p.waitForTimeout(1200);const f=PNG.replace('.png',`_b${String(k).padStart(2,'0')}.png`);await p.screenshot({path:f});console.log('burst',k,'objective',await obj(),'truck-cam m',await hd())}
 console.log('shot',PNG,'objective',last);
 const id=await p.evaluate(()=>{if(!window.__g9ev)return 'no hook (live build)';return __g9ev(`(()=>{const rc=new THREE.Raycaster(),out=[];for(const [x,y] of [[0,0.1],[0,-0.2],[-0.3,0],[0.3,0]]){rc.setFromCamera(new THREE.Vector2(x,y),camera);const h=rc.intersectObjects(scene.children,true).slice(0,3);
   out.push(h.map(i=>{let o=i.object,path=[];for(let q=o;q&&path.length<5;q=q.parent)path.push(q.name||q.type);const m=Array.isArray(o.material)?o.material[0]:o.material;return{d:+i.distance.toFixed(1),path:path.join('<'),col:m&&m.color&&'#'+m.color.getHexString(),op:m&&m.opacity,tr:m&&m.transparent,geo:o.geometry&&o.geometry.type,hilde:typeof M1!=='undefined'&&!!M1.hilde&&(()=>{for(let q=o;q;q=q.parent)if(q===M1.hilde)return true;return false})()}}))}
   const H=typeof M1!=='undefined'&&M1.hilde;return{out,hilde:H?{x:+H.position.x.toFixed(1),z:+H.position.z.toFixed(1),d:+Math.hypot(H.position.x-RO.x,H.position.z-RO.z).toFixed(1),vis:H.visible,inScene:!!H.parent}:null,cam:camera.position.toArray().map(v=>+v.toFixed(1)),car:[+RO.x.toFixed(1),+RO.z.toFixed(1)]}})()`)});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});console.log('ID',JSON.stringify(id));console.log('ERR',JSON.stringify(errs.filter(e=>!/GPU stall|GL Driver/.test(e)).slice(0,5)));await b.close()})();
