// t4/g8step.js: 852x393 touch. NEW BUILD → chassis (shower shot) → builder overview → tap a 2x2 on the chassis (held shot) → STEP UP x2 (shot) → STEP DOWN →
// PLACE (y check) → UNDO / REDO by toolbar taps (counts) → DONE (shower shot). usage: node t4/g8step.js <url> <outdir>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const O=process.argv[3];fs.mkdirSync(O,{recursive:true});const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto(process.argv[2]);await p.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:240000});const cdp=await ctx.newCDPSession(p);
 const tapXY=async(x,y)=>{const tp=[{x,y,id:1,radiusX:4,radiusY:4,force:1}];await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})]);await p.waitForTimeout(700)};
 const tap=async s=>{const e=await p.$(s);const bb=e&&await e.boundingBox();if(!bb)return console.log('NO',s);await tapXY(bb.x+bb.width/2,bb.y+bb.height/2)};const shot=async n=>{await p.screenshot({path:`${O}/${n}.png`});console.log('shot',n)};
 const L=()=>p.evaluate(()=>__gb.list().length);
 for(const s of['#gbMenuBtn','#gbx .gbTabs button[data-t="veh"]','.gnbGo']){if(s==='.gnbGo')await p.evaluate(()=>__g8.T.dur=12);await p.tap(s);await p.waitForTimeout(s==='.gnbGo'?400:1500);if(s==='.gnbGo'){await shot('01_shower_enter');console.log('showering',await p.evaluate(()=>__g8.showing()+' n='+__g8.shower()))}}await p.waitForSelector('[data-ch="sc8"]',{state:'visible',timeout:30000});
 await p.waitForFunction(()=>!__g8.showing(),null,{timeout:60000});await p.tap('[data-ch="sc8"]');
 await p.waitForTimeout(1500);await p.waitForFunction(()=>!__g8.showing(),null,{timeout:60000});await p.evaluate(()=>__g8.T.dur=1);await p.waitForTimeout(2000);await shot('02_overview');
 // a free chassis cell near the side, so the part can also step down beside the chassis
 const cell=await p.evaluate(()=>{const C=__gb.cells();let best=null;for(const[i,j]of C.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))){if(i<1||i>3)continue;const s=__gb.scr(i,j);if(s&&s.y<230&&s.y>70&&s.x>200&&s.x<640&&JSON.parse(__gnb.dbg(s.x,s.y)).c){best=[i,j,s];break}}return best});console.log('cell',JSON.stringify(cell));
 await tap('#gbBkPc [data-p="b22"]');const n0=await L();for(let k=0;k<3&&!await p.evaluate(()=>!!__g8.held());k++)await tapXY(cell[2].x,cell[2].y);console.log('held',JSON.stringify(await p.evaluate(()=>__g8.held())));await p.waitForTimeout(1200);await shot('03_held');
 const y0=(await p.evaluate(()=>__g8.held())).y;await tap('#gsBar [data-g8="1"]');await tap('#gsBar [data-g8="1"]');const y2=(await p.evaluate(()=>__g8.held())).y;await p.waitForTimeout(1200);await shot('04_step_up');
 await tap('#gsBar [data-g8="-1"]');const y1=(await p.evaluate(()=>__g8.held())).y;console.log('step y',y0,'→up2',y2,'→down',y1);
 await tap('#gsBar [data-g="place"]');await p.waitForTimeout(800);const n1=await L();const last=await p.evaluate(()=>{const l=__gb.list();return l.slice(-2).map(b=>b.t+'@'+b.x+','+b.z+',y'+b.y)});console.log('placed',n1-n0,JSON.stringify(last));await shot('05_placed');
 await tap('#gbBkT [data-a="undo"]');const n2=await L();await tap('#gbBkT [data-a="redo"]');const n3=await L();await tap('#gbBkT [data-a="undo"]');const n4=await L();
 console.log('undo/redo counts',n1,'undo→',n2,'redo→',n3,'undo→',n4,'redoDisabled',await p.$eval('#gbBkT [data-a="redo"]',e=>e.disabled));await tap('#gbBkT [data-a="redo"]');
 const rr=await p.evaluate(()=>{const r=document.querySelector('#gbBkT [data-a="redo"]').getBoundingClientRect(),u=document.querySelector('#gbBkT [data-a="undo"]').getBoundingClientRect(),d=document.querySelector('#gbBkT [data-a="done"]').getBoundingClientRect();return{undo:[u.x|0,u.y|0],redo:[r.x|0,r.y|0,r.width|0],doneRight:d.right|0,doneTop:d.top|0}});console.log('toolbar',JSON.stringify(rr));
 await p.evaluate(()=>__g8.T.dur=12);await tap('#gbBkT [data-a="done"]');await p.waitForTimeout(600);await shot('06_shower_exit');console.log('showering',await p.evaluate(()=>__g8.showing()+' n='+__g8.shower()));await p.waitForTimeout(2500);await shot('07_after');
 console.log('ERR',errs.slice(0,8));await b.close()})();
