// t4/g8trk.js: title → RACE (CHOOSE TRACK) at 852x393 touch: shot (top + scrolled to bottom), overlaps of #startRow with the WEATHER/CLASS rows, texts < 12 px. usage: node t4/g8trk.js <url> <outprefix>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto(process.argv[2]);await p.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:240000});
 await p.tap('#home .hc[data-a="quick"]');await p.waitForTimeout(1500);const O=process.argv[3];await p.screenshot({path:O+'_top.png'});
 const chk=()=>p.evaluate(()=>{const sr=document.querySelector('#startRow').getBoundingClientRect(),out=[],small=[];
  for(const s of document.querySelectorAll('#menu .mpanel .seg, #menu .mpanel #tracks, #menu .mpanel .goal')){const r=s.getBoundingClientRect();if(!r.width||getComputedStyle(s).display==='none')continue;if(r.bottom>sr.top+1&&r.top<sr.bottom-1&&r.right>sr.left&&r.left<sr.right)out.push((s.id||s.className)+':'+(s.querySelector('span')||{}).textContent+' '+Math.round(r.top)+'-'+Math.round(r.bottom))}
  for(const e of document.querySelectorAll('#menu .mpanel *')){const r=e.getBoundingClientRect();if(!r.width||r.bottom<0||r.top>innerHeight)continue;const own=[...e.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim()).map(n=>n.textContent.trim()).join(' ');if(!own)continue;let h=0;for(let q=e;q;q=q.parentElement)if(getComputedStyle(q).display==='none'||getComputedStyle(q).visibility==='hidden')h=1;if(h)continue;const fs=parseFloat(getComputedStyle(e).fontSize);if(fs<12)small.push(fs+'px '+own.slice(0,18))}
  return {startRow:[Math.round(sr.left),Math.round(sr.top),Math.round(sr.right),Math.round(sr.bottom)],overlap:out,small}});
 console.log('TOP',JSON.stringify(await chk()));
 await p.evaluate(()=>{const m=document.querySelector('#menu .mpanel');m.scrollTop=m.scrollHeight});await p.waitForTimeout(800);await p.screenshot({path:O+'_bottom.png'});console.log('BOTTOM',JSON.stringify(await chk()));console.log('ERR',errs.slice(0,5));await b.close()})();
