// t4/nbside.js: low side view of "My Build" behind a traffic car (screenshot only: the car is built through the builder hooks and the player is placed
// 7.5 m behind a frozen traffic car, like tW11's side test). The tap-built car and the real drive are in nb.js. usage: node t4/nbside.js <url> <outdir>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');const URL=process.argv[2],OUT=process.argv[3]||'t4/nbside';fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});
 const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto(URL);await p.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:240000});const cdp=await ctx.newCDPSession(p);
 const tapXY=async(x,y)=>{const tp=[{x,y,id:1,radiusX:4,radiusY:4,force:1}];await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})]);await p.waitForTimeout(600)};
 const tapEl=async e=>{const bb=await e.boundingBox();if(bb)await tapXY(bb.x+bb.width/2,bb.y+bb.height/2)};
 console.log('built',await p.evaluate(()=>{document.querySelector('#gbMenuBtn').click();__gb.enter();__gnb.nw('sc8');for(const[t,x,z,r]of[['hl',-4,-8],['tl',-4,7,2],['arch',-4,-7],['arch',-4,3],['b16',-4,-3],['ws4',-2,-4],['cs24',-2,-8],['cs24',-2,3,2],['spoiler',-3,5],['t16',-4,-3]])__gb.add(t,x,z,r||0,0);
  for(const o of __gb.list())if(o.t==='t16'||(o.t==='cs24'&&o.z===-8))o.c=9;__gb.refresh();document.querySelector('#gbBkT [data-a="done"]').click();document.querySelector('#gbx .gbTabs button[data-t="veh"]').click();document.querySelector('#gbSave').click();return JSON.stringify(__gnb.saved())}));
 await tapEl(await p.$('#hcStory'));for(let i=0;i<80;i++){await p.waitForTimeout(3000);if(await p.evaluate(()=>__mho.state+'|'+!!(__mho.LD&&__mho.LD.on))==='roam|false')break;for(const q of['#slotList .go','#m1Next']){const e=await p.$(q);if(e&&await e.isVisible())await tapEl(e)}}
 for(let i=0;i<14;i++){let hit=0;for(const l of[p.getByText('SKIP',{exact:false}),p.getByText('TAP TO CONTINUE'),p.locator('#m1Next')]){const e=l.first();if(await e.count()&&await e.isVisible()){await tapEl(await e.elementHandle());hit=1;break}}if(!hit&&i>3)break;await p.waitForTimeout(1500)}
 const sel=await p.evaluate(()=>{const M=__mho,R=M.RO,H=M.HUB,N=H.nodes;let j=-1,bd=1e9;(H.cars||[]).forEach((c,i)=>{if(c.dead>0||c.tr)return;const A=N[c.a],B=N[c.b];if(!A||!B||A.ab||B.ab||A.g||B.g)return;const L=Math.hypot(B.x-A.x,B.z-A.z);if(L*(1-c.t)<20||L*c.t<14)return;const d=Math.hypot(c.x-R.x,c.z-R.z);if(d<bd){bd=d;j=i}});if(j<0)return null;
  const c=H.cars[j];c.v=0;c.cv=0;c.hv=.01;c.route=[];c.hitT=99;window.__tc=j;const A=N[c.a],B=N[c.b],L=Math.hypot(B.x-A.x,B.z-A.z);return{x:c.x,z:c.z,h:Math.atan2((B.x-A.x)/L,(B.z-A.z)/L)}});
 console.log('traffic',JSON.stringify(sel));if(!sel){console.log('ERR',errs);return b.close()}
 const place=(x,z,h)=>p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+30);R.v=0;R.yr=0;R.vh=h;R.h=h;R.stkT=0;R.crTurn=null},[sel.x-Math.sin(sel.h)*7.5,sel.z-Math.cos(sel.h)*7.5,sel.h]);
 await place();await p.waitForTimeout(6000);await place();await p.waitForTimeout(3000);
 const cam=async(n,close)=>{await p.evaluate(([x,z,h,close])=>{const M=__mho,R=M.RO,ax=close?R.x:R.x+(x-R.x)*.35,az=close?R.z:R.z+(z-R.z)*.35,g=M.gnd(ax,az,R.y+.3),sx=Math.cos(h),sz=-Math.sin(h),k=close?3.6:9;__gnb.cam([ax+sx*k,g+(close?.35:1),az+sz*k,ax,g+(close?.25:.6),az])},[sel.x,sel.z,sel.h,close]);await p.waitForTimeout(3000);await p.screenshot({path:`${OUT}/${n}.png`});console.log('shot',n)};
 await cam('09_side_traffic',0);await cam('10_side_tyres',1);await p.evaluate(()=>__gnb.cam(null));
 console.log('tyre',await p.evaluate(()=>JSON.stringify(__gnb.gap())),'dist',await p.evaluate(()=>{const R=__mho.RO,c=__mho.HUB.cars[window.__tc];return+Math.hypot(c.x-R.x,c.z-R.z).toFixed(1)}));console.log('ERR',errs.slice(0,8));await b.close()})();
