// t4/r2place.js: R2 builder, place one part by real taps (debug). usage: node t4/r2place.js <url> <outdir>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');
(async()=>{const U=process.argv[2],O=process.argv[3];fs.mkdirSync(O,{recursive:true});const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
 const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});const pg=await ctx.newPage();const errs=[];pg.on('pageerror',e=>errs.push(String(e)));
 await pg.goto(U);await pg.waitForFunction(()=>window.__mho&&!document.querySelector('#topBtns').hidden,null,{timeout:240000});const cdp=await ctx.newCDPSession(pg);
 const tapXY=async(x,y,w=700)=>{const tp=[{x,y,id:1,radiusX:4,radiusY:4,force:1}];await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})]);await pg.waitForTimeout(w)};
 const tap=async(s,w)=>{const bb=await (await pg.$(s)).boundingBox();await tapXY(bb.x+bb.width/2,bb.y+bb.height/2,w)};const ev=(f,a)=>pg.evaluate(f,a);
 await tap('#gbMenuBtn',2500);await tap('#r2R [data-r2m="build"]',3000);await tap('#gbBkPc [data-p="b22"]');await ev(()=>{window.__lg=[];const M=__gb.GB_.ptr,od=M.delete.bind(M);M.delete=k=>{__lg.push('dt:'+(performance.now()-M.get(k).t)+':'+JSON.stringify(M.get(k))+'del:'+k+':multi'+__gb.GB_.multi+':drag'+__gb.GB_.drag+':bk'+__gb.GB_.bk);return od(k)};const c=window;for(const t of['pointerdown','pointerup','pointercancel'])c.addEventListener(t,e=>__lg.push(t+':ts'+Math.round(e.timeStamp)+':'+(e.target.id||e.target.className)+':'+e.pointerType+':'+e.pointerId+':'+__gb.GB_.ptr.size+':'+__gb.GB_.multi+':'+__gb.GB_.drag),true)});
 console.log('fps',await ev(()=>new Promise(r=>{let n=0;const t0=performance.now();const f=()=>{n++;if(performance.now()-t0<3000)requestAnimationFrame(f);else r(n/3)};requestAnimationFrame(f)})));console.log('tool',await ev(()=>__gb.GB_.tool),'pc',await ev(()=>__gb.GB_.pc));
 for(const[i,j]of[[-1,-1],[0,0],[-1,1],[0,-2]]){const s=await ev(([i,j])=>__gb.scr(i,j),[i,j]);const el=await ev(s=>{const e=document.elementFromPoint(s.x,s.y);return e&&(e.id||e.className)},s);console.log('cell',i,j,JSON.stringify(s),'el',el);
  console.log(' cand',JSON.stringify(await ev(s=>__r2.cand(s.x,s.y),s)),'area',JSON.stringify(await ev(()=>__r2.area())),'view',JSON.stringify(await ev(()=>{const c=__gb.mesh()&&window.__mho;return 0})));await tapXY(s.x,s.y);console.log(' log',JSON.stringify(await ev(()=>__lg.splice(0))),' tip',await ev(()=>document.querySelector('#gsTip')&&document.querySelector('#gsTip').textContent),' held',JSON.stringify(await ev(()=>__gs.held())),'n',await ev(()=>__gb.list().length));if(await ev(()=>__gs.held())){await tapXY(s.x,s.y);console.log(' after 2nd',await ev(()=>__gb.list().length));break}}
 await pg.screenshot({path:O+'/place.png'});console.log('ERR',errs.slice(0,3));await b.close()})();
