// t4/tx16drive.js <url> <out> : CAR=<preset id>. Fresh save with that car equipped, STORY → NEW GAME (real taps), tap through, hold GAS (real touch) 10 s, log speed + state per second.
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const OUT=process.argv[3];require('fs').mkdirSync(OUT,{recursive:true});const CAR=process.env.CAR||'t_taxi';
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});
 const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});const ev=(f,a)=>p.evaluate(f,a),W=ms=>p.waitForTimeout(ms);
 await p.goto(process.argv[2]);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:240000});
 await ev(c=>{localStorage.clear();localStorage.setItem('mho_slot','1');0},CAR);await p.reload();
 await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:240000});const cdp=await ctx.newCDPSession(p);
 const tapXY=async(x,y)=>{const tp=[{x,y,id:1,radiusX:4,radiusY:4,force:1}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await W(700)};
 const tap=async s=>{const e=await p.$(s);if(!e||!await e.isVisible())return 0;await e.scrollIntoViewIfNeeded().catch(()=>{});await W(300);const bb=await e.boundingBox();if(!bb)return 0;await tapXY(bb.x+bb.width/2,bb.y+bb.height/2);return 1};
 if(CAR!=='rod'){await tap('#gbMenuBtn');await W(1500);await tap('#r2R [data-r2m="rides"]');await W(1200);console.log('pick',await tap('[data-gc="'+CAR+'"]'));await W(2000);await p.screenshot({path:OUT+'/pick.png'});console.log('eq0',await ev(()=>__g9c.eq('car')));console.log('save',await tap('#gbSave'));await W(3000);console.log('eq',await ev(()=>__g9c.eq('car')))}
 console.log('sel',await ev(()=>{try{return JSON.parse(localStorage.getItem('mho_gar')).sel}catch(e){return 'x'}}));
 await tap('#hcStory');await W(800);await tap('#slotList .go');
 for(let i=0;i<150;i++){await W(2000);const s=await ev(()=>__mho.state+'|'+!!(__mho.LD&&__mho.LD.on));if(i%10==0)console.log('wait',i,s);if(s==='roam|false')break;if(s.startsWith('menu')&&i%5==4){await tap('#hcStory');await W(800);await tap('#slotList .go')}}
 if(process.env.OLD)for(let i=0;i<10;i++){let hit=0;for(const l of[p.getByText('SKIP',{exact:false}),p.getByText('TAP TO CONTINUE'),p.locator('#m1Next')]){const e=l.first();if(await e.count()&&await e.isVisible()){const bb=await e.boundingBox();console.log('oldtap',await e.evaluate(x=>(x.id||x.className||x.tagName)+':'+x.textContent.slice(0,40)));await tapXY(bb.x+bb.width/2,bb.y+bb.height/2);hit=1;break}}if(!hit&&i>3)break;await W(1500)}
 else for(let i=0;i<12;i++){let hit=0;for(const s of['#storyGo','#m1Cs','#rcGo','.m1go','#resBtn','#tutSkip','#m1Next']){if(await tap(s)){hit=1;break}}if(!hit&&i>3)break;await W(1200)}
 const st=()=>ev(()=>{const R=__mho.RO;return{spd:(document.body.innerText.match(/(\d+) KM\/H/)||[])[1],v:+((R.v||0)*3.6).toFixed(1),x:+R.x.toFixed(1),z:+R.z.toFixed(1),gas:!!(__mho.touch&&__mho.touch.gas),card:!!R.card,story:!!R.story,frozen:!!R.frozen,wk:!!R.wk,cd:R.ch&&R.ch.cd,mass:R.mass,veh:R.veh||R.form,hud:(document.querySelector('#roamSpd,#spd')||{}).textContent}});
 console.log('before',JSON.stringify(await st()));await p.screenshot({path:OUT+'/start.png'});
 const g=await (await p.$('#tG')).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g.x+g.width/2,y:g.y+g.height/2,id:2}]});
 for(let i=0;i<10;i++){await W(1000);console.log('t',i+1,JSON.stringify(await st()))}
 await p.screenshot({path:OUT+'/drive.png'});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 {const k=await (await p.$('#tB')).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:k.x+k.width/2,y:k.y+k.height/2,id:4}]});await W(8000);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.screenshot({path:OUT+'/chase_stop.png'})}
 const BB=()=>ev(()=>{const S0=typeof __mho.ships==='function'?__mho.ships():__mho.ships;const m=__mho.RO.mesh||S0[0].mesh;m.updateMatrixWorld(true);const V3=m.position.constructor;let B3=null;m.traverse(o=>{if(!B3&&o.isMesh){o.geometry.computeBoundingBox();B3=o.geometry.boundingBox.constructor}});const THREE={Box3:B3,Vector3:V3};const out={};for(const k of['gb','all']){const b=new THREE.Box3();m.traverse(o=>{let v=1;for(let q=o;q;q=q.parent)if(!q.visible)v=0;if(o.isMesh&&v&&(k==='all'||o.userData.gb))b.expandByObject(o)});const S=b.getSize(new THREE.Vector3());out[k]=[S.x,S.y,S.z].map(v=>+v.toFixed(2))}const ws=[];m.traverse(o=>{if(o.userData&&o.userData.gb&&o.isMesh){const q=o.getWorldScale(new THREE.Vector3());ws.push([q.x,q.y,q.z].map(v=>+v.toFixed(3)).join('/'))}});out.ws=[...new Set(ws)];out.sc=[m.scale.x,m.scale.y,m.scale.z].map(v=>+v.toFixed(3));const c=m.children[0];if(c)out.sc0=[c.scale.x,c.scale.y,c.scale.z].map(v=>+v.toFixed(3));return out}).catch(e=>String(e));
 console.log('bbox',JSON.stringify(await BB()));
 const cam=async(n,f)=>{await ev(f);await W(2500);await p.screenshot({path:OUT+'/'+n+'.png'});console.log('shot',n)};
 await cam('side_low',()=>{const R=__mho.RO,g=__mho.gnd(R.x,R.z,R.y+.3),sx=Math.cos(R.h),sz=-Math.sin(R.h);__gnb.cam([R.x+sx*6,g+.9,R.z+sz*6,R.x,g+1.6,R.z])});
 await cam('f34',()=>{const R=__mho.RO,g=__mho.gnd(R.x,R.z,R.y+.3),fx=Math.sin(R.h),fz=Math.cos(R.h),sx=Math.cos(R.h),sz=-Math.sin(R.h);__gnb.cam([R.x+fx*5+sx*3.6,g+1.8,R.z+fz*5+sz*3.6,R.x,g+1.7,R.z])});
 await cam('f34b',()=>{const R=__mho.RO,g=__mho.gnd(R.x,R.z,R.y+.3),fx=-Math.sin(R.h),fz=-Math.cos(R.h),sx=Math.cos(R.h),sz=-Math.sin(R.h);__gnb.cam([R.x+fx*5+sx*3.6,g+1.8,R.z+fz*5+sz*3.6,R.x,g+1.7,R.z])});
 console.log('gap',JSON.stringify(await ev(()=>{try{return __gnb.gap()}catch(e){return String(e)}})));
 await cam('traffic_low',()=>{const M=__mho,R=M.RO;let c=null,bd=1e9;for(const q of M.HUB.cars||[]){if(q.dead)continue;const d=Math.hypot(q.x-R.x,q.z-R.z);if(d<bd){bd=d;c=q}}if(!c)return;const g=M.gnd(c.x,c.z,(c.y||0)+.3);__gnb.cam([c.x+4.5,g+.8,c.z+4.5,c.x,g+1.3,c.z]);window.__tcD=Math.round(bd)});console.log('traffic dist',await ev(()=>window.__tcD));
 await ev(()=>{window.__gnbCam=null});
 console.log('ERR',JSON.stringify(errs.filter(e=>!/GPU stall|GL Driver/.test(e)).slice(0,6)));await b.close()})();
