// jsdom smoke test: no WebGL -> 2D fallback must draw the same information; API must not throw.
const { JSDOM } = require('../../node_modules/jsdom');
const fs = require('fs');
const dom = new JSDOM('<!doctype html><body><canvas id="c"></canvas><div id="fb"></div></body>', { runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window; w.eval(fs.readFileSync(__dirname + '/kit.js', 'utf8'));
const K = w.SFKit; let fails = 0; const ok = (c, m) => { if (!c) { fails++; console.log('FAIL', m); } else console.log('ok  ', m); };
const r = K.init(w.document.getElementById('c'), { fallback: w.document.getElementById('fb'), fonts: false });
ok(r.ok === false && r.mode === '2d', 'init falls back to 2d without WebGL');
K.setPlayers(4, 0, { names: ['You', 'Wren', 'Pike', 'Moss'], captain: 1 });
const mk = (s, n) => Array.from({ length: n }, (_, i) => ({ id: s + '-' + i, known: s === 0, color: i === 3 ? 'red' : i === 5 ? 'yellow' : 'blue', value: i === 3 ? 4.5 : i === 5 ? 5.1 : i + 1, cut: i === 1, infoToken: i === 2 ? 3 : null }));
for (let s = 0; s < 4; s++) K.setStand(s, 0, mk(s, 13));
K.setDial(2, 4); K.setTokens({ validation: [11], markers: [{ color: 'red', value: 4.5 }] });
K.setEquipment([{ id: 'eq6', name: 'Rewind', unlock: { value: 6, count: 2 }, state: 'ready', effect: 'Dial back one.' }]);
K.setMissionCards({ mission: { number: 9, name: 'Pecking Order', text: 'Cut in order.' }, numbers: [{ value: 5 }, { value: 3 }], sequence: { side: 'A', at: 0 }, constraints: [{ letter: 'A' }], challenges: [{ n: 4 }] });
K.setCharacters([{ seat: 0, name: 'Tally', item: 'double_probe' }]);
K.highlight(['1-4', { kind: 'dial' }]);
const fb = w.document.getElementById('fb');
ok(fb.querySelectorAll('.sf2d-seat').length === 4, '4 seats drawn');
ok(fb.querySelectorAll('.sf2d-t').length === 52, '52 tiles drawn');
ok(fb.querySelectorAll('.sf2d-t.back').length === 3 * 12, 'hidden opponent tiles show backs (36)');
ok(fb.querySelectorAll('.sf2d-t.cut').length === 4, 'cut tiles marked');
ok(fb.querySelectorAll('.sf2d-hl').length >= 1, 'highlight drawn');
ok(/Detonator dial 2 of 4/.test(fb.innerHTML), 'dial svg reflects value');
ok(fb.querySelectorAll('.sf2d-tv.ok').length === 1, 'validation token shown');
ok(fb.querySelectorAll('.sf2d-card').length === 1, 'equipment card shown');
ok(/Pecking Order/.test(fb.innerHTML), 'mission shown');
const t = fb.querySelector('[data-sf*="1-4"]'); const pk = K.pick2D(t); ok(pk && pk.kind === 'tile' && pk.id === '1-4', 'pick2D returns tile descriptor');
ok(K.pick(10, 10) === null, '3D pick returns null in 2d mode');
K.fx('boom'); K.fx('win'); ok(fb.querySelectorAll('.sf2d-pop').length === 2, 'fx pop-ups in 2d');
ok(typeof K.isAnimating() === 'boolean', 'isAnimating works');
const fresh = w.document.createElement('div'); K.render2D(fresh, K.getState()); ok(fresh.querySelectorAll('.sf2d-t').length === 52, 'render2D(container,state) standalone');
K.resize(390, 844); K.dispose(); ok(true, 'resize + dispose without WebGL');
console.log(fails ? fails + ' FAILED' : 'ALL PASSED'); process.exit(fails ? 1 : 0);
