// ath/perfd.js <url> fra|ath : CPU per tick while driving (render stubbed): mean / p95 / max over 3 x 200 ticks, + LV share. LIFE=x, SET=code
const enter=require('../bc/enter.js');const URL=process.argv[2],CITY=process.argv[3]||'fra';
(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:process.env.GFX||'normal',seed,tick:process.env.NOTICK?0:1});const {p,errs}=E;p.setDefaultTimeout(900000);
 if(process.env.LIFE)await p.evaluate(v=>__g9ev('TUNE.life='+v),process.env.LIFE);if(process.env.SET)await p.evaluate(v=>__g9ev(v),process.env.SET);await E.roamApi();
 const spots=await p.evaluate(()=>{const N=__mho.HUB.nodes,ok=[];for(let i=0;i<N.length;i++){const a=N[i];if(a&&a.nb&&a.nb.length>=2&&!a.ab&&N[a.nb[0]])ok.push(i)}return [.1,.5,.9].map(f=>{const a=N[ok[Math.floor(f*ok.length)]],b=N[a.nb[0]];return[a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z)]})});
 const T=[];let lv=0;for(const [x,z,h] of spots){await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+60);R.v=0;R.vh=h;R.h=h},[x,z,h]);await p.waitForTimeout(4000);
  const r=await p.evaluate(()=>{const C=__g9ev('composer'),RO=__mho.RO;const rr=C.render;C.render=()=>{};const t=[];for(let i=0;i<200;i++){RO.v=Math.max(RO.v,22);const t0=performance.now();__tick(1);t.push(performance.now()-t0)}C.render=rr;return {t,lv:typeof __lv!=='undefined'?__lv.LV.ms:0}});T.push(...r.t);lv+=r.lv/3}
 T.sort((a,b)=>a-b);const m=T.reduce((a,b)=>a+b,0)/T.length;console.log(CITY,'life',process.env.LIFE??'def',process.env.SET||'','mean',m.toFixed(2),'p95',T[Math.floor(T.length*.95)].toFixed(2),'p99',T[Math.floor(T.length*.99)].toFixed(2),'max',T[T.length-1].toFixed(2),'lvms',lv.toFixed(3),'errors',errs.length);await E.b.close()})();
