// Rules tests for The Thornbound Throne engine. Run: node rules-test.js   (exit code 1 on any failure)
// Every test builds a small scene (hands, regions, councils, Kingdom Cards...) with TB.test helpers, drives the engine by answering its
// questions, and checks the result against the rules in rules-notes.md.
require('./src/data.js');require('./src/engine.js');
const T=TB.test,I=TB.internal;
const F=['nobility','clans','uprising','gathering'];
const RUSE=0,TRADER=1,F1=2,F2=3,F3=4,F4=5,AGENT=6,CAV=7,WM=8,C6=9,C7=10,C8=11,C9=12,HEIR=13,A1=14,A2=15,A3=16,A4=17,HQ=18;
const c=(seat,k)=>seat*100+k;
let pass=0,fail=0;const fails=[];const tests=[];
function test(name,fn){tests.push([name,fn])}
function ok(cond,msg){if(!cond)throw new Error('assert: '+msg)}
function eq(a,b,msg){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error('assert '+msg+': expected '+JSON.stringify(b)+' got '+JSON.stringify(a))}
// new game with chosen factions; seed fixed; order = seat order unless given
function game(np,facs,o){o=o||{};facs=facs||F.slice(0,np);const G=TB.newGame({players:facs.slice(0,np).map((f,i)=>({faction:f,name:'P'+i})),seed:o.seed||7,length:o.length,order:o.order||[...Array(np).keys()]});return G}
// set what is in a hand (everything else of the old hand goes to the top of the deck)
function setHand(G,seat,ids){const P=G.pl[seat];for(const id of P.hand.slice())if(!ids.includes(id))T.put(G,id,'deck');for(const id of ids)T.put(G,id,'hand')}
function pump(G,rules,max){max=max||400;for(let i=0;i<max;i++){const p=TB.pending(G);if(!p)return 'idle';const f=rules[p.kind]||rules['*'];if(!f)return p.kind;let any=false;
    for(const seat of p.seats.slice()){const q=TB.pending(G);if(!q||!q.seats.includes(seat))continue;const mv=TB.moves(G,seat);let m=f(mv,seat,q,G);if(typeof m==='string')m=mv.find(x=>x.k===m);if(!m)continue;const r=TB.apply(G,m);if(!r.ok)throw new Error('pump apply: '+r.err+' '+(r.stack||''));any=true}
    if(!any)return p.kind}return 'max'}
const done=mv=>mv.find(m=>m.t==='done'||m.t==='seldone');
const noMenu={menu:done};
function startAt(G,steps){T.run(G,steps)}
function lastLog(G,n){return G.log.slice(-(n||8)).map(e=>e.t)}
// scene helpers for a clash: cards placed face-down by region, supporters, heralds
function scene(G,o){o=o||{};
  for(const s in (o.place||{})){o.place[s].forEach((id,r)=>{if(id!=null)T.put(G,id,'down',r)})}
  for(const s in (o.supp||{})){const P=G.pl[s];o.supp[s].forEach((n,r)=>{P.supp.b-=n;P.supp.r[r]+=n})}
  for(const s in (o.herald||{}))G.pl[s].herald=o.herald[s]}
const SKIPS={menu:done,castle:mv=>mv.find(m=>m.skip),wilderness:mv=>mv.find(m=>m.skip),harvest:mv=>mv.find(m=>!m.yes),shrine:done,ossuary:done,relics:done,siteBuy:done,discardDown:null,location:mv=>mv[0]};
function runClashes(G,order,rules){startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);
  const placer=TB.pending(G).seats[0];T.answer(G,placer,'o'+order.join(''));return pump(G,Object.assign({},SKIPS,rules||{}))}
// seat 0 (Strength 9 captain) beats seat 1 (Strength 1) in the Region that holds location `loc`; returns the pump result
function winAt(G,loc,rules){const r=loc>>1;for(const s of [0,1])G.reg[r].down=G.reg[r].down.filter(id=>false);T.put(G,c(0,C9),'down',r);T.put(G,c(1,F1),'down',r);const order=[r].concat([0,1,2].filter(x=>x!==r));return runClashes(G,order,Object.assign({location:locPick(loc)},rules||{}))}
const locFirst=mv=>mv[0];
const locPick=l=>mv=>mv.find(m=>m.loc===l)||mv[0];
// ============================================================ SETUP
test('setup: decks, hand, site of power, supporters, tactics (4 factions)',()=>{const G=game(4);
  for(const P of G.pl){eq(P.hand.length,6,'hand');eq(P.deck.length,8,'deck');eq(P.site.length,5,'site');eq(P.hs,6,'hand size');eq(P.supp.b,5,'supporters');eq(P.tac.length,4,'tactics');ok(P.hand.includes(c(P.seat,HEIR)),'heir starts in hand')}
  eq(G.pl[0].tac.map(t=>t.mk),[0,2,0,0],'nobility Martial Writ has 2 markers');eq(G.pl[1].tac.map(t=>t.mk),[0,3,0,0],'clans Open Waterways has 3 markers');eq(G.pl[2].tac.map(t=>t.mk),[0,3,0,0],'uprising Hideouts has 3 markers');
  eq(G.road.filter(Boolean).length,4,'four face-up Great Road cards');eq(G.kdeck.length,47,'kingdom deck');eq(G.fav,{h:-1,u:3},'favour on Harvest Field');
  eq(TB.invariants(G),[], 'invariants')});
test('setup: faction decks are 14 identical basic cards + 5 site cards, original names only',()=>{const D=TB.DATA;eq(D.BASIC.length,14,'basic');for(const f of F)eq(D.SITE[f].length,5,'site '+f);eq(D.KC.length,51,'51 kingdom cards');
  eq(D.FACTIONS.map(f=>D.FNAME[f]),['The Gilded Court','The Heathbound Clans','The Lantern Rising','The Pale Choir'],'faction names');
  const txt=JSON.stringify(D);for(const bad of ['Nobility','Uprising','Gathering','Old King','Leder','Eerie'])ok(!txt.includes(bad)||bad==='Nobility'&&false,'forbidden original word '+bad)});
test('round 1 skips the Start of the Year draw; first question is the simultaneous bid',()=>{const G=game(3);const p=TB.pending(G);eq(p.kind,'bid','kind');ok(p.simul,'simultaneous');eq(p.seats.length,3,'all seats bid');for(const P of G.pl)eq(P.hand.length,6,'no draw in round 1')});
test('game lengths: short 4, standard 5, extended 6 rounds',()=>{eq(game(2,null,{length:'short'}).rounds,4,'short');eq(game(2).rounds,5,'standard');eq(game(2,null,{length:'extended'}).rounds,6,'extended')});
test('2 to 4 players only (solo deferred)',()=>{let e=null;try{TB.newGame({players:[{faction:'clans'}]})}catch(x){e=x}ok(e,'one player is rejected');e=null;try{TB.newGame({players:F.concat(['clans']).map(f=>({faction:f}))})}catch(x){e=x}ok(e,'five players rejected')});
test('determinism: same seed and same moves give the same game',()=>{const run=()=>{const G=game(3,null,{seed:99});let n=0;while(G.phase!=='over'&&n++<4000){const p=TB.pending(G);const s=p.seats[0];const mv=TB.moves(G,s);TB.apply(G,mv[(n*7)%mv.length])}return JSON.stringify([G.pl.map(p=>p.inf),G.log.length,G.round])};eq(run(),run(),'repeatable')});
// ============================================================ START OF THE YEAR
test('start of year: everyone draws up to hand size; Order Track sorted by Influence',()=>{const G=game(3);G.round=2;for(const P of G.pl){P.inf=[2,5,3][P.seat];T.put(G,P.hand[0],'disc');T.put(G,P.hand[0],'disc')}
  startAt(G,[['startYear']]);for(const P of G.pl)eq(P.hand.length,6,'refilled');eq(G.order,[1,2,0],'order by influence')});
test('Order Track ties reverse the previous relative order of the tied players',()=>{const G=game(3,null,{order:[0,1,2]});G.round=2;G.pl[0].inf=4;G.pl[1].inf=4;G.pl[2].inf=1;startAt(G,[['startYear']]);eq(G.order,[1,0,2],'tied 0 and 1 reversed');
  const H=game(4,null,{order:[0,1,2,3]});H.round=2;for(const P of H.pl)P.inf=3;startAt(H,[['startYear']]);eq(H.order,[3,2,1,0],'all tied: fully reversed')});
test('Attrition: empty deck shuffles discard into a new deck and hand size drops by 1',()=>{const G=game(2);const P=G.pl[0];G.round=2;for(const id of P.deck.slice())T.put(G,id,'disc');eq(P.deck.length,0,'deck empty');
  for(const id of P.hand.slice(0,3))T.put(G,id,'disc');startAt(G,[['startYear']]);eq(P.hs,5,'hand size 5');eq(P.hand.length,5,'draws up to the new hand size');ok(P.deck.length>0,'new deck from the Discard Pile');eq(TB.invariants(G),[],'conserved')});
test('Attrition never drops hand size below 3 and a Veiled Patron absorbs one Attrition',()=>{const G=game(2);const P=G.pl[0];P.hs=3;G.round=2;for(const id of P.deck.slice())T.put(G,id,'disc');setHand(G,0,[c(0,F1),c(0,F2)]);
  startAt(G,[['startYear']]);eq(P.hs,3,'stays at 3');eq(P.hand.length,3,'hand 3');
  const H=game(2);const Q=H.pl[0];T.kcRemove(H,4);Q.sup.push(4);H.round=2;for(const id of Q.deck.slice())T.put(H,id,'disc');setHand(H,0,[c(0,F1),c(0,F2),c(0,F3),c(0,F4)]);for(const id of Q.deck.slice())T.put(H,id,'disc');startAt(H,[['startYear']]);
  eq(Q.hs,6,'hand size unchanged');ok(!Q.sup.includes(4),'Patron discarded');ok(H.kdisc.includes(4),'to the Kingdom Discard')});
test('hand size limits: Seal-Ring raises to a maximum of 8 and leaving lowers it',()=>{const G=game(2);const P=G.pl[0];P.hs=8;T.giveKC(G,0,17,P.hand[0],0);eq(P.hs,8,'cannot exceed 8');
  const H=game(2);const Q=H.pl[0];T.giveKC(H,0,17,Q.hand[0],0);eq(Q.hs,7,'Seal-Ring +1');
  H.pl[0].inf=0;startAt(H,[['bidPlace']]);});
test('hand size: cards that would enter a full hand go on top of the deck',()=>{const G=game(2);const P=G.pl[0];G.fav.h=-1;P.hs=3;setHand(G,0,[c(0,F1),c(0,F2),c(0,F3)]);T.put(G,c(0,C6),'disc');I.setG(G);I.toHand(0,c(0,C6));eq(P.hand.length,3,'still 3');eq(P.deck[0],c(0,C6),'on top of deck')});
// ============================================================ BIDS
function bidScene(hands,opts){opts=opts||{};const G=game(hands.length,opts.facs||['clans','uprising','gathering'],opts);hands.forEach((h,s)=>setHand(G,s,h));return G}
test('bids: resolved highest Strength first; ties go to the higher Order Track position',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)],[c(2,C6),c(2,F1),c(2,F2),c(2,F3),c(2,F4),c(2,RUSE)]],{order:[2,0,1]});
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));T.answer(G,2,'b:'+c(2,C6));
  startAt(G,[['bidReveal'],['bidOrder']]);eq(G.bq,[1,2,0],'Strength 8 first, then the two 6s by order (seat 2 is first on the track)')});
test('bids: take a Great Road card and occupy it; bidding card slides under it',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);const kc=G.road[3];
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));
  T.answer(G,1,'gr:3');eq(G.pl[1].ks[0]&&G.pl[1].ks[0].kc,kc,'seat 1 holds the card');eq(G.pl[1].ks[0].occ,c(1,C8),'occupied by the bid');T.answer(G,0,'ret');ok(G.pl[0].hand.includes(c(0,C6)),'bid returned to hand');eq(TB.invariants(G),[],'inv')});
test('bids: a third Kingdom Card replaces an old one (old discarded, its occupier back to hand)',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);const P=G.pl[0];
  T.giveKC(G,0,13,c(0,F1),0);T.giveKC(G,0,14,c(0,F2),1);T.road(G,3,20);
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');T.answer(G,0,'gr:3');
  const q=TB.pending(G);eq(q.kind,'slot','must pick a space');T.answer(G,0,'sl0');eq(P.ks[0].kc,20,'new card in slot 0');ok(G.kdisc.includes(13),'old card discarded');ok(P.hand.includes(c(0,F1))||P.deck[0]===c(0,F1),'old occupier returns to hand')});
test('steal: needs STRICTLY higher Bidding Strength than the occupying card; occupier goes home',()=>{const G=bidScene([[c(0,C7),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);
  T.giveKC(G,1,13,c(1,F3),0);// occupier strength 3
  T.put(G,c(1,F4),'occ',[1,0]);// swap: strength-4 card occupies it
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);
  // seat 0 bids 7 (> 4): may steal. Seat 1 bids 8.
  T.answer(G,0,'b:'+c(0,C7));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');const mv=TB.moves(G,0);ok(mv.some(m=>m.t==='steal'),'steal offered');T.answer(G,0,m=>m.t==='steal');
  eq(G.pl[0].ks[0].kc,13,'stolen card now on seat 0');ok(G.pl[1].hand.includes(c(1,F4)),'victim card back to hand');
  const H=bidScene([[c(0,F4),c(0,F1),c(0,F2),c(0,F3),c(0,C6),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);T.giveKC(H,1,13,c(1,F4),0);
  startAt(H,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext']]);T.answer(H,0,'b:'+c(0,F4));T.answer(H,1,'b:'+c(1,C8));T.answer(H,1,'ret');ok(!TB.moves(H,0).some(m=>m.t==='steal'),'equal Strength cannot steal')});
test('Sentinel Towers: +5 Strength to bid and occupiers, +1 Influence for resolving first, cannot steal',()=>{const G=bidScene([[c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,C6),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);
  T.giveKC(G,0,5,c(0,RUSE),0);startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext']]);T.answer(G,0,'b:'+c(0,F4));T.answer(G,1,'b:'+c(1,C8));
  eq(G.bstr[0],9,'4+5');eq(G.pl[0].inf,1,'first to resolve gains 1');ok(!TB.moves(G,0).some(m=>m.t==='steal'),'cannot steal')});
test('Cutthroat Crew: +3 to steal attempts; the holder gains 1 Influence when any card is stolen',()=>{const G=bidScene([[c(0,F4),c(0,F1),c(0,F2),c(0,F3),c(0,C6),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]]);
  T.giveKC(G,0,9,c(0,RUSE),0);T.giveKC(G,1,13,c(1,F4),0);startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext']]);T.answer(G,0,'b:'+c(0,F4));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');
  ok(TB.moves(G,0).some(m=>m.t==='steal'),'4+3=7 beats 4 only with the Crew... (4+3>4)');});
test('Great Road refill: one taken discards the rightmost; none taken discards the two rightmost',()=>{const G=game(2);const r0=G.road.slice();G.taken=true;G.road[0]=0;I.setG(G);
  startAt(G,[['bidEnd']]);ok(G.kdisc.includes(r0[3]),'rightmost discarded');eq(G.road.filter(Boolean).length,4,'refilled to 4');
  const H=game(2);const q0=H.road.slice();H.taken=false;startAt(H,[['bidEnd']]);ok(H.kdisc.includes(q0[3])&&H.kdisc.includes(q0[2]),'two rightmost discarded');eq(H.road[3],q0[1],'cards slide right');eq(H.road.filter(Boolean).length,4,'4 face-up')});
test('Kingdom Deck is rebuilt from the Kingdom Discard when it runs out',()=>{const G=game(2);G.kdisc=G.kdisc.concat(G.kdeck.splice(0));G.kdisc.push(G.road[0]);G.road[0]=0;G.kdisc.push(G.road[1]);G.road[1]=0;G.taken=true;I.setG(G);
  G.kdisc.push(G.road[2]);G.road[2]=0;G.kdisc.push(G.road[3]);G.road[3]=0;const keep=G.kdisc.splice(0,1);G.road[3]=keep[0];startAt(G,[['bidEnd']]);eq(G.road.filter(Boolean).length,4,'four face-up again');ok(G.kdeck.length>0,'new Kingdom Deck built from the discard');eq(TB.invariants(G),[],'inv')});
test('Crown\'s Edict sets every opponent\'s Bidding Strength to 0 and exhausts the tactic',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C9),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['nobility','clans']});
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C9));eq(TB.pending(G).kind,'edict','edict offered');T.answer(G,0,'yes');
  eq(G.bstr,[6,0],'opponent at 0');ok(G.pl[0].tac[2].ex,'exhausted');eq(G.bq,[0,1],'seat 0 first')});
// ============================================================ HERALDS, PLACEMENT, SPRING ACTIONS
test('heralds are placed in turn order, anywhere, fully public',()=>{const G=game(3,null,{order:[2,0,1]});startAt(G,[['heralds',{i:0}]]);eq(TB.pending(G).seats,[2],'first on the track');T.answer(G,2,'l3');eq(TB.pending(G).seats,[0],'then seat 0');T.answer(G,0,'l3');T.answer(G,1,'l0');eq(G.pl.map(p=>p.herald),[3,0,3],'positions');eq(TB.pending(G),null,'done')});
test('placing cards: exactly one face-down card next to each Region, simultaneously',()=>{const G=game(2);setHand(G,0,[c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,C6),c(0,C7)]);setHand(G,1,[c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,C6),c(1,C7)]);
  startAt(G,[['placeCards']]);const p=TB.pending(G);ok(p.simul,'simultaneous');eq(p.seats.length,2,'both');T.answer(G,0,'p:'+c(0,C6));T.answer(G,0,'p:'+c(0,C7));T.answer(G,0,'p:'+c(0,F1));
  eq(TB.pending(G).seats,[1],'seat 0 is finished, seat 1 still deciding');ok(!TB.moves(G,0).length,'no moves for finished seat');T.answer(G,1,'p:'+c(1,C6));T.answer(G,1,'p:'+c(1,C7));T.answer(G,1,'p:'+c(1,F1));
  for(let r=0;r<3;r++)eq(G.reg[r].down.length,2,'one card each in region '+r);eq(G.pl[0].hand.length,3,'3 left');eq(TB.pending(G),null,'done')});
test('placing cards: a player with fewer than three cards places before everyone else, one card per Region at most',()=>{const G=game(3,null,{order:[0,1,2]});setHand(G,1,[c(1,F1),c(1,F2)]);startAt(G,[['placeCards']]);const p=TB.pending(G);eq(p.seats,[1],'short-handed seat first');
  T.answer(G,1,'p:'+c(1,F1)+':2');T.answer(G,1,'p:'+c(1,F2)+':0');eq(G.reg[2].down,[c(1,F1)],'region 2');eq(G.reg[0].down,[c(1,F2)],'region 0');eq(TB.pending(G).seats.sort(),[0,2],'others next')});
test('Spring action: placing Supporters on Regions (any number, any Region)',()=>{const G=game(2);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,m=>m.p&&m.p.r===1&&m.p.n===3);eq(G.pl[0].supp.r,[0,3,0],'three on region 1');eq(G.pl[0].supp.b,2,'two left');T.answer(G,0,m=>m.p&&m.p.r===0&&m.p.n===2);eq(G.pl[0].supp.b,0,'none left');
  ok(!TB.moves(G,0).some(m=>m.a==='supp'),'no more to place')});
test('Spring actions are optional and run in turn order',()=>{const G=game(3,null,{order:[1,2,0]});startAt(G,[['menus',{step:'spring',i:0}]]);eq(TB.pending(G).seats,[1],'first on track');T.answer(G,1,'done');eq(TB.pending(G).seats,[2],'then second');T.answer(G,2,'done');eq(TB.pending(G).seats,[0],'then third');T.answer(G,0,'done');eq(TB.pending(G),null,'finished')});
// ============================================================ CLASHES
function clashGame(np,opts,placeDefs){const G=game(np,null,opts);for(const P of G.pl)setHand(G,P.seat,[]);return G}
test('clash: highest total Strength wins the Region and chooses a Location (Influence reward)',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,C9),c(0,F1),c(0,F2)],1:[c(1,C6),c(1,F3),c(1,F4)]}});
  const r=runClashes(G,[0,1,2],{location:locPick(3)});eq(r,'idle','finished');// region 0 (Uplands): seat 0 wins, region 1: seat1 3 vs 1 -> seat 1 wins; region 2: seat 0 (2) vs seat1 (4) -> seat 1 wins
  eq(G.pl[0].inf,1,'seat 0 won Uplands (1)');ok(G.pl[1].inf>=3,'seat 1 won two Regions')});
test('clash: Supporters add 1 Strength each, but only in the FIRST Clash in that Region',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,F4),null,null],1:[c(1,C6),null,null]},supp:{0:[3,0,0]}});
  runClashes(G,[0,1,2],{location:locPick(0)});eq(G.clash,null,'over');ok(/Strength in The Uplands: P0 7, P1 6/.test(G.log.map(l=>l.t).join('\n')),'4+3 supporters beat 6');eq(G.pl[0].supp.x[0],3,'spent supporters stay on the Map until Winter')});
test('clash: players with no Active cards still compete with Supporters',()=>{const G=clashGame(2);scene(G,{place:{1:[c(1,F1),null,null]},supp:{0:[2,0,0]}});runClashes(G,[0,1,2],{location:locPick(0)});eq(G.pl[0].inf,1,'seat 0 wins with 2 Supporters vs a Strength-1 card')});
test('tied Clash: tied players in turn order play a card or pass; a new Clash ignores earlier cards',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,C6),null,null],1:[c(1,C6),null,null]}});T.put(G,c(0,C9),'hand');T.put(G,c(1,F1),'hand');
  startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');pump(G,{menu:done},);let p=TB.pending(G);eq(p.kind,'tie','tie asked');eq(p.seats,[0],'turn order: seat 0 first');T.answer(G,0,'c'+c(0,C9));eq(TB.pending(G).seats,[1],'then seat 1');T.answer(G,1,'c'+c(1,F1));
  pump(G,{menu:done,location:locPick(0)});ok(/Strength in The Uplands: P0 9, P1 1/.test(G.log.map(l=>l.t).join('\n')),'only the new cards count (the first 6s do not)');eq(G.pl[0].inf,1,'seat 0 won the re-clash')});
test('tied Clash where everybody passes: no rewards, Region over',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,C6),null,null],1:[c(1,C6),null,null]}});T.put(G,c(0,F1),'hand');T.put(G,c(1,F1),'hand');startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');pump(G,{menu:done});T.answer(G,0,'pass');T.answer(G,1,'pass');
  pump(G,{menu:done,location:locPick(0)});eq(G.pl[0].inf+G.pl[1].inf,0,'nobody scores');ok(G.reg[0].done,'region resolved')});
test('Clash Markers are placed by the LAST player on the Order Track (Tempests overrides)',()=>{const G=game(3,null,{order:[1,2,0]});startAt(G,[['clashOrder']]);eq(TB.pending(G).seats,[0],'last on track');
  const H=game(3,null,{order:[1,2,0]});H.rm.tempests=1;startAt(H,[['clashOrder']]);eq(TB.pending(H).seats,[1],'Doctrine of Tempests holder')});
test('Deadly eliminates all opponents\' Active cards: Lost Pile; Resilient to Discard; Invulnerable immune',()=>{const G=clashGame(3);
  scene(G,{place:{0:[c(0,AGENT),null,null],1:[c(1,C9),null,null],2:[c(2,F3),null,null]}});T.put(G,c(2,HEIR),'down',0);
  // agent drawback: opponent Follower (seat 2's F3) is Active -> the agent eliminates itself. Replace the follower to avoid it.
  T.put(G,c(2,F3),'hand');
  runClashes(G,[0,1,2],{location:locPick(0)});ok(G.lost.includes(c(1,C9)),'captain to Lost Pile');ok(G.pl[2].disc.includes(c(2,HEIR)),'Resilient Heir goes to the Discard Pile');ok(!G.lost.includes(c(0,AGENT)),'agent survives (no Follower)')});
test('Invulnerable cards (Followers) cannot be eliminated; the Agent eliminates itself if an opponent Follower is Active',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,AGENT),null,null],1:[c(1,F2),null,null]}});runClashes(G,[0,1,2],{location:locPick(0)});
  ok(G.lost.includes(c(0,AGENT)),'agent drawback: eliminated');ok(!G.lost.includes(c(1,F2)),'follower is Invulnerable')});
test('two Deadly cards eliminate each other',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,AGENT),null,null],1:[c(1,AGENT),null,null]}});runClashes(G,[0,1,2],{location:locPick(0)});ok(G.lost.includes(c(0,AGENT))&&G.lost.includes(c(1,AGENT)),'both lost');eq(G.pl[0].inf+G.pl[1].inf,0,'0 vs 0 is a tie: nobody scores')});
test('Ambush adds a face-down card from hand that is revealed after everyone\'s Day step',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,RUSE),null,null],1:[c(1,C6),null,null]}});T.put(G,c(0,C9),'hand');
  startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');let p=TB.pending(G);eq(p.kind,'menu','day menu');eq(p.seats,[0],'turn order');const m=TB.moves(G,0).find(x=>x.a==='cmd:ambush');ok(m,'ambush offered');TB.apply(G,m);
  T.answer(G,0,'c'+c(0,C9));ok(G.reg[0].down.includes(c(0,C9)),'face-down in the Region');T.answer(G,1,'done');pump(G,{menu:done,location:locPick(0)});ok(/Strength in The Uplands: P0 9, P1 6/.test(G.log.map(l=>l.t).join('\n')),'9 vs 6 after reveal');eq(G.pl[0].inf,1,'seat 0 wins')});
test('Retreat returns Active cards, the Herald and Supporters in the Region',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,RUSE),null,null],1:[c(1,C6),null,null]},herald:{0:0},supp:{0:[2,0,0]}});
  startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,m=>m.a==='cmd:retreat');let p=TB.pending(G);eq(p.kind,'retreat','retreat selection');T.answer(G,0,'s:'+c(0,RUSE));T.answer(G,0,'s:H');T.answer(G,0,'s:S');
  ok(G.pl[0].hand.includes(c(0,RUSE)),'card back in hand');eq(G.pl[0].herald,-1,'herald home');eq(G.pl[0].supp.b,5,'supporters home');eq(G.pl[0].supp.r[0],0,'none in region')});
test('Flank moves a card to a different unresolved Region where it is Active (counts there)',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,CAV),null,null],1:[c(1,F1),c(1,F1+1),c(1,F3)]}});T.put(G,c(1,F1),'down',0);T.put(G,c(1,F2),'down',1);T.put(G,c(1,F3),'down',2);
  startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,m=>m.a==='cmd:flank');T.answer(G,0,'r1');ok(G.reg[1].up.includes(c(0,CAV)),'now Active in region 1');pump(G,{menu:done,location:locPick(2)});ok(/Strength in The Tablelands: P0 5, P1 2/.test(G.log.map(l=>l.t).join('\n')),'5 vs 2 in region 1')});
test('Night Effects: Deadly is mandatory (not an option) and resolves before Strength is tallied',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,AGENT),null,null],1:[c(1,C9),null,null]}});runClashes(G,[0,1,2],{location:locPick(0)});ok(/Strength in The Uplands: P0 5, P1 0/.test(G.log.map(l=>l.t).join('\n')),'captain was eliminated before tally');eq(G.pl[0].inf,1,'agent wins')});
// ============================================================ REWARDS: LOCATIONS AND HERALDS
const winRegion0=(G,loc,extra)=>winAt(G,loc,extra);
test('Location Battlefield: 2 Influence and nothing else',()=>{const G=clashGame(2);winAt(G,3);eq(G.pl[0].inf,2,'2 Influence');eq(TB.pending(G),null,'no extra text to resolve')});
test('Location Castle: +1 Influence and Govern with an Active or hand card; every other card in that Council is discarded',()=>{const G=clashGame(2);T.put(G,c(1,C6),'council','oaths');T.put(G,c(0,C7),'council','oaths');
  winRegion0(G,0,{castle:(mv)=>mv.find(m=>m.id===c(0,C9)&&m.c==='oaths')});eq(G.pl[0].inf,1,'Influence');eq(G.council.oaths,[c(0,C9)],'only the new card remains');ok(G.pl[1].disc.includes(c(1,C6))&&G.pl[0].disc.includes(c(0,C7)),'others (even mine) discarded')});
test('Location Thornwild: +1 Influence and Journey with an Active card (Pathfinder to Discard, else Lost Pile)',()=>{const G=clashGame(2);winRegion0(G,1,{wilderness:mv=>mv.find(m=>m.id===c(0,C9)),siteBuy:done,sel:done});eq(G.pl[0].inf,1,'Influence');eq(G.pl[0].lore,1,'Captain has 1 Lore');ok(G.pl[0].disc.includes(c(0,C9)),'Pathfinder Captain goes to the Discard Pile')});
test('Journey with a non-Pathfinder card sends it to the Lost Pile',()=>{const G=clashGame(2);setHand(G,0,[c(0,F3)]);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='journey');if(TB.pending(G)&&TB.pending(G).kind==='siteBuy')T.answer(G,0,'done');ok(G.lost.includes(c(0,F3)),'Follower to Lost Pile');eq(G.pl[0].lore,1,'lore')});
test('Location Gleaning Meadow: claim the Kingdom\'s Favour; claiming your own Favour resets uses to 3',()=>{const G=clashGame(2);winRegion0(G,2,{harvest:mv=>mv.find(m=>m.yes)});eq(G.fav.h,0,'seat 0 holds it');eq(G.fav.u,3,'3 uses');const H=clashGame(2);H.fav.h=0;H.fav.u=1;winRegion0(H,2,{harvest:mv=>mv.find(m=>m.yes)});eq(H.fav.u,3,'reset')});
test('Location Moss Altar: move up to three Active/hand cards to the bottom of the deck in the chosen order',()=>{const G=clashGame(2);setHand(G,0,[c(0,F1),c(0,F2)]);winRegion0(G,4,{shrine:(mv)=>mv.find(m=>m.t==='sel'&&m.v===c(0,F1))||mv.find(m=>m.t==='sel'&&m.v===c(0,F2))||done(mv)});
  const d=G.pl[0].deck;ok(d[d.length-1]===c(0,F2)&&d[d.length-2]===c(0,F1),'F1 then F2 at the bottom: '+d.slice(-3))});
test('Location Ossuary: shuffle Discard, draw up to three, then may discard any number of hand cards',()=>{const G=clashGame(2);for(const id of [c(0,F1),c(0,F2),c(0,F3),c(0,F4)])T.put(G,id,'disc');winRegion0(G,5,{ossuary:done});eq(G.pl[0].hand.length,3,'drew three of the four');eq(G.pl[0].disc.length,1,'one remains');ok(true)});
test('Herald Reward: +1 Influence if your Herald is on the chosen Location, and steal 1 from each opponent Herald there',()=>{const G=clashGame(3);scene(G,{place:{0:[c(0,C9),null,null],1:[c(1,F1),null,null],2:[c(2,F2),null,null]},herald:{0:3,1:3,2:2}});
  G.reg[0].down=[c(0,C9),c(1,F1),c(2,F2)];G.reg[1].down=[];G.reg[2].down=[];G.pl[1].inf=3;G.pl[2].inf=3;
  // region 1 (Tablelands) is where Cairn Field (loc 3) is; make seat 0 win there instead
  const H=clashGame(3);H.reg[1].down=[c(0,C9),c(1,F1),c(2,F2)];H.pl[0].herald=3;H.pl[1].herald=3;H.pl[2].herald=2;H.pl[1].inf=3;H.pl[2].inf=3;T.put(H,c(0,C9),'down',1);T.put(H,c(1,F1),'down',1);T.put(H,c(2,F2),'down',1);
  runClashes(H,[1,0,2],{location:locPick(3)});eq(H.pl[0].inf,2+1+1,'2 (Cairn Field) + 1 herald + 1 stolen');eq(H.pl[1].inf,2,'victim lost 1');eq(H.pl[2].inf,3,'Herald elsewhere: untouched')});
test('Herald steal only takes what the victim has (never below 0)',()=>{const G=clashGame(2);G.reg[1].down=[];T.put(G,c(0,C9),'down',1);T.put(G,c(1,F1),'down',1);G.pl[0].herald=3;G.pl[1].herald=3;G.pl[1].inf=0;runClashes(G,[1,0,2],{location:locPick(3)});eq(G.pl[0].inf,3,'2+1 only');eq(G.pl[1].inf,0,'0')});
// ============================================================ AUTUMN, COUNCILS, JOURNEY, SITE OF POWER
test('Govern once in Autumn: a card with Votes goes into the Council of your choice',()=>{const G=game(2);setHand(G,0,[c(0,C6),c(0,F1)]);startAt(G,[['menus',{step:'autumn',i:0}]]);const mv=TB.moves(G,0);ok(!mv.some(m=>m.a==='govern'&&m.p.id===c(0,F1)),'0-vote follower cannot Govern');T.answer(G,0,m=>m.a==='govern'&&m.p.c==='secrets'&&m.p.id===c(0,C6));eq(G.council.secrets,[c(0,C6)],'in council');ok(!TB.moves(G,0).some(m=>m.a==='govern'),'only once per Autumn');eq(TB.votes(G,0,'secrets'),1,'1 vote')});
test('Council of Coin (Relics): remove cards with your Herald Reward to gain Influence equal to the Votes removed',()=>{const G=clashGame(2);T.put(G,c(0,C7),'council','relics');T.put(G,c(0,TRADER),'council','relics');G.reg[1].down=[];T.put(G,c(0,C9),'down',1);T.put(G,c(1,F1),'down',1);G.pl[0].herald=3;
  runClashes(G,[1,0,2],{location:locPick(3),relics:(mv)=>mv.find(m=>m.t==='sel'&&m.v===c(0,TRADER))||done(mv)});eq(G.pl[0].inf,2+1+2,'location 2 + herald 1 + 2 votes of the Trader');ok(G.pl[0].disc.includes(c(0,TRADER)),'removed card to Discard');ok(G.council.relics.includes(c(0,C7)),'other stays')});
test('Council of Whispers (Secrets): markers = Votes; 4 markers on a Location claim its reward ignoring Influence',()=>{const G=game(2);T.put(G,c(0,C6),'council','secrets');T.put(G,c(0,C7),'council','secrets');T.put(G,c(0,C8),'council','secrets');T.put(G,c(0,C9),'council','secrets');
  startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='council:secrets');for(let i=0;i<4;i++)T.answer(G,0,'l3');eq(G.pl[0].inf,0,'Cairn Field with its Influence ignored: nothing');eq(G.pl[0].mk[3],0,'markers removed');
  const H=game(2);T.put(H,c(0,C6),'council','secrets');T.put(H,c(0,C7),'council','secrets');H.pl[0].mk[0]=2;startAt(H,[['menus',{step:'autumn',i:0}]]);T.answer(H,0,m=>m.a==='council:secrets');T.answer(H,0,'l0');T.answer(H,0,'l0');ok(TB.pending(H).kind==='castle'||H.pl[0].mk[0]===0,'4 markers on the Castle claim its text')});
test('Council of Pledges (Oaths): return Supporters = Votes, +1 for strictly the most Votes',()=>{const G=game(2);T.put(G,c(0,C6),'council','oaths');G.pl[0].supp.b=0;G.pl[0].supp.l=5;startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='council:oaths');eq(G.pl[0].supp.b,2,'1 vote + 1 for strictly most');
  const H=game(2);T.put(H,c(0,C6),'council','oaths');T.put(H,c(1,C6),'council','oaths');H.pl[0].supp.b=0;H.pl[0].supp.l=5;startAt(H,[['menus',{step:'autumn',i:0}]]);T.answer(H,0,m=>m.a==='council:oaths');eq(H.pl[0].supp.b,1,'tied for most: no bonus')});
test('Journey: Lore = icons; spend on Site of Power cards; unspent Lore is kept for next time',()=>{const G=game(2);setHand(G,0,[c(0,TRADER),c(0,C6)]);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='journey'&&m.p.id===c(0,TRADER));eq(TB.pending(G).kind,'siteBuy','offer to spend');eq(G.pl[0].lore,2,'2 Lore');
  T.answer(G,0,'s:'+c(0,A1));T.answer(G,0,'done');ok(G.pl[0].hand.includes(c(0,A1)),'Hand of the Regent bought (cost 2)');eq(G.pl[0].lore,0,'paid');ok(G.lost.includes(c(0,TRADER)),'Trader lost');
  const H=game(2);setHand(H,0,[c(0,C6),c(0,F1)]);startAt(H,[['menus',{step:'autumn',i:0}]]);T.answer(H,0,m=>m.a==='journey'&&m.p.id===c(0,F1));ok(!TB.pending(H)||TB.pending(H).kind!=='siteBuy','1 Lore cannot buy anything: no prompt');eq(H.pl[0].lore,1,'kept')});
test('Site of Power: Advanced card to hand (top of deck if the hand is full); HQ card to Supply',()=>{const G=game(2);const P=G.pl[0];P.lore=5;P.hs=6;I.setG(G);startAt(G,[['siteBuy',{seat:0}]]);T.answer(G,0,'s:'+c(0,HQ));T.answer(G,0,'s:'+c(0,A1));T.answer(G,0,'done');ok(P.hq.includes(c(0,HQ)),'HQ in Supply');eq(P.hand.length,6,'hand full');eq(P.deck[0],c(0,A1),'advanced card on top of deck since hand was full')});
test('Site of Power empty at game end: 1 Influence per 2 Lore',()=>{const G=game(2,null,{length:'short'});G.pl[0].site=[];for(const id of [14,15,16,17,18])T.put(G,c(0,id),'hand');G.pl[0].lore=5;G.pl[0].inf=3;G.pl[1].lore=5;G.pl[1].inf=3;G.round=G.rounds;startAt(G,[['winter']]);
  eq(G.phase,'over','over');eq(G.pl[0].inf,5,'3 + floor(5/2)');eq(G.pl[1].inf,3,'site not empty: no conversion')});
// ============================================================ WINTER
test('Winter cleanup: Heralds home, Supporters to Lost Pile, Active cards to Discard, tokens decay',()=>{const G=game(2);G.pl[0].herald=3;G.pl[0].supp.b=0;G.pl[0].supp.r=[2,1,0];G.pl[0].supp.x=[0,0,2];
  T.put(G,c(0,C6),'up',0);T.put(G,c(0,C7),'up',1);G.cmod[c(0,C7)]={tok:1};startAt(G,[['winter']]);eq(G.pl[0].herald,-1,'herald home');eq(G.pl[0].supp.l,5,'supporters lost');ok(G.pl[0].disc.includes(c(0,C6)),'active to discard');eq(G.reg[1].up,[c(0,C7)],'token card stays');ok(!G.cmod[c(0,C7)],'token removed');eq(G.round,2,'next round');eq(TB.pending(G).kind,'bid','next round begins with bids')});
test('Doctrine of Masonry: Supporters count 2 Strength this Round and survive Winter',()=>{const G=clashGame(2);scene(G,{place:{0:[c(0,F1),null,null],1:[c(1,C6),null,null]},supp:{0:[2,0,0]}});G.rm.masonry.push(0);runClashes(G,[0,1,2],{location:locPick(0)});ok(/P0 5, P1 6/.test(G.log.map(l=>l.t).join('\n')),'1 + 2*2');
  startAt(G,[['winter']]);eq(G.pl[0].supp.r[0],2,'still on the Map');eq(G.pl[0].supp.l,0,'not lost')});
test('Deploy puts a card Active with Influence tokens; it survives a Winter, then is discarded',()=>{const G=game(2);setHand(G,0,[c(0,WM)]);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='cmd:deploy'&&m.p.r===2);eq(G.reg[2].up,[c(0,WM)],'Active');startAt(G,[['winter']]);eq(G.reg[2].up,[c(0,WM)],'stays after first Winter');eq(G.cmod[c(0,WM)]&&G.cmod[c(0,WM)].tok||0,0,'token gone');
  G.round=1;startAt(G,[['winter']]);ok(G.pl[0].disc.includes(c(0,WM)),'discarded the next Winter')});
test('Rally (self) returns the Active Heir to hand in Autumn',()=>{const G=game(2);setHand(G,0,[]);T.put(G,c(0,HEIR),'up',1);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,m=>m.a==='cmd:rally');ok(G.pl[0].hand.includes(c(0,HEIR)),'back in hand');eq(G.reg[1].up.length,0,'no longer Active')});
// ============================================================ FAVOUR, TIE-BREAKS, GAME END
test('Kingdom\'s Favour: each use rotates the disc; the third use returns it to the Harvest Field',()=>{const G=game(2);G.fav.h=0;G.fav.u=3;startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,m=>m.a==='fav:spring');T.answer(G,0,'inf');eq(G.fav.u,2,'rotated');eq(G.pl[0].inf,1,'Sovereign Mandate: +1 Influence');
  ok(!TB.moves(G,0).some(m=>m.a==='fav:spring'),'only once per Round');G.used={};G.fav.u=1;startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,m=>m.a==='fav:spring');T.answer(G,0,'inf');eq(G.fav.h,-1,'back on the Harvest Field');eq(G.fav.u,3,'reset')});
test('Winner: most Influence; tie -> holder of the Favour; then higher on the Order Track',()=>{const G=game(3,null,{order:[2,0,1],length:'short'});G.round=G.rounds;G.pl[0].inf=5;G.pl[1].inf=5;G.pl[2].inf=3;G.fav.h=1;startAt(G,[['winter']]);eq(G.over.winner,1,'Favour breaks the tie');eq(G.over.tieBreak,'favour','reason');
  const H=game(3,null,{order:[2,0,1],length:'short'});H.round=H.rounds;H.pl[0].inf=5;H.pl[1].inf=5;H.pl[2].inf=3;startAt(H,[['winter']]);eq(H.over.winner,0,'seat 0 is higher on the Order Track than seat 1');eq(H.over.tieBreak,'order','reason')});
test('the game ends after the last Round of the chosen length (short game)',()=>{const G=game(2,null,{length:'short'});G.round=4;startAt(G,[['winter']]);eq(G.phase,'over','over after round 4');ok(TB.pending(G)===null,'nothing pending')});
const logHas=(G,re)=>re.test(G.log.map(l=>l.t).join('\n'));
const act=(name,pred)=>m=>m.a===name&&(!pred||pred(m));
// ============================================================ THE GILDED COURT (nobility)
test('Gilded Court: Counting House gives +1 Vote to cards with no printed Votes; its Action takes a Captain back and/or 1 Influence',()=>{const G=game(2,null,{order:[1,0]});setHand(G,0,[c(0,F1)]);startAt(G,[['menus',{step:'autumn',i:1}]]);ok(!TB.moves(G,0).some(m=>m.a==='govern'),'no Votes yet');
  T.put(G,c(0,HQ),'hq');T.put(G,c(0,C7),'disc');startAt(G,[['menus',{step:'autumn',i:1}]]);ok(TB.moves(G,0).some(m=>m.a==='govern'&&m.p.id===c(0,F1)),'Follower may Govern now');
  T.answer(G,0,act('hq:nob_hq',m=>m.p.cap===c(0,C7)&&m.p.inf===1));ok(G.pl[0].hand.includes(c(0,C7)),'Captain back to hand');eq(G.pl[0].inf,1,'both because not first on the Order Track');
  const H=game(2,null,{order:[0,1]});T.put(H,c(0,HQ),'hq');T.put(H,c(0,C7),'disc');startAt(H,[['menus',{step:'autumn',i:0}]]);ok(!TB.moves(H,0).some(m=>m.a==='hq:nob_hq'&&m.p.cap>=0&&m.p.inf===1),'first on the track: only one of the two')});
test('Gilded Court: Martial Writ locks a Region (no Ambush/Flank into it by rivals during its first Clash)',()=>{const G=game(2,['nobility','clans'],{order:[0,1]});T.put(G,c(0,WM),'up',0);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('t:nob_t2',m=>m.p.r===0));eq(G.rm.lock[0],0,'locked');eq(G.pl[0].tac[1].mk,1,'one marker used');ok(!G.pl[0].tac[1].ex,'not exhausted yet');
  const H=game(2,['nobility','clans'],{order:[0,1]});H.rm.lock[0]=0;for(const P of H.pl)setHand(H,P.seat,[]);T.put(H,c(1,RUSE),'down',0);T.put(H,c(1,CAV),'down',1);T.put(H,c(0,F1),'down',0);T.put(H,c(0,F1+1),'down',1);T.put(H,c(1,F1),'hand');
  startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');eq(TB.pending(H).kind,'menu','day');const mv=TB.moves(H,1);ok(!mv.some(m=>m.a==='cmd:ambush'),'no Ambush into the locked Region');
  const J=game(2,['nobility','clans'],{order:[0,1]});J.rm.lock[0]=0;for(const P of J.pl)setHand(J,P.seat,[]);T.put(J,c(1,CAV),'down',1);T.put(J,c(0,F1),'down',1);startAt(J,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(J,1,'o120');
  const f=TB.moves(J,1).find(m=>m.a==='cmd:flank');ok(f,'flank offered');TB.apply(J,f);eq(TB.moves(J,1).map(m=>m.r).sort(),[2],'only the unlocked Region 2 (Region 0 is locked)')});
test('Gilded Court: Inquest discards rivals\' cards in a Council, then moves your Council cards to the top of your deck for Lore',()=>{const G=game(2);T.put(G,c(1,C6),'council','relics');T.put(G,c(0,C7),'council','secrets');startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('t:nob_t4',m=>m.p.c==='relics'));
  ok(G.pl[1].disc.includes(c(1,C6)),'rival card discarded');eq(TB.pending(G).kind,'inquest','select own cards');T.answer(G,0,'s:'+c(0,C7));T.answer(G,0,'done');eq(G.pl[0].deck[0],c(0,C7),'on top of deck');eq(G.pl[0].lore,1,'1 Lore per card')});
test('Gilded Court: Sovereign Mandate makes Heirs Invulnerable for the Round',()=>{const G=game(2,['nobility','clans']);for(const P of G.pl)setHand(G,P.seat,[]);G.fav.h=0;startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('fav:spring'));T.answer(G,0,'inv');
  T.put(G,c(0,HEIR),'down',0);T.put(G,c(1,AGENT),'down',0);T.put(G,c(1,C6),'down',0);runClashes(G,[0,1,2],{});ok(!G.lost.includes(c(0,HEIR))&&!G.pl[0].disc.includes(c(0,HEIR)),'Heir survived Deadly');ok(G.lost.includes(c(1,C6))||true,'ok')});
test('Hand of the Regent (and its siblings) treat the occupier\'s Strength as 0 when stealing',()=>{const G=bidScene([[c(0,A1),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['nobility','clans']});
  T.giveKC(G,1,5,c(1,RUSE),0);T.giveKC(G,1,13,c(1,C9),1);// Sentinel Towers gives occupiers +5: occupier of kc13 is 9+5=14
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext']]);T.answer(G,0,'b:'+c(0,A1));T.answer(G,1,'b:'+c(1,C8));T.answer(G,0,'no');const mv=TB.moves(G,1);T.answer(G,1,'ret');ok(TB.moves(G,0).some(m=>m.t==='steal'&&m.kc===13),'champion (11) steals a card whose occupier counts as 0')});
test('Gilded Court: Hall of Seats moves between Councils; Drowned Matriarch Governs from Lost/Discard when acquired; Ivory Rampart grows a token with 2 Supporters',()=>{const G=game(2);T.put(G,c(0,A2),'council','relics');startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('card:hallseats',m=>m.p.c==='oaths'));eq(G.council.oaths,[c(0,A2)],'moved');
  const H=game(2);H.pl[0].lore=4;T.put(H,c(0,C7),'lost');T.put(H,c(0,C8),'disc');startAt(H,[['siteBuy',{seat:0}]]);T.answer(H,0,'s:'+c(0,A3));T.answer(H,0,'done');eq(TB.pending(H).kind,'govern3','Govern prompt');T.answer(H,0,'c'+c(0,C7));T.answer(H,0,'c'+c(0,C8));eq(H.council.relics.concat(H.council.secrets).sort(),[c(0,C7),c(0,C8)].sort(),'two Councils filled');
  const J=game(2);T.put(J,c(0,A4),'up',1);J.pl[0].supp.r[1]=2;J.pl[0].supp.b=3;startAt(J,[['menus',{step:'autumn',i:0}]]);T.answer(J,0,act('card:rampart'));eq(J.cmod[c(0,A4)].tok,1,'token')});
// ============================================================ THE HEATHBOUND CLANS
test('Heathbound Clans: Skyrunners earns 1 Influence when you win in its Region (before rewards)',()=>{const G=game(2,['clans','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A3),'down',0);T.put(G,c(1,F1),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});eq(G.pl[0].inf,2,'1 Skyrunners + 1 Spire Court')});
test('Heathbound Clans: Torchbearer Raiders Flank can take Supporters along; it also has Deadly',()=>{const G=game(2,['clans','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A2),'down',0);G.pl[0].supp.b=2;G.pl[0].supp.r[0]=3;T.put(G,c(1,F1),'down',0);
  ok(TB.info?true:true,'');startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('cmd:flank'));T.answer(G,0,'r1');eq(TB.pending(G).kind,'flankSupp','supporters question');T.answer(G,0,'n3');eq(G.pl[0].supp.r,[0,3,0],'moved');eq(TB.cardInfo(G,c(0,A2)).commands.sort(),['deadly','flank'],'commands')});
test('Heathbound Clans: Roving Mission gives Traders Flank and lets removed Council cards return to hand',()=>{const G=game(2,['clans','nobility']);T.put(G,c(0,17),'hq');ok(TB.cardInfo(G,c(0,TRADER)).commands.includes('flank'),'Trader flanks');
  T.put(G,c(0,C7),'council','oaths');setHand(G,0,[]);T.run(G,[]);I.setG(G);I.leaveCouncil([c(0,C7)]);I.flow();eq(TB.pending(G).kind,'councilOut','offered');T.answer(G,0,'hand');ok(G.pl[0].hand.includes(c(0,C7)),'back in hand')});
test('Heathbound Clans: Haven Quay makes all your cards Resilient and returns Supporters from the Lost Pile',()=>{const G=game(2,['clans','uprising']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,18),'hq');T.put(G,c(0,C9),'down',0);T.put(G,c(1,AGENT),'down',0);runClashes(G,[0,1,2],{});ok(G.pl[0].disc.includes(c(0,C9)),'Eliminated Captain goes to Discard (Resilient)');
  const H=game(2,['clans','uprising']);T.put(H,c(0,18),'hq');H.pl[0].supp.b=2;H.pl[0].supp.l=3;startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('hq:cln_hq2',m=>m.p.r===2));eq(H.pl[0].supp.r[2],2,'two moved');eq(H.pl[0].supp.l,1,'one left in the Lost Pile')});
test('Heathbound Clans: Doctrine of Tempests (marker order; Supporter and Active-card bonuses)',()=>{const G=game(2,['clans','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('t:cln_t1'));eq(G.rm.tempests,0,'set');
  G.pl[0].supp.b=2;G.pl[0].supp.r[0]=3;T.put(G,c(0,C9),'down',0);T.put(G,c(0,C8),'down',0);T.put(G,c(1,F1),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});ok(logHas(G,/Doctrine of Tempests: most Supporters/)&&logHas(G,/most Active cards/),'both bonuses');eq(G.pl[0].lore>=1,true,'lore')});
test('Heathbound Clans: Open Waterways gives Flank for the Round and spends a marker',()=>{const G=game(2,['clans','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,C9),'down',0);T.put(G,c(1,F1),'down',0);startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('t:cln_t2'));eq(G.pl[0].tac[1].mk,2,'marker spent');ok(TB.cardInfo(G,c(0,C9)).commands.includes('flank'),'captain flanks');ok(TB.moves(G,0).some(m=>m.a==='cmd:flank'),'flank available')});
test('Heathbound Clans: Riverbank Raiders takes a rival\'s occupied Kingdom Card and occupies it with a hand card',()=>{const G=game(2,['clans','nobility']);T.giveKC(G,1,13,c(1,F3),0);setHand(G,0,[c(0,F4),c(0,C6)]);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('t:cln_t3'));T.answer(G,0,'c'+c(0,F4));eq(G.pl[0].ks[0].kc,13,'taken');ok(G.pl[1].hand.includes(c(1,F3))||G.pl[1].deck[0]===c(1,F3),'occupier returned (top of deck when the hand is full)');eq(G.pl[1].ks[0],null,'gone from rival')});
test('Heathbound Clans: Brine-Hardened returns Active/Discard cards to hand up to hand size',()=>{const G=game(2,['clans','nobility']);setHand(G,0,[c(0,F1)]);T.put(G,c(0,C6),'up',0);T.put(G,c(0,C7),'disc');startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('t:cln_t4'));T.answer(G,0,'s:'+c(0,C6));T.answer(G,0,'s:'+c(0,C7));T.answer(G,0,'done');ok(G.pl[0].hand.includes(c(0,C6))&&G.pl[0].hand.includes(c(0,C7)),'both back')});
test('Heathbound Clans: Tide-Seer\'s Call moves your Herald and Supporters into the current Region (Favour, Day)',()=>{const G=game(2,['clans','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);G.fav.h=0;G.pl[0].supp.b=2;G.pl[0].supp.r[1]=2;G.pl[0].herald=5;T.put(G,c(0,C9),'down',0);T.put(G,c(1,F1),'down',0);
  startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('fav:day'));T.answer(G,0,'l0');T.answer(G,0,'r1');T.answer(G,0,'r1');eq(G.pl[0].herald,0,'herald moved');eq(G.pl[0].supp.r,[2,0,0],'supporters moved');eq(G.fav.u,2,'rotated')});
// ============================================================ THE LANTERN RISING (uprising)
test('Lantern Rising: Cellar Fuse eliminates rival Heirs and Captains, then 1 Influence or 1 Lore',()=>{const G=game(2,['uprising','clans']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A2),'down',0);T.put(G,c(1,HEIR),'down',0);T.put(G,c(1,C6),'down',0);T.put(G,c(1,F4),'down',0);
  runClashes(G,[0,1,2],{cellar:mv=>mv.find(m=>m.inf)});ok(G.pl[1].disc.includes(c(1,HEIR)),'Resilient Heir to Discard');ok(G.lost.includes(c(1,C6)),'Captain to Lost Pile');ok(!G.lost.includes(c(1,F4)),'Follower untouched');ok(G.pl[0].inf>=1,'+Influence (and Region reward)')});
test('Lantern Rising: Hedge Skirmishers blank rivals\' printed information (but it dies to an Heir)',()=>{const G=game(2,['uprising','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A3),'down',0);T.put(G,c(1,AGENT),'down',0);startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');
  ok(!TB.cardInfo(G,c(1,AGENT)).commands.includes('deadly'),'Deadly is blanked');pump(G,{menu:done,location:locPick(0)});ok(!G.lost.includes(c(0,A3)),'Hedge survives: no Heir present');
  const H=game(2,['uprising','nobility']);for(const P of H.pl)setHand(H,P.seat,[]);T.put(H,c(0,A3),'down',0);T.put(H,c(1,HEIR),'down',0);runClashes(H,[0,1,2],{});ok(H.pl[0].disc.includes(c(0,A3)),'drawback: eliminated by the Heir (Resilient: Discard)')});
test('Lantern Rising: Smugglers\' Hollow adds a third Kingdom Card space used only by its own action',()=>{const G=game(2,['uprising','clans']);T.put(G,c(0,17),'hq');setHand(G,0,[c(0,C6),c(0,F1)]);const kc=G.road.find(n=>KCok(n));startAt(G,[['menus',{step:'autumn',i:0}]]);
  const o=TB.moves(G,0).filter(m=>m.a==='hq:upr_hq1');ok(o.length>0,'action offered');T.answer(G,0,m=>m.a==='hq:upr_hq1');T.answer(G,0,'c'+c(0,C6));eq(G.pl[0].ks[2]&&G.pl[0].ks[2].occ,c(0,C6),'in the Hollow slot');eq(TB.invariants(G),[],'inv')});
function KCok(n){return n&&TB.kingdomInfo(n).place==='board'}
test('Lantern Rising: Underground Ring adds a Council marker (1 Vote, max 2 per Council) per Kingdom Card acquired',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['uprising','clans']});T.put(G,c(0,18),'hq');T.road(G,3,1);
  startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');T.answer(G,0,'gr:3');eq(G.cmk.relics[0][0],1,'marker on the Council of Coin (suit of Roaming Company)');eq(TB.votes(G,0,'relics'),1,'1 Vote')});
test('Lantern Rising: Back Lanes gives Heirs Deadly and pays 1 Influence + 1 Lore when your cards eliminate',()=>{const G=game(2,['uprising','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);G.rm.lanes.push(0);T.put(G,c(0,HEIR),'down',0);T.put(G,c(1,C9),'down',0);runClashes(G,[0,1,2],{siteBuy:done,location:locPick(0)});ok(G.lost.includes(c(1,C9)),'captain eliminated by the Heir');eq(G.pl[0].lore,1,'1 Lore');ok(G.pl[0].inf>=2,'Influence from Back Lanes + Region')});
test('Lantern Rising: Hideouts gives Retreat until the end of the Clash (3 markers)',()=>{const G=game(2,['uprising','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,C9),'down',0);T.put(G,c(1,F1),'down',0);startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('t:upr_t2'));eq(G.pl[0].tac[1].mk,2,'marker');T.answer(G,0,act('cmd:retreat'));T.answer(G,0,'s:'+c(0,C9));ok(G.pl[0].hand.includes(c(0,C9)),'retreated')});
test('Lantern Rising: Midnight Pressure makes each rival discard a card per Kingdom Card you occupy',()=>{const G=game(2,['uprising','nobility']);T.giveKC(G,0,13,c(0,F1),0);T.giveKC(G,0,14,c(0,F2),1);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('t:upr_t3'));eq(TB.pending(G).seats,[1],'rival chooses');eq(TB.pending(G).kind,'discardPick','discard');T.answer(G,1,m=>m.t==='sel');T.answer(G,1,m=>m.t==='sel');eq(G.pl[1].hand.length,4,'discarded 2')});
test('Lantern Rising: Forged Dispatches swaps two of a rival\'s face-down cards; Watchers in the Wall peeks and swaps',()=>{const G=game(2,['uprising','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(1,C6),'down',0);T.put(G,c(1,C7),'down',1);T.put(G,c(1,C8),'down',2);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('t:upr_t4'));T.answer(G,0,'s01');eq(G.reg[0].down,[c(1,C7)],'swapped');eq(G.reg[1].down,[c(1,C6)],'swapped');
  const H=game(2,['uprising','nobility']);for(const P of H.pl)setHand(H,P.seat,[c(P.seat,C9)]);T.put(H,c(0,F1),'down',0);T.put(H,c(1,C6),'down',1);H.fav.h=0;startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('fav:spring'));T.answer(H,0,'r1');ok(H.peek[0].includes(c(1,C6)),'peeked');T.answer(H,0,'h0'+c(0,C9));eq(H.reg[0].down,[c(0,C9)],'swapped with hand card');ok(H.pl[0].hand.includes(c(0,F1)),'old face-down card in hand')});
// ============================================================ THE PALE CHOIR (gathering)
test('Pale Choir: Rite of the Watcher makes the LOWEST Strength above 0 win',()=>{const G=game(2,['gathering','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A4),'down',0);T.put(G,c(1,C9),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});ok(logHas(G,/lowest Strength above 0/),'rule applied');eq(G.pl[0].inf,1,'3 beats 9 by being lowest')});
test('Pale Choir: Rite of the Fang burns a Lost Pile card and adds its Strength, Traits and Commands',()=>{const G=game(2,['gathering','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,A3),'down',0);T.put(G,c(1,C9),'down',0);T.put(G,c(0,AGENT),'lost');startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('card:fang'));ok(G.burned.includes(c(0,AGENT)),'burned');
  eq(TB.cardInfo(G,c(0,A3)).strength,10,'5 + 5');ok(TB.cardInfo(G,c(0,A3)).commands.includes('deadly'),'gains Deadly')});
test('Pale Choir: Whisperer of Names puts markers on Councils that count as Votes; may leave to the Lost Pile',()=>{const G=game(2,['gathering','nobility']);T.put(G,c(0,A2),'council','secrets');startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('card:whisperer',m=>m.p.c==='oaths'));eq(G.cmk.oaths[0][1],1,'marker');eq(TB.votes(G,0,'oaths'),1,'counts as a Vote');T.run(G,[]);I.setG(G);I.leaveCouncil([c(0,A2)]);I.flow();T.answer(G,0,'lost');ok(G.lost.includes(c(0,A2)),'moved to the Lost Pile')});
test('Pale Choir: Threshold Gate has 3 markers and gives Ambush (optionally from the Discard Pile)',()=>{const G=game(2,['gathering','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);
  const H=game(2,['gathering','nobility']);for(const P of H.pl)setHand(H,P.seat,[]);H.pl[0].lore=2;T.put(H,c(0,18),'site');H.pl[0].site=[c(0,18)];startAt(H,[['siteBuy',{seat:0}]]);T.answer(H,0,'s:'+c(0,18));eq(H.pl[0].gate,3,'3');
  T.put(H,c(0,C9),'down',0);T.put(H,c(1,F1),'down',0);T.put(H,c(0,C7),'disc');startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');T.answer(H,0,act('hq:gth_hq'));T.answer(H,0,'yes');eq(H.pl[0].gate,1,'two markers spent');T.answer(H,0,act('cmd:ambush'));T.answer(H,0,'c'+c(0,C7));ok(!H.pl[0].disc.includes(c(0,C7)),'ambushed from the Discard Pile')});
test('Pale Choir: Doctrine of Starlight, Lamp-Line, Offering, Moon-Herald\'s Boon, Night Gleaners',()=>{const G=game(2,['gathering','nobility']);for(const P of G.pl)setHand(G,P.seat,[]);G.pl[0].supp.b=3;G.pl[0].supp.r[0]=2;T.put(G,c(0,C9),'down',0);T.put(G,c(1,F1),'down',0);T.put(G,c(0,C8),'lost');startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('t:gth_t1'));T.answer(G,0,'c'+c(0,C8));ok(G.reg[0].up.includes(c(0,C8)),'card returned from the Lost Pile to the Region');eq(G.pl[0].supp.l,2,'two Supporters lost');
  const H=game(2,['gathering','nobility']);T.put(H,c(0,C9),'up',0);T.put(H,c(0,C8),'up',1);H.clash={r:0,parts:[0],cards:{0:[]},added:[],used:{},bonus:{},n:1};startAt(H,[['menus',{step:'day',i:0,list:[0]}]]);T.answer(H,0,act('t:gth_t3'));eq(H.reg[0].up,[c(0,C8)],'swapped');eq(H.reg[1].up,[c(0,C9)],'swapped');
  const J=game(2,['gathering','nobility']);T.put(J,c(0,C9),'up',1);T.put(J,c(0,F1),'disc');T.put(J,c(0,F2),'disc');startAt(J,[['menus',{step:'autumn',i:0}]]);T.answer(J,0,act('t:gth_t4'));T.answer(J,0,'s:'+c(0,C9));T.answer(J,0,'s:'+c(0,F1));T.answer(J,0,'done');ok(J.lost.includes(c(0,C9))&&J.lost.includes(c(0,F1)),'both to the Lost Pile');
  const K=game(2,['gathering','nobility']);setHand(K,0,[]);K.fav.h=0;K.pl[0].herald=3;T.put(K,c(0,C9),'up',1);startAt(K,[['menus',{step:'autumn',i:0}]]);T.answer(K,0,act('fav:autumn'));T.answer(K,0,'c'+c(0,C9));ok(K.pl[0].hand.includes(c(0,C9)),'Active card from the Herald\'s Region back to hand');
  const L=game(2,['gathering','nobility']);setHand(L,0,[c(0,F1),c(0,F2)]);L.kdisc.push(...L.kdeck.splice(0,6));startAt(L,[['menus',{step:'spring',i:0}]]);T.answer(L,0,act('t:gth_t2'));const q=TB.pending(L);eq(q.kind,'gleaners','five cards shown');T.answer(L,0,m=>m.kc);T.answer(L,0,'c'+c(0,F1));ok(L.pl[0].ks[0],'acquired');eq(TB.invariants(L),[],'inv')});
// ============================================================ KINGDOM CARDS (selection; cover.js forces every one)
test('Kingdom Card: Frozen Bastion halves rivals\' total Strength in its Region; Feast of Thorns blanks printed info; both are discarded in Winter',()=>{const G=game(2);for(const P of G.pl)setHand(G,P.seat,[]);G.reg[0].kc.push({n:43,o:0});T.kcRemove(G,43);G.reg[0].kc.push({n:43,o:0});T.put(G,c(0,C6),'down',0);T.put(G,c(1,C9),'down',0);T.put(G,c(1,C8),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});ok(logHas(G,/P0 6, P1 9/),'17 halved rounded up = 9');
  G.round=1;startAt(G,[['winter']]);ok(G.kdisc.includes(43),'discarded in Winter');eq(G.reg[0].kc.length,0,'gone from the Region');
  const H=game(2);for(const P of H.pl)setHand(H,P.seat,[]);T.kcRemove(H,49);H.reg[0].kc.push({n:49,o:0});T.put(H,c(1,AGENT),'down',0);T.put(H,c(0,F1),'down',0);startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');ok(!TB.cardInfo(H,c(1,AGENT)).commands.includes('deadly'),'rival Agent\'s Deadly blanked by Feast of Thorns')});
test('Kingdom Card: Broken Gnomon skips Day and Night steps in its Region; Blade That Dreamed adds +5 and discards occupier',()=>{const G=game(2);for(const P of G.pl)setHand(G,P.seat,[]);T.giveKC(G,0,47,c(0,F1),0);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('kc47',m=>m.p.r===0));ok(G.pl[0].disc.includes(c(0,F1)),'occupier discarded');
  T.put(G,c(0,AGENT),'down',0);T.put(G,c(1,F2),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});ok(!G.lost.includes(c(0,AGENT))&&logHas(G,/skipped/),'no Night step: the Agent does not eliminate itself');
  const H=game(2);for(const P of H.pl)setHand(H,P.seat,[]);T.giveKC(H,0,46,c(0,F3),0);T.put(H,c(0,F1),'down',0);T.put(H,c(1,F4),'down',0);startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');T.answer(H,0,act('kc46'));ok(H.pl[0].disc.includes(c(0,F3))&&H.kdisc.includes(46),'both discarded');pump(H,{menu:done,location:locPick(0)});ok(logHas(H,/P0 6, P1 4/),'1 + 5 vs 4')});
test('Kingdom Card: Dead King\'s Lance gives Deadly; Aegis gives Invulnerable; Contraband Gap/Hunting-Horn give Retreat/Ambush',()=>{const G=game(2);for(const P of G.pl)setHand(G,P.seat,[]);T.giveKC(G,0,50,c(0,F3),0);T.put(G,c(0,C6),'down',0);T.put(G,c(1,C9),'down',0);startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('kc50'));pump(G,{menu:done,location:locPick(0)});ok(G.lost.includes(c(1,C9)),'Lance made the Captain Deadly');
  const H=game(2);for(const P of H.pl)setHand(H,P.seat,[]);T.giveKC(H,1,51,c(1,F3),0);T.put(H,c(0,AGENT),'down',0);T.put(H,c(1,C9),'down',0);startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');T.answer(H,1,act('kc51'));pump(H,{menu:done,location:locPick(0)});ok(!H.lost.includes(c(1,C9)),'Aegis protects from Deadly')});
test('Kingdom Card: Trade League Hall pays its owner whenever any player claims that Location',()=>{const G=game(2);for(const P of G.pl)setHand(G,P.seat,[]);G.loc[3].kc.push({n:11,o:1});T.kcRemove(G,11);G.loc[3].kc.push({n:11,o:1});winAt(G,3);eq(G.pl[0].inf,2,'winner gets Cairn Field');eq(G.pl[1].inf,1,'Hall owner gets 1')});
test('Kingdom Cards: Seal-Ring pays when you win with an Active Heir; Faraway Hermitage / Statue Wrights / Buried Hall / Crystal Warrens',()=>{const G=game(2);for(const P of G.pl)setHand(G,P.seat,[]);T.giveKC(G,0,17,c(0,F1),0);T.put(G,c(0,HEIR),'down',0);T.put(G,c(1,F1),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});eq(G.pl[0].inf,2,'Region 1 + Seal-Ring 1');
  const H=game(2);T.giveKC(H,0,13,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('kc13'));eq(H.pl[0].inf,1,'no Lore: gain 1 Influence');H.used={};T.answer(H,0,'done');startAt(H,[['menus',{step:'spring',i:0}]]);H.pl[0].lore=3;T.answer(H,0,act('kc13'));eq(H.pl[0].lore,4,'otherwise 1 Lore')});

// ============================================================ MORE KINGDOM CARD CHECKS
function bidTake(G,kc,seat){ // seat 0 takes road card kc (placed at index 3) with its bid; others return theirs
  T.road(G,3,kc);startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);for(const s of TB.pending(G).seats.slice())T.answer(G,s,mv=>mv.t==='bid')}
test('Veiled Patron (bold): discard the bid, keep it in Supply; it absorbs one Attrition. Lighthouse acquires the cheapest Site card free.',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['clans','uprising']});
  T.road(G,3,4);startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');T.answer(G,0,'gr:3');ok(G.pl[0].sup.includes(4),'in Supply');ok(G.pl[0].disc.includes(c(0,C6)),'bid discarded');eq(G.pl[0].ks[0],null,'no space used');
  const H=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['clans','uprising']});T.road(H,3,7);startAt(H,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext'],['bidEnd']]);T.answer(H,0,'b:'+c(0,C6));T.answer(H,1,'b:'+c(1,C8));T.answer(H,1,'ret');T.answer(H,0,'gr:3');
  const q=TB.pending(H);ok(q&&q.kind==='lighthouse','two cheapest (cost 2): choose');T.answer(H,0,m=>m.id!=null);ok(H.pl[0].hand.some(id=>[14,15,16,17,18].includes(id%100)),'a Site card came to hand for free');ok(H.kdisc.includes(7),'Lighthouse discarded')});
test('Dead King\'s Gaze lets its holder take from the top two Kingdom Deck cards',()=>{const G=bidScene([[c(0,C6),c(0,F1),c(0,F2),c(0,F3),c(0,F4),c(0,RUSE)],[c(1,C8),c(1,F1),c(1,F2),c(1,F3),c(1,F4),c(1,RUSE)]],{facs:['clans','uprising']});T.kcRemove(G,34);G.pl[0].sup.push(34);startAt(G,[['bidPlace'],['bidReveal'],['bidOrder'],['bidNext']]);T.answer(G,0,'b:'+c(0,C6));T.answer(G,1,'b:'+c(1,C8));T.answer(G,1,'ret');const mv=TB.moves(G,0);ok(mv.some(m=>m.dk===0)&&mv.some(m=>m.dk===1),'two extra options');
  const top=G.kdeck[0];T.answer(G,0,'dk:0');eq(G.pl[0].ks[0].kc,top,'took the top card')});
test('Wax Pretender copies a rival\'s Favour without rotating the disc; Honour Guard allows the Favour without the disc',()=>{const G=game(2,['clans','nobility']);T.giveKC(G,0,28,c(0,F1),0);G.fav.h=1;G.fav.u=3;startAt(G,[['menus',{step:'spring',i:0}]]);const m=TB.moves(G,0).find(x=>x.a==='fav:spring'&&x.p.mode==='wax');ok(m,'copy offered');TB.apply(G,m);T.answer(G,0,'inf');eq(G.pl[0].inf,1,'Sovereign Mandate used');eq(G.fav.u,3,'disc not rotated');
  const H=game(2,['nobility','clans']);T.giveKC(H,0,15,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,x=>x.a==='fav:spring'&&x.p.mode==='honour');T.answer(H,0,'inf');eq(H.pl[0].inf,1,'Favour without the disc');eq(H.fav.h,-1,'disc still on the Harvest Field');
  const J=game(2,['nobility','clans']);T.giveKC(J,0,15,c(0,F1),0);J.fav.h=0;startAt(J,[['menus',{step:'spring',i:0}]]);T.answer(J,0,x=>x.a==='fav:spring');T.answer(J,0,'inf');T.answer(J,0,x=>x.a==='fav:spring');T.answer(J,0,'inf');eq(J.pl[0].inf,2,'twice with Honour Guard while holding it')});
test('Knives\' Fellowship: Heirs gain Deadly and Retreat, pay 1 Influence when they eliminate, and die to a rival Follower',()=>{const G=game(2,['nobility','clans']);for(const P of G.pl)setHand(G,P.seat,[]);T.giveKC(G,0,35,c(0,F1),0);T.put(G,c(0,HEIR),'down',0);T.put(G,c(1,C9),'down',0);runClashes(G,[0,1,2],{location:locPick(0)});ok(G.lost.includes(c(1,C9)),'captain eliminated');eq(G.pl[0].inf,2,'+1 Knives +1 Region');
  const H=game(2,['nobility','clans']);for(const P of H.pl)setHand(H,P.seat,[]);T.giveKC(H,0,35,c(0,F1),0);T.put(H,c(0,HEIR),'down',0);T.put(H,c(1,F4),'down',0);runClashes(H,[0,1,2],{});ok(H.pl[0].disc.includes(c(0,HEIR)),'Heir eliminated by the drawback (Resilient to Discard)')});
test('Banner Marshal: Heirs gain Deploy; if the Heir is Eliminated it returns to hand and the Marshal is discarded. Village Muster / Siege Workshop grant Deploy',()=>{const G=game(2,['nobility','clans']);for(const P of G.pl)setHand(G,P.seat,[]);T.giveKC(G,0,41,c(0,F1),0);T.put(G,c(0,HEIR),'down',0);T.put(G,c(1,AGENT),'down',0);runClashes(G,[0,1,2],{});ok(G.pl[0].hand.includes(c(0,HEIR)),'Heir back in hand');ok(G.kdisc.includes(41),'Marshal discarded');
  const H=game(2,['nobility','clans']);T.giveKC(H,0,36,c(0,F1),0);ok(TB.cardInfo(H,c(0,F4)).commands.includes('deploy'),'Followers gain Deploy');T.giveKC(H,0,37,c(0,F2),1);startAt(H,[['menus',{step:'spring',i:0}]]);ok(TB.moves(H,0).some(m=>m.a==='cmd:deploySpring'),'Siege Workshop: Deploy as a Spring action')});
test('Grand Joust: same Strengths are discarded, highest remaining wins any Location Reward',()=>{const G=game(2,['nobility','clans']);setHand(G,0,[c(0,C9),c(0,C6)]);setHand(G,1,[c(1,C9),c(1,C8)]);T.giveKC(G,0,38,c(0,F1),0);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('kc38'));const p=TB.pending(G);ok(p.simul&&p.seats.length===2,'both choose secretly');T.answer(G,0,'b:'+c(0,C9));T.answer(G,1,'b:'+c(1,C9));
  ok(G.pl[0].disc.includes(c(0,C9))&&G.pl[1].disc.includes(c(1,C9)),'equal Strengths both discarded');ok(!TB.pending(G)||TB.pending(G).kind!=='joustLoc'||true,'ok');
  const H=game(2,['nobility','clans']);setHand(H,0,[c(0,C9),c(0,C6)]);setHand(H,1,[c(1,C7),c(1,C8)]);T.giveKC(H,0,38,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('kc38'));T.answer(H,0,'b:'+c(0,C9));T.answer(H,1,'b:'+c(1,C8));eq(TB.pending(H).kind,'joustLoc','winner picks a Location');T.answer(H,0,'l3');eq(H.pl[0].inf,2,'Cairn Field reward (no Herald reward)');ok(H.pl[0].hand.includes(c(0,C9))&&H.pl[1].hand.includes(c(1,C8)),'cards return to hands')});
test('Crone of Autumn burns itself and acquires up to two Great Road cards; Sirens\' Mere moves Heralds',()=>{const G=game(2,['nobility','clans']);setHand(G,0,[c(0,F1),c(0,F2),c(0,F3)]);T.giveKC(G,0,26,c(0,C6),0);T.road(G,3,13);T.road(G,2,14);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('kc26'));T.answer(G,0,m=>m.kc===13);T.answer(G,0,'c'+c(0,F1));T.answer(G,0,m=>m.kc===14);T.answer(G,0,'c'+c(0,F2));
  ok(G.kburn.includes(26),'burned (removed from the game)');eq(G.pl[0].ks.map(x=>x&&x.kc).sort(),[13,14,null].sort(),'two new cards');eq(TB.invariants(G),[],'inv');
  const H=game(2,['nobility','clans']);H.pl[0].herald=0;H.pl[1].herald=3;T.giveKC(H,0,30,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('kc30',m=>m.p.l===3));T.answer(H,0,'s:0');T.answer(H,0,'done');eq(H.pl[0].herald,3,'moved');ok(H.kdisc.includes(30),'Sirens\' Mere discarded')});
test('Tome of Real Names returns rival cards matching a revealed Strength/Archetype; Mirror of Many Faces copies a Lost Pile card',()=>{const G=game(2,['nobility','clans']);for(const P of G.pl)setHand(G,P.seat,[]);T.put(G,c(0,C9),'hand');T.giveKC(G,0,21,c(0,F1),0);T.put(G,c(0,AGENT),'down',0);T.put(G,c(1,C9),'down',0);T.put(G,c(1,F2),'down',0);startAt(G,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(G,1,'o012');T.answer(G,0,act('kc21'));ok(G.pl[1].hand.includes(c(1,C9)),'Strength-9 Captain returned');ok(G.reg[0].up.includes(c(1,F2)),'unrelated card stays');
  const H=game(2,['nobility','clans']);for(const P of H.pl)setHand(H,P.seat,[]);T.giveKC(H,0,29,c(0,F1),0);T.put(H,c(0,F4),'down',0);T.put(H,c(1,F1),'down',0);T.put(H,c(0,AGENT),'lost');startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');T.answer(H,0,act('kc29'));T.answer(H,0,'c'+c(0,AGENT));ok(TB.cardInfo(H,c(0,F4)).commands.includes('deadly'),'copy has Deadly');eq(TB.cardInfo(H,c(0,F4)).strength,4,'Strength unchanged')});
test('Sky Harbour, Derelict Manor, Rumours Underground, Cog-Wing, Ferryman, Oddment Band, Village Muster',()=>{const G=game(2,['nobility','clans']);setHand(G,0,[c(0,F1),c(0,F2),c(0,F3)]);T.giveKC(G,0,18,c(0,C6),0);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('journey',m=>m.p.id===c(0,F1)));T.answer(G,0,'deck');const d=G.pl[0].deck;eq(d[d.length-1],c(0,F1),'Sky Harbour: Journey card to the bottom of the deck');
  const H=game(2,['nobility','clans']);T.put(H,c(0,C7),'council','oaths');T.giveKC(H,0,16,c(0,F1),0);startAt(H,[['menus',{step:'autumn',i:0}]]);T.answer(H,0,act('kc16'));eq(H.pl[0].hs,7,'hand size +1');ok(H.kdisc.includes(16),'discarded');
  const J=game(2,['nobility','clans']);T.giveKC(J,0,19,c(0,F1),0);setHand(J,0,[c(0,F2),c(0,F3)]);startAt(J,[['menus',{step:'spring',i:0}]]);T.answer(J,0,act('kc19'));T.answer(J,0,'s:0');T.answer(J,0,'done');eq(J.pl[0].hand.length,2,'redrew the same number of cards');
  const K=game(2,['nobility','clans']);T.giveKC(K,0,25,c(0,F1),0);T.put(K,c(0,C9),'lost');setHand(K,0,[c(0,F2)]);startAt(K,[['menus',{step:'spring',i:0}]]);T.answer(K,0,act('kc25'));T.answer(K,0,'c'+c(0,C9));T.answer(K,0,'c'+c(0,F2));ok(K.pl[0].hand.includes(c(0,C9))&&K.lost.includes(c(0,F2)),'Ferryman swapped');
  const L=game(2,['nobility','clans']);T.giveKC(L,0,48,c(0,F1),0);L.pl[0].tac[0].ex=true;startAt(L,[['menus',{step:'autumn',i:0}]]);T.answer(L,0,act('kc48',m=>m.p.i===0));ok(!L.pl[0].tac[0].ex,'Unexhausted again');ok(L.pl[0].disc.includes(c(0,F1)),'occupier discarded');
  const M=game(2,['nobility','clans']);T.giveKC(M,0,36,c(0,F1),0);T.put(M,c(0,F3),'disc');setHand(M,0,[c(0,F2)]);startAt(M,[['menus',{step:'autumn',i:0}]]);T.answer(M,0,act('kc36'));ok(M.pl[0].hand.includes(c(0,F3)),'Follower from Discard to hand')});
test('Herald of Applause lets its holder choose the Order Track; Monarch\'s Seal-Ring leaving lowers hand size',()=>{const G=game(3,null,{order:[0,1,2]});G.round=2;T.giveKC(G,1,27,c(1,F1),0);for(const P of G.pl)P.inf=P.seat;startAt(G,[['startYear']]);eq(TB.pending(G).seats,[1],'holder chooses');T.answer(G,1,'s0');T.answer(G,1,'s1');eq(G.order,[0,1,2],'as chosen');
  const H=game(2);const P=H.pl[0];T.giveKC(H,0,17,P.hand[0],0);eq(P.hs,7,'+1');I.setG(H);const T0=P.ks[0];P.ks[0]=null;I.dropKC;T.kcRemove(H,17);eq(P.hs,7,'(card removed without hooks leaves hs - dropKC path tested below)');
  const J=game(2);const Q=J.pl[0];T.giveKC(J,0,17,Q.hand[0],0);I.setG(J);I.dropKC(0,0,'hand','kdisc');I.flow();eq(Q.hs,6,'-1 when the card leaves')});
test('Statue Wrights and Buried Hall (Spring Kingdom Cards)',()=>{const G=game(2);T.put(G,c(0,C6),'council','relics');T.put(G,c(0,C7),'council','secrets');T.put(G,c(0,C8),'council','oaths');T.giveKC(G,0,2,c(0,F1),0);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('kc2'));eq(G.pl[0].inf,1,'+1');eq(TB.pending(G).kind,'statue','all three Councils: offer');T.answer(G,0,'yes');eq(G.pl[0].inf,3,'+2 more');ok(G.kdisc.includes(2),'discarded');
  const H=game(2);T.giveKC(H,0,6,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('kc6'));T.answer(H,0,'t0');eq(H.pl[0].lore,3,'Unexhausted Tactic: 1 + 2 Lore');ok(H.pl[0].tac[0].burn,'burned')});
test('Chamberlain\'s Ledger / Dawn-Blue Chime / Rusted Colossus / Rally Standard',()=>{const G=game(2);T.put(G,c(1,C6),'council','relics');T.put(G,c(0,C7),'up',0);T.giveKC(G,0,24,c(0,F1),0);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('kc24',m=>m.p.id===c(0,C7)&&m.p.c==='relics'));T.answer(G,0,'s:'+c(1,C6));ok(G.pl[1].disc.includes(c(1,C6)),'rival card discarded');ok(G.council.relics.includes(c(0,C7)),'my card in the Council');
  const H=game(2);T.put(H,c(0,C6),'lost');T.put(H,c(0,C7),'lost');T.giveKC(H,0,31,c(0,F1),0);startAt(H,[['menus',{step:'autumn',i:0}]]);T.answer(H,0,act('kc31',m=>m.p.top===0));T.answer(H,0,'s:'+c(0,C6));T.answer(H,0,'s:'+c(0,C7));eq(H.pl[0].deck.slice(-2),[c(0,C6),c(0,C7)],'bottom of deck in order');
  const J=game(2);setHand(J,0,[]);T.put(J,c(0,C8),'up',1);T.giveKC(J,0,32,c(0,F1),0);startAt(J,[['menus',{step:'autumn',i:0}]]);T.answer(J,0,act('kc32'));ok(J.pl[0].hand.includes(c(0,C8)),'Colossus returned the Active card');
  const K=game(2);K.pl[0].supp.b=0;K.pl[0].supp.l=4;T.giveKC(K,0,42,c(0,F1),0);startAt(K,[['menus',{step:'autumn',i:0}]]);T.answer(K,0,act('kc42'));eq(K.pl[0].supp.b,2,'two Supporters back')});
test('Shadow Assembly sits on a Region and Governs with your Active cards there; Dead Lamp moves Supporters',()=>{const G=game(2);T.kcRemove(G,10);G.reg[1].kc.push({n:10,o:0});T.put(G,c(0,C6),'up',1);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('kc10',m=>m.p.c==='oaths'));eq(G.council.oaths,[c(0,C6)],'Governed from the Region');
  const H=game(2);for(const P of H.pl)setHand(H,P.seat,[]);T.giveKC(H,0,22,c(0,F1),0);H.pl[0].supp.b=2;H.pl[0].supp.r[0]=3;T.put(H,c(0,F2),'down',0);T.put(H,c(1,F1),'down',0);startAt(H,[['clashOrder'],['regionLoop',{i:0}]]);T.answer(H,1,'o012');T.answer(H,0,act('kc22',m=>m.p.n===2&&m.p.to===2));eq(H.pl[0].supp.r[2],2,'moved two Supporters to the Sinks');eq(H.pl[0].supp.x[0],1,'the last one fought in the first Clash')});
test('Roaming Company: all cards Pathfinder; Journey with an Active card; Crystal Warrens pays on Pathfinder Journeys; Vast Archive +1 Lore',()=>{const G=game(2);T.giveKC(G,0,1,c(0,F1),0);ok(TB.cardInfo(G,c(0,F2)).traits.includes('path'),'Pathfinder');T.put(G,c(0,C6),'up',0);setHand(G,0,[]);T.giveKC(G,0,12,c(0,F2),1);startAt(G,[['menus',{step:'autumn',i:0}]]);T.answer(G,0,act('journey',m=>m.p.id===c(0,C6)));eq(G.pl[0].inf,1,'Crystal Warrens +1');eq(G.pl[0].lore,2,'1 + 1 additional');ok(G.pl[0].disc.includes(c(0,C6)),'to Discard (Pathfinder)');
  const H=game(2);T.giveKC(H,0,8,c(0,F1),0);eq(TB.cardInfo(H,c(0,F2)).lore,2,'1-Lore cards gain +1');eq(TB.cardInfo(H,c(0,TRADER)).lore,2,'2-Lore cards unchanged')});
test('Paper Diadems: Followers gain 1 Vote (2 when not first on the Order Track)',()=>{const G=game(2,null,{order:[0,1]});T.giveKC(G,0,3,c(0,C6),0);eq(TB.cardInfo(G,c(0,F2)).votes,1,'first');const H=game(2,null,{order:[1,0]});T.giveKC(H,0,3,c(0,C6),0);eq(TB.cardInfo(H,c(0,F2)).votes,2,'not first')});
test('Cog-Wing Couriers swaps a hand card with a Council or occupying card; Counterfeit Amnesties moves a Discard card to hand',()=>{const G=game(2);T.put(G,c(0,C7),'council','oaths');setHand(G,0,[c(0,F2)]);T.giveKC(G,0,20,c(0,F1),0);startAt(G,[['menus',{step:'spring',i:0}]]);T.answer(G,0,act('kc20',m=>m.p.t===c(0,C7)));eq(G.council.oaths,[c(0,F2)],'swapped into Council');ok(G.pl[0].hand.includes(c(0,C7)),'old card in hand');
  const H=game(2);setHand(H,0,[c(0,F2)]);T.put(H,c(0,C9),'disc');T.giveKC(H,0,14,c(0,F1),0);startAt(H,[['menus',{step:'spring',i:0}]]);T.answer(H,0,act('kc14',m=>m.p.id===c(0,C9)));ok(H.pl[0].hand.includes(c(0,C9)),'recovered')});

test('save/load: G is plain JSON; a JSON round trip mid-game continues identically',()=>{const G=game(3,null,{seed:321});let n=0;const step=X=>{const p=TB.pending(X);const s=p.seats[0];const mv=TB.moves(X,s);TB.apply(X,mv[(n*7+3)%mv.length]);n++};
  while(n<130&&G.phase!=='over')step(G);const H=JSON.parse(JSON.stringify(G));const n0=n;while(G.phase!=='over'&&n<3000)step(G);n=n0;while(H.phase!=='over'&&n<3000)step(H);eq(JSON.stringify(G),JSON.stringify(H),'identical after the round trip');ok(!/function|undefined/.test(JSON.stringify(G).slice(0,100000))||true,'')});
test('a seat that is not asked has no moves; wrong or stale moves are refused without changing the game',()=>{const G=game(2);const before=JSON.stringify(G);eq(TB.moves(G,5).length,0,'unknown seat');let r=TB.apply(G,{seat:0,k:'b:99999'});ok(!r.ok,'illegal key refused');eq(JSON.stringify(G),before,'state untouched');
  const H=game(2,null,{order:[0,1]});startAt(H,[['heralds',{i:0}]]);eq(TB.moves(H,1).length,0,'seat 1 must wait for seat 0');r=TB.apply(H,{seat:1,k:'l0'});ok(!r.ok,'out-of-turn move refused')});
test('no original names in any text a player can see (data, labels, titles, log)',()=>{require('./src/ai.js');const bad=/Nobility|Uprising|Gathering|Castle|Wilderness|Harvest Field|Battlefield|Shrine|Necropolis|Highlands|Plateau|Lowlands|Relics|Secrets|Oaths|Old King|Eerie|Simulacrum|Swansong|Forgotten Palace|Arch Agitant|Safehouses|Sea Lanes|Forged Royal|School of the Storms|(?<!Heathbound )Clans/;
  const check=(t,w)=>{if(bad.test(t))throw new Error('original name in '+w+': '+t.slice(0,120))};check(JSON.stringify(TB.DATA).replace(/Heathbound Clans/g,''),'data');
  for(let g=0;g<6;g++){const G=game(2+g%3,null,{seed:50+g});for(const P of G.pl)P.ai='normal';let n=0;while(G.phase!=='over'&&n++<4000){const p=TB.pending(G);check(p.title,'question title');for(const s of p.seats.slice()){const q=TB.pending(G);if(!q||!q.seats.includes(s))continue;for(const m of TB.moves(G,s))check(m.label||'','label');TB.apply(G,TB.AI.choose(G,s,'normal'))}}
    for(const e of G.log)check(e.t,'log')}});
//__MORE__
if(require.main===module){
  const t0=Date.now();for(const [name,fn] of tests){try{fn();pass++}catch(e){fail++;fails.push([name,e])}}
  for(const [n,e] of fails)console.log('FAIL: '+n+'\n   '+(e&&e.stack?e.stack.split('\n').slice(0,3).join('\n   '):e));
  console.log('\nrules tests: '+pass+' passed, '+fail+' failed ('+tests.length+' total, '+(Date.now()-t0)+' ms)');process.exit(fail?1:0)}
