"""Write audio-data.js, MAP.md, credits.html, ASSETS.md for Kaiten Kitchen and append NEW rows to ../ASSETS.md.
Usage: python3 bundle_kaiten.py <workdir>   (workdir = build_kaiten.py output)"""
import os, sys, json, base64
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
W = os.path.abspath(sys.argv[1]); rep = json.load(open(os.path.join(W, 'report.json')))
DATE = '2026-10-03'; CC0U = 'https://creativecommons.org/publicdomain/zero/1.0/'
b64 = lambda p: base64.b64encode(open(p, 'rb').read()).decode()
KEN = {'casino-audio': 'Casino Audio', 'interface-sounds': 'Interface Sounds', 'impact-sounds': 'Impact Sounds', 'rpg-audio': 'RPG Audio', 'ui-audio': 'UI Audio', 'music-jingles': 'Music Jingles'}
DESC = {'click': 'UI click', 'clink': 'plate clink (ceramic/glass tap + tin ring): plate lands on the counter',
        'slide': 'plate/card slide whoosh (a pick leaving the belt)', 'pass': 'hands pass to the next seat (longer slide, quiet)',
        'pick': 'card chosen / placed face-down on the mat', 'cloche': 'cloche lift (metal latch + tin ring + slide): reveal',
        'coin': 'coins handled: score gain', 'tick': 'score tick: replay with rising `rate` while counting',
        'round': 'round-end chime (two plucked jingles)', 'win': 'game-win jingle (sax + plucked layered)', 'error': 'illegal move'}
MUSD = {'main': 'diner music bed: relaxed instrumental jazz, loop', 'belt': 'soft conveyor-belt hum ambience (low-passed fridge drone), loop under music'}
MUS = {'main': ('Jazz Slower', 'Pro Sensory', 'jazz-slower', 'https://opengameart.org/sites/default/files/Jazz%20Take%202.wav', 'Jazz Take 2.wav'),
       'belt': ('The Shop collection: convenience store drinks fridge drone 2', 'LEGIT Audio', 'the-shop', 'https://opengameart.org/sites/default/files/02_-_legit_audio_-_theshopcollection_convenience_store_drinks_fridge_drone_2.mp3', '02_-_legit_audio_-_theshopcollection_convenience_store_drinks_fridge_drone_2.mp3')}
srcs = lambda sp: [sp['src']] + [m[0] for m in sp.get('mix', [])]
parts = ['/* audio-data.js for Kaiten Kitchen - generated by audio/kaiten/bundle_kaiten.py. Licences: see audio/ASSETS.md */', 'const GA_DATA={sfx:{']
sb = mb = 0
for n in DESC: p = os.path.join(W, 'sfx', n + '.mp3'); sb += os.path.getsize(p); parts.append('"%s":"%s",' % (n, b64(p)))
p = os.path.join(W, 'music', 'belt.mp3'); mb += os.path.getsize(p); parts.append('"belt":"%s",' % b64(p))
parts.append('},music:{')
p = os.path.join(W, 'music', 'main.mp3'); mb += os.path.getsize(p); parts.append('"main":"%s",' % b64(p))
parts.append('}};'); js = '\n'.join(parts) + '\n'; open(os.path.join(HERE, 'audio-data.js'), 'w').write(js)
R = rep
L = ['# Kaiten Kitchen: audio assets\n', 'All sounds are real CC0 recordings (Kenney packs, OpenGameArt), cut/layered/normalised by `build_kaiten.py` and bundled by `bundle_kaiten.py` (they import `../tools/dsp.py`, `sfx.py`). Checked %s. Licence snapshots: `licence-snapshots/` here (OpenGameArt pages and Kenney `License.txt`) plus `../licence-snapshots/` (Kenney pack pages). Nothing is synthesised; the only DSP on a recording is trim, fade, layering, loop cross-fade, loudness normalisation and one 1.1 kHz low-pass on the belt hum.\n' % DATE,
     '## Sound effects (mono MP3 48 kbps)\n', '| sample | source file(s) | pack | licence | length | size | use |', '|---|---|---|---|---|---|---|']
for n, v in R['sfx'].items():
    f = srcs(v['spec']); pk = sorted({KEN[x.split('/')[0]] for x in f})
    L.append('| `%s` | %s | Kenney %s | CC0 1.0 | %.2f s | %d B | %s |' % (n, ', '.join('`%s`' % os.path.basename(x) for x in f), ', '.join(pk), v['dur'], v['bytes'], DESC[n]))
L += ['', '## Music and ambience (mono MP3, seamless loop)\n', '| name | track | author | source page | download | licence | loop cut | length | size |', '|---|---|---|---|---|---|---|---|---|']
for n, m in R['music'].items():
    t, a, ps, dl, _ = MUS[n]
    L.append('| `%s` | "%s" | %s | https://opengameart.org/content/%s | %s | CC0 1.0 | %.2f s-%.2f s, 1.5 s cross-fade%s | %.1f s | %d B (%d kbps) |' % (n, t, a, ps, dl, m['a'], m['b'], ' (similarity %.3f)' % m['sim'] if m['sim'] else ', low-passed 1.1 kHz', m['dur'], m['bytes'], m['kbps']))
L.append('\nTotals: SFX %d KB + music/ambience %d KB MP3 = %d KB; `audio-data.js` %d KB (base64). Licence: CC0 1.0 %s\n' % (sb // 1024, mb // 1024, (sb + mb) // 1024, len(js) // 1024, CC0U))
L.append('Rebuild: `python3 build_kaiten.py <raw> <work> && python3 bundle_kaiten.py <work>` (raw = Kenney zips unpacked + `mus/` with `jazz_slower.wav` and `fridge2.mp3` downloaded from the URLs above).\n')
open(os.path.join(HERE, 'ASSETS.md'), 'w').write('\n'.join(L))
M = ["# Kaiten Kitchen: sound map\n", "Load order: `gameaudio.js`, this `audio-data.js`, then the game. `GA.init({sfx:GA_DATA.sfx, music:GA_DATA.music, key:'kk'})`; guard each sfx with `if (window.GA && GA.has(name)) { GA.play(name); return; }`.\n", '| sample | length | suggested use |', '|---|---|---|']
use = {'click': 'buttons', 'clink': 'plate lands on your counter', 'slide': 'a plate glides in / your pick leaves the hand', 'pass': 'all hands pass left', 'pick': 'you lock in a card (face-down)', 'cloche': 'the simultaneous reveal (cloches lift)', 'coin': 'a scoring line adds points', 'tick': 'score counting, rising `rate`', 'round': 'round ends, scores shown', 'win': 'game over / winner', 'error': 'illegal move'}
for n in DESC: M.append('| `%s` | %.2f s | %s |' % (n, R['sfx'][n]['dur'], use[n]))
M += ['', '## Music / ambience', '', '| name | length | track |', '|---|---|---|']
for n in MUSD: M.append('| `%s` | %.1f s | %s: "%s" by %s |' % (n, R['music'][n]['dur'], MUSD[n], MUS[n][0], MUS[n][1]))
M += ['', '```js', "GA.music('main');                 // after the first user gesture; seamless loop", "GA.loop('belt',{vol:.35,fade:1.5});  // belt hum ('belt' ships in GA_DATA.sfx so GA.loop works); GA.stopLoop('belt') at game end", '```', '', 'Ducking: pass `{duck:true}` for `win` and `round`. The user has not auditioned any of these by ear: tune per-sound `vol` in the game\'s `SND_MAP`.']
open(os.path.join(HERE, 'MAP.md'), 'w').write('\n'.join(M) + '\n')
mus = ''.join('<li>%s: &ldquo;%s&rdquo; by %s (<a href="https://opengameart.org/content/%s">OpenGameArt</a>, CC0)</li>\n' % ('Music' if n == 'main' else 'Ambience', MUS[n][0], MUS[n][1], MUS[n][2]) for n in MUSD)
packs = sorted({KEN[x.split('/')[0]] for v in R['sfx'].values() for x in srcs(v['spec'])})
open(os.path.join(HERE, 'credits.html'), 'w').write('<!-- Credits snippet for Kaiten Kitchen. Paste into the in-game Credits / Rules popup. Generated %s. -->\n<section class="credits-audio">\n<h3>Audio</h3>\n<p>With thanks to these public-domain (CC0) creators:</p>\n<ul>\n%s<li>Sound effects: %s by <a href="https://kenney.nl">Kenney</a> (CC0)</li>\n</ul>\n<p><small>All sounds were trimmed, loudness-normalised and converted to MP3 for this game. Names, card text and art are original.</small></p>\n</section>\n' % (DATE, mus, ', '.join(packs)))
# shared ASSETS.md: append NEW rows after the last table row (existing rows untouched)
p = os.path.join(ROOT, 'ASSETS.md'); t = open(p).read()
if 'kaiten/' in t: print('shared ASSETS.md already has kaiten rows'); sys.exit()
uses = {}
for n, v in R['sfx'].items():
    for sp in srcs(v['spec']): uses.setdefault(sp, []).append('kaiten/' + n)
rows = []
for sp, outs in sorted(uses.items()):
    pk = sp.split('/')[0]
    rows.append('| `%s` | [Kenney %s](https://kenney.nl/assets/%s) | Kenney (Kenney Vleugels) | CC0 1.0 | %s | %s | trimmed silence, layered where noted, normalised (~-16 LUFS target, -1 dBFS peak limit), mono MP3 48 kbps (same file may also be logged above for other games) | %s |' % (sp.replace('/Audio/', '/'), KEN[pk], pk, CC0U, DATE, ', '.join(outs)))
for n, (tt, a, ps, dl, fn) in MUS.items():
    m = R['music'][n]
    ch = 'cut %.2fs-%.2fs, 1.5 s equal-power cross-fade (similarity %.3f); normalised; mono %d kbps MP3' % (m['a'], m['b'], m['sim'], m['kbps']) if m['sim'] else 'cut %.1fs-%.1fs, low-passed 1.1 kHz, 1.5 s cross-fade loop; normalised; mono %d kbps MP3' % (m['a'], m['b'], m['kbps'])
    rows.append('| `%s` | [%s](https://opengameart.org/content/%s) | %s | CC0 1.0 | %s | %s | %s | kaiten/music.%s |' % (fn, tt, ps, a, CC0U, DATE, ch, n))
lines = t.split('\n'); last = max(i for i, l in enumerate(lines) if l.startswith('| `'))
lines[last + 1:last + 1] = rows
t = '\n'.join(lines)
t = t.replace('- Medieval: Harvest Season:', ''.join('- %s: %s\n' % (v[0], v[3]) for v in MUS.values()) + '- Medieval: Harvest Season:', 1)
t = t.replace('CC0 (optional thanks, shown in every game): Kenney;', 'CC0 (optional thanks, shown in every game): Kenney; Pro Sensory, LEGIT Audio (OpenGameArt music / ambience, Kaiten Kitchen);', 1)
open(p, 'w').write(t); print('appended', len(rows), 'rows')
