// play/hitprobe.js <url> <outdir> : Athens: what collider sits at each tPlay wall-hit point (HITS env JSON [[x,z],...]), road-edge distance
// (OC_roadE = city/fill/ab/lz/trail roads + junctions), and a top-down 852x393 shot per cluster centre (CL env JSON [[x,z],...]) with hit markers.
const enter=require('../bc/enter.js');const path=require('path');const [URL,OUT]=process.argv.slice(2);const HITS=JSON.parse(process.env.HITS||'[]'),CL=JSON.parse(process.env.CL||'[]');
(async()=>{const seed=`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`;
 const E=await enter(URL,{seed});const {p}=E;p.setDefaultTimeout(900000);await E.roamApi();
 const r=await p.evaluate(HITS=>__oc.ev(`(()=>{const H=${JSON.stringify(HITS)};const out=[];for(const[x,z]of H){const near=[];const seen=new Set();for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){const L=HUB.grid.get(Math.floor(x/40+dx)*10000+Math.floor(z/40+dz))||[];for(const b of L){if(seen.has(b))continue;seen.add(b);for(const rr of[1,2,3,4,6])if(bHit(b,x,z,rr)){near.push({r:rr,k:Object.keys(b).slice(0,14).join(','),t:b.t||b.kind||b.tag||b.type||'',x:+(b.x||b.cx||0).toFixed(1),z:+(b.z||b.cz||0).toFixed(1),w:b.w||b.hw,d:b.d||b.hd,h:b.h,ry:b.ry||b.a,src:b.src||b.by||''});break}}}out.push([x,z,+OC_roadE(x,z).toFixed(1),near.slice(0,3)])}return JSON.stringify(out)})()`),HITS);
 console.log(r);
 await p.evaluate(()=>{window.__shooting=1});
 for(let i=0;i<CL.length;i++){const[cx,cz]=CL[i];await p.evaluate(([cx,cz,H])=>__oc.ev(`(()=>{if(!window.__R0)window.__R0=__dbg.composer.render;__dbg.composer.render=window.__R0;RO.x=${cx};RO.z=${cz};RO.y=groundY(${cx},${cz});hubCullStep&&hubCullStep();lazyStep&&lazyStep();window.__mk&&window.__mk.forEach(m=>HUB.grp.remove(m));window.__mk=[];for(const[x,z]of ${JSON.stringify(H)}){if(Math.hypot(x-(${cx}),z-(${cz}))>90)continue;const m=new THREE.Mesh(new THREE.CylinderGeometry(1,1,6,10),new THREE.MeshBasicMaterial({color:0xff00ff}));m.position.set(x,groundY(x,z)+3,z);HUB.grp.add(m);window.__mk.push(m)}camera.position.set(${cx},groundY(${cx},${cz})+95,${cz}+.01);camera.up.set(0,0,-1);camera.lookAt(${cx},groundY(${cx},${cz}),${cz});camera.updateProjectionMatrix();__dbg.composer.render();__dbg.composer.render=()=>{};camera.up.set(0,1,0);return 1})()`),[cx,cz,HITS]);await p.waitForTimeout(300);await p.screenshot({path:path.join(OUT,`top_${i}_${cx}_${cz}.png`)})}
 await E.b.close()})().catch(e=>{console.error(e);process.exit(1)});
