// v89o: Athens start (tPlay-style save: STORY → CONTINUE), 852x393 touch; shot of the district plate vs the ⚙ (#tuG), normal and during a challenge (body.racing)
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');const URL=process.argv[2],OUT=process.argv[3];fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const ctx=await b.newContext({viewport:{width:852,height:393},isMobile:true,hasTouch:true});
 const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});const cdp=await ctx.newCDPSession(p);
 const tap=async s=>{const e=await p.$(s);if(!e||!await e.isVisible())return false;const bb=await e.boundingBox();const tp=[{x:bb.x+bb.width/2,y:bb.y+bb.height/2,id:1,radiusX:4,radiusY:4,force:1}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:tp});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(800);return true};
 await p.goto(URL);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:240000,polling:500});
 await p.evaluate(()=>{localStorage.clear();localStorage.setItem('mho_slot','1');localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{}}');localStorage.setItem('mho_story.ath@1','{"seen":1}')});
 await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:240000,polling:500});
 await tap('#hcStory');await p.waitForTimeout(1500);await tap('#slotList .go');
 for(let i=0;i<200;i++){try{if(await p.evaluate(()=>__mho.state==='roam'&&!(__mho.LD&&__mho.LD.on)))break}catch(e){}await p.waitForTimeout(3000)}
 for(let i=0;i<12;i++){let h=0;for(const s of['#storyGo','#m1Cs','#rcGo','.m1go','#resBtn','#tutSkip','#m1Next'])if(await tap(s)){h=1;break}if(!h&&i>2)break;await p.waitForTimeout(1500)}
 await p.waitForTimeout(4000);console.log('city',await p.evaluate(()=>__mho.cid()));
 const gas=await p.evaluate(()=>{const e=[...document.querySelectorAll('button,div')].find(x=>x.textContent.trim()==='GAS'&&x.offsetWidth>40&&x.offsetWidth<200);if(!e)return null;const b=e.getBoundingClientRect();return{x:b.left+b.width/2,y:b.top+b.height/2}});console.log('gas',JSON.stringify(gas));
 if(gas){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:gas.x,y:gas.y,id:2,radiusX:4,radiusY:4,force:1}]});await p.waitForTimeout(5000);console.log('kmh',await p.evaluate(()=>Math.round(Math.abs(__mho.RO.v)*3.6)))}
 console.log('DIAG',JSON.stringify(await p.evaluate(()=>{const e=document.querySelector('#roamPlate');const anc=[];for(let x=e;x&&x!==document.body;x=x.parentElement)anc.push(x.id+':'+getComputedStyle(x).display+':'+(x.hidden?'H':''));const rules=[];for(const ss of document.styleSheets){try{for(const r of ss.cssRules){if(r.selectorText&&r.selectorText.includes('roamPlate')&&e.matches(r.selectorText.split(',').filter(q=>q.includes('roamPlate')).join(','))&&/display|visibility|opacity/.test(r.style.cssText))rules.push(r.selectorText.slice(0,160)+' {'+r.style.cssText.slice(0,80))}}catch(_){}}return{body:document.body.className,mode:document.body.dataset.mode,anc,rules}})));
 const chk=async tag=>{await p.evaluate(()=>{const e=document.querySelector('#roamPlate');e.style.transition='none';e.classList.remove('crHide');if(!document.getElementById('shotPl')){const st=document.createElement('style');st.id='shotPl';st.textContent='body.v85 #roamPlate#roamPlate{display:block!important;opacity:1!important}';document.head.appendChild(st)}});await p.waitForTimeout(100);
  const r=await p.evaluate(()=>{const R=s=>{const e=document.querySelector(s);if(!e)return null;const b=e.getBoundingClientRect(),cs=getComputedStyle(e);return{x0:Math.round(b.left),y0:Math.round(b.top),x1:Math.round(b.right),y1:Math.round(b.bottom),vis:cs.display!=='none'&&cs.visibility!=='hidden'&&+cs.opacity>0&&b.width>0}};const a=R('#roamPlate'),g=R('#tuG');return{racing:document.body.classList.contains('racing'),plate:a,gear:g,overlap:!!(a&&g&&a.vis&&g.vis&&a.x0<g.x1&&g.x0<a.x1&&a.y0<g.y1&&g.y0<a.y1),txt:document.querySelector('#roamPlate').textContent}});
  console.log('PLATE',tag,JSON.stringify(r));await p.screenshot({path:`${OUT}/ath_plate_${tag}.png`})};
 await p.evaluate(()=>document.body.classList.remove('racing'));await chk('roam');await p.evaluate(()=>document.body.classList.add('racing'));await p.waitForTimeout(300);await chk('racing');if(gas)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 console.log('ERR',JSON.stringify(errs.filter(e=>!/GPU stall|GL Driver/.test(e)).slice(0,8)));await b.close()})();
