import re, os, io, json, base64, sys
h=open('head.html').read()
b=open('body.html').read()
h=h.replace('<style>','<style>\n'+open('../shell/shell.css').read()+'\n',1)
h=h.replace('</style>','\n'+open('bf.css').read()+'\n'+open('tbl.css').read()+'\n</style>',1)  # board-first layer + the dungeon-table layer, last so they win
def art_js():
    man = json.load(open('art/manifest.json', encoding='utf-8'))
    out, total = {}, 0
    for k, name in man['items'].items():
        f = os.path.join('art', name + '.webp')
        if not os.path.exists(f): print('NOTE: art missing', name, file=sys.stderr); continue
        data = open(f, 'rb').read(); total += len(data); out[k] = 'data:image/webp;base64,' + base64.b64encode(data).decode('ascii')
    print('art: %d images, %d KB' % (len(out), total // 1024), file=sys.stderr)
    return '// painted card art (generated by build.py from ./art)\nvar DK_ART = ' + json.dumps(out, separators=(',', ':')) + ';\n'
SRC={'shell.js':'../shell/shell.js','trystero.min.js':'../net/trystero.min.js','netroom.js':'../net/netroom.js','perfhud.js':'../perf/perfhud.js','gameaudio.js':'../audio/gameaudio.js','audio-data.js':'../audio/doorkick/audio-data.js','gx-campaign.js':'../shell/gx-campaign.js','gx-viewport.js':'../shell/gx-viewport.js','gx-help.js':'../shell/gx-help.js','gx-tutor.js':'../shell/gx-tutor.js'}  # the shared speed tool and the shared audio player + this game's samples
for f in ['trystero.min.js','netroom.js','shell.js','gx-viewport.js','gx-help.js','gx-tutor.js','gx-campaign.js','campaign-data.js','perfhud.js','cards.js','rules-html.js','art-data.js','art.js','gfx.js','engine.js','ai.js','gameaudio.js','audio-data.js','sound.js','coach.js','net.js','ui.js','ph.js','bf.js','tbl.js','hlp.js','tutor.js','campaign.js']:
    tag=f'<script src="{f}"></script>'
    assert tag in b,f
    src=('window.CAMPAIGN='+open('campaign.json').read().strip()+';') if f=='campaign-data.js' else art_js() if f=='art-data.js' else open(SRC.get(f,f)).read()
    b=b.replace(tag,'<script>\n'+src+'\n</script>')
h=h.replace('</head>','<style>\n'+open('../shell/gx-campaign.css').read()+'\n'+open('../shell/gx-help.css').read()+'\n'+open('../shell/gx-tutor.css').read()+'\n</style>\n</head>',1)  # the shared story-campaign screens
out=h+b
open('doorkick.html','w').write(out)
js='\n'.join(re.findall(r'<script>(.*?)</script>',out,re.S))
open('x.js','w').write(js)
print(len(out))
