// ---------- the card table: the 168-card base deck (94 door, 74 treasure). Names and texts are original; numbers and effects follow the real cards.
// ref = id of the real card in cards-base.json (the audit trail). Effects are data (ops) plus a few special keys (sp) the engine knows.
const TRAITNAME={human:'Human',elf:'Elf',dwarf:'Dwarf',halfling:'Halfling',warrior:'Warrior',wizard:'Wizard',thief:'Thief',cleric:'Cleric'};
const EXPS=[];
const M=(ref,n,lvl,tr,x,badt,bad,o)=>Object.assign({ref,d:'door',t:'monster',n,lvl,tr,lv:1,x,badt,bad},o||{});
const I=(ref,n,slot,b,g,x,o)=>Object.assign({ref,d:'tr',t:'item',n,slot:slot==='1h'||slot==='2h'||slot==='-'?null:slot,hands:slot==='1h'?1:slot==='2h'?2:0,b,g,x},o||{});
const O=(ref,n,b,g,x,o)=>Object.assign({ref,d:'tr',t:'oneshot',n,b,g,x},o||{});
const C=(ref,n,x,ops,o)=>Object.assign({ref,d:'door',t:'curse',n,x,ops},o||{});
const L=(ref,n,x,o)=>Object.assign({ref,d:'tr',t:'level',n,x:x||'Go up a level. Play on anyone, any time, but never to reach the winning level.'},o||{});
const CARDS=[
// ---- classes and races (generic fantasy archetypes keep their plain names) ----
{ref:'base-warrior',k:'warrior',d:'door',t:'class',cls:'warrior',n:'Warrior',art:'warrior',cp:3,x:'Berserk: in a fight, discard up to 3 cards, +1 each. You win ties.'},
{ref:'base-wizard',k:'wizard',d:'door',t:'class',cls:'wizard',n:'Wizard',art:'wizard',cp:3,x:'Flight: discard up to 3 cards, +1 each to run away. Charm: discard your whole hand to send one lone monster away and take its treasure (no level).'},
{ref:'base-thief',k:'thief',d:'door',t:'class',cls:'thief',n:'Thief',art:'thief',cp:3,x:'Backstab: discard a card to give a fighter -2 (once per victim per fight). Steal: discard a card to try for a small item: roll 4+, or lose a level.'},
{ref:'base-cleric',k:'cleric',d:'door',t:'class',cls:'cleric',n:'Cleric',art:'cleric',cp:3,x:'Resurrection: instead of kicking a new door, take the top door discard and discard a card. Turning: discard up to 3 cards against undead, +3 each.'},
{ref:'base-elf',k:'elf',d:'door',t:'race',race:'elf',n:'Elf',art:'elf',cp:3,x:'+1 to run away. Go up a level for each monster you help someone kill.'},
{ref:'base-dwarf',k:'dwarf',d:'door',t:'race',race:'dwarf',n:'Dwarf',art:'dwarf',cp:3,x:'Carry any number of Big items. Hold up to 6 cards.'},
{ref:'base-halfling',k:'halfling',d:'door',t:'race',race:'halfling',n:'Halfling',art:'half',cp:3,x:'-1 to run away. Once per turn, sell one item for double its price.'},
{ref:'base-half-breed',k:'mixed',d:'door',t:'special',sp:'half',n:'Mixed Heritage',cp:2,x:'You may have two races. With one race, you get its perks and none of its drawbacks.'},
{ref:'base-super-munchkin',k:'double',d:'door',t:'special',sp:'super',n:'Double Major',cp:2,x:'You may have two classes. With one class, you get its perks and none of its drawbacks.'},
// ---- monsters (37) ----
M('base-3-872-orcs','The Endless Goblin Horde',10,3,'+6 against Dwarves (it is a long story).','Roll a die: 1–2 and you are trampled to death, otherwise lose that many levels.',[['orcs']],{vs:[{race:'dwarf',b:6}],k:'horde'}),
M('base-amazon','Shieldmaiden Champion',8,2,'Never attacks a woman: a female fighter just gets 1 treasure from her.','Lose your class(es); with no class, lose 3 levels.',[['clsOr',3]],{sp:'amazon',k:'amazon'}),
M('base-bigfoot','Hairy Hat-Muncher',12,3,'+3 against Dwarves and Halflings.','Flattens you and eats your hat: lose the headgear you wear.',[['item','headW']],{vs:[{race:'dwarf',b:3},{race:'halfling',b:3}],k:'hatmuncher'}),
M('base-bullrog','Horned Inferno',18,5,'Won’t chase anyone of level 4 or lower.','You are toasted to a crisp. Dead.',[['death']],{lv:2,nop:4,k:'inferno'}),
M('base-crabs','Pinch Mites',1,1,'You can’t run away from them.','Lose your armor and everything worn below the waist.',[['item','armor','all'],['item','below','all']],{sp:'noescape',k:'mites'}),
M('base-drooling-slime','Sock Slurper',1,1,'+4 against Elves.','Lose the footgear you wear; with none, lose a level.',[['itemOr','footW',1]],{vs:[{race:'elf',b:4}],k:'slurper'}),
M('base-face-sucker','Kissy Leech',8,2,'+6 against Elves.','It kisses your face off, hat and all: lose all headgear and a level.',[['item','head','all'],['lvl',1]],{vs:[{race:'elf',b:6}],k:'leech'}),
M('base-floating-nose','Hovering Sniffer',10,3,'Bribe it with an item worth 200 gold or more to make it leave. A garlic gargle kills it outright.','You can’t escape it, nothing helps: lose 3 levels.',[['lvl',3]],{sp:'nose',k:'sniffer'}),
M('base-flying-frogs','Kamikaze Toads',2,1,'-1 to run away.','They bite: lose 2 levels.',[['lvl',2]],{runm:-1,k:'toads'}),
M('base-gazebo','Menacing Pergola',8,2,'Nobody can help you against it.','Lose 3 levels.',[['lvl',3]],{sp:'nohelp',k:'pergola'}),
M('base-gelatinous-octahedron','Jiggling Pyramid',2,1,'+1 to run away.','Drop all your Big items.',[['item','big','all']],{runm:1,k:'pyramid'}),
M('base-ghoulfiends','Grave Gnawers',8,2,'No items or bonuses count against them: fight with your level alone.','Your level drops to the lowest level at the table.',[['lowest']],{sp:'lvlonly',k:'gnawers'}),
M('base-harpies','Off-Key Sirens',4,2,'+5 against Wizards.','Their singing is awful: lose 2 levels.',[['lvl',2]],{vs:[{cls:'wizard',b:5}],k:'sirens'}),
M('base-hippogriff','Stampeding Skygrif',16,4,'Won’t chase anyone of level 3 or lower.','You drop things as you flee: each other player takes one treasure card from your table or hand.',[['hippo']],{lv:2,nop:3,k:'skygrif'}),
M('base-insurance-salesman','Timeshare Pitchman',14,4,'Your level doesn’t count: fight him with bonuses only.','You sign up: lose 1,000 gold worth of items, or all of them.',[['gold',1000]],{sp:'bonusonly',k:'pitchman'}),
M('base-king-tut','Pharaoh Wrappington',16,4,'Undead. Won’t chase level 3 or lower; anyone higher who flees loses 2 levels even when they get away.','Lose all your items and your whole hand.',[['item','any','all'],['hand','all']],{lv:2,nop:3,undead:true,sp:'escape2',k:'pharaoh'}),
M('base-lame-goblin','Limping Imp',1,1,'+1 to run away.','A whack with its crutch: lose a level.',[['lvl',1]],{runm:1,k:'imp'}),
M('base-large-angry-chicken','Furious Rooster',2,1,'Beat it with fire or flame and gain an extra level.','Painful pecking: lose a level.',[['lvl',1]],{sp:'fire',k:'rooster'}),
M('base-lawyers','Litigation Lizards',6,2,'Never attack a Thief (professional courtesy): a Thief may instead swap 2 treasures in hand for 2 new ones.','An injunction: starting on your left, each player draws a card from your hand; discard the rest.',[['lawyer']],{sp:'lawyer',k:'lizards'}),
M('base-leperchaun','Pickpocket Pixie',4,2,'+5 against Elves.','Takes 2 of your items: the players on either side each pick one.',[['pixie']],{vs:[{race:'elf',b:5}],k:'pixie'}),
M('base-maul-rat','Hellmouse',1,1,'+3 against Clerics.','A nasty nip: lose a level.',[['lvl',1]],{vs:[{cls:'cleric',b:3}],k:'hellmouse'}),
M('base-mr-bones','Rattlebones',2,1,'Undead. If you flee, lose a level even if you get away.','A bony touch: lose 2 levels.',[['lvl',2]],{undead:true,sp:'escape1',k:'rattle'}),
M('base-net-troll','Forum Troll',10,3,'No special powers, and very upset about it.','The highest-level player(s) each take one item from you.',[['troll']],{k:'troll'}),
M('base-pit-bull','Snappy Hound',2,1,'If you can’t win, drop a pole or staff to distract it: you get away automatically.','Bite marks: lose 2 levels.',[['lvl',2]],{sp:'fetch',k:'hound'}),
M('base-platycore','Duck-Billed Terror',6,2,'+6 against Wizards.','Discard your whole hand, or lose 2 levels.',[['handOr',2]],{vs:[{cls:'wizard',b:6}],k:'duckbill'}),
M('base-plutonium-dragon','Uranium Wyrm',20,5,'Won’t chase anyone of level 5 or lower.','Roasted and eaten. Dead.',[['death']],{lv:2,nop:5,k:'wyrm'}),
M('base-potted-plant','Ficus of Menace',1,1,'An Elf who beats it draws an extra treasure.','None: you always get away.',[],{sp:'plant',k:'ficus'}),
M('base-pukachu','Barfabunny',6,2,'Beat it with no help and no bonuses at all and gain an extra level.','Projectile sick: discard your whole hand.',[['hand','all']],{sp:'pure',k:'barfabunny'}),
M('base-shrieking-geek','Nitpicking Nerd',6,2,'+6 against Warriors.','You become a plain Human: lose your races and classes.',[['race','all'],['cls','all']],{vs:[{cls:'warrior',b:6}],k:'nerd'}),
M('base-snails-on-speed','Turbo Slugs',4,2,'-2 to run away.','Roll a die: lose that many items or cards from your hand, your pick.',[['slugs']],{runm:-2,k:'slugs'}),
M('base-squidzilla','Tentaclopolis',18,4,'+4 against Elves. Won’t chase anyone of level 4 or lower, except Elves.','Grabbed, slimed and gobbled. Dead.',[['death']],{lv:2,nop:4,vs:[{race:'elf',b:4}],sp:'nopNotElf',k:'tentacles'}),
M('base-stoned-golem','Sleepy Boulderman',14,4,'You may simply walk past him and skip the fight (Halflings look tasty and must fight).','He gets the munchies and eats you. Dead.',[['death']],{sp:'golem',k:'boulder'}),
M('base-tongue-demon','Slobber Fiend',12,3,'+4 against Clerics. Before the fight, discard one item of your choice.','A revolting kiss: lose 2 levels (3 for Elves).',[['lvlIf',{race:'elf'},3,2]],{vs:[{cls:'cleric',b:4}],sp:'tongue',k:'slobber'}),
M('base-undead-horse','Zombie Pony',4,2,'Undead. +5 against Dwarves.','Kicks, bites and smells: lose 2 levels.',[['lvl',2]],{undead:true,vs:[{race:'dwarf',b:5}],k:'pony'}),
M('base-unspeakably-awful-indescribable-horror','The Nameless Dread',14,4,'+4 against Warriors.','Unspeakable death for anyone but a Wizard. A Wizard just loses the Wizard card.',[['dread']],{vs:[{cls:'warrior',b:4}],k:'dread'}),
M('base-wannabe-vampire','Bat-Cape Poser',12,3,'A Cleric can shoo him off without a fight and take all his treasure (no level).','He blocks the door and tells you his backstory: lose 3 levels.',[['lvl',3]],{sp:'vamp',k:'poser'}),
M('base-wight-brothers','The Grave Twins',16,4,'Undead. Won’t chase level 3 or lower; anyone higher who flees loses 2 levels even when they get away.','Back to level 1.',[['lvl','all']],{lv:2,nop:3,undead:true,sp:'escape2',k:'twins'}),
// ---- monster boosts ----
{ref:'base-ancient',k:'primordial',d:'door',t:'enh',n:'Primordial',b:10,trb:2,x:'+10 to a monster. If it is beaten, 2 more treasures.'},
{ref:'base-humongous',k:'gargantuan',d:'door',t:'enh',n:'Gargantuan',b:10,trb:2,x:'+10 to a monster. If it is beaten, 2 more treasures.'},
{ref:'base-enraged',k:'furious',d:'door',t:'enh',n:'Furious',b:5,trb:1,x:'+5 to a monster. If it is beaten, 1 more treasure.'},
{ref:'base-intelligent',k:'genius',d:'door',t:'enh',n:'Genius',b:5,trb:1,x:'+5 to a monster. If it is beaten, 1 more treasure.'},
{ref:'base-baby',k:'tiny',d:'door',t:'enh',n:'Tiny',b:-5,trb:-1,x:'-5 to a monster (never below level 1). If it is beaten, 1 less treasure (never below 1).'},
{ref:'base-mate',k:'plusone',d:'door',t:'enh',sp:'mate',n:'Plus-One',b:0,x:'The monster brings a date: an identical second monster with the same boosts. Beat both for double levels and treasure.'},
// ---- other door cards ----
{ref:'base-wandering-monster',k:'uninvited',d:'door',t:'special',sp:'wander',n:'Uninvited Guest',cp:2,x:'Play with a monster from your hand during any fight: it joins in.'},
{ref:'base-cheat',k:'loophole',d:'door',t:'special',sp:'cheat',n:'Loophole',x:'Wear one item the rules would not allow (any restriction or slot). Lose this card when you lose that item.'},
{ref:'base-divine-intervention',k:'favor',d:'door',t:'special',sp:'divine',n:'Heavenly Favor',x:'However it is drawn, every Cleric goes up a level at once, even to win.'},
{ref:'base-help-me-out-here',k:'borrow',d:'door',t:'special',sp:'borrow',n:'Mind If I Borrow That?',x:'In your own fight, take one item from another player, if it turns your loss into a win.'},
{ref:'base-illusion',k:'mirrors',d:'door',t:'special',sp:'illusion',n:'Smoke and Mirrors',x:'In any fight, swap one monster (and its boosts) for a monster from your hand.'},
{ref:'base-out-to-lunch',k:'fishing',d:'door',t:'special',sp:'lunch',n:'Gone Fishing',x:'In any fight, all the monsters leave; the fighter draws 2 treasures.'},
// ---- curses (19 copies) ----
C('base-curse-change-class','Career Change Hex','If you have a class, it is replaced by the first class card in the door discards (or just lost).',[['swap','cls']],{k:'hexcls'}),
C('base-curse-change-race','Family Tree Hex','If you have a race, it is replaced by the first race card in the door discards (or just lost).',[['swap','race']],{k:'hexrace'}),
C('base-curse-change-sex','Gender Swap Hex','Your sex changes for good, and you are at -5 in your next fight while you get used to it.',[['sex']],{k:'hexsex'}),
C('base-curse-chicken-on-your-head','Hen Hat Hex','A hen roosts on your head: -1 to all your die rolls, until something takes your headgear.',[['pers']],{pers:{die:-1},k:'hexhen'}),
C('base-curse-duck-of-doom','Goose of Gloom','You picked up a goose in a dungeon. Lose 2 levels.',[['lvl',2]],{k:'hexgoose'}),
C('base-curse-income-tax','Tax Collector','Discard an item of your choice. Everyone else must discard items worth at least as much, or discard all their items and lose a level.',[['tax']],{k:'hextax'}),
C('base-curse-lose-1-big-item','Butterfingers','Discard one Big item of your choice.',[['pick','big']],{k:'hexbig'}),
C('base-curse-lose-1-level','Rotten Luck','Lose a level.',[['lvl',1]],{cp:2,k:'hexlvl'}),
C('base-curse-lose-1-small-item','Light-Fingered Gremlin','Discard one small item of your choice.',[['pick','small']],{cp:2,k:'hexsmall'}),
C('base-curse-lose-two-cards','Grabby Neighbours','The player on your left takes a random card from your hand, then the player on your right does.',[['grab']],{k:'hexgrab'}),
C('base-curse-lose-your-class','Career Crisis','Discard a class (your choice if you have two). With no class, lose a level.',[['clsOr1']],{k:'hexcrisis'}),
C('base-curse-lose-your-race','Identity Crisis','Discard your race cards and become a plain Human.',[['race','all']],{k:'hexid'}),
C('base-curse-lose-the-armor-you-are-wearing','Rust Storm','Lose the armor you are wearing.',[['item','armorW']],{k:'hexrust'}),
C('base-curse-lose-the-footgear-you-are-wearing','Sock Goblin','Lose the footgear you are wearing.',[['item','footW']],{k:'hexsock'}),
C('base-curse-lose-the-headgear-you-are-wearing','Sudden Gust','Lose the headgear you are wearing.',[['item','headW']],{k:'hexgust'}),
C('base-curse-malign-mirror','Spiteful Mirror','In your next fight only, weapons give you no bonus.',[['pers']],{pers:{noweap:1,once:1},k:'hexmirror'}),
C('base-truly-obnoxious-curse','Utterly Rotten Hex','Lose the item that gives you your biggest bonus.',[['item','best']],{k:'hexrotten'}),
// ---- go up a level (9) and other treasures ----
L('base-1-000-gold-pieces','Windfall of Coins',null,{k:'l1'}),L('base-boil-an-anthill','Squash a Beetle Colony',null,{k:'l2'}),L('base-bribe-gm-with-food','Snacks for the Referee',null,{k:'l3'}),
L('base-convenient-addition-error','Creative Arithmetic',null,{k:'l4'}),L('base-invoke-obscure-rules','Obscure Footnote',null,{k:'l5'}),L('base-potion-of-general-studliness','Tonic of Pure Swagger',null,{k:'l6'}),
L('base-kill-the-hireling','Fire the Porter','Go up a level, only if a Porter is in play (anyone’s): the Porter is discarded.',{sp:'killhire',k:'l7'}),
L('base-mutilate-the-bodies','Loot the Leftovers','Go up a level. Only right after a fight (anyone’s).',{sp:'after',k:'l8'}),
L('base-whine-at-the-gm','Complain Loudly','Go up a level. Not if you are the highest level, or tied for it.',{sp:'whine',k:'l9'}),
{ref:'base-hireling',k:'porter',d:'tr',t:'special',sp:'hire',n:'Porter',x:'Play any time. Carries one extra Big item for you. Won’t fight.'},
{ref:'base-hoard',k:'pile',d:'tr',t:'special',sp:'hoard',n:'Treasure Pile!',x:'When you get this card, draw 3 more treasures at once.'},
{ref:'base-steal-a-level',k:'heist',d:'tr',t:'special',sp:'steal',n:'Level Heist',x:'Pick a player: they go down a level and you go up one (never to win).'},
// ---- items (38) ----
I('base-bad-ass-bandanna','Tough-Guy Headband','head',3,400,'Humans only.',{req:'human',k:'headband'}),
I('base-boots-of-butt-kicking','Stompy Boots','foot',2,400,'',{k:'stompy'}),
I('base-boots-of-running-really-fast','Sprint Sneakers','foot',0,400,'+2 to run away.',{run:2,k:'sneakers'}),
I('base-bow-with-ribbons','Frilly Longbow','2h',4,800,'Elves only.',{req:'elf',k:'longbow'}),
I('base-broad-sword','Dame’s Blade','1h',3,400,'Women only.',{req:'female',k:'dame'}),
I('base-buckler-of-swashing','Swashbuckler Shield','1h',2,400,'',{k:'swash'}),
I('base-chainsaw-of-bloody-dismemberment','Buzzsaw of Mayhem','2h',3,600,'',{big:true,k:'buzzsaw'}),
I('base-cheese-grater-of-peace','Holy Cheese Grater','1h',3,400,'Clerics only.',{req:'cleric',k:'grater'}),
I('base-cloak-of-obscurity','Shady Cloak','-',4,600,'Thieves only.',{req:'thief',k:'cloak',art:'cloak'}),
I('base-dagger-of-treachery','Backstabber’s Shiv','1h',3,400,'Thieves only.',{req:'thief',k:'shiv'}),
I('base-eleven-foot-pole','Extra-Long Pole','2h',1,200,'A pole.',{tags:['pole'],k:'pole'}),
I('base-flaming-armor','Blazing Breastplate','armor',2,400,'Fire and flame.',{tags:['fire'],k:'blazing'}),
I('base-gentleman-s-club','Fella’s Cudgel','1h',3,400,'Men only.',{req:'male',k:'cudgel'}),
I('base-hammer-of-kneecapping','Shin-Smasher Hammer','1h',4,600,'Dwarves only.',{req:'dwarf',k:'shinhammer'}),
I('base-helm-of-courage','Brave Bucket','head',1,200,'',{k:'bucket'}),
I('base-horny-helmet','Antlered Helm','head',1,600,'+1, or +3 for an Elf.',{elfb:3,k:'antler'}),
I('base-huge-rock','Enormous Boulder','2h',3,0,'No value.',{big:true,k:'boulderitem'}),
I('base-kneepads-of-allure','Charming Kneepads','-',0,600,'Not for Clerics. Whoever you ask for help can’t refuse or ask for treasure.',{req:'!cleric',tags:['below'],sp:'allure',k:'kneepads',art:'legs'}),
I('base-leather-armor','Scruffy Jerkin','armor',1,200,'',{k:'jerkin'}),
I('base-limburger-and-anchovy-sandwich','Stinky Fish Sandwich','-',3,400,'Halflings only.',{req:'halfling',k:'sandwich',art:'food'}),
I('base-mace-of-sharpness','Pointy Holy Mace','1h',4,600,'Clerics only.',{req:'cleric',k:'mace'}),
I('base-mithril-armor','Moonsilver Plate','armor',3,600,'Not for Wizards.',{big:true,req:'!wizard',k:'moonsilver'}),
I('base-pantyhose-of-giant-strength','Leggings of Mighty Might','-',3,600,'Not for Warriors.',{req:'!warrior',tags:['below'],k:'leggings',art:'legs'}),
I('base-pointy-hat-of-power','Tall Hat of Zap','head',3,400,'Wizards only.',{req:'wizard',k:'zaphat'}),
I('base-rapier-of-unfairness','Cheater’s Rapier','1h',3,600,'Elves only.',{req:'elf',k:'rapier'}),
I('base-rat-on-a-stick','Snack on a Stick','1h',0,0,'Discard it to get away automatically from any monster of level 8 or lower.',{sp:'ratstick',k:'snackstick'}),
I('base-really-impressive-title','Very Fancy Title','-',3,0,'No value.',{k:'title',art:'scroll'}),
I('base-sandals-of-protection','Lucky Flip-Flops','foot',0,700,'Curses you draw when you kick open a door don’t affect you.',{sp:'sandals',k:'flipflops'}),
I('base-shield-of-ubiquity','Wall-Sized Shield','1h',4,600,'Warriors only.',{big:true,req:'warrior',k:'wallshield'}),
I('base-short-wide-armor','Stubby Plate','armor',3,400,'Dwarves only.',{req:'dwarf',k:'stubby'}),
I('base-singing-dancing-sword','Tap-Dancing Sword','-',2,400,'Not for Thieves. Needs no hands.',{req:'!thief',k:'tapsword',art:'1h'}),
I('base-slimy-armor','Gooey Mail','armor',1,200,'',{k:'gooey'}),
I('base-sneaky-bastard-sword','Rascal’s Sword','1h',2,400,'',{k:'rascal'}),
I('base-spiky-knees','Pointy Kneecaps','-',1,200,'',{tags:['below'],k:'kneecaps',art:'legs'}),
I('base-staff-of-napalm','Staff of Wildfire','1h',5,800,'Wizards only. A fiery staff.',{req:'wizard',tags:['fire','pole'],k:'wildfire'}),
I('base-stepladder','Folding Stepstool','-',3,400,'Halflings only.',{big:true,req:'halfling',k:'stepstool',art:'ladder'}),
I('base-swiss-army-polearm','Everything Halberd','2h',4,600,'Humans only. A pole.',{big:true,req:'human',tags:['pole'],k:'halberd'}),
I('base-tuba-of-charm','Soothing Sousaphone','1h',0,300,'+1 to run away.',{big:true,run:1,k:'sousaphone'}),
// ---- one-shots (24 copies) ----
O('base-cotion-of-ponfusion','Fonfusing Cizzy Potion',3,100,'+3 to either side in any fight.',{k:'cizzy'}),
O('base-electric-radioactive-acid-potion','Fizzing Doom Potion',5,200,'+5 to either side in any fight.',{k:'fizz'}),
O('base-flaming-poison-potion','Hot Sauce Potion',3,100,'+3 to either side in any fight. Fire and flame.',{tags:['fire'],k:'hotsauce'}),
O('base-freezing-explosive-potion','Frosty Bang Potion',3,100,'+3 to either side in any fight.',{k:'frosty'}),
O('base-magic-missile','Zappy Dart',5,300,'+5 to either side in any fight.',{k:'dart'}),
O('base-nasty-tasting-sports-drink','Sour Energy Drink',2,200,'+2 to either side in any fight.',{k:'sour'}),
O('base-potion-of-halitosis','Garlic Gargle',2,100,'+2 to either side in any fight, or kill a Hovering Sniffer outright.',{sp:'garlic',k:'garlic'}),
O('base-potion-of-idiotic-bravery','Liquid Courage',2,100,'+2 to either side in any fight.',{k:'courage'}),
O('base-pretty-balloons','Shiny Balloons',5,0,'+5 to either side in any fight. No value.',{k:'balloons'}),
O('base-sleep-potion','Snooze Syrup',2,100,'+2 to either side in any fight.',{k:'snooze'}),
O('base-yuppie-water','Artisanal Spring Water',2,100,'Only for Elves: +2 for each Elf in the fight.',{sp:'elfwater',k:'water'}),
O('base-doppleganger','Mirror Twin',0,300,'Only if you fight alone: your strength is doubled.',{sp:'dbl',k:'twin'}),
O('base-flask-of-glue','Jar of Sticky Paste',0,100,'When someone gets away from a monster, they must roll again.',{sp:'glue',k:'paste'}),
O('base-friendship-potion','Hug Juice',0,200,'In any fight, all the monsters leave. No treasure.',{sp:'flee',k:'hugjuice'}),
O('base-instant-wall','Pop-Up Wall',0,300,'When running away, you (and your helper) get away automatically.',{sp:'wall',k:'wall'}),
O('base-invisibility-potion','Vanishing Tonic',0,200,'When you fail to run away, you get away after all.',{sp:'invis',k:'vanish'}),
O('base-loaded-die','Weighted Die',0,300,'After your own roll, change it to any number.',{sp:'die',k:'weighted'}),
O('base-magic-lamp','Wishing Lantern',0,500,'On your own turn, one monster vanishes, even after it caught you. If it was your only monster, take its treasure (no level).',{sp:'lamp',cp:2,k:'lantern'}),
O('base-pollymorph-potion','Parrotify Potion',0,1300,'In any fight, one monster turns into a parrot and flies off, leaving its treasure (no level).',{sp:'poly',k:'parrot'}),
O('base-transferal-potion','Not-My-Problem Potion',0,300,'In any fight, another player of your choice takes over the fight, with its rewards. The first player may still loot the room.',{sp:'transfer',k:'notmine'}),
O('base-wishing-ring','Ring of Undoing',0,500,'Cancel a curse, any time (including one already on you).',{sp:'ward',cp:2,k:'undoring'}),
O('base-wand-of-dowsing','Rummaging Rod',0,1100,'Take any one card you want from the discard piles.',{sp:'dowse',k:'rod'})
];
CARDS.forEach(c=>{if(!c.k)c.k=c.ref.replace(/^base-/,'');c.cp=c.cp||1;if(c.t==='monster'&&c.lv==null)c.lv=1;if(c.t==='oneshot'&&c.b&&!c.sp)c.cb=1});
const DEF={};for(const c of CARDS){if(DEF[c.k])throw new Error('duplicate key '+c.k);DEF[c.k]=c}
