# Builds shortfuse.html (the playable game, one self-contained file) and x.js (all our scripts, for node --check).
# Also keeps building debug.html from src/ (the stage-1 debug page).
# Kit: kit.js is copied from ../kit (never edited there); a few small patches are applied to the COPY here (see KIT_PATCHES and UI-REPORT.md).
import re,os,sys,json,base64
D=os.path.dirname(os.path.abspath(__file__))
SP=os.path.abspath(os.path.join(D,'..','..'))
def rd(p):return open(p,encoding='utf-8').read()
def art_js():
    # painted card art: ../art/<key>.webp (key = EQUIP / CHARS / ITEMS id) -> SF_ART data URIs; extras.js turns them into blob URLs
    A=os.path.join(SP,'short-fuse','art');man=json.load(open(os.path.join(A,'manifest.json'),encoding='utf-8'))['items']
    out,total={},0
    for k,name in man.items():
        f=os.path.join(A,name+'.webp')
        if not os.path.exists(f):print('NOTE: art missing',name,file=sys.stderr);continue
        d=open(f,'rb').read();total+=len(d);out[k]='data:image/webp;base64,'+base64.b64encode(d).decode('ascii')
    print('art: %d images, %d KB'%(len(out),total//1024),file=sys.stderr)
    return '// painted card art (generated by build.py from ../art)\nvar SF_ART = '+json.dumps(out,separators=(',',':'))+';\n'

# ---------- debug page (unchanged from stage 1) ----------
b=rd(os.path.join(D,'src','debug.html'))
for f in ['data.js','engine.js','ai.js','debug-ui.js']:
    tag=f'<script src="{f}"></script>';assert tag in b,f
    b=b.replace(tag,'<script>\n'+rd(os.path.join(D,'src',f))+'\n</script>')
open(os.path.join(D,'debug.html'),'w',encoding='utf-8').write(b)

# ---------- the game ----------
SRC={'shell.js':os.path.join(SP,'shell','shell.js'),'gx-campaign.js':os.path.join(SP,'shell','gx-campaign.js'),'gx-viewport.js':os.path.join(SP,'shell','gx-viewport.js'),'gx-help.js':os.path.join(SP,'shell','gx-help.js'),'gx-tutor.js':os.path.join(SP,'shell','gx-tutor.js'),'perfhud.js':os.path.join(SP,'perf','perfhud.js'),
     'gameaudio.js':os.path.join(SP,'audio','gameaudio.js'),'audio-data.js':os.path.join(SP,'short-fuse','audio','audio-data.js'),
     'data.js':os.path.join(D,'src','data.js'),'engine.js':os.path.join(D,'src','engine.js'),'ai.js':os.path.join(D,'src','ai.js'),'netstrip.js':os.path.join(D,'src','netstrip.js'),
     'trystero.min.js':os.path.join(SP,'net','trystero.min.js'),'netroom.js':os.path.join(SP,'net','netroom.js')}
ORDER=['shell.js','gx-viewport.js','gx-help.js','gx-tutor.js','gx-campaign.js','campaign-data.js','perfhud.js','trystero.min.js','netroom.js','art-data.js','data.js','engine.js','ai.js','netstrip.js','texts.js','hlp.js','gameaudio.js','audio-data.js','sound.js','net.js','ui.js','tbl.js','extras.js','tutor.js','start.js']
h=rd(os.path.join(D,'head.html')).replace('/*SHELL_CSS*/',rd(os.path.join(SP,'shell','shell.css'))+'\n'+rd(os.path.join(SP,'shell','gx-help.css'))+'\n'+rd(os.path.join(SP,'shell','gx-tutor.css'))).replace('/*TABLE_CSS*/',rd(os.path.join(SP,'shell','gx-campaign.css'))+'\n'+rd(os.path.join(D,'table.css')))
body=rd(os.path.join(D,'body.html'))
body=body.replace('<!--CREDITS-->',rd(os.path.join(SP,'short-fuse','audio','credits.html')))
for f in ORDER:
    tag=f'<script src="{f}"></script>';assert tag in body,f
    if f=='campaign-data.js':src='window.CAMPAIGN = '+json.dumps(json.load(open(os.path.join(SP,'short-fuse','campaign.json'),encoding='utf-8')),separators=(',',':'),ensure_ascii=False)+';'
    elif f=='art-data.js':src=art_js()
    else:src=rd(SRC.get(f,os.path.join(D,f)))
    src=src.replace('</script','<\\/script')
    body=body.replace(tag,'<script>\n'+src+'\n</script>')
out=h+body
open(os.path.join(D,'shortfuse.html'),'w',encoding='utf-8').write(out)
js='\n'.join(x for x in re.findall(r'<script>(.*?)</script>',out,re.S))
open(os.path.join(D,'x.js'),'w',encoding='utf-8').write(js)
print('shortfuse.html',len(out.encode('utf-8')),'bytes')
