// Phone layout check (real WebGL via SwiftShader, isMobile + hasTouch). node lay-phone.js [WxH,...] [--before] [--2d] [--safe=t,r,b,l] [--hot]
// Plays a real human turn ONLY by touch: tap a crewmate's wire on the table -> zoom + "Call a value" pop-up -> value -> Snip -> result card -> Continue.
// --before = same build with ?phone=0 (the old layout): only measures the board.
const PW=require((process.env.PW||require('child_process').execSync('npm root -g').toString().trim()+'/playwright'));
const fs=require('fs'),path=require('path');const HERE=__dirname,OUT=path.join(HERE,'shots','ph');fs.mkdirSync(OUT,{recursive:true});fs.mkdirSync(path.join(HERE,'out'),{recursive:true});
const html=fs.readFileSync(path.join(HERE,'shortfuse.html'));
const SIZES=(process.argv[2]&&!process.argv[2].startsWith('--')?process.argv[2]:'390x844,844x390,360x740,740x360').split(',').map(s=>s.split('x').map(Number));
const BEFORE=process.argv.includes('--before'),TWO=process.argv.includes('--2d'),HOT=process.argv.includes('--hot');const SAFE=(process.argv.find(a=>a.startsWith('--safe='))||'').slice(7);
const NP=+((process.argv.find(a=>a.startsWith('--np='))||'').slice(5)||4),JOB=+((process.argv.find(a=>a.startsWith('--job='))||'').slice(6)||9);
(async()=>{const b=await PW.chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let bad=0;const rep=[];
for(const [W,H] of SIZES){const t=W+'x'+H+(BEFORE?'_before':'')+(TWO?'_2d':'');const ctx=await b.newContext({viewport:{width:W,height:H},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await ctx.route('**/*',r=>{const u=new URL(r.request().url());return u.host==='gns.test'?r.fulfill({status:200,contentType:'text/html',body:html}):r.abort()});
  const p=await ctx.newPage();p.setDefaultTimeout(120000);const errs=[];p.on('pageerror',e=>errs.push('pageerror '+e.message));p.on('console',m=>{if(m.type()==='error'&&!/net::|Failed to load resource/.test(m.text()))errs.push(m.text())});
  const log=(...a)=>console.log(t,...a);const prob=(...a)=>{bad++;log('PROBLEM',...a)};
  const q='?'+(BEFORE?'phone=0':'phone=1')+(TWO?'&2d':'')+(SAFE?'&safe='+SAFE:'');
  await p.goto('https://gns.test/'+q);await p.waitForTimeout(1200);await p.evaluate(()=>{try{localStorage.clear()}catch(e){}setSeed(5);setAiSeed(5);AIDELAY=60});
  const FIT=require('../../phfit.js');const shot=async n=>{(await FIT.run(p)).forEach(m=>prob('FIT '+n,m));await p.screenshot({path:path.join(OUT,`P_${t}_${n}.png`),timeout:150000})};
  const scroll=async tag=>{const r=await p.evaluate(()=>({h:document.documentElement.scrollHeight,w:document.documentElement.scrollWidth,vh:innerHeight,vw:innerWidth,bh:document.body.scrollHeight}));if(r.h>r.vh+1||r.w>r.vw+1||r.bh>r.vh+1)prob(tag,'SCROLL',JSON.stringify(r))};
  // projection of a wire (or any world point) to client px
  await p.evaluate(()=>{window.__proj=(x,y,z)=>{const K=SFKit._K;K.cam.updateMatrixWorld(true);const cv=document.querySelector('#c3');const R=cv.getBoundingClientRect();const v=new THREE.Vector3(x,y,z).project(K.cam);return [R.left+(v.x+1)/2*R.width,R.top+(1-v.y)/2*R.height]};
    window.__wire=(si,k)=>{const K=SFKit._K;SFKit.renderOnce();const r=K.recs[tid(G.st[si].w[k].u)];if(!r)return null;return window.__proj(r.p.x,r.p.y,r.p.z)};
    // size of one wire in px: pitch between two neighbouring slots of one rack * tile width / pitch
    window.__wsize=(si)=>{const K=SFKit._K;SFKit.renderOnce();const n=G.st[si].w.length;const C=document.querySelector('#c3').getBoundingClientRect();const cx=C.left+C.width/2;let best=null;for(let k=0;k+1<n;k++){const a=K.recs[tid(G.st[si].w[k].u)],c=K.recs[tid(G.st[si].w[k+1].u)];if(!a||!c||G.st[si].w[k].cut||G.st[si].w[k+1].cut)continue;const A=window.__proj(a.p.x,a.p.y,a.p.z),B=window.__proj(c.p.x,c.p.y,c.p.z);if(A[0]<C.left||A[0]>C.right)continue;const top=window.__proj(a.p.x,a.p.y+0.7,a.p.z),bot=window.__proj(a.p.x,a.p.y-0.7,a.p.z);const dd=Math.abs(A[0]-cx);if(!best||dd<best.dd)best={dd,w:Math.hypot(A[0]-B[0],A[1]-B[1])/1.13,h:Math.hypot(top[0]-bot[0],top[1]-bot[1])}}return best};
    // bbox of all racks (rows) in px, and the table plate
    window.__ring=()=>{const K=SFKit._K;SFKit.renderOnce();let x0=1e9,y0=1e9,x1=-1e9,y1=-1e9;for(const r of K.rows){if(!r.m)continue;const c=Math.cos(r.rot),s=Math.sin(r.rot);const hw=(r.m*1.13+.5)*r.s/2;for(const du of[-.5,2.5])for(const dx of[-hw,hw]){const X=dx,Z=du*r.s;const w=[X*c+Z*s+r.px,-X*s+Z*c+r.pz];const P=window.__proj(w[0],0.2,w[1]);x0=Math.min(x0,P[0]);x1=Math.max(x1,P[0]);y0=Math.min(y0,P[1]);y1=Math.max(y1,P[1])}}return [x0,y0,x1,y1]}});
  const metrics=async()=>p.evaluate(()=>{const R=document.querySelector('.gx-board').getBoundingClientRect();const cv=document.querySelector('#c3');const C=cv.getBoundingClientRect();const ring=SFKit._K.on?window.__ring():[0,0,0,0];
    const bar=document.querySelector('.gx-bar').getBoundingClientRect();let ow=1e9;for(let si=0;si<G.st.length;si++){if(ownerOf(si)===(UI.V&&UI.V.seat))continue;const z=window.__wsize(si);if(z)ow=Math.min(ow,z.w)}return {W:innerWidth,H:innerHeight,short:Math.min(innerWidth,innerHeight),board:[R.left,R.top,R.width,R.height].map(Math.round),canvas:[C.width,C.height].map(Math.round),ring:[ring[2]-ring[0],ring[3]-ring[1]].map(Math.round),ovWire:+ow.toFixed(1),ringBox:ring.map(Math.round),bar:[Math.round(bar.top),Math.round(bar.height)],mode:SFKit._K.layout&&SFKit._K.layout.mode}});
  const targets=async tag=>{const r=await p.evaluate(()=>{const o=[];for(const e of document.querySelectorAll('.gx-bar button,#ps button,#ppop button,#pc button,#netst button,#zb button,.zpan')){if(e.closest('[hidden]'))continue;const R=e.getBoundingClientRect();if(!R.width||!R.height)continue;const cs=getComputedStyle(e);if(cs.visibility==='hidden'||cs.display==='none')continue;if(R.right<0||R.left>innerWidth||R.bottom<0||R.top>innerHeight)continue;if(R.width<43.5||R.height<43.5)o.push((e.dataset.a||e.dataset.ph||e.className||e.tagName)+':'+Math.round(R.width)+'x'+Math.round(R.height))}return o});if(r.length)prob(tag,'SMALL TAP TARGETS',JSON.stringify(r.slice(0,6)));return r.length};
  const minTarget=async()=>p.evaluate(()=>{let m=1e9,w='';for(const e of document.querySelectorAll('.gx-bar button,#ps button,#ppop button,#pc button,#zb button,.zpan')){if(e.closest('[hidden]'))continue;const R=e.getBoundingClientRect();if(!R.width||!R.height)continue;const cs=getComputedStyle(e);if(cs.visibility==='hidden'||cs.display==='none')continue;if(R.right<0||R.left>innerWidth||R.bottom<0||R.top>innerHeight)continue;const s=Math.min(R.width,R.height);if(s<m){m=s;w=(e.dataset.a||e.dataset.ph||e.className||e.tagName)+':'+Math.round(R.width)+'x'+Math.round(R.height)}}return [Math.round(m),w]});
  const overlap=(A,B)=>A[0]<B[2]&&A[2]>B[0]&&A[1]<B[3]&&A[3]>B[1];
  const rectOf=async sel=>p.evaluate(s=>{const e=document.querySelector(s);if(!e)return null;const R=e.getBoundingClientRect();return [R.left,R.top,R.right,R.bottom].map(Math.round)},sel);
  const camDone=async()=>{for(let k=0;k<40;k++){const d=await p.evaluate(()=>!PX.cam);if(d)break;await p.waitForTimeout(150)}await p.waitForTimeout(150)};
  const waitHuman=async()=>{let ok=0;for(let k=0;k<160&&ok<3;k++){const s=await p.evaluate(()=>{const d=decider();return !!G.over||(UI.V&&UI.V.seat>=0&&d===UI.V.seat&&!G.q&&!!UI.V.legal&&!document.querySelector('#pc:not([hidden]) [data-a=take]'))});ok=s?ok+1:0;await p.waitForTimeout(250)}};
  const cards=async(only)=>{for(let k=0;k<14;k++){const kind=await p.evaluate(()=>{const c=document.querySelector('#pc:not([hidden])');if(!c)return null;return PX.card&&PX.card.kind});if(!kind)break;if(only&&!only.includes(kind))break;
      const btn=await p.evaluate(k=>{const c=document.querySelector('#pc:not([hidden])');const sel={brief:'[data-a=briefok]',res:'[data-ph=resok]',coach:'[data-a=coach]',q:'[data-a=q]',over:'[data-ph=dismiss]',pass:'[data-a=take]'}[k];const b=c&&c.querySelector(sel);if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]},kind);
      if(!btn)break;await p.touchscreen.tap(btn[0],btn[1]);await p.waitForTimeout(350)}};
  const metersFor=async tag=>{const m=await metrics();log(tag,JSON.stringify(m));return m};
  // 0. start screen (is the page usable?)
  await scroll('start');await shot('0start');
  if(BEFORE){await p.evaluate(([j,n])=>{showStart();UI.setup.job=j;UI.setup.np=n;UI.setup.seats=['human','ai','ai','ai','ai'];renderStart()},[JOB,NP]);await p.waitForTimeout(300);await p.click('[data-a=start]');await p.waitForTimeout(2000);
    await p.evaluate(()=>{const b=document.querySelector('[data-a=briefok]');if(b)b.click()});await p.waitForTimeout(1200);for(let k=0;k<6;k++){const qq=await p.$('#main [data-a=q]');if(!qq)break;await qq.click();await p.waitForTimeout(500)}
    for(let k=0;k<80;k++){const s=await p.evaluate(()=>!!(UI.V&&UI.V.legal&&decider()===UI.V.seat)||!!G.over);if(s)break;await p.waitForTimeout(300)}
    const m=await p.evaluate(()=>{const K=SFKit._K;SFKit.renderOnce();const cv=document.querySelector('#c3');const C=cv.getBoundingClientRect();const v=new THREE.Vector3();const pj=(x,y,z)=>{v.set(x,y,z).project(K.cam);return [C.left+(v.x+1)/2*C.width,C.top+(1-v.y)/2*C.height]};
      let x0=1e9,y0=1e9,x1=-1e9,y1=-1e9;const rows={};for(const r of K.rows){if(!r.m)continue;const c=Math.cos(r.rot),s=Math.sin(r.rot);const hw=(r.m*1.13+.5)*r.s/2;for(const du of[-.5,2.5])for(const dx of[-hw,hw]){const w=[dx*c+du*r.s*s+r.px,-dx*s+du*r.s*c+r.pz];const P=pj(w[0],.2,w[1]);x0=Math.min(x0,P[0]);x1=Math.max(x1,P[0]);y0=Math.min(y0,P[1]);y1=Math.max(y1,P[1])}}
      const ws=[];for(const id in K.recs){const r=K.recs[id];if(!r.key||r.key==='__gone'||r.data.cut)continue;(rows[r.key]=rows[r.key]||[]).push({s:r.slot,p:pj(r.p.x,r.p.y,r.p.z),mine:+r.key.split(':')[0]===K.st.my})}
      for(const k in rows){const a=rows[k].sort((u,w)=>u.s-w.s);for(let i=1;i<a.length;i++)if(a[i].s===a[i-1].s+1)ws.push({d:Math.hypot(a[i].p[0]-a[i-1].p[0],a[i].p[1]-a[i-1].p[1])/1.13,mine:a[0].mine})}
      const opp=ws.filter(x=>!x.mine).map(x=>x.d).sort((u,w)=>u-w);let sm=1e9,sw='';for(const e of document.querySelectorAll('button,[data-a]')){if(e.closest('[hidden]'))continue;const R=e.getBoundingClientRect();const cs=getComputedStyle(e);if(!R.width||!R.height||cs.visibility==='hidden'||R.bottom<0||R.top>innerHeight)continue;const s=Math.min(R.width,R.height);if(s<sm){sm=s;sw=(e.dataset.a||e.dataset.gx||e.className||e.tagName).toString().slice(0,20)}}
      return {W:innerWidth,H:innerHeight,short:Math.min(innerWidth,innerHeight),board:[Math.round(C.width),Math.round(C.height)],ring:[Math.round(x1-x0),Math.round(y1-y0)],oppWireMin:+(opp[0]||0).toFixed(1),oppWireMed:+(opp[opp.length>>1]||0).toFixed(1),smallestTap:[Math.round(sm),sw],mode:K.layout.mode}});
    log('BEFORE',JSON.stringify(m));rep.push({t,m});await shot('before');await ctx.close();continue}
  // 1. a solo job: briefing card, opening token question card, then my turn
  await p.evaluate(([j,n,hot])=>{showStart();UI.setup.job=j;UI.setup.np=n;UI.setup.seats=hot?['human','human','human','ai','ai'].slice(0,n):['human','ai','ai','ai','ai'];renderStart()},[JOB,NP,HOT]);await p.waitForTimeout(300);
  await p.tap('[data-a=start]');await p.waitForTimeout(1800);await scroll('brief');
  const brief=await p.evaluate(()=>({card:!document.querySelector('#pc').hidden,k:PX.card&&PX.card.kind,txt:document.querySelector('#pc').textContent.slice(0,40)}));if(!brief.card||brief.k!=='brief')prob('no briefing card',JSON.stringify(brief));
  await shot('1brief');await targets('brief');await cards(HOT?['brief']:null);await p.waitForTimeout(500);
  if(HOT){const pass=await p.evaluate(()=>({k:PX.card&&PX.card.kind,rack:!!document.querySelector('#ps .ps-rack:not([hidden]) .pw'),owner:document.querySelector('#ps .ps-rack')&&document.querySelector('#ps .ps-rack').dataset.owner}));log('hot pass',JSON.stringify(pass));if(pass.k!=='pass')prob('no pass card in hot-seat',JSON.stringify(pass));if(pass.rack)prob('my rack visible before the pass card was taken');await shot('1pass');await cards();await p.waitForTimeout(600);
    const taken=await p.evaluate(()=>({rack:!!document.querySelector('#ps .ps-rack:not([hidden]) .pw'),owner:document.querySelector('#ps .ps-rack').dataset.owner,seat:UI.V.seat}));if(!taken.rack||taken.owner!==String(taken.seat))prob('rack after taking the device is wrong',JSON.stringify(taken))}
  await cards();await waitHuman();await cards();await waitHuman();await p.waitForTimeout(400);
  if(TWO){ // 2D board fallback (no camera): wires are big tiles on a scrolling board; check sizes, no page scroll, one touch turn
    await scroll('2d turn');await shot('2d_turn');await targets('2d turn');
    const sz=await p.evaluate(()=>{let m=1e9;for(const e of document.querySelectorAll('#fb .sf2d-t')){const R=e.getBoundingClientRect();if(!R.width)continue;m=Math.min(m,R.width,R.height)}return Math.round(m)});log('2D smallest wire tile px',sz);if(sz<44)prob('2D wire tile smaller than 44 px',sz);
    const tg2=await p.evaluate(()=>{const L=UI.V.legal;const m=L.plain.filter(m=>m.ks.length===1)[0];const el=[...document.querySelectorAll('#fb .sf2d-hl')].find(e=>{const d=JSON.parse(e.getAttribute('data-sf'));return d.id===tid(G.st[m.st].w[m.ks[0]].u)});if(!el)return null;el.scrollIntoView({block:'center'});const R=el.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});
    if(tg2){await p.touchscreen.tap(tg2[0],tg2[1]);await p.waitForTimeout(600);const o=await p.evaluate(()=>({open:!document.querySelector('#ppop').hidden}));if(!o.open)prob('2D: wire tap did not open the pop-up');await shot('2d_popup');await targets('2d pop-up')}
    log('errors',JSON.stringify(errs.slice(0,4)));bad+=errs.length;await ctx.close();continue}
  await camDone();
  await scroll('turn');const m0=await metersFor('metrics');
  const need=FIT.share(W,H)*m0.short;if(m0.board[2]<need-1||m0.board[3]<need-1)prob('board smaller than 0.85 of the short side',JSON.stringify(m0.board),need);
  const ringDim=m0.W>m0.H?m0.ring[1]:m0.ring[0],needB=.85*Math.min(m0.board[2],m0.board[3]);if(ringDim<needB)prob('rack ring',m0.ring,(m0.W>m0.H?'height':'width'),'< 0.85 x the board short side',needB);
  await shot('2turn');await targets('turn');
  // board points inside the board and hit-testing to the canvas
  const whole=async tag=>{const r=await p.evaluate(()=>{const R=document.querySelector('.gx-board').getBoundingClientRect();const cv=document.querySelector('#c3');const out=[],cov={};let n=0;for(let si=0;si<G.st.length;si++){if(ownerOf(si)===UI.V.seat)continue;for(let k=0;k<G.st[si].w.length;k++){if(G.st[si].w[k].cut)continue;const P=window.__wire(si,k);if(!P)continue;n++;if(!(P[0]>=R.left&&P[0]<=R.right&&P[1]>=R.top&&P[1]<=R.bottom)){out.push(si+':'+k+':'+Math.round(P[0])+','+Math.round(P[1]));continue}const e=document.elementFromPoint(P[0],P[1]);if(!(e===cv||cv.contains(e)||(e&&e.closest('.sfk-ov,#zb')))){const kk=e?(e.id||String(e.className)||e.tagName):'none';cov[kk]=(cov[kk]||0)+1}}}return {n,out:out.slice(0,5),outN:out.length,cov}});
    if(r.outN||Object.keys(r.cov).length)prob(tag,'WIRES outside the board or covered',JSON.stringify(r));return r};
  await whole('turn overview');
  // my own rack strip: tap a wire -> what I know about it
  const own=await p.evaluate(()=>{const b=document.querySelector('#ps .ps-rack .pw:not(.cut)');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2,b.getAttribute('aria-label')]});
  if(!own)prob('no own wires in the strip');else{await p.touchscreen.tap(own[0],own[1]);await p.waitForTimeout(350);const o=await p.evaluate(()=>({open:!document.querySelector('#ppop').hidden,txt:document.querySelector('#ppop').textContent.slice(0,90)}));log('own wire',JSON.stringify(o));if(!o.open)prob('own wire pop-up did not open');await shot('3own');await targets('own pop-up');
    await p.touchscreen.tap(...(await p.evaluate(()=>{const b=document.querySelector('#ppop [data-ph=pclose]');const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]})));await p.waitForTimeout(250);if(!(await p.evaluate(()=>document.querySelector('#ppop').hidden)))prob('x did not close the own wire pop-up')}
  // chips: job -> pop-up, closed by Esc
  const chip=await p.evaluate(()=>{const b=document.querySelector('#ps .ps-chips [data-k=job]');if(!b)return null;b.scrollIntoView({inline:'center',block:'nearest'});const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});
  if(!chip)prob('no job chip');else{await p.touchscreen.tap(...chip);await p.waitForTimeout(300);const o=await p.evaluate(()=>({open:!document.querySelector('#ppop').hidden,txt:document.querySelector('#ppop').textContent.slice(0,60)}));if(!o.open)prob('job chip pop-up did not open');await shot('4chip');await p.keyboard.press('Escape');await p.waitForTimeout(250);if(!(await p.evaluate(()=>document.querySelector('#ppop').hidden)))prob('Esc did not close the chip pop-up')}
  const gchip=await p.evaluate(()=>{const b=document.querySelector('#ps .ps-chips [data-k=eq]');if(!b)return null;b.scrollIntoView({inline:'center',block:'nearest'});const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});
  if(gchip){await p.touchscreen.tap(...gchip);await p.waitForTimeout(300);const o=await p.evaluate(()=>({open:!document.querySelector('#ppop').hidden,txt:document.querySelector('#ppop').textContent.slice(0,60)}));if(!o.open)prob('gear chip pop-up did not open');await shot('4gear');await p.keyboard.press('Escape');await p.waitForTimeout(250)}
  // 2. full human turns by touch
  let turns=0,zoomChecked=false;
  for(let round=0;round<30&&turns<4;round++){await waitHuman();await cards();const st=await p.evaluate(()=>({over:!!G.over,me:!!(UI.V&&UI.V.seat>=0&&decider()===UI.V.seat&&UI.V.legal&&!G.q)}));if(st.over)break;if(!st.me){await p.waitForTimeout(400);continue}
    await camDone();
    // choose a target wire: the first legal plain target, on any crewmate rack
    const tg=await p.evaluate(()=>{const L=UI.V.legal;const hold=new Set();for(const st of UI.V.stands)if(st.mine)for(const x of st.slots)if(!x.cut&&x.v!=null)hold.add(x.v);
      const c=L.plain.filter(m=>m.ks.length===1);if(!c.length)return null;const m=c[Math.floor(Math.random()*c.length)];const P=window.__wire(m.st,m.ks[0]);return {st:m.st,k:m.ks[0],P,solo:L.solo.length}});
    if(!tg){log('no plain target; passing the turn by other action');const o=await p.evaluate(()=>{const b=document.querySelector('#ps .ps-acts [data-a]');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});if(o)await p.touchscreen.tap(...o);await p.waitForTimeout(600);turns++;continue}
    // a solo cut sometimes, through the strip
    if(tg.solo&&turns===1){const sb=await p.evaluate(()=>{const b=document.querySelector('#ps .ps-acts [data-a=solo]');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});if(sb){await shot('5solo');await p.touchscreen.tap(...sb);await p.waitForTimeout(700);turns++;await shot('5solo_res');await cards();continue}}
    if(!tg.P){prob('target wire has no screen position');break}
    // tap in the overview (wires are small: this is only the first tap, it zooms and selects)
    const inside=await p.evaluate(P=>{const R=document.querySelector('.gx-board').getBoundingClientRect();const e=document.elementFromPoint(P[0],P[1]);return P[0]>=R.left&&P[0]<=R.right&&P[1]>=R.top&&P[1]<=R.bottom&&!!e&&e.id==='c3'},tg.P);if(!inside)prob('target wire not hit-testing to the table in the overview',JSON.stringify(tg.P));
    await p.touchscreen.tap(tg.P[0],tg.P[1]);await p.waitForTimeout(900);await camDone();
    const z=await p.evaluate(()=>({zoom:PX.zoom&&PX.zoom.key,pop:!document.querySelector('#ppop').hidden,sel:UI.sel&&UI.sel.tg&&UI.sel.tg.length,card:PX.card&&PX.card.kind,zb:!document.querySelector('#zb').hidden}));
    if(!z.zoom)prob('tap on a wire did not zoom to its rack',JSON.stringify(z));if(!z.zb)prob('zoom bar missing');
    // zoomed: wire size, every wire of the rack on the table, pointed wire hit-tests
    const ws=await p.evaluate(si=>window.__wsize(si),tg.st);log('zoomed wire px',JSON.stringify(ws));if(!ws||ws.w<43.5||ws.h<43.5)prob('zoomed wire smaller than 44 px',JSON.stringify(ws));
    const P2=await p.evaluate(([si,k])=>window.__wire(si,k),[tg.st,tg.k]);
    const hit=await p.evaluate(P=>{const R=document.querySelector('.gx-board').getBoundingClientRect();const e=document.elementFromPoint(P[0],P[1]);return P[0]>=R.left&&P[0]<=R.right&&P[1]>=R.top&&P[1]<=R.bottom&&!!e&&e.id==='c3'},P2);
    if(!hit)prob('pointed wire is outside the zoomed view',JSON.stringify(P2));
    if(!z.pop){// not a legal pick (e.g. selection did not stick): tap again in the zoom
      await p.touchscreen.tap(P2[0],P2[1]);await p.waitForTimeout(500)}
    await p.waitForTimeout(500);const pp=await p.evaluate(()=>{const e=document.querySelector('#ppop');const R=e.getBoundingClientRect();const B=document.querySelector('.gx-board').getBoundingClientRect();return {open:!e.hidden,pop:[R.left,R.top,R.right,R.bottom].map(Math.round),board:[B.left,B.top,B.right,B.bottom].map(Math.round),vals:e.querySelectorAll('.ph-v').length,txt:e.textContent.slice(0,100)}});
    log('call pop-up',JSON.stringify(pp));if(!pp.open){prob('Call a value pop-up did not open',JSON.stringify(pp));break}
    if(overlap(pp.pop,pp.board))prob('POP-UP covers the table',JSON.stringify(pp));
    const P3=await p.evaluate(([si,k])=>window.__wire(si,k),[tg.st,tg.k]);if(P3&&P3[0]>=pp.pop[0]&&P3[0]<=pp.pop[2]&&P3[1]>=pp.pop[1]&&P3[1]<=pp.pop[3])prob('POP-UP covers the pointed wire',JSON.stringify([P3,pp.pop]));
    if(!zoomChecked){zoomChecked=true;const fr0=await p.evaluate(()=>SFKit._K.frame.n);await p.waitForTimeout(1200);log('webgl',JSON.stringify(await p.evaluate(fr0=>({on:SFKit._K.on,lost:window.SF_LOST||0,frames:SFKit._K.frame.n-fr0,tris:SFKit._K.r.info.render.triangles,pan:PX.zoom&&PX.zoom.pan,cam:SFKit._K.camState.pos.toArray().map(x=>+x.toFixed(2)),anim:!!PX.cam}),fr0)));await shot('6zoom_popup');await targets('call pop-up');
      // a tap on an empty spot of the table closes the pop-up (tap outside); then point at the wire again
      const em=await p.evaluate(()=>{const R=document.querySelector('#c3').getBoundingClientRect();for(const [fx,fy] of [[.5,.9],[.5,.2],[.25,.9],[.75,.9],[.5,.5]]){const x=R.left+R.width*fx,y=R.top+R.height*fy;if(!SFKit.pick(x,y)&&!document.elementFromPoint(x,y).closest('#zb,.zpan'))return [x,y]}return null});
      if(!em)log('no empty table spot found for the tap-outside check');else{await p.touchscreen.tap(em[0],em[1]);await p.waitForTimeout(500);if(!(await p.evaluate(()=>document.querySelector('#ppop').hidden)))prob('tap on the empty table did not close the pop-up');
        const Pw=await p.evaluate(([si,k])=>window.__wire(si,k),[tg.st,tg.k]);await p.touchscreen.tap(Pw[0],Pw[1]);await p.waitForTimeout(700);if(await p.evaluate(()=>document.querySelector('#ppop').hidden))prob('pointing at the wire again did not reopen the pop-up')}
      // drag along the rack (if it is longer than the screen) and the arrows
      const pan0=await p.evaluate(()=>PX.zoom?PX.zoom.pan:0);const half=await p.evaluate(()=>PX.zoom?PX.zoom.half:0);log('rack pan range',half.toFixed(2),'pan',pan0.toFixed(2));
      if(half>.4){const ar=await p.evaluate(()=>{const b=document.querySelector('#zpr:not([hidden]),#zpl:not([hidden])');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2,b.id]});if(!ar)prob('rack longer than the screen but no slide arrow');else{await p.touchscreen.tap(ar[0],ar[1]);await p.waitForTimeout(200);const pan1=await p.evaluate(()=>PX.zoom.pan);if(Math.abs(pan1-pan0)<.05)prob('slide arrow did nothing');await p.touchscreen.tap(...(await p.evaluate(id=>{const o=document.querySelector(id==='zpr'?'#zpl:not([hidden])':'#zpr:not([hidden])');if(!o)return [0,0];const R=o.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]},ar[2])));await p.waitForTimeout(200)}}
      // drag along the rack with a finger / mouse (dispatches pointer events on the canvas): the view must slide
      if(half>.4){const dg=await p.evaluate(()=>{const R=document.querySelector('#c3').getBoundingClientRect();return {x:R.left+R.width*.5,y:R.top+R.height*.72,pan:PX.zoom.pan,half:PX.zoom.half}});const dx=dg.pan<0?-110:110;
        await p.mouse.move(dg.x,dg.y);await p.mouse.down();await p.mouse.move(dg.x+dx/2,dg.y,{steps:4});await p.mouse.move(dg.x+dx,dg.y,{steps:4});await p.mouse.up();await p.waitForTimeout(300);
        const pn=await p.evaluate(()=>PX.zoom.pan);if(Math.abs(pn-dg.pan)<.05)prob('dragging the table did not slide the rack',dg.pan,pn);else log('drag slid the rack',dg.pan.toFixed(2),'->',pn.toFixed(2))}
      // next rack and back
      const key0=await p.evaluate(()=>PX.zoom&&PX.zoom.key);await p.touchscreen.tap(...(await p.evaluate(()=>{const b=document.querySelector('#zb [data-ph=znext]');const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]})));await p.waitForTimeout(500);await camDone();const key1=await p.evaluate(()=>PX.zoom&&PX.zoom.key);if(key1===key0)prob('next rack button did nothing');
      await shot('6zoom_next');await p.touchscreen.tap(...(await p.evaluate(()=>{const b=document.querySelector('#zb [data-ph=zprev]');const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]})));await p.waitForTimeout(500);await camDone();
      // the rack change dropped the target: bring the wire into view with the slide arrows, then point at it again
      for(let k=0;k<8;k++){const P4=await p.evaluate(([si,k])=>{const P=window.__wire(si,k);const R=document.querySelector('.gx-board').getBoundingClientRect();return {P,l:P[0]<R.left+30,r:P[0]>R.right-30}},[tg.st,tg.k]);if(!P4.l&&!P4.r)break;
        const id=P4.l?'#zpl:not([hidden])':'#zpr:not([hidden])';const ab=await p.evaluate(id=>{const b=document.querySelector(id);if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]},id);if(!ab){prob('wire off screen but no slide arrow',id);break}await p.touchscreen.tap(ab[0],ab[1]);await p.waitForTimeout(250)}
      const P5=await p.evaluate(([si,k])=>window.__wire(si,k),[tg.st,tg.k]);await p.touchscreen.tap(P5[0],P5[1]);await p.waitForTimeout(700);const sel2=await p.evaluate(()=>!!(UI.sel&&UI.sel.tg&&UI.sel.tg.length));if(!sel2)prob('pointing at the wire again after the rack change did not select it')}
    // value (the recommended one if marked), then Snip
    const v=await p.evaluate(()=>{const b=document.querySelector('#ppop .ph-v.best')||document.querySelector('#ppop .ph-v');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2,b.dataset.v]});
    if(!v){log('no value I could say here: closing');await p.touchscreen.tap(...(await p.evaluate(()=>{const b=document.querySelector('#ppop [data-ph=pclose]');const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]})));await p.waitForTimeout(400);turns++;continue}
    await p.touchscreen.tap(v[0],v[1]);await p.waitForTimeout(400);
    const go=await p.evaluate(()=>{const b=document.querySelector('#ppop [data-a=dual]:not([disabled])');if(!b)return null;const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]});
    if(turns===0)await shot('7value');
    if(!go){prob('no Snip button after choosing a value');break}
    await p.touchscreen.tap(go[0],go[1]);await p.waitForTimeout(700);
    const rc=await p.evaluate(()=>({k:PX.card&&PX.card.kind,txt:document.querySelector('#pc').textContent.slice(0,50)}));log('after snip',JSON.stringify(rc));
    if(turns===0){if(rc.k!=='res'&&!(HOT&&rc.k==='pass'))prob('no result card after my move',JSON.stringify(rc));await shot('8result');await targets('result card');const bb=await p.evaluate(()=>{const e=document.querySelector('#pc');const R=e.getBoundingClientRect();const B=document.querySelector('.gx-board').getBoundingClientRect();return [[R.left,R.top,R.right,R.bottom].map(Math.round),[B.left,B.top,B.right,B.bottom].map(Math.round)]});if(overlap(bb[0],bb[1]))prob('result card covers the table',JSON.stringify(bb))}
    await cards();turns++;await p.waitForTimeout(400)}
  await waitHuman();await cards();await camDone();await p.waitForTimeout(500);await scroll('later');await whole('later');await shot('9later');
  // drawers (menu, job, gear, know)
  for(const id of['setd','knowd','missiond','geard']){await p.touchscreen.tap(...(await p.evaluate(id=>{const b=document.querySelector(`.gx-bar [data-gx="${id}"]`);const R=b.getBoundingClientRect();return [R.left+R.width/2,R.top+R.height/2]},id)));await p.waitForTimeout(700);await scroll('drawer '+id);if(id==='setd')await shot('10menu');await p.keyboard.press('Escape');await p.waitForTimeout(350)}
  // game over card
  await p.evaluate(()=>{AIDELAY=0;ANIM=0;let n=0;while(!G.over&&n++<4000){const s=sideToAct();if(s<0){const st=aiStep();if(!st){tick(5);continue}performMove(st.m,st.seat);continue}if(isHuman(s)){const mv=aiMove(s);performMove(mv,s);continue}performMove(aiMove(s),s)}ANIM=1;refresh()});await p.waitForTimeout(1500);
  await scroll('over');const ov=await p.evaluate(()=>({k:PX.card&&PX.card.kind}));if(ov.k!=='over')prob('no game over card',JSON.stringify(ov));await shot('11over');await targets('over card');
  await cards();await p.waitForTimeout(400);await whole('over dismissed').catch(()=>{});
  const mt=await minTarget();log('smallest tap target',JSON.stringify(mt));
  log('errors',JSON.stringify(errs.slice(0,4)));bad+=errs.length;rep.push({t,m0,mt});await ctx.close()}
fs.writeFileSync(path.join(HERE,'out','layphone'+(BEFORE?'_before':'')+(HOT?'_hot':'')+'.json'),JSON.stringify(rep,null,1));console.log('PROBLEMS',bad);await b.close()})().catch(e=>{console.error('FATAL',e);process.exit(1)});
