// Named rule scenarios: the five riskiest rules from the research, then one scenario per special job mechanic.
// Each scenario builds a real game, rigs the stands where needed (all other wires go to the box), plays real moves through performMove and checks the result.
const {load}=require('./tools/load');
const X=load(['data.js','engine.js','ai.js']);const E=X.E;
const B=(v,c)=>(v-1)*4+(c||0),RD=v=>47+v,YL=v=>58+v; // blue v copy c, red v.5, yellow v.1
let pass=0,fail=0;const fails=[];
function T(name,fn){try{const r=fn();if(r===false)throw new Error('returned false');pass++;console.log('PASS',name)}catch(e){fail++;fails.push(name);console.log('FAIL',name,'-',e.message.split('\n')[0])}}
function ok(c,msg){if(!c)throw new Error(msg||'assertion failed')}
function eq(a,b,msg){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error((msg||'')+` expected ${JSON.stringify(b)} got ${JSON.stringify(a)}`)}
function inv(){const v=X.checkInvariants();ok(!v.length,'invariants: '+v[0])}
function toAct(lim){let k=0;const L=lim==null?400:lim;while(!X.G.over&&k++<L){if(!X.G.q&&X.G.step==='act')return;const st=X.ai.aiStep();if(!st)return;X.performMove(st.m,st.seat)}}
function toPlay(){let k=0;while(!X.G.over&&X.G.phase==='setup'&&k++<200){const st=X.ai.aiStep();if(!st)return;X.performMove(st.m,st.seat)}}
function game(n,np,o){X.setSeed((o&&o.seed)||11);X.ai.setAiSeed(3);X.newGame(Object.assign({np,mission:n,mode:'ai',captain:0},o||{}));return X.G}
// replace every stand's contents (ids in the given order; sorted unless keep) and send all other wires to the box
function rig(stands,o){o=o||{};const G=X.G;const used=stands.flat();if(o.robot)G.robot.w=o.robot.slice();const keep=new Set([...(G.robot?G.robot.w:[]),...G.pile,...G.aside]);
  G.box=[];for(let id=0;id<70;id++)if(!used.includes(id)&&!keep.has(id))G.box.push(id);G.gone=[];if(!o.robot&&G.robot)G.robot.w=G.robot.w.filter(id=>!used.includes(id));
  G.pile=G.pile.filter(id=>!used.includes(id));G.aside=G.aside.filter(id=>!used.includes(id));
  stands.forEach((ids,i)=>{const w=ids.map(id=>E.newSlot(id));if(!o.keep)w.sort((a,b)=>E.WIRES[a.id].s-E.WIRES[b.id].s);G.st[i].w=w;G.st[i].side=[]});
  G.tokSup=E.clone(E.INFO_TOKENS);G.marks=[];G.tot={};for(const id of [...used,...(G.robot?G.robot.w:[]),...G.pile]){const v=E.cv(id);if(v!=='R')G.tot[v]=(G.tot[v]||0)+1}
  G.fin={};G.valid=[];G.ann=[];G.hist=[];for(const e of G.eq){if(!o.keepEq)e.st='locked'}}
function act(seat){const G=X.G;G.phase='turn';G.q=null;G.ag=[];G.tfx={};G.cur=seat;G.actor=seat;G.step='act';if(!G.round)G.round=1}
function mv(m,seat){const r=X.performMove(m,seat==null?X.G.actor:seat);return r}
function must(m,seat){const r=mv(m,seat);ok(r.success,'move rejected: '+r.error+' '+JSON.stringify(m));return r}
function bad(m,seat,why){const r=mv(m,seat);ok(!r.success,'move should be illegal: '+JSON.stringify(m));if(why)ok(r.error.includes(why),`wrong reason "${r.error}"`);return r}
const slots=si=>X.G.st[si].w;const K=(si,id)=>{const k=X.G.st[si].w.findIndex(x=>x.id===id);ok(k>=0,'wire not on stand');return k};const filler=(not,n)=>{const o=[];for(let v=1;v<=12&&o.length<n;v++)if(!not.includes(v))o.push(v);return o};const cutN=si=>slots(si).filter(x=>x.cut).length;
function answer(f){ok(X.G.q,'expected a question');const i=f?X.G.q.opts.findIndex(f):0;ok(i>=0,'option not found');must({a:'q',i},X.G.q.who)}
function eqReady(id){const e=X.G.eq.find(x=>x.id===id);if(e){e.st='ready';e.down=0}else X.G.eq.push({id,st:'ready',down:0,cover:null,perm:0});X.G.eqOut=X.G.eqOut.filter(x=>x!==id);X.G.eqPool=X.G.eqPool.filter(x=>x!==id)}
// ================= the five riskiest rules =================
console.log('--- 1. two stands per player');
T('2 players: 2 stands each; 3 players: foreman 2, others 1; 4-5 players: 1 each',()=>{for(const [np,want] of [[2,[2,2]],[3,[2,1,1]],[4,[1,1,1,1]],[5,[1,1,1,1,1]]]){game(4,np);eq(X.G.seats.map(s=>E.standsOf(s.i).length),want,np+'p')}});
T('dealing is even across stands (difference at most one)',()=>{for(const np of [2,3,4,5]){game(8,np);const n=X.G.st.map(s=>s.w.length);ok(Math.max(...n)-Math.min(...n)<=1,JSON.stringify(n))}});
T('a two-stand player places only one opening token',()=>{game(4,2);toAct();for(const s of [0,1]){const n=E.standsOf(s).reduce((a,si)=>a+slots(si).reduce((b,x)=>b+x.tok.length,0),0);eq(n,1,'tokens of seat '+s)}});
T('the two stands are one hand: solo cut across both stands',()=>{game(4,2);toAct();rig([[B(5,0),B(5,1),B(2)],[B(5,2),B(5,3),B(9)],[B(3),B(4)],[B(6),B(7)]]);act(0);must({a:'solo',v:5});eq(cutN(0)+cutN(1),4)});
T('Sweep answers once per stand for a two-stand player',()=>{game(9,2);toAct();rig([[B(5),B(2)],[B(6),B(9)],[B(5,1),B(7)],[B(8),B(10)]]);eqReady('eq8');act(0);must({a:'eq',id:'eq8',v:5});const a=X.G.ann.find(x=>x.k==='sweep');eq(a.res.map(r=>r.yes),[1,0,1,0])});
T('Handsets: the incoming wire goes on the stand the outgoing one left',()=>{game(9,2);toAct();rig([[B(2),B(4)],[B(6),B(9)],[B(5,1),B(7)],[B(8),B(10)]]);eqReady('eq2');act(0);must({a:'eq',id:'eq2',s:1,k:0,to:1});answer(o=>o.d.ru===slots(3)[0].u);ok(slots(1).some(x=>x.id===B(8)),'8 arrives on stand 2');ok(slots(3).some(x=>x.id===B(6)),'6 arrives on the stand the 8 left');inv()});
console.log('--- 2. solo-cut conditions');
T('all four in hand: legal; three in hand with one elsewhere: illegal',()=>{game(4,4);toAct();rig([[B(5,0),B(5,1),B(5,2),B(7,0),B(7,1),B(7,2),B(7,3)],[B(5,3),B(9)],[B(10)],[B(11)]]);act(0);bad({a:'solo',v:5},0,'remaining');must({a:'solo',v:7});eq(cutN(0),4)});
T('last two after two were cut: legal; two in hand with two uncut elsewhere: illegal',()=>{game(4,4);toAct();rig([[B(5,0),B(5,1),B(6,0),B(6,1)],[B(5,2),B(5,3),B(6,2),B(6,3)],[B(10)],[B(11)]]);slots(1)[0].cut=1;slots(1)[1].cut=1;act(0);bad({a:'solo',v:6});must({a:'solo',v:5})});
T('yellow solo: both yellows in play in one hand',()=>{game(4,4);toAct();rig([[YL(2),YL(6),B(1)],[B(5)],[B(10)],[B(11)]]);act(0);must({a:'solo',v:'Y'});eq(cutN(0),2)});
T('a dual cut can never be made with a value you do not hold',()=>{game(4,4);toAct();rig([[B(2),B(3)],[B(5),B(9)],[B(10)],[B(11)]]);act(0);bad({a:'dual',st:1,ks:[0],v:5},0,'hold')});
console.log('--- 3. Twin Probe (Double Detector) and red wires');
T('one red and one non-match: no explosion, the token goes on the non-red wire, one step burns',()=>{game(4,4);toAct();rig([[B(9),B(1)],[RD(3),B(4),B(10)],[B(11)],[B(12)]]);act(0);const d0=X.G.dial;must({a:'dual',st:1,ks:[0,1],v:9,tool:'dd'});ok(!X.G.over,'no boom');eq(X.G.dial,d0-1);eq(slots(1)[1].tok.map(t=>t.v),[4]);eq(slots(1)[0].tok.length,0)});
T('both pointed wires red: explosion',()=>{game(4,4);toAct();rig([[B(9),B(1)],[RD(3),RD(5),B(10)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0,1],v:9,tool:'dd'});ok(X.G.over&&!X.G.over.win)});
T('the Twin Probe never names yellow',()=>{game(4,4);toAct();rig([[YL(2),B(1)],[YL(3),B(4),B(10)],[B(11)],[B(12)]]);act(0);bad({a:'dual',st:1,ks:[0,1],v:'Y',tool:'dd'},0,'yellow')});
T('both pointed wires match: the crewmate chooses which one to cut',()=>{game(4,4);toAct();rig([[B(9),B(1)],[B(9,1),B(9,2),B(10)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0,1],v:9,tool:'dd'});eq(X.G.q&&X.G.q.kind,'pickMatch');eq(X.G.q.who,1);answer((o,i)=>i===1);ok(slots(1)[1].cut&&!slots(1)[0].cut)});
T('the Twin Probe is used once per job',()=>{game(4,4);toAct();rig([[B(9),B(9,3),B(1)],[B(9,1),B(9,2),B(10)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0,1],v:9,tool:'dd'});answer();act(0);bad({a:'dual',st:1,ks:[1,2],v:9,tool:'dd'},0,'not available')});
console.log('--- 4. red and yellow have no number');
T('a red 7.5 is not a 7 for the Sweep',()=>{game(9,4);toAct();rig([[B(5)],[RD(7),B(9)],[B(7),B(10)],[B(11)]]);eqReady('eq8');act(0);must({a:'eq',id:'eq8',v:7});eq(X.G.ann[0].res.map(r=>r.yes),[0,0,1,0])});
T('nobody may name red; yellow is named as "yellow"',()=>{game(4,4);toAct();rig([[YL(4),B(1)],[YL(8),B(9)],[RD(3),B(10)],[B(11)]]);act(0);bad({a:'dual',st:2,ks:[0],v:'R'});must({a:'dual',st:1,ks:[0],v:'Y'});eq(cutN(0)+cutN(1),2)});
T('a miss on a yellow wire shows the yellow token',()=>{game(4,4);toAct();rig([[B(9),B(1)],[YL(8),B(10)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0],v:9});eq(slots(1)[0].tok[0].t,'y')});
T('yellow breaks restrictions A-E and passes F',()=>{game(32,4);toAct();rig([[YL(4),B(2),B(5)],[YL(8),B(9),B(4)],[B(10)],[B(11)]]);X.G.ms.gcon='A';act(0);bad({a:'dual',st:1,ks:[0],v:'Y'},0,'restriction');X.G.ms.gcon='F';act(0);must({a:'dual',st:1,ks:[0],v:'Y'})});
T('the Two-Value Probe may include yellow',()=>{game(8,4);toAct();rig([[YL(4),B(2)],[YL(8),B(9)],[B(10)],[B(11)]]);eqReady('eq10');act(0);must({a:'dual',st:1,ks:[K(1,YL(8))],v:2,v2:'Y',two:'eq10'});ok(slots(1)[K(1,YL(8))].cut);ok(X.G.ann.some(a=>a.k==='holds'&&a.v===2),'announces the other value')});
console.log('--- 5. equipment unlock timing and fuse direction');
T('Rewind unlocks the moment the first two 6s are cut and works at once, once',()=>{game(4,4);toAct();rig([[B(6),B(6,1),B(1)],[B(6,2),B(9)],[B(6,3),B(10)],[B(11)]]);eqReady('eq6');X.G.eq.find(e=>e.id==='eq6').st='locked';act(0);
  bad({a:'eq',id:'eq6'},0);X.G.dial=2;must({a:'dual',st:1,ks:[0],v:6});eq(X.G.eq.find(e=>e.id==='eq6').st,'ready');must({a:'eq',id:'eq6'},2);eq(X.G.dial,3);bad({a:'eq',id:'eq6'},2)});
T('a miss burns one step; the last step is the explosion; the fuse never exceeds 6',()=>{game(4,4);toAct();rig([[B(9),B(1)],[B(4),B(10)],[B(11)],[B(12)]]);act(0);X.G.dial=2;must({a:'dual',st:1,ks:[0],v:9});eq(X.G.dial,1);act(0);must({a:'dual',st:1,ks:[1],v:9});ok(X.G.over&&!X.G.over.win);
  game(4,5);toAct();eqReady('eq6');act(0);X.G.dial=6;bad({a:'eq',id:'eq6'},0,'cannot turn back')});
T('fuse start: player count; jobs 41/55/60/62 at 1; job 51 one further',()=>{for(const np of [2,3,4,5]){eq(game(4,np).dial,np)}for(const n of [41,55,60,62])eq(game(n,4).dial,1,'job '+n);eq(game(51,3).dial,4);eq(game(51,5).dial,6)});
T('Damper: a miss does not burn and a red does not explode, red gets no token',()=>{game(9,4);toAct();rig([[B(9),B(1)],[RD(3),B(4),B(10)],[B(11)],[B(12)]]);eqReady('eq9');act(0);const d=X.G.dial;must({a:'eq',id:'eq9'});must({a:'dual',st:1,ks:[0],v:9});ok(!X.G.over);eq(X.G.dial,d);eq(slots(1)[0].tok.length,0)});
T('instant cards fire on unlock (Hidden Compartment adds two cards)',()=>{game(9,4);toAct();rig([[YL(2),B(1)],[YL(5),B(9)],[B(10)],[B(11)]]);X.G.eq.push({id:'eqY',st:'locked',down:0,cover:null,perm:0});X.G.eqPool=X.G.eqPool.filter(x=>x!=='eqY');X.G.eqOut=X.G.eqOut.filter(x=>x!=='eqY');const n=X.G.eq.length;act(0);must({a:'dual',st:1,ks:[0],v:'Y'});eq(X.G.eq.length,n+2);inv()});
T('equipment needs the FIRST two wires: one cut is not enough',()=>{game(9,4);toAct();rig([[B(4),B(1)],[B(4,1),B(9)],[B(10)],[B(11)]]);const e=X.G.eq[0];e.id=e.id;X.G.eq=[{id:'eq4',st:'locked',down:0,cover:null,perm:0}];X.G.eqPool=X.G.eqPool.filter(x=>x!=='eq4');X.G.eqOut=E.clone(Object.keys(E.EQUIP)).filter(x=>x!=='eq4'&&!X.G.eqPool.includes(x));act(0);must({a:'dual',st:1,ks:[0],v:4});eq(X.G.eq[0].st,'ready')});
T('a crew member with only reds reveals them at the start of their turn',()=>{game(4,4);toAct();rig([[B(9),B(1)],[RD(3),RD(6)],[B(9,1),B(11)],[B(1,1),B(12)]]);act(0);must({a:'dual',st:2,ks:[0],v:9});ok(slots(1).every(x=>x.cut),'reds revealed');eq(X.G.cur,2)});
// ================= job mechanics =================
console.log('--- job mechanics');
T('9 order cards: the second value is locked until two of the first are cut',()=>{game(9,4);toAct();X.G.ms.gate={vals:[3,5,8],at:0,req:2};rig([[B(5),B(3),B(1)],[B(5,1),B(3,1),B(9)],[B(10)],[B(11)]]);act(0);bad({a:'dual',st:1,ks:[1],v:5},0,'order');must({a:'dual',st:1,ks:[0],v:3});eq(X.G.ms.gate.at,1)});
T('16 order with side B: all four of the first value first',()=>{game(16,4);toAct();X.G.ms.gate.vals=[3,5,8];rig([[B(5),B(3),B(3,2),B(1)],[B(5,1),B(3,1),B(3,3),B(9)],[B(10)],[B(11)]]);act(0);must({a:'dual',st:1,ks:[0],v:3});act(0);bad({a:'dual',st:1,ks:[1],v:5},0,'order')});
T('10 free order: after a turn anyone may claim, but not twice in a row',()=>{game(10,4);toAct();eq(X.G.step,'act');const s=X.G.actor;const vm=X.validMoves(s).filter(m=>m.a==='dual');must(vm[0],s);toAct(5);if(X.G.step==='claim'){ok(!X.validMoves(s).some(m=>m.a==='claim'),'last player cannot claim');const o=(s+1)%4;must({a:'claim'},o);eq(X.G.actor,o)}});
T('10 timer: the clock running out is a loss',()=>{game(10,4);toAct();X.G.clock=899;E.advanceClock(5);E.hook('tick');ok(X.G.over&&!X.G.over.win)});
T('11 a blue value acts as red: cannot be named, revealed at the end',()=>{game(11,4);toAct();const v=X.G.ms.fakeRed;eq(E.cv(B(v)),'R');rig([[B(v),B(1)],[B(v,1),B(9)],[B(1,1)],[B(11)]]);act(0);bad({a:'dual',st:1,ks:[0],v})});
T('12 covered equipment: needs its own value AND the cover value',()=>{game(12,4);toAct();rig([[B(6),B(6,1),B(2),B(1)],[B(6,2),B(2,1),B(9)],[B(6,3),B(10)],[B(11)]]);X.G.eq=[{id:'eq6',st:'locked',down:0,cover:2,perm:0}];X.G.eqPool=X.G.eqPool.filter(x=>x!=='eq6');X.G.eqOut=Object.keys(E.EQUIP).filter(x=>x!=='eq6'&&!X.G.eqPool.includes(x));
  act(0);must({a:'dual',st:1,ks:[K(1,B(6,2))],v:6});eq(X.G.eq[0].st,'locked');act(0);must({a:'dual',st:1,ks:[K(1,B(2,1))],v:2});eq(X.G.eq[0].st,'ready');inv()});
T('13 the three reds: no reveal; pointing at all three cuts them; a wrong one explodes',()=>{game(13,4);toAct();rig([[RD(2),B(1)],[RD(5),B(9)],[RD(8),B(10)],[B(11)]]);act(0);must({a:'multi',kind:'red3',tg:[{s:0,k:1},{s:1,k:0},{s:2,k:0}]});ok(!X.G.over&&slots(0)[1].cut&&slots(2)[0].cut);
  game(13,4);toAct();rig([[RD(2),B(1)],[RD(5),B(9)],[RD(8),B(10)],[B(11)]]);act(0);must({a:'multi',kind:'red3',tg:[{s:0,k:0},{s:1,k:0},{s:2,k:0}]});ok(X.G.over&&!X.G.over.win)});
T('14 the rookie (foreman card holder) explodes on a miss and may not use the Damper',()=>{game(14,4);toAct();const r=X.G.seats.find(s=>s.role==='rookie').i;const o=(r+1)%4;rig([[B(9),B(1)],[B(4),B(10)],[B(9,1),B(11)],[B(12),B(2)]]);eqReady('eq9');act(r);bad({a:'eq',id:'eq9'},r);const st=E.standsOf(o)[0];act(r);const myv=E.cv(X.G.st[E.standsOf(r)[0]].w[0].id);const tv=E.cv(X.G.st[st].w[0].id);
  must({a:'dual',st,ks:[0],v:myv===tv?E.cv(X.G.st[E.standsOf(r)[0]].w[1].id):myv},r);ok(X.G.over&&/rookie/.test(X.G.over.why))});
T('15 face-down equipment turns up when the shown number value is finished',()=>{game(15,4);toAct();const v=X.G.ms.nd.face;const f=filler([v],3);rig([[B(v),B(v,1),B(v,2),B(v,3),B(f[0])],[B(f[1])],[B(f[2])],[B(f[2],1)]]);act(0);must({a:'solo',v});ok(X.G.eq.some(e=>!e.down&&e.st==='ready'),'one card is ready');inv()});
T('17 the fibber\'s tokens are false; a miss on the fibber shows the called value',()=>{game(17,4);toAct();const l=X.G.seats.find(s=>s.role==='liar').i;const toks=E.standsOf(l).flatMap(si=>slots(si).flatMap(x=>x.tok.map(t=>({t,v:E.cv(x.id)}))));ok(toks.length===2&&toks.every(x=>x.t.t==='f'&&x.t.v!==x.v),'two false tokens');
  const o=(l+1)%4;rig([[B(9),B(1)],[B(4),B(10)],[B(3),B(11)],[B(12),B(2)]]);const ls=E.standsOf(l)[0];const ov=E.cv(slots(E.standsOf(o)[0])[0].id);act(o);const tv=E.cv(slots(ls)[0].id);const call=ov===tv?E.cv(slots(E.standsOf(o)[0])[1].id):ov;must({a:'dual',st:ls,ks:[0],v:call},o);if(!X.G.over)eq(slots(ls)[0].tok[0],{t:'f',v:call})});
T('17 the fibber may not use equipment',()=>{game(17,4);toAct();const l=X.G.seats.find(s=>s.role==='liar').i;eqReady('eq6');X.G.dial=2;bad({a:'eq',id:'eq6'},l)});
T('18 searchlight: the turned-up value is swept and the chosen player must cut it',()=>{game(18,4);toPlay();ok(X.G.ann.some(a=>a.k==='sweep'),'a sweep was made');eq(X.G.q&&X.G.q.kind,'designate')});
T('19 the cheating clock: about 668 s of play; the screen jumps from 10:00 to 5:00',()=>{game(19,4);toAct();X.G.clock=300;eq(Math.round(X.E.RH.timer.pub({},0).show),600);X.G.clock=340;ok(X.E.RH.timer.pub({},0).show<340);X.G.clock=669;E.hook('tick');ok(X.G.over&&!X.G.over.win)});
T('20 the last dealt wire is unsorted with an X, and equipment cannot touch it',()=>{game(20,4);ok(X.G.st.every(s=>s.w[s.w.length-1].x),'X at far right');toAct();eqReady('eq4');const a=X.G.actor;const s=E.standsOf(a)[0];const k=slots(s).length-1;bad({a:'eq',id:'eq4',s,k},a,'cannot touch')});
T('21 / 33 even-odd tokens replace info tokens',()=>{game(21,4);toAct();const t=X.G.st.flatMap(s=>s.w.flatMap(x=>x.tok));ok(t.length&&t.every(x=>x.t==='p'))});
T('22 negative opening tokens lie beside the stand for values not held',()=>{game(22,4);toAct();for(const s of X.G.st){for(const t of s.side){ok(t.mean==='none');ok(!E.heldVals(E.ownerOf(s.i),true)[t.v],'not held')}}ok(X.G.st.some(s=>s.side.length))});
T('22 first yellow pair: everyone gives a token to the left, placed truthfully',()=>{game(22,4);toAct();rig([[YL(2),B(1),B(5)],[YL(5),B(9),B(5,1)],[B(10),B(5,2)],[B(11),B(5,3)]]);act(0);must({a:'dual',st:1,ks:[K(1,YL(5))],v:'Y'});eq(X.G.q&&X.G.q.kind,'giftTok');eq(X.G.q.who,0);answer(o=>o.d.v===5);ok(slots(1).some(x=>x.tok.some(t=>t.v===5)),'left neighbour placed 5 on its 5')});
T('23 the shown value goes only by the four-wire action; a burn each round until then',()=>{game(23,4);toAct();const v=X.G.ms.sp4.v;const f=filler([v],4);rig([[B(v),B(f[0])],[B(v,1),B(f[1])],[B(v,2),B(f[2])],[B(v,3),B(f[3])]]);act(0);bad({a:'dual',st:1,ks:[K(1,B(v,1))],v},0,'four-wire');const n=X.G.eqDeck.length;
  must({a:'multi',kind:'four',tg:[{s:0,k:K(0,B(v))},{s:1,k:K(1,B(v,1))},{s:2,k:K(2,B(v,2))},{s:3,k:K(3,B(v,3))}]});ok(X.G.ms.sp4.done);eq(X.G.eqDeck.length,0);ok(X.G.eq.length===n,'pile becomes ready');inv()});
T('24 / 40 count tokens: how many of that value are on the stand',()=>{game(24,4);toAct();for(const s of X.G.st)for(const x of s.w)for(const t of x.tok){eq(t.t,'c');eq(t.v,s.w.filter(y=>E.cv(y.id)===E.cv(x.id)).length)}});
T('26 turn over a face-up number card, then cut exactly that value',()=>{game(26,4);toAct();ok(X.G.ms.dec.v!=null||X.G.tfx.skipped,'a card was declared');if(X.G.ms.dec.v!=null){const v=X.G.ms.dec.v;const other=X.validMoves(X.G.actor).filter(m=>m.a==='dual');ok(other.every(m=>m.v===v))}});
T('27 no personal tools; first yellow pair: a token draft',()=>{game(27,4);toAct();ok(X.G.seats.every(s=>s.noItem));rig([[YL(2),B(1),B(5)],[YL(5),B(9)],[B(10)],[B(11)]]);act(0);must({a:'dual',st:1,ks:[0],v:'Y'});eq(X.G.q&&X.G.q.kind,'ydraft');inv()});
T('28 the foreman has no crew card and fumbles: a miss explodes',()=>{game(28,4);toAct();eq(X.G.seats[0].ch,null);rig([[B(9),B(1)],[B(4),B(10)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0],v:9});ok(X.G.over&&/foreman/.test(X.G.over.why))});
T('29 the right neighbour lays a hidden card; cutting that value burns a step',()=>{game(29,4);toAct(3);ok(X.G.ms.mr.fd||X.G.q,'hidden card or question');if(X.G.q&&X.G.q.kind==='mindCard'){answer();}toAct();ok(X.G.ms.mr.fd,'face-down card in place')});
T('30 timed targets: a missed first target burns a step',()=>{game(30,4);toAct();const d=X.G.dial;const v=X.G.ms.bus.tg[0];ok(v!=null,'first target');X.G.clock=21;E.hook('tick');if(E.cutCount(v)<2)eq(X.G.dial,d-1);eq(X.G.ms.bus.pi,1)});
T('30 the three-value rush locks every other value',()=>{game(30,4);toAct();X.G.ms.bus.tg=[3,5,8];X.G.ms.bus.lock=1;rig([[B(3),B(9),B(1)],[B(3,1),B(9,1)],[B(10)],[B(11)]]);act(0);bad({a:'dual',st:1,ks:[1],v:9},0,'three target');must({a:'dual',st:1,ks:[0],v:3})});
T('31 restriction draft; a blocked player turns the card down for good',()=>{game(31,4);toAct();ok(X.G.seats.every(s=>s.con));X.G.seats[0].con='A';X.G.seats[0].conDown=0;rig([[B(3),B(5)],[B(3,1),B(9)],[B(10)],[B(11)]]);X.G.phase='turn';X.G.q=null;X.G.ag=[];E.later('startTurn',{seat:0});E.flow();ok(X.G.seats[0].conDown,'turned down')});
T('32 shared restriction: the foreman may swap it at the start of each turn; blocked players skip',()=>{game(32,4);toAct(1);ok(X.G.q&&X.G.q.kind==='replaceCon'||X.G.ms.gcon!=null)});
T('34 the weak link: a correct accusation restores personal tools; a wrong one burns a step',()=>{game(34,4);toAct();const w=X.G.seats.find(s=>s.role==='weak').i;const a=(w+1)%4;act(a);must({a:'accuse',who:w,con:X.G.seats[w].con},a);ok(!X.G.ms.mole.hidden);
  game(34,4);toAct();const w2=X.G.seats.find(s=>s.role==='weak').i;const a2=(w2+1)%4;act(a2);const d=X.G.dial;const wrong='ABCDE'.split('').find(c=>c!==X.G.seats[w2].con);must({a:'accuse',who:w2,con:wrong},a2);eq(X.G.dial,d-1)});
T('35 extra X wires wait until all yellows are cut',()=>{game(35,4);ok(X.G.st.every(s=>s.w[s.w.length-1].x&&E.WIRES[s.w[s.w.length-1].id].c==='b'));toAct();const a=X.G.actor;const o=(a+1)%4;const so=E.standsOf(o)[0];const k=slots(so).length-1;const v=E.cv(slots(so)[k].id);
  const r=mv({a:'dual',st:so,ks:[k],v},a);ok(!r.success,'locked')});
T('36 the five-card line: only the arrowed value; the cutter chooses where the arrow goes next',()=>{game(36,4);toAct();X.G.ms.ln={vals:[3,6,9,2,11],end:'L'};rig([[B(3),B(6),B(1)],[B(3,1),B(6,1),B(10)],[B(12)],[B(12,1)]]);act(0);bad({a:'dual',st:1,ks:[1],v:6},0,'line');must({a:'dual',st:1,ks:[0],v:3});eq(X.G.q&&X.G.q.kind,'lineFlip');answer((o,i)=>i===1);eq(X.G.ms.ln.end,'R')});
T('37 the shared restriction changes when a value is finished',()=>{game(37,4);toAct();rig([[B(5),B(5,1),B(5,2),B(5,3),B(1)],[B(10)],[B(12)],[B(12,1)]]);X.G.ms.gcon=null;const before=X.G.ms.gc.deck.length;act(0);must({a:'solo',v:5});ok(X.G.ms.gc.deck.length===before-1||X.G.over,'next card turned')});
T('38 only the foreman may cut the flipped wire; a wrong own-flipped cut explodes',()=>{game(38,4);const f=E.standsOf(0).flatMap(si=>slots(si).map((x,k)=>({si,k,x}))).find(o=>o.x.flip);ok(f,'foreman has a flipped wire');toAct();act(1);const r=mv({a:'dual',st:f.si,ks:[f.k],v:E.cv(f.x.id)},1);ok(!r.success&&/foreman/.test(r.error),r.error)});
T('39 four wires at once; then the rest of the number deck becomes extra tokens',()=>{game(39,4);toAct();const v=X.G.ms.sp4.v;const f=filler([v],5);rig([[B(v),B(f[0]),B(f[4])],[B(v,1),B(f[1])],[B(v,2),B(f[2])],[B(v,3),B(f[3])]]);act(0);must({a:'multi',kind:'four',tg:[{s:0,k:K(0,B(v))},{s:1,k:K(1,B(v,1))},{s:2,k:K(2,B(v,2))},{s:3,k:K(3,B(v,3))}]});ok(X.G.ms.sp4.done);ok(X.G.seats.some(s=>s.cards.length),'cards dealt')});
T('41 snare wires: right turns the fuse back, wrong burns a step with a token',()=>{game(41,4);toAct();rig([[YL(2),B(1),B(5)],[YL(5),B(9)],[YL(8),B(10)],[YL(10),B(11)]]);act(0);X.G.dial=1;must({a:'trip',s:1,k:0});eq(X.G.dial,2);act(0);bad({a:'dual',st:2,ks:[0],v:'Y'},0,'snare');must({a:'trip',s:2,k:1});eq(X.G.dial,1);eq(slots(2)[1].tok[0].v,10)});
T('42 circus: magician returns a pair, tamer moves seats, knife throws cut wires away',()=>{game(42,4);toAct();rig([[B(5),B(5,1),B(5,2),B(5,3),B(1)],[B(9)],[B(10)],[B(11)]]);act(0);must({a:'solo',v:5});
  const p0=X.G.pos.slice();X.G.ms.cir.ai=1;X.G.clock=111;E.hook('tick');eq(X.G.pos,p0.map(p=>(p+1)%4));
  X.G.clock=37;X.G.ms.cir.ai=0;E.hook('tick');eq(X.G.q&&X.G.q.kind,'magic');answer();eq(X.G.st.flatMap(s=>s.w).filter(x=>x.cut).length,2,'one pair back uncut');
  X.G.pos=[0,1,2,3];X.G.clock=238;X.G.ms.cir.ai=4;X.G.cur=0;E.hook('tick');ok(E.standsOf(0).every(si=>slots(si).every(x=>!x.cut)),'cut wires thrown');ok(X.G.gone.length>0);inv()});
T('43 the robot walks after every turn and hands over a wire when its value is cut',()=>{game(43,4);toAct();const at=X.G.robot.at;const rw=[B(12,0),B(12,1),B(12,2),B(12,3)].slice(0,X.G.robot.w.length);const n=rw.length;rig([[B(at),B(3)],[B(at,1),B(9)],[B(10)],[B(11)]],{robot:rw});act(0);must({a:'dual',st:1,ks:[K(1,B(at,1))],v:at});eq(X.G.robot.w.length,n-1);eq(X.G.robot.at,at+1);inv()});
T('44 shared oxygen by depth; cannot pay means skip and burn',()=>{game(44,4);toAct();rig([[B(11),B(1)],[B(11,1),B(9)],[B(10)],[B(12)]]);X.G.ms.ox.res=2;X.G.seats.forEach(s=>s.ox=0);X.G.seats[0].ox=X.G.ms.ox.total-2;act(0);bad({a:'dual',st:1,ks:[0],v:11},0,'oxygen');must({a:'dual',st:1,ks:[1],v:1});eq(X.G.ms.ox.res,1)});
T('45 volunteers: a false call burns a step; the caller must cut the card value',()=>{game(45,4);toPlay();eq(X.G.step,'snip');const v=X.G.ms.vol.v;const lack=X.G.seats.find(s=>!E.heldVals(s.i)[v]);const d=X.G.dial;if(lack){must({a:'snip'},lack.i);eq(X.G.dial,d-1)}const has=X.G.seats.find(s=>E.heldVals(s.i)[v]);if(has){must({a:'snip'},has.i);eq(X.G.actor,has.i);ok(X.validMoves(has.i).filter(m=>m.a==='dual').every(m=>m.v===v))}});
T('46 the 7s go last, all at once, by a hand of only 7s',()=>{game(46,4);toAct();rig([[B(7),B(7,1)],[B(7,2),B(9)],[B(7,3),B(10)],[B(9,1),B(10,1)]]);act(1);bad({a:'dual',st:0,ks:[0],v:7},1,'7s');act(0);bad({a:'dual',st:1,ks:[0],v:7},0);must({a:'multi',kind:'sevens',tg:[{s:0,k:0},{s:0,k:1},{s:1,k:0},{s:2,k:0}]});ok(!X.G.over||X.G.over.win)});
T('47 arithmetic: two face-up cards make the value; both are discarded',()=>{game(47,4);toAct();rig([[B(7),B(1)],[B(7,1),B(9)],[B(10)],[B(11)]]);act(0);bad({a:'dual',st:1,ks:[0],v:7,calc:[3,3,'+']},0);must({a:'dual',st:1,ks:[0],v:7,calc:[10,3,'-']});ok(!X.G.ms.mt.up.includes(10)&&!X.G.ms.mt.up.includes(3))});
T('48 three yellows at once; a miss tags every pointed wire and burns one step',()=>{game(48,4);toAct();rig([[YL(2),B(1)],[YL(5),B(9)],[YL(8),B(10)],[B(11)]]);act(0);const d=X.G.dial;must({a:'multi',kind:'y3',tg:[{s:0,k:K(0,B(1))},{s:1,k:K(1,B(9))},{s:2,k:K(2,B(10))}]});eq(X.G.dial,d-1);eq(slots(1)[K(1,B(9))].tok[0].v,9);
  act(1);must({a:'multi',kind:'y3',tg:[{s:0,k:K(0,YL(2))},{s:1,k:K(1,YL(5))},{s:2,k:K(2,YL(8))}]},1);eq(E.cutCount('Y'),3)});
T('49 bottle post: pay V oxygen to a crewmate before cutting V',()=>{game(49,4);toAct();rig([[B(3),B(1)],[B(3,1),B(9)],[B(10)],[B(11)]]);act(0);const a=X.G.seats[0].ox,b=X.G.seats[2].ox;must({a:'dual',st:1,ks:[0],v:3,oxTo:2});eq(X.G.seats[0].ox,a-3);eq(X.G.seats[2].ox,b+3)});
T('50 lights out: tokens lie beside the stand, no validation tokens',()=>{game(50,4);toAct();ok(X.G.st.some(s=>s.side.some(t=>t.mean==='has')));ok(X.G.st.every(s=>s.w.every(x=>!x.tok.length)));ok(X.G.validOff)});
T('51 the boss turns up a card and picks who cuts; lacking it costs a token and a step',()=>{game(51,4);toPlay();eq(X.G.q&&X.G.q.kind,'designate');const v=X.G.q.opts[0].d.v;const lack=X.G.seats.find(s=>!E.heldVals(s.i)[v]);if(lack){const d=X.G.dial;answer(o=>o.d.seat===lack.i);if(X.G.q&&X.G.q.kind==='lackTag')answer();eq(X.G.dial,d-1)}});
T('52 every token is false',()=>{game(52,4);toAct();const t=X.G.st.flatMap(s=>s.w.flatMap(x=>x.tok.map(k=>({k,v:E.cv(x.id)}))));ok(t.length===8&&t.every(o=>o.k.t==='f'&&o.k.v!==o.v))});
T('53 the robot is the fuse: +1 after a hit, +2 after a miss, -1 on its own value',()=>{game(53,4);toAct();rig([[B(9),B(1),B(2)],[B(4),B(9,1),B(10),B(2,1)],[B(11)],[B(12)]]);act(0);X.G.ms.rf.at=0;must({a:'dual',st:1,ks:[K(1,B(9,1))],v:9});eq(X.G.ms.rf.at,1);act(0);must({a:'dual',st:1,ks:[K(1,B(4))],v:1});eq(X.G.ms.rf.at,3);act(0);X.G.ms.rf.at=2;must({a:'dual',st:1,ks:[K(1,B(2,1))],v:2});eq(X.G.ms.rf.at,1)});
T('54 a leak draws a red from the pile into the hand in sorted order',()=>{game(54,4);toAct();const n=X.G.pile.length;const s=X.G.cur;const before=E.standsOf(s).reduce((a,si)=>a+slots(si).length,0);X.G.ms.rt.ei=0;X.G.clock=42;E.hook('tick');if(X.G.q)answer();eq(X.G.pile.length,n-1);eq(E.standsOf(s).reduce((a,si)=>a+slots(si).length,0),before+1);inv()});
T('55 / 60 challenges: meeting one turns the fuse back',()=>{game(55,4);toAct();rig([[B(5),B(5,1),B(5,2),B(5,3),B(1)],[B(9)],[B(10)],[B(11)]]);X.G.ms.chal=[{id:5}];X.G.hist=[{seat:1,kind:'solo',ok:1,turn:1}];act(0);X.G.dial=2;must({a:'solo',v:5});ok(X.G.ms.chalDone.includes(5));eq(X.G.dial,3)});
T('55 challenge 1: calling red on a non-red explodes',()=>{game(55,4);toAct();X.G.ms.chal=[{id:1}];rig([[B(5),B(1)],[B(9),RD(4)],[B(10)],[B(11)]]);act(0);must({a:'redcall',s:1,k:K(1,B(9))});ok(X.G.over&&!X.G.over.win)});
T('56 cutting a crewmate\'s flipped wire costs a step even on success',()=>{game(56,4);toAct();const a=X.G.actor;const o=(a+1)%4;const f=E.standsOf(o).flatMap(si=>slots(si).map((x,k)=>({si,k,x}))).find(z=>z.x.flip);const v=E.cv(f.x.id);if(v!=='R'&&E.heldVals(a)[v]){const d=X.G.dial;must({a:'dual',st:f.si,ks:[f.k],v},a);eq(X.G.dial,d-1)}else ok(true)});
T('57 each validation token switches on its paired restriction',()=>{game(57,4);toAct();rig([[B(5),B(5,1),B(5,2),B(5,3),B(1)],[B(10)],[B(12)],[B(12,1)]]);act(0);must({a:'solo',v:5});eq(X.G.ms.gcon,X.G.ms.gc.pair[5])});
T('58 no tokens; the Twin Probe works every turn',()=>{game(58,4);toAct();ok(X.G.st.every(s=>s.w.every(x=>!x.tok.length)));rig([[B(9),B(9,3),B(1)],[B(9,1),B(9,2),B(10),B(4)],[B(11)],[B(12)]]);act(0);must({a:'dual',st:1,ks:[0,1],v:9,tool:'dd'});if(X.G.q)answer();act(0);must({a:'dual',st:1,ks:[2,3],v:1,tool:'dd'})});
T('59 the robot guide: cut only the value under the robot',()=>{game(59,4);toPlay();ok(X.G.q&&X.G.q.kind==='robotGo'||X.G.tfx.skipped,'robot question or stuck skip')});
T('61 rotate restrictions each round; swap for a random F-L card by burning a step',()=>{game(61,4);toAct();const s=X.G.actor;const old=X.G.seats[s].con;const d=X.G.dial;must({a:'swapCon'},s);ok('FGHIJKL'.includes(X.G.seats[s].con));eq(X.G.dial,d-1);E.QH.rotateCon({dir:1});inv()});
T('62 a finished meteor value turns the fuse back',()=>{game(62,4);toAct();X.G.ms.met.vals=[5];rig([[B(5),B(5,1),B(5,2),B(5,3),B(1)],[B(9)],[B(10)],[B(11)]]);act(0);X.G.dial=1;must({a:'solo',v:5});eq(X.G.dial,2)});
T('63 the oxygen bundle passes left after each turn',()=>{game(63,4);toAct();const s=X.G.actor;const st=X.G.seats.map(q=>q.ox);const vm=X.validMoves(s).find(m=>m.a==='dual');must(vm,s);toAct();ok(X.G.seats[s].ox===0,'passed on');inv()});
T('64 two flipped wires: the lower far left, the higher far right',()=>{game(64,4);for(const q of X.G.seats){const sl=E.standsOf(q.i).flatMap(si=>slots(si));const f=sl.filter(x=>x.flip);eq(f.length,2);ok(sl[0].flip&&sl[sl.length-1].flip);ok(E.WIRES[sl[0].id].s<=E.WIRES[sl[sl.length-1].id].s)}});
T('38/56/64 own flipped wire: the move names which flipped wire; the right one succeeds, the wrong one explodes',()=>{for(const wrong of [0,1]){game(64,4);toAct();rig([[B(3),B(12),B(12,1)],[B(3,1),B(9)],[B(10)],[B(11)]],{keep:true});const w=slots(0);w[0].flip=1;w[2].flip=1;act(0);
    bad({a:'solo',v:12,flip:1},0,'fu');const fu=wrong?w[0].u:w[2].u;must({a:'solo',v:12,flip:1,fu});if(wrong)ok(X.G.over&&!X.G.over.win,'wrong flipped wire explodes');else{ok(!X.G.over,'no boom');ok(w[1].cut&&w[2].cut&&!w[0].cut)}}});
T('38 the foreman cuts a flipped wire with a plain dual cut naming it',()=>{game(38,4);toAct();rig([[B(9),B(3)],[B(3,1),B(10)],[B(11)],[B(12)]],{keep:true});const w=slots(0);w[1].flip=1;act(0);bad({a:'dual',st:1,ks:[0],v:3,own:'flip',fu:w[1].u,tool:'dd'},0);must({a:'dual',st:1,ks:[0],v:3,own:'flip',fu:w[1].u});ok(w[1].cut&&slots(1)[0].cut)});
T('65 hot potato: only values on your cards; a card is handed on after the turn',()=>{game(65,4);toAct();const s=X.G.actor;const mine=X.G.seats[s].cards;ok(X.validMoves(s).filter(m=>m.a==='dual'||m.a==='solo').every(m=>mine.includes(m.v)))});
T('66 bunker: a cut moves the crew toward a side its value satisfies',()=>{game(66,4);toAct();const b=X.G.ms.bk;b.sides={U:'A',R:'A',D:'A',L:'A'};b.action='E';rig([[B(4),B(1)],[B(4,1),B(9)],[B(10)],[B(11)]]);act(0);must({a:'dual',st:1,ks:[0],v:4});eq(X.G.q&&X.G.q.kind,'bkMove');answer(o=>o.d.dir==='R');eq([b.r,b.c],[3,1])});
T('66 bunker: missing an objective deadline ends the job',()=>{game(66,4);toAct();X.G.clock=81;E.hook('tick');ok(X.G.over&&!X.G.over.win)});
console.log(`\nrules-test: ${pass} passed, ${fail} failed${fail?' -> '+fails.join(' | '):''}`);
