# Builds final-approach.html (one self-contained file) and x.js (all our scripts joined, for node --check).
# All paths are repo-relative (this file lives in games-src/final-approach/game/).
import re, os, sys, json, base64, io
D = os.path.dirname(os.path.abspath(__file__))
SP = os.path.abspath(os.path.join(D, '..', '..'))   # games-src
FP = os.path.abspath(os.path.join(D, '..'))         # games-src/final-approach
def rd(p): return open(p, encoding='utf-8').read()
parts = sorted(f for f in os.listdir(os.path.join(D, 'src')) if re.match(r'ui\d+\.js$', f))
ui = ''.join(rd(os.path.join(D, 'src', f)) for f in parts)
open(os.path.join(D, 'ui.js'), 'w', encoding='utf-8').write(ui)
audio = os.path.join(SP, 'audio', 'final-approach', 'audio-data.js')
S = lambda f: os.path.join(D, 'src', f)
SRC = {'shell.js': os.path.join(SP, 'shell', 'shell.js'), 'perfhud.js': os.path.join(SP, 'perf', 'perfhud.js'), 'gameaudio.js': os.path.join(SP, 'audio', 'gameaudio.js'),
       'art-data.js': '', 'data.js': S('data.js'), 'layout.js': S('layout.js'), 'engine.js': S('engine.js'), 'aiw.js': S('aiw.js'), 'ai.js': S('ai.js'), 'ui.js': os.path.join(D, 'ui.js'),
       'trystero.min.js': os.path.join(SP, 'net', 'trystero.min.js'), 'netroom.js': os.path.join(SP, 'net', 'netroom.js'), 'netstrip.js': S('netstrip.js'), 'net.js': S('net.js')}
# ---- painted art: ../art/manifest.json maps id -> base name. <name>.png (a painting dropped in by hand) wins over <name>.webp (made by ../paint/paint.js).
ART = os.path.join(FP, 'art')
def art_js():
    man = json.load(open(os.path.join(ART, 'manifest.json'), encoding='utf-8'))
    out, total = {}, 0
    for k, name in man['items'].items():
        png, webp = os.path.join(ART, name + '.png'), os.path.join(ART, name + '.webp')
        if os.path.exists(png):
            from PIL import Image
            im = Image.open(png).convert('RGBA'); W, H = man['size'].get(k, im.size)
            if im.size != (W, H): im = im.resize((W, H), Image.LANCZOS)
            b = io.BytesIO(); im.save(b, 'WEBP', quality=82, method=6); data = b.getvalue(); print('art: using', name + '.png', file=sys.stderr)
        elif os.path.exists(webp): data = open(webp, 'rb').read()
        else: print('NOTE: art missing', name, file=sys.stderr); continue
        total += len(data); out[k] = 'data:image/webp;base64,' + base64.b64encode(data).decode('ascii')
    print('art: %d images, %d KB' % (len(out), total // 1024), file=sys.stderr)
    return '// painted art (generated by build.py from ../art; see ../paint/paint.js)\nvar FA_ART = ' + json.dumps(out, separators=(',', ':')) + ';\nvar FA_ATLAS = ' + json.dumps(man.get('atlas', {}), separators=(',', ':')) + ';\n'
ART_JS = art_js()
if os.path.exists(audio): SRC['audio-data.js'] = audio
else: print('NOTE: audio-data.js missing, silent build', file=sys.stderr)
ORDER = ['shell.js', 'perfhud.js', 'trystero.min.js', 'netroom.js', 'art-data.js', 'data.js', 'layout.js', 'engine.js', 'aiw.js', 'ai.js', 'netstrip.js', 'gameaudio.js', 'audio-data.js', 'net.js', 'ui.js']
h = rd(os.path.join(D, 'head.html')).replace('/*SHELL_CSS*/', rd(os.path.join(SP, 'shell', 'shell.css')))
body = rd(os.path.join(D, 'body.html'))
if 'audio-data.js' in SRC: body = body.replace('<script src="ui.js"></script>', '<script src="audio-data.js"></script>\n<script src="ui.js"></script>')
for f in ORDER:
    tag = '<script src="%s"></script>' % f
    if f not in SRC: continue
    assert tag in body, f
    src = (ART_JS if f == 'art-data.js' else rd(SRC[f])).replace('</script', '<\\/script')
    body = body.replace(tag, '<script>\n' + src + '\n</script>')
# PixiJS (MIT, licence header kept): stored as text and only run when the page decides to use the WebGL/canvas table
px = rd(os.path.join(SP, 'kaiten', 'vendor', 'pixi.min.js')).replace('//# sourceMappingURL=pixi.min.js.map', '').replace('</script', '<\\/script')
ptag = '<script type="text/plain" id="pixi-src" src="pixi.min.js"></script>'
assert ptag in body
body = body.replace(ptag, '<script type="text/plain" id="pixi-src">\n' + px + '\n</script>')
out = h + body
open(os.path.join(D, 'final-approach.html'), 'w', encoding='utf-8').write(out)
js = '\n'.join(re.findall(r'<script>(.*?)</script>', out, re.S))
open(os.path.join(D, 'x.js'), 'w', encoding='utf-8').write(js)
print('final-approach.html', len(out.encode('utf-8')), 'bytes')
