
/* ------------------------------------------------------------------ 2D fallback: painted-chart SVG, fully clickable */
var NS = 'http://www.w3.org/2000/svg';
function el(tag, attrs, parent, html) { var e = document.createElementNS(NS, tag); if (attrs) for (var k in attrs) e.setAttribute(k, attrs[k]); if (html != null) e.innerHTML = html; if (parent) parent.appendChild(e); return e; }
function f2(v) { return Math.round(v * 1000) / 1000; }
function roseSVG(cx, cy, R, op) {
  var s = '<g transform="translate(' + cx + ' ' + cy + ')" opacity="' + op + '"><circle r="' + R + '" fill="none" stroke="' + C.goldD + '" stroke-width="' + R * .012 + '"/><circle r="' + R * .93 + '" fill="none" stroke="' + C.goldD + '" stroke-width="' + R * .008 + '"/><circle r="' + R * .5 + '" fill="none" stroke="' + C.goldD + '" stroke-width="' + R * .008 + '"/>';
  for (var p = 0; p < 16; p++) { var an = p / 16 * Math.PI * 2 - Math.PI / 2, len = p % 4 === 0 ? .92 : p % 2 === 0 ? .66 : .42, w = p % 4 === 0 ? .11 : p % 2 === 0 ? .075 : .05, cs = Math.cos(an), sn = Math.sin(an), px = -sn, py = cs;
    [[1, C.gold], [-1, '#b8862a']].forEach(function (sd) { s += '<path d="M0 0L' + f2(cs * R * len) + ' ' + f2(sn * R * len) + 'L' + f2(cs * R * w * 1.6 + px * R * w * sd[0]) + ' ' + f2(sn * R * w * 1.6 + py * R * w * sd[0]) + 'Z" fill="' + sd[1] + '" stroke="' + C.ink + '" stroke-width="' + R * .008 + '"/>'; }); }
  return s + '<circle r="' + R * .06 + '" fill="' + C.ink + '" stroke="' + C.gold + '" stroke-width="' + R * .014 + '"/><text y="' + -R * 1.1 + '" text-anchor="middle" font-size="' + R * .16 + '" font-weight="700" fill="' + C.gold + '" stroke="' + C.ink + '" stroke-width="' + R * .015 + '" paint-order="stroke" font-family="' + FD.replace(/"/g, "'") + '">N</text></g>';
}
var R2 = {
  svg: null,
  build: function () {
    var host = K.fallback; if (!host) return; host.innerHTML = ''; host.setAttribute('data-tw2d', '1');
    var V = HALF + .15, svg = el('svg', { viewBox: -V + ' ' + -V + ' ' + V * 2 + ' ' + V * 2, preserveAspectRatio: 'xMidYMid meet', role: 'img', 'aria-label': 'Tidewake sea chart, 6 by 6 squares', style: 'width:100%;height:100%;display:block;touch-action:manipulation;user-select:none' }, host); R2.svg = svg;
    var style = el('style', null, svg, '.tw2-spin{animation:tw2spin 6s linear infinite;transform-box:fill-box;transform-origin:center}.tw2-spin2{animation:tw2spin 3.4s linear infinite reverse;transform-box:fill-box;transform-origin:center}@keyframes tw2spin{to{transform:rotate(360deg)}}.tw2-sq{cursor:pointer}.tw2-pulse{animation:tw2pl 1.2s ease-in-out infinite}@keyframes tw2pl{50%{opacity:.35}}');
    var defs = el('defs', null, svg, '<radialGradient id="tw2sea" cx=".5" cy=".5" r=".75"><stop offset="0" stop-color="#2a8e93"/><stop offset=".6" stop-color="#1b6f78"/><stop offset="1" stop-color="#0f4a56"/></radialGradient>' +
      '<radialGradient id="tw2tile" cx=".5" cy=".45" r=".75"><stop offset="0" stop-color="#4cb4ae"/><stop offset=".55" stop-color="#2a8c92"/><stop offset="1" stop-color="#17606c"/></radialGradient><radialGradient id="tw2lev" cx=".5" cy=".5" r=".7"><stop offset="0" stop-color="#1a4a58"/><stop offset="1" stop-color="#061821"/></radialGradient>' +
      '<linearGradient id="tw2wood" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#7b3626"/><stop offset="1" stop-color="#4a1c12"/></linearGradient><linearGradient id="tw2paper" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f0e2b4"/><stop offset=".5" stop-color="#e5d29a"/><stop offset="1" stop-color="#d7bf84"/></linearGradient>' +
      '<filter id="tw2glow" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation=".035"/></filter><filter id="tw2wash" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".9 .6" numOctaves="2" seed="4" result="n"/><feColorMatrix in="n" type="matrix" values="0 0 0 0 .1  0 0 0 0 .35  0 0 0 0 .38  0 0 0 .9 -.28"/></filter>' +
      '<filter id="tw2sh" x="-30%" y="-30%" width="160%" height="170%"><feDropShadow dx="0" dy=".03" stdDeviation=".03" flood-color="#021a20" flood-opacity=".55"/></filter>');
    var g = el('g', null, svg), lo = HALF;
    el('rect', { x: -lo - .1, y: -lo - .1, width: lo * 2 + .2, height: lo * 2 + .2, rx: .22, fill: 'url(#tw2wood)' }, g); el('rect', { x: -lo, y: -lo, width: lo * 2, height: lo * 2, fill: 'url(#tw2sea)' }, g); el('rect', { x: -lo, y: -lo, width: lo * 2, height: lo * 2, filter: 'url(#tw2wash)', opacity: .55 }, g);
    var sg = ''; for (var row = 0; row < 18; row++) for (var col = 0; col < 14; col++) { var cx = -lo + col * .65 + (row % 2) * .325, cy = -lo + row * .5; sg += '<path d="M' + (cx - .3) + ' ' + cy + 'a.3 .3 0 0 1 .6 0M' + (cx - .2) + ' ' + cy + 'a.2 .2 0 0 1 .4 0M' + (cx - .1) + ' ' + cy + 'a.1 .1 0 0 1 .2 0" />'; }
    el('g', { fill: 'none', stroke: '#d8f4ec', 'stroke-opacity': .11, 'stroke-width': .012 }, g, sg);
    var gs = ''; for (var r = 0; r < 6; r++) for (var c = 0; c < 6; c++) gs += '<rect x="' + (c - G) + '" y="' + (r - G) + '" width="1" height="1" fill="' + ((r + c) % 2 ? 'rgba(255,255,255,.05)' : 'rgba(0,30,40,.08)') + '"/>';
    el('g', null, g, gs); var gl = ''; for (var l = 0; l <= 6; l++) gl += '<path d="M' + (l - G) + ' ' + -G + 'V' + G + 'M' + -G + ' ' + (l - G) + 'H' + G + '"/>';
    el('g', { stroke: 'rgba(232,196,110,.6)', 'stroke-width': .012, 'stroke-dasharray': '.05 .05', fill: 'none' }, g, gl); el('rect', { x: -G, y: -G, width: 6, height: 6, fill: 'none', stroke: C.gold, 'stroke-width': .028 }, g);
    el('g', null, g, roseSVG(0, 0, 2.3, .45));
    var cp_ = coastPts(HALF - .45, 99), d = 'M' + -lo + ' ' + -lo + 'H' + lo + 'V' + lo + 'H' + -lo + 'Z M' + f2(cp_[0][0]) + ' ' + f2(cp_[0][1]); for (var q = 1; q < cp_.length; q++) d += 'L' + f2(cp_[q][0]) + ' ' + f2(cp_[q][1]); d += 'Z';
    el('path', { d: d, fill: 'url(#tw2paper)', 'fill-rule': 'evenodd' }, g); var cd = 'M' + f2(cp_[0][0]) + ' ' + f2(cp_[0][1]); for (var q2 = 1; q2 < cp_.length; q2++) cd += 'L' + f2(cp_[q2][0]) + ' ' + f2(cp_[q2][1]); cd += 'Z';
    el('path', { d: cd, fill: 'none', stroke: 'rgba(220,245,235,.5)', 'stroke-width': .1, transform: 'scale(.985)' }, g); el('path', { d: cd, fill: 'none', stroke: C.ink, 'stroke-width': .022 }, g);
    var tk = ''; for (var t2 = 0; t2 < 48; t2 += 2) { var a = -lo + .08 + t2 / 48 * (2 * lo - .16), b = a + (2 * lo - .16) / 48; tk += '<rect x="' + a + '" y="' + (-lo + .08) + '" width="' + (b - a) + '" height=".12"/><rect x="' + a + '" y="' + (lo - .2) + '" width="' + (b - a) + '" height=".12"/><rect y="' + a + '" x="' + (-lo + .08) + '" height="' + (b - a) + '" width=".12"/><rect y="' + a + '" x="' + (lo - .2) + '" height="' + (b - a) + '" width=".12"/>'; }
    el('g', { fill: C.ink }, g, tk); el('rect', { x: -lo + .08, y: -lo + .08, width: lo * 2 - .16, height: lo * 2 - .16, fill: 'none', stroke: C.ink, 'stroke-width': .018 }, g);
    [[-1, -1], [1, -1], [-1, 1]].forEach(function (cc, i) { el('ellipse', { cx: cc[0] * (HALF - 1), cy: cc[1] * (HALF - 1), rx: .26, ry: .2, fill: 'rgba(214,190,120,.95)', stroke: C.ink, 'stroke-width': .014 }, g); }); el('g', null, g, roseSVG((HALF - 1), (HALF - 1), .62, .9));
    var md = ''; for (var n = 1; n <= 6; n++) { var u = n - 3.5;[[u, -G - .42], [u, G + .42], [-G - .42, u], [G + .42, u]].forEach(function (p) { md += '<circle cx="' + p[0] + '" cy="' + p[1] + '" r=".19" fill="rgba(12,40,50,.92)" stroke="' + C.gold + '" stroke-width=".017"/><text x="' + p[0] + '" y="' + (p[1] + .085) + '" text-anchor="middle" font-size=".27" font-weight="700" fill="#fff2c4" font-family="' + FD.replace(/"/g, "'") + '">' + n + '</text>'; }); }
    el('g', null, g, md);
    var sm = ''; for (var e = 0; e < 6; e++) for (var pp = 0; pp < 2; pp++) { var ff = e + (pp ? 2 / 3 : 1 / 3) - G;[[ff, -G], [ff, G], [-G, ff], [G, ff]].forEach(function (m) { sm += '<circle cx="' + m[0] + '" cy="' + m[1] + '" r=".075" fill="rgba(10,40,50,.88)" stroke="' + C.gold + '" stroke-width=".014"/><circle cx="' + m[0] + '" cy="' + m[1] + '" r=".026" fill="' + C.gold + '"/>'; }); }
    el('g', null, g, sm);
    R2.gTiles = el('g', null, svg); R2.gLine = el('g', null, svg); R2.gLegal = el('g', null, svg); R2.gSpecial = el('g', null, svg); R2.gShips = el('g', null, svg); R2.gGhost = el('g', { 'pointer-events': 'none' }, svg); R2.gHover = el('g', { 'pointer-events': 'none' }, svg); R2.gDice = el('g', null, svg); R2.gFx = el('g', { 'pointer-events': 'none' }, svg);
    // transparent hit squares
    var hit = el('g', null, svg); for (var r2 = 0; r2 < 6; r2++) for (var c2 = 0; c2 < 6; c2++) el('rect', { x: c2 - G, y: r2 - G, width: 1, height: 1, fill: 'transparent', class: 'tw2-sq', 'data-c': c2, 'data-r': r2 }, hit);
    svg.addEventListener('click', function (e) { if (K.onClick) K.onClick(R2.pick(e.clientX, e.clientY), e); });
    svg.addEventListener('pointermove', function (e) { var p = R2.hover(e.clientX, e.clientY); if (K.onHover) K.onHover(p, e); });
    svg.addEventListener('pointerleave', function () { R2.hover(null); });
    // replay model
    Object.keys(S.tiles).forEach(function (k) { R2.tile(S.tiles[k]); }); Object.keys(S.levs).forEach(function (k) { R2.lev(S.levs[k]); }); Object.keys(S.ships).forEach(function (k) { R2.ship(S.ships[k]); }); Object.keys(S.gates).forEach(function (k) { var G_ = S.gates[k]; R2.gate(G_.c, G_.r, true, G_); }); Object.keys(S.mael).forEach(function (k) { R2.mael(S.mael[k].c, S.mael[k].r, true); }); R2.legal(); R2.ghost(); R2.line(); if (S.dice.length) R2.dice(S.dice);
  },
  resize: function () {},
  toWorld: function (x, y) { var rc = R2.svg.getBoundingClientRect(), V = HALF + .15, sc = Math.min(rc.width, rc.height) / (V * 2); return [(x - rc.left - rc.width / 2) / sc, (y - rc.top - rc.height / 2) / sc]; },
  pick: function (x, y) { if (!R2.svg) return null; var w = R2.toWorld(x, y); return pickWorld(w[0], w[1], false); },
  pickEl: function (e) { while (e && e.getAttribute && !e.getAttribute('data-c')) e = e.parentNode; if (!e || !e.getAttribute) return null; return { kind: 'square', c: +e.getAttribute('data-c'), r: +e.getAttribute('data-r') }; },
  hover: function (x, y) { if (!R2.svg) return null; R2.gHover.innerHTML = ''; if (x == null) { S.hover = null; return null; } var p = R2.pick(x, y); if (p && p.kind === 'square') { S.hover = { c: p.c, r: p.r }; el('rect', { x: p.c - G + .02, y: p.r - G + .02, width: .96, height: .96, rx: .05, fill: 'rgba(255,226,140,.18)', stroke: '#ffe28c', 'stroke-width': .03 }, R2.gHover); } else S.hover = null; return p; },
  legal: function () { if (!R2.svg) return; R2.gLegal.innerHTML = ''; S.legal.forEach(function (s) { el('rect', { x: s.c - G + .03, y: s.r - G + .03, width: .94, height: .94, rx: .06, fill: 'rgba(155,255,232,.12)', stroke: '#9bffe8', 'stroke-width': .03, 'stroke-dasharray': '.1 .06', class: 'tw2-pulse', 'pointer-events': 'none' }, R2.gLegal); }); },
  tileInner: function (paths, c, r, ghost) {
    var ox = c - G, oy = r - G, s = '<rect x="' + (ox + .02) + '" y="' + (oy + .02) + '" width=".96" height=".96" rx=".06" fill="url(#tw2tile)" stroke="' + C.ink + '" stroke-width=".03"/><rect x="' + (ox + .05) + '" y="' + (oy + .05) + '" width=".9" height=".9" rx=".04" fill="none" stroke="rgba(227,178,75,.7)" stroke-width=".008"/>';
    s += paths.map(function (p) { return '<path d="' + pathD(p[0], p[1], 1, ox, oy) + '" fill="none" stroke="#9fe6dc" stroke-opacity=".4" stroke-width=".15" stroke-linecap="round" filter="url(#tw2glow)"/>'; }).join('');
    s += paths.map(function (p) { return '<path d="' + pathD(p[0], p[1], 1, ox, oy) + '" fill="none" stroke="#17606c" stroke-opacity=".6" stroke-width=".085" stroke-linecap="round"/>'; }).join('');
    s += paths.map(function (p) { return '<path d="' + pathD(p[0], p[1], 1, ox, oy) + '" fill="none" stroke="#f6f2df" stroke-width=".05" stroke-linecap="round"/><path d="' + pathD(p[0], p[1], 1, ox, oy) + '" fill="none" stroke="#fff" stroke-width=".014" stroke-linecap="round" stroke-dasharray=".05 .07"/>'; }).join('');
    for (var i = 0; i < 8; i++) s += '<circle cx="' + (ox + PORT[i][0]) + '" cy="' + (oy + PORT[i][1]) + '" r=".022" fill="' + C.gold + '"/>';
    return s;
  },
  tile: function (T) { if (!R2.svg) return; if (T.node) T.node.remove(); T.node = el('g', { 'data-c': T.c, 'data-r': T.r, 'pointer-events': 'none', filter: 'url(#tw2sh)' }, R2.gTiles, R2.tileInner(T.paths, T.c, T.r)); T.node.style.opacity = 0; T.node.style.transition = 'opacity .3s'; raf(function () { T.node.style.opacity = 1; }); },
  untile: function (T) { if (T.node) T.node.remove(); },
  lev: function (L) {
    if (!R2.svg) return; if (L.node) L.node.remove(); var ox = L.c - G, oy = L.r - G, cx = ox + .5, cy = oy + .5; var s = '<rect x="' + (ox + .02) + '" y="' + (oy + .02) + '" width=".96" height=".96" rx=".06" fill="url(#tw2lev)" stroke="' + C.ink + '" stroke-width=".03"/><circle cx="' + cx + '" cy="' + cy + '" r=".2" fill="none" stroke="' + C.gold + '" stroke-opacity=".6" stroke-width=".01"/>';
    var pal = LEV_PAL[L.kind]; s += '<g class="lv"><path d="M' + (cx - .12) + ' ' + (cy + .14) + 'c-.2-.2 .02-.34 .15-.26s.06 .22-.1 .18c-.16-.05-.1-.2 .02-.2" fill="none" stroke="' + pal.b + '" stroke-width=".11" stroke-linecap="round"/><path d="M' + (cx - .12) + ' ' + (cy + .14) + 'c-.2-.2 .02-.34 .15-.26s.06 .22-.1 .18c-.16-.05-.1-.2 .02-.2" fill="none" stroke="' + pal.a + '" stroke-width=".08" stroke-linecap="round" stroke-dasharray=".05 .02"/><ellipse cx="' + (cx + .06) + '" cy="' + (cy - .14) + '" rx=".08" ry=".055" fill="' + pal.a + '" stroke="' + pal.b + '" stroke-width=".02"/><circle cx="' + (cx + .08) + '" cy="' + (cy - .16) + '" r=".016" fill="' + pal.eye + '"/></g>';
    L.arrows.forEach(function (a) { var an = (a.dir * 45 - 90) * Math.PI / 180, ax = cx + Math.cos(an) * .38, ay = cy + Math.sin(an) * .38, nx = cx + Math.cos(an) * .27, ny = cy + Math.sin(an) * .27; s += '<g transform="translate(' + ax + ' ' + ay + ') rotate(' + a.dir * 45 + ') scale(.011)"><path d="M0-10L7-1H2.6V8H-2.6V-1H-7Z" fill="' + C.gold + '" stroke="' + C.ink + '" stroke-width="1"/></g><circle cx="' + nx + '" cy="' + ny + '" r=".055" fill="' + C.ink + '" stroke="' + C.gold + '" stroke-width=".01"/><text x="' + nx + '" y="' + (ny + .03) + '" text-anchor="middle" font-size=".08" font-weight="700" fill="#fff2c4" font-family="' + FD.replace(/"/g, "'") + '">' + a.n + '</text>'; });
    L.node = el('g', { 'pointer-events': 'none', filter: 'url(#tw2sh)' }, R2.gTiles, s);
  },
  unlev: function (L) { if (L.node) L.node.remove(); },
  pulse: function (c, r) { R2.fx('splash', c - 2.5, r - 2.5, 1.2); },
  destroy: function (T, isLev) { if (T.node) { T.node.style.transition = 'opacity .5s, transform .5s'; T.node.style.opacity = 0; setTimeout(function () { T.node.remove(); }, 520); } R2.fx('splash', T.c - 2.5, T.r - 2.5, 1.3); R2.fx('chips', T.c - 2.5, T.r - 2.5, 1); },
  ship: function (s, redraw) {
    if (!R2.svg) return; if (s.node) s.node.remove(); var col = SHIP_COLORS[s.color % 8];
    var sail = '<path d="M-.02-.02 L.17-.06 L.16-.34 L-.02-.38Z" fill="' + col.sail + '" stroke="' + C.ink + '" stroke-width=".02"/><path d="M-.02-.12L.165-.15M-.02-.21L.165-.24M-.02-.3L.165-.32" stroke="rgba(40,20,5,.55)" stroke-width=".015"/>';
    var cn = ''; for (var i = 0; i < Math.min(5, s.cannons); i++) cn += '<circle cx="' + (-.1 + i * .06) + '" cy="-.02" r=".022" fill="#b98a3a" stroke="' + C.ink + '" stroke-width=".008"/>';
    s.node = el('g', { 'data-ship': s.id, 'pointer-events': 'none' }, R2.gShips); s.hull = el('g', null, s.node, '<ellipse rx=".3" ry=".15" cy=".03" fill="rgba(2,26,32,.35)"/><path d="M-.26-.09Q-.29 0-.26.09L.12.11Q.34 0 .12-.11Z" fill="#8a5a34" stroke="' + C.ink + '" stroke-width=".022"/><path d="M-.24-.075L.12-.095M-.24.075L.12.095" stroke="' + col.trim + '" stroke-width=".03" stroke-linecap="round"/><rect x="-.27" y="-.06" width=".1" height=".12" rx=".02" fill="' + col.trim + '" stroke="' + C.ink + '" stroke-width=".015"/>' + cn);
    s.sail = el('g', null, s.node, sail); s.sailRot = s.sail;
  },
  unship: function (s) { if (s.node) s.node.remove(); },
  gate: function (c, r, on, G_) { if (!R2.svg) return; var id = 'g' + c + ',' + r, old = R2.gSpecial.querySelector('[data-id="' + id + '"]'); if (old) old.remove(); if (!on) return; var p = G_.pal || ['#9b5cff', '#35e0ff'], cx = c - 2.5, cy = r - 2.5; var g = el('g', { 'data-id': id, 'pointer-events': 'none' }, R2.gSpecial, '<circle cx="' + cx + '" cy="' + cy + '" r=".4" fill="' + p[0] + '" opacity=".25" filter="url(#tw2glow)"/><g class="tw2-spin"><circle cx="' + cx + '" cy="' + cy + '" r=".3" fill="none" stroke="' + p[0] + '" stroke-width=".07" stroke-dasharray=".25 .1"/></g><g class="tw2-spin2"><circle cx="' + cx + '" cy="' + cy + '" r=".19" fill="none" stroke="' + p[1] + '" stroke-width=".05" stroke-dasharray=".12 .08"/></g><circle cx="' + cx + '" cy="' + cy + '" r=".34" fill="none" stroke="' + C.gold + '" stroke-width=".035"/>'); },
  mael: function (c, r, on) { if (!R2.svg) return; var id = 'm' + c + ',' + r, old = R2.gSpecial.querySelector('[data-id="' + id + '"]'); if (old) old.remove(); if (!on) return; var cx = c - 2.5, cy = r - 2.5; el('g', { 'data-id': id, 'pointer-events': 'none' }, R2.gSpecial, '<circle cx="' + cx + '" cy="' + cy + '" r=".44" fill="#06222c" opacity=".85"/><g class="tw2-spin2"><path d="M' + cx + ' ' + cy + 'm0-.4a.4 .4 0 0 1 .4 .4M' + cx + ' ' + cy + 'm.3 .05a.3 .3 0 0 1-.3 .3M' + cx + ' ' + cy + 'm-.3-.1a.3 .3 0 0 1 .3-.3" fill="none" stroke="#c8fff0" stroke-width=".05" stroke-linecap="round"/><path d="M' + cx + ' ' + cy + 'm-.2 0a.2 .2 0 0 1 .2-.2M' + cx + ' ' + cy + 'm.2 0a.2 .2 0 0 1-.2 .2" fill="none" stroke="#5fd0c8" stroke-width=".05" stroke-linecap="round"/></g>'); },
  waveTile: function (c, r, on) { if (!R2.svg) return; var id = 'w' + c + ',' + r, old = R2.gSpecial.querySelector('[data-id="' + id + '"]'); if (old) old.remove(); if (!on) return; var ox = c - G, oy = r - G; el('g', { 'data-id': id, 'pointer-events': 'none' }, R2.gSpecial, '<rect x="' + (ox + .02) + '" y="' + (oy + .02) + '" width=".96" height=".96" rx=".06" fill="#1b8c96" stroke="' + C.ink + '" stroke-width=".03"/><path d="M' + (ox + .1) + ' ' + (oy + .8) + 'C' + (ox + .3) + ' ' + (oy + .3) + ' ' + (ox + .6) + ' ' + (oy + .15) + ' ' + (ox + .75) + ' ' + (oy + .3) + 'C' + (ox + .85) + ' ' + (oy + .45) + ' ' + (ox + .65) + ' ' + (oy + .5) + ' ' + (ox + .62) + ' ' + (oy + .4) + 'C' + (ox + .8) + ' ' + (oy + .55) + ' ' + (ox + .85) + ' ' + (oy + .7) + ' ' + (ox + .9) + ' ' + (oy + .8) + 'Z" fill="#79d7d0" stroke="#fff" stroke-width=".03"/>'); },
  marker: function (edge, index, on) { if (!R2.svg) return; var old = R2.gSpecial.querySelector('[data-id="rogue"]'); if (old) old.remove(); if (!on) return; var p = { top: [index - 3.5, -G - .85], bottom: [index - 3.5, G + .85], left: [-G - .85, index - 3.5], right: [G + .85, index - 3.5] }[edge]; el('g', { 'data-id': 'rogue', 'pointer-events': 'none' }, R2.gSpecial, '<circle cx="' + p[0] + '" cy="' + p[1] + '" r=".25" fill="#2c6fd0" stroke="' + C.gold + '" stroke-width=".05"/><path d="M' + (p[0] - .14) + ' ' + (p[1] + .04) + 'q.07-.14 .14 0t.14 0" fill="none" stroke="#ffe9a8" stroke-width=".04" stroke-linecap="round"/>'); },
  line: function () { if (!R2.svg) return; R2.gLine.innerHTML = ''; var l = S.line; if (!l) return; var h = l.row != null; el('rect', { x: h ? -G : l.col - G, y: h ? l.row - G : -G, width: h ? 6 : 1, height: h ? 1 : 6, fill: 'rgba(90,184,255,.28)', stroke: '#5ab8ff', 'stroke-width': .03, class: 'tw2-pulse', 'pointer-events': 'none' }, R2.gLine); },
  sweep: function (axis, lane, dir) { var g = el('g', null, R2.gFx), w = el('path', { d: 'M-.4 .4Q-.2-.3 .15-.3Q.4-.2 .3 .05Q.2-.05 .15 .05Q.4 .2 .5 .4Z', fill: '#79d7d0', stroke: '#fff', 'stroke-width': .04 }, g); var start = -dir * (HALF + .6), end = dir * (HALF + .6); tween(2, function (e) { var p = lerp(start, end, e); g.setAttribute('transform', 'translate(' + (axis === 'x' ? p : lane) + ' ' + (axis === 'x' ? lane : p) + ') rotate(' + (axis === 'x' ? (dir > 0 ? 0 : 180) : (dir > 0 ? 90 : -90)) + ') scale(1.6)'); }, EASE.sine).then(function () { g.remove(); }); },
  ghost: function () { if (!R2.svg) return; R2.gGhost.innerHTML = ''; var G0 = S.ghost; if (!G0) return; var g = el('g', { opacity: G0.valid ? .82 : .6 }, R2.gGhost, R2.tileInner(G0.paths, G0.c, G0.r)); if (!G0.valid) el('rect', { x: G0.c - G + .02, y: G0.r - G + .02, width: .96, height: .96, rx: .06, fill: 'rgba(255,60,40,.35)' }, R2.gGhost); if (G0.trace && G0.trace.length) { var pts = routePts(G0.trace); el('path', { d: 'M' + pts.map(function (p) { return f2(p[0]) + ' ' + f2(p[1]); }).join('L'), fill: 'none', stroke: '#ffd978', 'stroke-width': .06, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'stroke-dasharray': '.1 .07', opacity: .95 }, R2.gGhost); } },
  dice: function (list) {
    if (!R2.svg) return; R2.gDice.innerHTML = ''; list.forEach(function (d, i) {
      var k = DIEK[d.kind] || DIEK.gold, x = (i - (list.length - 1) / 2) * .58, y = HALF - .6, P = { 1: [[0, 0]], 2: [[-.07, -.07], [.07, .07]], 3: [[-.07, -.07], [0, 0], [.07, .07]], 4: [[-.07, -.07], [.07, -.07], [-.07, .07], [.07, .07]], 5: [[-.07, -.07], [.07, -.07], [0, 0], [-.07, .07], [.07, .07]], 6: [[-.07, -.08], [.07, -.08], [-.07, 0], [.07, 0], [-.07, .08], [.07, .08]] }[d.value];
      var g = el('g', { transform: 'translate(' + x + ' ' + y + ') rotate(' + (i % 2 ? 8 : -9) + ')', 'data-die': d.kind, 'data-value': d.value }, R2.gDice, '<rect x="-.17" y="-.17" width=".34" height=".34" rx=".06" fill="' + k.f[0] + '" stroke="' + C.ink + '" stroke-width=".025" filter="url(#tw2sh)"/>' + P.map(function (p) { return '<circle cx="' + p[0] + '" cy="' + p[1] + '" r=".03" fill="' + k.p[0] + '"/>'; }).join(''));
      g.style.opacity = 0; g.style.transition = 'opacity .25s'; raf(function () { g.style.opacity = 1; });
    });
  },
  fx: function (kind, x, z, s) {
    if (!R2.svg || kind === 'bubbles' || kind === 'smoke') return; s = s || 1; var n = kind === 'chips' || kind === 'sparks' ? 8 : 0;
    var ring = el('circle', { cx: x, cy: z, r: .1, fill: 'none', stroke: kind === 'flash' ? '#ffd27a' : '#f6f2df', 'stroke-width': .05 }, R2.gFx); tween(.7, function (e) { ring.setAttribute('r', .1 + e * .55 * s); ring.setAttribute('opacity', 1 - e); }, EASE.out).then(function () { ring.remove(); });
    for (var i = 0; i < n; i++) { (function () { var a = Math.random() * 6.28, v = .5 + Math.random() * .6, c = el('circle', { cx: x, cy: z, r: .03, fill: kind === 'chips' ? '#7a4a22' : '#ffd27a' }, R2.gFx); tween(.6, function (e) { c.setAttribute('cx', x + Math.cos(a) * v * e); c.setAttribute('cy', z + Math.sin(a) * v * e); c.setAttribute('opacity', 1 - e); }, EASE.out).then(function () { c.remove(); }); })(); }
  },
  update: function (dt, t) {
    if (!R2.svg) return;
    Object.keys(S.ships).forEach(function (id) { var s = S.ships[id]; if (!s.node) return; s.node.style.display = s.alive || s.sink < 1 ? '' : 'none'; var bob = Math.sin(t * 1.7 + s.phase) * .01; s.node.setAttribute('transform', 'translate(' + f2(s.x) + ' ' + f2(s.z + bob - s.y * .5 + s.sink * .12) + ') scale(' + f2(Math.max(.01, s.scale * (1 - s.sink * .5))) + ')'); s.node.setAttribute('opacity', 1 - s.sink * .85); s.hull.setAttribute('transform', 'rotate(' + f2(s.h * 180 / Math.PI) + ')'); });
    Object.keys(S.levs).forEach(function (k) { var L = S.levs[k]; if (L.node) { var lv = L.node.querySelector('.lv'); if (lv) lv.setAttribute('transform', 'translate(0 ' + f2(-.03 * Math.sin(t * 1.5 + L.ph)) + ')'); } });
  }
};
TWKit.R2 = R2;
