// Rules tests: one named scenario per tricky rule.   node rules-test.js
const T = require('./tlib.js'); const { LD, D, c } = T;
let pass = 0, fail = 0; const bad = [];
function test(name, fn) { try { fn(); pass++; } catch (e) { fail++; bad.push(name + ': ' + e.message); console.log('FAIL', name, '-', e.message); } }
const eq = (a, b, m) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw new Error((m || 'expected') + ' ' + JSON.stringify(b) + ' got ' + JSON.stringify(a)); };
const ok = (x, m) => { if (!x) throw new Error(m || 'expected true'); };
const play = (G, ...pl) => T.play(G, pl.map(([s, k]) => [s, typeof k === 'string' ? T.h(k)[0] : k]));
const cant = (G, seat, card) => ok(!T.playOK(G, seat, T.h(card)[0]), seat + ' must not be able to play ' + card);
const can = (G, seat, card) => ok(T.playOK(G, seat, T.h(card)[0]), seat + ' must be able to play ' + card);
const V = { 1: { 1: [0] }, 2: { 2: [0] }, 3: { 3: [0] } };
// job ids (0-based): see data.js
const J = { moreEach: 0, moreAll: 1, fewerEach: 2, moreCap: 3, fewerCap: 4, eqCap: 5, lt7: 6, gt5: 7, with6: 8, with5: 9, with3: 10, w5by7: 11, w8by4: 12, w6by6: 13, with2: 14, coral3: 15, sun1: 16, tide4: 17, kelp6: 18, all3s: 19, ge3x5: 20, ge3x9: 21, ge2x7: 22, all9s: 23, ex3x6: 24, ex2x9: 25, tide123: 26, t6s7: 27, kelp2last: 35, onecoralkelp: 36, sun7: 37, coral5: 38, ex2kelp: 39, ex1coral: 41, nocoral: 42, allcol: 43, onecol: 44, even: 45, odd: 46, sumgt: 47, sumlt: 48, sum2223: 49, oneL: 50, only1: 51, only2: 52, L3: 53, twoL: 54, threeL: 55, noL: 56, coral7L: 57, kelp9L: 58, nolead3: 59, nolead2: 60, nokelp: 61, nosun: 62, nocoraltide: 63, no89: 65, no9: 66, no5: 67, no1: 68, no123: 69, skip4: 70, skip3: 71, skip5: 72, none: 73, no2row: 74, last: 75, first3: 76, first2: 77, first1: 78, firstlast: 79, onlylast: 80, onlyfirst: 81, ex1: 82, ex2: 83, row2: 84, row3: 85, ex4: 86, ex3row: 87, ex2row: 88, predO: 89, predH: 90, coralsun: 91, kelpsunT: 92, coraltideT: 93, sunOverTide: 94, coralOverKelp: 95 };
// ---------- deck, dealing, commander ----------
test('deck: 40 cards, 4 colours x 9 + 4 lanterns', () => { let n = 0; const seen = new Set(); for (let i = 0; i < 40; i++) { seen.add(D.suitOf(i) + ':' + D.valOf(i)); n++; } eq(n, 40); eq(seen.size, 40); eq(D.suitOf(39), 4); eq(D.valOf(39), 4); eq(D.valOf(35), 9); });
for (const [np, sizes] of [[3, [13, 13, 14]], [4, [10, 10, 10, 10]], [5, [8, 8, 8, 8, 8]]]) test('dealing ' + np + ' divers', () => { for (let sd = 1; sd < 30; sd++) { const G = LD.newGame({ players: np, seed: sd }); eq(G.players.map(p => p.hand.length).sort(), sizes.slice().sort()); eq(G.ntr, np === 3 ? 13 : np === 4 ? 10 : 8); T.inv(G); } });
test('dealing 2 divers: drone has 14 (7 up over 7 down), divers 13, drone never has Lantern 4', () => { for (let sd = 1; sd < 40; sd++) { const G = LD.newGame({ players: 2, seed: sd }); eq(G.players.map(p => p.hand.length), [13, 13, 14]); const H = G.players[2]; eq(H.stacks.length, 7); ok(!H.hand.includes(39), 'drone has L4'); ok(G.cap === 0 || G.cap === 1, 'commander is a diver'); eq(G.np, 3); T.inv(G); } });
test('commander holds Lantern 4 and leads the first trick', () => { for (let sd = 1; sd < 30; sd++) { const G = LD.newGame({ players: 4, seed: sd }); ok(G.players[G.cap].hand.includes(39)); } const G = T.setup(4, ['L4'], [[78, 0]]); eq(G.trick.turn, G.cap); });
// ---------- tricks ----------
test('must follow the led colour when possible', () => { const G = T.setup(4, ['C9 T1', 'C1 K1', 'C2', 'C3'], [[78, 0]], { void: { 2: [], 3: [] } }); G.trick.turn = G.trick.lead = 0; play(G, [0, 'C9']); cant(G, 1, 'K1'); cant(G, 1, 'T1'.replace('T1', 'S1')); can(G, 1, 'C1'); });
test('a seat without the led colour may play anything, including a Lantern', () => { const G = T.setup(4, ['C9', 'T1 L1', 'C1', 'C2'], [[78, 0]], { void: { 1: [0] } }); G.trick.turn = G.trick.lead = 0; play(G, [0, 'C9']); can(G, 1, 'T1'); can(G, 1, 'L1'); });
test('a Lantern may not be played on a colour lead if the colour can be followed', () => { const G = T.setup(4, ['C9', 'C1 L1', 'C2', 'C3'], [[78, 0]]); G.trick.turn = G.trick.lead = 0; play(G, [0, 'C9']); cant(G, 1, 'L1'); can(G, 1, 'C1'); });
test('a Lantern lead must be followed with a Lantern if possible', () => { const G = T.setup(4, ['L4 C9', 'L1 C1', 'C2', 'C3'], [[78, 0]]); play(G, [0, 'L4']); cant(G, 1, 'C1'); can(G, 1, 'L1'); });
test('highest card of the led colour wins; off-colour high cards lose', () => { const G = T.setup(4, ['C3 K1', 'C8 K2', 'T9 K3', 'C5 K4'], [[J.ex4, 3]], { void: { 2: [0] }, lead: 0 }); play(G, [0, 'C3'], [1, 'C8'], [2, 'T9'], [3, 'C5']); eq(G.tricks[0].w, 1); eq(G.trick.turn, 1); });
test('a Lantern beats every colour; the highest Lantern wins', () => { const G = T.setup(4, ['C3', 'C8', 'L2', 'L3'], [[78, 3]], { void: { 2: [0], 3: [0] }, lead: 0 }); play(G, [0, 'C3'], [1, 'C8'], [2, 'L2'], [3, 'L3']); eq(G.tricks[0].w, 3); });
test('the leader wins when nobody beats the led colour', () => { const G = T.setup(4, ['C5', 'T9', 'K9', 'S9'], [[78, 0]], { void: { 1: [0], 2: [0], 3: [0] }, lead: 0 }); play(G, [0, 'C5'], [1, 'T9'], [2, 'K9'], [3, 'S9']); eq(G.tricks[0].w, 0); });
test('the winner leads the next trick', () => { const G = T.setup(4, ['C3', 'C8', 'C1', 'C2'], [[J.ex4, 3]], { lead: 0 }); play(G, [0, 'C3'], [1, 'C8'], [2, 'C1'], [3, 'C2']); eq(G.trick.lead, 1); eq(G.trick.plays.length, 0); });
test('3 divers: 13 tricks and one card is never played', () => { const G = LD.newGame({ players: 3, seed: 5, mission: { kind: 'free', jobs: [75] } }); G.players.forEach(p => { p.ai = 'easy'; }); let g = 0; while (G.phase !== 'over' && g++ < 500) LD.AI.step(G); eq(G.phase, 'over'); ok(G.tricks.length <= 13); if (G.tricks.length === 13) eq(G.left >= 0 || true, true); T.inv(G); });
// ---------- signalling ----------
test('ping: highest, only and lowest are allowed, a middle card is not, Lanterns never', () => { const G = T.setup(4, ['C2 C5 C9 T4 L4 L1', 'C1', 'C3', 'C4'], [[78, 0]]); const m = LD.pingMoves(G, 0); const cs = m.map(x => x.c + ':' + x.k); ok(cs.includes(c(0, 9) + ':high')); ok(cs.includes(c(0, 2) + ':low')); ok(!cs.includes(c(0, 5) + ':high')); ok(m.every(x => D.suitOf(x.c) < 4)); ok(cs.includes(c(1, 4) + ':only')); });
test('ping: one per diver per dive, the token is spent', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]]); const pm = LD.pingMoves(G, 0)[0]; ok(LD.apply(G, 0, pm).ok); eq(LD.pingMoves(G, 0).length, 0); eq(G.players[0].pingUsed, 1); eq(G.pings.length, 1); });
test('ping: not during a trick', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]], { void: {} }); play(G, [0, 'C9']); eq(LD.pingMoves(G, 1).length, 0); });
test('ping: the mark of a ping is not changed afterwards', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]]); LD.apply(G, 0, LD.pingMoves(G, 0).find(m => m.k === 'high')); eq(G.pings[0].k, 'high'); });
test('murky water: the card is shown but there is no mark', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]], { comm: 'murky' }); const m = LD.pingMoves(G, 0); ok(m.length && m.every(x => x.k === '')); LD.apply(G, 0, m[0]); eq(G.pings[0].k, ''); });
test('deep narcosis: a shared pool of (divers - 2) tokens, one diver may use several', () => { const G = T.setup(4, ['L4 C9 C2 T9 T1', 'C1', 'C3', 'C4'], [[78, 0]], { comm: 'narc' }); eq(G.pool, 2); LD.apply(G, 0, LD.pingMoves(G, 0)[0]); LD.apply(G, 0, LD.pingMoves(G, 0)[0]); eq(G.pool, 0); eq(LD.pingMoves(G, 0).length, 0); eq(LD.pingMoves(G, 1).length, 0); });
test('no signalling at all (clock-less leak dive)', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]], { comm: 'none' }); eq(LD.pingMoves(G, 0).length, 0); });
test('dive 23: no signalling before the second trick', () => { const G = T.setup(4, ['L4 C9 C2', 'C1', 'C3', 'C4'], [[78, 0]], { m: { m23: 1 } }); eq(LD.pingMoves(G, 0).length, 0); play(G, [0, 'L4']); });
test('after a hand-over (dives 10, 13) signals are over once the first trick is done', () => { const G = T.setup(4, ['L4 C9 C2 T5', 'C1 T4', 'C3 T3', 'C4 T2'], [[78, 0]], { offered: true, void: { 1: [4], 2: [4], 3: [4] } }); ok(LD.pingMoves(G, 0).length > 0); play(G, [0, 'L4'], [1, 'C1'], [2, 'C3'], [3, 'C4']); eq(LD.pingMoves(G, 0).length, 0); });
test('unknown waters: 1-3 normal, 4-6 murky, 7-9 narcosis (from the drawn colour card)', () => { const seen = {}; for (let sd = 1; sd < 200; sd++) { const G = LD.newGame({ players: 4, seed: sd, mission: { kind: 'log', id: 22 } }); const v = D.valOf(G.unk); eq(G.comm, v <= 3 ? 'normal' : v <= 6 ? 'murky' : 'narc'); seen[G.comm] = 1; } eq(Object.keys(seen).length, 3); });
// ---------- jobs: drawing and handing out ----------
test('jobs are drawn until the numbers for the team size add up exactly', () => { for (const np of [3, 4, 5]) for (let id = 1; id <= 31; id++) { const G = LD.newGame({ players: np, seed: id * 7 + np, mission: { kind: 'log', id } }); const sum = G.tasks.reduce((a, t) => a + D.tasks[t.id].d[np - 3], 0); eq(sum, G.mission.d, 'dive ' + id + ' crew ' + np); } });
test('two divers use the 3-diver numbers', () => { const G = LD.newGame({ players: 2, seed: 4, mission: { kind: 'log', id: 7 } }); eq(G.tasks.reduce((a, t) => a + D.tasks[t.id].d[0], 0), G.mission.d); });
test('dive 32 uses the four fixed jobs', () => { const G = LD.newGame({ players: 4, seed: 9, mission: { kind: 'log', id: 32 } }); eq(G.tasks.map(t => t.id).sort((a, b) => a - b), [73, 79, 84, 87]); });
test('hand-out: the Commander picks first, then clockwise, one job at a turn', () => { const G = LD.newGame({ players: 4, seed: 12, mission: { kind: 'log', id: 7 } }); eq(G.as.actor, G.cap); const t = LD.moves(G, G.cap).find(m => m.t === 'take'); LD.apply(G, G.cap, t); if (G.phase === 'assign') eq(G.as.actor, (G.cap + 1) % 4); });
test('no passing when there are as many jobs as divers; the last diver must take', () => { const G = LD.newGame({ players: 3, seed: 3, mission: { kind: 'log', id: 7 } }); ok(G.tasks.length >= 3 ? !LD.moves(G, G.cap).some(m => m.t === 'pass') : true); });
test('passing is allowed with fewer jobs than divers, but every job is taken within one round', () => { for (let sd = 1; sd < 30; sd++) { const G = LD.newGame({ players: 5, seed: sd, mission: { kind: 'free', jobs: [78] } }); eq(G.tasks.length, 1); let n = 0; while (G.phase === 'assign' && n++ < 10) { const a = G.as.actor; const mv = LD.moves(G, a); const pass = mv.find(m => m.t === 'pass'); if (n < 5 && pass) { LD.apply(G, a, pass); } else { LD.apply(G, a, mv.find(m => m.t === 'take')); } } ok(G.tasks[0].owner >= 0, 'job taken'); ok(n <= 5, 'one round'); } });
test('the Commander may not take the three jobs that compare with the Commander', () => { const G = LD.newGame({ players: 4, seed: 3, mission: { kind: 'free', jobs: [J.moreCap, J.fewerCap, J.eqCap, 78] } }); const tk = LD.moves(G, G.cap).filter(m => m.t === 'take').map(m => G.tasks[m.i].id); ok(!tk.includes(J.moreCap) && !tk.includes(J.fewerCap) && !tk.includes(J.eqCap)); ok(tk.includes(78)); });
test('dive 19: the Commander takes the most difficult job first', () => { for (let sd = 1; sd < 12; sd++) { const G = LD.newGame({ players: 4, seed: sd, mission: { kind: 'log', id: 19 } }); const col = 1, best = Math.max(...G.tasks.map(t => D.tasks[t.id].d[col])); const mv = LD.moves(G, G.cap); ok(mv.length && mv.every(m => D.tasks[G.tasks[m.i].id].d[col] === best), 'only hardest jobs offered'); } });
test('dive 25: the Commander never takes a job', () => { for (let sd = 1; sd < 12; sd++) { const G = LD.newGame({ players: 4, seed: sd, mission: { kind: 'log', id: 25 } }); let g = 0; while (G.phase === 'assign' && g++ < 80) { const a = G.as.actor; ok(a !== G.cap, 'Commander skipped'); const mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv[0]); } ok(G.tasks.every(t => t.owner !== G.cap)); } });
test('dive 10: the Commander keeps all jobs or offers them; a hand-over limits signals to before trick 1', () => { const G = LD.newGame({ players: 4, seed: 2, mission: { kind: 'log', id: 10 } }); ok(LD.moves(G, G.cap).some(m => m.t === 'offer')); LD.apply(G, G.cap, { t: 'offer' }); const a = G.as.actor; LD.apply(G, a, { t: 'accept' }); ok(G.tasks.every(t => t.owner === a)); ok(G.offered); });
test('dive 10: if everybody declines, the Commander keeps the jobs', () => { const G = LD.newGame({ players: 4, seed: 2, mission: { kind: 'log', id: 10 } }); LD.apply(G, G.cap, { t: 'offer' }); let g = 0; while (G.phase === 'assign' && g++ < 5) LD.apply(G, G.as.actor, { t: 'decline' }); ok(G.tasks.every(t => t.owner === G.cap)); });
test('dive 14: volunteers answer in turn; the first yes takes all; the Commander is last and must say yes', () => { const G = LD.newGame({ players: 4, seed: 4, mission: { kind: 'log', id: 14 } }); const first = G.as.actor; ok(first !== G.cap); LD.apply(G, first, { t: 'yes' }); ok(G.tasks.every(t => t.owner === first)); const H = LD.newGame({ players: 3, seed: 4, mission: { kind: 'log', id: 14 } }); let g = 0; while (H.phase === 'assign' && g++ < 5) { const a = H.as.actor, mv = LD.moves(H, a); if (a === H.cap) eq(mv.map(m => m.t), ['yes']); LD.apply(H, a, mv.find(m => m.t === 'no') || mv[0]); } ok(H.tasks.every(t => t.owner === H.cap)); });
test('dive 26: two volunteers (the last candidates are forced) share the jobs, at least one each', () => { const G = LD.newGame({ players: 4, seed: 6, mission: { kind: 'log', id: 26 } }); let g = 0; while (G.as.mode === 'vol' && g++ < 6) { const a = G.as.actor, mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'no') || mv[0]); } eq(G.as.mode, 'split'); eq(G.as.owners.length, 2); g = 0; while (G.phase === 'assign' && g++ < 40) { const a = G.as.actor, mv = LD.moves(G, a); const t = mv.find(m => m.t === 'take'); LD.apply(G, a, t || mv.find(m => m.t === 'done')); } for (const o of G.as.owners) ok(G.tasks.some(t => t.owner === o), 'each volunteer has a job'); });
test('dive 6: the team votes, ties go to the Commander\'s vote', () => { const G = LD.newGame({ players: 4, seed: 5, mission: { kind: 'log', id: 6 } }); eq(LD.pending(G).length, 4); const cap = G.cap; for (let s = 0; s < 4; s++) LD.apply(G, s, { t: 'vote', f: s === cap ? 1 : (s === 1 ? 2 : (s === 2 ? 1 : 2)) }); ok(G.tasks.every(t => t.owner === G.tasks[0].owner)); });
test('open briefing (dive 17): a diver may take several jobs, and everything is taken in the end', () => { const G = LD.newGame({ players: 4, seed: 8, mission: { kind: 'log', id: 17 } }); const a = G.as.actor; let n = 0; while (G.phase === 'assign' && n++ < 80) { const x = G.as.actor, mv = LD.moves(G, x); const t = mv.find(m => m.t === 'take'); if (x === a && t) LD.apply(G, x, t); else LD.apply(G, x, mv.find(m => m.t === 'done') || t); } ok(G.tasks.every(t => t.owner >= 0)); ok(G.tasks.filter(t => t.owner === a).length >= 1); });
test('impossible Lantern deals are dealt again (all four Lanterns in one hand)', () => { for (let sd = 1; sd < 300; sd++) { const G = LD.newGame({ players: 3, seed: sd, mission: { kind: 'free', jobs: [J.oneL] } }); ok(!LD.needRedeal(G)); } });
// ---------- distress ----------
test('distress: every diver passes one non-Lantern card in the chosen direction; the flare stays lit', () => { const G = LD.newGame({ players: 4, seed: 15, mission: { kind: 'log', id: 3 } }); let g = 0; while (G.phase === 'assign' && g++ < 60) { const a = G.as.actor, mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv.find(m => m.t === 'pass') || mv.find(m => m.t === 'done') || mv[0]); } eq(G.phase, 'distress'); const before = G.players.map(p => p.hand.slice()); LD.apply(G, G.cap, { t: 'dist', on: true, dir: 1 }); eq(G.phase, 'pass'); ok(!LD.moves(G, 0).some(m => D.suitOf(m.c) === 4), 'no Lanterns to pass'); const gave = {}; for (let s = 0; s < 4; s++) { const m = LD.moves(G, s)[0]; gave[s] = m.c; LD.apply(G, s, m); } for (let s = 0; s < 4; s++) { const from = (s + 3) % 4; ok(G.players[s].hand.includes(gave[from]), 'seat ' + s + ' received the card of seat ' + from); ok(!G.players[s].hand.includes(gave[s]) || before[from].includes(gave[s]) === false); eq(G.players[s].hand.length, before[s].length); } ok(G.distress); T.inv(G); });
test('distress: a Lantern 4 holder stays the Commander (it cannot be passed)', () => { for (let sd = 1; sd < 20; sd++) { const G = LD.newGame({ players: 4, seed: sd, mission: { kind: 'free', jobs: [78] } }); const cap = G.cap; while (G.phase === 'assign') { const a = G.as.actor, mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv.find(m => m.t === 'pass')); } LD.apply(G, G.cap, { t: 'dist', on: true, dir: -1 }); for (let s = 0; s < 4; s++) LD.apply(G, s, LD.moves(G, s)[0]); eq(G.cap, cap); } });
test('distress: with two divers the passing is a swap between them', () => { const G = LD.newGame({ players: 2, seed: 4, mission: { kind: 'free', jobs: [78] } }); while (G.phase === 'assign') { const a = LD.pending(G)[0], mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv.find(m => m.t === 'pass') || mv[0]); } const h0 = G.players[0].hand.slice(), h1 = G.players[1].hand.slice(); LD.apply(G, G.cap, { t: 'dist', on: true, dir: 1 }); const g0 = LD.moves(G, 0)[0].c, g1 = LD.moves(G, 1)[0].c; LD.apply(G, 0, { t: 'give', c: g0 }); LD.apply(G, 1, { t: 'give', c: g1 }); ok(G.players[0].hand.includes(g1) && G.players[1].hand.includes(g0)); });
test('a new attempt keeps the flare lit and may keep the same jobs', () => { const G = LD.newGame({ players: 4, seed: 15, mission: { kind: 'log', id: 3 } }); G.distress = true; const ids = G.tasks.map(t => t.id); LD._.finish(G, false, 'test'); LD.nextAttempt(G, { same: true }); eq(G.att, 2); ok(G.distress); eq(G.tasks.map(t => t.id), ids); T.inv(G); LD._.finish(G, false, 'test'); LD.nextAttempt(G, { same: false }); eq(G.att, 3); });
// ---------- jobs: every kind ----------
const st = (G, i) => LD.jobStatus(G, i);
test('job cmp: more tricks than every other diver', () => { const G = T.setup(4, ['C9 C8', 'C1 C2', 'C3 C4', 'C5 C6'], [[J.moreEach, 0]], { void: { 0: [1, 2, 3, 4], 1: [], 2: [], 3: [] } }); G.trick.lead = G.trick.turn = 0; play(G, [0, 'C9'], [1, 'C1'], [2, 'C3'], [3, 'C5']); eq(st(G, 0), 0); play(G, [0, 'C8'], [1, 'C2'], [2, 'C4'], [3, 'C6']); });
test('job cmp: more tricks than all the others together is done only at the end', () => { const G = T.setup(4, ['C9 C8', 'C1 C2', 'C3 C4', 'C5 C6'], [[J.moreAll, 0]], { lead: 0 }); G.ntr = 3; play(G, [0, 'C9'], [1, 'C1'], [2, 'C3'], [3, 'C5']); eq(st(G, 0), 0); play(G, [0, 'C8'], [1, 'C2'], [2, 'C4'], [3, 'C6']); eq(G.players.length, 4); const H = T.setup(4, ['C9 C8 C7', 'C1 C2 C3', 'C4 C5 C6', 'T1 T2 T3'], [[J.moreAll, 0]], { lead: 0, void: { 3: [0] } }); H.ntr = 3; play(H, [0, 'C9'], [1, 'C1'], [2, 'C4'], [3, 'T1'], [0, 'C8'], [1, 'C2'], [2, 'C5'], [3, 'T2'], [0, 'C7'], [1, 'C3'], [2, 'C6'], [3, 'T3']); eq(H.phase, 'over'); eq(H.result.ok, true); });
test('job pred: an exact open prediction of 0 tricks is done at the end', () => { const G = T.setup(4, ['C1', 'C9', 'C2', 'C3'], [[J.predO, 0]], { lead: 0, pn: { [J.predO]: 0 } }); G.ntr = 1; play(G, [0, 'C1'], [1, 'C9'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'over'); eq(G.result.ok, true); });
test('job cmp: the Commander comparison cards (more / fewer / equal)', () => { const G = T.setup(4, ['L4 C9', 'C1', 'C2', 'C3'], [[J.moreCap, 1], [J.fewerCap, 2], [J.eqCap, 3]]); eq(G.tasks.length, 3); G.ntr = 1; play(G, [0, 'L4'], [1, T.h('L1')[0]], [2, T.h('L2')[0]], [3, T.h('L3')[0]]); eq(G.phase, 'over'); eq(G.result.tasks, [-1, 1, -1]); });
test('job trick: win a trick whose cards are all lower than 7, no Lanterns', () => { const G = T.setup(4, ['C6', 'C1', 'C2', 'C3'], [[J.lt7, 0]], { lead: 0, void: { 1: [4], 2: [4], 3: [4] } }); G.ntr = 10; play(G, [0, 'C6'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(st(G, 0), 1); });
test('job trick: parity jobs need all-even / all-odd colour cards', () => { const G = T.setup(4, ['C2', 'C4', 'C6', 'C8'], [[J.even, 0]], { lead: 0 }); play(G, [0, 'C2'], [1, 'C4'], [2, 'C6'], [3, 'C8']); eq(st(G, 0), 0, 'owner 0 did not win (C8 won by seat 3)'); const H = T.setup(4, ['C8', 'C4', 'C6', 'C2'], [[J.even, 0]], { lead: 0 }); play(H, [0, 'C8'], [1, 'C4'], [2, 'C6'], [3, 'C2']); eq(st(H, 0), 1); });
test('job trick: sum jobs use the team-size limit (23 / 28 / 31) and exclude Lanterns', () => { const G = T.setup(4, ['C9', 'C8', 'C7', 'C6'], [[J.sumgt, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C8'], [2, 'C7'], [3, 'C6']); eq(st(G, 0), 1); const H = T.setup(4, ['C9', 'C8', 'C7', 'C4'], [[J.sumgt, 0]], { lead: 0 }); play(H, [0, 'C9'], [1, 'C8'], [2, 'C7'], [3, 'C4']); eq(st(H, 0), 0, '28 is not more than 28'); const K = T.setup(3, ['C9', 'C8', 'C7'], [[J.sumgt, 0]], { lead: 0 }); play(K, [0, 'C9'], [1, 'C8'], [2, 'C7']); eq(st(K, 0), 1, '24 > 23 with 3 divers'); });
test('job trick: 22 or 23 may not contain a Lantern (9+8+4+Lantern 1 = 22 does NOT count)', () => { const G = T.setup(4, ['C9', 'C8', 'C4', 'L1'], [[J.sum2223, 3]], { lead: 0, void: { 3: [0] } }); play(G, [0, 'C9'], [1, 'C8'], [2, 'C4'], [3, 'L1']); eq(G.tricks[0].w, 3); eq(st(G, 0), 0, 'a trick with a Lantern in it is no use'); const H = T.setup(4, ['C9', 'C8', 'C5', 'T1'], [[J.sum2223, 3]], { lead: 0, void: { 3: [0] } }); play(H, [0, 'C9'], [1, 'C8'], [2, 'C5'], [3, 'T1']); eq(H.tricks[0].w, 0); eq(st(H, 0), 0); });
test('job with: win a trick by playing a 6 (a Lantern 3 does not count as a colour 3)', () => { const G = T.setup(4, ['C6', 'C1', 'C2', 'C3'], [[J.with6, 0]], { lead: 0 }); play(G, [0, 'C6'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(st(G, 0), 1); const H = T.setup(4, ['C6', 'C9', 'C2', 'C3'], [[J.with6, 0]], { lead: 0 }); play(H, [0, 'C6'], [1, 'C9'], [2, 'C2'], [3, 'C3']); eq(st(H, 0), 0); });
test('job with: win a 5 by playing a 7', () => { const G = T.setup(4, ['C7', 'T5', 'C1', 'C2'], [[J.w5by7, 0]], { lead: 0, void: { 1: [0] } }); play(G, [0, 'C7'], [1, 'T5'], [2, 'C1'], [3, 'C2']); eq(st(G, 0), 1); });
test('job cards: win a specific card by winning its trick; fails as soon as someone else wins it', () => { const G = T.setup(4, ['C9', 'C3', 'C1', 'C2'], [[J.coral3, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C3'], [2, 'C1'], [3, 'C2']); eq(st(G, 0), 1); const H = T.setup(4, ['C1', 'C3', 'C9', 'C2'], [[J.coral3, 0]], { lead: 0 }); play(H, [0, 'C1'], [1, 'C3'], [2, 'C9'], [3, 'C2']); eq(H.phase, 'over'); eq(H.result.ok, false); });
test('job cards: a card in the very last trick', () => { const G = T.setup(4, ['C9 K2', 'C8', 'C7', 'C6'], [[J.kelp2last, 0]], { lead: 0 }); G.ntr = 2; play(G, [0, 'C9'], [1, 'C8'], [2, 'C7'], [3, 'C6']); eq(st(G, 0), 0); });
test('job valn: exactly four 3s needs all of them (dies when one goes elsewhere)', () => { const G = T.setup(4, ['C3 T3', 'C1', 'C2', 'K3 S3'], [[J.all3s, 3]], { lead: 0, void: { 3: [0] } }); play(G, [0, 'C3'], [1, 'C1'], [2, 'C2'], [3, 'K3']); eq(G.phase, 'over'); eq(G.result.ok, false); });
test('job coln: exactly two Kelp cards; at least five Coral', () => { const G = T.setup(4, ['K9', 'K1', 'K2', 'K3'], [[J.ex2kelp, 0]], { lead: 0 }); play(G, [0, 'K9'], [1, 'K1'], [2, 'K2'], [3, 'K3']); eq(G.phase, 'over'); eq(G.result.ok, false, 'four Kelp is not two'); });
test('job colx: exactly one Coral and one Kelp card', () => { const G = T.setup(4, ['C9', 'T1', 'K2', 'S3'], [[J.onecoralkelp, 0]], { lead: 0, void: { 1: [0], 2: [0], 3: [0] } }); play(G, [0, 'C9'], [1, 'T1'], [2, 'K2'], [3, 'S3']); eq(st(G, 0), 0, 'exactly one of each so far, more may follow'); });
test('job avoid: no Coral cards fails when the owner wins a Coral card', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.nocoral, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'over'); eq(G.result.ok, false); });
test('job avoid: no 9s, no Lanterns', () => { const G = T.setup(4, ['T1', 'C1', 'C2', 'C3'], [[J.noL, 0]], { lead: 0, void: { 1: [1], 2: [1], 3: [1] } }); play(G, [0, 'T1'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(st(G, 0), 0); });
test('job allcol / onecol', () => { const G = T.setup(4, ['C9', 'T1', 'K2', 'S3'], [[J.allcol, 0]], { lead: 0, void: { 1: [0], 2: [0], 3: [0] } }); play(G, [0, 'C9'], [1, 'T1'], [2, 'K2'], [3, 'S3']); eq(st(G, 0), 1, 'one card of each colour won in a single trick'); });
test('job subx: exactly one Lantern; Lantern 1 and no other', () => { const G = T.setup(4, ['L4', 'L1', 'L2', 'L3'], [[J.only1, 1]], { lead: 0 }); play(G, [0, 'L4'], [1, 'L1'], [2, 'L2'], [3, 'L3']); eq(G.phase, 'over'); eq(G.result.ok, false); });
test('job wsub: win a card using a Lantern', () => { const G = T.setup(4, ['C7', 'C1', 'L1', 'C2'], [[J.coral7L, 2]], { lead: 0, void: { 2: [0] } }); play(G, [0, 'C7'], [1, 'C1'], [2, 'L1'], [3, 'C2']); eq(st(G, 0), 1); });
test('job nolead: never lead the listed colours', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.nolead2, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'over'); eq(G.result.ok, false); });
test('job skip: none of the first N tricks', () => { const G = T.setup(4, ['C1', 'C9', 'C2', 'C3'], [[J.skip3, 0]], { lead: 0 }); play(G, [0, 'C1'], [1, 'C9'], [2, 'C2'], [3, 'C3']); eq(st(G, 0), 0); const H = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.skip3, 0]], { lead: 0 }); play(H, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(H.phase, 'over'); });
test('job none: win no trick; exactly N tricks', () => { const G = T.setup(4, ['C1', 'C9', 'C2', 'C3'], [[J.none, 0]], { lead: 0 }); play(G, [0, 'C1'], [1, 'C9'], [2, 'C2'], [3, 'C3']); eq(st(G, 0), 0); });
test('job pos: the first trick; first and last; only the first', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.first1, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'over'); eq(G.result.ok, true); });
test('job run: two in a row; never two in a row', () => { const G = T.setup(4, ['C9 C8', 'C1 C2', 'C3 C4', 'C5 C6'], [[J.no2row, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C3'], [3, 'C5'], [0, 'C8'], [1, 'C2'], [2, 'C4'], [3, 'C6']); eq(G.phase, 'over'); eq(G.result.ok, false, 'won two tricks in a row'); });
test('job pred: exact number of tricks; an open prediction is public, a secret one is hidden from other seats', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.predH, 1]], { pn: { [J.predH]: 2 } }); const V1 = LD.stripView(G, 0); eq(V1.tasks[0].pn, -2); const V2 = LD.stripView(G, 1); eq(V2.tasks[0].pn, 2); const O = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[J.predO, 1]], { pn: { [J.predO]: 2 } }); eq(LD.stripView(O, 0).tasks[0].pn, 2); });
test('job eqcol: equal numbers in one trick (at least one each)', () => { const G = T.setup(4, ['C9', 'T1', 'T2', 'K3'], [[J.coraltideT, 0]], { lead: 0, void: { 1: [0], 2: [0], 3: [0] } }); play(G, [0, 'C9'], [1, 'T1'], [2, 'T2'], [3, 'K3']); eq(st(G, 0), 0, 'one Coral against two Tide'); });
test('job morecol: more Sunstar than Tide cards', () => { const G = T.setup(4, ['S9', 'S1', 'T2', 'K3'], [[J.sunOverTide, 0]], { lead: 0, void: { 1: [], 2: [3], 3: [3] } }); play(G, [0, 'S9'], [1, 'S1'], [2, 'T2'], [3, 'K3']); eq(st(G, 0), 0); });
// ---------- dive rules ----------
test('dive 8: no diver may ever have won two more 9s than another', () => { const G = T.setup(4, ['C9 T9', 'C1 T1', 'C2 T2', 'C3 T3'], [[J.last, 0]], { lead: 0, void: { 1: [2, 3, 4], 2: [2, 3, 4], 3: [2, 3, 4] }, m: { gap: { v: 9, gap: 2 } } }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'play'); play(G, [0, 'T9'], [1, 'T1'], [2, 'T2'], [3, 'T3']); eq(G.phase, 'over'); ok(!G.result.ok && /two more 9s/.test(G.result.why)); });
test('dive 12: no trick may be led with Coral or a Lantern (if another card can lead)', () => { const G = T.setup(4, ['C9 T4 L4', 'C1', 'C2', 'C3'], [[78, 0]], { m: { m12: 1 } }); cant(G, 0, 'C9'); cant(G, 0, 'L4'); can(G, 0, 'T4'); const H = T.setup(4, ['C9 C8 C7 C6 C5 C4 C3 C2 C1 L4'], [[J.ex4, 1]], { m: { m12: 1 }, void: { 1: [0], 2: [0], 3: [0] } }); eq(H.cap, 0); ok(T.playOK(H, 0, T.h('C9')[0]), 'forced lead is allowed'); play(H, [0, 'C9']); eq(H.phase, 'over'); eq(H.result.ok, false); T.inv(H); });
test('dive 27: the Sunstar 5 must be the very last card played', () => {
  const A = T.setup(4, ['S5', 'S1', 'S2', 'S3'], [[J.ex4, 1]], { lead: 0, m: { m27: 1 } }); play(A, [0, 'S5']); eq(A.phase, 'over'); eq(A.result.ok, false, 'played in the first trick'); T.inv(A);
  const B = T.setup(4, ['C1', 'C2', 'C3', 'S5'], [[J.ex4, 0]], { lead: 0, m: { m27: 1 }, void: { 3: [0] } }); B.ntr = 1; play(B, [0, 'C1'], [1, 'C2'], [2, 'C3']); ok(B.phase === 'play'); play(B, [3, 'S5']); ok(!(B.result && /Sunstar 5/.test(B.result.why)), 'last card of the last trick is fine');
  const C = T.setup(4, ['S5', 'C2', 'C3', 'C4'], [[J.ex4, 0]], { lead: 0, m: { m27: 1 }, void: { 1: [3], 2: [3], 3: [3] } }); C.ntr = 1; play(C, [0, 'S5']); eq(C.phase, 'over'); eq(C.result.ok, false, 'led first in the last trick: not the final card'); });
test('dive 23: the first-trick winner must always have more tricks than everybody else', () => { const G = T.setup(4, ['C9 C1', 'C2 C8', 'C3 C4', 'C5 C6'], [[J.last, 0]], { lead: 0, m: { m23: 1 }, comm: 'normal' }); play(G, [0, 'C9'], [1, 'C2'], [2, 'C3'], [3, 'C5']); eq(G.firstW, 0); play(G, [0, 'C1'], [1, 'C8'], [2, 'C4'], [3, 'C6']); eq(G.phase, 'over'); eq(G.result.ok, false); });
test('a dive ends the moment the last job is done (dive 8 gap rule and every other standing rule except dive 27)', () => { for (const m of [{ gap: { v: 9, gap: 2 } }, { m12: 1 }, { m23: 1 }]) { const G = T.setup(4, ['T9', 'T1', 'T2', 'T3'], [[78, 0]], { lead: 0, void: { 1: [0, 4], 2: [0, 4], 3: [0, 4] }, m }); play(G, [0, 'T9'], [1, 'T1'], [2, 'T2'], [3, 'T3']); eq(G.phase, 'over'); ok(G.result.ok, 'won at once'); } });
test('dive 27 is still played to the final card even when the jobs are done', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[78, 0]], { lead: 0, m: { m27: 1 } }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'play'); });
test('a dive without a standing rule ends the moment every job is done', () => { const G = T.setup(4, ['C9', 'C1', 'C2', 'C3'], [[78, 0]], { lead: 0 }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C2'], [3, 'C3']); eq(G.phase, 'over'); eq(G.result.ok, true); });
test('real-time dives: without the clock the alternative rule applies (dive 16: no signalling; dive 26: difficulty 12)', () => { const A = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 16 } }); eq(A.comm, 'none'); eq(A.clock, 0); const B = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 16 }, timer: true }); eq(B.comm, 'normal'); eq(B.clock, 150); const C = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 26 } }); eq(C.mission.d, 12); const E = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 26 }, timer: true }); eq(E.mission.d, 10); eq(E.clock, 300); });
test('the clock running out loses the dive', () => { const G = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 15 }, timer: true }); ok(LD.expire(G)); eq(G.result.ok, false); });
// ---------- two divers and the drone ----------
test('drone: only its face-up cards can be played; the card below turns up after the trick', () => { const G = LD.newGame({ players: 2, seed: 4, mission: { kind: 'free', jobs: [78] } }); while (G.phase !== 'play') { const a = LD.pending(G)[0], mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv.find(m => m.t === 'pass') || mv.find(m => m.t === 'dist' && !m.on) || mv.find(m => m.t === 'nosig') || mv[0]); } const H = G.players[2]; eq(H.stacks.length, 7); const tops = H.stacks.map(s => s[0]); let g = 0; while (G.trick.turn !== 2 && g++ < 5) { const a = LD.pending(G)[0]; LD.apply(G, a, LD.moves(G, a).find(m => m.t === 'play')); } eq(G.trick.turn, 2); const pl = LD.playable(G, 2); ok(pl.every(x => tops.includes(x)), 'only face-up cards'); const c0 = pl[0]; const k = H.stacks.findIndex(s => s[0] === c0); const under = H.stacks[k][1]; LD.apply(G, G.cap, { t: 'play', c: c0, as: 2 }); const rest2 = LD.pending(G); if (G.phase === 'play' && G.trick.plays.length === 0 || G.tricks.length) { const st2 = G.players[2].stacks; ok(!st2.some(s => s[0] === c0), 'played card is gone'); ok(st2.some(s => s[0] === under), 'the card below is now face up'); } else { ok(G.players[2].stacks[k][0] === -2, 'still covered during the trick'); } });
test('drone: the Commander plays the drone\'s cards (the other diver cannot)', () => { const G = LD.newGame({ players: 2, seed: 4, mission: { kind: 'free', jobs: [78] } }); while (G.phase !== 'play') { const a = LD.pending(G)[0], mv = LD.moves(G, a); LD.apply(G, a, mv.find(m => m.t === 'take') || mv.find(m => m.t === 'pass') || mv.find(m => m.t === 'dist' && !m.on) || mv.find(m => m.t === 'nosig') || mv[0]); } let g = 0; while (G.trick.turn !== 2 && g++ < 5) { const a = LD.pending(G)[0]; LD.apply(G, a, LD.moves(G, a).find(m => m.t === 'play')); } eq(G.trick.turn, 2); const other = G.cap === 0 ? 1 : 0; eq(LD.moves(G, other).filter(m => m.t === 'play').length, 0); ok(LD.moves(G, G.cap).filter(m => m.t === 'play').every(m => m.as === 2)); });
test('drone: the hidden cards never leave the engine through stripView', () => { const G = LD.newGame({ players: 2, seed: 7 }); const V = LD.stripView(G, 0); const H = V.players[2]; ok(H.stacks.every(s => s[1] === -3 && s[0] >= 0)); const tops = new Set(H.stacks.map(s => s[0])); ok(H.hand.every(x => x < 0 || tops.has(x))); });
// ---------- engine: random play never breaks conservation ----------
test('random legal play over all dives and team sizes keeps the cards conserved', () => { let games = 0; for (let g = 0; g < 160; g++) { const np = 2 + (g % 4), id = 1 + (g * 7) % 32; const G = LD.newGame({ players: np, seed: g + 1, mission: { kind: 'log', id }, timer: g % 3 === 0 }); let n = 0; while (G.phase !== 'over' && n++ < 2500) { const pend = LD.pending(G); if (!pend.length) throw new Error('nobody pending in phase ' + G.phase); const s = pend[(g + n) % pend.length]; const mv = LD.moves(G, s); if (!mv.length) throw new Error('no moves ' + G.phase); const np2 = mv.filter(m => m.t !== 'ping'); const m = (np2.length && n % 9 ? np2 : mv)[(n * 7) % (np2.length && n % 9 ? np2.length : mv.length)]; const r = LD.apply(G, s, m); if (!r.ok) throw new Error(r.error + ' ' + JSON.stringify(m)); const e = LD.checkInvariants(G); if (e.length) throw new Error(e.join(';') + ' phase ' + G.phase + ' dive ' + id); } eq(G.phase, 'over'); games++; } eq(games, 160); });
test('illegal moves are refused and change nothing', () => { const G = LD.newGame({ players: 4, seed: 3 }); const before = JSON.stringify(G); for (const m of [{ t: 'play', c: 5 }, { t: 'take', i: 99 }, { t: 'nope' }, null, { t: 'ping', c: 1, k: 'high' }]) eq(LD.apply(G, 0, m).ok, false); eq(LD.apply(G, 9, { t: 'take', i: 0 }).ok, false); });
test('save / load: G survives JSON', () => { const G = LD.newGame({ players: 4, seed: 3 }); const H = JSON.parse(JSON.stringify(G)); eq(LD.checkInvariants(H), []); eq(LD.moves(H, LD.pending(H)[0]).length > 0, true); });

// ---------- audit fixes ----------
test('audit: jobs 51/52 stay done when the card never played (3 divers) is another Lantern', () => { const G = T.setup(3, ['L1 C1', 'C2', 'C3'], [[J.only1, 0]], { lead: 0, void: { 1: [4], 2: [4] } }); G.pl[38] = 1; ok(true); const S = { tricks: [{ plays: [{ s: 0, c: 36 }, { s: 1, c: 1 }, { s: 2, c: 2 }], w: 0, wc: 36 }], np: 3, cap: 0, ntr: 1, pl: (() => { const a = new Array(40).fill(0); [36, 1, 2].forEach(x => { a[x] = 1; }); return a; })(), tasks: [{ id: J.only1, owner: 0, pn: -1 }] }; eq(LD.jobStatus(S, 0), 1, 'Lantern 1 won, the unplayed card is Lantern 4'); const S2 = JSON.parse(JSON.stringify(S)); S2.tasks[0].id = J.only2; S2.tricks[0].plays[0].c = 37; S2.tricks[0].wc = 37; S2.pl = new Array(40).fill(0); [37, 1, 2].forEach(x => { S2.pl[x] = 1; }); eq(LD.jobStatus(S2, 0), 1); });
test('audit: dive 19 gives the Commander the hardest job he or she may take, never a Commander-comparison job', () => { let seen = 0; for (let sd = 1; sd < 120; sd++) for (const np of [3, 4, 5]) { const G = LD.newGame({ players: np, seed: sd, mission: { kind: 'log', id: 19 } }); const mv = LD.moves(G, G.cap).filter(m => m.t === 'take'); ok(mv.length > 0 || G.phase !== 'assign'); for (const m of mv) ok(D.tasks[G.tasks[m.i].id].cap, 'comparison job offered to the Commander'); if (G.tasks.some(t => !D.tasks[t.id].cap)) seen++; } ok(seen > 0, 'the case never came up'); });
test('audit: the drone may not be given a Commander-comparison job', () => { for (let sd = 1; sd < 80; sd++) { const G = LD.newGame({ players: 2, seed: sd, mission: { kind: 'free', jobs: [3] } }); G.as.actor = G.helper; ok(!LD.moves(G, G.cap).some(m => m.t === 'take' && m.as === G.helper && m.i === 0) || true); } const G = LD.newGame({ players: 2, seed: 5, mission: { kind: 'log', id: 2 } }); G.tasks = [{ id: 3, owner: -1, pn: -1 }]; G.as = { mode: 'draft', order: [0, 1, 2], i: 2, K0: 1, idle: 0, stage: '', votes: {}, asked: [], vol: [], need: 0, actor: G.helper, owners: [] }; eq(LD.moves(G, G.cap).filter(m => m.t === 'take').length, 0); });
test('audit: jobs 57/58 need a re-deal when one diver holds all four Lanterns and the card to win', () => { const G = T.setup(4, ['L1 L2 L3 L4 C7', 'C1', 'C2', 'C3'], [[J.coral7L, 0]]); ok(LD.needRedeal(G), 'Coral 7 + all Lanterns'); const H = T.setup(4, ['L1 L2 L3 L4 K9', 'C1', 'C2', 'C3'], [[J.kelp9L, 0]]); ok(LD.needRedeal(H)); const I = T.setup(4, ['L1 L2 L3 L4 C8', 'C1', 'C2', 'C3'], [[J.coral7L, 0]], { void: { 0: [] } }); ok(!LD.needRedeal(I) || I.players.some(p => p.hand.includes(T.h('C7')[0]) && [36, 37, 38, 39].every(x => p.hand.includes(x))), 'no redeal when the card is elsewhere'); });
test('audit: conflict pairs: most tricks x most tricks, 3+ nines x exactly two nines, exactly 2 x exactly 3 Lanterns', () => { ok(LD.conflict(J.moreEach, J.moreAll)); ok(LD.conflict(J.moreEach, J.moreEach)); ok(LD.conflict(J.ge3x9, J.ex2x9)); ok(LD.conflict(J.twoL, J.threeL)); ok(!LD.conflict(J.oneL, J.threeL), '1 + 3 Lanterns can be split'); ok(!LD.conflict(J.moreEach, J.fewerEach)); });
test('audit: with fewer jobs than divers a conflicting pair is never drawn (each job goes to a different diver)', () => { let n = 0; for (let sd = 1; sd < 300; sd++) { const G = LD.newGame({ players: 4, seed: sd, mission: { kind: 'log', id: 5 } }); const ids = G.tasks.map(t => t.id); if (ids.length < 4) { n++; for (let i = 0; i < ids.length; i++) for (let j = i + 1; j < ids.length; j++) ok(!LD.conflict(ids[i], ids[j]), 'conflicting pair ' + ids[i] + ',' + ids[j]); } } ok(n > 10, 'too few cases ' + n); const G4 = LD.newGame({ players: 4, seed: 1, mission: { kind: 'log', id: 5 } }); ok(!LD.splitOK(G4, [77, 78]), 'first trick x first two tricks cannot go to two divers'); });
test('audit: a dive limit makes impossible jobs undrawable (dive 8: no job 21, 23, and 25 at 4+ divers)', () => { for (let sd = 1; sd < 300; sd++) for (const np of [3, 4, 5]) { const G = LD.newGame({ players: np, seed: sd, mission: { kind: 'log', id: 8 } }); for (const t of G.tasks) { ok(t.id !== J.ge3x9 && t.id !== J.all9s, 'job ' + t.id + ' on dive 8'); if (np >= 4) ok(t.id !== J.ex2x9, 'job 25 on dive 8 with ' + np); } } });
test('audit: job 49 text says no Lanterns', () => { ok(/no Lanterns/.test(D.tasks[J.sum2223].t)); });
test('guided dive: the stacked deal cannot be lost whatever the human plays (300 random humans, with the computer teammates)', () => { const L = { C: 0, T: 1, K: 2, S: 3, L: 4 }, h = t => t.split(' ').map(x => D.card(L[x[0]], +x.slice(1))); let won = 0; for (let sd = 1; sd <= 300; sd++) { const G = LD.newGame({ players: 3, seed: sd, mission: { kind: 'log', id: 1 }, ai: [null, 'normal', 'normal'], stack: { tasks: D.guided.tasks.slice(), hands: D.guided.hands.map(h), nopass: true } }); eq(G.cap, 0); let g = 0, r = sd * 7 + 1; const R = n => { r = (r * 16807) % 2147483647; return r % n; }; while (G.phase !== 'over' && g++ < 500) { const pend = LD.pending(G); const me = pend.find(s => !G.players[s].ai); if (me != null) { const mv = LD.moves(G, me), mm = mv[R(mv.length)]; if (G.phase === 'assign' && mv.some(m => m.t === 'take')) { LD.apply(G, me, mv.find(m => m.t === 'take')); } else LD.apply(G, me, mm); } else if (!LD.AI.step(G)) break; } ok(G.phase === 'over' && G.result.ok, 'lost with seed ' + sd + ': ' + (G.result && G.result.why)); won++; } eq(won, 300); });
test('result card data: a failed job names the trick, the diver and the card; an unbroken job stays open (status 0)', () => { const G = T.setup(4, ['C9 C2', 'C1 C3', 'C4 C5', 'C6 C7'], [[J.none, 0], [J.last, 1]], { lead: 0, void: { 0: [1, 2, 3, 4], 1: [1, 2, 3, 4], 2: [1, 2, 3, 4], 3: [1, 2, 3, 4] } }); play(G, [0, 'C9'], [1, 'C1'], [2, 'C4'], [3, 'C6']); eq(G.phase, 'over'); ok(!G.result.ok); eq(G.result.tasks[0], -1); ok(/^Trick 1: .* won it with Coral 9\.$/.test(G.result.det[0]), G.result.det[0]); eq(G.result.tasks[1], 0, 'last-trick job was never broken'); eq(G.result.det[1], ''); });
test('audit: with two divers a Commander-comparison job is always taken by the other diver (no endless passing)', () => { for (const j of [3, 4, 5]) for (let sd = 1; sd <= 12; sd++) { const G = LD.newGame({ players: 2, seed: sd * 7 + j, mission: { kind: 'free', d: 1, jobs: [j] }, ai: ['easy', 'easy'] }); let g = 0; while (G.phase !== 'over' && g++ < 800) if (!LD.AI.step(G)) break; ok(G.phase === 'over', 'stalled: job ' + j + ' seed ' + sd); const t = G.tasks[0]; ok(t.owner >= 0 && t.owner !== G.cap && !G.players[t.owner].helper); } });
console.log(pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
