#!/usr/bin/env python3
"""Placeholder art for Mainhattan Nightrun.
  python3 games-src/nightrun/make-placeholders.py
Reads assets-manifest.json. For every file listed there that does not exist yet in games/mainhattan-nightrun/media/ it writes a labelled placeholder WebP (never overwrites real art),
and it regenerates ASSETS-NEEDED.md. To replace a placeholder: save your real image under the same file name and size (see the table), run this script (it updates media/ready.json) and commit both.
To ask for a new asset: add an entry to assets-manifest.json and run this script."""
import json, os, glob
from PIL import Image, ImageDraw, ImageFont
HERE = os.path.dirname(os.path.abspath(__file__)); MEDIA = os.path.normpath(os.path.join(HERE, '..', '..', 'games', 'mainhattan-nightrun', 'media'))
M = json.load(open(os.path.join(HERE, 'assets-manifest.json')))
COL = {'Garage kit perks': (255, 90, 61), 'Garage SOON cards': (140, 134, 184), 'Stage medals': (255, 176, 32), 'Difficulty badges': (255, 45, 149), 'Boss chest reveal': (255, 225, 77), 'Enemies': (25, 227, 255),
       'Effects': (61, 255, 176), 'Planned ships': (192, 138, 255), 'Mini-bosses': (255, 64, 96), 'Portrait parallax': (91, 140, 255)}
def font(sz):
    for f in ('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', '/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf'):
        if os.path.exists(f): return ImageFont.truetype(f, sz)
    return ImageFont.load_default()
def make(e):
    w, h = e['w'], e['h']; c = COL.get(e['group'], (200, 200, 200)); fx = e['kind'] == 'fx'
    im = Image.new('RGBA', (w, h), (0, 0, 0, 255) if fx else (0, 0, 0, 0)); d = ImageDraw.Draw(im)
    d.rectangle([1, 1, w - 2, h - 2], fill=(20, 12, 38, 255) if not fx else (10, 10, 10, 255), outline=c + (255,), width=max(2, w // 64))
    for i in range(-h, w, max(12, w // 10)): d.line([(i, h), (i + h, 0)], fill=c + (40,), width=1)             # hatching: obviously not final
    base = e['file'].rsplit('.', 1)[0]; fs = max(9, min(w // 9, h // 5, 28))
    lines = ['PLACEHOLDER', base, '%dx%d' % (w, h)]
    y = h // 2 - int(fs * 1.7)
    for i, t in enumerate(lines):
        f = font(fs if i else int(fs * .9)); tw = d.textlength(t, font=f)
        while tw > w - 8 and f.size > 7: f = font(f.size - 1); tw = d.textlength(t, font=f)
        d.text(((w - tw) / 2, y), t, font=f, fill=(255, 255, 255, 255) if i == 1 else c + (255,)); y += int(f.size * 1.35)
    return im
import hashlib
md5 = lambda p: hashlib.md5(open(p, 'rb').read()).hexdigest()
SIG = os.path.join(MEDIA, 'placeholders.json'); sig = json.load(open(SIG)) if os.path.exists(SIG) else {}
made = 0
for e in M:
    p = os.path.join(MEDIA, e['file'])
    if not os.path.exists(p): make(e).save(p, 'WEBP', quality=80, method=6); sig[e['file']] = md5(p); made += 1
print('placeholders written:', made, '| total in manifest:', len(M))
# ready.json: the manifest files whose picture is real art (not the placeholder we wrote). The game draws these and uses its own vector shapes for the rest.
ready = sorted(e['file'] for e in M if os.path.exists(os.path.join(MEDIA, e['file'])) and md5(os.path.join(MEDIA, e['file'])) != sig.get(e['file']))
json.dump(sig, open(SIG, 'w'), indent=0); json.dump(ready, open(os.path.join(MEDIA, 'ready.json'), 'w'))
print('real art found for', len(ready), 'files:', ready)
# ----- the document -----
by = {}
for e in M: by.setdefault(e['group'], []).append(e)
out = ['# Nightrun: art and sound still needed', '', 'Generated by `make-placeholders.py` from `assets-manifest.json`. Every file below already exists as a labelled **placeholder** (hatched box with its name and size) in `games/mainhattan-nightrun/media/`.',
       '**To include real art:** save your image under the SAME file name and size into that folder, run `python3 games-src/nightrun/make-placeholders.py` (it detects real art and lists it in `media/ready.json`), then commit. Until a file is real art the game draws its own simple vector SHAPE for that item (never the placeholder picture), so everything already works; the real file replaces the shape automatically. Each item below says what the shape is.', '',
       'Style: the same painted look as the existing `spr-*`, `pk-*`, `fx-*`, `boss-*` files. WebP, transparent background for sprites and icons; **light on black** for `fx-*` (drawn additively). Sprites face LEFT (enemies, bosses) or RIGHT (player ships), as in `PAINTED-ART-HANDOFF.md`.', '']
st = {'WIRED': sum(e['status'] == 'WIRED' for e in M), 'RESERVED': sum(e['status'] == 'RESERVED' for e in M)}
out += ['**%d files:** %d WIRED (used now), %d RESERVED (for planned features).' % (len(M), st['WIRED'], st['RESERVED']), '']
for g, es in by.items():
    out += ['## ' + g, '', '| file | size | status | where it is used | what to paint |', '|---|---|---|---|---|']
    for e in es: out.append('| `%s` | %dx%d | %s | %s | %s |' % (e['file'], e['w'], e['h'], e['status'], e['where'], e['notes']))
    out.append('')
out += ['## Sound (no placeholder files yet)', '', 'Short effects, MP3 or OGG, about -16 LUFS, mono is fine, under 1 s unless noted. Save as `games/mainhattan-nightrun/sfx/<name>.mp3`. Today these are made by the built-in synth.', '',
       '| name | length | what it is for |', '|---|---|---|',
       '| `sfx-heartbeat` | 0.4 s | the soft thump on every beat at 1 hull (synth sine today) |', '| `sfx-equip` / `sfx-unequip` | 0.3 s | garage LOAD tab equip and unequip clicks |', '| `sfx-sell` | 0.5 s | coins dropping, selling a perk level |', '| `sfx-buy` | 0.4 s | buying in the garage or the daily shop |',
       '| `sfx-leader-warn` | 0.8 s | a squad leader is about to fire its fan (low brass stab) |', '| `sfx-leader-down` | 1.0 s | leader killed, squad panics |', '| `sfx-medal` | 1.5 s | medal on the stage clear screen |', '| `sfx-chest` | 2.0 s | boss chest reveal (planned feature) |', '',
       '## Music', '', 'Menu song for the garage/shop (2 min loop, calm, same -18 LUFS as the others, with `bpm` and `offsetMs` measured for `tracks.json`). Optional: a short stinger for LEGEND difficulty.', '']
open(os.path.join(HERE, 'ASSETS-NEEDED.md'), 'w').write('\n'.join(out))
print('ASSETS-NEEDED.md written')
