// per-child world bbox of the player in Athens with a set + upgrades bought by taps: node t/bbox.js <set> <ups e.g. 3333> [page]
const {chromium,devices}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const [id,u,page]=[process.argv[2]||'gold',process.argv[3]||'3333',process.argv[4]||'dev2/local_dbg.html'];const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const p=await (await b.newContext({...devices['iPhone 13'],viewport:{width:852,height:393},deviceScaleFactor:1})).newPage();p.setDefaultTimeout(600000);const errs=[];p.on('pageerror',e=>errs.push(e.message));
 await p.goto('http://127.0.0.1:8766/'+page);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu');
 await p.evaluate(()=>{localStorage.clear();localStorage.setItem('mho_slot','1');localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{}}');localStorage.setItem('mho_story.ath@1','{"seen":1}')});await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu');
 await p.evaluate(()=>__gar.cheat(99999,40));const ck=async s=>{await p.evaluate(s=>document.querySelector(s).click(),s);await p.waitForTimeout(300)};
 await ck('#gbMenuBtn');await p.waitForFunction(()=>!document.querySelector('#gbx').hidden);await p.waitForTimeout(800);await ck('#gbx .gbTabs [data-t="veh"]');await ck(`[data-gset="${id}"]`);
 for(const[i,k]of['sp','ex','wh','bo'].entries())for(let n=0;n<+u[i];n++)await ck(`[data-gup="${k}"]`);await p.evaluate(()=>[...document.querySelectorAll('#gbx button')].find(b=>/SAVE/.test(b.textContent)).click());await p.waitForTimeout(1500);
 await p.evaluate(()=>__mho.enterRoam());await p.waitForFunction(()=>__mho.state==='roam');await p.evaluate(()=>{__mho.storyClose&&__mho.storyClose();__mho.roamSim(10)});
 const r=await p.evaluate(()=>{const T=__dbg.THREE,m=__mho.pl.mesh,B=new T.Box3(),out=[];m.updateMatrixWorld(true);const walk=(o,path,d)=>{if(!o.visible)return;let bb=new T.Box3();o.traverseVisible(x=>{if(x.isMesh&&x.geometry&&!(x.material&&(x.material.transparent||x.material.blending===T.AdditiveBlending))){if(!x.geometry.boundingBox)x.geometry.computeBoundingBox();bb.union(x.geometry.boundingBox.clone().applyMatrix4(x.matrixWorld))}});if(bb.isEmpty())return;const s=bb.getSize(new T.Vector3());const mx=Math.max(s.x,s.y,s.z);if(mx>6||d<2)out.push({path,d,name:o.name,type:o.type,ud:Object.keys(o.userData||{}).slice(0,6).join(','),sz:[s.x,s.y,s.z].map(v=>+v.toFixed(1)),n:o.children.length});if(mx>6&&d<6)o.children.forEach((c,i)=>walk(c,path+'/'+i,d+1))};walk(m,'pl',0);return {sel:__gar.get().sel,ups:__gar.ups(),RO:{x:__mho.RO.x|0,z:__mho.RO.z|0},out:out.slice(0,40)}});
 console.log(JSON.stringify(r,null,0),'errs',JSON.stringify(errs));await b.close()})();
