// per-child world bbox of the player in Athens with a set + upgrades bought by taps: node t/bbox.js <set> <ups e.g. 3333> [page]
const {chromium,devices}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const [id,u,page]=[process.argv[2]||'gold',process.argv[3]||'3333',process.argv[4]||'dev2/local_dbg.html'];const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const p=await (await b.newContext({...devices['iPhone 13'],viewport:{width:852,height:393},deviceScaleFactor:1})).newPage();p.setDefaultTimeout(600000);const errs=[];p.on('pageerror',e=>errs.push(e.message));
 await p.goto('http://127.0.0.1:8766/'+page);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu');
 await p.evaluate(()=>{localStorage.clear();localStorage.setItem('mho_slot','1');localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{}}');localStorage.setItem('mho_story.ath@1','{"seen":1}')});await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu');
 await p.evaluate(()=>__gar.cheat(99999,40));const ck=async s=>{await p.evaluate(s=>document.querySelector(s).click(),s);await p.waitForTimeout(300)};
 await ck('#gbMenuBtn');await p.waitForFunction(()=>!document.querySelector('#gbx').hidden);await p.waitForTimeout(800);await ck('#gbx .gbTabs [data-t="veh"]');await ck(`[data-gset="${id}"]`);
 for(const[i,k]of['sp','ex','wh','bo'].entries())for(let n=0;n<+u[i];n++)await ck(`[data-gup="${k}"]`);await p.evaluate(()=>[...document.querySelectorAll('#gbx button')].find(b=>/SAVE/.test(b.textContent)).click());await p.waitForTimeout(1500);
 console.log('TRK',await p.evaluate(()=>JSON.stringify(__dbg.TRK)));const trk=process.env.TRK||await p.evaluate(()=>__dbg.TRK.find(t=>/akro|ath/i.test(t))||__dbg.TRK[0]);console.log('use',trk);await p.evaluate(t=>__dbg.RS(null,t),trk);await p.waitForFunction(()=>__dbg.ST!=='countdown',null,{timeout:60000}).catch(()=>{});await p.keyboard.down('ArrowUp');
 const S=()=>p.evaluate(()=>{const T=__dbg.THREE,m=__mho.pl.mesh;m.updateMatrixWorld(true);const bb=new T.Box3();let big=null;m.traverseVisible(x=>{if(x.isMesh&&x.geometry&&!(x.material&&(x.material.transparent||x.material.blending===T.AdditiveBlending))){if(!x.geometry.boundingBox)x.geometry.computeBoundingBox();const b=x.geometry.boundingBox.clone().applyMatrix4(x.matrixWorld);bb.union(b);const z=b.getSize(new T.Vector3());if(!big||z.length()>big.L){const ch=[];let q=x;while(q){ch.push([q.scale.x,q.scale.y,q.scale.z].map(v=>+v.toFixed(2)).join('/'));q=q.parent}big={L:z.length(),sz:z.toArray().map(v=>+v.toFixed(1)),ud:Object.keys(x.userData).join(','),gbb:[x.geometry.boundingBox.min.toArray(),x.geometry.boundingBox.max.toArray()].map(a=>a.map(v=>+v.toFixed(1))),sc:ch.join(' < ')}}}});const z=bb.getSize(new T.Vector3());return JSON.stringify({st:__dbg.ST,pos:m.position.toArray().map(v=>v|0),sz:z.toArray().map(v=>+v.toFixed(1)),big})});
 for(let k=0;k<+(process.env.N||12);k++){await p.waitForTimeout(3000);console.log('S'+k,await S())}
 await p.screenshot({path:'qa_rb_'+id+u+'.png'});await b.close();return;
await p.waitForTimeout(+(process.env.WAIT||8000));console.log('ST',await p.evaluate(()=>__dbg.ST));await p.screenshot({path:'qa_rb_'+id+u+'.png'});
 const r=await p.evaluate(()=>{const T=__dbg.THREE,m=__mho.pl.mesh,B=new T.Box3(),out=[];m.updateMatrixWorld(true);const walk=(o,path,d)=>{if(!o.visible)return;let bb=new T.Box3();o.traverseVisible(x=>{if(x.isMesh&&x.geometry&&!(x.material&&(x.material.transparent||x.material.blending===T.AdditiveBlending))){if(!x.geometry.boundingBox)x.geometry.computeBoundingBox();bb.union(x.geometry.boundingBox.clone().applyMatrix4(x.matrixWorld))}});if(bb.isEmpty())return;const s=bb.getSize(new T.Vector3());const mx=Math.max(s.x,s.y,s.z);if(mx>6||d<2)out.push({path,d,name:o.name,type:o.type,ud:Object.keys(o.userData||{}).slice(0,6).join(','),sz:[s.x,s.y,s.z].map(v=>+v.toFixed(1)),sc:[o.scale.x,o.scale.y,o.scale.z].map(v=>+v.toFixed(2)),gb:o.geometry?(o.geometry.computeBoundingBox(),[o.geometry.boundingBox.min.toArray(),o.geometry.boundingBox.max.toArray()].map(a=>a.map(v=>+v.toFixed(1)))):0,n:o.children.length});if(mx>6&&d<6)o.children.forEach((c,i)=>walk(c,path+'/'+i,d+1))};walk(m,'pl',0);return {sel:__gar.get().sel,ups:__gar.ups(),pos:m.position.toArray().map(v=>v|0),out:out.slice(0,40)}});
 console.log(JSON.stringify(r,null,0),'errs',JSON.stringify(errs));await b.close()})();
