// close-ups of other vehicles' drivers (rivals, player 4x4/boat): node t/rv.js <prefix>
const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const pre=process.argv[2]||'shots/RV';const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const ctx=await b.newContext({viewport:{width:852,height:393},deviceScaleFactor:1});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,200))});
 await p.goto('http://127.0.0.1:8766/'+(process.env.PG||'local_dbg.html'));await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:300000});
 await p.evaluate(()=>{localStorage.clear();localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))});await p.reload({timeout:600000});await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:300000});
 await p.evaluate(()=>__mho.enterRoam());await p.waitForFunction(()=>__mho.state==='roam',null,{timeout:300000});await p.evaluate(()=>{__mho.storyClose&&__mho.storyClose();window.__fastR=__dbg.composer.render;__dbg.composer.render=()=>{};__mho.roamSim(20);window.requestAnimationFrame=()=>0;document.querySelectorAll('body > div').forEach(d=>{if(!d.querySelector('canvas'))d.style.visibility='hidden'})});
 const L=process.argv.slice(3).length?process.argv.slice(3):['v_rossi:1','v_kaiser:1','off:0','boat:0'];
 for(const s of L){const [id,i]=s.split(':');await p.evaluate(([id,i])=>{const T=__dbg.THREE,pm=__mho.pl.mesh;pm.visible=false;if(window.__rvg)__dbg.scene.remove(window.__rvg);const PV={ufo:()=>{const u={sp:3,ex:3,wh:3,bo:3};const S=__gar.SETS.find(s=>s.id===(window.__rvS||'posei'));return __gar.grpA(__gar.apply(S.off().map(e=>({t:e[0],x:e[1],z:e[2],r:e[3]%4,c:e[4],y:e[5],m:0})),u,'off').map(b=>[b.t,b.x,b.z,b.r,b.c,b.y]),'u1')},ubo:()=>{const u={sp:3,ex:3,wh:3,bo:3};const S=__gar.SETS.find(s=>s.id===(window.__rvS||'posei'));return __gar.grpA(__gar.apply(S.boat().map(e=>({t:e[0],x:e[1],z:e[2],r:e[3]%4,c:e[4],y:e[5],m:0})),u,'boat').map(b=>[b.t,b.x,b.z,b.r,b.c,b.y]),'u2')},ucar:()=>{const u={sp:3,ex:3,wh:3,bo:3};const S=__gar.SETS.find(s=>s.id===(window.__rvS||'posei'));return __gar.grpA(__gar.apply(S.car().map(e=>({t:e[0],x:e[1],z:e[2],r:e[3]%4,c:e[4],y:e[5],m:0})),u,'car').map(b=>[b.t,b.x,b.z,b.r,b.c,b.y]),'u3')},gt1:()=>__gar.grpA(__gar.gt({}),'v1'),gt2:()=>__gar.grpA(__gar.gt({body:'#16121c',acc:'#f5c20c',wing:'#f5c20c',bubble:1,big:1}),'v2')};const g=PV[id]?PV[id]():__gar.grp(id,+i);const h=new T.Group();h.add(g);h.position.copy(pm.position);h.position.y+=id==='boat'?.3:0;h.rotation.y=pm.rotation.y;h.scale.setScalar(pm.userData.m?pm.userData.m.scale.x:1);__dbg.scene.add(h);window.__rvg=h;h.updateMatrixWorld(true);
  const B=new T.Box3().setFromObject(h),c=B.getCenter(new T.Vector3()),sz=B.getSize(new T.Vector3());const fw=new T.Vector3(0,0,-1).applyQuaternion(h.quaternion),rt=new T.Vector3(1,0,0).applyQuaternion(h.quaternion);
  const cam=__dbg.camera,d=Math.max(sz.x,sz.z)*.95;cam.position.copy(c).addScaledVector(fw,d*.8).addScaledVector(rt,-d*.75);cam.position.y=B.max.y+d*.15;cam.lookAt(c.x,(c.y+B.max.y)/2,c.z);cam.fov=40;cam.updateProjectionMatrix();window.__fastR.call(__dbg.composer)},[id,i]);
  await p.screenshot({path:`${pre}_${id}${i}.png`})}
 console.log('errs',JSON.stringify(errs));await b.close()})();
