// ---------- Event deck (73) and wreckage (3). Names are original; effects follow the real cards (ref = cards.json id). ----------
// op vocabulary: see OPDOC in engine.js. who: 'first' | 'all' | 'actor'
const EVENTS=[
{ref:'event-argument',k:'bicker',n:'Bickering',icon:'book',ev:[['noMix']],th:{n:'Make Peace',pw:2,diff:1,rw:[['morale',1],['det','actor',1]]},te:[['ldet','all',1]]},
{ref:'event-awful-weather',k:'grimskies',n:'Grim Skies',icon:'explore',ev:[['wx','rain']],th:{n:'Rig a Windbreak',pw:1,req:{res:{wood:1}},rw:[['det','actor',1]]},te:[['wx','snow']]},
{ref:'event-bad-feelings',k:'hunch',n:'Uneasy Hunch',icon:'book',ev:[['actTok','gather','reroll']],th:{n:'Shake It Off',pw:1,rw:[['det','actor',1]]},te:[['actTok','gather','adv'],['actTok','gather','reroll']]},
{ref:'event-bear',k:'bear',n:'Prowling Bear',icon:'book',ev:[['actTok','camp','black']],th:{n:'Dig a Pit Trap',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['morale',-1],['ldet','all',1]]},
{ref:'event-body-on-the-beach',k:'ashore',n:'Washed Ashore',icon:'book',ev:[['morale',-1]],th:{n:'Bury the Stranger',pw:1,req:{items:['shovel']},rw:[['det','actor',2]]},te:[['morale',-2]]},
{ref:'event-broken-tree',k:'snapped',n:'Snapped Trunk',icon:'build',ev:[['wound','all',1]],th:{n:'Haul It Away',pw:1,req:{items:['rope']},rw:[['det','actor',1],['res','wood',1]]},te:[['morale',-1]]},
{ref:'event-call-of-the-wild',k:'jungle',n:'Call of the Jungle',icon:'book',ev:[['beastStr']],th:{n:'Scare Them Off',pw:1,req:{weapon:2},rw:[['res','food',1]]},te:[['beastStr']]},
{ref:'event-catastrophe',k:'scatter',n:'Everything Scattered',icon:'build',ev:[['itemsAway']],th:{n:'Collect the Gear',pw:1,rw:[['det','actor',1]]},te:[['loseItem',1,1]]},
{ref:'event-chronic-tiredness',k:'weary',n:'Bone Weary',icon:'explore',ev:[['nightFood']],th:{n:'Take It Slow',pw:2,rw:[['det','actor',2]]},te:[['wound','all',1]]},
{ref:'event-cloudburst',k:'downpour',n:'Downpour',icon:'gather',ev:[['moveCamp']],th:{n:'Rebuild',pw:1,rw:[['restoreMove']]},te:[]},
{ref:'event-cold-rain',k:'chillrain',n:'Chill Rain',icon:'explore',ev:[['wx','rain']],th:{n:'Dig a Drain',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['wx','rain']]},
{ref:'event-council',k:'council',n:'Heated Council',icon:'book',ev:[['discardInv',3]],th:{n:'Settle the Plan',pw:1,rw:[['pickInv',1],['det','actor',1]]},te:[['discardInv',2]]},
{ref:'event-culled-area',k:'stripped',n:'Stripped Grounds',icon:'gather',ev:[['prod','nofood']],th:{n:'Track New Game',pw:1,req:{weapon:2},rw:[['res','food',2]]},te:[]},
{ref:'event-dangerous-night',k:'eyesdark',n:'Eyes in the Dark',icon:'book',ev:[['beastWaits']],th:{n:'Lure It Away',pw:1,req:{weapon:2},rw:[['beastWaitToHunt']]},te:[]},
{ref:'event-depression',k:'gloom',n:'Gloom',icon:'book',ev:[['discardInv',2],['ldet','all',1]],th:{n:'Share a Meal',pw:1,req:{res:{food:1}},rw:[['det','actor',2]]},te:[['morale',-1],['discardInv',2]]},
{ref:'event-despondency',k:'heartless',n:'Loss of Heart',icon:'book',ev:[['passFirst']],th:{n:'Rally',pw:1,req:{res:{food:1}},rw:[['det','actor',1]]},te:[['morale',-2]]},
{ref:'event-devastation',k:'trampled',n:'Trampled Groves',icon:'book',ev:[['exhaustAdj',2]],th:{n:'Replant',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['exhaustAdj',1]]},
{ref:'event-disaster',k:'campcollapse',n:'Collapse at Camp',icon:'gather',ev:[['roofOrPal',-1]],th:{n:'Shore It Up',pw:1,req:{res:{wood:1}},rw:[['roofOrPal',1,'shelter']]},te:[['halfRoofOrPal']]},
{ref:'event-drought',k:'dryriver',n:'Dry Riverbed',icon:'book',ev:[['coverTerr','river',1]],th:{n:'Dig for Water',pw:1,req:{items:['shovel']},rw:[['det','actor',1],['uncoverTerr','river']]},te:[['coverTerr','river',1]]},
{ref:'event-earthquake',k:'tremor',n:'Tremor',icon:'book',ev:[['inaccessAdj',1]],th:{n:'Clear the Rubble',pw:1,req:{items:['shovel']},rw:[['reaccess']]},te:[]},
{ref:'event-exhausting-night',k:'restless',n:'Restless Night',icon:'book',ev:[['actTok','build','reroll']],th:{n:'Sleep It Off',pw:1,rw:[['det','actor',1]]},te:[['morale',-2]]},
{ref:'event-fight-in-the-dark',k:'scuffle',n:'Scuffle at Night',icon:'book',ev:[['huntDiscard',1]],th:{n:'Stand Guard',pw:1,req:{weapon:2},rw:[['det','actor',1]]},te:[['wx','animals']]},
{ref:'event-fight',k:'tempers',n:'Tempers Flare',icon:'build',ev:[['wound','all',1]],th:{n:'Cool Down',pw:1,rw:[['det','actor',1]]},te:[['ldet','all',2]]},
{ref:'event-fire',k:'brushfire',n:'Brushfire',icon:'explore',ev:[['prod','nowood']],th:{n:'Firebreak',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['prod','nowood']]},
{ref:'event-flood',k:'flashflood',n:'Flash Flood',icon:'explore',ev:[['pick',[[['loseItem',1,0]],[['weapon',-1]],[['pal',-1]],[['wound','all',1]]],['lose an item','weapon -1','palisade -1','everyone 1 wound']]],th:{n:'Channel the Water',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['pal',-1]]},
{ref:'event-flying-surprise',k:'swoop',n:'Swooping Birds',icon:'build',ev:[['roofOrPal',-1]],th:{n:'Net the Nest',pw:1,req:{res:{wood:1}},rw:[['det','actor',1]]},te:[['roofOrPal',-1]]},
{ref:'event-foul-weather',k:'muddy',n:'Muddy Tracks',icon:'book',ev:[['actTok','gather','time']],th:{n:'Lay a Boardwalk',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['exhaustAdj',2]]},
{ref:'event-frost',k:'earlyfrost',n:'Early Frost',icon:'gather',ev:[['wx','snow']],th:{n:'Insulate',pw:1,req:{alt:[{res:{wood:1}},{res:{fur:1}}]},rw:[['det','actor',2]]},te:[['wx','snow']]},
{ref:'event-heavy-clouds',k:'heavyskies',n:'Heavy Skies',icon:'build',ev:[['wx','rain']],th:{n:'Hide Tarp',pw:1,req:{res:{fur:1}},rw:[['det','actor',1]]},te:[['wx','rain']]},
{ref:'event-heavy-rain-is-coming',k:'rainway',n:'Rain on the Way',icon:'gather',ev:[['wx','rain']],th:{n:'Dig Channels',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['wx','rain']]},
{ref:'event-heavy-rain',k:'pouring',n:'Pouring Rain',icon:'build',ev:[['wx','rain']],th:{n:'Patch the Roof',pw:1,req:{res:{wood:1}},rw:[['det','actor',1]]},te:[['wx','rain']]},
{ref:'event-high-water',k:'risingwater',n:'Rising Water',icon:'gather',ev:[['actTok','explore','adv']],th:{n:'Build a Levee',pw:2,req:{alt:[{items:['shovel']},{res:{wood:1}}]},rw:[['det','actor',2]]},te:[['loseAllRes'],['prod','skip']]},
{ref:'event-howling-from-the-woods',k:'howls',n:'Howls in the Trees',icon:'book',ev:[['huntStrongest3']],th:{n:'Torches',pw:1,req:{items:['fire']},rw:[['huntTopBottom'],['det','actor',1]]},te:[['huntFightTop']]},
{ref:'event-jaguar',k:'spotted',n:'Spotted Hunter',icon:'build',ev:[['wound','all',1]],th:{n:'Drive It Off',pw:1,req:{weapon:2},rw:[]},te:[['wound','all',1]]},
{ref:'event-landslide',k:'mudslide',n:'Mudslide',icon:'build',ev:[['moveCamp']],th:{n:'Clear the Path',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['prod','skip']]},
{ref:'event-loss-of-hope',k:'hopeless',n:'Hopeless',icon:'book',ev:[['onlyActs','first',['build','camp','rest']]],th:{n:'Find Hope',pw:1,rw:[['det','actor',1]]},te:[['morale',-2]]},
{ref:'event-memories-of-the-cruise',k:'voyage',n:'Memories of the Voyage',icon:'build',ev:[['morale',-1]],th:{n:'Tell Stories',pw:2,rw:[['det','actor',2],['morale',1]]},te:[['ldet','all',1]]},
{ref:'event-mess-in-the-camp',k:'messy',n:'Messy Camp',icon:'book',ev:[['actTok','camp','time']],th:{n:'Tidy Up',pw:1,rw:[['det','actor',1]]},te:[['ldet','all',1]]},
{ref:'event-mist',k:'mist',n:'Thick Mist',icon:'book',ev:[['actTok','explore','time']],th:{n:'Wait It Out',pw:1,rw:[['det','actor',1]]},te:[['actTok','explore','time'],['actTok','explore','adv']]},
{ref:'event-natural-dam-breaks',k:'burstdam',n:'Burst Dam',icon:'book',ev:[['prod','plusWoodNoFood'],['actTok','explore','adv']],th:{n:'Rebuild the Dam',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['loseItem',2,1]]},
{ref:'event-night-attack',k:'nightraid',n:'Night Raid',icon:'explore',ev:[['wound','all',1],['huntPeek']],th:{n:'Ambush',pw:1,req:{weapon:3},rw:[['huntLootTop']]},te:[['huntDiscard',1]]},
{ref:'event-night-howling',k:'howlnight',n:'Howling Night',icon:'book',ev:[['beastStr']],th:{n:'Keep Watch',pw:1,req:{weapon:2},rw:[['det','actor',1]]},te:[['pal',-1]]},
{ref:'event-otters',k:'otters',n:'Thieving Otters',icon:'book',ev:[['exhaustClosest','fish']],th:{n:'Chase the Otters',pw:1,req:{weapon:1},rw:[['unexhaust','fish']]},te:[['again']]},
{ref:'event-poisoning',k:'badwater',n:'Bad Water',icon:'book',ev:[['wound','all',1]],th:{n:'Boil the Water',pw:1,req:{items:['knife']},rw:[['det','actor',1],['weapon',1]]},te:[['wound','all',1]]},
{ref:'event-precipice',k:'cliff',n:'Cliff Fall',icon:'explore',ev:[['inaccessAdj',1]],th:{n:'Build a Bridge',pw:1,req:{res:{wood:2}},rw:[['reaccess'],['det','actor',3]]},te:[]},
{ref:'event-predator-in-the-vicinity',k:'stalks',n:'Something Stalks',icon:'explore',ev:[['wx','animals']],th:{n:'Set Snares',pw:1,req:{weapon:2},rw:[['det','actor',1]]},te:[['wx','animals']]},
{ref:'event-predator-is-near',k:'hawk',n:'Hawk Overhead',icon:'book',ev:[['exhaustClosest','parrot']],th:{n:'Scare the Hawk',pw:1,req:{weapon:2},rw:[['unexhaust','parrot'],['det','actor',1]]},te:[['actTok','explore','adv'],['actTok','gather','adv']]},
{ref:'event-predators-in-the-woods',k:'nearby',n:'Predators Nearby',icon:'explore',ev:[['actTok','explore','beast']],th:{n:'Clear the Woods',pw:1,req:{weapon:1},rw:[['det','actor',1],['actTokOff','explore','beast']]},te:[['wound','all',1],['actTokOff','explore','beast']]},
{ref:'event-predators',k:'pack',n:'Pack Hunters',icon:'explore',ev:[['exhaustClosest','foodsrc']],th:{n:'Fight the Pack',pw:2,req:{weapon:2},rw:[['unexhaust','foodsrc'],['det','actor',1]]},te:[['again']]},
{ref:'event-raging-river',k:'swollen',n:'Swollen River',icon:'gather',ev:[['prod','half']],th:{n:'Dig a Bypass',pw:1,req:{items:['shovel']},rw:[['det','actor',1]]},te:[['prod','skip']]},
{ref:'event-rain',k:'drizzle',n:'Drizzle',icon:'gather',ev:[['wx','rain']],th:{n:'Hide Cover',pw:1,req:{res:{fur:1}},rw:[['det','actor',1]]},te:[['wx','rain']]},
{ref:'event-ravenous-predators',k:'starving',n:'Starving Beasts',icon:'book',ev:[['beastStr']],th:{n:'Ring of Fire',pw:1,req:{items:['fire']},rw:[['det','actor',1]]},te:[['pal',-1]]},
{ref:'event-ravishing-hurricane',k:'hurricane',n:'Hurricane Winds',icon:'book',ev:[['exhaustTileAdj']],th:{n:'Clear the Debris',pw:1,req:{items:['shovel']},rw:[['unexhaustTile'],['det','actor',1]]},te:[]},
{ref:'event-ravishing-windstorm',k:'gale',n:'Gale',icon:'explore',ev:[['weapon',-2,1]],th:{n:'Salvage Weapons',pw:1,rw:[['weapon',1],['det','actor',1]]},te:[]},
{ref:'event-rough-passage',k:'rockfall',n:'Rockfall',icon:'book',ev:[['coverTerr','hills',1]],th:{n:'Clear the Pass',pw:1,rw:[['det','actor',1],['uncoverTerr','hills']]},te:[['coverTerr','hills',1]]},
{ref:'event-searching-for-a-new-path',k:'losttrail',n:'Lost Trail',icon:'book',ev:[['actTok','explore','reroll']],th:{n:'Mark the Trail',pw:1,rw:[['det','actor',1]]},te:[['actTok','explore','adv'],['actTok','gather','adv']]},
{ref:'event-sleepless-night',k:'sleepless',n:'Sleepless Hours',icon:'book',ev:[['actTok','build','reroll'],['actTok','gather','reroll'],['actTok','explore','reroll']],th:{n:'Nap',pw:1,rw:[['det','actor',1]]},te:[['actTok','explore','adv'],['actTok','gather','adv']]},
{ref:'event-slow-work',k:'sluggish',n:'Sluggish Work',icon:'book',ev:[['actTok','build','wood']],th:{n:'Sharpen Tools',pw:1,rw:[['det','actor',1]]},te:[['actTok','build','wood']]},
{ref:'event-smoke-on-the-horizon',k:'smoke',n:'Smoke in the Distance',icon:'book',ev:[['coverTerr','plains',1]],th:{n:'Investigate',pw:1,rw:[['det','actor',1],['uncoverTerr','plains']]},te:[['coverTerr','plains',1]]},
{ref:'event-storm-damage',k:'battered',n:'Battered Camp',icon:'gather',ev:[['halfRoofOrPal']],th:{n:'Mend the Camp',pw:1,req:{res:{wood:1}},rw:[['roofOrPal',1,'shelter']]},te:[['roofOrPal',-1]]},
{ref:'event-storm',k:'squall',n:'Squall',cp:2,icon:'gather',ev:[['wx','storm']],th:{n:'Batten Down',pw:1,req:{alt:[{items:['shovel']},{res:{wood:1}}]},rw:[['det','actor',1]]},te:[['pal',-1]]},
{ref:'event-stroke-of-fate',k:'twist',n:'Twist of Fate',icon:'gather',ev:[['flushThreats']],th:{n:'Accept It',pw:1,rw:[['det','actor',3]]},te:[['ldet','all',1]]},
{ref:'event-strong-wind',k:'howlwind',n:'Howling Wind',icon:'book',ev:[['actTok','build','time']],th:{n:'Tie Everything Down',pw:1,rw:[['det','actor',1]]},te:[['loseItem',1,1]]},
{ref:'event-sunny-beach',k:'sunny',n:'Sunny Shore',icon:'explore',ev:[],th:{n:'Enjoy the Sun',pw:2,rw:[['det','all',1]]},te:[['ldet','all',1]]},
{ref:'event-termites',k:'borers',n:'Wood Borers',icon:'book',ev:[['lose','wood',1,1]],th:{n:'Smoke Them Out',pw:1,req:{items:['fire']},rw:[['det','actor',1]]},te:[['lose','wood',1,1]]},
{ref:'event-the-island-fights-back',k:'strikes',n:'The Island Strikes',icon:'book',ev:[['book']],th:{n:'Hold Firm',pw:1,rw:[['det','actor',1]]},te:[['book']]},
{ref:'event-thunderstorm',k:'lightning',n:'Lightning Strike',icon:'gather',ev:[['exhaustClosest','wood']],th:{n:'Clear the Burnt Trees',pw:1,req:{items:['shovel']},rw:[['unexhaust','wood']]},te:[['again']]},
{ref:'event-unusually-cold-night',k:'bitter',n:'Bitter Night',icon:'book',ev:[['pick',[[['lose','wood',2]],[['wound','all',1]]],['discard 2 wood','everyone 1 wound']]],th:{n:'Stockpile Fuel',pw:1,req:{alt:[{res:{wood:1}},{res:{fur:1}}]},rw:[['det','actor',1]]},te:[['wound','all',1]]},
{ref:'event-vertigo',k:'dizzy',n:'Dizzy Spell',icon:'book',ev:[['pawnMinus','first']],th:{n:'Rest a While',pw:1,rw:[['det','actor',1]]},te:[['ldet','all',1]]},
{ref:'event-weakness',k:'feeble',n:'Feeble',icon:'book',ev:[['noSkills','first']],th:{n:'Build Strength',pw:1,rw:[['det','actor',1]]},te:[['noSkills','first']]},
{ref:'event-winter-depression',k:'winterblues',n:'Winter Blues',icon:'book',ev:[['morale',-1]],th:{n:'Warm Supper',pw:1,req:{res:{food:1}},rw:[['det','actor',1]]},te:[['ldet','all',1]]},
{ref:'event-wrecked-balloon',k:'balloon',n:'Fallen Balloon',icon:'book',ev:[['morale',-1]],th:{n:'Search the Basket',pw:1,rw:[['mystery',{treasure:1,until:1}]]},te:[]}
];
const WRECKS=[
{ref:'event-food-crates',k:'crates',n:'Crates on the Tide',icon:'wreck',ev:[],th:{n:'Wade Out for the Crates',pw:'1-2',rw1:[['res','food',1]],rw2:[['res','food',1],['res','pfood',1]]},te:[]},
{ref:'event-captain-s-chest',k:'seachest',n:'Floating Sea Chest',icon:'wreck',ev:[],th:{n:'Swim for the Chest',pw:'1-2',rw1:[['res','wood',1]],rw2:[['res','wood',1],['startItem']]},te:[]},
{ref:'event-wrecked-lifeboat',k:'dinghy',n:'Smashed Dinghy',icon:'wreck',ev:[],th:{n:'Salvage the Dinghy',pw:'1-2',rw1:[['res','wood',1]],rw2:[['res','wood',2]]},te:[]}
];
