// ---------- Adventure decks: build, gather, explore (30 each) and the Mystery deck (52). Original names; real effects. ----------
// ops run for the acting character; 'decide' = [discard option, keep option (keep = shuffle into the Event deck)]; ev = the card's event half
const ADVENTURES=[
// ----- build (30) -----
{ref:'adv-build-accident',k:'b_slip',n:'Slipped Hammer',deck:'build',ops:[['spWound','leg']],shuffle:1,ev:{n:'Festering Leg',ops:[['spw','leg',[['ifItem','medicine',[['wound','sp',1]],[['wound','sp',3]]]]]]}},
{ref:'adv-build-breakdown',k:'b_breakdown',n:'Low Moment',deck:'build',ops:[['morale',-1]],shuffle:1,ev:{n:'Second Wind',ops:[['det','first',2]]}},
{ref:'adv-build-broken-lever',k:'b_lever',n:'Cracked Lever',deck:'build',ops:[['weapon',-1]]},
{ref:'adv-build-broken-tool',k:'b_tool',n:'Broken Tool',deck:'build',ops:[['loseItem',1,1]]},
{ref:'adv-build-coming-to-terms',k:'b_terms',n:'Giving Up Plans',deck:'build',ops:[['discardInv',3]],shuffle:1,ev:{n:'Out of Ideas',ops:[['morale',-1]]}},
{ref:'adv-build-construction',k:'b_construct',n:'Solid Joints',deck:'build',ops:[],shuffle:1,ev:{n:'Sturdier Walls',ops:[['pal',1,'shelter']]}},
{ref:'adv-build-cut-head',k:'b_cuthead',n:'Knock on the Head',deck:'build',ops:[['wound','actor',1],['det','actor',2],['spWound','head']],shuffle:1,ev:{n:'Pounding Headache',ops:[['spw','head',[['ifItem','medicine',[],[['wound','sp',2]]]]]]}},
{ref:'adv-build-dangerous-work',k:'b_dangerous',n:'Risky Work',deck:'build',ops:[['actTok','build','reroll'],['actTok','build','adv']]},
{ref:'adv-build-dark-clouds-in-the-sky',k:'b_darkclouds',n:'Darkening Sky',deck:'build',ops:[['wx','rain']],shuffle:1,ev:{n:'After the Shower',ops:[['pal',1,'shelter']]}},
{ref:'adv-build-fast-work',k:'b_fast',n:'Quick Hands',deck:'build',decide:[[],[['extraBuild']]],ev:{n:'More Haste, Less Speed',ops:[['roofOrPal',-1]]}},
{ref:'adv-build-fear-of-the-beasts',k:'b_fear',n:'Fear of Beasts',deck:'build',ops:[],shuffle:1,ev:{n:'Heavier Weapons',ops:[['costTok','weapon']]}},
{ref:'adv-build-hard-work',k:'b_hard',n:'Back-Breaking Work',deck:'build',ops:[['lose','food',1,1]]},
{ref:'adv-build-howling-in-the-bushes',k:'b_howl',n:'Rustling Bushes',deck:'build',ops:[],shuffle:1,ev:{n:'It Pounces!',ops:[['fight',{str:3,wl:1,food:2,fur:1,pal:1},'first']]}},
{ref:'adv-build-hungry-predator',k:'b_hungry',n:'Hungry Visitor',deck:'build',decide:[[['wound','actor',2],['res','food',2],['res','fur',1]],[['lose','food',1],['pal',-1]]],ev:{n:'It Returns',ops:[['fight',{str:3,wl:0,food:1,fur:1,pal:1},'first']]}},
{ref:'adv-build-in-a-hurry',k:'b_hurry',n:'In a Rush',deck:'build',decide:[[],[['disc',2]]],ev:{n:'A Crack Appears',ops:[['pal',-1]]}},
{ref:'adv-build-laborious-work',k:'b_laborious',n:'Slow Going',deck:'build',cp:2,ops:[['actTok','build','time']]},
{ref:'adv-build-lack-of-hope',k:'b_nohope',n:'Dashed Hopes',deck:'build',ops:[['discardInv',3]]},
{ref:'adv-build-monkey-see',k:'b_monkey',n:'Curious Monkeys',deck:'build',ops:[],shuffle:1,ev:{n:'Monkey Business',ops:[['halfRoofOrPal']]}},
{ref:'adv-build-nasty-wound',k:'b_nasty',n:'Deep Gash',deck:'build',ops:[['spWound','arm']],shuffle:1,ev:{n:'Infected Gash',ops:[['spw','arm',[['ifItem','medicine',[],[['wound','sp',2]]]]]]}},
{ref:'adv-build-predator-in-the-camp',k:'b_campbeast',n:'Beast in the Camp',deck:'build',ops:[['fight',{str:4},'actor']],shuffle:1,ev:{n:'Fair Trade',ops:[['res','food',2],['res','fur',2]]}},
{ref:'adv-build-savings',k:'b_savings',n:'Spare Timber',deck:'build',decide:[[],[['res','wood',2]]],ev:{n:'Wobbly Build',ops:[['morale',-1]]}},
{ref:'adv-build-sting',k:'b_sting',n:'Wasp Sting',deck:'build',ops:[['spWound','belly']],shuffle:1,ev:{n:'The Shakes',ops:[['spw','belly',[['ifItem','medicine',[],[['pawnMinus','sp']]]]]]}},
{ref:'adv-build-tired',k:'b_tired',n:'Worn Out',deck:'build',decide:[[],[['heal','actor',2]]],ev:{n:'Squabble',ops:[['morale',-1]]}},
{ref:'adv-build-tools-inspection',k:'b_inspect',n:'Checking the Tools',deck:'build',ops:[['markItems',2]],shuffle:1,ev:{n:'Tools Give Out',ops:[['loseMarked']]}},
{ref:'adv-build-unmotivated',k:'b_unmotivated',n:'No Energy',deck:'build',ops:[['pick',[[['ldet','actor',1]],[['wound','actor',1]]],['discard 1 determination','take 1 wound']]],shuffle:1,ev:{n:'Worn Tools',ops:[['ldet','all',1]]}},
{ref:'adv-build-visit-of-a-predator',k:'b_visit',n:'Nosy Predator',deck:'build',ops:[['lose','food',1]],shuffle:1,ev:{n:'Night Prowler',ops:[['wx','animals']]}},
{ref:'adv-build-weak-construction',k:'b_weak',n:'Shaky Frame',deck:'build',ops:[],shuffle:1,ev:{n:'Crash!',ops:[['halfRoof']]}},
{ref:'adv-build-windstorm',k:'b_wind',n:'Gusts',deck:'build',ops:[['pal',-1]],shuffle:1,ev:{n:'Windbreak Hedge',ops:[['pal',1,'shelter']]}},
{ref:'adv-build-you-need-a-bigger-camp',k:'b_bigger',n:'Cramped Camp',deck:'build',ops:[],shuffle:1,ev:{n:'Bigger Camp',ops:[['costTok','shelter'],['costTok','roof'],['costTok','pal']]}},
// ----- gather (30) -----
{ref:'adv-gather-after-the-hurricane',k:'g_hurricane',n:'Storm Debris',deck:'gather',ops:[['res','wood',2],['tileTok','time']],shuffle:1,ev:{n:'Washed Away',ops:[['inaccessTok','time']]}},
{ref:'adv-gather-end-of-source',k:'g_end',n:'Picked Clean',deck:'gather',cp:5,ops:[['exhaustHere']]},
{ref:'adv-gather-eyes-in-the-bushes',k:'g_eyes',n:'Eyes in the Leaves',deck:'gather',ops:[],shuffle:1,ev:{n:'Uninvited Guest',ops:[['wx','animals']]}},
{ref:'adv-gather-fruit',k:'g_fruit',n:'Strange Fruit',deck:'gather',ops:[['spWound','belly']],shuffle:1,ev:{n:'Bellyache',ops:[['spw','belly',[['ifItem','medicine',[],[['onlyActs','sp',['rest']]]]]]]}},
{ref:'adv-gather-furs',k:'g_furs',n:'Pelts in a Hollow',deck:'gather',decide:[[],[['res','fur',2]]],ev:{n:'Biting Insects',ops:[['prod','minusFood']]}},
{ref:'adv-gather-gold-coin',k:'g_coin',n:'Old Coin',deck:'gather',ops:[],shuffle:1,ev:{n:'Cursed Coin',ops:[['actTok','build','reroll'],['actTok','gather','reroll'],['actTok','explore','reroll']]}},
{ref:'adv-gather-mushrooms',k:'g_mushroom',n:'Mushroom Patch',deck:'gather',decide:[[],[['resPer','food']]],ev:{n:'Queasy',ops:[['ifItem','medicine',[],[['wound','all',1]]]]}},
{ref:'adv-gather-nestlings',k:'g_nest',n:'Nest of Eggs',deck:'gather',decide:[[],[['resPer','food']]],ev:{n:'Angry Mother Bird',ops:[['roof',-1]]}},
{ref:'adv-gather-new-flock',k:'g_flock',n:'New Flock',deck:'gather',ops:[['tileTok','food']],shuffle:1,ev:{n:'Flock Moves On',ops:[['exhaustTok','food']]}},
{ref:'adv-gather-nice-surprise',k:'g_surprise',n:'Driftwood Pile',deck:'gather',decide:[[],[['res','wood',3]]],ev:{n:'Sagging Roof',ops:[['halfRoof']]}},
{ref:'adv-gather-path-of-a-predator',k:'g_path',n:'Fresh Prints',deck:'gather',ops:[],shuffle:1,ev:{n:'Ambushed!',ops:[['wx','animals']]}},
{ref:'adv-gather-pirate-s-chest',k:'g_chest',n:'Buried Chest',deck:'gather',decide:[[],[['mystery',{treasure:2,draw:2}]]],ev:{n:'Unlucky Day',ops:[['pawnMinus','all']]}},
{ref:'adv-gather-shortage',k:'g_shortage',n:'Last of It',deck:'gather',ops:[['gatherExtra'],['exhaustHere']]},
{ref:'adv-gather-signs-of-a-predator',k:'g_signs',n:'Claw Marks',deck:'gather',ops:[],shuffle:1,ev:{n:'Predator Strikes',ops:[['ifWeapon',3,[],[['exhaustCampFood']]]]}},
{ref:'adv-gather-skeleton',k:'g_skeleton',n:'Old Bones',deck:'gather',ops:[],shuffle:1,ev:{n:"A Dead Man's Notes",ops:[['morale',-1],['drawInv',1]]}},
{ref:'adv-gather-spider',k:'g_spider',n:'Hairy Spider',deck:'gather',ops:[['spWound','head']],shuffle:1,ev:{n:'Neck Bite',ops:[['spw','head',[['pawnMinus','sp']]]]}},
{ref:'adv-gather-surprise-in-the-bushes',k:'g_bushes',n:'Something in the Brush',deck:'gather',decide:[[],[['startItem']]],ev:{n:'Brooding',ops:[['morale',-1]]}},
{ref:'adv-gather-tracks-of-a-predator',k:'g_tracks',n:'Big Paw Prints',deck:'gather',ops:[['tileTok','beast']]},
{ref:'adv-gather-twisted-ankle',k:'g_ankle',n:'Turned Ankle',deck:'gather',ops:[['spWound','leg']],shuffle:1,ev:{n:'Swollen Ankle',ops:[['spw','leg',[['onlyActs','sp',['camp','build','rest']]]]]}},
{ref:'adv-gather-unbelievable-effort',k:'g_effort',n:'Heroic Effort',deck:'gather',decide:[[],[['res','wood',2],['spWound','arm']]],ev:{n:'Aching Arms',ops:[['spw','arm',[['wound','sp',1]]]]}},
{ref:'adv-gather-unexpected-discovery',k:'g_find',n:'Lucky Find',deck:'gather',ops:[['disc',1]]},
{ref:'adv-gather-unexpected-troubles',k:'g_trouble',n:'Treacherous Ground',deck:'gather',ops:[['coverTerrHere']]},
{ref:'adv-gather-viper',k:'g_viper',n:'Adder in the Grass',deck:'gather',ops:[],shuffle:1,ev:{n:'Bitten',ops:[['ifItem','medicine',[['wound','first',1]],[['wound','first',3]]]]}},
{ref:'adv-gather-weather-breakdown',k:'g_weather',n:'Weather Turns',deck:'gather',ops:[],shuffle:1,ev:{n:'Storm',ops:[['wx','storm']]}},
{ref:'adv-gather-winter-freezing',k:'g_freeze',n:'Frozen Ground',deck:'gather',ops:[['exhaustHere']]},
{ref:'adv-gather-winter-is-coming',k:'g_winter',n:'Winter Draws Near',deck:'gather',ops:[],shuffle:1,ev:{n:'Ground Frost',ops:[['wx','snow']]}},
// ----- explore (30) -----
{ref:'adv-explore-bamboo',k:'e_bamboo',n:'Bamboo Grove',deck:'explore',decide:[[],[['res','wood',2]]],ev:{n:'Snapping Canes',ops:[['roofOrPal',-1]]}},
{ref:'adv-explore-carcass',k:'e_carcass',n:'Fresh Carcass',deck:'explore',decide:[[],[['res','food',2],['res','fur',2]]],ev:{n:'Bad Meat',ops:[['wound','all',1]]}},
{ref:'adv-explore-cold-wind',k:'e_coldwind',n:'Icy Breeze',deck:'explore',ops:[],shuffle:1,ev:{n:'Snowfall',ops:[['wx','snow']]}},
{ref:'adv-explore-dangerous-terrain',k:'e_danger',n:'Dangerous Ground',deck:'explore',ops:[['tileTok','beast']]},
{ref:'adv-explore-empty-forest',k:'e_empty',n:'Silent Forest',deck:'explore',ops:[],shuffle:1,ev:{n:'Hungry Predators',ops:[['beastStr']]}},
{ref:'adv-explore-flu',k:'e_flu',n:'Chills',deck:'explore',decide:[[['lose','food',1]],[]],ev:{n:'Sore Throat',ops:[['nightFood']]}},
{ref:'adv-explore-it-s-going-to-rain',k:'e_rain',n:'Rain Clouds Gather',deck:'explore',ops:[],shuffle:1,ev:{n:'Heavy Rain',ops:[['wx','rain']]}},
{ref:'adv-explore-lost-in-the-thicket',k:'e_thicket',n:'Lost in the Thicket',deck:'explore',ops:[['nightOut',[['disc',1]]]]},
{ref:'adv-explore-lost-in-the-woods',k:'e_woods',n:'Wandering in Circles',deck:'explore',ops:[['ldet','actor',2]]},
{ref:'adv-explore-lost',k:'e_lost',n:'Lost!',deck:'explore',ops:[['nightOut',[['morale',1]]]]},
{ref:'adv-explore-misadventure',k:'e_misstep',n:'Misstep',deck:'explore',ops:[['spWound','leg']],shuffle:1,ev:{n:'Swollen Ankle',ops:[['spw','leg',[['onlyActs','sp',['rest','camp','build']]]]]}},
{ref:'adv-explore-old-grave',k:'e_grave',n:'Old Grave',deck:'explore',ops:[['ldet','actor',1]],shuffle:1,ev:{n:'Ghost of a Castaway',ops:[['ldet','first',2]]}},
{ref:'adv-explore-old-hut',k:'e_oldhut',n:'Abandoned Hut',deck:'explore',decide:[[],[['mystery',{creature:1,treasure:1,draw:2}]]],ev:{n:"The Hermit's Ghost",ops:[['ldet','all',1]]}},
{ref:'adv-explore-puma',k:'e_puma',n:'Big Cat Tracks',deck:'explore',decide:[[['nightOut',[]]],[]],ev:{n:'The Big Cat Attacks!',ops:[['fight',{str:3,wl:1,food:2,fur:1,pal:1},'first']]}},
{ref:'adv-explore-remains-of-a-settlement',k:'e_settle',n:'Old Settlement',deck:'explore',decide:[[],[['mystery',{trap:1,treasure:2,draw:3}]]],ev:{n:'Sickness',ops:[['wound','all',1]]}},
{ref:'adv-explore-ruined-hut',k:'e_ruinhut',n:'Tumbledown Shack',deck:'explore',decide:[[],[['buildFree',['knife','rope','shovel','medicine']]]],ev:{n:'Nightmares',ops:[['morale',-1]]}},
{ref:'adv-explore-secret-cave',k:'e_cave',n:'Hidden Cave',deck:'explore',decide:[[],[['mystery',{monOrTrap:1,treasure:2,draw:3}]]],ev:{n:'The Beast Wakes',ops:[['fight',{str:3,wl:0,food:2,fur:1,pal:1},'first']]}},
{ref:'adv-explore-shrine',k:'e_shrine',n:'Jungle Shrine',deck:'explore',decide:[[],[['mystery',{treasure:1,draw:1}]]],ev:{n:'Bad Dreams',ops:[['actTok','build','reroll'],['actTok','gather','reroll'],['actTok','explore','reroll']]}},
{ref:'adv-explore-signs-of-fire',k:'e_fire',n:'Scorched Earth',deck:'explore',cp:2,ops:[['exhaustHereAny']]},
{ref:'adv-explore-storm-on-the-horizon',k:'e_storm',n:'Storm on the Horizon',deck:'explore',ops:[],shuffle:1,ev:{n:'Storm',ops:[['wx','storm']]}},
{ref:'adv-explore-surprising-discovery',k:'e_surprise',n:'Hidden Blade',deck:'explore',ops:[['keep','e_surprise']]},
{ref:'adv-explore-swamp',k:'e_swamp',n:'Bog',deck:'explore',ops:[['tileTok','time']]},
{ref:'adv-explore-there-s-something-in-the-air',k:'e_air',n:'Something in the Air',deck:'explore',ops:[['actTok','explore','adv']],shuffle:1,ev:{n:'The Island Is Cursed',ops:[['actTok','explore','adv']]}},
{ref:'adv-explore-thorny-bush',k:'e_thorn',n:'Thorn Thicket',deck:'explore',ops:[['spWound','arm']],shuffle:1,ev:{n:'Swollen Arm',ops:[['spw','arm',[['ifItem','medicine',[],[['pawnMinus','sp']]]]]]}},
{ref:'adv-explore-tiger',k:'e_tiger',n:'Striped Shadow',deck:'explore',decide:[[['nightOut',[]]],[]],ev:{n:'The Striped Cat Finds You!',ops:[['fight',{str:4,wl:1,food:2,fur:1,pal:1},'first']]}},
{ref:'adv-explore-vipers',k:'e_vipers',n:'Snake Nest',deck:'explore',ops:[['spWound','head']],shuffle:1,ev:{n:'Fever',ops:[['spw','head',[['ifItem','medicine',[],[['pawnMinus','sp']]]]]]}},
{ref:'adv-explore-wild-berries',k:'e_berries',n:'Wild Berries',deck:'explore',ops:[['spWound','belly']],shuffle:1,ev:{n:'Nausea',ops:[['spw','belly',[['pawnMinus','sp']]]]}},
{ref:'adv-explore-wild-dog',k:'e_dog',n:'Stray Dog',deck:'explore',ops:[['wound','actor',1]],shuffle:1,ev:{n:'The Dog Comes Back',ops:[['pick',[[['lose','food',1],['weapon',1]],[]],['feed it (1 food, weapon +1)','send it away']]]}},
{ref:'adv-explore-wrong-track',k:'e_wrong',n:'Wrong Turn',deck:'explore',ops:[['nightOut',[['res','wood',2]]]]}
];
const MYSTERIES=[
// ----- treasures (25) -----
{ref:'mystery-treasure-amulet-with-a-portrait-of-a-beautiful-lady',k:'m_locket',n:'Locket with a Portrait',type:'treasure',ops:[['coverArrows',2]]},
{ref:'mystery-treasure-antique-rapier',k:'m_rapier',n:'Old Duelling Sword',type:'treasure',ops:[['weapon',2]]},
{ref:'mystery-treasure-backpack',k:'m_backpack',n:'Canvas Backpack',type:'treasure',keep:1},
{ref:'mystery-treasure-barrel',k:'m_barrel',n:'Water Cask',type:'treasure',keep:1},
{ref:'mystery-treasure-blankets',k:'m_blankets',n:'Wool Blankets',type:'treasure',keep:1,uses:3},
{ref:'mystery-treasure-bottle-of-wine',k:'m_wine',n:'Bottle of Brandy',type:'treasure',keep:1,uses:1},
{ref:'mystery-treasure-boxes',k:'m_boxes',n:'Sealed Tins',type:'treasure',keep:1},
{ref:'mystery-treasure-captain-stone-s-spyglass',k:'m_spyglass',n:"Navigator's Spyglass",type:'treasure',ops:[['peekTiles',3]]},
{ref:'mystery-treasure-cave-with-furs',k:'m_furcave',n:'Cave of Pelts',type:'treasure',ops:[['res','fur',2]]},
{ref:'mystery-treasure-ceremonial-bowl',k:'m_bowl',n:'Ritual Bowl',type:'treasure',ops:[['charReroll','actor']],shuffle:1,ev:{n:'Lifting the Curse',ops:[['charRerollOff']]}},
{ref:'mystery-treasure-compass',k:'m_compass',n:'Brass Compass',type:'treasure',ops:[['keepPawn','explore']]},
{ref:'mystery-treasure-crocks',k:'m_crocks',n:'Clay Jars',type:'treasure',ops:[['buildFree',['pot']]]},
{ref:'mystery-treasure-gold',k:'m_gold',n:'Chest of Gold',type:'treasure',ops:[]},
{ref:'mystery-treasure-hatchet',k:'m_hatchet',n:'Rusty Hatchet',type:'treasure',ops:[['campTok','wood']]},
{ref:'mystery-treasure-helmet',k:'m_helmet',n:'Iron Helmet',type:'treasure',keep:1},
{ref:'mystery-treasure-herbal-mixture',k:'m_herbal',n:'Fortune Tea',type:'treasure',keep:1,uses:1},
{ref:'mystery-treasure-old-clothes',k:'m_clothes',n:'Old Coats',type:'treasure',keep:1},
{ref:'mystery-treasure-old-map',k:'m_oldmap',n:'Faded Chart',type:'treasure',bones:1,ops:[['det','all',1]]},
{ref:'mystery-treasure-old-rifle',k:'m_rifle',n:'Old Musket',type:'treasure',keep:1,uses:1},
{ref:'mystery-treasure-protective-amulet',k:'m_amulet',n:'Warding Charm',type:'treasure',keep:1,uses:1},
{ref:'mystery-treasure-ropes',k:'m_ropes',n:'Coil of Rope',type:'treasure',bones:1,ops:[['roofOrPal',1]]},
{ref:'mystery-treasure-saber',k:'m_saber',n:'Cutlass',type:'treasure',keep:1},
{ref:'mystery-treasure-treasure-map',k:'m_tmap',n:"Pirate's Map",type:'treasure',keep:1,uses:1},
{ref:'mystery-treasure-candles',k:'m_candles',n:'Box of Candles',type:'treasure',ops:[['keepPawn','build',2]]},
{ref:'mystery-treasure-hammock',k:'m_hammock',n:'Rope Hammock',type:'treasure',keep:1},
// ----- traps (14) -----
{ref:'mystery-trap-blowgun',k:'m_blowgun',n:'Poison Dart',type:'trap',ops:[['pawnMinusNext','actor']]},
{ref:'mystery-trap-blunt-spear',k:'m_bluntspear',n:'Spike Pit',type:'trap',bones:1,ops:[['wound','actor',2]]},
{ref:'mystery-trap-collapse',k:'m_collapse',n:'Cave-In',type:'trap',stop:1,ops:[]},
{ref:'mystery-trap-confused',k:'m_confused',n:'Disoriented',type:'trap',ops:[['charRerollNext','actor']]},
{ref:'mystery-trap-net',k:'m_net',n:'Hanging Net',type:'trap',stop:1,bones:1,ops:[['nightOut',[]]]},
{ref:'mystery-trap-poisonous-spores',k:'m_spores',n:'Poison Spores',type:'trap',ops:[['wound','actor',1],['ifItem','medicine',[],[['nightWound','all',1]]]]},
{ref:'mystery-trap-sharp-blade',k:'m_blade',n:'Swinging Blade',type:'trap',ops:[['wound','actor',2]]},
{ref:'mystery-trap-snare',k:'m_snaretrap',n:'Snapping Snare',type:'trap',ops:[['weapon',-2,1]]},
{ref:'mystery-trap-spider-web',k:'m_web',n:'Giant Web',type:'trap',ops:[['wound','actor',1],['ifItem','medicine',[],[['keep','m_web']]]]},
{ref:'mystery-trap-strange-disease',k:'m_disease',n:'Strange Fever',type:'trap',ops:[['strangeDisease']]},
{ref:'mystery-trap-terrible-scream',k:'m_scream',n:'Blood-Curdling Scream',type:'trap',ops:[['ldetAll','actor']]},
{ref:'mystery-trap-trapdoor',k:'m_trapdoor',n:'Trapdoor',type:'trap',ops:[['loseDrawnTreasures']]},
{ref:'mystery-trap-unfortunate-adventure',k:'m_unfortunate',n:'Ill-Fated Venture',type:'trap',cp:2,bones:1,ops:[['book']]},
// ----- monsters (13) -----
{ref:'mystery-creature-a-shiny-jewel',k:'m_jewel',n:'Glittering Eyes',type:'creature',ops:[['nightWound','all',1]]},
{ref:'mystery-creature-bats',k:'m_bats',n:'Swarm of Bats',type:'creature',ops:[['pick',[[['ldet','actor',1]],[['wound','actor',1]]],['discard 1 determination','take 1 wound']]]},
{ref:'mystery-creature-bite',k:'m_bite',n:'Something Bites',type:'creature',ops:[['wound','actor',1]]},
{ref:'mystery-creature-furious-tiger',k:'m_tiger',n:'Enraged Big Cat',type:'creature',ops:[['fight',{str:4},'actor']]},
{ref:'mystery-creature-giant-snake',k:'m_bigsnake',n:'Giant Serpent',type:'creature',stop:1,ops:[['ldetAll','actor']]},
{ref:'mystery-creature-gorilla',k:'m_ape',n:'Great Ape',type:'creature',ops:[['wound','actor',2]],shuffle:1,ev:{n:'Ape in the Camp',ops:[['weapon',-2]]}},
{ref:'mystery-creature-gremlins',k:'m_imps',n:'Cave Imps',type:'creature',ops:[['fight',{str:2},'actor']],shuffle:1,ev:{n:'The Imps Find You',ops:[['fight',{str:3},'first'],['reshuffleSelf']]}},
{ref:'mystery-creature-savage',k:'m_savage',n:'Wild Man',type:'creature',ops:[['weaponTo',0]],shuffle:1,ev:{n:'Failed Hunt',ops:[['mystery',{treasure:1,draw:1}]]}},
{ref:'mystery-creature-scorpion',k:'m_scorpion',n:'Scorpion',type:'creature',ops:[['ifItem','medicine',[],[['wound','actor',3]]]]},
{ref:'mystery-creature-snake',k:'m_snake',n:'Rock Snake',type:'creature',ops:[['wound','actor',2]]},
{ref:'mystery-creature-spiders',k:'m_spiders',n:'Crawling Spiders',type:'creature',ops:[['ldet','actor',2]]},
{ref:'mystery-creature-unleashed-beast',k:'m_loose',n:'Beast on the Loose',type:'creature',ops:[['huntDiscard',1]]},
{ref:'mystery-creature-big-ape',k:'m_bigape',n:'Hulking Ape',type:'creature',ops:[],shuffle:1,ev:{n:'Night Demon',ops:[['fight',{str:4,wl:0,food:0,fur:2},'first']]}}
];
