// ---------- story text: the castaways' journal. Original writing; one short beat per string. ----------
const FLAVOR={
 ev:{
  bicker:{s:'Someone ate the last crab claw. Nobody will admit it. Today everyone insists on working alone.',t:'We sit in a circle and air it all out. The crab claw is forgiven.',x:'The sulking lingers. Nobody quite believes in anybody today.'},
  grimskies:{s:'The sky turns the colour of old porridge. Rain is coming, and it looks personal.',t:'We lash branches into a windbreak. The wind grumbles and goes round.',x:'The wind swings north and the rain turns to sleet. We should have listened.'},
  hunch:{s:'Something feels off about the woods today. Our hands hesitate over every basket.',t:'We laugh at our own nerves and get on with it.',x:'The hunch grows into a dread. Every bush looks like trouble now.'},
  bear:{s:'Great claw marks on the tree by camp. Something big has been poking round our things.',t:'We dig a deep pit and cover it with fronds. Let it come.',x:'The bear raids us in the night. We wake to wreckage and sore spirits.'},
  ashore:{s:'The tide brings a stranger in, long past helping. It shakes all of us.',t:'We dig a grave above the tideline and say a few kind words.',x:'We leave the stranger where he lies. None of us can look at the beach.'},
  snapped:{s:'A rotten trunk groans and topples across camp. We all get clipped scrambling clear.',t:'We rope the trunk and haul it off. Good timber, as it turns out.',x:'The dead tree stays across the path, a daily reminder of our bruises.'},
  jungle:{s:'The jungle roars all night. The beasts out there are hungry and bold.',t:'We bang pots and wave spears until the roaring retreats. One leaves supper behind.',x:'Nobody answers the jungle’s challenge. The beasts grow bolder still.'},
  scatter:{s:'A gust flings our gear across the clearing. We can’t find a thing today.',t:'We comb the undergrowth and bring every tool home.',x:'Some of our gear is simply gone. The island keeps it.'},
  weary:{s:'Our bones ache from dawn. Tired bodies burn through food faster.',t:'We pace ourselves and take proper breaks. It pays off.',x:'We push through the tiredness and pay for it in pulled muscles.'},
  downpour:{s:'The sky opens and a river runs straight through camp. We have to move.',t:'We rebuild at the new site, board by stubborn board.',x:'We make do in the new spot, grumbling.'},
  chillrain:{s:'A cold, needling rain sets in. Everything we own is damp.',t:'We dig a drain round the camp and the puddles slink away.',x:'The drizzle never lets up. More rain rolls in behind it.'},
  council:{s:'The camp meeting turns loud. Half our clever plans get thrown out.',t:'We shake hands on one good idea and write it down.',x:'Still arguing. More ideas end up in the fire.'},
  stripped:{s:'Something has eaten its way through our hunting grounds. The game has fled.',t:'We follow fresh tracks further out and come back with meat.',x:'We tighten our belts and wait for the game to return.'},
  eyesdark:{s:'Two green eyes watch us from beyond the firelight. They will be back.',t:'We drag a bloody hide into the jungle and lead the beast away.',x:'We leave the watcher be, and it waits for us.'},
  gloom:{s:'A grey mood settles over camp. Plans feel pointless and hands feel heavy.',t:'We share a proper meal and someone starts to hum.',x:'The gloom thickens. Even the Cook stops making jokes.'},
  heartless:{s:'Our leader wakes up without a plan. Someone else must step up today.',t:'A little food and a lot of encouragement and we’re back on our feet.',x:'Nobody steps up. The whole camp droops.'},
  trampled:{s:'Something huge has stampeded through the groves by camp. Nothing is left.',t:'We replant the torn shoots. The groves will come back.',x:'The bare earth stays bare. Another grove is lost.'},
  campcollapse:{s:'A crack, a groan, and part of our camp comes down around our ears.',t:'We prop it all back up with fresh timber, stronger than before.',x:'Nobody fixes it, and half of what we built just slumps away.'},
  dryriver:{s:'The river shrinks to a trickle and then to cracked mud.',t:'We dig in the riverbed until cool water seeps up.',x:'The drought spreads. Another stretch of river runs dry.'},
  tremor:{s:'The ground shudders. Rocks tumble and block the way to a nearby valley.',t:'We shovel through the rubble and reopen the path.',x:'The rubble stays. We find other paths.'},
  restless:{s:'Nobody slept. Hammers slip and joints come out crooked.',t:'An early night and an afternoon nap work wonders.',x:'Another sleepless night. We are all snapping at each other.'},
  scuffle:{s:'Crashes in the dark. Something has been fighting over our hunting grounds.',t:'We keep watch with spears, and the night passes quietly.',x:'The beasts grow restless and hungry. We will hear them tonight.'},
  tempers:{s:'An argument over firewood turns to shoving. Everyone ends up bruised.',t:'We cool off in the sea and apologise, dripping.',x:'The quarrel festers. Nobody feels like trying today.'},
  brushfire:{s:'Smoke! A brushfire races through the trees we cut our wood from.',t:'We dig a firebreak and the flames die out at its edge.',x:'The fire smoulders on, and the woods keep burning.'},
  flashflood:{s:'A wall of brown water crashes through camp. We have to choose what to save.',t:'We carve a channel and send the flood off to the sea.',x:'The water chews at the base of our wall until it sags.'},
  swoop:{s:'A flock of angry birds dive-bombs the camp, tearing at thatch and stakes.',t:'We net their nest and move it somewhere far more scenic.',x:'The birds are back, pecking our camp to pieces.'},
  muddy:{s:'Everywhere is ankle-deep mud. Every trip to the woods takes twice as long.',t:'We lay planks over the worst of it. Clean feet at last.',x:'The mud spreads. Our favourite spots nearby are trampled to sludge.'},
  earlyfrost:{s:'We wake to frost on the fronds. The cold has arrived early.',t:'We stuff the walls with dry grass and hides. Snug as mice.',x:'We shiver through it. More snow is on the way.'},
  heavyskies:{s:'Black clouds pile up over the peaks. A soaking is coming.',t:'We stretch a hide tarp over our stores. Let it pour.',x:'No cover goes up, and the next cloud follows the last.'},
  rainway:{s:'The birds have gone quiet. That means rain, and plenty of it.',t:'We dig channels round camp to carry the water away.',x:'The rain arrives exactly as promised, and brings a friend.'},
  pouring:{s:'Rain drums on the roof, then drips through it, then pours.',t:'We patch the roof with fresh boards and stay dry.',x:'The leaks win. Another cloudburst finds its way in.'},
  risingwater:{s:'The sea creeps higher every hour. Paths inland are turning treacherous.',t:'We build a levee and the water stops at our feet.',x:'The sea sweeps into camp and carries off our stores.'},
  howls:{s:'Howls in the treetops. Something big has moved into our hunting grounds.',t:'With torches blazing, we steer the hunt away from the worst of it.',x:'The howler comes to us. Our leader must face it.'},
  spotted:{s:'A spotted cat drops out of a tree and slashes at anyone within reach.',t:'We drive it off with spears and stones.',x:'The cat returns for another go at us.'},
  mudslide:{s:'The hillside gives way and a river of mud swallows our camp. We move.',t:'We dig a clear path to the new site.',x:'The mud buries our food and wood stores. Nothing grows this round.'},
  hopeless:{s:'Our leader stares at the sea all morning. They will only potter about camp today.',t:'We point out every small win so far. Hope flickers back.',x:'The despair spreads to all of us.'},
  voyage:{s:'Someone mentions the ship’s cook’s puddings. Suddenly everyone is homesick.',t:'We tell the best stories from the voyage and laugh until we cry.',x:'The homesickness lingers like a cold.'},
  messy:{s:'Camp is a disaster of fish bones and wood shavings. Nothing can be found.',t:'We tidy up and sort everything into neat piles.',x:'The mess gets worse, and so do our moods.'},
  mist:{s:'A thick white mist rolls in. We can barely see our own feet.',t:'We sit tight until it lifts, playing pebble games.',x:'The mist hangs on, and exploring becomes guesswork.'},
  burstdam:{s:'A natural dam upstream gives way. Driftwood tumbles down; the fish are gone.',t:'We pile rocks and logs until the river calms.',x:'The flood tears through camp and carries off our gear.'},
  nightraid:{s:'Beasts rush the camp in the dark! Everyone is scratched before we drive them off.',t:'We lie in wait and bring down the leader of the raid.',x:'The raiders scatter into the hills, taking the easy game with them.'},
  howlnight:{s:'All night the howling circles camp. The beasts out there are getting braver.',t:'We take turns on watch and nothing gets past us.',x:'The beasts test our walls, and a section gives way.'},
  otters:{s:'Otters! Sleek little thieves have raided our fishing spot.',t:'We chase the otters downstream, splashing and shouting.',x:'The otters come back for seconds.'},
  badwater:{s:'The water tastes of rust and rot. By noon we all have cramps.',t:'We boil every drop, and whittle a spear while we wait.',x:'We keep drinking it anyway. More cramps.'},
  cliff:{s:'A ledge crumbles away, cutting off the route to a nearby tile.',t:'We build a rope-and-plank bridge. It’s the proudest thing we’ve made.',x:'The gap stays. We go the long way round.'},
  stalks:{s:'Fresh prints circle the camp. Something is watching and waiting.',t:'We ring the camp with snares and hear nothing more.',x:'The stalker is hungry and it knows where we sleep.'},
  hawk:{s:'A hawk has claimed the parrot roost nearest camp. The parrots are gone.',t:'We wave, whoop and throw stones until the hawk leaves.',x:'The hawk scares everything off. The woods feel strange.'},
  nearby:{s:'Paw prints on every path. Exploring without a weapon now is asking for trouble.',t:'We sweep the woods with spears and flush the predators out.',x:'The predators pick us off before they finally move on.'},
  pack:{s:'A pack of hunters has claimed our closest hunting ground.',t:'We fight the pack together and win our ground back.',x:'The pack strikes again at another of our food sources.'},
  swollen:{s:'The river bursts its banks and floods half our fields.',t:'We dig a bypass and the fields drain.',x:'The river swallows our harvest whole.'},
  drizzle:{s:'A fine, endless drizzle begins. It gets into everything.',t:'We stretch a hide over the stores. Dry socks for once.',x:'The drizzle turns into proper rain.'},
  starving:{s:'The beasts are starving and it makes them fierce.',t:'We ring the camp with fire. No starving beast will cross it.',x:'A starving beast smashes through our wall.'},
  hurricane:{s:'Hurricane winds flatten the land next to camp. Every tree is down.',t:'We clear the debris and the land breathes again.',x:'The flattened land will take its time to recover.'},
  gale:{s:'A howling gale snaps our spears and blows our bows away.',t:'We hunt through the bushes and rescue what weapons we can.',x:'We let the weapons lie where the wind flung them.'},
  rockfall:{s:'Boulders tumble down the hills and block the passes.',t:'We roll the rocks aside and clear the pass.',x:'More rocks come down. The hills are closed to us.'},
  losttrail:{s:'The paths we marked have vanished overnight. Where did we go yesterday?',t:'We blaze the trees with bright notches.',x:'Lost and grumpy, we stumble into strange places.'},
  sleepless:{s:'A night of buzzing insects. Nobody’s hands are steady today.',t:'A long nap in the shade restores our wits.',x:'Groggy and careless, we wander where we shouldn’t.'},
  sluggish:{s:'Our tools are blunt and our arms are slow. Building eats more wood.',t:'We sharpen every blade on a flat stone.',x:'Blunt tools, wasted wood, another sluggish day.'},
  smoke:{s:'A column of smoke rises beyond the plains. Nobody wants to walk that way.',t:'We creep over for a look. Just a lightning fire. The plains are safe.',x:'The smoke keeps rising, and the plains stay off-limits.'},
  battered:{s:'The storm tears at our camp all night. Half our work is in tatters.',t:'We mend every lashing and nail every board back in place.',x:'Nobody mends it, and the next gust takes more.'},
  squall:{s:'A squall barrels in off the sea, black and furious.',t:'We batten down everything that moves.',x:'The squall kicks our wall in.'},
  twist:{s:'Everything happens at once. Our troubles all come due together.',t:'We shrug, laugh, and take what comes. Hardship makes us tougher.',x:'The upheaval leaves us drained.'},
  howlwind:{s:'A fierce wind makes every build a wrestling match.',t:'We tie everything down with rope and knots.',x:'The wind snatches away some of our gear.'},
  sunny:{s:'A perfect sunny morning. The sea sparkles and nothing is on fire.',t:'We take the day off to swim and bask. Pure joy.',x:'We’re too busy to enjoy it. The sun sets on grumpy faces.'},
  borers:{s:'Tiny borers are chewing through our woodpile.',t:'We smoke them out with a smouldering fire.',x:'The borers feast on another log.'},
  strikes:{s:'The island seems to rise against us. Its oldest trouble wakes.',t:'We hold our nerve and weather it together.',x:'The island strikes again, harder.'},
  lightning:{s:'Lightning splits the forest nearest camp. The trees burn black.',t:'We clear the burnt timber and new shoots spring up.',x:'Another strike hits another grove.'},
  bitter:{s:'The coldest night yet. We burn our wood or we freeze.',t:'We stack a great pile of fuel for tomorrow.',x:'We shiver until dawn, frostbitten and sore.'},
  dizzy:{s:'Our leader wakes up dizzy and can only manage half a day.',t:'We make them lie down in the shade with coconut water.',x:'The dizziness spreads. Nobody is at their best.'},
  feeble:{s:'Our leader wakes up weak as a kitten. Their special tricks are beyond them today.',t:'Stretching, good food, and they’re stronger by the hour.',x:'The weakness hangs on another day.'},
  winterblues:{s:'Short days and cold nights. The camp is sinking into the winter blues.',t:'A hot supper round the fire brings the smiles back.',x:'The blues deepen. Everyone’s spirit dims.'},
  balloon:{s:'A torn balloon hangs in a tree, its basket empty. Poor souls.',t:'We search the basket and find something useful inside.',x:'We leave the basket swinging in the tree.'},
  crates:{s:'Wooden crates bob in the surf, stamped with the ship’s mark.',t:'We wade out and drag them ashore. Food!',x:'The crates drift off with the tide.'},
  seachest:{s:'A sea chest floats just past the breakers.',t:'We swim out and haul it in. Timber, and maybe a treasure.',x:'The chest bobs away out of reach.'},
  dinghy:{s:'Our smashed dinghy lies on the rocks. There’s good timber in her yet.',t:'We break her up and carry the boards home.',x:'The waves finish off the dinghy for us.'}
 },
 adv:{
  b_slip:{s:'The hammer slips and lands squarely on the Carpenter’s shin. Ouch.',e:'The leg wound starts to fester. Without medicine it gets ugly.'},
  b_breakdown:{s:'Halfway through the build, someone just sits down and cries.',e:'A good night’s sleep, and our leader wakes full of fire.'},
  b_lever:{s:'Our best spear cracks while we use it as a lever.'},
  b_tool:{s:'Snap! A tool breaks in half mid-swing.'},
  b_terms:{s:'We admit some plans just won’t work here. They go on the fire.',e:'We stare at the blank sketch-bark. Out of ideas, out of heart.'},
  b_construct:{s:'The joints fit perfectly. This build feels properly solid.',e:'Our careful work pays off: the walls stand even stronger.'},
  b_cuthead:{s:'A beam swings round and cracks someone on the head. They see stars, and also an idea.',e:'The headache returns with a vengeance.'},
  b_dangerous:{s:'This build is risky. Every beam feels ready to fall.'},
  b_darkclouds:{s:'Dark clouds roll in as we work. Rain is coming.',e:'After the rain, the wet earth packs hard round our stakes.'},
  b_fast:{s:'Our hands fly today. We could squeeze in one more build.',e:'We rushed it. Something we built comes loose.'},
  b_fear:{s:'Roars from the jungle. We need bigger, heavier weapons.',e:'Our new weapon designs are hefty, and hungry for timber.'},
  b_hard:{s:'Back-breaking work. We eat more than we’d planned.'},
  b_howl:{s:'The bushes by the build site rustle. We keep one eye on them.',e:'It pounces! A beast bursts out of the bushes.'},
  b_hungry:{s:'A hungry beast noses into the site. Fight it, or feed it and hope?',e:'The hungry visitor returns, and this time it wants more.'},
  b_hurry:{s:'We could rush this and find treasures in the scrap pile.',e:'A crack runs through the wall we built in a hurry.'},
  b_laborious:{s:'Every board fights back. This will take longer than planned.'},
  b_nohope:{s:'Our grand designs crumble. We scrap a pile of ideas.'},
  b_monkey:{s:'Monkeys watch us build, heads tilted. They look far too interested.',e:'The monkeys return and take our camp apart, piece by piece.'},
  b_nasty:{s:'A splinter tears a deep gash in an arm.',e:'The gash turns red and angry. Medicine, please.'},
  b_campbeast:{s:'A beast strolls right into camp. Nothing for it but to fight!',e:'We skin and salt what’s left of the beast. A fine store of meat and hide.'},
  b_savings:{s:'We have timber left over. Keep it, and hope the build holds?',e:'The corners we cut make the building wobble. Spirits sag.'},
  b_sting:{s:'A wasp stings someone right in the belly.',e:'The sting brings on the shakes. Without medicine, a half-day lost.'},
  b_tired:{s:'We’re worn out. Take a rest now and pay for it later?',e:'The lazy afternoon leads to a squabble.'},
  b_inspect:{s:'We check our tools. A couple look close to giving out.',e:'Snap, clunk. The tools we worried about finally break.'},
  b_unmotivated:{s:'No energy at all. Push through the pain, or give up for the day?',e:'The tools feel dull in our hands. So do we.'},
  b_visit:{s:'A sly predator snatches some food while we hammer away.',e:'The prowler comes back at night, hungrier.'},
  b_weak:{s:'The frame looks shaky. We shrug and carry on.',e:'Crash! Half the roof caves in.'},
  b_wind:{s:'A gust flattens part of the wall.',e:'We plant a hedge as a windbreak. The wall grows stronger.'},
  b_bigger:{s:'Our camp feels cramped. We’ll need more room soon.',e:'The camp grows, and so does the bill for timber.'},
  g_hurricane:{s:'The storm has left plenty of driftwood, though the path is a mess.',e:'The tide washes out the path completely.'},
  g_end:{s:'We gather the last of it. This spot is picked clean.'},
  g_eyes:{s:'Eyes in the leaves watch us gather. We work faster.',e:'Our watcher comes calling tonight.'},
  g_fruit:{s:'A strange purple fruit. It tastes wonderful, then rumbles.',e:'The bellyache hits. Without medicine, a day in the hammock.'},
  g_furs:{s:'A hollow full of old pelts. Take them, and whatever lives there?',e:'Biting insects from the pelts get into the food stores.'},
  g_coin:{s:'An old gold coin glints in the dirt. We pocket it.',e:'The coin is cursed! Everything we try goes a little wrong.'},
  g_mushroom:{s:'A patch of plump mushrooms. Probably edible. Probably.',e:'Very probably not edible. Queasy stomachs all round.'},
  g_nest:{s:'A nest full of eggs. Breakfast for everyone, if we dare.',e:'The mother bird finds us and tears at our roof.'},
  g_flock:{s:'A new flock of birds settles nearby. Easy pickings.',e:'The flock moves on, and the spot is empty.'},
  g_surprise:{s:'A great pile of driftwood! Something about it feels too lucky.',e:'The driftwood was soft and rotten. The roof sags.'},
  g_path:{s:'Fresh prints cross the gathering path.',e:'Ambushed! The predator we tracked comes for us.'},
  g_chest:{s:'A buried chest, iron-banded. Dig it up?',e:'Unlucky day. Everyone moves as if through treacle.'},
  g_shortage:{s:'We take the very last of it. A good haul, but that’s the end.'},
  g_signs:{s:'Deep claw marks on the trees. A predator has marked its ground.',e:'The predator strikes our food source by camp.'},
  g_skeleton:{s:'Old bones under a tree, clutching a leather wallet.',e:'The dead man’s notes are grim reading, but hold a clever idea.'},
  g_spider:{s:'A hairy spider drops onto someone’s neck.',e:'The bite swells up. They can only manage half a day.'},
  g_bushes:{s:'Something shiny in the brush. Grab it?',e:'We keep brooding on what else might lurk out there.'},
  g_tracks:{s:'Big paw prints all around the gathering spot. We’ll be careful here.'},
  g_ankle:{s:'A root catches a foot. The ankle turns with a nasty twist.',e:'The ankle swells. Only light camp work for a while.'},
  g_effort:{s:'One big heave and we could haul extra timber. Our arms might not thank us.',e:'The arms ache badly after that heroic effort.'},
  g_find:{s:'A lucky find in the undergrowth!'},
  g_trouble:{s:'The ground here is treacherous and crumbling. We’ll steer clear for now.'},
  g_viper:{s:'An adder slides through the grass by our feet. We freeze until it passes.',e:'The adder strikes! Without medicine, the bite is serious.'},
  g_weather:{s:'The wind shifts. Old sailors know what that means.',e:'The storm arrives, right on cue.'},
  g_freeze:{s:'The ground is frozen hard. Nothing more will come from here.'},
  g_winter:{s:'A cold edge on the breeze. Winter is drawing near.',e:'Frost on the ground by morning, and snow in the clouds.'},
  e_bamboo:{s:'A grove of tall bamboo! Cut it down, if we don’t mind the risk.',e:'The bamboo was brittle. It snaps under the weight.'},
  e_carcass:{s:'A freshly killed carcass. Meat and hide, if we are brave or foolish.',e:'The meat was bad. Everyone gets sick.'},
  e_coldwind:{s:'An icy breeze sweeps down from the peaks.',e:'Snow begins to fall across the island.'},
  e_danger:{s:'Dangerous ground here: bones, prints and a strong musky smell.'},
  e_empty:{s:'The forest is silent. No birds, no beasts. Unsettling.',e:'The beasts are back, and they are starving.'},
  e_flu:{s:'Chills and a runny nose. Rest and eat more, or tough it out?',e:'The sore throat spreads. Everyone needs more food tonight.'},
  e_rain:{s:'Rain clouds gather on the horizon.',e:'The heavy rain arrives, right on schedule.'},
  e_thicket:{s:'Lost in a thicket, we curl up for the night far from camp. There’s a find nearby.'},
  e_woods:{s:'We walk in circles for hours. Sore feet, sorer spirits.'},
  e_lost:{s:'Lost for the night! Somehow the stars cheer us more than camp would.'},
  e_misstep:{s:'A misstep on a loose rock. The leg twists badly.',e:'The leg swells up. Only light work for a while.'},
  e_grave:{s:'An old grave, marked with a rough cross. It chills us.',e:'The ghost of a castaway haunts our leader’s dreams.'},
  e_oldhut:{s:'An abandoned hut. Something lives there still, maybe. Search it?',e:'The hermit’s ghost wails through the night.'},
  e_puma:{s:'Big cat tracks, very fresh. Hide out for the night or head home?',e:'The big cat attacks the camp!'},
  e_settle:{s:'The ruins of an old settlement. Rich pickings, and possibly traps.',e:'The settlement carried some old sickness. We all fall ill.'},
  e_ruinhut:{s:'A tumbledown shack full of old tools. Salvage something?',e:'Nightmares of the shack’s last owner haunt us.'},
  e_cave:{s:'A hidden cave. Treasures, surely. Something else too, probably.',e:'The beast in the cave wakes up and follows us home.'},
  e_shrine:{s:'A jungle shrine, carved with strange faces. Leave an offering and take a peek?',e:'The faces follow us in our dreams. Everything goes a bit wrong.'},
  e_fire:{s:'Scorched earth. A fire has ruined this place.'},
  e_storm:{s:'A storm brews on the horizon.',e:'The storm hits the island with full force.'},
  e_surprise:{s:'A blade glints in the sand. Just the thing for a tight spot.'},
  e_swamp:{s:'A bog sucks at our boots. This place will be slow going.'},
  e_air:{s:'Something in the air. The island feels watchful.',e:'The island is cursed, and it lets us know.'},
  e_thorn:{s:'A thorn thicket rakes our arms bloody.',e:'The scratches swell. Without medicine, a day lost.'},
  e_tiger:{s:'A striped shadow slips between the trees. Hide out tonight, or risk home?',e:'The striped cat has followed us home!'},
  e_vipers:{s:'A snake nest! One strikes before we can jump back.',e:'A fever sets in. Without medicine, half a day lost.'},
  e_berries:{s:'Wild berries, sweet and juicy. We eat far too many.',e:'Nausea. Only half a day’s work possible.'},
  e_dog:{s:'A stray dog snaps at us, then follows at a distance.',e:'The dog is back, eyes pleading. Feed it, or send it off?'},
  e_wrong:{s:'A wrong turn, and night falls far from camp. We gather wood by starlight.'}
 },
 mys:{
  m_locket:{s:'A locket with a portrait of a smiling stranger. It lifts our spirits.'},
  m_rapier:{s:'An old duelling sword, still sharp. En garde!'},
  m_backpack:{s:'A sturdy canvas backpack. We can carry more.'},
  m_barrel:{s:'A water cask, sealed tight. Fresh water, anywhere.'},
  m_blankets:{s:'Wool blankets, dry and warm. Perfect for cold nights.'},
  m_wine:{s:'A bottle of brandy! For medicinal purposes, of course.'},
  m_boxes:{s:'Sealed tins. Who knows what’s inside? Something useful, surely.'},
  m_spyglass:{s:'A navigator’s spyglass. We can see what lies ahead.'},
  m_furcave:{s:'A cave full of old pelts. Warm nights ahead.'},
  m_bowl:{s:'A ritual bowl. Touching it brings bad luck on our hands.',e:'We perform a little ceremony, and the curse lifts.'},
  m_compass:{s:'A brass compass. Exploring gets much easier.'},
  m_crocks:{s:'Clay jars, whole and sound. A ready-made cooking pot.'},
  m_gold:{s:'A chest of gold. Utterly useless here, but lovely to look at.'},
  m_hatchet:{s:'A rusty hatchet. Still bites wood nicely.'},
  m_helmet:{s:'An iron helmet. Dented, but it fits.'},
  m_herbal:{s:'A pouch of fortune tea. Supposedly lucky.'},
  m_clothes:{s:'Old coats, musty but warm.'},
  m_oldmap:{s:'A faded chart of the island. It gives us all heart.'},
  m_rifle:{s:'An old musket with one good shot left.'},
  m_amulet:{s:'A warding charm. We feel safer already.'},
  m_ropes:{s:'A coil of good rope. The camp gets stronger.'},
  m_saber:{s:'A cutlass! Now we’re properly pirate-y.'},
  m_tmap:{s:'A pirate’s map, marked with an X. Worth following once.'},
  m_candles:{s:'A box of candles. We can work late into the night.'},
  m_hammock:{s:'A rope hammock. Luxury.'},
  m_blowgun:{s:'A poison dart whistles out of the dark! Tomorrow will be sluggish.'},
  m_bluntspear:{s:'A spike pit! We fall right into it.'},
  m_collapse:{s:'Cave-in! We scramble out and don’t go back.'},
  m_confused:{s:'We lose our bearings in the tunnels. Tomorrow will be clumsy.'},
  m_net:{s:'A hanging net scoops us up! We spend the night dangling.'},
  m_spores:{s:'Poison spores puff up from the ground. Without medicine, tonight will hurt.'},
  m_blade:{s:'A swinging blade scythes out of the wall!'},
  m_snaretrap:{s:'A snare snaps shut on our weapons and drags them away.'},
  m_web:{s:'A giant web! We tear free, but it clings.'},
  m_disease:{s:'A strange fever creeps into our bones. The night will be rough.'},
  m_scream:{s:'A blood-curdling scream echoes through the ruins. Our nerve shatters.'},
  m_trapdoor:{s:'A trapdoor! Everything we found tumbles into the dark.'},
  m_unfortunate:{s:'An ill-fated venture wakes the island’s darkest trouble.'},
  m_jewel:{s:'Glittering eyes in the darkness. Tonight, they come for us.'},
  m_bats:{s:'A swarm of bats! Duck and flee, or swat them away?'},
  m_bite:{s:'Something small and nasty bites and scurries off.'},
  m_tiger:{s:'An enraged big cat! We must fight it.'},
  m_bigsnake:{s:'A giant serpent uncoils in the dark. We run and don’t look back.'},
  m_ape:{s:'A great ape roars and swings at us!',e:'The ape tracks us home and smashes our weapons.'},
  m_imps:{s:'Cave imps swarm out of the rocks! Fight them off!',e:'The imps have found the camp. They’re back again!'},
  m_savage:{s:'A wild man leaps out and snatches all our weapons.',e:'The wild man drops something as he flees our hunt.'},
  m_scorpion:{s:'A scorpion’s sting! Without medicine, it’s bad.'},
  m_snake:{s:'A rock snake strikes from a crevice!'},
  m_spiders:{s:'Spiders crawling everywhere. We shudder for hours.'},
  m_loose:{s:'A beast on the loose chases our game away.'},
  m_bigape:{s:'A hulking ape watches from the shadows, then vanishes.',e:'The night demon comes to camp. We must fight!'}
 },
 beast:{
  alligator:'Two eyes and a snout break the swamp water. Alligator!',
  bear:'A bear rears up, twice our height and very annoyed.',
  birds:'A flock of plump birds. Easy supper, if we’re quiet.',
  boa:'A boa hangs from a branch, lazily flexing its coils.',
  chamois:'A chamois leaps from rock to rock, horns lowered.',
  cheetah:'A cheetah flashes through the grass faster than thought.',
  fox:'A fox sniffs the air and bares tiny sharp teeth.',
  goats:'A herd of wild goats, stubborn and horned.',
  gorilla:'A gorilla beats its chest. Its eyes are very clever.',
  iguana:'A huge iguana with a whip of a tail. It will leave a mark.',
  jaguar:'A jaguar drops silently from the canopy.',
  puma:'A puma crouches on the rocks, tail twitching.',
  tapir:'A startled tapir snorts and charges.',
  tiger:'A tiger steps out of the shadows. Everything goes quiet.',
  'wild-dog':'A wild dog snarls, hackles up, foam on its lips.',
  'wild-pig':'A wild pig grunts, tusks gleaming. Supper, or trouble.'
 },
 scen:{
  marooned:{title:'The Signal on the Hill',
   intro:['The storm split our ship like kindling. By dawn, only a handful of us crawled ashore on a strip of wet sand.','{crew}','Somewhere out there, ships still sail these waters. If we can light a fire and build a signal pile high enough, one might spot us.','Summer is short on this island. The rain will come, then worse. We have until the last days of autumn.'],
   days:{1:'First morning. We count our fingers, our toes, and our blessings.',2:'The beach is ours. The rest of the island is still a mystery.',3:'We are learning the island’s moods. It has many.',4:'The first rains arrive. Time to keep our heads dry.',5:'Wet sand, wet wood, wet socks. Still here.',6:'Half our time is gone. The signal pile must grow.',7:'The air turns cold. The beasts grow hungry.',8:'Snow on the peaks. We huddle and keep building.',9:'Our hands are hard now. So are we.',10:'Any day now, a ship might pass. Is the fire ready?',11:'Every eye watches the horizon.',12:'The last chance. Light it, and pray for a sail.'},
   win:'A white sail breaks the horizon and turns toward our smoke. We cheer until we’re hoarse, and the dog barks at the waves. We are going home.',
   lose:'The seasons turned and no ship came. The island keeps us, and our journal ends here.'},
  hexed:{title:'The Curse of the Hexed Isle',
   intro:['We washed ashore on an island that feels wrong. The birds don’t sing, and the fog moves against the wind.','{crew} Old stones, strange carvings and whispered warnings. Someone cursed this place, and now the curse has caught us too.','The old stories say five crosses, raised on five different corners of the island, will break it.','Winter comes early here. Snow will bite before long. We must hurry.'],
   days:{1:'The fog lifts a little. We can see the island’s edge.',2:'Carvings on the rocks watch us work.',3:'The fog shifts where we don’t look.',4:'Something whispers from the trees at night.',5:'Halfway there. The curse feels heavier.',6:'The first snow falls, thin and grey.',7:'Cold hands, cold hearts. But we keep going.',8:'The fog swallows paths we walked yesterday.',9:'The curse grows restless. So do we.',10:'The last days. Every cross counts.'},
   win:'The fifth cross is raised and the fog rolls back into the sea. Birds sing for the first time since we arrived. The island is at peace, and so are we.',
   lose:'The fog closed in for good, and the curse kept its prize. We should never have landed here.'},
  stranded:{title:'Ada on the Rock',
   intro:['The wreck scattered us along the reef. {Count} of us made it to the beach, but our shipmate Ada did not.{fri}','She clings to a spur of rock out beyond the breakers, waving her shawl. We can hear her calling.','We need a raft to reach her, and after that a proper lifeboat to carry us all home.','Every night on the rock, the sea takes more out of Ada. We have no time to waste.'],
   days:{1:'Ada waves from the rock. We wave back and get to work.',2:'We can hear her singing to keep her spirits up.',3:'The rock looks smaller every day.',4:'Ada’s voice is growing faint.',5:'The beasts have noticed us. Hungry nights ahead.',6:'The sea is rough. Hold on, Ada.',7:'We’re almost ready. Just a little longer.',8:'The last chance. Now or never.'},
   win:'With Ada safe aboard, our little lifeboat punches through the surf. She won’t stop hugging everyone, the dog included. We’re going home together.',
   lose:'We were too slow, and the sea took what it wanted. Our journal ends with a name we will never forget.'},
  settlers:{title:'A Home on the Island',
   intro:['Nobody is coming. We have made our peace with that.','{crew} Instead, we will build a home: a real one, with a roof, a wall, tools and a garden.','And soon there will be little ones to feed. We must be ready.','The island is harsh, but it is ours now. Let’s make something of it.'],
   days:{1:'The first day of our new life.',2:'We sketch plans in the sand.',3:'The rain comes to test us.',4:'The camp takes shape, board by board.',5:'Snow on the hills. Snug walls matter now.',6:'Halfway there. Keep building.',7:'A baby’s cry! The camp is growing.',8:'Little mouths, big appetites.',9:'Another child joins us.',10:'The cold bites. We huddle close and keep working.',11:'A third little one. The camp is full of noise.',12:'The last push. Is our home ready?'},
   win:'The house stands snug, the walls are strong, and the children sleep soundly. We’re not castaways any more. We’re home.',
   lose:'We couldn’t keep everyone fed and safe. The settlement failed, and the island claims it back.'}
 },
 chars:{
  carpenter:{bio:'Hands like shovels and a heart of gold; can build anything from anything, given enough grumbling.',hurt:['Mind the thumbs!','Just a splinter. A big one.','Ow, that’s my good arm!'],success:['Solid as oak.','Measure twice, cut once.','Now that’s craftsmanship.'],fail:['Wood’s too green.','Back to the drawing board.','That’s firewood now.'],hungry:['Can’t swing a hammer on an empty stomach.','Is that pot bubbling yet?'],cheer:['We’ll build our way out of this.','Every board is one step closer home.']},
  cook:{bio:'Plump, cheerful and utterly unflappable; can make soup from seaweed and a joke from anything.',hurt:['That’s going in the soup!','Oof, my apron!','Just a scratch, love.'],success:['Dinner is served!','Bit of salt, bit of luck.','Nobody goes hungry on my watch.'],fail:['Burned it again.','Well, that didn’t rise.','We’ll call it rustic.'],hungry:['Even I’m hungry, and I’ve been tasting.','The pot’s empty. That’s not right.'],cheer:['Nothing a hot meal won’t fix.','Chin up, bellies full!']},
  explorer:{bio:'All legs and curiosity; would walk into a volcano to see what was inside.',hurt:['Worth it for the view!','I’ve had worse. Probably.','Ouch. Noted on the map.'],success:['Found it!','Another blank on the map filled in.','Look what’s over here!'],fail:['Dead end.','That path went nowhere.','Must’ve gone the wrong way round.'],hungry:['I could eat a map.','Exploring runs on food.'],cheer:['There’s always something round the next corner.','Adventure awaits!']},
  soldier:{bio:'Stern, steady and secretly soft; keeps watch so everyone else can sleep.',hurt:['Hold the line!','Only a flesh wound.','I’ve had worse on parade.'],success:['Mission complete.','That’s how it’s done.','Target down.'],fail:['Tactical retreat.','Regroup and try again.','Blast it.'],hungry:['An army marches on its stomach.','Rations, please.'],cheer:['Stand fast, all of you.','We’ve survived worse.']},
  friday:{bio:'A friendly islander who knows every path and laughs at our clumsy ways.',hurt:['Aiee! Careful, friends.','Island bites, but I bite back.','Not so bad.'],success:['Easy, see?','The island likes us today.','Ha! Good work.'],fail:['Hmm. Island says no.','Tomorrow, better.','Even I miss sometimes.']},
  ada:{bio:'Our quick-witted shipmate, stubborn enough to outlast any rock in the sea.',hurt:['Hurry, please!','I can’t hold on much longer!']}
 },
 phase:{
  dawn:['A new day on the island. The sun climbs over the sea.','Morning comes, bright and damp. We stretch and get up.','Another dawn, another chance. We’re still here.','The birds wake us. Time to see what today brings.'],
  moraleUp:['Spirits rise! Someone is whistling.','We’re in good heart today.','Laughter round the camp. It helps.'],
  moraleDown:['Spirits sink. Nobody says much.','A heavy mood hangs over camp.','We’re losing heart.'],
  prod:['Our camp gives what it can: food and firewood.','Traps and trees yield their small harvest.','The camp’s surroundings feed and fuel us.'],
  plan:['We sit in a circle and plan the day.','Sticks in the sand: who goes where?','Plans are made, jobs are shared out.'],
  calm:['Blue skies. A rare kindness.','The weather holds fair today.','Calm and clear. We make the most of it.'],
  rain:['Rain rattles on the fronds.','Rain again. Everything is soggy.','A steady rain. Keep the wood covered!'],
  snow:['Snow falls, soft and cold.','Snowflakes on the sand. It’s bitter.','Snow piles up round camp. We need wood.'],
  storm:['A storm tears across the island!','Thunder, lightning and wind. Hold on!'],
  animals:['Hungry animals prowl round camp.','Growls at the edge of the firelight.'],
  nightFed:['Full bellies tonight. We sleep well.','Supper, then we huddle together. Life isn’t so bad.','Everyone eats. Fed, if not quite warm.'],
  nightFire:['Supper round the fire. Life isn’t so bad.','The fire crackles and everyone eats. Warm and fed.'],
  nightHungry:['We go to bed hungry.','Empty bellies and a long night.','Not enough food to go round.'],
  nightOpen:['We sleep under the stars, cold and exposed.','No shelter tonight. The ground is hard.'],
  nightShelter:['Snug under our own roof.','The shelter keeps the worst of the night out.'],
  build:['Finished! We step back and admire it.','Another piece of our new life stands complete.','It holds! Well done, everyone.'],
  gather:['Our baskets come back full.','A good haul from the island.','We carry our harvest home.'],
  explore:{beach:'Sand, shells and seabirds. The beach opens up before us.',river:'Clear water tumbles over stones. Fish flash in the shallows.',plains:'Wide grassy plains roll away under an open sky.',hills:'Rocky hills rise ahead, covered in scrub and goats.',mountains:'Craggy peaks tower above the clouds.'},
  exploreFail:['We push into the unknown and find nothing but thorns.','Our trek ends at a dead end. Maybe tomorrow.'],
  huntWin:['The hunt is a success! Meat tonight.','We bring down the beast. Food and hides!'],
  huntHurt:['The beast fights back hard.','We win, but not without scars.'],
  threatDone:['We deal with the trouble. One less worry.','That’s sorted. Back to work.']
 }
};
