# Builds cauldron-fair.html (one self-contained file) and x.js (all our scripts joined, for node --check).
# All paths are repo-relative (this file lives in games-src/cauldron-fair/).
import re, os, sys, json, base64, io
D = os.path.dirname(os.path.abspath(__file__))
SP = os.path.abspath(os.path.join(D, '..'))   # games-src
def rd(p): return open(p, encoding='utf-8').read()
S = os.path.join(D, 'src')
parts = sorted((f for f in os.listdir(S) if re.match(r'ui\d+\.js$', f)), key=lambda f: int(re.findall(r'\d+', f)[0]))
ui = ''.join(rd(os.path.join(S, f)) for f in parts)
open(os.path.join(D, 'ui.js'), 'w', encoding='utf-8').write(ui)
AUD = os.path.join(D, 'audio')
SRC = {'shell.js': os.path.join(SP, 'shell', 'shell.js'), 'gx-viewport.js': os.path.join(SP, 'shell', 'gx-viewport.js'), 'gx-help.js': os.path.join(SP, 'shell', 'gx-help.js'), 'gx-tutor.js': os.path.join(SP, 'shell', 'gx-tutor.js'), 'perfhud.js': os.path.join(SP, 'perf', 'perfhud.js'), 'gameaudio.js': os.path.join(SP, 'audio', 'gameaudio.js'),
       'gx-campaign.js': os.path.join(SP, 'shell', 'gx-campaign.js'), 'campaign-data.js': '', 'kit.js': os.path.join(S, 'kit.js'), 'art-data.js': '', 'data.js': os.path.join(S, 'data.js'), 'engine.js': os.path.join(S, 'engine.js'), 'ai.js': os.path.join(S, 'ai.js'), 'ui.js': os.path.join(D, 'ui.js'),
       'trystero.min.js': os.path.join(SP, 'net', 'trystero.min.js'), 'netroom.js': os.path.join(SP, 'net', 'netroom.js'), 'netstrip.js': os.path.join(S, 'netstrip.js'), 'net.js': os.path.join(S, 'net.js')}
# ---- painted art: art/manifest.json maps id -> base name. <name>.png (a painting dropped in by hand) wins over <name>.webp (made by paint/paint.js);
# a PNG is resized to the manifest size and re-encoded as WebP so the file stays small.
ART = os.path.join(D, 'art')
def art_js():
    mp = os.path.join(ART, 'manifest.json')
    if not os.path.exists(mp): print('NOTE: no art manifest, vector view only', file=sys.stderr); return '// no painted art\nvar CF_ART = {};\n'
    man = json.load(open(mp, encoding='utf-8'))
    out, total = {}, 0
    for k, name in man['items'].items():
        png, webp = os.path.join(ART, name + '.png'), os.path.join(ART, name + '.webp')
        if os.path.exists(png):
            from PIL import Image
            im = Image.open(png).convert('RGBA'); W, H = man['size'].get(k, im.size); im.thumbnail((W, H), Image.LANCZOS)
            if im.size != (W, H) and (k.startswith('t-') or k in ('cauldron', 'title', 'table')): im = im.resize((W, H), Image.LANCZOS)
            b = io.BytesIO(); im.save(b, 'WEBP', quality=82, method=6); data = b.getvalue(); print('art: using', name + '.png', file=sys.stderr)
        elif os.path.exists(webp): data = open(webp, 'rb').read()
        else: print('NOTE: art missing', name, file=sys.stderr); continue
        total += len(data); out[k] = 'data:image/webp;base64,' + base64.b64encode(data).decode('ascii')
    print('art: %d images, %d KB' % (len(out), total // 1024), file=sys.stderr)
    return '// painted art (generated by build.py from art/; see paint/paint.js)\nvar CF_ART = ' + json.dumps(out, separators=(',', ':')) + ';\n'
ART_JS = art_js()
# credits snippet for the rules drawer
cr = os.path.join(AUD, 'credits.html')
if os.path.exists(cr): ART_JS += 'var CF_CREDITS = ' + json.dumps(rd(cr)) + ';\n'
audio = os.path.join(AUD, 'audio-data.js')
if os.path.exists(audio): SRC['audio-data.js'] = audio
else: print('NOTE: audio-data.js missing, silent build', file=sys.stderr)
ORDER = ['shell.js', 'gx-viewport.js', 'gx-help.js', 'gx-tutor.js', 'gx-campaign.js', 'campaign-data.js', 'perfhud.js', 'trystero.min.js', 'netroom.js', 'data.js', 'engine.js', 'ai.js', 'kit.js', 'art-data.js', 'netstrip.js', 'gameaudio.js', 'audio-data.js', 'net.js', 'ui.js']
h = rd(os.path.join(S, 'head.html')).replace('/*SHELL_CSS*/', rd(os.path.join(SP, 'shell', 'shell.css'))).replace('</head>', '<style>\n' + rd(os.path.join(SP, 'shell', 'gx-campaign.css')) + '\n' + rd(os.path.join(SP, 'shell', 'gx-help.css')) + '\n' + rd(os.path.join(SP, 'shell', 'gx-tutor.css')) + '\n</style>\n</head>', 1)
body = rd(os.path.join(S, 'body.html'))
if 'audio-data.js' in SRC: body = body.replace('<script src="ui.js"></script>', '<script src="audio-data.js"></script>\n<script src="ui.js"></script>')
for f in ORDER:
    tag = '<script src="%s"></script>' % f
    if f not in SRC: continue
    assert tag in body, f
    src = (ART_JS if f == 'art-data.js' else ('window.CAMPAIGN = ' + json.dumps(json.load(open(os.path.join(D, 'campaign.json'), encoding='utf-8')), separators=(',', ':'), ensure_ascii=False) + ';') if f == 'campaign-data.js' else rd(SRC[f])).replace('</script', '<\\/script')
    body = body.replace(tag, '<script>\n' + src + '\n</script>')
# PixiJS (MIT, licence header kept): stored as text and only run when the page decides to use the WebGL/canvas table
px = rd(os.path.join(D, 'vendor', 'pixi.min.js')).replace('//# sourceMappingURL=pixi.min.js.map', '').replace('</script', '<\\/script')
ptag = '<script type="text/plain" id="pixi-src" src="pixi.min.js"></script>'
assert ptag in body
body = body.replace(ptag, '<script type="text/plain" id="pixi-src">\n' + px + '\n</script>')
out = h + body
open(os.path.join(D, 'cauldron-fair.html'), 'w', encoding='utf-8').write(out)
js = '\n'.join(re.findall(r'<script>(.*?)</script>', out, re.S))
open(os.path.join(D, 'x.js'), 'w', encoding='utf-8').write(js)
print('cauldron-fair.html', len(out.encode('utf-8')), 'bytes')
