// r17probe.js — read-only in-page measurements for tRace (race worker 17). Works on live and on the race15 stack.
// PACK: every ship's distance (pack spread 1st→last, overtakes). CLEAR: ray-based clearance of a car.
//  - tyres: a ray from 0.6 m above each tyre's lowest point straight down onto the world (road, corridor, water);
//    gap = hit distance − 0.6 (>0 floating, <0 sunk). Wheels hidden (boat) → the hull's lowest point vs the water (draft, <0).
//  - walls: horizontal rays left/right from the car centre at 0.7 m; nearest vertical surface minus the car's half width.
module.exports.PACK=`(()=>{const E=__oc.ev;return E('ships.map((o,i)=>[i,+o.dist.toFixed(1),o.eliminated||o.finished?1:0,o.isPlayer?1:0])')})()`;
module.exports.CLEAR=(who)=>`(()=>{const E=__oc.ev;return E(${JSON.stringify(`(()=>{
 const R=window.__r17rc||(window.__r17rc=new THREE.Raycaster());const up=new THREE.Vector3(0,1,0),dn=new THREE.Vector3(0,-1,0);
 const ex=new Set();for(const o of ships)if(o.mesh)o.mesh.traverse(m=>ex.add(m));
 const visOk=o=>{for(let a=o;a;a=a.parent)if(!a.visible)return false;return true};
 if(!window.__r17obj||window.__r17objT!==TD){const L=[];scene.traverse(o=>{if((o.isMesh||o.isInstancedMesh)&&!o.isSprite&&!o.isPoints&&o.geometry&&o.geometry.attributes&&o.geometry.attributes.position)L.push(o)});window.__r17obj=L;window.__r17objT=TD}
 const cand=(p,r)=>window.__r17obj.filter(o=>{if(ex.has(o)||!visOk(o))return false;if(typeof R15I!=='undefined'&&o===R15I.im)return false;const g=o.geometry;if(!g.boundingSphere)g.computeBoundingSphere();if(o.isInstancedMesh)return true;const c=g.boundingSphere.center.clone().applyMatrix4(o.matrixWorld);const rr=g.boundingSphere.radius*o.matrixWorld.getMaxScaleOnAxis();return c.distanceTo(p)<rr+r});
 const one=(s)=>{if(!s||!s.mesh)return null;s.mesh.updateMatrixWorld(true);const f=frameAt(TD,s.dist,mkF());const out={terr:s.terrain||'road',kmh:Math.round(s.v*3.6),air:!!s.air};
  const tyres=[];{const n=f.u.clone().normalize(),cand=[],v=new THREE.Vector3();s.mesh.traverse(w=>{if(w.isMesh&&!w.isInstancedMesh&&visOk(w)&&w.geometry&&!(w.material&&w.material.transparent)&&w!==s.mesh.userData.under){w.geometry.computeBoundingBox();const sz=w.geometry.boundingBox.getSize(new THREE.Vector3());const sc=new THREE.Vector3();w.matrixWorld.decompose(new THREE.Vector3(),new THREE.Quaternion(),sc);sz.multiply(sc);const h=sz.y;if(h>.5&&h<1.6&&Math.max(sz.x,sz.z)<2.2){
     // lowest real vertex toward the road normal (not the rotated bounding box: on an 8–11° bank its corner reads ~0.2 m low)
     const P=w.geometry.attributes.position;let best=null,bd=1e9;for(let i=0;i<P.count;i++){v.fromBufferAttribute(P,i).applyMatrix4(w.matrixWorld);const d=v.dot(n);if(d<bd){bd=d;best=v.clone()}}cand.push({p:best,d:bd})}}});
   if(cand.length>=4){const lo=Math.min(...cand.map(c=>c.d));for(const c of cand.filter(c=>c.d<lo+.15).slice(0,6))tyres.push(c.p)}}
  const body=new THREE.Box3(),bb=new THREE.Box3();s.mesh.traverse(o=>{if(o.isMesh&&visOk(o)&&o.geometry&&!(o.material&&o.material.transparent)){o.geometry.computeBoundingBox();bb.copy(o.geometry.boundingBox).applyMatrix4(o.matrixWorld);body.union(bb)}});
  const ctr=body.getCenter(new THREE.Vector3());const C=cand(ctr,40);
  const down=(p)=>{const nn=f.u.clone().normalize();R.set(p.clone().addScaledVector(nn,.6),nn.clone().negate());R.far=3;const h=R.intersectObjects(C,false).find(h=>!h.face||h.face.normal.clone().transformDirection(h.object.matrixWorld).y>.4);if(h&&h.distance-.6<-.05&&window.__r17diag){const o=h.object,m=Array.isArray(o.material)?o.material[0]:o.material;window.__r17low=(window.__r17low||[]).slice(-5).concat([[+(h.distance-.6).toFixed(3),o.name||o.type,o.isInstancedMesh?'inst':'',m&&m.color?m.color.getHexString():'',m&&m.map?'tex':'',+(o.geometry.boundingBox?o.geometry.boundingBox.getSize(new THREE.Vector3()).y:0).toFixed(2),o.parent&&(o.parent.name||o.parent.type)]])}return h?+(h.distance-.6).toFixed(3):null};
  const plane=q=>{const rel=q.clone().sub(f.p);const lat=rel.dot(f.r);return +(q.y-(f.p.y+f.r.y*lat+f.t.y*rel.dot(f.t))).toFixed(3)};if(tyres.length){out.mode='tyre';out.g=tyres.slice(0,6).map(down);out.gp=tyres.slice(0,6).map(plane)}else{out.mode='hull';out.g=[down(new THREE.Vector3(ctr.x,body.min.y,ctr.z))]}
  let hw=s._r17hw;if(!hw){const inv=s.mesh.matrixWorld.clone().invert(),lb=new THREE.Box3(),m4=new THREE.Matrix4();s.mesh.traverse(o=>{if(o.isMesh&&visOk(o)&&o.geometry&&!(o.material&&o.material.transparent)){bb.copy(o.geometry.boundingBox).applyMatrix4(m4.multiplyMatrices(inv,o.matrixWorld));lb.union(bb)}});const sc=new THREE.Vector3();s.mesh.matrixWorld.decompose(new THREE.Vector3(),new THREE.Quaternion(),sc);hw=s._r17hw=(lb.max.x-lb.min.x)/2*sc.x}
  const r=new THREE.Vector3(f.r.x,0,f.r.z).normalize();const o0=ctr.clone();o0.y=body.min.y+.7;const side=d=>{R.set(o0,d);R.far=40;const h=R.intersectObjects(C,false).find(h=>!h.face||Math.abs(h.face.normal.clone().transformDirection(h.object.matrixWorld).y)<.6);return h?h.distance:99};
  const dl=side(r.clone().negate()),dr=side(r);out.wall=+(Math.min(dl,dr)-hw).toFixed(2);out.hw=+hw.toFixed(2);out.x=+s.x.toFixed(1);if(window.__r17diag){const ud=s.mesh.userData;const u=new THREE.Vector3(0,1,0).transformDirection(ud.m.matrixWorld),fz=new THREE.Vector3(0,0,-1).transformDirection(ud.m.matrixWorld);out.d={yaw:+s.yaw.toFixed(3),beta:+s.beta.toFixed(3),pitch:+(Math.asin(fz.dot(f.u))*57.3).toFixed(1),roll:+(Math.asin(u.clone().cross(fz).normalize().dot(f.u))*57.3).toFixed(1),upAng:+(Math.acos(Math.min(1,u.dot(f.u)))*57.3).toFixed(1),mpos:+ud.m.position.length().toFixed(2),nitro:!!s.nitro,boatK:+(s.boatK||0).toFixed(2),fry:+f.r.y.toFixed(3),fty:+f.t.y.toFixed(3),k:+(1/(Math.abs(f.k)+1e-6)).toFixed(0)}}return out};
 const W=${JSON.stringify(who)};const P=W==='pl'?[pl]:W==='all'?[pl,...ships.filter(o=>!o.isPlayer).sort((a,b)=>Math.abs(a.dist-pl.dist)-Math.abs(b.dist-pl.dist)).slice(0,2)]:[pl];return P.map(one)})()`)})})()`;
