// review.js <outprefix> : full reviewer shot set on the phone layout (852x393 touch) + tyre gaps (player + 5 traffic cars)
const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const OUT=process.argv[2];const br=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const ctx=await br.newContext({viewport:{width:852,height:393},deviceScaleFactor:2,isMobile:true,hasTouch:true});const p=await ctx.newPage();p.setDefaultTimeout(500000);
const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,150)));const R={};
const boot=async(city)=>{await p.evaluate(c=>{localStorage.clear();localStorage.setItem('mho_slot','1');localStorage.setItem('mho_athpre','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));if(c==='ath')localStorage.setItem('mho_city@1','ath')},city);await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{polling:500})};
const roam=async()=>{await p.evaluate(()=>{try{__m1&&__m1.skip&&__m1.skip()}catch(e){}__mho.enterRoam()});await p.waitForFunction(()=>__mho.state==='roam');await p.evaluate(()=>__mho.storyClose&&__mho.storyClose());await p.waitForTimeout(2500)};
const kmh=()=>p.evaluate(()=>(document.querySelector('#roamGauge b')||{}).textContent||'?');
const setup=()=>p.evaluate(()=>{const {scene,camera,THREE}=__dbg;const W={};window.__rv=W;
 W.skip=()=>{const S=new Set();scene.traverse(o=>{if(o.isInstancedMesh&&o.userData.w){S.add(o);S.add(o.userData.w)}if(o.userData&&o.userData.gbV)o.traverse(q=>S.add(q))});return S};
 W.list=()=>{const S=W.skip(),L=[];scene.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&o.visible&&o.geometry&&o.geometry.attributes.position&&o.material&&!o.material.transparent&&!S.has(o))L.push(o)});return L};
 W.ground=(L,pt)=>{const rc=new THREE.Raycaster();rc.camera=camera;rc.set(pt.clone().add(new THREE.Vector3(0,3,0)),new THREE.Vector3(0,-1,0));const hs=[];for(const o of L){try{rc.intersectObject(o,false,hs)}catch(e){}}hs.sort((a,b)=>a.distance-b.distance);return hs[0]?hs[0].point.y:null};
 W.car=()=>{let c=null;scene.traverse(o=>{if(!c&&o.userData&&o.userData.gbV)c=o});return c};
 W.cam=(pos,look)=>{scene.onBeforeRender=()=>{camera.position.copy(pos);camera.lookAt(look);camera.updateMatrixWorld();camera.matrixWorldInverse.copy(camera.matrixWorld).invert()}};
 W.free=()=>{scene.onBeforeRender=()=>{}};
 W.player=()=>{const L=W.list(),car=W.car(),out=[];car.traverse(o=>{if(o.isMesh&&o.userData.r){let v=true,q=o;while(q){if(!q.visible)v=false;q=q.parent}if(!v)return;const c=new THREE.Vector3();o.getWorldPosition(c);const s=new THREE.Vector3();o.getWorldScale(s);const g=W.ground(L,c);out.push(g==null?null:+(c.y-o.userData.r*s.y-g).toFixed(3))}});
  const cp=new THREE.Vector3();car.getWorldPosition(cp);const fw=new THREE.Vector3();camera.getWorldDirection(fw);fw.y=0;fw.normalize();const sd=new THREE.Vector3(-fw.z,0,fw.x),c0=cp.clone().addScaledVector(sd,4.5);const gy=__dbg.GY(cp.x,cp.z),gc=__dbg.GY(c0.x,c0.z);
  W.cam(c0.setY(Math.max(gy,gc)+.54),new THREE.Vector3(cp.x,gy+.5,cp.z));return out};
 W.traffic=()=>{const L=W.list(),M=new THREE.Matrix4(),P=new THREE.Vector3(),C=[];scene.traverse(o=>{if(o.isInstancedMesh&&o.userData.w){const w=o.userData.w;w.geometry.computeBoundingBox();for(let j=0;j<o.count;j++){w.getMatrixAt(j,M);if(M.elements[0]===0&&M.elements[5]===0)continue;P.setFromMatrixPosition(M);C.push({w,j,p:P.clone(),mb:w.geometry.boundingBox.min.y,d:P.distanceTo(camera.position)})}}});
  C.sort((a,b)=>a.d-b.d);const top=C.slice(0,5),gaps=top.map(c=>{c.w.getMatrixAt(c.j,M);const bb=c.w.geometry.boundingBox,ins=.35,pts=[[bb.min.x+ins,bb.min.z+.6],[bb.max.x-ins,bb.min.z+.6],[bb.min.x+ins,bb.max.z-.6],[bb.max.x-ins,bb.max.z-.6]];
   return pts.map(([lx,lz])=>{const wp=new THREE.Vector3(lx,bb.min.y,lz).applyMatrix4(M);const rc=new THREE.Raycaster();rc.set(wp.clone().add(new THREE.Vector3(0,.6,0)),new THREE.Vector3(0,-1,0));const hs=[];for(const o of L){try{rc.intersectObject(o,false,hs)}catch(e){}}hs.sort((a,b)=>a.distance-b.distance);const h=hs[0];
    const g=h?+(wp.y-h.point.y).toFixed(3):null;return Math.abs(g)>.05&&h?g+' ['+(h.object.name||h.object.geometry.type)+' v'+h.object.geometry.attributes.position.count+' ny'+(h.face?h.face.normal.y.toFixed(2):'')+' road'+(h.point.y-__dbg.GY(wp.x,wp.z)).toFixed(2)+']':g})});
  // pick the nearest car with a clear line of sight from a camera 4 m to its side, 0.5 m above the road
  const rc=new THREE.Raycaster();rc.camera=camera;const camFor=c=>{c.w.getMatrixAt(c.j,M);const rt=new THREE.Vector3(M.elements[0],0,M.elements[2]).normalize();const q=new THREE.Vector3().setFromMatrixPosition(M);const cp=q.clone().addScaledVector(rt,4);cp.y=Math.max(__dbg.GY(cp.x,cp.z),__dbg.GY(q.x,q.z))+.54;return{cp,q}};
  let T=top[0];for(const c of C.slice(0,25)){const {cp,q}=camFor(c);const tgt=q.clone().setY(q.y+.5);const dir=tgt.clone().sub(cp);const dist=dir.length();rc.set(cp,dir.normalize());rc.far=dist;let hs=[];try{hs=rc.intersectObjects(scene.children,true).filter(h=>h.object.visible&&!h.object.isSprite&&h.object.material&&!h.object.material.transparent)}catch(e){continue}
   const first=hs[0];if(first&&first.object.userData&&(first.object.userData.w===c.w||first.object===c.w)&&first.instanceId===c.j){T=c;break}if(!first||first.distance>dist-1.6){T=c;break}}
  const Q=new THREE.Vector3();scene.onBeforeRender=()=>{const {cp,q}=camFor(T);camera.position.copy(cp);camera.lookAt(q.x,q.y+.45,q.z);camera.updateMatrixWorld();camera.matrixWorldInverse.copy(camera.matrixWorld).invert()};
  return {gaps,n:C.length}}});
await p.goto('http://127.0.0.1:8766/local_dbg.html');await boot('fra');await p.waitForTimeout(1500);await p.screenshot({path:OUT+'_1start.png'});
await roam();await setup();await p.keyboard.down('ArrowUp');await p.waitForTimeout(6000);R.fraKmh=await kmh();await p.screenshot({path:OUT+'_2fra_drive.png'});await p.keyboard.up('ArrowUp');await p.keyboard.down('ArrowDown');await p.waitForTimeout(500);R.playerBraking=await p.evaluate(()=>{const g=__rv.player();__rv.free();return g});await p.keyboard.up('ArrowDown');await p.waitForTimeout(3500);
R.player=await p.evaluate(()=>__rv.player());await p.waitForTimeout(1200);await p.screenshot({path:OUT+'_3player_side.png'});await p.evaluate(()=>__rv.free());
R.traffic=await p.evaluate(()=>__rv.traffic());await p.waitForTimeout(1200);await p.screenshot({path:OUT+'_4traffic_side.png'});await p.evaluate(()=>__rv.free());
await p.evaluate(()=>document.querySelector('#roamPause [data-p="garage"]')?.click()||__mho.pause?.());await p.waitForTimeout(600);
await p.waitForFunction(()=>!document.querySelector('#gbx').hidden,null,{timeout:8000}).catch(async()=>{await p.keyboard.press('Escape');await p.waitForTimeout(500);await p.evaluate(()=>document.querySelector('#roamPause [data-p="garage"]').click());await p.waitForFunction(()=>!document.querySelector('#gbx').hidden)});
await p.waitForTimeout(1200);await p.screenshot({path:OUT+'_5garage.png'});
await boot('ath');await roam();await p.keyboard.down('ArrowUp');await p.waitForTimeout(6000);R.athKmh=await kmh();R.tutGap=await p.evaluate(()=>{const t=document.getElementById('roamTut');if(!t||!t.getClientRects().length)return 'no tut';const tr=t.getBoundingClientRect();let m=1e9;for(const e of document.querySelectorAll('.tbtn,button')){if(!e.getClientRects().length||e.closest('#roamTut'))continue;const r=e.getBoundingClientRect();if(r.bottom<tr.top||r.top>tr.bottom)continue;const g=r.right<=tr.left?tr.left-r.right:r.left>=tr.right?r.left-tr.right:-1;m=Math.min(m,g)}return m});await p.screenshot({path:OUT+'_6ath_drive.png'});await p.keyboard.up('ArrowUp');await p.waitForTimeout(3000);await setup();R.athTraffic=await p.evaluate(()=>__rv.traffic());await p.waitForTimeout(1200);await p.screenshot({path:OUT+'_7ath_traffic_side.png'});await p.evaluate(()=>__rv.free());
console.log(JSON.stringify(R));console.log('errs',JSON.stringify(errs));await br.close()})();
