// tRoute24.js: mission route quality (drive24). Generates 10 routes per mission type exactly the way the game does
// (qvLayout stage lists → the GPS path qvPath between stages; chase van / escort car / M1 follow + tail vehicle paths), then measures
// turns per km, min distance between turns, turns < 80 m apart, sharp turns (> 70°), U-turns, zig-zags. Optional: a JSON dump of the paths.
// Each GPS leg (one qvPath call = one stop to the next) is measured on its own; a followed vehicle's whole path is one route.
// usage: node tools/tRoute24.js <url-of-local_dbg.html> <out.json> [city=fra]
const fs=require('fs');const{chromium,boot,routeStats,agg}=require('./d24lib');
const URL=process.argv[2],OUT=process.argv[3]||'qa24/route.json',CITY=process.argv[4]||'fra';
(async()=>{const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const{p,errs}=await boot(b,{city:CITY,url:URL});
 if(process.env.TUNE)await p.evaluate(t=>__g9ev('Object.assign(TUNE,'+t+')'),process.env.TUNE);
 const R=await p.evaluate(()=>__g9ev(`(()=>{const G=qvGraph();const rng=mul(4242);const out={};const pick=()=>{for(;;){const i=G.list[Math.floor(rng()*G.list.length)];const x=G.X[i],z=G.Z[i];if(!inRiver(x,z,-3)&&!roamHit(x,z,3))return{x,z}}};
  const kinds=['taxi','deliver','chase','checkpoint','race','speed','escort','photo','collect','wall'];
  for(const k of kinds){out[k]=[];for(let n=0;n<10;n++){const O=pick();const e={id:'d24'+k+n,kind:k,npc:'X',name:'t'};let L;try{L=qvLayout(e,1000+n*7,O)}catch(er){out[k].push({err:String(er)});continue}
    let P=[],prev=O;if(k==='chase'){const S=L.st[0],a=qvNear(O.x+300,O.z,400);const sx=a>=0?G.X[a]:O.x,sz=a>=0?G.Z[a]:O.z;P=qvPath(sx,sz,S.x,S.z)}
    else if(k==='escort'){const S=L.st.find(s=>s.t==='escort');P=qvPath(S.fx,S.fz,S.x,S.z)}
    else{let h0;for(const S of L.st){if(S.x==null)continue;const q=qvPath(prev.x,prev.z,S.x,S.z,h0);if(q.length>1){const a=q[q.length-2],b=q[q.length-1];h0=Math.atan2(b[0]-a[0],b[1]-a[1])}if(q.length>1&&qvCum(q).slice(-1)[0]>150)out[k].push(q.map(a=>[+a[0].toFixed(1),+a[1].toFixed(1)]));prev=S}continue}
    out[k].push(P.map(a=>[+a[0].toFixed(1),+a[1].toFixed(1)]))}}
  // followed vehicles (M1 follow / tail): the authored Hot Drop routes + 10 random 3-leg routes through 600-900 m waypoints
  out.follow=[];if(CID==='fra'){const D=M1_DEF.hotdrop;const c={st:[],O:{x:0,z:0}};D.build(c);for(const S of c.st){if(S.t==='follow')out.follow.push(M1_path(S.pts.map(p=>M1_P(p.x,p.z))).P.map(a=>[+a[0].toFixed(1),+a[1].toFixed(1)]));
    if(S.t==='tail')out.follow.push(M1_path([{x:S.via[0].x+60,z:S.via[0].z},...S.via,S.to].map(p=>M1_P(p.x,p.z))).P.map(a=>[+a[0].toFixed(1),+a[1].toFixed(1)]))}}
  while(out.follow.length<10){const a=pick();const pts=[a];for(let k=0;k<3;k++){const q=pts[pts.length-1];let best=null;for(let t=0;t<30;t++){const c=pick(),d=Math.hypot(c.x-q.x,c.z-q.z);if(d>600&&d<900){best=c;break}}if(best)pts.push(best)}
    out.follow.push(M1_path(pts.map(p=>M1_P(p.x,p.z))).P.map(a=>[+a[0].toFixed(1),+a[1].toFixed(1)]))}
  return out})()`));
 const tab={};let all=[];for(const[k,L]of Object.entries(R)){const st=L.filter(P=>Array.isArray(P)&&P.length>1).map(routeStats);all=all.concat(st);tab[k]=agg(st)}tab.ALL=agg(all);
 fs.mkdirSync(require('path').dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({city:CITY,tab,paths:R}));
 console.log('kind        routes km   turns/km minGap medMinGap <80m sharp/km U zig');for(const[k,t]of Object.entries(tab))console.log(k.padEnd(11),String(t.routes).padStart(3),String(t.km).padStart(5),String(t.turnsPerKm).padStart(8),String(t.minGap).padStart(6),String(t.medMinGap).padStart(8),String(t.close80).padStart(5),String(t.sharpPerKm).padStart(8),String(t.uturns).padStart(3),String(t.zigzags).padStart(4));
 if(process.env.PLOT){const n=+process.env.PLOT;const{routeStats}=require('./d24lib');const all=[].concat(...Object.values(R)).filter(P=>Array.isArray(P)&&P.length>1).map(P=>({P,s:routeStats(P)})).sort((a,b)=>(b.s.uturn*3+b.s.zig+b.s.close80)-(a.s.uturn*3+a.s.zig+a.s.close80));const L=all.slice(0,n).map(o=>o.P);console.log('worst',all.slice(0,n).map(o=>JSON.stringify(o.s)).join('\n'));for(let i=0;i<L.length;i++){const P=L[i];await p.evaluate(([P])=>__g9ev(`(()=>{const P=${JSON.stringify(P)};const G=qvGraph();let x0=1e9,x1=-1e9,z0=1e9,z1=-1e9;for(const[x,z]of P){x0=Math.min(x0,x);x1=Math.max(x1,x);z0=Math.min(z0,z);z1=Math.max(z1,z)}const pad=60;x0-=pad;x1+=pad;z0-=pad;z1+=pad;const W=1400,S=W/Math.max(x1-x0,z1-z0);let c=document.getElementById('d24c');if(!c){c=document.createElement('canvas');c.id='d24c';c.style.cssText='position:fixed;left:0;top:0;z-index:99999;background:#fff';document.body.appendChild(c)}c.width=W;c.height=W;c.style.width='852px';c.style.height='852px';const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,W,W);const T=(x,z)=>[(x-x0)*S,(z1-z)*S];g.strokeStyle='#bbb';g.lineWidth=1;g.beginPath();for(let i=0;i<G.n;i++){if(G.X[i]<x0||G.X[i]>x1||G.Z[i]<z0||G.Z[i]>z1)continue;for(let e=G.off[i];e<G.off[i+1];e++){const j=G.nb[e];if(j<i)continue;g.moveTo(...T(G.X[i],G.Z[i]));g.lineTo(...T(G.X[j],G.Z[j]))}}g.stroke();g.strokeStyle='#e00';g.lineWidth=3;g.beginPath();g.moveTo(...T(...P[0]));for(const q of P)g.lineTo(...T(...q));g.stroke();g.fillStyle='#0a0';g.beginPath();g.arc(...T(...P[0]),8,0,7);g.fill()})()`),[P]);await p.setViewportSize({width:852,height:852});await p.locator('#d24c').screenshot({path:OUT.replace('.json','_plot'+i+'.png')})}}
 console.log('errors',errs.length,errs.slice(0,3));await b.close()})();
