// tW12.js (paint probe; harness copied from tW11.js) — worker 11 evidence probe (same start/harness as tW10: real CDP touch on #tG/#tB/#tL/#tR, test-driven rAF clock).
// usage: FAST=1 node tools/tW11.js <url local_dbg.html> <outdir>   env TEST=wall|tyre|turn|slalom|side|all (default all)
// wall:   car placed 12 m from a building wall (setup only), then real GAS held: drive in, keep GAS 5 s after contact. Reports time pinned, UNSTUCK, freed (≥4 m from contact and > 8 km/h).
// tyre:   per-tyre clearance after a REAL render (wheel clamp runs in onBeforeRender): tyre bottom (wheel centre − r·scale) − ground under that tyre
//         (gnd ray from 0.6 m above the tyre, and a THREE ray against the visible road meshes). Player at rest, at 60 km/h, and after a stop.
// turn:   90° right turn at a city junction (real ▶ touch), 6-frame strip; slip = |h−vh|, camera lag = time camera yaw trails car yaw at 45°.
// slalom: Autobahn straight, ◀/▶ alternating every 0.8 s at ~70 km/h, 6-frame strip; max slip.
// side:   low side view aimed at the PLAYER car with a traffic car ahead in the same lane, same direction.
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const fs=require('fs');const path=require('path');const {execSync}=require('child_process');
const src=fs.readFileSync(path.join(__dirname,'tPlay.js'),'utf8');const INIT=eval('`'+/const INIT=`([\s\S]*?)`;/.exec(src)[1]+'`');
const FASTM=process.env.FAST==='1',URL0=process.argv[2]||'http://127.0.0.1:8766/local_dbg.html',URL=FASTM&&!/fast=1/.test(URL0)?URL0+(URL0.includes('?')?'&':'?')+'fast=1':URL0;
const OUT=process.argv[3]||'qa_w12';fs.mkdirSync(OUT,{recursive:true});const TEST=process.env.TEST||'all',has=t=>TEST==='all'||TEST.split(',').includes(t);
(async()=>{const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
 const ctx=await b.newContext({viewport:{width:852,height:393},deviceScaleFactor:3,isMobile:true,hasTouch:true});
 const p=await ctx.newPage();p.setDefaultTimeout(900000);const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,200)));p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text().slice(0,200))});
 await p.addInitScript(INIT);const cdp=await ctx.newCDPSession(p);let SYN=Date.now()/1000;if(FASTM){const s0=cdp.send.bind(cdp);cdp.send=(m,o)=>s0(m,m==='Input.dispatchTouchEvent'?{...o,timestamp:SYN}:o)}
 const tick=n=>{if(FASTM)SYN+=n/60;return p.evaluate(n=>__tick(n),n)};
 const F={};const pts=()=>Object.values(F).map(f=>({x:f.x,y:f.y,id:f.id,radiusX:6,radiusY:6,force:1}));
 const center=sel=>p.evaluate(s=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect();if(r.width<4)return null;for(let a=e;a;a=a.parentElement)if(a.hidden)return null;if(getComputedStyle(e).display==='none')return null;return[r.left+r.width/2,r.top+r.height/2]},sel);
 const send=()=>cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts()});
 const down=async(n,xy)=>{if(!xy)return false;let id=0;while(Object.values(F).some(o=>o.id===id))id++;F[n]={x:xy[0],y:xy[1],id};await send();return true};
 const up=async n=>{if(!F[n])return;delete F[n];const P=pts();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});if(P.length){SYN+=.44;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:P})}};
 const tap=async s=>{const xy=await center(s);if(!xy)return false;await down('tap',xy);await tick(4);await up('tap');await tick(4);return true};
 const ctl={gas:false,brake:false,L:false,R:false};
 async function apply(c){c={...ctl,...c};for(const [k,sel] of [['gas','#tG'],['brake','#tB'],['L','#tL'],['R','#tR']])if(c[k]!==ctl[k]){if(c[k])await down(k,await center(sel));else await up(k)}Object.assign(ctl,c)}
 const render=async()=>p.evaluate(()=>{window.__shooting=1;if(window.__fastR){__dbg.composer.render=window.__fastR;window.__fastR=null}__tick(1)});
 const unrender=async()=>p.evaluate(()=>{window.__shooting=0;if(!window.__fastR){window.__fastR=__dbg.composer.render;__dbg.composer.render=()=>{}}});
 const shot=async name=>{await render();const f=path.join(OUT,name+'.jpg');await p.screenshot({path:f,type:'jpeg',quality:75});await unrender();return f};
 // ---- start like a player
 await p.goto(URL);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{polling:500});
 await p.evaluate(()=>{localStorage.clear();localStorage.setItem('mho_slot','1')});await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{polling:500});
 await tap('#hcStory');await tick(10);await tap('#slotList .go');
 for(let i=0;i<150;i++){if(await p.evaluate(()=>window.__mho&&__mho.state==='roam'))break;await p.waitForTimeout(2000)}await p.evaluate(()=>{window.__auto=false});
 const CONT=['#storyGo','#m1Cs','#rcGo','#ogRetryB','#setDone','.m1go','#resBtn','#tutSkip'];
 for(let i=0;i<30;i++){await tick(30);let t=null;for(const s of CONT)if(await tap(s)){t=s;break}if(!t)break}
 await tap('#tG');await tick(2);
 await p.evaluate(()=>{window.__L=[];window.__mon=()=>{if(!window.__logOn)return;const R=__mho.RO,c=__dbg.camera,d=new __dbg.THREE.Vector3();c.getWorldDirection(d);
  __L.push({h:R.h,vh:R.vh??R.h,v:R.v,x:R.x,z:R.z,y:R.y,st:R.stkT||0,cy:Math.atan2(d.x,d.z),msg:(document.querySelector('#msg')||{}).textContent||''})}});
 const busy=()=>p.evaluate(()=>{const R=__mho.RO;return!!(R.card||R.mapOpen||R.story||R.frozen)});
 async function clear(){for(let i=0;i<10;i++){if(!(await busy()))return;for(const s of CONT)if(await tap(s))break;await tick(20)}}
 const place=async(x,z,h,v=0)=>{await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+30);R.v=0;R.yr=0;R.vh=h;R.h=h;R.stkT=0;R.crTurn=null},[x,z,h]);await tick(30);await clear();await p.evaluate(([x,z,h,v])=>{const R=__mho.RO;R.x=x;R.z=z;R.h=R.vh=h;R.v=v;R.yr=0;R.stkT=0},[x,z,h,v]);await tick(2)};
 const log=async on=>{await p.evaluate(on=>{window.__logOn=on;if(on)window.__L=[]},on);if(!on)return p.evaluate(()=>__L)};

 await apply({gas:true});await tick(120);await apply({gas:false});await tick(60);const S0=await p.evaluate(()=>{const R=__mho.RO;return{x:R.x,z:R.z,h:R.h}});await place(S0.x,S0.z,S0.h);await tick(30);
 const EV=s=>p.evaluate(s=>__oc.ev(s),s);
 console.log('MATS',JSON.stringify(await EV(`(()=>{const o=[];pl.mesh.traverse(m=>{if(!m.isMesh)return;for(const t of[].concat(m.material)){const c=m.geometry.attributes.color,cols=new Set();if(c)for(let i=0;i<c.count;i+=Math.max(1,c.count/200|0))cols.add([c.getX(i),c.getY(i),c.getZ(i)].map(v=>v.toFixed(2)).join(','));o.push({n:m.name,type:t.type,id:t.id,cc:t.clearcoat,rough:t.roughness,env:t.envMapIntensity,hasEnv:!!t.envMap,em:t.emissive&&t.emissive.getHexString(),vc:t.vertexColors,col:t.color&&t.color.getHexString(),cols:[...cols].slice(0,6),obc:!!t.onBeforeCompile&&String(t.onBeforeCompile).slice(0,120)})}});return{tm:renderer.toneMapping,exp:renderer.toneMappingExposure,ei:scene.environmentIntensity,ocs:renderer.outputColorSpace,mats:o}})()`)));
 // camera: low 3/4 side view of the player car
 const cam=async()=>{await render();await p.evaluate(()=>{const M=__mho,R=M.RO,D=__dbg,sx=Math.cos(R.h),sz=-Math.sin(R.h),fx=Math.sin(R.h),fz=Math.cos(R.h),g=M.gnd(R.x,R.z,R.y+.3);D.camera.position.set(R.x+sx*4.2+fx*2.2,g+1.3,R.z+sz*4.2+fz*2.2);D.camera.lookAt(R.x,g+.55,R.z);D.camera.updateMatrixWorld();D.composer.render();window.__cp=[D.camera.position.toArray(),R.x,R.z]});console.log('CAM',JSON.stringify(await p.evaluate(()=>[window.__cp,__dbg.camera.position.toArray()])))};
 const box=()=>EV(`(()=>{const T=__dbg.THREE,B=new T.Box3().setFromObject(pl.mesh),c=__dbg.camera,pts=[];for(const x of[B.min.x,B.max.x])for(const y of[B.min.y,B.max.y])for(const z of[B.min.z,B.max.z]){const v=new T.Vector3(x,y,z).project(c);pts.push([(v.x+1)/2*innerWidth,(1-v.y)/2*innerHeight])}return[Math.min(...pts.map(q=>q[0])),Math.min(...pts.map(q=>q[1])),Math.max(...pts.map(q=>q[0])),Math.max(...pts.map(q=>q[1]))]})()`);
 // recolour the dominant body colour (test only): vertex colours equal to the current body colour → target sRGB hex
 const paint=hex=>EV(`(()=>{const T=__dbg.THREE,C=new T.Color('${hex}');let n=0;window.__body=window.__body||null;pl.mesh.traverse(m=>{if(!m.isMesh||!m.geometry.attributes.color)return;const a=m.geometry.attributes.color;if(!window.__body){const h={};for(let i=0;i<a.count;i++){const k=[a.getX(i),a.getY(i),a.getZ(i)].map(v=>v.toFixed(3)).join(',');h[k]=(h[k]||0)+1}}});
   if(!window.__body){const h={};pl.mesh.traverse(m=>{if(!m.isMesh||!m.geometry.attributes.color)return;const a=m.geometry.attributes.color;for(let i=0;i<a.count;i++){const r=a.getX(i),g=a.getY(i),b=a.getZ(i);if(Math.max(r,g,b)-Math.min(r,g,b)<.15)continue;const k=[r,g,b].map(v=>v.toFixed(3)).join(',');h[k]=(h[k]||0)+1}});window.__body=Object.keys(h).sort((x,y)=>h[y]-h[x])[0].split(',').map(Number);window.__cur=window.__body.slice()}
   const B=window.__cur;pl.mesh.traverse(m=>{if(!m.isMesh||!m.geometry.attributes.color)return;const a=m.geometry.attributes.color;let ch=0;for(let i=0;i<a.count;i++){if(Math.abs(a.getX(i)-B[0])+Math.abs(a.getY(i)-B[1])+Math.abs(a.getZ(i)-B[2])<.01){a.setXYZ(i,C.r,C.g,C.b);n++;ch=1}}if(ch)a.needsUpdate=true});window.__cur=[C.r,C.g,C.b];return{n,body:window.__body}})()`);
 const OUT2=OUT;const res={};
 const close=async()=>{await render();await p.evaluate(()=>{const M=__mho,R=M.RO,D=__dbg,sx=Math.cos(R.h),sz=-Math.sin(R.h),fx=Math.sin(R.h),fz=Math.cos(R.h),g=M.gnd(R.x,R.z,R.y+.3);D.camera.position.set(R.x+sx*3.6+fx*.8,g+.6,R.z+sz*3.6+fz*.8);D.camera.lookAt(R.x+fx*.8,g+.5,R.z+fz*.8);D.camera.updateMatrixWorld();D.composer.render()})};
 const sample=async(name)=>{await close();const bb=[852*.45,393*.41,852*.8,393*.5];const f=path.join(OUT2,name+'.png');await p.screenshot({path:f});await unrender();
   // median colour of saturated pixels inside the car box (device px = css*3)
   const k=3,x0=Math.max(0,bb[0]*k|0),y0=Math.max(0,bb[1]*k|0),w=Math.min(852*k-x0,(bb[2]-bb[0])*k|0),h=Math.min(393*k-y0,(bb[3]-bb[1])*k|0);
   const txt=execSync(`convert ${f} -crop ${w}x${h}+${x0}+${y0} -scale 25% -depth 8 txt:- | tail -n +2`,{maxBuffer:1e8}).toString().trim().split('\n');
   return{f,bb,txt}};


 if(process.env.GAR){await p.evaluate(()=>window.__gb.enter());await tick(60);await render();await p.screenshot({path:path.join(OUT,'garage.jpg'),type:'jpeg',quality:80});await unrender();console.log('GAR',JSON.stringify(errs));await b.close();return}
 if(process.env.RIB){const r=await EV(`(()=>{const T=__dbg.THREE,rc=new T.Raycaster(),cand=[];scene.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&o.geometry&&o.geometry.attributes.position&&!(o.userData&&o.userData.trG)){if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();const b=o.geometry.boundingBox;const m=[].concat(o.material)[0];if(m&&m.map&&m.map.wrapS===T.ClampToEdgeWrapping&&m.polygonOffset&&(b.max.x-b.min.x>100||b.max.z-b.min.z>100))cand.push(o)}});
   const out=[];let rnd=1;const R=()=>(rnd=rnd*16807%2147483647)/2147483647;const S0=abSamples();const PT=${process.env.PT||'null'};for(let k=0;k<(PT?PT.length:600);k++){let x,z,S;if(PT){[x,z]=PT[k];S=abAt(x,z).S}else{S=S0[Math.floor(R()*S0.length)];if(!S.r.ab)continue;const p=S.pts[Math.floor(R()*S.pts.length)];if(abSkip(p.x,p.z))continue;const o=(R()*2-1)*(S.r.w/2-1);x=p.x+p.tz*o;z=p.z-p.tx*o}const g=groundY(x,z);
    rc.set(new T.Vector3(x,g+3,z),new T.Vector3(0,-1,0));rc.far=6;const h=rc.intersectObjects(cand,false);if(!h.length){out.push({x,z,miss:1});continue}const gm=[];scene.traverse(o=>{});const top=h[0];const pa=top.object.geometry.attributes.position,mw=top.object.matrixWorld;let vb=null,vd=1e9;const v=new T.Vector3();for(let q=0;q<pa.count;q++){v.fromBufferAttribute(pa,q).applyMatrix4(mw);const dd=(v.x-x)**2+(v.z-z)**2;if(dd<vd){vd=dd;vb=[+(v.y-groundY(v.x,v.z)).toFixed(3),+Math.sqrt(dd).toFixed(1)]}}const G2=[];if(!window.__trg){window.__trg=[];scene.traverse(o=>{if(o.isMesh&&o.userData&&o.userData.trG)window.__trg.push(o)})}const gh=rc.intersectObjects(window.__trg,false);out.push({gr:gh.length?+(gh[0].point.y-top.point.y).toFixed(3):null,vb,x:+x.toFixed(0),z:+z.toFixed(0),id:S.r.id,c:S.r.c?1:0,d:+(top.point.y-g).toFixed(3),gs:+(groundAt(x,z,g+1)-g).toFixed(3)})}
   const d=out.filter(q=>!q.miss).map(q=>q.d).sort((a,b)=>a-b);return JSON.stringify({tri:ART8.tri.ab,w12:typeof W12_ST!=='undefined'?W12_ST:null,grassAbove:out.filter(q=>q.gr!=null&&q.gr>-0.01).length,grassMax:Math.max(...out.filter(q=>q.gr!=null).map(q=>q.gr)),cand:cand.length,n:d.length,miss:out.filter(q=>q.miss).length,min:d[0],p5:d[d.length*.05|0],med:d[d.length>>1],p95:d[d.length*.95|0],max:d[d.length-1],worst:out.filter(q=>!q.miss).sort((a,b)=>Math.abs(b.d-.06)-Math.abs(a.d-.06)).slice(0,6)})})()`);console.log('RIB',r);await b.close();return}
 if(process.env.DBG){console.log('DBG',await EV(`(()=>{const o=[];pl.mesh.traverse(m=>{if(m.isMesh)for(const t of[].concat(m.material))o.push([t.type,!!t.userData.w12,t.customProgramCacheKey().slice(-30),String(t.onBeforeCompile).slice(0,60), (renderer.properties.get(t).currentProgram||{}).cacheKey?.slice(-40)])});return JSON.stringify(o.slice(0,8))})()`));}
 if(process.env.VAR){await paint('#d01712');const SET=(e,c)=>`pl.mesh.traverse(o=>{if(o.isMesh)[].concat(o.material).forEach(m=>{if(m.envMapIntensity!==undefined){if(m.userData.a10e!==undefined)m.userData.a10e=${e};m.envMapIntensity=${e}}if(m.isMeshPhysicalMaterial&&m.clearcoat>0)m.clearcoat=${c}})});ART10.mats.forEach(m=>{if(m.userData.a10e!==undefined&&!m.vertexColors){}})`;
  const V={base:''};
  const close0=async()=>{await render();await p.evaluate(()=>{const M=__mho,R=M.RO,D=__dbg,sx=Math.cos(R.h),sz=-Math.sin(R.h),fx=Math.sin(R.h),fz=Math.cos(R.h),g=M.gnd(R.x,R.z,R.y+.3);D.camera.position.set(R.x+sx*3.6+fx*.8,g+.6,R.z+sz*3.6+fz*.8);D.camera.lookAt(R.x+fx*.8,g+.5,R.z+fz*.8);D.camera.updateMatrixWorld();D.composer.render()})};
  for(const k in V){const r=await EV(V[k]||'0');await close();const f=path.join(OUT,'var_'+k+'.png');await p.screenshot({path:f});await unrender();
   const px=execSync(`convert ${f} -scale 10% -depth 8 txt:- | tail -n +2`,{maxBuffer:1e8}).toString().trim().split('\n').map(l=>/\((\d+),(\d+),(\d+)/.exec(l)).filter(Boolean).map(m=>[+m[1],+m[2],+m[3]]).filter(q=>q[0]>90&&q[0]>q[1]*1.8&&q[0]>q[2]*1.5);
   const med=i=>{const a=px.map(q=>q[i]).sort((a,b)=>a-b);return a[a.length>>1]};console.log('VAR',k,await EV(`(()=>{let r;pl.mesh.traverse(o=>{if(!r&&o.isMesh&&o.material.isMeshPhysicalMaterial&&o.geometry.attributes.color)r=[o.material.envMapIntensity,o.material.clearcoat,!!o.material.envMap,scene.environmentIntensity]});return JSON.stringify(r)})()`),px.length,JSON.stringify([med(0),med(1),med(2)]))}
  console.log('DBG4',await EV(`(()=>{let r=null;pl.mesh.traverse(m=>{if(!r&&m.isMesh&&m.material.type==='ShaderMaterial'){const t=m.material;r={name:m.name,ud:Object.keys(m.userData),par:m.parent&&m.parent.type,blend:t.blending,tr:t.transparent,dw:t.depthWrite,side:t.side,u:Object.keys(t.uniforms),fs:t.fragmentShader.slice(0,900),vs:t.vertexShader.slice(0,300),ro:m.renderOrder}}});return JSON.stringify(r)})()`));console.log('DBG3',await EV(`(()=>{const o=[];pl.mesh.traverse(m=>{if(m.isMesh&&m.geometry.attributes.color){const t=m.material,pr=renderer.properties.get(t);o.push([m.visible,m.isInstancedMesh,t.type,t.id,!!t.userData.w12,pr.__version,pr.currentProgram&&renderer.getContext().getShaderSource(pr.currentProgram.fragmentShader).includes('w12p'),m.geometry.attributes.position.count])}});return JSON.stringify(o)})()`));console.log('DBG2',await EV(`(()=>{const o=[];pl.mesh.traverse(m=>{if(m.isMesh)for(const t of[].concat(m.material)){const pr=renderer.properties.get(t);o.push([t.type,!!t.userData.w12,t.version,pr.__version,(pr.currentProgram||{}).cacheKey?.slice(-12),pr.currentProgram&&renderer.getContext().getShaderSource(pr.currentProgram.fragmentShader).includes('w12p')])}});return JSON.stringify(o.slice(0,8))})()`));
  await b.close();return}
 for(const [nm,hex] of[['red','#d01712'],['blue','#0055bf'],['yellow','#fac80a']]){const r=await paint(hex);const sm=await sample(process.env.TAG+'_'+nm);
   const px=sm.txt.map(l=>/\((\d+),(\d+),(\d+)/.exec(l)).filter(Boolean).map(m=>[+m[1],+m[2],+m[3]]);
   const T=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];
   const near=px.filter(q=>{const mx=Math.max(...q),mn=Math.min(...q);if(mx-mn<60)return false;const hue=(c=>{const[r,g,b]=c.map(v=>v/255),M=Math.max(r,g,b),m=Math.min(r,g,b),d=M-m;let H=M===r?((g-b)/d)%6:M===g?(b-r)/d+2:(r-g)/d+4;return(H*60+360)%360})(q);const th=(c=>{const[r,g,b]=c.map(v=>v/255),M=Math.max(r,g,b),m=Math.min(r,g,b),d=M-m;let H=M===r?((g-b)/d)%6:M===g?(b-r)/d+2:(r-g)/d+4;return(H*60+360)%360})(T);let dh=Math.abs(hue-th);dh=Math.min(dh,360-dh);return dh<25&&(mx-mn)/mx>.6});
   const med=i=>{const a=near.map(q=>q[i]).sort((a,b)=>a-b);return a[a.length>>1]};const hue=c=>{const[r,g,b]=c.map(v=>v/255),M=Math.max(r,g,b),m=Math.min(r,g,b),d=M-m||1;let H=M===r?((g-b)/d)%6:M===g?(b-r)/d+2:(r-g)/d+4;return+((H*60+360)%360).toFixed(0)};
   const M3=[med(0),med(1),med(2)];res[nm]={target:T,n:near.length,median:M3,hue:hue(M3),targetHue:hue(T),painted:r.n,shot:sm.f};console.log('PAINT',nm,JSON.stringify(res[nm]))}
 res.errs=errs;fs.writeFileSync(path.join(OUT,'w12_'+process.env.TAG+'.json'),JSON.stringify(res,null,1));console.log('ERRS',JSON.stringify(errs.slice(0,5)));await b.close()})().catch(e=>{console.error('ERR',e);process.exit(1)});
