// node tools/w8v.js <url> <outdir> <city fra|ath> '<js returning list of [name, expr]>'  → boots to roam, evals each expr (returns {png}) and saves <outdir>/<name>.png
const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const [URL,OUT,CITY='fra',JOBS='[]']=process.argv.slice(2);fs.mkdirSync(OUT,{recursive:true});
 const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const p=await b.newPage(process.env.TOUCH?{viewport:{width:852,height:393},hasTouch:true,isMobile:true,deviceScaleFactor:1,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'}:{viewport:{width:852,height:393}});const cdp=await p.context().newCDPSession(p);
 const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto(URL);await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:300000,polling:500});
 await p.evaluate(([c])=>{localStorage.clear();localStorage.setItem('mho_slot','1');if(c==='ath'){localStorage.setItem('mho_city@1',c);localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{}}');localStorage.setItem('mho_story.ath@1','{"seen":1}')}},[CITY]);
 await p.reload();await p.waitForFunction(()=>window.__mho&&__mho.state==='menu',null,{timeout:300000,polling:500});
 const click=async s=>{const e=await p.$(s);if(e&&await e.isVisible()){await e.click().catch(()=>{});return 1}return 0};
 if(process.env.BOOT==='skip'){await p.evaluate(()=>{localStorage.setItem('mho_athpre','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));try{__m1.skip()}catch(e){}__mho.enterRoam()})}
 for(let i=0;i<200;i++){const st=await p.evaluate(()=>__mho.state);if(st==='roam')break;if(st==='menu'){await click('#odNewX');await click('#hcStory');await p.waitForTimeout(500);await click('#slotList .go')}await p.waitForTimeout(2000)}
 await p.waitForTimeout(8000);for(const s of ['#storyGo','#m1Cs','#rcGo','.m1go','#tutSkip','#setDone'])await click(s);await p.waitForTimeout(2000);
 for(const [n,ex] of eval(JOBS)){try{const r=await p.evaluate(ex);if(r&&r.hold){const e=await p.$(r.hold);const bb=await e.boundingBox();const pt=[{x:bb.x+bb.width/2,y:bb.y+bb.height/2,id:1}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pt});await p.waitForTimeout(r.wait||3000);await p.screenshot({path:`${OUT}/${n}.png`});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(800);await p.screenshot({path:`${OUT}/${n}_up.png`})}if(r&&r.page){await p.waitForTimeout(r.wait||1500);await p.screenshot({path:`${OUT}/${n}.png`})}if(r&&r.png){fs.writeFileSync(`${OUT}/${n}.png`,Buffer.from(r.png.split(',')[1],'base64'));delete r.png}console.log(n,JSON.stringify(r))}catch(e){console.log(n,'ERR',String(e).slice(0,300))}}
 console.log('ERRORS',errs.length,errs.slice(0,5).join(' | '));await b.close()})();
