// distance culling for the big city: anything static further than CULL_R from the camera is hidden
function waterFx(dt){const s=pl;if(!s||!RO.on)return;const boat=s.boatMode&&!s.air,sp=Math.abs(RO.v);
  if(boat&&!RO.wasBoat&&sp>12){burst(WATER,V3(RO.x,HWY+1,RO.z),40,14,.8,new THREE.Color(.6,.85,1.3));AU.sfx('splash')}RO.wasBoat=boat;
  if(boat&&sp>6){RO.wkT=(RO.wkT||0)+dt*Math.min(3,sp/20);while(RO.wkT>.05){RO.wkT-=.05;const fx=Math.sin(RO.h),fz=Math.cos(RO.h),y=HWY+waveH(RO.x,RO.z,T)+.3;for(const sd of[-1,1])burst(WATER,V3(RO.x-fx*5+fz*sd*2.4,y,RO.z-fz*5-fx*sd*2.4),1,3+sp*.06,.7,new THREE.Color(.85,.95,1.2))}}}
function hubCullAdd(root){if(HUB.cull)root.traverse(o=>cullPush(HUB.cull,o));HUB.cpos=null}
function hubCullInit(){const L=HUB.cull=[];for(const top of HUB.grp.children)if(top!==RO.grp&&top.visible!==false)top.traverse(o=>cullPush(L,o));if(RO.grp){for(const im of RO.sim||[])if(im.boundingSphere)L.push({o:im,x:im.boundingSphere.center.x,z:im.boundingSphere.center.z,r:Math.min(im.boundingSphere.radius,400),small:true});for(const o of RO.grp.children)if(o.userData.ramp)L.push({o,x:o.position.x,z:o.position.z,r:30,small:false})}}
function cullPush(L,o){{if(!(o.isMesh||o.isInstancedMesh)||o.frustumCulled===false)return;if(o.isInstancedMesh){if(!o.boundingSphere)o.computeBoundingSphere()}else if(!o.geometry.boundingSphere)o.geometry.computeBoundingSphere();const bs=o.isInstancedMesh?o.boundingSphere:o.geometry.boundingSphere;if(!bs||bs.radius>1500)return;const g=o.geometry,tri=(g.index?g.index.count:g.attributes.position.count)/3;L.push({o,x:bs.center.x+o.position.x,z:bs.center.z+o.position.z,r:bs.radius,small:o.isInstancedMesh&&tri<1200&&!o.userData.nr})}}
function hubCullStep(){if(!HUB.cull)hubCullInit();if(HUB.cull.length>4000){const C=HUB.cull,cx=camera.position.x,cz=camera.position.z,R2=SET.q==='high'?2100:1600,
    jump=!HUB.cpos||Math.hypot(cx-HUB.cpos[0],cz-HUB.cpos[1])>150,f=HUB.cf=((HUB.cf||0)+1)%8;if(jump)HUB.cpos=[cx,cz];else if(f===0)HUB.cpos=[cx,cz];
    for(let i=jump?0:f;i<C.length;i+=jump?1:8){const c=C[i];c.o.visible=Math.hypot(c.x-cx,c.z-cz)-c.r<(c.o.userData.cd||(c.small?750:R2))}return}const cx=camera.position.x,cz=camera.position.z,jump=!HUB.cpos||Math.hypot(cx-HUB.cpos[0],cz-HUB.cpos[1])>150;if((HUB.cf=(HUB.cf||0)+1)%8!==1&&!jump)return;HUB.cpos=[cx,cz];const R2=SET.q==='high'?2100:1600;for(const c of HUB.cull)c.o.visible=Math.hypot(c.x-cx,c.z-cz)-c.r<(c.o.userData.cd||(c.small?750:R2))}
// districts: a small label when you cross into a new part of Mainhattan
if(CID!=='fra'){const e=document.querySelector('#roamPlate b');if(e)e.textContent=''}
const DIST_R=RF.districts.map(([name,r,side],i,A)=>({name,side:side||0,...rfRect(r),dup:A.findIndex(q=>q[0]===name)<i})),DISTRICTS=DIST_R;
function districtAt(x,z){if(inRiver(x,z))return 'Am Main';let sd=null;for(const d of DIST_R)if(x>=d.x0&&x<d.x1&&z>=d.z0&&z<d.z1){if(d.side){if(sd==null)sd=rivSide(x,z);if(sd!==d.side)continue}return d.name}return inCity(x,z)?CCF.fb[0]:CCF.fb[1]}
// map helpers: the Main and the basin as filled polygons (bank lines optional), buildings as (rotated) rectangles
function rfWaterPaint(g,P,fill,edge,lw){for(const S of WATERS){const A=S.pts,L=[],Rr=[];for(let i=0;i<A.length;i+=2){const p=A[i];L.push(P(p.x+p.tz*p.hw,p.z-p.tx*p.hw));Rr.push(P(p.x-p.tz*p.hw,p.z+p.tx*p.hw))}const q=A[A.length-1];L.push(P(q.x+q.tz*q.hw,q.z-q.tx*q.hw));Rr.push(P(q.x-q.tz*q.hw,q.z+q.tx*q.hw));
  g.fillStyle=fill;g.beginPath();L.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));for(let i=Rr.length-1;i>=0;i--)g.lineTo(Rr[i][0],Rr[i][1]);g.closePath();g.fill();
  if(edge){g.strokeStyle=edge;g.lineWidth=lw;for(const B of[L,Rr]){g.beginPath();B.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.stroke()}}}}
function bldPaint(g,P,b,k){if(b.c==null){const p=P(b.x+b.hw,b.z+b.hd);g.fillRect(p[0],p[1],b.hw*2*k,b.hd*2*k);return}g.beginPath();[[-1,-1],[1,-1],[1,1],[-1,1]].forEach(([a,c],i)=>{const lx=a*b.hw,lz=c*b.hd,q=P(b.x+lx*b.c+lz*b.s,b.z-lx*b.s+lz*b.c);i?g.lineTo(q[0],q[1]):g.moveTo(q[0],q[1])});g.fill()}
let MINI=null;function miniBase(){const kc=SET.q==='low'?.25:Math.min(.34,2048/(HX1-HX0),2048/(HZN-HZT)),kw=Math.min(.146,2048/(WX1-WX0),2048/(WZN-WZS)),C=miniPaint(HX0,HX1,HZT,HZN,kc);C.w=miniPaint(WX0,WX1,WZS,WZN,kw,1);return C}
let URB=null;function urbLayer(){if(URB&&URB.cid===CID)return URB;const C=50,nx=Math.ceil((WX1-WX0)/C),nz=Math.ceil((WZN-WZS)/C),G=new Uint8Array(nx*nz);const put=(x,z)=>{const i=Math.floor((x-WX0)/C),j=Math.floor((z-WZS)/C);if(i>=0&&j>=0&&i<nx&&j<nz)G[j*nx+i]=1};for(const b of HUB.bld)put(b.x,b.z);for(const L of LAZY){for(const b of L.bld||[])put(b.x,b.z);const Q=L.q;if(Q&&Q.length)for(let i=0;i<Q.length;i+=9)put(Q[i],Q[i+1])}const D=new Uint8Array(G);for(let j=1;j<nz-1;j++)for(let i=1;i<nx-1;i++){if(G[j*nx+i])continue;let n=0;for(let b=-1;b<=1;b++)for(let a=-1;a<=1;a++)n+=G[(j+b)*nx+i+a];if(n>=3)D[j*nx+i]=1}const k=1/C,[c,g]=cv(nx,nz);const im=g.createImageData(nx,nz);for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){if(!D[j*nx+i])continue;const px=(nx-1-i),py=(nz-1-j),o=(py*nx+px)*4;im.data[o]=255;im.data[o+1]=255;im.data[o+2]=255;im.data[o+3]=255}g.putImageData(im,0,0);return URB={cid:CID,c,k,x1:WX0+nx*C,z1:WZS+nz*C}}
function urbDraw(g,P,sc,col){const U=urbLayer(),[x,y]=P(U.x1,U.z1),w=U.c.width/U.k*sc,h=U.c.height/U.k*sc;g.save();g.imageSmoothingEnabled=true;const t=document.createElement('canvas');t.width=U.c.width;t.height=U.c.height;const tg=t.getContext('2d');tg.drawImage(U.c,0,0);tg.globalCompositeOperation='source-in';tg.fillStyle=col;tg.fillRect(0,0,t.width,t.height);g.drawImage(t,x,y,w,h);g.restore()}
function miniPaint(x0,x1,z0,z1,k,wt){const W=Math.ceil((x1-x0)*k),H=Math.ceil((z1-z0)*k),[c,g]=cv(W,H);const P=(x,z)=>[(x1-x)*k,(z1-z)*k];
  const rect=(a,b,cc,d,col)=>{const p=P(a,d),q=P(cc,b);g.fillStyle=col;g.fillRect(Math.min(p[0],q[0]),Math.min(p[1],q[1]),Math.abs(q[0]-p[0]),Math.abs(q[1]-p[1]))};
  g.fillStyle=CCF.gnd;g.fillRect(0,0,W,H);if(wt){if(CID==='fra'){rect(WX0,WZS,WX1,-2600,'#4f9e3a');rect(WX0,3400,WX1,WZN,'#8cc456')}for(const B of BIOMES)if(B.g!=='city'&&B.g!=='hill')rect(B.r[0],B.r[2],B.r[1],B.r[3],B.g==='field'?'#8cc456':B.g==='forest'?'#4f9e3a':B.g==='air'?'#a8c87a':'#b8c49a');g.strokeStyle='#ff5a3c';g.lineWidth=4;g.strokeRect(1,1,W-2,H-2)}for(const Z of ZONES)rect(Z.x0,Z.z0,Z.x1,Z.z1,Z.t==='dirt'?'#c9a46a':Z.t==='plaza'?'#e6d7b8':Z.t==='yard'?'#a9adb3':Z.t==='hills'?'#4f9e3a':'#3f9a2c');
  if(wt)urbDraw(g,P,k,CID==='fra'?'#cfd3c8':'#e3dccb');rfWaterPaint(g,P,'#2f86e8','#7cc0ff',2)
  g.fillStyle='#d9d2c4';for(const b of HUB.bld)bldPaint(g,P,b,k);for(const L of LAZY)if(!L.done)for(const b of L.bld)bldPaint(g,P,b,k)
  g.lineCap='round';const road=(pts,w)=>{for(const [col,ex] of [['#8c8478',3],['#fbf7ee',0]]){g.strokeStyle=col;g.lineWidth=Math.max(3,w*k*.9)+ex;g.beginPath();pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)});g.stroke()}};
  const thin=(pts,w,col)=>{g.strokeStyle=col;g.lineWidth=Math.max(1.5,w*k*.55);g.beginPath();pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)});g.stroke()};for(const r of hubRoads())thin([{x:r.x0,z:r.z0},{x:r.x1,z:r.z1}],r.w,'#ece6d8');for(const T of TRAILS)road(T.pts,T.w*.7);for(const S of LZ.roads){if(S.name==='Odos'){if(!wt)thin(S.pts,S.w,'#e2dccd')}else road(S.pts,S.w)}for(const S of CITY_S){const c=S.r.cls;if(c==='main'||c==='ring'||c==='arterial'||c==='quay')continue;thin(S.pts,S.r.w,c==='ped'?'#f3e4c2':'#f6f1e6')}for(const S of CITY_S){const c=S.r.cls;if(c==='main'||c==='ring'||c==='arterial'||c==='quay')road(S.pts,S.r.w*1.15)}for(const S of mtnSamples())road(S.pts,S.r.w);for(const S of abSamples())for(const[col,ex]of[['#8c5a1c',3],['#ffc46a',0]]){g.strokeStyle=col;g.lineWidth=Math.max(3,S.r.w*k*.9)+ex;g.beginPath();S.pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)});g.stroke()}for(const b of BRIDGES){g.strokeStyle='#ffd23a';g.lineWidth=Math.max(3,b.w*k*.9);g.beginPath();g.moveTo(...P(...deckPt(b,-b.half)));g.lineTo(...P(...deckPt(b,b.half)));g.stroke()}
  return{c,k,x1,z1}}
function miniDraw(){if(!RO.on)return;HUB.mf=(HUB.mf||0)+1;if(HUB.mf%2)return;const el=$('#roamMini canvas');if(!el||el.offsetParent===null)return;if(!MINI)MINI=miniBase();
  const g=el.getContext('2d'),W=el.width,c=W/2,R0=c-6,s=RO.miniS=(RO.miniS||.36)+((.36-.18*clamp((Math.abs(RO.v)-30)/40,0,1))-(RO.miniS||.36))*.05,h=RO.camH??RO.h,co=Math.cos(h),si=Math.sin(h);
  const to=RO.miniTo=(x,z)=>{const ox=-(x-RO.x)*s,oy=-(z-RO.z)*s;return[ox*co-oy*si,ox*si+oy*co]};
  g.clearRect(0,0,W,W);g.save();g.beginPath();g.arc(c,c,R0,0,7);g.clip();g.fillStyle=CCF.gnd;g.fillRect(0,0,W,W);
  g.translate(c,c);g.rotate(h);{const rr=R0/s+30,inC=SM_ON||RO.x-HX0>rr&&HX1-RO.x>rr&&RO.z-HZT>rr&&HZN-RO.z>rr;for(const Q of inC?[MINI]:inCity(RO.x,RO.z,rr)?[MINI.w,MINI]:[MINI.w]){const f=s/Q.k;g.drawImage(Q.c,-(Q.x1-RO.x)*Q.k*f,-(Q.z1-RO.z)*Q.k*f,Q.c.width*f,Q.c.height*f)}}g.setTransform(1,0,0,1,0,0);
  // route line to the current target
  const ch=RO.ch,tg=ch?chNext(ch):RO.sp?RO.sp.G[RO.sp.gi]:(RO.wp||RO.near);
  if(!qvMini(g,to,c)&&tg&&Number.isFinite(tg.x)){const[a,b]=to(tg.x,tg.z);g.strokeStyle='rgba(255,255,255,.95)';g.lineWidth=5;g.setLineDash([2,9]);g.lineCap='round';g.beginPath();g.moveTo(c,c);g.lineTo(c+a,c+b);g.stroke();g.setLineDash([]);const cq=cpTargets();if(cq&&cq.b){const[a2,b2]=to(cq.b.x,cq.b.z);g.strokeStyle='rgba(76,234,255,.8)';g.lineWidth=3;g.setLineDash([2,7]);g.beginPath();g.moveTo(c+a,c+b);g.lineTo(c+a2,c+b2);g.stroke();g.setLineDash([])}}
  g.restore();g.textAlign='center';g.textBaseline='middle';g.font='15px system-ui';
  const pin=(x,z,col,ic,big)=>{let[a,b]=to(x,z);const d=Math.hypot(a,b),lim=R0-12;if(d>lim){if(!big)return;a*=lim/d;b*=lim/d}const r=big?12:10;g.fillStyle=col;g.beginPath();g.arc(c+a,c+b,r,0,7);g.fill();g.lineWidth=2.5;g.strokeStyle='#fff';g.stroke();g.fillStyle='#fff';g.fillText(ic,c+a,c+b+1)};
  if(ch&&ch.kind==='ball'&&ch.ball){const[a1,b1]=to(ch.ball.x,ch.ball.z),[a2,b2]=to(ch.goal[0],ch.goal[1]);g.save();g.beginPath();g.arc(c,c,R0,0,7);g.clip();g.strokeStyle='#ffd400';g.lineWidth=4;g.setLineDash([3,6]);g.beginPath();g.moveTo(c+a1,c+b1);g.lineTo(c+a2,c+b2);g.stroke();g.setLineDash([]);g.restore();pin(ch.goal[0],ch.goal[1],'#36d17a','🥅',true);pin(ch.ball.x,ch.ball.z,'#2a7fff','⚽',true)}if(ch)for(const o of ch.objs||[])if(!o.done&&Number.isFinite(o.x)&&o!==tg)pin(o.x,o.z,'#ffb000','•',false);if(!ch&&!RO.sp)for(const m of RO.marks){if(!markKnown(m)||markLocked(m))continue;const dn=markDone(m);if(Math.hypot(m.x-RO.x,m.z-RO.z)>R0/s+20&&m!==RO.wp)continue;pin(m.x,m.z,dn?'#59636e':m.col||'#2a6fdb',dn?'✔':mapIcon(m),m===RO.wp)}qvMiniQ(pin,R0,s);
  if(tg&&Number.isFinite(tg.x))pin(tg.x,tg.z,'#ff3b5c',ch||RO.sp?'◆':mapIcon(tg)||'◆',true);
  // north marker on the rim, player arrow in the middle
  {const[a,b]=to(RO.x,RO.z+1e4),d=Math.hypot(a,b),nx=c+a/d*(R0-2),ny=c+b/d*(R0-2);g.fillStyle='#ffd400';g.beginPath();g.arc(nx,ny,11,0,7);g.fill();g.strokeStyle='#141413';g.lineWidth=2;g.stroke();g.fillStyle='#141413';g.font='900 13px system-ui';g.fillText('N',nx,ny+1)}
  g.fillStyle='#fff';g.strokeStyle='#141413';g.lineWidth=3;g.beginPath();g.moveTo(c,c-14);g.lineTo(c+10,c+11);g.lineTo(c,c+5);g.lineTo(c-10,c+11);g.closePath();g.stroke();g.fill();
  if(HUB.mf%20===0||HUB.mf<4){const pl2=$('#roamPlate');{const lm=CID!=='fra'&&athLmNear(RO.x,RO.z);pl2.querySelector('b').textContent=lm?lm.name:RO.dist||districtAt(RO.x,RO.z)||CCF.fb[0]}pl2.querySelector('small').textContent=`${CCF.ch} ${chapter()} · ${CHS()[chapter()-1].title}`;$('#roamStuds b').textContent=(season().cr).toLocaleString('de-DE')}}
function athDistGo(d,x,z,h,snap){if(athDistGo.on||!ATH_DIST[d])return false;athDistGo.on=1;if(x!=null){RO.x=x;RO.z=z;RO.h=h??RO.h;RO.y=0}const v=x!=null?0:Math.max(0,RO.v||0);try{roamSavePos();localStorage.setItem('mho_athd@'+SLOT,d)}catch(e){}
  const f=JSON.stringify({go:'roam',t:Date.now(),athv:+v.toFixed(1),snap:snap?1:0,athd:d});try{sessionStorage.setItem('mho_boot',f)}catch(e){try{localStorage.setItem('mho_boot',f)}catch(_){}}
  RO.on=false;RO.frozen=true;if(pl){AU.engine(pl,0,false);AU.scrape(false)}if(RO.mapOpen)toggleMap(false);ldShow('Driving to '+ATH_DIST[d].name);ldSet(.4);setTimeout(()=>location.reload(),450);return true}
function athDistPick(d){if(SM_ON&&ATH_DIST[d]){toggleMap(false);const D=ATH_DIST[d],[x,z]=WP(D.st[0],D.st[1]),q=rfSnap(x,z,200);roamWarp(q[0],q[1],q[2]);return true}const D=ATH_DIST[d],[x,z]=WP(D.st[0],D.st[1]);if(d===ATHD){toggleMap(false);const q=rfSnap(x,z,200);roamWarp(q[0],q[1],q[2]);return true}return athDistGo(d,x,z,0,1)}
function SM_step(){if(CID!=='ath'||!RO.on)return;const[e,n]=RW(RO.x,RO.z),d=athDistAt(e,n);
  if(d&&d!==ATHD){const was=ATHD;ATHD=d;try{localStorage.setItem('mho_athd@'+SLOT,d)}catch(_){}if(typeof ATC!=='undefined')ATC.mk=0;
    if(!SM.first){SM.cross++;SM.log.push([was,d,Math.round(performance.now())]);const el=$('#roamDist');if(el){el.textContent='📍 '+ATH_DIST[d].name.toUpperCase();el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}}}
  SM.first=0;if(d||RO.ch||RO.sp||RO.wk)return;
  RO.edgeT2=(RO.edgeT2||0)-.5;if(RO.edgeT2<=0){RO.edgeT2=3;const el=$('#roamDist');if(el){el.textContent='↩ TURN BACK · '+ATH_DIST[ATHD].name.toUpperCase();el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}}}
function athDistStep(){if(SM_ON)return SM_step();if(CID!=='ath'||!RO.on||RO.ch||RO.sp||RO.wk||LD.busy)return;const[e,n]=RW(RO.x,RO.z);if(athIn(ATHD,e,n))return;const d=athDistAt(e,n);if(d){athDistGo(d);return}
  RO.edgeT2=(RO.edgeT2||0)-.5;if(RO.edgeT2<=0){RO.edgeT2=3;const el=$('#roamDist');if(el){el.textContent='↩ TURN BACK · '+ATH_DIST[ATHD].name.toUpperCase();el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}}}
function districtStep(){HUB.df=(HUB.df||0)+1;if(HUB.df%30)return;athDistStep();const n=RO.abRoad||districtAt(RO.x,RO.z);if(n&&n!==RO.dist){const first=!RO.dist;RO.dist=n;if(!first){const el=$('#roamDist');if(el){el.textContent='📍 '+n.toUpperCase();el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}}}}
const _hfw=new THREE.Vector3(),_hrt=new THREE.Vector3(),_hup=new THREE.Vector3(0,1,0);
function hubTrafficStep(dt){CR_npcPush();if(HUB.ridge)HUB.ridge.position.set(camera.position.x,0,camera.position.z);if(RO.on&&!RO.frozen){const v=Math.abs(RO.v);RO.pdist=(RO.pdist||0)+v*dt;RO.ptop=Math.max(RO.ptop||0,v*3.6);RO.pfT=(RO.pfT||0)+dt;if(RO.pfT>8){RO.pfT=0;pstatFlush()}}if(CLOUDS)CLOUDS.position.x+=dt*3;miniDraw();if(HUB.waterU)HUB.waterU.value=T;waterFx(dt);hubRecycle();pedStep(dt);hubCullStep();lazyStep();districtStep();const N=HUB.nodes;for(const c of HUB.cars){const im=HUB.cim[c.k];if(c.dead>0){c.dead-=dt;if(CR_tumble(c,im,dt))continue;_m.makeScale(0,0,0);im.setMatrixAt(c.j,_m);if(im.userData.w)im.userData.w.setMatrixAt(c.j,_m);if(im.userData.g)im.userData.g.setMatrixAt(c.j,_m);if(c.dead<=0){c.a=Math.floor(R()*N.length);c.b=N[c.a].nb[0];c.t=0;if(c.tr){const T=HUB.trn;c.a=T[Math.floor(R()*T.length)];c.b=N[c.a].nb.find(n=>N[n].tr)}}continue}
    if(!N[c.b]||!N[c.a]){c.a=Math.floor(R()*N.ng);c.b=N[c.a].nb[0]??c.a;c.t=0;continue}const A=N[c.a],B=N[c.b],L=Math.hypot(B.x-A.x,B.z-A.z)||1;
    // brake behind the player
    const ahead=Math.hypot(RO.x-(c.x+(B.x-A.x)/L*8),RO.z-(c.z+(B.z-A.z)/L*8))<9;const V=A.ab?(c.hv||(c.hv=rr(28,36))):c.v;if(c.hitT>0){c.hitT-=dt;c.cv=W10_brake(c.cv||0,dt)}else c.cv=(c.cv??V)+Math.min(((ahead?Math.min(2,V):V)-(c.cv??V))*Math.min(1,dt*3),4*dt);
    c.t+=c.cv*dt/L;if(c.t>=1&&c.route){c.a=c.b;c.b=c.route.length?c.route.shift():c.a;c.t=0;c.rn=(c.rn||0)+1;continue}if(c.t>=1){let nx=B.nb.filter(n=>n!==c.a&&!QS_shut(c.b,n));if(c.tr)nx=nx.filter(n=>N[n].tr);c.a=c.b;c.b=nx.length?nx[Math.floor(R()*nx.length)]:c.a;c.t=0;continue}
    // v88u perf: cars > 250 m away get their pose (ground probe, suspension, matrix) every 4th frame only; they still move every frame
    if(TUNE.lvLod&&c.dead<=0&&!c.route&&!c.pk&&(HUB.fr+c.j+c.k)%4&&(c.x-RO.x)**2+(c.z-RO.z)**2>62500)continue;
    const dx=(B.x-A.x)/L,dz=(B.z-A.z)/L,gA=A.g||B.g,W=c.pk&&c.ofW?c.ofW:A.ab||gA?0:Math.min(A.w||20,B.w||20),lane=W*c.lane,x=A.x+(B.x-A.x)*c.t-dz*lane,z=A.z+(B.z-A.z)*c.t+dx*lane;
    c.x=x;c.z=z;c.y=A.ab||gA?groundAt(x,z,(c.y||0)+4):groundY(x,z);
    _m.makeBasis(_hrt.set(dz,0,-dx),_hup,_hfw.set(dx,0,dz)).setPosition(x,c.y,z);CR_susp(c,dx,dz,dt,im,_m);
    const d=Math.hypot(x-RO.x,z-RO.z);if(d<5&&Math.abs(c.y-RO.y)<3&&OB_car(x,z,dx,dz,c)){const crLg=(RO.crLg||0)>0,pin=W10_pin(c),crSm=crLg||pin||Math.abs(RO.v)>CR_SMASHV;if(!crSm){W10_bump(c,x,z,dx,dz,W)}else if(1){c.dead=25;CR_tumbleStart(c,x,z,dx,dz);const at=V3(x,c.y+1.5,z),f2=V3(Math.sin(RO.vh),0,Math.cos(RO.vh));debris(at,V3(0,9,0).addScaledVector(f2,Math.abs(RO.v)*.5),18,[new THREE.Color(HCOL[(c.j*3+c.k)%HCOL.length]),new THREE.Color('#22252f'),new THREE.Color('#d0e8ff')],1.1,c.y);for(let k=0;k<8;k++)studBurst(at,f2,Math.abs(RO.v));const rx=x-RO.x,rz=z-RO.z,rl=Math.hypot(rx,rz)||1,ho=(f2.x*dx+f2.z*dz)<-.6&&(f2.x*rx+f2.z*rz)/rl>.7;RO.v*=pl&&pl.nitro?.95:ho?.6:.88;shake=ho?.5:.3;AU.sfx('crash');if(crSm)CR_smashHit();if(pl&&pl.nitro)roamHeal(3);else if(!crLg&&!pin)roamDamage(ho?12:5);addXP(3,'traffic smash');comboAdd(3);qCrate();if(pl)pl.bm=Math.min(100,pl.bm+12)}else{c.t=Math.max(0,c.t-.02)}}if(c.crB>0)c.crB-=dt;
    else if(d<10&&Math.abs(RO.v)>45&&!(c.nm>0)&&Math.abs(c.y-RO.y)<3){c.nm=3;if(pl){pl.bm=Math.min(100,pl.bm+8);award(pl,'NEAR MISS',0,200,'#4ceaff');AU.sfx('near');comboAdd(2)}}if(c.nm>0)c.nm-=dt}
  for(const im of HUB.cim){im.instanceMatrix.needsUpdate=true;if(im.userData.w)im.userData.w.instanceMatrix.needsUpdate=true;if(im.userData.g)im.userData.g.instanceMatrix.needsUpdate=true}}
// ---------- entering / leaving the hub world
let CLOUDS=null;function cloudsOn(v){if(v&&!CLOUDS){const N=150,per=6,geo=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshLambertMaterial({color:0xffffff,emissive:0xdfe9f7,emissiveIntensity:.72,fog:false}),im=new THREE.InstancedMesh(geo,mat,N*per),M=new THREE.Matrix4(),q=new THREE.Quaternion(),S=new THREE.Vector3(),P=new THREE.Vector3();let r=7;const rnd=()=>(r=(r*16807)%2147483647)/2147483647;let k=0;
    for(let c=0;c<N;c++){const cx=WX0-800+rnd()*(WX1-WX0+1600),cz=WZS-600+rnd()*(WZN-WZS+1200),cy=230+rnd()*180,sz=50+rnd()*70;for(let j=0;j<per;j++){const w=sz*(.35+rnd()*.5),h=sz*(.18+rnd()*.22),d=sz*(.3+rnd()*.4);P.set(cx+(rnd()-.5)*sz*1.3,cy+(j<4?0:h*.7)+rnd()*h*.4,cz+(rnd()-.5)*sz*.8);S.set(w,h,d);M.compose(P,q,S);im.setMatrixAt(k++,M)}}
    im.frustumCulled=false;CLOUDS=new THREE.Group();CLOUDS.add(im);CLOUDS.userData.keep=1}
  if(CLOUDS){if(v&&!CLOUDS.parent)scene.add(CLOUDS);if(!v&&CLOUDS.parent)scene.remove(CLOUDS)}}
// ground layers below the road were only 1-2 cm apart (road 0, pavement -1 cm, grass -3 cm) and z-fought at distance: spread them out
function hubLayerFix(){if(HUB.layerFixed)return;HUB.layerFixed=1;HUB.grp.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||!o.geometry)return;const g=o.geometry;if(!g.boundingBox)g.computeBoundingBox();const b=g.boundingBox;if(b.max.y-b.min.y>.005)return;const y=b.max.y+o.position.y;if(y<-.0045&&y>-.05)o.position.y+=y*5})}
let hubShadow=false;function hubEnter(){buildHub();hubLayerFix();if(!HUB.grp.parent)scene.add(HUB.grp);if(ROOT)ROOT.visible=false;HUB.grp.visible=true;for(const o of TRM)for(const key in o)o[key].visible=false;if(typeof trShadow!=='undefined'){trShadow.visible=false;trGlow.visible=false;trLights.visible=false}
  for(const k in PROP)PROP[k].visible=false;applyMood(CCF.mood);scene.fog.density=SET.q==='high'?.00016:.00024;cloudsOn(true);/* P0 v88h: un-hide what the old cull list hid before dropping it; hubCullInit skips hidden top-level meshes, so far parts of the city stayed hidden for good after every re-entry ("city not loading") */if(HUB.cull)for(const c of HUB.cull)c.o.visible=true;HUB.cull=null;HUB.cpos=null;if(SET.q==='high'){renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;moonL.castShadow=true;moonL.shadow.mapSize.set(2048,2048);const sc=moonL.shadow.camera;sc.left=-110;sc.right=110;sc.top=110;sc.bottom=-110;sc.near=50;sc.far=900;sc.updateProjectionMatrix();moonL.shadow.bias=-.0006;moonL.shadow.normalBias=.6;if(!moonL.target.parent)scene.add(moonL.target);RO.shadowOn=true;if(pl)pl.mesh.traverse(o=>{if(o.isMesh)o.castShadow=true});if(!HUB.shadowSet){HUB.shadowSet=1;HUB.grp.traverse(o=>{if(o.isInstancedMesh&&o.count<2000&&o.geometry.boundingBox&&o.geometry.boundingBox.max.y*(o.userData.ks||1)>2)o.castShadow=true;if(o.isMesh)o.receiveShadow=true})}}camera.far=SET.q==='high'?3400:2600;camera.near=2;camera.updateProjectionMatrix()}
function hubLeave(){cloudsOn(false);if(RO.shadowOn){moonL.castShadow=false;RO.shadowOn=false;renderer.shadowMap.enabled=false}if(camera.far!==9000||camera.near!==.4){camera.far=9000;camera.near=.4;camera.updateProjectionMatrix()}if(!HUB.grp)return;HUB.grp.visible=false;if(HUB.grp.parent)scene.remove(HUB.grp);if(ROOT)ROOT.visible=true;for(const o of TRM)for(const key in o)o[key].visible=true;if(typeof trShadow!=='undefined'){trShadow.visible=true;trGlow.visible=true;trLights.visible=true}for(const k in PROP)PROP[k].visible=true;if(hubShadow){moonL.castShadow=false;hubShadow=false}}
function hubFrame(dt){if(!HUB.grp||!HUB.grp.visible)return}


// ---- career places at real, named spots: every mark is snapped onto a street (or filler road) and faces along it
// rfSnap: nearest street centre within r (else filler road), heading along the road towards its longer side
function rfSnap(x,z,r=70){const q=cityAt(x,z);if(q&&q.d<r){const p=q.p,f=q.s<q.S.L/2?1:-1;return[p.x,p.z,Math.atan2(p.tx*f,p.tz*f)]}
  const fq=fillAt(x,z);if(fq&&fq.d<r){const R2=fq.r,t=clamp((x-R2.x0)*R2.ux+(z-R2.z0)*R2.uz,0,R2.L),f=t<R2.L/2?1:-1;return[R2.x0+R2.ux*t,R2.z0+R2.uz*t,Math.atan2(R2.ux*f,R2.uz*f)]}return[x,z,0]}
// waypoint tokens: [e,n] real point, ['qN'|'qS',e] quay at real e, ['bN'|'bS',id] bridge end
function rfWp(w){if(typeof w[0]==='number')return WP(w[0],w[1]);const[k,v]=w;if(k==='qN'||k==='qS'){const P=MAINR.pts;let bi=0,bd=1e9;P.forEach((p,i)=>{const d=Math.abs(RW(p.x,p.z)[0]-v);if(d<bd){bd=d;bi=i}});const p=P[bi],o=(k==='qN'?1:-1)*(p.hw+18);return[p.x+p.tz*o,p.z-p.tx*o]}
  const b=BRIDGES.find(q=>q.id===v);return deckPt(b,(k==='bN'?1:-1)*(b.half+6))}
// thread a waypoint list along the real streets: consecutive waypoints on the same street piece follow its samples (80 m steps)
function rfPath(wps){const W2=wps.map(rfWp),out=[W2[0]];const pieces=(x,z)=>{const L=new Map();for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++){const C=CITY_G.get((Math.floor(x/64)+a)*100000+Math.floor(z/64)+b);if(C)for(let j=0;j<C.length;j+=2){const p=CITY_S[C[j]].pts[C[j+1]],d=Math.hypot(p.x-x,p.z-z);if(d<26&&(!L.has(C[j])||L.get(C[j])[0]>d))L.set(C[j],[d,C[j+1]])}}return L};
  for(let k=1;k<W2.length;k++){const A=pieces(...W2[k-1]),B=pieces(...W2[k]);let si=-1;for(const[s]of A)if(B.has(s)){si=s;break}
    if(si>=0){const i0=A.get(si)[1],i1=B.get(si)[1],P=CITY_S[si].pts,st=i1>i0?10:-10;for(let i=i0+st;st>0?i<i1:i>i1;i+=st)out.push([P[i].x,P[i].z])}out.push(W2[k])}
  return out.filter((p,i)=>i===0||Math.hypot(p[0]-out[i-1][0],p[1]-out[i-1][1])>1)}
const SPRINTS=CID!=='fra'?[]:[{id:'sp_zeil',name:'Zeil Dash',ch:1,d:'From the Opernplatz through the Freßgass to the Hauptwache, then down the Zeil to the Konstablerwache.',wp:[[-740,575],[-250,412],[-230,400],[310,445],[650,470]],ai:['ROSSI','WEBER','VOSS']},
 {id:'sp_kai',name:'Mainkai Run',ch:1,d:'Flat out west along the north quay, from the Ostend past the Römer to the Westhafen. Mind the bridge ramps.',wp:[['qN',1550],['qN',-1100]],ai:['WEBER','KAYA','ADLER']},
 {id:'sp_bridge',name:'Bridge Sprint',ch:2,d:'Over the Eiserner Steg to Sachsenhausen, east along the Schaumainkai and back north over the Alte Brücke.',wp:[['qN',-60],['bN','steg'],['bS','steg'],['qS',40],['qS',380],['bS','alte'],['bN','alte'],[395,-120],[330,300]],ai:['MOREAU','OKAFOR','LINDQVIST']},
 {id:'sp_wald',name:'Stadtwald Trail',ch:2,d:'Off-road on the forest trail south of Sachsenhausen. Off-road mode grips the dirt.',trail:'wald',ai:['OKAFOR','BRANDT','KAYA']},
 {id:'sp_slalom',name:'Bankenviertel Slalom',ch:3,d:'Corner after corner between the towers: up the Neue Mainzer Straße, round the Taunusanlage and back along the Kaiserstraße. Drift every turn.',wp:[[-600,-280],[-630,420],[-700,560],[-760,560],[-900,343],[-860,160],[-700,0],[-640,-20],[-360,250]],ai:['FERREIRA','ÇELIK','MOREAU']},
 {id:'sp_tour',name:'Grand Tour',ch:4,d:'The whole city in one run: west along the Hanauer Landstraße, round the Anlagenring, over the Untermainbrücke and down the Schweizer Straße.',wp:[[1635,265],[935,354],[790,300],[740,480],[421,734],[-171,715],[-760,560],[-900,343],[-700,0],[-543,-177],[-440,-370],['bN','untermain'],['bS','untermain'],[-360,-560],[-179,-807],[100,-1150]],ai:['NAKAMURA','BRANDT','ROSSI','FERREIRA']},
 {id:'sp_ring',name:'Anlagenring Loop',ch:2,d:'From the Deutsche Bank towers once round the whole Anlagenring: Alte Oper, Eschenheimer Turm, Konstablerwache, down to the Main, west along the Untermainkai and back up past the Commerzbank.',wp:[[-900,343],[-760,560],[-620,650],[-450,700],[-171,715],[150,735],[421,734],[600,640],[740,480],[790,300],[790,60],[760,-200],['qN',600],['qN',100],['qN',-430],[-440,-370],[-543,-177],[-700,0],[-860,160],[-900,343]],ai:['FERREIRA','OKAFOR','KAYA']},
 {id:'sp_henninger',name:'Around the Henninger Turm',ch:2,d:'A loop through Sachsenhausen: down the Schweizer Straße, up the Hainer Weg to the Henninger Turm, over the top of the Sachsenhäuser Berg and back along the Landwehrweg.',wp:[[-280,-700],[-179,-807],[100,-1150],[350,-1300],[600,-1420],[745,-1455],[820,-1800],[560,-1760],[300,-1650],[50,-1500],[-250,-1330],[-600,-1150],[-179,-807]],ai:['BRANDT','MOREAU','LINDQVIST']},
 {id:'sp_feld',name:'Feldberg Hillclimb',ch:2,d:'Up the Taunus from the A66 to the Großer Feldberg tower. Mind the hairpins.',path:MTN[0].pts.map(p=>[p[0],p[1]]),ai:['BRANDT','KAYA','LINDQVIST']},
 {id:'sp_burg',name:'Burg Downhill',ch:3,d:'From Burg Königstein down the Burgweg to the Feldbergstraße. Brave lines win.',path:MTN[1].pts.slice().reverse().map(p=>[p[0],p[1]]),ai:['NAKAMURA','ÇELIK','ADLER']}];
for(const e of SPRINTS){if(e.wp)e.path=rfPath(e.wp);else if(e.trail){const T=TRAILS.find(t=>t.id===e.trail);e.path=T.pts.filter((p,i)=>i%10===0||i===T.pts.length-1).map(p=>[p.x,p.z])}}
const SCH={};SPRINTS.forEach(e=>{SCH[e.id]=e.ch;const P=e.path;let L=0;for(let i=1;i<P.length;i++)L+=Math.hypot(P[i][0]-P[i-1][0],P[i][1]-P[i-1][1]);e.len=L});
// MARKPOS/MARKH: filled from RF.spots (real named places) when the roam world is built; the test fails on a missing key
const MARKPOS={},MARKH={};
function rfMarks(){for(const k in RF.spots){const sp=RF.spots[k],[x,z,h]=rfSnap(...rfWp(sp));MARKPOS[k]=[x,z];MARKH[k]=h;if(sp.length>=4&&typeof sp[2]==='number'){const[fx,fz]=WP(sp[2],sp[3]);MARKH[k]=Math.atan2(fx-x,fz-z)}}
  for(const e of SPRINTS){const a=e.path[0],b=e.path[1];MARKPOS[e.id]=[a[0],a[1]];MARKH[e.id]=Math.atan2(b[0]-a[0],b[1]-a[1])}
  {const b=BRIDGES.find(q=>q.id==='steg');if(b&&MARKPOS.lj1){const[x,z]=deckPt(b,b.half+10);MARKPOS.lj1=[x,z];MARKH.lj1=Math.atan2(-b.ux,-b.uz)}}
  // keep marks apart (40 m) by sliding along their road
  const K=Object.keys(MARKPOS);for(let i=0;i<K.length;i++)for(let t=0;t<6;t++){const p=MARKPOS[K[i]];if(!K.slice(0,i).some(k=>Math.hypot(MARKPOS[k][0]-p[0],MARKPOS[k][1]-p[1])<40))break;const h=MARKH[K[i]]||0;MARKPOS[K[i]]=[p[0]+Math.sin(h)*45,p[1]+Math.cos(h)*45]}}
// 20 city ramps on straight stretches of the real streets (lane-side, away from junctions and marks)
function rfRamps(){const out=[];for(const S of CITY_S.slice().sort((a,b)=>b.L-a.L)){if(S.r.cls==='hill')continue;const P=S.pts;for(let s=120;s<S.L-120;s+=420){const i=Math.round(s/8),p=P[i],q=P[Math.max(0,i-6)],r=P[Math.min(P.length-1,i+6)];if(Math.abs(q.tx*r.tz-q.tz*r.tx)>.08)continue;
    if(JUNC.some(J=>Math.hypot(J.x-p.x,J.z-p.z)<J.r+50)||hillH(p.x,p.z)>0||!inCity(p.x,p.z))continue;if(Object.values(MARKPOS).some(m=>Math.hypot(m[0]-p.x,m[1]-p.z)<60))continue;if(out.some(o=>Math.hypot(o[0]-p.x,o[1]-p.z)<300))continue;
    const lo=S.r.w*.22;out.push([p.x-p.tz*lo,p.z+p.tx*lo,Math.atan2(p.tx,p.tz)]);if(out.length>=20)return out}}return out}
// checkpoint run: 6 gates along the mark's street, or on the Main for the river run
function rfCheckpoints(m,river){if(river)return[850,650,480,280,120,-150].map(e=>{const P=MAINR.pts;let bi=0,bd=1e9;P.forEach((p,i)=>{const d=Math.abs(RW(p.x,p.z)[0]-e);if(d<bd){bd=d;bi=i}});return[P[bi].x,P[bi].z]});
  const q=cityAt(m.x,m.z);if(!q)return[[m.x+Math.sin(m.h)*60,m.z+Math.cos(m.h)*60]];const P=q.S.pts;let dir=Math.sin(m.h)*q.p.tx+Math.cos(m.h)*q.p.tz>=0?1:-1,i=q.i;const out=[];
  for(let k=0;k<6;k++){let j=i+dir*9;if(j<0||j>=P.length){dir=-dir;j=i+dir*9}j=clamp(j,0,P.length-1);out.push([P[j].x,P[j].z]);i=j}return out}

const markKey=m=>m.dyn?'enc:'+m.uid:m.kind==='flight'?'flight':m.kind==='garage'?(m.id&&m.id!=='g_city'?m.id:'garage'):m.kind==='season'?'season':m.kind==='rival'||m.kind==='boss'?m.ev.p:m.kind==='challenge'?m.ev.id:m.kind==='mode'?m.ev.k:m.ev.id;
let RAMPT=null;function addRamp(x,z,h,len,hgt,w,col,Y0){if(!RAMPT){const[c,g2]=cv(128,128);g2.fillStyle='#1b1c22';g2.fillRect(0,0,128,128);g2.fillStyle='#ffffff';for(let k=-128;k<256;k+=32){g2.beginPath();g2.moveTo(k,0);g2.lineTo(k+16,0);g2.lineTo(k+16-128,128);g2.lineTo(k-128,128);g2.fill()}RAMPT=tex(c);RAMPT.wrapS=RAMPT.wrapT=THREE.RepeatWrapping;RAMPT.repeat.set(2,3);KEEP_TEX.add(RAMPT)}
  const y0=Y0??Math.min(groundY(x,z),groundY(x-Math.sin(h)*len/2,z-Math.cos(h)*len/2))/* v88z: the lip sits on the ground at the low end (was the centre's height: up to 2.2 m floating step on slopes) */,g=new THREE.Mesh(new THREE.BoxGeometry(w,.6,Math.hypot(len,hgt)),new THREE.MeshStandardMaterial({color:col||0xffcd03,map:RAMPT,roughness:.45,metalness:.1,emissive:new THREE.Color(col||0xffcd03),emissiveIntensity:.15}));
  g.position.set(x,y0+hgt/2,z);g.rotation.set(-Math.atan2(hgt,len),h,0,'YXZ');g.castShadow=g.receiveShadow=true;g.userData.ramp=1;RO.grp.add(g);for(const sd of[-1,1]){const st=new THREE.Mesh(new THREE.BoxGeometry(.35,.35,Math.hypot(len,hgt)),neonMat('#ffffff',1.2));st.userData.ramp=1;st.position.set(x+Math.cos(h)*sd*w/2,y0+hgt/2+.35,z-Math.sin(h)*sd*w/2);st.rotation.copy(g.rotation);RO.grp.add(st)}
  RO.ramps.push({x,z,h,len,hgt,w,y0,dk:Y0!=null,col:col||0xffcd03})}
// 30 Athens golden bricks: hill tops (Lycabettus, the Acropolis plateau x3, Philopappou, Strefi, Ardittos, Areopagus, Tourkovounia), squares, parks, Plaka, Gazi, Koukaki, Chalandri, Psychiko and halfway up the Lycabettus road
function athGbSpots(){const A=athGbSpots0().map((s,i)=>[s[0],s[1],s[2],i]);return SM_ON?A:A.filter(s=>athIn(ATHD,...RW(s[0],s[1])))}
function athGbSpots0(){const out=[],add=(x,z)=>{for(let k=0;k<50;k++){const a=k*2.4,r=k*2,px=x+Math.cos(a)*r,pz=z+Math.sin(a)*r,gy=groundY(px,pz);if(!roamHit(px,pz,3.5,gy+1)&&!lzHit(px,pz,3.5)){out.push([px,pz,gy+2.5]);return}}out.push([x,z,groundY(x,z)+2.5])};
  for(const[e,n]of[[175,-480],[20,-530],[40,-440],[-330,-930],[-193,-400],[20,50],[-470,75],[-250,-170],[-660,260],[-1180,330],[250,-385],[1560,655],[820,-40],[1334,129],[1390,-965],[1150,-350],[840,-610],[2000,-800],[2300,150],[740,1200],[2600,650],[2050,500],[2724,736],[3100,1000],[4330,3140],[3300,2600],[5000,4300],[6350,5073],[6950,8000],[7100,5350]])add(...WP(e,n));
  const S=CITY_S.find(q=>q.r.id==='lyka');if(S){const p=S.pts[Math.floor(S.pts.length*.55)];out.push([p.x,p.z,p.y+2.5])}return out}
function buildRoam(){const grp=new THREE.Group();HUB.grp.add(grp);RO.grp=grp;RO.marks=[];RO.studs=[];RO.ramps=[];RO.built=true;const cat=roamCatalog();rfMarks();for(const L of LAZY)for(const k in L.spots){const q=L.spots[k];MARKPOS[k]=[q[0],q[1]];MARKH[k]=q[2]||0}for(const g of GARAGES)if(g.x!=null)MARKPOS[g.id]=[g.x,g.z];
  if(CID==='fra'){const g=GARAGES.find(q=>q.id==='g_fra');if(g){const sx=Math.sin(g.h),sz=Math.cos(g.h),rx=Math.cos(g.h),rz=-Math.sin(g.h);let best=null;for(const o of[60,-60,80,-80,100,-100]){const x=g.x+rx*o,z=g.z+rz*o;if(!lzHit(x,z,10)&&!roamHit(x,z,10)&&!lzHit(x+sx*26,z+sz*26,6)&&x>WX0+60&&x<WX1-60&&z>WZS+60&&z<WZN-60){best=[x,z];break}}let bq=null,bd=1e9;for(const S of LZ.roads)for(const q of S.pts){const dg=Math.hypot(q.x-g.x,q.z-g.z);if(dg<50||dg>170||lzHit(q.x,q.z,7)||roamHit(q.x,q.z,7))continue;const d=Math.hypot(q.x-g.x-rx*60,q.z-g.z-rz*60);if(d<bd){bd=d;bq=q}}MARKPOS.flight=bq?[bq.x,bq.z]:best||[g.x+rx*60,g.z+rz*60];MARKH.flight=bq?Math.atan2(bq.tx,bq.tz):g.h}}
  for(const m of cat){const p=MARKPOS[markKey(m)];if(!p)continue;m.x=p[0];m.z=p[1];m.h=MARKH[markKey(m)]??0;if(m.kind==='garage'&&m.id!=='g_city')m.h=GARAGES.find(q=>q.id===m.id).h;const y=groundY(m.x,m.z),g=new THREE.Group();g.position.set(m.x,y,m.z);
    if(m.kind==='otg'){const arch=new THREE.Mesh(new THREE.TorusGeometry(7,.5,8,40,Math.PI),neonMat(m.col,2.2));arch.rotation.y=m.h+Math.PI/2;g.add(arch);const pane=new THREE.Mesh(new THREE.CircleGeometry(7,32,0,Math.PI),new THREE.MeshBasicMaterial({color:glowCol(m.col,.8),transparent:true,opacity:.2,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));pane.rotation.y=m.h+Math.PI/2;g.add(pane);m.ring=arch;m.pane=pane}
    else{const ring=new THREE.Mesh(new THREE.TorusGeometry(9,.6,8,48),neonMat(m.col,2.4));ring.rotation.x=Math.PI/2;ring.position.y=.3;g.add(ring);m.ring=ring}
    const beam=new THREE.Mesh(new THREE.CylinderGeometry(1.6,3,140,14,1,true),new THREE.MeshBasicMaterial({color:glowCol(m.col,1),transparent:true,opacity:.28,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide}));beam.position.y=70;g.add(beam);m.beam=beam;
    const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:iconTex(m),depthWrite:false}));sp.scale.set(10,10,1);sp.position.y=m.kind==='otg'?13:12;g.add(sp);m.g=g;m.sp=sp;if(m.kind==='quest'){const f=minifig(m.col);f.position.set(Math.cos(m.h)*13,0,-Math.sin(m.h)*13);f.rotation.y=m.h-Math.PI/2;g.add(f);m.fig=f}grp.add(g);RO.marks.push(m)}
  const LJ=RO.marks.filter(m=>m.kind==='otg'&&m.ev.kind==='longjump');for(const m of LJ){const st=m.ev.id==='lj1'&&LM_BY['Eiserner Steg'];if(st){const b=st.bridge;addRamp(b.cx,b.cz,m.h,18,3.5,10,0xffcd03,deckY(b,0));m.rampAt=RO.ramps[RO.ramps.length-1];continue}const big=m.ev.id==='lj2',d=28;addRamp(m.x+Math.sin(m.h)*d,m.z+Math.cos(m.h)*d,m.h,big?26:18,big?9:5.5,12,big?0xff5a1c:0xffcd03);m.rampAt=RO.ramps[RO.ramps.length-1]}
  for(const[x,z,h]of rfRamps())addRamp(x,z,h,24,7,16,0xffb020);
  if(MTN.length)for(const[ri,si]of[[0,90],[0,260],[1,120],[2,150]]){const S=mtnSamples()[ri],a=S.pts[Math.min(si,S.pts.length-4)],b=S.pts[Math.min(si,S.pts.length-4)+3];addRamp(a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z),24,7,16,0xff5a1c)}
  {RO.pads=[];const[pc,pg]=cv(64,128);pg.fillStyle='rgba(0,0,0,0)';pg.fillRect(0,0,64,128);pg.strokeStyle='#ffd12c';pg.lineWidth=9;pg.lineCap='round';for(let k=0;k<3;k++){pg.beginPath();pg.moveTo(8,100-k*36);pg.lineTo(32,72-k*36);pg.lineTo(56,100-k*36);pg.stroke()}const pt=tex(pc);KEEP_TEX.add(pt);const pm=new THREE.MeshBasicMaterial({map:pt,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false,color:new THREE.Color(2,1.6,.8)});
   abPads(grp,pm)}
  const rnd=mul(77),sg=new THREE.CylinderGeometry(.75,.75,.32,8).rotateX(Math.PI/2),sm=new THREE.MeshStandardMaterial({color:0xffd12c,emissive:new THREE.Color('#ffb000'),emissiveIntensity:.3,metalness:.8,roughness:.3}),sb=new THREE.MeshStandardMaterial({color:0x6ad7ff,emissive:new THREE.Color('#2f9bff'),emissiveIntensity:1,metalness:.8,roughness:.25});
  const put=(x,z,y,v0)=>{if(((RO._pc=(RO._pc||0)+1)%12)!==0||roamHit(x,z,1,y))return;const v=v0>=100?40:v0>10?Math.round(v0*.4):Math.max(1,Math.round(v0*.4));RO.studs.push({x,y,z,v,m:{position:V3(x,y,z),rotation:{z:0},visible:true},alive:true,t:0})};
  {const RR=hubRoads();for(let t=0;t<420;t++){if(rnd()<.35||!RR.length){const S=CITY_S[Math.floor(rnd()*CITY_S.length)],i0=Math.floor(rnd()*Math.max(1,S.pts.length-8));for(let k=0;k<8;k++){const p=S.pts[Math.min(S.pts.length-1,i0+k)];put(p.x,p.z,groundY(p.x,p.z)+1.4,k===7&&rnd()<.2?100:10)}}else{const r=RR[Math.floor(rnd()*RR.length)],a0=rr2s(rnd,10,Math.max(11,r.L-50));for(let k=0;k<8;k++)put(r.x0+r.ux*(a0+k*5),r.z0+r.uz*(a0+k*5),1.4,k===7&&rnd()<.2?100:10)}}}
  for(const m of RO.marks)for(let k=0;k<10;k++){const a=k/10*6.28;put(m.x+Math.cos(a)*12,groundY(m.x,m.z)+1.4,m.z+Math.sin(a)*12,10)}
  for(const r of RO.ramps)for(let k=1;k<=8;k++){const d=r.len/2+k*7,y=r.y0+r.hgt+Math.sin(k/9*Math.PI)*9;put(r.x+Math.sin(r.h)*d,y,r.z+Math.cos(r.h)*d,k===4?100:10)}
  if(MAINR){const C=MAINR.pts.filter(p=>Math.abs(p.x)<HX1-60&&p.z>HZS&&p.z<HZN);for(let i=0;i<90;i++){const p=C[Math.floor(rnd()*C.length)],d=rr2s(rnd,-p.hw+10,p.hw-10);put(p.x+p.tz*d,p.z-p.tx*d,HWY+1.4,10)}}
  for(const S of mtnSamples())for(let i=20;i<S.pts.length;i+=14){const q=S.pts[i];put(q.x,q.z,tauH(q.x,q.z)+1.4,(i/14|0)%10===0?100:10)}
  RO.nR0=RO.ramps.length;abRoam(put);
  for(const L of LAZY){for(const q of L.ramps){addRamp(q[0],q[1],q[2],q[3]||24,q[4]||7,q[5]||16,q[6]||0xff5a1c);const r=RO.ramps[RO.ramps.length-1];for(let j=1;j<=8;j++){const d=r.len/2+j*8;put(r.x+Math.sin(r.h)*d,r.z+Math.cos(r.h)*d,r.y0+r.hgt+Math.sin(j/9*Math.PI)*9,j===4?100:10)}}
    for(const[x,z,v]of L.studs)if(!lzHit(x,z,1.2))put(x,z,groundY(x,z)+1.4,v||10)}
  const gs=RO.studs.filter(s=>s.v<=10),bs=RO.studs.filter(s=>s.v>10);{const gm=new THREE.MeshStandardMaterial({color:0xffc21a,emissive:new THREE.Color('#ffa000'),emissiveIntensity:.5,metalness:.55,roughness:.3}),geo=mergeG([cbox(2,1.2,2,0,0,0,'#f0b020'),...[-.5,.5].flatMap(x=>[-.5,.5].map(z=>ccyl(.42,.42,.35,x,.78,z,'#fff0a0',14)))]),/* v89i: opacity 0: the art pass squashed this 90 m beam into a 3 m white disc that read as a plinth under the brick */bmM=new THREE.MeshBasicMaterial({color:glowCol('#ffd12c',1.2),transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false});
   const spots=[];for(const r of RO.ramps.slice(0,RO.nR0))spots.push([r.x+Math.sin(r.h)*(r.len/2+34),r.z+Math.cos(r.h)*(r.len/2+34),r.y0+r.hgt+7]);
   for(const B of HUB.blocks.filter(b=>b.t==='park'||b.t==='plaza'||b.t==='yard').slice(0,6))spots.push([(B.x0+B.x1)/2,(B.z0+B.z1)/2,2.5]);for(const b of BRIDGES){const[x,z]=deckPt(b,0,b.w/2+14);spots.push([x,z,HWY+2])}{const S=LM_BY['Deutsche Bank Park'];if(S)spots.push([S.x,S.z,2.5])}
   if(CID!=='fra'){spots.length=0;spots.push(...athGbSpots())}packInit(grp);const got=roamSave().gb||[];RO.gbs=spots.slice(0,SM_ON?999:30).map(([x,z,y0,gi],i0)=>{const i=gi??i0,y=y0-1.4/* v89k: a 2×2 brick at about car-roof height (was a 4 m block on a 2.5 m pole) */;const m=new THREE.Mesh(geo,gm);m.position.set(x,y,z);m.visible=!got.includes(i);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.8,2.5,90,10,1,true),bmM);beam.position.y=45;grp.add(m);return{i,x,z,y,m,beam}})}
  RO.sim=[];bs.forEach(s=>s.big=1);for(const[L,mt]of[[gs,sm],[bs,sb]]){const q={};for(const s of L){const k=hubTile(s.x,s.z);(q[k]=q[k]||[]).push(s)}for(const k in q){const part=q[k],im=new THREE.InstancedMesh(sg,mt,part.length);part.forEach((s,i)=>{s.im=im;s.i=i});RO.sim.push(im);grp.add(im)}}studSync();for(const im of RO.sim){im.computeBoundingSphere();im.boundingSphere.radius+=40}}
const _sq=new THREE.Quaternion(),_se=new THREE.Euler();function studSync(){if(!RO.sim)return;for(const s of RO.studs){const m=s.m;if(m.visible){_se.set(0,0,m.rotation.z);_sq.setFromEuler(_se);_m.compose(m.position,_sq,_ts.setScalar(s.big?1.5:1))}else _m.makeScale(0,0,0);s.im.setMatrixAt(s.i,_m)}for(const im of RO.sim)im.instanceMatrix.needsUpdate=true}
const rr2s=(r,a,b)=>a+r()*(b-a);
function abPads(grp,pm){for(const S of abSamples()){const r=S.r,P=S.pts,step=S.L/(P.length-1);const pad=(p,o,dir)=>{const x=p.x-p.tz*o,z=p.z+p.tx*o,m=new THREE.Mesh(new THREE.PlaneGeometry(7,14),pm);m.rotation.set(-Math.PI/2,0,0);m.rotateZ(Math.atan2(-p.tx*dir,-p.tz*dir));m.position.set(x,groundY(x,z)+AB_RY(r)+.03,z);};
  if(!r.ab){pad(P[Math.max(0,P.length-5)],0,1);continue}if(r.c)continue;const lo=7.3;let k=0;for(let s=400;s<S.L-200;s+=1200,k++){const p=P[Math.round(s/step)];if(abSkip(p.x,p.z))continue;const dir=k%2?-1:1;pad(p,dir*lo,dir)}}}
function abRoam(put){for(const S of abSamples()){const r=S.r,P=S.pts,step=S.L/(P.length-1);if(!r.ab||r.c)continue;const lo=3.5;let k=0;for(let s=1000;s<S.L-200;s+=1200,k++){const p=P[Math.round(s/step)];if(abSkip(p.x,p.z,40))continue;const dir=k%2?1:-1,o=dir*lo;
    if(k%3===1){const so=dir*(r.w/2-4.5),x=p.x-p.tz*so,z=p.z+p.tx*so,h=Math.atan2(p.tx*dir,p.tz*dir);addRamp(x,z,h,24,6,7,0xff5a1c);const q=RO.ramps[RO.ramps.length-1];for(let j=1;j<=8;j++){const d=q.len/2+j*8;put(q.x+Math.sin(h)*d,q.z+Math.cos(h)*d,q.y0+q.hgt+Math.sin(j/9*Math.PI)*10,j===4?100:10)}}
    else for(let j=0;j<8;j++){const q=P[Math.min(P.length-1,Math.round(s/step)+dir*j)],x=q.x-q.tz*o,z=q.z+q.tx*o;put(x,z,groundY(x,z)+1.4,j===7&&k%4===0?100:10)}}}}
const CH_SCAT=new Set(['smash','collect','photo','wall']);function liveStars(ch){const g=ch.g||OTG_GOAL[ch.kind];if(!g)return'';let n;if(ch.hi??OTG_HI[ch.kind]){if(ch.kind!=='drift')return'';const v=ch.n||0;n=v>=g[0]?3:v>=g[1]?2:v>=g[2]?1:0}else{const t=(ch.v2&&ch.v2.L.esc?ch.away:ch.t)||0;n=t<=g[0]?3:t<=g[1]?2:t<=g[2]?1:0}return'★'.repeat(n)+'<i>'+'★'.repeat(3-n)+'</i>'}
// race widget (position, checkpoint, time, stars) + 3D beam on the current checkpoint + wrong-way warning
const CH_LBL={ball:'BALL → GOAL',checkpoint:'CHECKPOINT',smash:'PILES',collect:'BRICKS',chase:'RAMS',wall:'WALLS',photo:'PHOTOS',deliver:'CRATES',stunt:'JUMPS',taxi:'RIDES'};
function cpTargets(){const sp=RO.sp,ch=RO.ch;if(sp&&!sp.done){const a=sp.G[sp.gi],b=sp.G[sp.gi+1];return a?{a,b,last:sp.gi===sp.G.length-1,i:sp.gi+1,n:sp.G.length}:null}
  if(ch&&ch.v2){const t=qvTgt(ch),S=ch.v2.L.st[ch.v2.si];return t&&S?{a:t,b:null,last:ch.v2.si===ch.v2.L.st.length-1,i:S.ic,col:S.t==='chase'?'#ff2d55':'#ffd12c'}:null}
  if(ch&&ch.kind==='ball'&&ch.goal)return{a:{x:ch.goal[0],z:ch.goal[1]},b:null,last:false,i:'🥅'};if(ch&&ch.kind==='chase'&&ch.tg)return{a:ch.tg,b:null,last:false,i:'🚨',col:'#ff2d55'};if(ch&&ch.kind!=='checkpoint'&&(ch.cd==null||ch.cd<=0)){const t=chNext(ch)||(RO.wp&&Number.isFinite(RO.wp.x)?RO.wp:null);if(t)return{a:t,b:null,last:false,i:(BRIEF[ch.kind]||['◆'])[0],col:'#4ceaff'}}if(ch&&ch.kind==='checkpoint'){const L=ch.objs.filter(o=>!o.done);return L[0]?{a:L[0],b:L[1],last:L.length===1,i:ch.n+1,n:ch.objs.length}:null}return null}
function raceHud(){const sp=RO.sp,ch=RO.ch,el=huQ('#raceW'),on=!!((sp&&!sp.done)||(ch&&(ch.cd==null||ch.cd<=0||true)));huH(el,!on);huQ('#roam').classList.toggle('racing',on);
  const cp=cpTargets();cpBeam(cp);
  if(on){const pe=el.querySelector('.pos'),ce=el.querySelector('.cp');if(sp){huH(pe,false);const pl2=sp.place||1;huT(pe.querySelector('b'),String(pl2));huT(pe.querySelector('sup'),['ST','ND','RD'][pl2-1]||'TH');huT(pe.querySelector('small'),'/'+(sp.ai.length+1));pe.dataset.p=pl2}else huH(pe,true);
    const lbl=sp?'CHECKPOINT':ch.v2?'STAGE':CH_LBL[ch.kind],cnt=sp?`${Math.min(sp.gi+1,sp.G.length)}/${sp.G.length}`:ch.v2?(ch.v2.si+1)+'/'+ch.v2.L.st.length:ch.kind==='checkpoint'?`${Math.min(ch.n+1,ch.objs.length)}/${ch.objs.length}`:ch.kind==='chase'?`${ch.n}/3`:ch.kind==='ball'?`${Math.round(ch.gd||0)} m`:ch.kind==='drift'?String(Math.round(ch.n)):(ch.objs&&ch.objs.length?`${ch.n}/${ch.objs.length}`:'');
    huH(ce,!cnt);if(cnt){huT(ce.querySelector('small'),ch&&ch.kind==='drift'?'POINTS':lbl||'');huT(ce.querySelector('b'),cnt)}
    const t=sp?sp.t:ch.v2?ch.v2.left:ch.t;huT(el.querySelector('.tm'),fmt(Math.max(0,t||0)));const ls=ch?liveStars(ch):'';const le=el.querySelector('.lst');if(le.innerHTML!==ls)le.innerHTML=ls}
  // wrong way: moving away from the current checkpoint for a while
  let ww=false;if(cp&&Math.abs(RO.v)>12){const la=(RO.ch&&RO.ch.v2&&qvLook())||cp.a,want=Math.atan2(la.x-RO.x,la.z-RO.z),off=Math.abs(angDiff(want,RO.h));RO.wwT=off>2.1?(RO.wwT||0)+1:0;ww=RO.wwT>40}else RO.wwT=0;huH(huQ('#wrongWay'),!ww)}
function cpBeam(cp){if(!RO.cpBeam){const g=new THREE.Group(),bm=new THREE.Mesh(new THREE.CylinderGeometry(1.6,1.6,140,12,1,true),new THREE.MeshBasicMaterial({color:0xffd12c,transparent:true,opacity:.32,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide,fog:false}));bm.position.y=70;g.add(bm);
    const[c2,g2]=cv(128,128),tx=new THREE.CanvasTexture(c2),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,depthTest:false,transparent:true}));sp.scale.set(9,9,1);sp.position.y=17;sp.renderOrder=5;g.add(sp);
    const nb=new THREE.Mesh(new THREE.CylinderGeometry(1,1,100,8,1,true),new THREE.MeshBasicMaterial({color:0x4ceaff,transparent:true,opacity:.18,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide,fog:false}));nb.position.y=50;
    RO.cpBeam={g,bm,sp,c2,g2,tx,nb,last:''};scene.add(g);scene.add(nb)}
  const B=RO.cpBeam;B.g.visible=!!cp;B.nb.visible=!!(cp&&cp.b);if(!cp)return;const ya=groundAt(cp.a.x,cp.a.z,99);B.g.position.set(cp.a.x,ya,cp.a.z);B.bm.material.color.set(cp.col||(cp.last?0xffffff:0xffd12c));{const dc=Math.hypot(camera.position.x-cp.a.x,camera.position.z-cp.a.z);B.sp.visible=dc>28&&!document.body.classList.contains('crQ');B.sp.scale.setScalar(clamp(dc*.05,6,22));B.sp.position.y=12+clamp(dc*.03,0,18);B.bm.material.opacity=dc<45?.1:.32}if(cp.b)B.nb.position.set(cp.b.x,groundAt(cp.b.x,cp.b.z,99)+50,cp.b.z);
  const key=(cp.last?'FIN':String(cp.i))+(cp.col||'');if(key!==B.last){B.last=key;const g=B.g2;g.clearRect(0,0,128,128);g.fillStyle=cp.col||(cp.last?'#ffffff':'#ffd12c');g.beginPath();g.arc(64,64,56,0,7);g.fill();g.lineWidth=8;g.strokeStyle='#141413';g.stroke();g.fillStyle='#141413';g.font=/^[0-9A-Z]+$/.test(String(cp.i))&&!cp.last?'italic 900 62px system-ui':'58px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(cp.last?'🏁':String(cp.i),64,68);B.tx.needsUpdate=true}}
function hitPop(t,col){const el=$('#hitPop');if(!el)return;el.textContent=t;el.style.color=col||'#ffd400';el.hidden=false;el.classList.remove('on');void el.offsetWidth;el.classList.add('on');clearTimeout(hitPop.t);hitPop.t=setTimeout(()=>el.hidden=true,1100)}
function chNext(ch){if(ch.v2)return qvTgt(ch);const L=(ch.objs||[]).filter(o=>!o.done&&Number.isFinite(o.x)&&Number.isFinite(o.z));if(!L.length)return ch.tg||null;if(!CH_SCAT.has(ch.kind))return L[0];let b=L[0],bd=1e9;for(const o of L){const d=Math.hypot(o.x-RO.x,o.z-RO.z);if(d<bd){bd=d;b=o}}return b}
function chStart(m,o){RO.qLast={m,p0:{x:RO.x,z:RO.z,h:RO.h}};if(qvUse(m))return qvStart(m,o||{});const e=m.ev,ch={m,kind:e.kind,t:0,n:0,objs:[]};if(BRIEF[e.kind])setTimeout(()=>{if(RO.ch&&RO.ch.m===m)npcSay(e.npc?e:{id:'coach',npc:'Coach Kai',em:'🏁',col:'#ffd12c'},BRIEF[e.kind][0]+' '+BRIEF[e.kind][1]+' '+BRIEF[e.kind][2])},300);RO.ch=ch;RO.cool=3;RO.pop=null;RO.pm=null;$('#roamPop').hidden=true;$('#roamPrompt').hidden=true;for(const q of RO.marks)q.g.visible=false;const rnd=mul(e.id.length*31);
  if(e.kind==='checkpoint'){const pts=rfCheckpoints(m,e.river);
    for(const[x,z] of pts){const r=new THREE.Mesh(new THREE.TorusGeometry(6,.45,8,32),neonMat('#2f9bff',2.6));r.position.set(x,groundY(x,z)+6,z);RO.grp.add(r);ch.objs.push({x,z,m:r,done:false})}ch.objs[0].m.material=neonMat('#5dffb0',3);ch.objs.forEach((o,i)=>o.m.visible=i<2);ch.limit=OTG_GOAL.checkpoint[2]+6}
  else if(e.kind==='smash'){for(let i=0;i<60&&ch.objs.length<12;i++){const a=rnd()*6.28,d=12+rnd()*40,x=m.x+Math.cos(a)*d,z=m.z+Math.sin(a)*d;if(roamHit(x,z,3)||inRiver(x,z))continue;const g=new THREE.Group(),M=vmat(TEAMS[i%TEAMS.length]);box(g,M.a,3,1.6,3,0,.8,0);box(g,M.b,2.2,1.4,2.2,.3,2.3,.2);studs(g,M.c,[[-.5,-.5],[.5,-.5],[-.5,.5],[.5,.5]],3.1);g.position.set(x,0,z);RO.grp.add(g);ch.objs.push({x,z,m:g,done:false,col:M.a.color})}ch.limit=OTG_GOAL.smash[2]+8}
  else if(e.kind==='longjump'){ch.limit=40}
  else if(e.kind==='drift'){ch.limit=30}
  else if(e.kind==='speed'){const d=360,x=m.x+Math.sin(m.h)*d,z=m.z+Math.cos(m.h)*d,g=new THREE.Group(),r=new THREE.Mesh(new THREE.TorusGeometry(13,.8,8,40),neonMat('#ff2d95',2.8));r.position.y=6;r.rotation.y=m.h;g.add(r);for(const sd of[-1,1]){const p=new THREE.Mesh(new THREE.BoxGeometry(1,12,1),neonMat('#ffffff',1.5));p.position.set(Math.cos(m.h)*sd*13,6,-Math.sin(m.h)*sd*13);g.add(p)}g.position.set(x,groundY(x,z),z);RO.grp.add(g);ch.objs.push({x,z,m:g});ch.limit=25}
  else if(e.kind==='collect'){const gm=new THREE.MeshStandardMaterial({color:0xffc21a,emissive:new THREE.Color('#ffb000'),emissiveIntensity:.9,metalness:.8,roughness:.25});for(let i=0;i<300&&ch.objs.length<10;i++){const a=rnd()*6.28,d=30+rnd()*170,x=m.x+Math.cos(a)*d,z=m.z+Math.sin(a)*d;if(roamHit(x,z,3)||inRiver(x,z)||ch.objs.some(o=>Math.hypot(o.x-x,o.z-z)<25))continue;const g=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.4,4.8),gm);g.position.set(x,2.2,z);RO.grp.add(g);const bm=new THREE.Mesh(new THREE.CylinderGeometry(.6,1.6,40,8,1,true),new THREE.MeshBasicMaterial({color:glowCol('#ffd12c',1),transparent:true,opacity:.25,blending:THREE.AdditiveBlending,depthWrite:false}));bm.position.y=20;g.add(bm);ch.objs.push({x,z,m:g,done:false})}ch.limit=60}
  else if(e.kind==='chase'){const N=HUB.nodes;let a=0,bd=1e9;N.forEach((n,i)=>{const d=Math.hypot(n.x-m.x,n.z-m.z);if(d<bd&&d>60){bd=d;a=i}});const mat=kmMat('car').clone();mat.color=new THREE.Color(e.id==='tk2'?'#ff3b55':'#ffd12c');const g=new THREE.Mesh(kmGeo('delivery',3.2),mat);RO.grp.add(g);const sir=new THREE.Mesh(new THREE.BoxGeometry(2.4,.4,.8),neonMat('#ff2d95',3));sir.position.y=5.6;g.add(sir);
    ch.tg={a,b:N[a].nb[0],t:0,x:N[a].x,z:N[a].z,v:58,hit:0,m:g};ch.objs.push({m:g});ch.limit=60}
  else if(QK.has(e.kind))qStart(ch,m,e,rnd);
  say(e.name.toUpperCase(),e.kind==='longjump'?'HIT THE RAMP':'GO!',1.4);AU.sfx('go')}
// zoomable map: opens on the player, + / − / ⌖ buttons, drag to pan, pinch or wheel to zoom; icons always, names only when they fit
function mapIcon(m){const k=m.kind;return k==='rival'?'🚩':k==='boss'?'👑':k==='garage'?'🔧':k==='season'?'🏆':k==='sprint'?'🏁':k==='quest'?(m.ev.em||'❗'):k==='otg'?'⚡':k==='challenge'?'🏅':k==='mode'?(m.ev.icon||'🎮'):m.icon||'•'}
function mapRedraw(){if(RO.mapRaf)return;RO.mapRaf=requestAnimationFrame(()=>{RO.mapRaf=0;if(RO.mapOpen)drawRoamMap()})}
function athMapBase(g,P,W,Hh,sc,zm,dpr,inV){g.fillStyle='#e6e1d6';g.fillRect(0,0,W,Hh);const rect=(a,b,c,d,col)=>{const p=P(a,d),q=P(c,b);g.fillStyle=col;g.fillRect(p[0],p[1],q[0]-p[0],q[1]-p[1])};
  for(const d in ATH_DIST)for(const r of ATH_DIST[d].r){const[x0,z0]=WP(r[1],r[2]),[x1,z1]=WP(r[0],r[3]);rect(Math.min(x0,x1),Math.min(z0,z1),Math.max(x0,x1),Math.max(z0,z1),d===ATHD?'#f2efe9':'#e9e4da')}
  const ell=(H,col)=>{g.fillStyle=col;g.beginPath();for(let k=0;k<=36;k++){const t=k/36*Math.PI*2,u=Math.sin(t),v=Math.cos(t),de=(u*H.rx)*H.ca+(v*H.rz)*H.sa,dn=-(u*H.rx)*H.sa+(v*H.rz)*H.ca,[x,y]=P(H.cx-de*H.sx,H.cz+dn*H.sz);k?g.lineTo(x,y):g.moveTo(x,y)}g.fill()};
  for(const H of HILLS)if(H.H)ell(H,'#cddcb0');for(const H of HILLS)if(H.H>40){const I={...H,rx:H.rx*.55,rz:H.rz*.55};ell(I,'#bccf98')}
  for(const Z of ZONES){const c=Z.t==='plaza'?'#ddd8e6':Z.t==='grass'?'#c8f0c0':Z.t==='forest'?'#b8d8a0':Z.t==='dirt'?'#e8d8b8':null;if(c)rect(Z.x0,Z.z0,Z.x1,Z.z1,c)}for(const R of PARKS)rect(R.x0,R.z0,R.x1,R.z1,'#c8f0c0');for(const R of PLAZAS)rect(R.x0,R.z0,R.x1,R.z1,'#ddd8e6');
  if(sc>.1){g.fillStyle='#d9cfc5';for(const b of HUB.bld){if(!inV(b.x,b.z,40))continue;bldPaint(g,P,b,sc)}}else if(typeof urbDraw==='function')urbDraw(g,P,sc,'#d9cfc5');
  g.lineCap='round';g.lineJoin='round';const path=pts=>{g.beginPath();let on=0;pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)})};
  const ST={res:['#ffffff','#b9b2a8',.95],link:['#fcd6a4','#b8885a',.95],ped:['#ddd8e6','#a9a0b8',.9],sec:['#ffffff','#9a948a',1],main:['#f7f3a6','#a8a052',1],arterial:['#fcc98a','#a2662e',1],hill:['#efe0b8','#a89060',.9]},ORD=['ped','res','link','sec','hill','main','arterial'];
  const vis=S=>{const a=S.pts[0],b=S.pts[S.pts.length-1],m=S.pts[S.pts.length>>1];return inV(a.x,a.z,80)||inV(b.x,b.z,80)||inV(m.x,m.z,80)};const VS=CITY_S.filter(vis);
  for(const pass of[0,1])for(const c of ORD){const st=ST[c];if(!st)continue;for(const S of VS){if(S.r.cls!==c)continue;const w=Math.max((c==='res'||c==='ped'?1.3:2)*dpr,S.r.w*sc);g.lineWidth=pass?w:w+2.2*dpr;g.strokeStyle=pass?st[0]:st[1];if(c==='ped'&&pass)g.setLineDash([4*dpr,3*dpr]);path(S.pts);g.stroke();g.setLineDash([])}}
  for(const T of TRAILS){g.strokeStyle='#b07a4a';g.setLineDash([3*dpr,3*dpr]);g.lineWidth=1.5*dpr;path(T.pts);g.stroke();g.setLineDash([])}
  for(const d in ATH_DIST){const D=ATH_DIST[d];for(const r of D.r){const[x0,z0]=WP(r[1],r[2]),[x1,z1]=WP(r[0],r[3]),p=P(Math.min(x0,x1),Math.max(z0,z1)),q=P(Math.max(x0,x1),Math.min(z0,z1));g.save();g.strokeStyle=D.col;g.lineWidth=(d===ATHD?3:2)*dpr;g.setLineDash(d===ATHD?[]:[8*dpr,6*dpr]);g.strokeRect(Math.min(p[0],q[0]),Math.min(p[1],q[1]),Math.abs(q[0]-p[0]),Math.abs(q[1]-p[1]));g.restore()}
    if(d!==ATHD){const r=D.r[0],[cx,cz]=WP((r[0]+r[1])/2,(r[2]+r[3])/2);if(inV(cx,cz,600)){const[tx,tz]=P(cx,cz);g.font=`900 ${Math.round(14*dpr)}px system-ui`;g.textAlign='center';g.fillStyle='rgba(60,50,40,.55)';g.fillText(d+' · '+D.name.toUpperCase()+(SM_ON?'':' ▶'),tx,tz)}}}
  g.textAlign='center';g.textBaseline='middle';for(const G of HUB.gates||[]){if(!inV(G.x,G.z,20))continue;const[x,y]=P(G.x,G.z);g.fillStyle=ATH_DIST[G.to].col;g.beginPath();g.arc(x,y,6*dpr,0,7);g.fill();g.fillStyle='#141413';g.font=`900 ${Math.round(9*dpr)}px system-ui`;g.fillText(G.to,x,y+.5*dpr)}
  {g.save();g.beginPath();g.rect(0,0,W,Hh);for(const r of(SM_ON?Object.values(ATH_DIST).flatMap(D=>D.r):ATH_DIST[ATHD].r)){const[x0,z0]=WP(r[1],r[2]),[x1,z1]=WP(r[0],r[3]),p=P(Math.min(x0,x1),Math.max(z0,z1)),q=P(Math.max(x0,x1),Math.min(z0,z1));g.rect(Math.min(p[0],q[0]),Math.min(p[1],q[1]),Math.abs(q[0]-p[0]),Math.abs(q[1]-p[1]))}g.fillStyle='rgba(40,34,28,.42)';g.fill('evenodd');g.restore()}
  RO.athLm=[];for(const L of HUB.lmk||[]){if(!inV(L.x,L.z,40))continue;const[x,y]=P(L.x,L.z),r=Math.round(clamp(8+zm*1.4,9,16))*dpr;g.fillStyle='#fffaf0';g.strokeStyle='#7a4a1a';g.lineWidth=2*dpr;g.beginPath();g.arc(x,y,r,0,7);g.fill();g.stroke();g.font=`${Math.round(r*1.15)}px system-ui`;g.fillStyle='#141413';g.fillText(L.ic,x,y+dpr);RO.athLm.push([x,y,r,L])}
  if(zm>=1.1){g.font=`800 ${Math.round(11*dpr)}px system-ui`;for(const[x,y,r,L]of RO.athLm){const t=L.name,w=g.measureText(t).width+8*dpr;g.fillStyle='rgba(255,250,240,.9)';g.fillRect(x-w/2,y+r+2*dpr,w,15*dpr);g.fillStyle='#4a2a0a';g.fillText(t,x,y+r+9.5*dpr)}}}
function drawRoamMap(){const cvs=$('#roamMapC'),dpr=DPR2(),tw=Math.floor(cvs.clientWidth*dpr),th=Math.floor(cvs.clientHeight*dpr),g=cvs.getContext('2d');if(cvs.width!==tw||cvs.height!==th||!g.reset){cvs.width=tw;cvs.height=th}else g.reset();const W=cvs.width,Hh=cvs.height;const x0=WX0,x1=WX1,z0=WZS,z1=WZN;
  const base=SM_ON?Math.min(W,Hh)/2200:Math.min(W/(HX1-HX0),Hh/(HZN-HZT)),zmin=RO.mapZmin=Math.min(W/(x1-x0),Hh/(z1-z0))/base,zm=RO.mapZ=clamp(RO.mapZ||3,zmin,10),sc=base*zm;if(!RO.mapC)RO.mapC={x:RO.x,z:RO.z};const hw=W/2/sc,hh=Hh/2/sc;
  RO.mapC.x=clamp(RO.mapC.x,x0+Math.min(hw,(x1-x0)/2),x1-Math.min(hw,(x1-x0)/2));RO.mapC.z=clamp(RO.mapC.z,z0+Math.min(hh,(z1-z0)/2),z1-Math.min(hh,(z1-z0)/2));const cx=RO.mapC.x,cz=RO.mapC.z;
  const P=(x,z)=>[W/2-(x-cx)*sc,Hh/2-(z-cz)*sc];RO.mapP=P;RO.mapI=(px,py)=>[cx-(px-W/2)/sc,cz-(py-Hh/2)/sc];RO.mapSc=sc;const inV=(x,z,m=0)=>Math.abs(x-cx)<hw+m&&Math.abs(z-cz)<hh+m;{g.fillStyle='#16241a';g.fillRect(0,0,W,Hh);
  const rect=(a,b,c,d,col)=>{const p=P(a,d),q=P(c,b);g.fillStyle=col;g.fillRect(p[0],p[1],q[0]-p[0],q[1]-p[1])};rect(x0,z0,x1,z1,true?'#2b3a2b':'#4a4632');if(CID==='fra'){rect(x0,z0,x1,-2600,'#25402a');rect(x0,3400,x1,z1,'#3a4a2a')}for(const B of BIOMES)if(B.g!=='city'&&B.g!=='hill')rect(B.r[0],B.r[2],B.r[1],B.r[3],B.g==='field'?'#3a4a2a':B.g==='forest'?'#25402a':B.g==='air'?'#45503a':'#3d4038');rect(HX0,HZT,HX1,HZN,true?'#2b3a2b':'#5a543c');
  for(const Z of ZONES)rect(Z.x0,Z.z0,Z.x1,Z.z1,Z.t==='dirt'?'#6a4a2a':Z.t==='plaza'?'#8a7a68':Z.t==='yard'?'#55585e':Z.t==='hills'?'#35612c':'#3f7a34');rfWaterPaint(g,P,'#1f5fb0',null);
  if(sc<.5)urbDraw(g,P,sc,true?'#47514f':'#7a7258');g.fillStyle='#5a5f6a';if(sc>.12)for(const b of[...HUB.bld,...LAZY.filter(L=>!L.done).flatMap(L=>L.bld)]){if(!inV(b.x,b.z,60))continue;bldPaint(g,P,b,sc)}
  g.lineCap='round';const ln=(a,b,c,d,w)=>{const p=P(a,b),q=P(c,d);g.lineWidth=Math.max(2*dpr,w*sc*.8);g.beginPath();g.moveTo(...p);g.lineTo(...q);g.stroke()};g.strokeStyle=true?'rgba(214,220,228,.55)':'rgba(214,206,186,.45)';for(const r of hubRoads()){const p=P(r.x0,r.z0),q=P(r.x1,r.z1);g.lineWidth=Math.max(1*dpr,r.w*sc*.42);g.beginPath();g.moveTo(...p);g.lineTo(...q);g.stroke()}
  {const path=pts=>{g.beginPath();pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)})};if(zm>=1.8){g.strokeStyle='rgba(200,194,178,.32)';for(const t of LZ.roads){if(t.name!=='Odos')continue;g.lineWidth=Math.max(1*dpr,t.w*sc*.4);path(t.pts);g.stroke()}}g.strokeStyle='#cfc9bb';for(const t of LZ.roads){if(t.name==='Odos')continue;g.lineWidth=Math.max(1.5*dpr,t.w*sc*.6);path(t.pts);g.stroke()}for(const t of TRAILS){g.strokeStyle='#c9b48a';g.setLineDash([4*dpr,4*dpr]);g.lineWidth=Math.max(1.5*dpr,t.w*sc*.5);path(t.pts);g.stroke();g.setLineDash([])}for(const S of mtnSamples()){g.strokeStyle='#d6dce4';g.lineWidth=Math.max(2*dpr,S.r.w*sc*.8);path(S.pts);g.stroke()}const MAJ=c=>c==='main'||c==='ring'||c==='arterial'||c==='quay';for(const S of CITY_S){if(MAJ(S.r.cls))continue;g.strokeStyle=S.r.cls==='ped'?'#efe2c4':S.r.cls==='hill'?'#e2c79a':'#d6dce4';g.lineWidth=Math.max(1.6*dpr,S.r.w*sc*.6);if(S.r.cls==='ped')g.setLineDash([5*dpr,4*dpr]);path(S.pts);g.stroke();g.setLineDash([])}for(const[col,ex]of[['#1b1b18',3.5*dpr],['#fffaf0',0]]){g.strokeStyle=col;for(const S of CITY_S){if(!MAJ(S.r.cls))continue;g.lineWidth=Math.max(3*dpr,S.r.w*sc*.9)+ex;path(S.pts);g.stroke()}}}
  for(const S of abSamples())for(const[col,ex]of[['#5a3a10',3*dpr],['#ffb347',0]]){g.strokeStyle=col;g.lineWidth=Math.max(3*dpr,S.r.w*sc*.8)+ex;g.beginPath();S.pts.forEach((q,i)=>{const p=P(q.x,q.z);i?g.lineTo(...p):g.moveTo(...p)});g.stroke()}
  g.textAlign='center';g.textBaseline='middle';g.font=`900 ${Math.round(11*dpr)}px system-ui`;for(const S of abSamples()){if(!S.r.ab||S.r.c)continue;const st=Math.max(60,Math.round(170*dpr/(sc*10)));for(let i=Math.floor(st/2);i<S.pts.length;i+=st){const q=S.pts[i];if(!inV(q.x,q.z))continue;const[x,y]=P(q.x,q.z),w=g.measureText(S.r.id).width+10*dpr,h=16*dpr;g.fillStyle='#1f4fa8';g.fillRect(x-w/2,y-h/2,w,h);g.strokeStyle='#fff';g.lineWidth=1.5*dpr;g.strokeRect(x-w/2,y-h/2,w,h);g.fillStyle='#fff';g.fillText(S.r.id,x,y+dpr)}}}
  const ln=(a,b,c,d,w)=>{const p=P(a,b),q=P(c,d);g.lineWidth=Math.max(2*dpr,w*sc*.8);g.beginPath();g.moveTo(...p);g.lineTo(...q);g.stroke()};
  g.strokeStyle='#ffd23a';for(const b of BRIDGES){const[a1,c1]=deckPt(b,-b.half),[a2,c2]=deckPt(b,b.half);ln(a1,c1,a2,c2,b.w)}
  if(zm>=1.6){g.font=`800 ${Math.round(11*dpr)}px system-ui`;g.fillStyle=false?'#2a2a2a':'#fff';g.strokeStyle=false?'rgba(255,255,255,.9)':'rgba(0,0,0,.75)';g.lineWidth=3*dpr;const seen=new Set(),MJ=c=>c==='main'||c==='ring'||c==='arterial';for(const S of CITY_S.slice().sort((a,b)=>b.L-a.L)){if(seen.has(S.r.id)||S.r.cls==='quay'||(zm<3.5&&(!MJ(S.r.cls)||S.L<500)))continue;seen.add(S.r.id);const p=S.pts[S.pts.length>>1];if(!inV(p.x,p.z))continue;const[tx,tz]=P(p.x,p.z);g.save();g.translate(tx,tz);let an=Math.atan2(p.tz,-p.tx);if(an>Math.PI/2)an-=Math.PI;if(an<-Math.PI/2)an+=Math.PI;g.rotate(an);const nm=S.r.name.split(' → ')[0];g.strokeText(nm,0,-3*dpr);g.fillText(nm,0,-3*dpr);g.restore()}}
  {const a=P(x0,z1),b=P(x1,z0);g.save();g.setLineDash([10*dpr,7*dpr]);g.strokeStyle='#ff5a3c';g.lineWidth=3*dpr;g.strokeRect(Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]));g.restore()}
  g.textAlign='center';g.textBaseline='middle';g.font=`italic 900 ${Math.round(clamp(9+zm*1.6,10,22))*dpr}px system-ui`;g.fillStyle=false?'rgba(90,60,40,.42)':'rgba(255,255,255,.28)';
  for(const d of DIST_R){if(d.dup)continue;const dx=(Math.max(d.x0,x0)+Math.min(d.x1,x1))/2,dz=(Math.max(d.z0,z0)+Math.min(d.z1,z1))/2;if(inV(dx,dz,300)){const[tx,tz]=P(dx,dz);g.fillText(d.name.toUpperCase(),tx,tz)}}
  qvMapPath(g,P,dpr);
  // markers: icons first, then labels that do not overlap (nearest to the player first)
  const R0=Math.round(clamp(7+zm*1.2,9,15))*dpr,used=[],ms=RO.marks.filter(m=>inV(m.x,m.z,80)&&markKnown(m)).sort((a,b)=>(a===RO.wp?-1:b===RO.wp?1:0)||Math.hypot(a.x-RO.x,a.z-RO.z)-Math.hypot(b.x-RO.x,b.z-RO.z));
  g.font=`${R0*1.15}px system-ui`;for(const m of ms){const[x,z]=P(m.x,m.z),lk=markLocked(m),dn=markDone(m);g.globalAlpha=lk?.4:1;g.fillStyle=dn?'#3a4652':'#0b1626';g.beginPath();g.arc(x,z,R0,0,7);g.fill();g.lineWidth=2.5*dpr;g.strokeStyle=RO.wp===m?'#ffffff':dn?'#7a8a9a':m.col;g.stroke();g.fillStyle='#fff';g.fillText(dn?'✔':mapIcon(m),x,z+dpr);g.globalAlpha=1;const st=markStars(m);if(st){g.font=`900 ${Math.round(R0*.7)}px system-ui`;g.fillStyle='#ffd12c';g.fillText('★'.repeat(st),x,z+R0+6*dpr);g.font=`${R0*1.15}px system-ui`}used.push([x-R0,z-R0,x+R0,z+R0+8*dpr])}
  if(zm>=2.2){g.font=`700 ${Math.round(11*dpr)}px system-ui`;for(const m of ms){if(markLocked(m))continue;const[x,z]=P(m.x,m.z),t=markTitle(m),w=g.measureText(t).width+8*dpr,h=15*dpr,bx=[x-w/2,z-R0-h-2*dpr,x+w/2,z-R0-2*dpr];if(used.some(u=>bx[0]<u[2]&&bx[2]>u[0]&&bx[1]<u[3]&&bx[3]>u[1]))continue;used.push(bx);g.fillStyle='rgba(5,11,24,.78)';g.fillRect(bx[0],bx[1],w,h);g.fillStyle=markDone(m)?'#9fb0c0':'#fff';g.fillText(t,x,(bx[1]+bx[3])/2)}}
  qvMapPins(g,P,inV,R0,dpr);PIN_mapDraw(g,P,dpr,R0);{const m=flightMark();if(m&&inV(m.x,m.z,80)){const[fx,fz]=P(m.x,m.z),lk=markLocked(m),t=lk?`🔒 ${fraFlags()}/${ATH_NEED} FLAGS`:true?'FLIGHTS ✈ ATHENS':'FLIGHTS ✈ FRANKFURT';g.save();g.textAlign='center';g.textBaseline='middle';g.font=`900 ${Math.round(10*dpr)}px system-ui`;const w=g.measureText(t).width+10*dpr,y0=fz+R0+(markStars(m)?16:6)*dpr;if(!lk){const ex=true?W:0,ey=true?Hh:0;g.setLineDash([8*dpr,8*dpr]);g.strokeStyle='rgba(127,212,255,.75)';g.lineWidth=2.5*dpr;g.beginPath();g.moveTo(fx,fz);g.quadraticCurveTo((fx+ex)/2+(true?1:-1)*W*.08,(fz+ey)/2-Hh*.18,ex,ey);g.stroke();g.setLineDash([])}if(lk){g.fillStyle='rgba(5,11,24,.85)';g.fillRect(fx-w/2,y0,w,15*dpr);g.fillStyle='#9fb0c0';g.fillText(t,fx,y0+8*dpr)}g.restore()}}
  const[px,pz]=P(RO.x,RO.z);g.save();g.translate(px,pz);g.rotate(-RO.h);g.fillStyle='#fff';g.strokeStyle='#000';g.lineWidth=2*dpr;g.beginPath();g.moveTo(0,-15*dpr);g.lineTo(10*dpr,11*dpr);g.lineTo(-10*dpr,11*dpr);g.closePath();g.fill();g.stroke();g.restore()}

// ---------- City sprints: point-to-point races through free roam (2K-style, no loading)
function spSave(){return roamSave().sp||{}}
function spGates(e){const G=[],P=e.path;let cum=0;for(let i=1;i<P.length;i++){const[a,b]=[P[i-1],P[i]],L=Math.hypot(b[0]-a[0],b[1]-a[1]),n=Math.max(1,Math.round(L/320));for(let k=1;k<=n;k++){const t=k/n;G.push({x:a[0]+(b[0]-a[0])*t,z:a[1]+(b[1]-a[1])*t,h:Math.atan2(b[0]-a[0],b[1]-a[1]),cum:cum+L*t})}cum+=L}return G}
function spPos(e,s){const P=e.path;let cum=0;for(let i=1;i<P.length;i++){const a=P[i-1],b=P[i],L=Math.hypot(b[0]-a[0],b[1]-a[1]);if(s<=cum+L||i===P.length-1){const t=clamp((s-cum)/L,0,1);return{x:a[0]+(b[0]-a[0])*t,z:a[1]+(b[1]-a[1])*t,h:Math.atan2(b[0]-a[0],b[1]-a[1]),toCorner:cum+L-s,i}}cum+=L}}
function sprintStart(m){const e=m.ev,G=spGates(e);const ring=new THREE.TorusGeometry(15,.9,8,40);const sp={e,m,G,gi:0,t:0,cd:3,ai:[],objs:[],done:false};RO.sp=sp;RO.pop=null;
  G.forEach((g,i)=>{const last=i===G.length-1,mesh=new THREE.Mesh(ring,neonMat(last?'#ffffff':'#5dffb0',last?3:2.4));mesh.position.set(g.x,groundAt(g.x,g.z,99)+9,g.z);mesh.rotation.y=g.h;mesh.visible=i<2;RO.grp.add(mesh);g.mesh=mesh;sp.objs.push(mesh)});
  const s0=spPos(e,0);RO.x=s0.x-Math.sin(s0.h)*6;RO.z=s0.z-Math.cos(s0.h)*6;RO.y=groundAt(RO.x,RO.z,1);RO.h=RO.vh=s0.h;RO.v=0;RO.vy=0;RO.yr=0;camSnap=true;
  e.ai.forEach((p,i)=>{const pd=PD[p],team=vehOf(p)||(pd?teamOf(pd):TEAMS[i%6]),g=shipMesh(team);RO.grp.add(g);sp.objs.push(g);const lane=[-1,1][i%2]*(5+4*Math.floor(i/2));sp.ai.push({p,name:pd?pd.full:p,g,s:-10-i*7,lane,v:0,base:(68+i*2.5+(chapter()-1)*2.5)*diffMul(),fin:null})});
  RO.card=null;$('#roamCard').hidden=true;say(e.name.toUpperCase(),'CITY SPRINT · '+(e.len/1000).toFixed(1)+' km',1.2);AU.sfx('pick')}
function sprintStep(dt){const sp=RO.sp;if(!sp)return;const e=sp.e;RO.cool=2;
  if(sp.cd>0){const c0=Math.ceil(sp.cd);sp.cd-=dt;RO.v=0;if(Math.ceil(sp.cd)!==c0&&sp.cd>0){say(String(Math.ceil(sp.cd)),'',.6);AU.sfx('beep')}if(sp.cd<=0){say('GO!','',.8);AU.sfx('go')}}else if(!sp.done)sp.t+=dt;
  // player progress through the gates
  const g=sp.G[sp.gi];if(g&&!sp.done&&sp.cd<=0&&Math.hypot(g.x-RO.x,g.z-RO.z)<17){g.mesh.visible=false;sp.gi++;AU.sfx('pick');comboAdd(1);if(sp.gi>=sp.G.length)return sprintFinish();const n1=sp.G[sp.gi],n2=sp.G[sp.gi+1];n1.mesh.visible=true;n1.mesh.material=neonMat(sp.gi===sp.G.length-1?'#ffffff':'#ffd12c',3);if(n2)n2.mesh.visible=true}
  const ng=sp.G[sp.gi];if(ng)RO.wp={x:ng.x,z:ng.z,kind:'gate',name:sp.gi===sp.G.length-1?'Finish':'Checkpoint '+(sp.gi+1)+'/'+sp.G.length};
  const myS=ng?ng.cum-Math.hypot(ng.x-RO.x,ng.z-RO.z):e.len;sp.myS=myS;
  // rivals drive the route: slow for corners, rubber band toward the player
  for(const a of sp.ai){if(a.fin!=null&&a.s>=e.len+40){continue}const q=spPos(e,Math.max(0,a.s));const gap=a.s-myS,rub=gap>150?.9:gap<-150?1.12:1;let tv=a.base*rub;if(q.toCorner<60&&q.i<e.path.length-1)tv=Math.min(tv,38);
    if(sp.cd>0)tv=0;a.v+=(tv-a.v)*Math.min(1,dt*(tv>a.v?1.8:2.5));a.s+=a.v*dt;if(a.s>=e.len&&a.fin==null)a.fin=sp.t;
    const p2=spPos(e,Math.max(0,a.s)),ox=Math.cos(p2.h)*a.lane,oz=-Math.sin(p2.h)*a.lane,x=p2.x+ox,z=p2.z+oz;a.y=groundAt(x,z,(a.y??0)+3);a.h=(a.h??p2.h)+angDiff(p2.h,a.h??p2.h)*Math.min(1,dt*4);
    a.g.position.set(x,a.y,z);a.g.rotation.y=a.h+Math.PI;const ud=a.g.userData;ud.m.position.y=1.6+Math.sin(T*6+a.lane)*.1;for(const rb of ud.ribbons){rb.scale.z=6+a.v/8;rb.material.uniforms.uT.value=T}
    const d=Math.hypot(x-RO.x,z-RO.z);if(d<5.5&&Math.abs(a.y-RO.y)<3){const k=(5.5-d)/2;RO.x+=(RO.x-x)/d*k;RO.z+=(RO.z-z)/d*k;if(Math.abs(RO.v)>a.v+15&&pl&&pl.nitro){a.v*=.3;feed('SLAM · '+a.name,300,'#ff2d95');AU.sfx('crash');shake=.4;comboAdd(3)}else{a.v*=.9;RO.v*=.95;AU.sfx('bump')}}}
  const place=1+sp.ai.filter(a=>(a.fin!=null?e.len+1e6-a.fin:a.s)>myS).length;sp.place=place;
  sp.hud=`<b>🏁 ${e.name.toUpperCase()}</b><span>POS ${place}/${sp.ai.length+1} · CP ${Math.min(sp.gi,sp.G.length)}/${sp.G.length} · ${fmt(Math.max(0,sp.t))} · Esc to quit</span>`}
function spHud(){if(RO.sp&&RO.sp.hud)huTop(RO.sp.hud)}
function sprintEnd(){const sp=RO.sp;if(!sp)return;for(const o of sp.objs)RO.grp.remove(o);RO.sp=null;RO.wp=null;RO.cool=3}
function sprintFinish(){const sp=RO.sp,e=sp.e;sp.done=true;const place=1+sp.ai.filter(a=>a.fin!=null&&a.fin<sp.t).length,stars=place===1?3:place===2?2:place===3?1:0;
  const o=roamSave();o.sp=o.sp||{};const prev=o.sp[e.id]||{st:0,best:0};const nb=!prev.best||sp.t<prev.best;o.sp[e.id]={st:Math.max(prev.st,stars),best:nb?sp.t:prev.best};roamStore(o);
  const all=store.get('mho_stars',{}),key='sprint:'+e.id,best=all[key]||0,pay=1700,fresh=Math.max(0,stars-best),cr=Math.round(pay*fresh+pay*(best>=3?.2:.3)*Math.min(stars,best)),xp=Math.round(130*(fresh+(best>=3?.1:.25)*Math.min(stars,best)));const gift=stars===3&&best<3?rewardItem():'';logDone(key,e.name,'sprint',stars,fmt2(sp.t));if(stars>best){all[key]=stars;store.set('mho_stars',all)}if(cr){const S=season();S.cr+=cr;saveSeason(S)}if(xp)addXP(xp);
  const rows=[{n:'YOU',t:sp.t,me:1},...sp.ai.map(a=>({n:a.name,t:a.fin!=null?a.fin:null}))].sort((a,b)=>(a.t??1e9)-(b.t??1e9));
  const el=$('#spRes');el.hidden=false;el.innerHTML=`<h3>${place===1?'1ST · YOU WIN!':ord(place)+' PLACE'}</h3><div class="st">${'★'.repeat(stars)}<i>${'★'.repeat(3-stars)}</i></div><p>${e.name} · ${fmt2(sp.t)}${nb?' · NEW BEST':''}</p><p>+<b>${cr.toLocaleString('de-DE')}</b> studs · +<b>${xp}</b> XP${fresh?` · ${fresh} new ★`:stars?' · replay (30%)':''}${gift?`<br>🎁 <b>NEW GARAGE PART: ${gift}</b>`:''}</p><table>${rows.map((r,i)=>`<tr class="${r.me?'me':''}"><td>${i+1}</td><td>${r.n}</td><td>${r.t!=null?fmt2(r.t):'—'}</td></tr>`).join('')}</table><div class="rcb"><button class="go" id="spAgain">RACE AGAIN</button><button class="go alt" id="spOk">CONTINUE</button></div>`;
  AU.sfx(stars?'finish':'crash');$('#spOk').onclick=()=>{el.hidden=true};$('#spAgain').onclick=()=>{el.hidden=true;const m=sp.m;sprintStart(m)};sprintEnd()}
// ---------- first-time tutorial with Hilde
const TUT=[{t:'Drive! Hold ↑ (on touch it accelerates by itself).',tt:'Drive! Your car accelerates by itself — steer with ◀ ▶.',ok:()=>Math.abs(RO.v)*3.6>150},
 {t:'Hold SHIFT for TURBO. Smashing things refills the bar.',tt:'Hold BOOST for TURBO. Smashing things refills the bar.',ok:()=>(RO.boostT||0)>.8},
 {t:'Hold X and steer to DRIFT. Release for a mini-turbo!',tt:'Hold DRIFT and steer to slide. Release for a mini-turbo!',ok:()=>RO.tutTurbo},
 {t:'Press SPACE to HOP over traffic.',tt:'Tap HOP to jump over traffic.',ok:()=>RO.tutHop},
 {t:'Smash 10 things in a row to build a CHAIN — studs multiply!',tt:'Smash 10 things in a row to build a CHAIN — studs multiply!',ok:()=>CB.n>=10},
 {t:'Glowing beacons start races and events. 🏁 EVENTS shows them all on the map. Have fun!',tt:'Glowing beacons start races and events. 🏁 EVENTS shows them all on the map. Have fun!',ok:()=>RO.tutT>6}];
function tutStep(dt){const o=store.peek('mho_roam',{});if(o.tut||RO.sp||RO.ch||RO.story)return $('#roamTut').hidden=true;RO.tutI=RO.tutI||0;const s=TUT[RO.tutI];const el=$('#roamTut');el.hidden=false;
  el.querySelector('img').src=avatar('HILDE');el.querySelector('p').textContent=TOUCH.on?s.tt:s.t;el.querySelector('small').textContent=`TUTORIAL ${RO.tutI+1}/${TUT.length}`;RO.tutT=(RO.tutT||0)+dt;RO.tutShow=(RO.tutShow||0)+dt;el.classList.toggle('min',RO.tutShow>6);
  if(RO.tutT>1.2&&s.ok()||RO.tutT>25){RO.tutI++;RO.tutT=0;RO.tutShow=0;AU.sfx('pick');if(RO.tutI>=TUT.length)tutDone(true)}}
function tutDone(fin){const o=roamSave();o.tut=1;roamStore(o);$('#roamTut').hidden=true;if(fin){const S=season();S.cr+=500;saveSeason(S);addXP(50,'tutorial');say('TUTORIAL DONE','+500 studs',1.6)}}
function roamCatalog(){const GL=GARAGES.filter(g=>CID==='fra'||SM_ON||(g.x==null?ATHD==='A':athIn(ATHD,...RW(g.x,g.z)))).map(g=>({kind:'garage',id:g.id,name:g.x==null&&CID==='fra'?'Garage':g.name,icon:'🔧',col:'#5dffb0'})),FL={kind:'flight',id:'fl_'+CID,name:CID==='fra'?'✈ Flights · Athens':'✈ Flights · Frankfurt',icon:'✈',col:'#7fd4ff'};if(CID!=='fra')return SM_ON||ATHD==='A'?[...GL,FL]:GL;const L=[...GL,{kind:'season',name:'Grand Prix Stadium',icon:'🏆',col:'#ffd12c'}];
  RIVAL_EV.forEach(e=>L.push({kind:'rival',ev:e,col:'#4ceaff'}));L.push({kind:'boss',ev:BOSS_EV,col:'#ff2a4a'});EVENTS.forEach((e,i)=>L.push({kind:'challenge',ev:e,idx:i,icon:'🏅',col:'#ff9a3c'}));
  MODE_EV.forEach(e=>L.push({kind:'mode',ev:e,icon:e.icon,col:'#c46bff'}));OTG.forEach(e=>L.push({kind:'otg',ev:e,col:'#2f9bff'}));SPRINTS.forEach(e=>L.push({kind:'sprint',ev:e,icon:'🏁',col:'#5dffb0'}));QUESTS.forEach(e=>L.push({kind:'quest',ev:e,icon:e.em,col:e.col}));L.push(FL);return L}
function markTitle(m){const k=m.kind,e=m.ev;return k==='rival'||k==='boss'?PD[e.p].full:k==='challenge'?e.name:k==='mode'?e.name:k==='otg'?e.name:k==='quest'?e.npc+' · '+e.name:k==='sprint'?e.name:m.name}
function markDone(m){if(m.dyn)return false;const F=flagsR(),k=m.kind,e=m.ev,RS=()=>store.peek('mho_roam',{});if(k==='rival')return !!F[e.p];if(k==='boss')return !!F.SKYCUP;if(k==='challenge')return (store.peek('mho_career',{})[e.id]||0)>=1;if(k==='otg'||k==='quest')return ((RS().otg||{})[e.id]||0)>=1;if(k==='sprint')return (((RS().sp||{})[e.id]||{}).st||0)>=3;return false}
const disc=()=>store.get('mho_disc',[]);let DISC=null;
const ftGar=m=>m.kind==='garage'&&!!m.id&&m.id!=='g_city';
function markKnown(m){if(m.dyn)return !!m.disc;if(m.sq)return true;if(m.kind==='flight')return true;if(markLocked(m))return false;if(!['otg','quest'].includes(m.kind)&&!ftGar(m))return true;if(markDone(m))return true;if(!DISC)DISC=new Set(disc());return DISC.has(markKey(m))}
function discover(m){if(m.dyn)return qvDisc(m);if(m.kind==='flight')return;if(!DISC)DISC=new Set(disc());const k=markKey(m);if(DISC.has(k))return;DISC.add(k);store.set('mho_disc',[...DISC]);if(['otg','quest'].includes(m.kind))feed('📍 NEW · '+markTitle(m).toUpperCase(),0,m.col||'#4ceaff');else if(ftGar(m))feed('🔧 FAST TRAVEL · '+markTitle(m).toUpperCase(),0,'#5dffb0')}
function ftShow(m){const b=$('#roamFT');if(!b)return;if(m&&(m.kind==='garage'&&markKnown(m)||m.kind==='flight'&&!markLocked(m)&&flyFT())){RO.ftSel=m;b.hidden=false;b.textContent='⚡ FAST TRAVEL · '+markTitle(m).toUpperCase()}else{RO.ftSel=null;b.hidden=true}}
function fastTravel(m,now){if(!m||!RO.on)return false;const t=performance.now()/1000;if(RO.ch||RO.sp){say('','FINISH THE EVENT FIRST',1.2);return false}if(t<(RO.ftT||0)){say('','FAST TRAVEL IN '+Math.ceil(RO.ftT-t)+' s',1);return false}RO.ftT=t+15;ftShow(null);if(RO.mapOpen)toggleMap(false);
  const go=()=>{roamWarp(m.x+Math.sin(m.h)*26,m.z+Math.cos(m.h)*26,m.h);RO.cool=2;say('',('⚡ '+markTitle(m)).toUpperCase(),1.4);AU.sfx('boost');if(m.kind==='flight')setTimeout(()=>{if(RO.on&&!RO.card){roamOpen(m);RO.cardPin=1}},600)};const need=lzNeed(m.x+Math.sin(m.h)*26,m.z+Math.cos(m.h)*26);if(now){for(const L of need)lzRun(L);go();return true}if(need.length){ldTravel(go,need);return true}if(Math.hypot(m.x-RO.x,m.z-RO.z)>1500){ldFlash(go);return true}const f=$('#warpFade');if(f)f.classList.add('on');setTimeout(()=>{go();if(f)f.classList.remove('on')},260);return true}
function markStars(m){const all=store.peek('mho_stars',{}),k=m.kind,e=m.ev;const key=k==='rival'?'rival:'+e.p:k==='boss'?'boss:'+e.p:k==='otg'||k==='quest'?'otg:'+e.id:k==='sprint'?'sprint:'+e.id:k==='challenge'?'challenge:'+e.id:null;return key?all[key]||0:0}
function markLocked(m){if(m.kind==='flight')return !flyOpen();if(markCh(m)>chapter())return true;if(m.kind==='boss')return !roamBossOpen();if(m.kind==='challenge')return !unlocked(m.idx);return false}
function iconTex(m){const[c,g]=cv(128,128);g.fillStyle='rgba(3,14,26,.9)';g.beginPath();g.arc(64,64,58,0,7);g.fill();g.lineWidth=7;g.strokeStyle=m.col;g.stroke();
  if(m.kind==='rival'||m.kind==='boss'){g.save();g.beginPath();g.arc(64,64,52,0,7);g.clip();g.drawImage(avatarCv(m.ev.p),12,12,104,104);g.restore();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
  g.font='64px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillStyle='#fff';g.fillText(m.kind==='otg'?({checkpoint:'⭕',longjump:'🛫',drift:'🌀',speed:'📸',collect:'🪙',chase:'🚓'}[m.ev.kind]||'🧱'):m.icon,64,70);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function enterRoam(atMark){if(LD.busy)return LD.busy;if(!RO.built)return LD.busy=roamLoad(atMark);roamPre();setupRace(ROAMCFG);hubEnter();roamPost(atMark)}
const ROAMCFG={type:'roam',laps:999,traffic:0,items:false,aggr:0,track:'hafen',mood:'night'};
function roamPre(){chAbort();if(RO.wk){RO.wk=null;if(RBRK)RBRK.visible=false}RO.hp=100;RO.inv=0;if(RO.sp)sprintEnd();RO.tutI=0;RO.tutT=0;if(CM.on)cmClose();PK=perkSet();$('#tF').textContent='HOP';menuTab='quick'}
function roamPost(atMark){RO.tEnter=performance.now();state='roam';RO.on=true;RO.card=null;DISC=null;RO.frozen=false;RO.jOpen=false;RO.cool=1.5;RO.ch=null;RO.fromRoam=false;
  $('#menu').hidden=true;$('#results').hidden=true;$('#hud').hidden=true;$('#roam').hidden=false;$('#roamCard').hidden=true;$('#roamMap').hidden=true;RO.mapOpen=false;$('#journal').hidden=true;$('#spRes').hidden=true;$('#npcSay').hidden=true;clearTimeout(npcSay.t);clearTimeout(chEnd.q);$('#touch').hidden=!TOUCH.on;document.body.dataset.tc=SET.touch;document.body.classList.add('racing');document.body.dataset.mode='roam';
  if(!RO.built)buildRoam();const sv=roamSave();{const gg=sv.gb||[],pk=packs();(RO.gbs||[]).forEach(g=>g.m.visible=!gg.includes(g.i));(RO.packs||[]).forEach(p=>p.m.visible=!pk.includes(p.i))}RO.vsel=sv.vsel||'auto';$('#roamVeh').textContent='⟳ '+VNAME[RO.vsel];const fm=RO.arrive?flightMark():null;RO.arrive=null;const m0=atMark&&RO.marks.includes(atMark)?atMark:fm||(SM_ON&&RO.marks.find(m=>m.kind==='garage'&&SM_dz(m.x,m.z)===ATHD))||RO.marks.find(m=>m.kind==='garage');
  if(sv.pos&&sv.lay!==LAYOUT_VER){delete sv.pos;sv.lay=LAYOUT_VER;roamStore(sv)}
  if(!atMark&&!fm&&sv.pos&&!roamHit(sv.pos.x,sv.pos.z,3,sv.pos.y)){RO.x=sv.pos.x;RO.z=sv.pos.z;RO.h=sv.pos.h;RO.y=sv.pos.y}
  else if(m0){RO.h=m0.h;RO.x=m0.x+Math.sin(m0.h)*26;RO.z=m0.z+Math.cos(m0.h)*26;if(roamHit(RO.x,RO.z,3)){RO.x=m0.x+Math.cos(m0.h)*12;RO.z=m0.z-Math.sin(m0.h)*12}RO.y=groundY(RO.x,RO.z)}
  RO.y=groundAt(RO.x,RO.z,RO.y??0);if(CID!=='ath'||!(BOOTF&&BOOTF.athv))roamFaceOpen();RO.v=0;RO.vy=0;if(CID==='ath'&&BOOTF&&BOOTF.snap&&!atMark){const q=rfSnap(RO.x,RO.z,250);if(q){RO.x=q[0];RO.z=q[1];RO.h=q[2];RO.y=groundY(RO.x,RO.z)}BOOTF.snap=0}if(CID==='ath'&&BOOTF&&BOOTF.athv&&!atMark){RO.v=BOOTF.athv;BOOTF.athv=0}RO.yr=0;RO.story=false;$('#story').hidden=true;pl.air=null;pl.bm=60;camSnap=true;roamHud();if(!storyCheck()&&!atMark)say(fm?CCF.arrTxt.toUpperCase():CCF.career,`${CID==='fra'?'CHAPTER':CCF.ch.toUpperCase()} ${chapter()} · ${CHS()[chapter()-1].title.toUpperCase()}`,2.6)}
// ---- Athens Stage A: travel between the cities (reload-based: save, per-slot city key, boot flag, loader, reload; boot goes straight into roam)
const ATH_NEED=4,fraFlags=()=>{const F=flagsR();return RIVAL_EV.filter(e=>F[e.p]).length},athPre=ALL_OPEN||(()=>{try{const q=new URLSearchParams(location.search);if(q.has('athens')){localStorage.setItem('mho_athpre','1');history.replaceState(null,'',location.pathname+location.hash)}return localStorage.getItem('mho_athpre')==='1'}catch(e){return false}})(),flyOpen=()=>CID!=='fra'||athPre||fraFlags()>=ATH_NEED;
function flightMark(){return RO.marks?RO.marks.find(m=>m.kind==='flight'):null}
const flyFT=()=>{if(CID!=='fra'||athPre)return true;const g=RO.marks&&RO.marks.find(q=>q.kind==='garage'&&q.id==='g_fra');return !!g&&markKnown(g)};
function cityTravel(to){to=to||CCF.to;if(to===CID||!CITYCFG[to]||LD.busy||LD.fly||!flyOpen())return false;pstatFlush();if(RO.on&&RO.built&&!(pl&&pl.air))roamSavePos();
  if(CID==='fra'){const st=store.get('mho_story',{seen:0,end:0});if(!st.fly){st.fly=1;store.set('mho_story',st)}}
  try{const K='mho_roam'+(to==='fra'?'':'.'+to)+'@'+SLOT,o=JSON.parse(localStorage.getItem(K)||'null')||{otg:{},studs:[]};if(!o.tut){o.tut=1;localStorage.setItem(K,JSON.stringify(o))}localStorage.setItem('mho_city@'+SLOT,to)}catch(e){return false}
  const f=JSON.stringify({go:'roam',arrive:'flight',from:CID,to,t:Date.now()});let ok=false;try{sessionStorage.setItem('mho_boot',f);ok=sessionStorage.getItem('mho_boot')===f}catch(e){}if(!ok)try{localStorage.setItem('mho_boot',f)}catch(e){}
  RO.on=false;RO.frozen=true;if(pl){AU.engine(pl,0,false);AU.scrape(false)}if(RO.mapOpen)toggleMap(false);LD.fly={a:CCF.code,b:CITYCFG[to].code,to};ldShow(CCF.flyTxt);ldSet(.4);setTimeout(()=>ldSet(1),150);setTimeout(()=>location.reload(),700);return true}
function flyRoute(){const m=flightMark();if(!m)return;RO.wp=m;pickAdd(m);toggleMap(true);RO.mapC={x:m.x,z:m.z};drawRoamMap();ftShow(m);say('','ROUTE · ✈ FLIGHTS',1.6)}
function slotInfo(n){const g=k=>{try{const v=localStorage.getItem(k+'@'+n);return v?JSON.parse(v):null}catch(e){return null}};const pr=g('mho_prof'),F=g('mho_flags')||{},S=g('mho_season')||{},st=g('mho_story');if(!pr&&!st&&!g('mho_roam'))return null;const xp=(pr&&pr.xp)||0,l=lvlOf(xp),nf=RIVAL_EV.filter(e=>F[e.p]).length;
  let ch=1;for(const C of CHAPTERS)if(nf>=C.need)ch=C.n;let city='fra';try{city=localStorage.getItem('mho_city@'+n)==='ath'?'ath':'fra'}catch(e){}return{l,nf,ch,cr:S.cr||0,cup:!!F.SKYCUP,last:st&&st.last,city}}
function showSlots(){const L=$('#slotList');L.innerHTML='';for(let n=1;n<=3;n++){const I=slotInfo(n),d=document.createElement('div');d.className='slot';
  d.innerHTML=I?`<div><b>Slot ${n}${I.city==='ath'?' · 📍 Athens':''} · Chapter ${I.ch}${I.cup?' · 🏆':''}</b><small>Level ${I.l} · Class ${I.l>=20?'A':I.l>=10?'B':'C'} · 🚩 ${I.nf}/8 flags · ${I.cr.toLocaleString('de-DE')} studs${I.last?' · '+new Date(I.last).toLocaleDateString():''}</small></div>`:`<div><b>Slot ${n} · empty</b><small>Start a new career in Frankfurt.</small></div>`;
  const sb=document.createElement('div');sb.className='sb';const go=document.createElement('button');go.className='go';go.textContent=I?'CONTINUE':'NEW GAME';go.onclick=()=>{const want=I?I.city:'fra';if(want!==CID){try{localStorage.setItem('mho_slot',n)}catch(e){}const f=JSON.stringify({go:'roam',t:Date.now()});try{sessionStorage.setItem('mho_boot',f)}catch(e){try{localStorage.setItem('mho_boot',f)}catch(_){}}$('#slots').hidden=true;ldShow('Loading slot '+n+' · '+CITYCFG[want].name);setTimeout(()=>location.reload(),200);return}SLOT=n;_SC.clear();try{localStorage.setItem('mho_slot',n)}catch(e){}$('#slots').hidden=true;RO.wp=null;enterRoam()};sb.appendChild(go);
  if(I){const del=document.createElement('button');del.className='go alt';del.textContent='DELETE';del.onclick=()=>{if(!confirm(`Delete save slot ${n}? This cannot be undone.`))return;for(const k of CK)localStorage.removeItem(k+'@'+n);for(const k of CITYK)localStorage.removeItem(k+'.ath@'+n);showSlots()};sb.appendChild(del)}d.appendChild(sb);L.appendChild(d)}$('#slots').hidden=false}
function exitRoam(){pstatFlush();if(RO.sp)sprintEnd();if(RO.on&&!(pl&&pl.air))roamSavePos();RO.on=false;chAbort();clearTimeout(chEnd.q);$('#roam').hidden=true;toMenu()}
