// ---- track deck as a drivable road in free roam
const VSEL=['auto','ship','boat','offroad'],VNAME={auto:'AUTO',ship:'SHIP',boat:'BOAT',offroad:'4×4'};
function cycleVehicle(){RO.vsel=VSEL[(VSEL.indexOf(RO.vsel||'auto')+1)%4];if(RO.vsel==='boat'&&!WATERS.length)RO.vsel=VSEL[(VSEL.indexOf('boat')+1)%4];const o=roamSave();o.vsel=RO.vsel;roamStore(o);say('',`VEHICLE · ${VNAME[RO.vsel]}`,.8);AU.sfx('brick');$('#roamVeh').textContent='⟳ '+VNAME[RO.vsel]}
function roamFaceOpen(){let best=RO.h,bs=-1;for(let k=0;k<16;k++){const h=RO.h+k*Math.PI/8*(k%2?1:-1)/2;let free=0;for(let d=4;d<=60;d+=4){if(roamHit(RO.x+Math.sin(h)*d,RO.z+Math.cos(h)*d,2.5,RO.y)||roamTerr(RO.x+Math.sin(h)*d,RO.z+Math.cos(h)*d,RO.y).low)break;free=d}if(free>bs){bs=free;best=h}if(free>=60)break}RO.h=RO.vh=best}
function edgeStep(dt){const e=[[RO.x-WX0,1,0],[WX1-RO.x,-1,0],[RO.z-WZS,0,1],[WZN-RO.z,0,-1]].sort((a,b)=>a[0]-b[0])[0],d=e[0];RO.edgeT=Math.max(0,(RO.edgeT||0)-dt);if(d>=150)return;const out=Math.sin(RO.vh)*e[1]+Math.cos(RO.vh)*e[2]<0;if(out&&RO.v>0)RO.v-=RO.v*Math.min(1,dt*2.6*(1-d/150));if(RO.edgeT<=0){RO.edgeT=3;RO.edgeN=(RO.edgeN||0)+1;const el=$('#roamDist');if(el){el.textContent='↩ TURN BACK · '+CCF.edgeT+' · '+CCF.edge[e[1]>0?0:e[1]<0?1:e[2]>0?2:3];el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}}}
function roamWarp(x,z,h,now){if(!RO.on||RO.ch||RO.sp||RO.wk)return false;RO.x=clamp(x,WX0+20,WX1-20);RO.z=clamp(z,WZS+20,WZN-20);RO.y=groundAt(RO.x,RO.z,99);if(h!=null)RO.h=h;RO.vh=RO.h;RO.v=0;RO.vy=0;RO.yr=0;RO.dDir=0;RO.lastRamp=null;if(pl)pl.air=null;camSnap=true;camera.position.set(RO.x-Math.sin(RO.h)*14,RO.y+5,RO.z-Math.cos(RO.h)*14);HUB.cpos=null;hubCullStep();for(let i=0;i<30;i++)hubRecycle();for(const p of HUB.peds||[])pedPlace(p,30,380);RO.dist=null;roamSavePos();return true}
function roamSavePos(){const st=store.get('mho_story',{seen:0,end:0});st.last=Date.now();store.set('mho_story',st);const o=roamSave();o.pos={x:+RO.x.toFixed(1),z:+RO.z.toFixed(1),y:+RO.y.toFixed(1),h:+RO.h.toFixed(3)};o.lay=LAYOUT_VER;roamStore(o)}
// W13: city top speed was 62% of the car's top (≈91 km/h, 0-100 never reached): "slow like a bike". City .82 (≈120 km/h), open road 1.0,
// and the throttle pull falls off with (v/top)² instead of v/top, so 0-100 km/h takes ≈4.5 s in the city instead of never.
const W13S={city:.82,open:1,cp:2,scrub:20,a0:.18,a1:.15,lift:.6};
// cornering: with the stronger pull a car held at full lock gained speed through a junction and ran wide (w13 feel gate). W14: tyres scrub
// speed only in a real corner: lock held one way past ~13° of rotation (slalom flicks stay below that) AND the yaw asked for exceeds the
// tyres' grip (C26 c26x>1). Scrub fades out as the car slows to the speed that full lock can hold, so it settles near 50 km/h.
// Not while drifting, boosting or in the air.
function W13_corner(c,dt){const st=Math.abs(c.steer||0),sg=Math.sign(c.steer||0);if(st>=.3&&sg===RO.w13s){RO.w13h=(RO.w13h||0)+dt;RO.w13a=(RO.w13a||0)+Math.abs(RO.yr||0)*dt}else{RO.w13h=0;RO.w13a=0}RO.w13s=st>=.3?sg:0;
  if(st<.3||RO.dDir||RO.v<=0||(pl&&pl.air)||RO.boosting)return;const k=clamp(((RO.w13a||0)-W13S.a0)/W13S.a1,0,1)*clamp(((RO.c26x||0)-1)/.35,0,1);RO.w13k=k;RO.v-=W13S.scrub*k*clamp((RO.v-12)/8,0,1)*dt}
const W13_lift=c=>1-W13S.lift*clamp((Math.abs(c.steer||0)-.3)/.7,0,1)*clamp((RO.v-10)/8,0,1)*clamp(((RO.w13a||0)-.1)/.12,0,1);
// BG23: boost/turbo push fades out at the boosted top speed (was added on top of it: holding BOOST in the city ran to 213 km/h)
const BG23_cap=(v,tt)=>v<=0?1:Math.max(0,1-(v/tt)**3);
function roamStep(dt){const s=pl;if(!s)return;if(RO.wk){AU.engine(s,0,false);AU.scrape(false);roamWreckStep(dt);hubTrafficStep(dt);studFXStep(dt);roamHud();return}RO.inv=Math.max(0,(RO.inv||0)-dt);RO.lastHit=(RO.lastHit||0)+dt;if(RO.lastHit>4)roamHeal(3*dt);
  if((RO.hp??100)<35&&R()<.25)puff(s.mesh.position.clone().add(V3(0,2.4,0)),1,_tipC.setRGB(.2,.2,.22),1,4,.9,.5,1,3);if((RO.hp??100)<15&&R()<.2)burst(SPARK,s.mesh.position.clone().add(V3(0,2,0)),4,8,.3,new THREE.Color(2,1.2,.4));
  if(!s.mesh.visible&&!(typeof M1!=='undefined'&&M1.ghost>0))s.mesh.visible=true;const c=ctlPlayer(dt);CTL=c;const busy=RO.card||RO.mapOpen||RO.story;RO.hitCd=Math.max(0,(RO.hitCd||0)-dt);
  const T0=roamTerr(RO.x,RO.z,RO.y+.3),ground=T0.g,air=RO.y>ground+.5;const terr=FL_terr(T0,ground,dt);
  const veh=FL_veh();const V85OFF=v85Off(dt);
  const fit=Math.max(.87,{ship:{road:1,dirt:.72,water:.78},boat:{road:.42,dirt:.38,water:1},offroad:{road:.93,dirt:1,water:.35}}[veh][terr]);
  if(((RO.abF=(RO.abF||0)+1)&3)===1){const a=abAt(RO.x,RO.z);RO.onAB=!!a&&!!a.road.ab&&Math.abs(a.lat)<a.road.w/2+1&&RO.y<groundY(RO.x,RO.z)+14;RO.abRoad=RO.onAB?a.road.name:null;const q=RO.onAB?null:cityAt(RO.x,RO.z);RO.inCity=!RO.onAB&&(RO.x>HX0&&RO.x<HX1&&RO.z>HZS&&RO.z<HZN||!!q&&q.d<q.road.w/2+30);const rq=RO.onAB?a:q&&q.d<q.road.w/2+2?q:null;RO.rdT=rq?[rq.p.tx,rq.p.tz]:null;if(!RO.rdT&&!RO.onAB){const f=fillAt(RO.x,RO.z);if(f&&f.d<f.r.w/2+2)RO.rdT=[f.r.ux,f.r.uz]}/* drive24b: filler-grid streets have a direction too (the assist was off on them) */}
  const lvl=carStat();const top=s.stats.top*.8*lvl.top,boost=c.boost&&s.bm>1&&!busy;RO.boosting=boost||RO.turbo>0;RO.turbo=Math.max(0,(RO.turbo||0)-dt);
  if(boost){RO.boostT=(RO.boostT||0)+dt;if(!RO.wasB){AU.sfx('nitro');fovKick=Math.max(fovKick,9*TUNE.fxFov)}s.bm=Math.max(0,s.bm-TUNE.bDrain*dt);RO.bIdle=0}else{RO.bIdle=(RO.bIdle||0)+dt;if(RO.bIdle>.5)s.bm=Math.min(100,s.bm+FL_RECH*dt)}RO.wasB=boost;s.nitro=boost||RO.turbo>0;RO.top=top;
  // hop: Space / HOP button
  if(pressed.fire){pressed.fire=false;if(!busy&&!air&&RO.vy<=0){RO.tutHop=true;RO.vy=TUNE.hop;RO.y+=.05;AU.sfx('launch');fovKick=Math.max(fovKick,4)}}
  if(air)RO.airT=(RO.airT||0)+dt;
  if(busy)RO.v*=Math.max(0,1-dt*4);else if(!air){RO.bRamp=clamp((RO.bRamp||0)+(boost?dt*2.5:-dt*4),0,1);const tt=TUNE.spOn?QS_tt(lvl,fit*V85OFF)/* v88z: real class top speeds (98qs_speed.js) */:top*(1+(RO.inCity?.25:.3)*TUNE.bTop*RO.bRamp)*(RO.turbo>0&&!RO.bash?1.25:1)*fit*V85OFF*(RO.onAB?TUNE.abTop:RO.inCity?W13S.city:W13S.open);C26_ramp(RO,c,C26.on?dt:1);if(c.thr||boost||RO.turbo>0)RO.v+=(s.stats.acc*TUNE.acc*lvl.acc*Math.max(0,1-(RO.v>0?(RO.v/tt)**W13S.cp:RO.v/tt))*W13_lift(c)*(boost||RO.turbo>0||!C26.on?1:Math.max(.05,RO.thA))+(TUNE.bPush*RO.bRamp+(RO.turbo>0?16:0))*BG23_cap(RO.v,tt))*dt;else if(C26.on){const cd=(Math.abs(RO.v)*.08+.9)*dt;RO.v=Math.abs(RO.v)<=cd?0:RO.v-Math.sign(RO.v)*cd}else RO.v-=RO.v*.4*dt;if(c.park){RO.v-=Math.sign(RO.v)*Math.min(Math.abs(RO.v),60*dt);RO.bz=0}else if(c.brk){if(RO.v>0){RO.v=Math.max(0,RO.v-(C26.on?C26.brkCity*(.1+.9*RO.bkA):75)*dt);RO.bz=0}else{RO.bz=(RO.bz||0)+dt;if(RO.bz>.7||RO.v<0)RO.v-=22*dt}}else RO.bz=0;RO.v=Math.max(-TUNE.rev,RO.v);if(RO.v>tt)RO.v-=(RO.v-tt)*1.5*dt;W13_corner(c,dt)}
  // boost pads
  for(const pd of RO.pads||[]){if(!air&&Math.hypot(pd.x-RO.x,pd.z-RO.z)<7&&(RO.padT||0)<=0){RO.turbo=Math.max(RO.turbo,1.8);RO.v=Math.max(RO.v,top*1.05);RO.padT=.8;award(s,'BOOST PAD',8,100,'#ffd12c');comboAdd(1);AU.sfx('boost');fovKick=Math.max(fovKick,10)}}RO.padT=Math.max(0,(RO.padT||0)-dt);
  // steering: target yaw rate eases in; sharper when slow, calmer when fast; velocity heading follows with surface grip (slight slide on dirt/water)
  const sp=Math.abs(RO.v),vr=clamp(sp/Math.max(30,top),0,1),maxR=(TUNE.stMax-TUNE.stSpd*vr)*({low:.85,high:1.15}[SET.steer]||1)*lvl.han*(air?.45:1)*(air?clamp(sp/9,0,1):Math.max(.6,clamp(sp/9,0,1)));
  const hbOk=c.hb&&!air&&sp>(window.B2K_DMIN||22)&&!busy; // B2K hook: drift speed from 98k_boost2k
  if(hbOk&&!RO.dDir&&Math.abs(c.steer)>.2){RO.dDir=Math.sign(c.steer);RO.dT=0;AU.sfx('roll')}
  if(RO.dDir&&!hbOk){const tr=RO.dT>2?3:RO.dT>1.1?2:RO.dT>.5?1:0;if(tr){RO.tutTurbo=true;RO.turbo=Math.max(RO.turbo,[0,.8,1.3,2][tr]);s.bm=Math.min(100,s.bm+6*tr);award(s,['','MINI-TURBO','SUPER TURBO','ULTRA TURBO'][tr],0,250*tr*tr,['','#4ceaff','#ff9a3c','#c46bff'][tr]);AU.sfx('boost');fovKick=Math.max(fovKick,5+3*tr);comboAdd(tr)}RO.dDir=0;RO.dT=0}
  let ytg=-c.steer*maxR*Math.sign(RO.v||1);
  if(RO.dDir){const into=clamp(c.steer*RO.dDir,-1,1);ytg=-RO.dDir*maxR*(TUNE.drSlip+.6*into);RO.dT+=dt*(1+.8*Math.max(0,into))*(PK.has('drift')?1.35:1);s.bm=Math.min(100,s.bm+8*dt);RO.v-=RO.v*.06*dt;
    const tr=RO.dT>2?3:RO.dT>1.1?2:RO.dT>.5?1:0,col=[new THREE.Color(1.4,1.4,1.4),new THREE.Color(.6,1.6,2.6),new THREE.Color(2.6,1.2,.3),new THREE.Color(1.8,.6,2.6)][tr],fx0=Math.sin(RO.h),fz0=Math.cos(RO.h);
    for(const sd of[-1,1])if(R()<.8)emit(SPARK,V3(RO.x-fx0*3+fz0*sd*2.2,RO.y+.3,RO.z-fz0*3-fx0*sd*2.2),V3(rr(-2,2)-fx0*6,rr(1,4),rr(-2,2)-fz0*6),.28,col)}
  // steering assist (touch): with no steering input at speed, gently line the car up with the road it is on
  if(SET.assist!=='off'&&!air&&!busy&&!RO.dDir&&RO.rdT&&RO.v>6&&Math.abs(c.steer)<.05){const a0=Math.atan2(RO.rdT[0],RO.rdT[1]);let e=angDiff(a0,RO.h);if(Math.abs(e)>Math.PI/2)e=angDiff(a0+Math.PI,RO.h);if(Math.abs(e)<TUNE.asMax)ytg+=e*TUNE.assist*clamp((sp-6)/14,0,1)*(1-Math.abs(e)/(TUNE.asMax*1.375))/* drive24b: TUNE.asMax = widest heading error the assist acts on */}
  {const y0=RO.yr||0;RO.yr=CR_yaw(c,dt,ytg,maxR,air);if(C26.on&&!air&&!RO.dDir&&!busy&&sp>3){let t=C26_yawCap(RO,RO.yr,sp,C26_cityMu(terr,veh));const b=angDiff(RO.h,RO.vh??RO.h)*Math.sign(RO.v||1);t-=C26.align*(b-clamp(b,-.1,.1))*Math.min(1,sp/20);RO.yr=y0+(t-y0)*Math.min(1,dt*(TUNE.stOn&&Math.abs(t)<Math.abs(y0)?TUNE.yrOut:TUNE.yrIn>0?TUNE.yrIn:11-4*Math.min(1,sp/40)))/* drive24b: TUNE.yrIn = yaw build-up rate (0 = old 11→7 /s) *//* D24: a let-go stops the turn fast (TUNE.yrOut /s) */}}RO.h+=RO.yr*dt;
  // pinned (throttle on, barely moving): turn to the nearest open direction and roll off. Braking to a stop is not pinned (W10: it kicked the car ±22° and 36 km/h), only a blocked reverse is; and only < 2 m/s counts, so pulling away from a stop is never 'pinned'
  {const mv=Math.hypot(RO.x-(RO.stkX??RO.x),RO.z-(RO.stkZ??RO.z));RO.stkX=RO.x;RO.stkZ=RO.z;if((c.thr&&!c.brk||boost||c.brk&&(RO.bz||0)>1.2)&&!busy&&!air&&mv<dt*2)RO.stkT=(RO.stkT||0)+dt;else RO.stkT=Math.max(0,(RO.stkT||0)-dt*2);
   if(RO.stkT>.6){let best=null,bd=9;for(let k=1;k<16;k++){const ang=RO.h+(k%2?1:-1)*Math.ceil(k/2)*Math.PI/8,px=RO.x+Math.sin(ang)*7,pz=RO.z+Math.cos(ang)*7,N=roamTerr(px,pz,RO.y+.3);if(N.low||N.g>RO.y+1.4||roamHit(px,pz,2.4,RO.y)||(HUB.cars||[]).some(q=>!q.dead&&q.x!=null&&Math.hypot(q.x-px,q.z-pz)<5.5))continue;const d=Math.abs(angDiff(ang,RO.h));if(d<bd){bd=d;best=ang}}
     if(best!=null){RO.crTurn=best;RO.yr=0;RO.v=Math.max(RO.v,10);RO.stkT=0}else if(RO.stkT>2){RO.v=c.brk&&!c.thr?8:-8;RO.stkT=0;say('','UNSTUCK',.6)}}}
  const grip=(air?.6:terr==='water'?2.6:terr==='dirt'?(veh==='offroad'?20:14):TUNE.gripRoad)*(RO.dDir?(terr==='road'?TUNE.drGrip:.22):1);RO.vh=(RO.vh??RO.h)+(C26.on?C26_vhStep(RO,angDiff(RO.h,RO.vh??RO.h),grip,dt,sp,C26_cityMu(terr,veh),air||!!RO.dDir||busy):angDiff(RO.h,RO.vh??RO.h)*Math.min(1,dt*grip));if(C26.on&&!RO.dDir){const b=angDiff(RO.h,RO.vh),sm=TUNE.slipMax??.6/* drive26: max slip outside drift (was .6) */;if(Math.abs(b)>sm)RO.vh=RO.h-Math.sign(b)*sm;if(!air)RO.v-=RO.v*Math.sin(b)**2*C26.scrub*dt}s.latV=Math.sin(angDiff(RO.h,RO.vh))*sp;
  if(Math.abs(angDiff(RO.h,RO.vh))>.25&&sp>25&&!air&&(terr!=='road'))RO.v-=RO.v*.08*dt;
  const fx=Math.sin(RO.vh),fz=Math.cos(RO.vh);let nx=RO.x+fx*RO.v*dt,nz=RO.z+fz*RO.v*dt;
  const N=roamTerr(nx,nz,RO.y+.3);
  if(N.low){let pop=false;for(const b of ALL_DECKS){const h=deckAt(b,nx,nz);if(h!=null&&h-RO.y<4.5){RO.y=h;RO.vy=Math.max(RO.vy,3);pop=true}}
    if(!pop){const ax=roamTerr(nx,RO.z,RO.y+.3).low;roamBounce(ax?'x':'z',sp);nx=RO.x;nz=RO.z}}
  else if(N.g>RO.y+1.4&&!air){if(ground<-1.5&&N.g<=.5&&RO.v>10){RO.vy=16;RO.y+=.1;award(s,'BANK HOP',6,150,'#4ceaff');AU.sfx('launch');nx=RO.x;nz=RO.z}
    else if(N.g-RO.y<8&&RO.ramps.some(r=>Math.hypot(nx-r.x,nz-r.z)<r.len)){RO.y=N.g;RO.vy=Math.max(RO.vy,4)}
    else{const ax=roamTerr(nx,RO.z,RO.y+.3).g>RO.y+1.4;roamBounce(ax?'x':'z',sp);nx=RO.x;nz=RO.z}}
  else if(air&&N.g>RO.y+.2){nx=RO.x;nz=RO.z}
  // deck walls keep you on the road
  if(T0.deck&&!air){const b=T0.deck,lim=b.w/2-1.6,dl=deckLocal(b,nx,nz);if(Math.abs(dl[1])>lim&&Math.abs(dl[0])<b.half-2){const q=deckPt(b,dl[0],Math.sign(dl[1])*lim);nx=q[0];nz=q[1];{const ua=Math.atan2(b.ux,b.uz);let e=angDiff(ua,RO.h);if(Math.abs(e)>Math.PI/2)e=angDiff(ua+Math.PI,RO.h);RO.h+=e*Math.min(1,dt*6)}if(sp>20){RO.v*=1-.5*dt;if(R()<.4)burst(SPARK,V3(nx,RO.y+1.2,nz),6,12,.3,new THREE.Color(2,1.4,.6))}}}
  const hb=SC_hit(nx,nz,RO.y);if(hb){const pp=SC_push(hb,nx,nz),ddx=pp[0]-nx,ddz=pp[1]-nz,dl=Math.hypot(ddx,ddz);nx=pp[0];nz=pp[1];if(sp>20)burst(SPARK,V3(nx,RO.y+1.5,nz),RO.hitCd>0?4:14,18,.4,new THREE.Color(2,1.4,.6));roamBounce(pp[2],sp,dl>1e-4?ddx/dl:null,dl>1e-4?ddz/dl:null)}
  RO.x=clamp(nx,WX0+10,WX1-10);RO.z=clamp(nz,WZS+10,WZN-10);edgeStep(dt);
  const g2=groundAt(RO.x,RO.z,RO.y+.3);const onRamp=RO.ramps.find(r=>{const dx=RO.x-r.x,dz=RO.z-r.z,a=dx*Math.sin(r.h)+dz*Math.cos(r.h),b=dx*Math.cos(r.h)-dz*Math.sin(r.h);return Math.abs(b)<r.w/2&&a>-r.len/2&&a<r.len/2});
  if(onRamp&&!air){RO.rampV=RO.v*onRamp.hgt/onRamp.len;RO.lastRamp=onRamp}else if(RO.lastRamp&&!onRamp&&!air&&RO.y>g2+.3){RO.vy=Math.max(RO.vy,RO.rampV*1.15+3);CR_rampLaunch(RO.lastRamp);RO.takeoff={x:RO.x,z:RO.z,r:RO.lastRamp};RO.lastRamp=null;AU.sfx('launch');fovKick=Math.max(fovKick,8)}
  if(!onRamp&&!(RO.y>g2+.05||RO.vy>0))RO.lastRamp=null;if(CID==='ath'&&RO.vy===0&&!RO.lastRamp&&!onRamp&&RO.y>g2&&RO.y-g2<=Math.abs(RO.v)*dt*.4+.1)RO.y=g2;
  if(RO.y>g2+.05||RO.vy>0){RO.vy-=(RO.crRJ?CR_RG:TUNE.grav)*dt;if(RO.crRJ&&RO.vy<-22)RO.vy=-22;RO.y+=RO.vy*dt;if(RO.y<=g2){if(RO.vy<-24)roamDamage(Math.min(20,(-RO.vy-24)*1.5+6));RO.landK=Math.min(1,Math.max(RO.landK||0,-RO.vy/22));if(RO.vy<-8&&g2>-1.5)puff(V3(RO.x,g2+.4,RO.z),6,_tipC.setRGB(.8,.78,.74),2,7,.8,.4,4,2);if(RO.vy<-10){AU.sfx(g2<-1.5?'splash':'land');if(g2<-1.5)burst(WATER,V3(RO.x,g2+1,RO.z),50,18,.8,new THREE.Color(.4,.7,1.2));shake=.35}RO.y=g2;RO.vy=0;roamLanded()}}else{RO.crRJ=0;if(g2-RO.y<1.6)RO.y+=(g2-RO.y)*Math.min(1,dt*14);else RO.y=g2}
  if(RO.y>g2+1.2&&!s.air)s.air={vy:RO.vy};else if(RO.y<=g2+.3)s.air=null;
  if(!s.air){s.terrain=terr;s.boatMode=veh==='boat';s.dirtMode=veh==='offroad'}RO.fit=fit;RO.terr=terr;RO.veh=veh;
  s.v=sp;s.dist=0;
  // studs: magnet pulls them in
  const mag=roamMagnet();for(const st of RO.studs){if(!st.alive){if((st.t-=dt)<=0){st.alive=true;st.m.visible=true;st.m.position.set(st.x,st.y,st.z);st.pull=false}continue}st.m.rotation.z+=dt*3;const dx=RO.x-st.m.position.x,dz=RO.z-st.m.position.z,dy=RO.y+.6-st.m.position.y,d=Math.hypot(dx,dz);
    if(!st.pull&&d<mag&&Math.abs(dy)<mag)st.pull=true;if(st.pull){const k=Math.min(1,dt*(9+sp*.12));st.m.position.x+=dx*k;st.m.position.z+=dz*k;st.m.position.y+=dy*k}
    if(d<2.6&&Math.abs(dy)<3){st.alive=false;st.m.visible=false;st.t=240;studGain(st.v)}}
  RO.cool=Math.max(0,RO.cool-dt);RO.saveT=(RO.saveT||0)+dt;if(RO.saveT>3&&!air){RO.saveT=0;roamSavePos()}
  sprintStep(dt);tutStep(dt);qvTick(dt);PIN_tick(dt);if(RO.ch)chStep(dt);else{let near=null,nd=1e9;for(const m of RO.marks){const d=Math.hypot(m.x-RO.x,m.z-RO.z);m.ring.rotation.z+=dt;if(m.fig){const u=m.fig.userData;u.arm.rotation.z=-.6-Math.sin(T*5)*.6;u.ex.position.y=5.4+Math.sin(T*3)*.25;u.ex.visible=!markDone(m)}const lk=markLocked(m);{const nf=clamp((d-12)/45,.12,1);m.sp.material.opacity=(lk?.25:markDone(m)?.5:1)*nf;if(m.beam)m.beam.material.opacity=.28*nf;if(m.pane)m.pane.material.opacity=.2*nf}const busyEv=RO.ch||RO.sp||document.body.classList.contains('crQ');m.g.visible=busyEv?(RO.ch&&RO.ch.m===m):!lk||m.kind==='flight';if(busyEv)continue;if(!lk&&d<350)discover(m);if(!markDone(m)&&!lk&&markKnown(m)&&d<nd){nd=d;near=m}if((!lk||m.kind==='flight')&&d<11&&Math.abs(RO.y-m.g.position.y)<6&&!RO.card&&RO.cool<=0){RO.pmNew=m;if(Math.abs(RO.v)<7)roamOpen(m)}}
    if(RO.wp){const d=Math.hypot(RO.wp.x-RO.x,RO.wp.z-RO.z);if(d<12)RO.wp=null;else{near=RO.wp;nd=d}}RO.near=near;RO.nd=nd}
  if(RO.card&&!RO.cardPin&&Math.hypot(RO.card.x-RO.x,RO.card.z-RO.z)>12){RO.card=null;$('#roamCard').hidden=true}roamPrompt(dt);
  smashCheck(dt);studFXStep(dt);hubTrafficStep(dt);comboStep(dt);popStep(dt,busy);gbStep(dt);RO.prT=(RO.prT||0)+dt;if(RO.prT>1){propRespawn(RO.prT);RO.prT=0}hubFrame(dt);
  roamPose(s,dt);roamHud();spHud();AU.engine(s,c.thr,true)}
// glancing hits keep most of the speed and turn you along the wall; head-on hits bounce you back
function qCrate(){const ch=RO.ch;if(!ch||(ch.cc||0)>ch.t)return;if(ch.v2&&ch.v2.L.fragile){ch.cc=ch.t+.7;ch.t+=5;feed('🤕 OUCH! +5 s',0,'#ff5a2d');return}if(ch.kind!=='deliver'||ch.n<=0||!ch.crates)return;ch.cc=ch.t+.7;ch.n--;const c=ch.crates.children[ch.crates.children.length-1];if(c){debris(c.getWorldPosition(V3()),V3(0,6,0),10,[new THREE.Color('#9a6a3a'),new THREE.Color('#ffd84a')],.8,RO.y);ch.crates.remove(c)}AU.sfx('brick');feed('CRATE SMASHED · '+ch.n+' left',0,'#ff5a2d')}
function roamDamage(d){if(RO.wk||(RO.inv||0)>0||d<1||state!=='roam')return;RO.hp=Math.max(0,(RO.hp??100)-d);RO.lastHit=0;if(d>6)flashHud();if(RO.hp<=0)roamWreck()}
function roamHeal(h){if(RO.wk)return;RO.hp=Math.min(100,(RO.hp??100)+h)}
let RBRK=null;function roamWreck(){const s=pl;if(!s)return;const ud=s.mesh.userData,t=s.team,cols=[t.a,t.b,t.c,'#ffd12c','#2a2f38'].map(c=>new THREE.Color(c));
  if(!RBRK){RBRK=new THREE.InstancedMesh(brickGeo(),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.3,metalness:.05}),70);RBRK.frustumCulled=false;HUB.grp.add(RBRK)}if(!RBRK.parent)HUB.grp.add(RBRK);
  const fw=V3(Math.sin(RO.h),0,Math.cos(RO.h)),rs=V3(Math.cos(RO.h),0,-Math.sin(RO.h)),c0=V3(RO.x,RO.y+1.6,RO.z),B=[];
  for(let i=0;i<70;i++){const home=V3(rr(-3.6,3.6),rr(-.4,1),rr(-4.2,4.2)),p=c0.clone().addScaledVector(rs,home.x).add(V3(0,home.y,0)).addScaledVector(fw,home.z);B.push({home,p,v:V3(rr(-14,14),rr(8,22),rr(-14,14)).addScaledVector(fw,RO.v*.45),q:new THREE.Quaternion().setFromEuler(new THREE.Euler(rr(0,6),rr(0,6),rr(0,6))),w:V3(rr(-9,9),rr(-9,9),rr(-9,9)),s:rr(.55,.85)});RBRK.setColorAt(i,cols[i%cols.length])}
  RBRK.instanceColor.needsUpdate=true;RBRK.visible=true;s.mesh.visible=false;RO.wk={t:0,B,c0};RO.v=0;RO.dDir=0;CB.n=0;
  for(let k=0;k<8;k++)studBurst(c0,fw,10);burst(SPARK,c0,60,40,.8,new THREE.Color(2,1.6,.9));puff(c0,10,new THREE.Color(.5,.5,.55),3,12,1.6,.6,2,4);AU.sfx('crash');AU.sfx('brick');shake=1;say('WRECKED!','REBUILDING…',1.6)}
function roamWreckStep(dt){const W=RO.wk,s=pl;W.t+=dt;const fw=V3(Math.sin(RO.h),0,Math.cos(RO.h)),rs=V3(Math.cos(RO.h),0,-Math.sin(RO.h)),c0=V3(RO.x,RO.y+1.6,RO.z),qh=new THREE.Quaternion().setFromAxisAngle(V3(0,1,0),RO.h);
  W.B.forEach((b,i)=>{if(W.t<1.3){b.v.y-=30*dt;b.p.addScaledVector(b.v,dt);const fl=groundAt(b.p.x,b.p.z,b.p.y+1)+.4;if(b.p.y<fl){b.p.y=fl;b.v.y=Math.abs(b.v.y)*.35;b.v.x*=.7;b.v.z*=.7;b.w.multiplyScalar(.7)}_q2.setFromEuler(_e2.set(b.w.x*dt,b.w.y*dt,b.w.z*dt));b.q.multiply(_q2)}
    else{const k=Math.min(1,(W.t-1.3)/(.55+i%7*.03)),e=k*k*(3-2*k),hp=c0.clone().addScaledVector(rs,b.home.x).add(V3(0,b.home.y,0)).addScaledVector(fw,b.home.z);b.p.lerp(hp,e*.35+(k>=1?1:0));b.q.slerp(qh,e*.3)}
    _m.compose(b.p,b.q,_s2.setScalar(b.s));RBRK.setMatrixAt(i,_m)});RBRK.instanceMatrix.needsUpdate=true;
  if(W.t>1.3&&!W.snap){W.snap=1;AU.sfx('pick')}if(W.t>=2){RBRK.visible=false;s.mesh.visible=true;RO.wk=null;RO.hp=100;RO.inv=2;camSnap=true;RO.camH=RO.camB=RO.camY=RO.camL=null;burst(SPARK,c0,40,18,.6,new THREE.Color(2.4,2.2,1));AU.sfx('boost');say('','REBUILT!',.9)}}
// slide along the wall: pick the wall tangent the player steers toward (or the one closest to the current heading) and keep moving
function roamGlance(ax,sp){if(RO.v<0){RO.v=3;return}const st=(CTL&&CTL.steer)||0,a=ax==='x'?[0,Math.PI]:[Math.PI/2,-Math.PI/2];
  let t;if(Math.abs(st)>.2)t=a.find(x=>Math.sign(angDiff(x,RO.h))===-Math.sign(st))??a[0];else{const d0=Math.abs(angDiff(a[0],RO.h)),d1=Math.abs(angDiff(a[1],RO.h));t=Math.abs(d0-d1)<.05?a[R()<.5?0:1]:d0<d1?a[0]:a[1]}
  RO.h+=angDiff(t,RO.h)*.8;RO.vh=t;RO.yr=0;RO.v=Math.max(12,sp*.45);RO.stkT=0}
function roamBounce(ax,sp,nX,nZ){const vx=Math.sin(RO.vh)*RO.v,vz=Math.cos(RO.vh)*RO.v;if(nX==null){if(ax==='x'){nX=-(Math.sign(vx)||1);nZ=0}else{nX=0;nZ=-(Math.sign(vz)||1)}}
  const vn=vx*nX+vz*nZ;if(vn>-.05)return;const a=Math.min(1,-vn/Math.max(sp,.1)),hard=-vn>7&&RO.hitCd<=0,fd=Math.sin(RO.h)*nX+Math.cos(RO.h)*nZ;if(hard){RO.hitCd=.3;if(sp>18)qCrate()}
  if(a>.9&&Math.abs(fd)>.35){const bv=Math.min(12,2+(-vn)*.2);RO.vh=RO.h;RO.v=fd<0?-bv:bv;RO.yr*=.3;if(sp<14)RO.stkT=(RO.stkT||0)+.2;
    if(hard){roamDamage(Math.max(0,(-vn-10)*.5));if(-vn>12){AU.sfx('crash');shake=Math.max(shake,Math.min(.7,-vn/70))}else AU.sfx('bump')}return}
  const tx=vx-vn*nX,tz=vz-vn*nZ;if(Math.hypot(tx,tz)<.01){RO.v*=.5;return}const ns=sp*(1-.6*a*a),tf=Math.atan2(tx,tz);
  if(Math.abs(angDiff(tf,RO.h))<=Math.PI/2){RO.vh=tf;RO.v=ns;RO.h+=angDiff(tf,RO.h)*.6}else{RO.vh=tf+Math.PI;RO.v=-ns;RO.h+=angDiff(tf+Math.PI,RO.h)*.6}RO.yr*=.5;RO.stkT=0;
  if(hard){roamDamage(Math.max(0,(-vn-15)*.3));if(-vn>10){AU.sfx('bump');shake=Math.max(shake,Math.min(.3,-vn/140))}}}
const angDiff=(a,b)=>{let d=a-b;while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;return d};
let studCombo=0,studComboT=0;// street studs: earnings from wandering decay with a 4-minute half-life; past 1200 recent studs the payout drops to 50 %, past 3000 to 20 %
function streetMul(){const now=performance.now()/1000,dt=now-(RO.stT||now);RO.stT=now;RO.stE=(RO.stE||0)*Math.pow(.5,dt/240);return RO.stE<1200?1:RO.stE<3000?.5:.2}
function studGain(v,bonus){const S2=season();studCombo=performance.now()-studComboT<900?studCombo+1:1;studComboT=performance.now();let g=v;if(state==='roam'&&!bonus){g=Math.max(1,Math.round(v*streetMul()));RO.stE+=g}S2.cr+=g;saveSeason(S2);AU.sfx('pick');if(pl&&state==='roam'){pl.bm=Math.min(100,pl.bm+.6);roamHeal(.2)}if(studCombo%5===1||v>10)feed(v>10?'BIG STUD':'STUDS ×'+studCombo,v*studCombo>v?v:v,'#ffd12c')}
const PD_HILDE={n:'HILDE',full:'Oma Hilde',flag:'🔧',team:'aeppler',style:'clean',r:0};PD.HILDE=PD_HILDE;
PD.ELENI={n:'ELENI',full:'Eleni Mavrou',flag:'🇬🇷',team:'helix',style:'clean',r:0};PD.DRAKOS={n:'DRAKOS',full:'Thanos Drakos',flag:'🏴',team:'shadow',style:'aggressor',r:1};
const ATH_RIVAL_EV=[];
const ATH_CHAPTERS=[{n:1,title:'Welcome to Athens',need:0,who:'ELENI',txt:"Good morning, champion, and welcome to Athens! I'm Eleni Mavrou, Hilde's old co-driver, and my garage in Psyrri is yours now. Drakos' riders are still lying low, so take the city in first: the marble of <b>Ermou</b>, <b>Syntagma</b> and the long <b>Vasilissis Sofias</b> out to Ambelokipi. I'll call you when they show up.<br><br><i>Your flight home to Frankfurt leaves right next to my garage ✈.</i>"},
 {n:2,title:'The Alleys of Plaka',need:2,who:'ELENI',txt:"Two flags! The couriers of Plaka noticed you. The Lycabettus road is open."},
 {n:3,title:'Drakos',need:4,who:'DRAKOS',txt:"Four flags, tourist? My crew will send you home on the next plane.<br><br><i>Eleni: The Lycabettus and Kifisias belong to them. Show them.</i>"},
 {n:4,title:'Akropolis Cup',need:5,who:'ELENI',txt:"The Panathenaic Stadium opens its gates. Beat Drakos in the Akropolis Cup Final."}];
const ATH_EPILOGUE={who:'ELENI',title:'Akropolis Cup Champion',txt:"Bravo! The Akropolis Cup stays in Athens and Drakos goes back to the shadows."};
const ATH_INVITE={who:'ELENI',title:'A call from Athens',txt:"Good morning, champion! Eleni Mavrou here, Hilde's old co-driver. I run a little garage in Psyrri, Athens. Kaiser's money men, the Schattenwerk, moved here and bought the streets. Their new king, Thanos Drakos, races for the <b>Akropolis Cup</b> and nobody beats him. Come and help us!<br><br><i>Hilde: Your flight leaves from <b>Fraport Hangar 7</b> ✈. Studs, XP, cars and parts fly with you, and Frankfurt waits for you.</i>"};
const CHS=()=>CID==='ath'?ATH_CHAPTERS:CHAPTERS;
function athInvited(){const m=flightMark();if(m){pickAdd(m);RO.wp=m}feed('✈ NEW · FLIGHTS TO ATHENS AT FRAPORT HANGAR 7',0,'#7fd4ff')}
const athInvitePending=()=>CID==='fra'&&fraFlags()>=ATH_NEED&&!store.get('mho_story',{}).ath;
const CHAPTERS=[{n:1,title:'New in Mainhattan',need:0,who:'HILDE',txt:"Welcome to Mainhattan! I'm Hilde, and this garage is yours now. Frankfurt's racers rule the streets, the river and the Sky Cup, and Vex Kaiser rules them all by cheating. Start small: beat <b>Luca Rossi</b> and <b>Jana Weber</b> one-on-one and take their flags. The blue holo-gates pay studs and XP, and every level makes your craft faster."},
 {n:2,title:'The Harbour Gang',need:2,who:'HILDE',txt:"Two flags! The harbour crew noticed you. <b>Inès Moreau</b> and <b>Tunde Okafor</b> want a race, and the <b>Grand Prix Stadium</b> has opened its gates. New holo-gates appeared on the river and the ramps. Spend your studs in the garage."},
 {n:3,title:'Kaiser’s Shadow',need:4,who:'KAISER',txt:"Four flags? Cute. My crew will shut you down: <b>Ferreira</b> and <b>Çelik</b> are waiting. You will never reach the Sky Cup.<br><br><i>Hilde: Ignore him. The Battle Arena and the Derby Bowl are open now. Toughen up.</i>"},
 {n:4,title:'The Finale',need:6,who:'HILDE',txt:"Six flags. Only <b>Ole Brandt</b> and <b>Aoi Nakamura</b> are left among the elite, and the <b>Grand Arena</b> is open. Beat Vex Kaiser there and the Sky Cup comes home to Frankfurt."}];
const EPILOGUE={who:'HILDE',title:'Sky Cup Champion',txt:"You did it! Kaiser's crown is in my garage now and Frankfurt has a new champion. The city is yours: rematch the rivals, chase gold on every holo-gate and climb the driver levels."};
const nFlags=()=>{const F=flagsR();return(CID==='ath'?ATH_TRK_EV:RIVAL_EV).filter(e=>F[e.p]).length};
const chapter=()=>{const nf=nFlags();let c=1;for(const C of CHS())if(nf>=C.need)c=C.n;return c};
const RCH={ROSSI:1,WEBER:1,MOREAU:2,OKAFOR:2,FERREIRA:3,'ÇELIK':3,BRANDT:4,NAKAMURA:4},MCH={tt:1,zone:2,junction:2,arena:3,derby:3,daily:4},OCH={cp1:1,sm1:1,cp2:2,lj1:2,lj2:3,sm2:3,dz1:1,sp1:1,cl1:1,tk1:2,dz2:2,sp2:2,cl2:3,tk2:3,sp3:3},ECH=[1,2,2,3,3,4];
function markCh(m){const k=m.kind;return k==='rival'?RCH[m.ev.p]:k==='boss'?4:k==='season'?2:k==='challenge'?ECH[m.idx]:k==='mode'?MCH[m.ev.k]:k==='otg'?OCH[m.ev.id]:k==='sprint'?SCH[m.ev.id]:k==='quest'?QCH[m.ev.id]:1}
const drvClass=()=>{const l=carStat().lvl;return l>=20?'A':l>=10?'B':'C'};
function storyCheck(){const st=store.get('mho_story',{seen:0,end:0}),ch=chapter();let show=null,fx=null;if(ch>st.seen){show=CHS()[ch-1];st.seen=ch}else if(CID==='fra'&&flags().SKYCUP&&!st.end){show=EPILOGUE;st.end=1}else if(CID==='ath'&&flags().AKROCUP&&!st.end){show=ATH_EPILOGUE;st.end=1}else if(CID==='fra'&&!st.ath&&fraFlags()>=ATH_NEED){show=ATH_INVITE;st.ath=1;fx=athInvited}if(!show)return false;store.set('mho_story',st);storyShow(show);if(fx)fx();return true}
function storyShow(C){const el=$('#story');el.hidden=false;RO.story=true;el.querySelector('img').src=avatar(C.who);el.querySelector('h4').textContent=(C.n?`${CID==='fra'?'CHAPTER':CCF.ch.toUpperCase()} ${C.n} · `:'')+C.title.toUpperCase();el.querySelector('b.who').textContent=PD[C.who].full;el.querySelector('p').innerHTML=C.txt;AU.sfx('pick')}
$('#roamMini')&&$('#roamMini').addEventListener('click',()=>{if(typeof toggleMap==='function')toggleMap()});
function homeShow(v){$('#menu').classList.toggle('home',v);if(!v){const m=$('.mpanel');if(m)m.scrollTop=0}if(v)homeArt()}
function homeArt(){const c=$('#hcStory canvas');if(!c||c.dataset.done)return;c.dataset.done=1;const g=c.getContext('2d'),W=c.width,H=c.height;const sk=g.createLinearGradient(0,0,0,H);sk.addColorStop(0,'#3a8dff');sk.addColorStop(.7,'#9fd4ff');g.fillStyle=sk;g.fillRect(0,0,W,H);
  g.fillStyle='#fff';for(const[x,y,w]of[[40,60,90],[230,100,110],[150,30,60]]){g.fillRect(x,y,w,22);g.fillRect(x+w*.2,y-14,w*.5,16)}
  const tw=[[20,180,40,'#d9d2c4'],[70,120,46,'#7a8fa8'],[125,150,38,'#c9c2b4'],[175,90,52,'#5a6f88'],[240,140,44,'#d9d2c4'],[295,170,40,'#9aa8b8']];for(const[x,h,w,col]of tw){g.fillStyle=col;g.fillRect(x,H*.62-h,w,h+40);g.fillStyle='rgba(255,255,255,.55)';for(let yy=H*.62-h+8;yy<H*.62;yy+=14)for(let xx=x+5;xx<x+w-6;xx+=10)g.fillRect(xx,yy,5,7)}
  g.fillStyle='#6cbf45';g.fillRect(0,H*.66,W,H);g.fillStyle='#5b5f68';g.beginPath();g.moveTo(W*.38,H*.66);g.lineTo(W*.62,H*.66);g.lineTo(W*.95,H);g.lineTo(W*.05,H);g.fill();g.fillStyle='#ffd400';g.fillRect(W*.495,H*.68,6,H);
  // LEGO minifig driver: helmet, yellow face, grin, torso with racing stripe
  const cx=W*.5,hy=H*.42;g.fillStyle='#1d3f9e';g.beginPath();g.moveTo(cx-78,H*.86);g.lineTo(cx-60,hy+70);g.lineTo(cx+60,hy+70);g.lineTo(cx+78,H*.86);g.fill();g.fillStyle='#fff';g.fillRect(cx-8,hy+70,16,H*.86-hy-70);g.fillStyle='#e8202a';g.fillRect(cx-60,hy+92,120,10);
  g.fillStyle='#f5c518';g.beginPath();g.roundRect(cx-46,hy-34,92,98,26);g.fill();g.fillStyle='#e8a90f';g.fillRect(cx-22,hy+60,44,14);
  g.fillStyle='#e8202a';g.beginPath();g.arc(cx,hy-6,58,Math.PI*1.02,Math.PI*1.98);g.lineTo(cx+58,hy+6);g.lineTo(cx-58,hy+6);g.fill();g.fillStyle='#fff';g.fillRect(cx-6,hy-64,12,60);
  g.fillStyle='#141413';g.beginPath();g.ellipse(cx-18,hy+22,6,8,0,0,7);g.ellipse(cx+18,hy+22,6,8,0,0,7);g.fill();g.lineWidth=5;g.strokeStyle='#141413';g.beginPath();g.arc(cx,hy+30,22,.2*Math.PI,.8*Math.PI);g.stroke();
  g.fillStyle='rgba(255,255,255,.6)';g.beginPath();g.ellipse(cx-26,hy-30,12,6,-.5,0,7);g.fill()}
$('#homeBack').onclick=()=>homeShow(true);{const e=$('#hcStory small');if(e)e.textContent=`Free roam ${CCF.name} · career`}
document.querySelectorAll('#home [data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;AU.sfx&&AU.sfx('pick');if(a==='career'){homeShow(false);if(slotInfo(SLOT)){RO.wp=null;enterRoam()}else $('#careerBtn').click();return}if(a==='slots'){homeShow(false);showSlots();return}homeShow(false);const t=document.querySelector(`#tabs button[data-t="${a}"]`);if(t)t.click()});
homeArt();
function roamPauseOpen(){if(state!=='roam')return;RO.pOpen=true;RO.frozen=true;if(pl){AU.engine(pl,0,false);AU.scrape(false)}const I=slotInfo(SLOT);$('#ppSub').textContent=`Slot ${SLOT}${CID!=='fra'?' · 📍 '+CCF.name:''} · ${CID==='fra'?'Chapter':CCF.ch} ${chapter()} · ${RO.dist||districtAt(RO.x,RO.z)}`;{const fb=document.querySelector('#roamPause [data-p="fly"]');if(fb)fb.hidden=!flyOpen()}document.querySelectorAll('#roamPause .ev').forEach(b=>b.hidden=!RO.ch);$('#roamPause').hidden=false}
function roamPauseClose(){RO.pOpen=false;$('#roamPause').hidden=true;$('#profile').hidden=true;RO.frozen=!!(RO.jOpen||RO.pOpen);camSnap=true}
function pstatFlush(){if(!RO.on)return;const o=store.get('mho_pstat',{dist:0,top:0});o.dist=(o.dist||0)+(RO.pdist||0);o.top=Math.max(o.top||0,RO.ptop||0);RO.pdist=0;store.set('mho_pstat',o)}
function profileOpen(){pstatFlush();const p=prof(),L=lvlOf(p.xp),x0=150*(L-1)**2,x1=150*L**2,F=flags(),nf=RIVAL_EV.filter(e=>F[e.p]).length,stars=store.get('mho_stars',{}),sv=Object.values(stars),tot=sv.reduce((a,b)=>a+b,0),three=sv.filter(v=>v>=3).length,log=Object.values(store.get('mho_log',{})),ps=store.get('mho_pstat',{}),S=season(),team=TEAMS[teamIdx],eq=perkEq(),gbn=(roamSave().gb||[]).length,pk=store.get('mho_packs',[]).length,own=store.get('mho_gbown',[]).length,parts=Object.values(GB_PARTS).reduce((a,l)=>a+l.length,0);
  const bar=(v,m)=>`<span class="pbar"><i style="width:${Math.round(100*clamp(v/m,0,1))}%"></i></span>`;
  $('#pfBody').innerHTML=`<div class="pcol"><div class="pcard drv"><div class="lvl"><small>LEVEL</small><b>${L}</b></div><div><b>${(store.get('mho_name','')||'Rookie').toUpperCase()}</b><small>Class ${drvClass()}${CID!=='fra'?' · 📍 '+CCF.name:''} · ${CID==='fra'?'Chapter':CCF.ch} ${chapter()} · 🚩 ${CID==='fra'?'':'Frankfurt '}${nf}/8 flags</small>${bar(p.xp-x0,x1-x0)}<small>${L>=30?'MAX LEVEL':`${(x1-p.xp).toLocaleString('de-DE')} XP to level ${L+1}`}</small></div></div>
    <div class="pcard"><h5>STATS</h5><div class="pstats"><div><b>${tot}</b><small>★ stars</small></div><div><b>${three}</b><small>mastered ★★★</small></div><div><b>${log.length}</b><small>events done</small></div><div><b>${S.cr.toLocaleString('de-DE')}</b><small>studs</small></div><div><b>${((ps.dist||0)/1000).toFixed(1)} km</b><small>driven</small></div><div><b>${Math.round(ps.top||0)}</b><small>km/h top</small></div><div><b>${gbn}/${CID!=='fra'?30:RO.gbs?RO.gbs.length:30}</b><small>golden bricks${CID!=='fra'?' · '+CCF.name:''}${(()=>{try{const o=JSON.parse(localStorage.getItem(CID==='fra'?'mho_roam.ath@'+SLOT:'mho_roam@'+SLOT)||'null');return o&&(CID!=='fra'||o.gb)?`<br>${CID==='fra'?'Athens':'Frankfurt'} ${(o.gb||[]).length}/30`:''}catch(e){return ''}})()}</small></div><div><b>${pk}/12</b><small>crates</small></div></div></div></div>
    <div class="pcol"><div class="pcard"><h5>CAR · ${team.name.toUpperCase()}</h5>${UPG.map(u=>{const lv=(S.up||{})[u.k]||0;return`<div class="pup"><span>${u.name}</span>${bar(lv,5)}<small>Lv ${lv}/5${lv<5?` · next ${UPC[lv].toLocaleString('de-DE')} studs${UPS[lv]?' + '+UPS[lv]+'★':''}`:' · MAX'}</small></div>`}).join('')}<small class="pnote">Upgrade at any 🔧 garage in the world.</small></div>
    <div class="pcard"><h5>PERKS · ${eq.length}/${perkSlots()} slots</h5><div class="pperks">${eq.length?eq.map(id=>{const q=PERKS.find(x=>x.id===id);return`<span><i>${q.icon}</i>${q.name}</span>`}).join(''):'<small>No perks equipped. Win rival duels to unlock perks; equip them at a garage.</small>'}</div></div>
    <div class="pcard"><h5>COLLECTION</h5><small>Garage parts ${own}/${parts} · Liveries and horns unlock from crates and 3★ rewards.</small>${bar(own,parts)}</div></div>`;
  $('#profile').hidden=false}
document.querySelectorAll('#roamPause [data-p]').forEach(b=>b.onclick=()=>{const a=b.dataset.p;AU.sfx('pick');if(a==='resume')roamPauseClose();else if(a==='evr'){roamPauseClose();qvRestart()}else if(a==='eva'){roamPauseClose();qvAbandon()}else if(a==='map'){roamPauseClose();toggleMap(true)}else if(a==='log'){roamPauseClose();RO.jTab='todo';journalOpen()}else if(a==='profile')profileOpen();else if(a==='garage'){roamPauseClose();gbOpen()}else if(a==='settings')openSettings();else if(a==='cam'){roamCamCycle();b.textContent='🎥 '+(RCAM[SET.rcam]||RCAM.chase).n}else if(a==='quit'){roamPauseClose();exitRoam()}else if(a==='fly'){roamPauseClose();flyRoute()}});
$('#profX').onclick=()=>{$('#profile').hidden=true};
{const ok=e=>{e.preventDefault();e.stopPropagation();document.body.classList.add('portraitOk');try{localStorage.setItem('mho_portok','1')}catch(_){}};$('#rotOk').addEventListener('click',ok);$('#rotOk').addEventListener('touchend',ok,{passive:false});$('#rotOk').addEventListener('pointerup',ok)}try{if(localStorage.getItem('mho_portok'))document.body.classList.add('portraitOk')}catch(e){}
function storyClose(){$('#story').hidden=true;RO.story=false;RO.cool=1;if(athInvitePending()&&RO.on&&state==='roam')setTimeout(()=>{if(RO.on&&state==='roam'&&!RO.story&&athInvitePending())storyCheck()},450)}
const roamBossOpen=()=>nFlags()>=BOSS_EV.need;
function roamPrompt(dt){const el=$('#roamPrompt');if(!el)return;if(RO.pmNew&&!RO.card){if(RO.pm!==RO.pmNew){RO.pm=RO.pmNew;const m=RO.pm;el.innerHTML=`<b>${markTitle(m)}</b><span>${TOUCH.on?'TAP TO OPEN':'ENTER TO OPEN'}</span>`;el.style.setProperty('--c',m.col||'#4ceaff')}RO.pmT=2.5}
  RO.pmNew=null;RO.pmT=Math.max(0,(RO.pmT||0)-dt);if(RO.card||RO.ch||RO.sp||RO.pmT<=0)RO.pm=null;el.hidden=!RO.pm}
function roamPromptOpen(){const m=RO.pm;if(!m||RO.card)return false;RO.pm=null;$('#roamPrompt').hidden=true;roamOpen(m);RO.cardPin=1;return true}
const BRIEF={checkpoint:['🟢','Drive through every ring in order.','The next ring glows green. Follow the arrow and the dotted line on the minimap.'],
 smash:['🧱','Smash all 12 brick piles around this spot.','Every pile is a pin on your minimap. The arrow points to the nearest one.'],
 longjump:['🛫','Hit the orange ramp ahead at full speed.','Hold BOOST in the air to fly further. Distance counts.'],
 drift:['🌀','Keep GAS on, steer and hold BRAKE to slide and score.','Long, unbroken drifts score most. 30 seconds.'],
 speed:['📸','Blast through the speed camera gate straight ahead.','Build speed and hold BOOST before the gate.'],
 collect:['⭐','Collect the golden bricks scattered nearby.','Each brick is a pin on your minimap. The arrow points to the nearest one.'],
 chase:['🚨','Catch the thief’s van and ram it 3 times.','Follow the red light beam (and the red pin on the minimap). BOOST when you are close.'],
 deliver:['📦','Carry the crates to the drop-off.','Follow the arrow. Drive gently: hard bumps break crates.'],
 ball:['⚽','Push the giant red ball into the goal.','The ball has a ⚽ marker, the goal has a light beam. The yellow arrow next to the ball points to the goal. Hit the ball from behind, in the arrow direction.'],
 escort:['🚗','Follow the car and stay close.','If you are more than 10 s away, the job fails.'],
 wall:['💥','Smash the 3 walls at 200+ km/h.','Each wall is a pin on the minimap. BOOST before you hit them.'],
 taxi:['🚕','Pick up the passenger, then drop them off.','Stop right next to each marker. 3 rides.'],
 photo:['📷','Stop on the blue ring in front of each tower for a photo.','Each photo spot is a pin on the minimap; the arrow points to the nearest one. Hold still for a second.'],
 stunt:['🤸','Land 3 big jumps of 45 m or more.','Use the ramps near here. BOOST before take-off.']};
function briefHTML(e){const b=BRIEF[e.kind],g=OTG_GOAL[e.kind],u=OTG_HI[e.kind]?OTG_U[e.kind]:' s',bs=(store.get('mho_stars',{})['otg:'+e.id])||0;return`<div class="brief"><div><i>${b[0]}</i><b>GOAL</b><span>${b[1]}</span></div><div><i>📍</i><b>WHERE</b><span>${e.where?e.where+' '+b[2]:'Starts right here. '+b[2]}</span></div></div>`}
const CARD_PAY={otg:550,quest:1000,sprint:1700,rival:2200,boss:4500,challenge:1700,mode:1300,season:800};
function cardStars(m,k,e,lock){const st=markStars(m),T=$('#rcTiers'),S=$('#rcStars');$('#rcType').textContent=(KIND_N[k]||'').toUpperCase();const rated=CARD_PAY[k]&&!lock;S.hidden=!rated;T.hidden=!rated;if(!rated){S.innerHTML='';T.innerHTML='';return}
  S.innerHTML=`<span class="big">${'★'.repeat(st)}<i>${'★'.repeat(3-st)}</i></span><small>${st>=3?'MASTERED':st?'YOUR BEST':'NOT PLAYED YET'}</small>`;
  const qg=qvCardG(m),g=qg?qg.g:(k==='otg'||k==='quest')?OTG_GOAL[e.kind]:null,u=qg?qg.u:g&&(OTG_HI[e.kind]?OTG_U[e.kind]:' s'),lab=g?[`${g[2]}${u}`,`${g[1]}${u}`,`${g[0]}${u}`]:['3rd place','2nd place','1st place'];
  const pay=qg?qg.pay:CARD_PAY[k];T.innerHTML=`<div class="tiers">${[1,2,3].map(n=>`<div class="${st>=n?'on':''}"><b>${'★'.repeat(n)}</b><span>${lab[n-1]}</span></div>`).join('')}</div><div class="rew"><span>🟡 ${pay.toLocaleString('de-DE')} per new ★</span>${st<3?'<span>🎁 garage part at ★★★</span>':'<span>✔ replays pay 20% studs</span>'}</div>`}
function roamOpen(m){RO.card=m;RO.cool=2;RO.cardPin=0;const c=$('#roamCard'),k=m.kind,e=m.ev,lock=markLocked(m),done=markDone(m);c.hidden=false;const img=c.querySelector('img');
  img.src=k==='quest'?npcAvatar(e):(k==='rival'||k==='boss')?avatar(e.p):(m.sp?m.sp.material.map.image:iconTex(m).image).toDataURL();c.querySelector('h4').textContent=(k==='rival'||k==='boss')?`${PD[e.p].flag} ${PD[e.p].full}${k==='boss'?' · BOSS':''}`:markTitle(m);
  let body='',go='RACE ▶';const P=c.querySelector('p'),X=$('#rcExtra');X.innerHTML='';
  if(k==='rival'){const td=TRACK_DEFS.find(t=>t.id===e.track);body=`Rival race · one-on-one · ${SIG[e.sig]} · ${td.short}<br><i>“${e.line}”</i>`}
  else if(k==='boss'){body=lock?`<i>“Come back with ${BOSS_EV.need} flags, nobody.”</i>`:`Grand Arena · 6 pilots · 3 laps on the Grand Prix<br><i>“${e.line}”</i>`}
  else if(k==='season'){const S=season(),rd=seasonRound(S.L,S.r);body=`${LEAGUES[S.L].name} · Round ${S.r+1}/5: <b>${rd.name}</b> on ${rd.short}${rd.dbl?' (double points)':''}<br>Championship points, credits and promotion.`;go='RACE ROUND ▶'}
  else if(k==='challenge'){body=lock?'Win a medal in the previous challenge first.':`${e.sub}<br>${e.goal}`}
  else if(k==='mode'){body=e.d+(e.track?` · ${TRACK_DEFS.find(t=>t.id===e.track).short}`:'');go='PLAY ▶'}
  else if(k==='quest'){const md=roamSave().otg[e.id]||0;c.querySelector('h4').textContent=e.em+' '+e.npc+' · '+e.name;body=`<i>“${e.hi}”</i>`;go='LET\'S GO ▶'}
  else if(k==='sprint'&&SPR_TRACK[e.id]){const bs=(store.get('mho_stars',{})['sprint:'+e.id])||0,td=TRACK_DEFS.find(t=>t.id===SPR_TRACK[e.id]);body=`🏟️ <b>Track race</b> · ${td.name}<br>${e.d}<br>${bs?`Your best ${'★'.repeat(bs)}${'☆'.repeat(3-bs)}${bs>=3?' · mastered: replays pay studs only':''}`:'1st ★★★ · 2nd ★★ · 3rd ★'}`;go='TO THE TRACK ▶'}
  else if(k==='sprint'){const r=spSave()[e.id]||{};body=`City sprint · ${(e.len/1000).toFixed(1)} km · ${e.ai.length} rivals · traffic on<br>${e.d}<br>${r.best?`Best ${fmt2(r.best)} · ${'★'.repeat(r.st||0)}${'☆'.repeat(3-(r.st||0))}`:'1st ★★★ · 2nd ★★ · 3rd ★ · 1,300 studs per ★'}`;go='RACE ▶'}
  else if(k==='otg'){body=qvUse(m)?QV_D[e.kind]:`${e.d}`;go='START ▶'}
  else if(k==='cruise'){body='Free drive through neon Frankfurt: smash props for studs, switch to boat on the Main and find the holo-gate challenges.';go='DRIVE ▶'}
  else if(k==='flight'){const T=CITYCFG[CCF.to];body=lock?`🔒 <b>Unlocks after ${ATH_NEED} Frankfurt flags</b> · you have ${fraFlags()}/${ATH_NEED}.<br>Beat the Frankfurt rivals one-on-one to win their flags. Someone in Athens is waiting for you.`:`<b>${CCF.code} → ${T.code} · ${T.name}</b> · ${CCF.flight}<br>Your progress here is saved. Studs, XP, cars and garage parts fly with you.${RO.ch||RO.sp?'<br><b>Finish the event first.</b>':''}`;go=CID==='fra'?'✈ FLY TO ATHENS ▶':'✈ FLY HOME TO FRANKFURT ▶'}
  else if(k==='garage'){body=`Credits <b>${season().cr.toLocaleString('de-DE')}</b> · choose your team and upgrade your craft.`;go='DONE';garageUI(X)}
  if(markCh(m)>chapter())body=`🔒 Unlocks in <b>Chapter ${markCh(m)} · ${CHS()[markCh(m)-1].title}</b> (${CHS()[markCh(m)-1].need} flags).`;
  if(CM.on&&!['garage','cruise'].includes(k)){go='SET ROUTE ▶';body+='<br><small>📍 Drive there to start. The minimap shows the way.</small>'}const bf=BRIEF[e&&e.kind];if((k==='otg'||k==='quest')&&e)body+=qvUse(m)?(lock?'':qvBrief(m)):bf?briefHTML(e):'';P.innerHTML=body;cardStars(m,k,e,lock);$('#rcGo').disabled=lock||(k==='flight'&&!!(RO.ch||RO.sp));$('#rcGo').textContent=lock?'🔒 LOCKED':go;RO.v*=.3;AU.sfx('pick')}
function garageUI(X){const S=season();{const gb=document.createElement('button');gb.className='go';gb.style.cssText='width:100%;margin-bottom:6px';gb.textContent='🔧 OPEN GARAGE BUILDER';gb.onclick=()=>gbOpen();X.appendChild(gb)}const tw=document.createElement('div');tw.className='gTeams';if(teamLocked(TEAMS[teamIdx])){teamIdx=0;store.set('mho_team',0)}const cur=TEAMS[teamIdx],pc=v=>Math.round(v*100);const vh=document.createElement('div');vh.className='gH';vh.innerHTML=`VEHICLE · <b>${cur.name}</b> <small>${cur.desc} · top ${pc(cur.top)} · acc ${pc(cur.acc)} · grip ${pc(cur.han)} · hull ${pc(cur.hull)}</small>`;X.appendChild(vh);
  TEAMS.forEach((t,i)=>{const b=document.createElement('button');const buy=t.cost&&!garOwned().includes(t.id)&&t.unlock<=medalPts(),lock=teamLocked(t)&&!buy;b.className='rnd'+(i===teamIdx?' cur':'')+(t.own||t.cost?' veh':'');b.title=t.desc;b.disabled=lock||(buy&&S.cr<t.cost);
    b.innerHTML=(lock?'🔒 ':'')+t.name+(buy?` · ${t.cost.toLocaleString('de-DE')} cr`:'')+(lock&&t.own?` <small>(${t.own==='SKYCUP'?'win the Sky Cup':'beat '+PD[t.own].full.split(' ').pop()})</small>`:'');
    b.onclick=()=>{if(buy){const S2=season();if(S2.cr<t.cost)return;S2.cr-=t.cost;saveSeason(S2);const o=garOwned();o.push(t.id);store.set('mho_garage',o);AU.sfx('brick')}teamIdx=i;store.set('mho_team',i);const m=RO.card;if(m)roamOpen(m)};tw.appendChild(b)});X.appendChild(tw);
  {const eq=perkEq(),ns=perkSlots(),h=document.createElement('div');h.className='gH';h.innerHTML=`PERKS · ${eq.length}/${ns} equipped <small>${ns<3?'· more slots at driver level '+(ns<2?8:16):''}</small>`;X.appendChild(h);const pw=document.createElement('div');pw.className='gPerks';
   PERKS.forEach(p=>{const un=perkUnlocked(p),on=eq.includes(p.id),b=document.createElement('button');b.className='perk'+(on?' on':'');b.disabled=!un;b.innerHTML=`<i>${p.icon}</i><b>${p.name}</b><small>${un?p.d:'🔒 '+perkReq(p)}</small>`;
     b.onclick=()=>{let e=perkEq();if(on)e=e.filter(x=>x!==p.id);else{if(e.length>=perkSlots())e.shift();e.push(p.id)}store.set('mho_perks',e);AU.sfx('pick');const m=RO.card;if(m)roamOpen(m)};pw.appendChild(b)});X.appendChild(pw)}
  UPG.forEach(u=>{const lv=S.up[u.k]||0,cost=UPC[lv];const d=document.createElement('div');d.className='upg';d.innerHTML=`<div><b>${u.name}</b> <small>${u.fx}</small></div><span class="pips">${[0,1,2,3,4].map(i=>`<i class="${i<lv?'on':''}"></i>`).join('')}</span>`;const b=document.createElement('button');b.className='rnd';const needS=UPS[lv]||0,haveS=totStars(),lockS=lv<5&&haveS<needS;b.textContent=lv>=5?'MAX':lockS?'🔒 '+needS+' ★':cost.toLocaleString('de-DE')+' cr';b.title=lockS?`Level ${lv+1} needs ${needS} ★ (you have ${haveS}). Win events to earn stars.`:'';b.disabled=lv>=5||lockS||S.cr<cost;b.onclick=()=>{const S2=season();if(S2.cr<cost||totStars()<needS)return;S2.cr-=cost;S2.up[u.k]=lv+1;saveSeason(S2);AU.sfx('brick');roamOpen(RO.card)};d.appendChild(b);X.appendChild(d)})}
function roamGo(){const m=RO.card;if(m&&m.kind==='flight'){if($('#rcGo').disabled)return;$('#roamCard').hidden=true;RO.card=null;if(!cityTravel(CCF.to))say('','✈ NO FLIGHT RIGHT NOW',1.6);return}if(CM.on&&m&&!['garage','cruise'].includes(m.kind)&&!$('#rcGo').disabled){const rm=RO.marks.find(q=>markKey(q)===markKey(m));if(rm){RO.card=null;$('#roamCard').hidden=true;cmClose();cmResume();RO.wp=rm;pickAdd(rm);say('',('ROUTE SET · drive to '+markTitle(rm)).toUpperCase(),2.2);AU.sfx('pick');return}}if(RO.sp&&m&&m.kind!=='sprint')sprintEnd();if(!m||$('#rcGo').disabled)return;pickAdd(m);const k=m.kind,e=m.ev;$('#roamCard').hidden=true;
  if(k==='garage'){RO.card=null;RO.cool=3;return}if(k==='cruise'){RO.card=null;cmClose();enterRoam();return}if(k==='otg'){RO.card=null;chStart(m);return}if(k==='sprint'&&!SPR_TRACK[e.id]){RO.card=null;sprintStart(m);return}if(k==='sprint'){RO.sprId=e.id;menuTab='quick';menuTrack=SPR_TRACK[e.id];quickTraffic=false}if(k==='quest'){RO.card=null;chStart(m);return}
  if(RO.on)roamSavePos();if(CM.on)cmClose();RO.lastMark=m;RO.on=false;$('#roam').hidden=true;RO.card=null;
  if(k==='rival'||k==='boss'){worldPick=e;menuTab='world'}else if(k==='season')menuTab='season';else if(k==='challenge'){menuTab='career';evIdx=m.idx}
  else if(k==='mode'){menuTab=e.k;if(e.track)menuTrack=e.track;if(e.k==='tt')ttFormat='lap';quickTraffic=true}
  RO.launching=true;startRace();RO.launching=false;RO.fromRoam=true}
// ---- On-The-Go challenges
function chStep(dt){const ch=RO.ch;if(ch.cd==null){ch.cd=3.2;ch.cdN=4}if(ch.cd>0){ch.cd-=dt;RO.v*=Math.max(0,1-dt*6);const n=Math.ceil(ch.cd);if(n!==ch.cdN){ch.cdN=n;if(n>0){say(String(n),ch.m.ev.name.toUpperCase(),.8);AU.sfx('beep')}else{say('GO!','',.8);AU.sfx('go')}}return}ch.t+=dt;const e=ch.m.ev;if(ch.v2)return qvStep(ch,dt);
  if(ch.kind==='checkpoint'){const o=ch.objs.find(o=>!o.done);if(o&&Math.hypot(o.x-RO.x,o.z-RO.z)<7.5){o.done=true;o.m.visible=false;ch.n++;AU.sfx('pick');hitPop('✔ CHECKPOINT '+ch.n+'/'+ch.objs.length);const nx=ch.objs.find(o=>!o.done);if(nx){nx.m.material=neonMat('#5dffb0',3);const n2=ch.objs.find(o=>!o.done&&o!==nx);if(n2)n2.m.visible=true}else return chEnd(ch.t)}}
  else if(ch.kind==='smash'){for(const o of ch.objs)if(!o.done&&Math.hypot(o.x-RO.x,o.z-RO.z)<4&&RO.y<4){o.done=true;o.m.visible=false;ch.n++;hitPop('🧱 SMASH '+ch.n+'/'+ch.objs.length);debris(V3(o.x,2,o.z),V3(0,8,0).addScaledVector(pl._fw||V3(),RO.v*.4),12,[o.col.clone(),new THREE.Color('#ffffff'),o.col.clone().multiplyScalar(.6)],.7,0);AU.sfx('brick');RO.v*=.95;if(ch.n>=ch.objs.length)return chEnd(ch.t)}}
  else if(ch.kind==='drift'){const H2=e.zone==='hbf'&&LMI.hbf,inZ=!!H2&&RO.x>H2.x0-26&&RO.x<H2.x1&&RO.z>H2.z0&&RO.z<H2.z1;if(H2&&inZ!==!!ch.inZ){ch.inZ=inZ;if(inZ)feed('UNDER THE GLASS ROOF · POINTS ×2',0,'#4ceaff')}if(H2&&!inZ)RO.wp={x:(H2.x0+H2.x1)/2,z:(H2.z0+H2.z1)/2+40,kind:'gate',name:'Station halls'};else if(H2)RO.wp=null;if(RO.dDir){const tr=RO.dT>2?3:RO.dT>1.1?2:RO.dT>.5?1:0;ch.n+=dt*Math.abs(RO.v)*1.2*(1+.5*tr)*(inZ?2:1)}if(ch.t>=ch.limit)return chEnd(ch.n)}
  else if(ch.kind==='speed'){const o=ch.objs[0];if(Math.hypot(o.x-RO.x,o.z-RO.z)<13)return chEnd(Math.abs(RO.v)*3.6)}
  else if(ch.kind==='collect'){for(const o of ch.objs){if(o.done)continue;o.m.rotation.y+=dt*2;if(Math.hypot(o.x-RO.x,o.z-RO.z)<5&&RO.y<6){o.done=true;o.m.visible=false;ch.n++;studGain(10);AU.sfx('pick');hitPop('⭐ BRICK '+ch.n+'/'+ch.objs.length);if(ch.n>=ch.objs.length)return chEnd(ch.t)}}}
  else if(ch.kind==='chase'){const T=ch.tg,N=HUB.nodes,A=N[T.a],B=N[T.b],L=Math.hypot(B.x-A.x,B.z-A.z)||1,dP=Math.hypot(T.x-RO.x,T.z-RO.z);T.v=dP<40?66:dP>260?40:58;T.t+=T.v*dt/L;
    if(T.t>=1){const nx=B.nb.filter(n=>n!==T.a);let best=nx[0]??T.a,bs=-1;for(const n of nx){const sc=Math.hypot(N[n].x-RO.x,N[n].z-RO.z)+R()*120;if(sc>bs){bs=sc;best=n}}T.a=T.b;T.b=best;T.t=0}
    const dx=(B.x-A.x)/L,dz=(B.z-A.z)/L;T.x=A.x+(B.x-A.x)*Math.min(1,T.t)-dz*6;T.z=A.z+(B.z-A.z)*Math.min(1,T.t)+dx*6;T.y=groundAt(T.x,T.z,(T.y||0)+4);T.m.position.set(T.x,T.y,T.z);T.m.rotation.y=Math.atan2(dx,dz);
    T.cd=Math.max(0,(T.cd||0)-dt);if(dP<7&&T.cd<=0&&Math.abs(RO.v)>20){T.cd=1;ch.n++;T.v+=10;const at=T.m.position.clone().add(V3(0,2,0));debris(at,V3(0,9,0),16,[new THREE.Color('#ffd12c'),new THREE.Color('#22252f')],1,at.y-2);for(let k=0;k<6;k++)studBurst(at,V3(dx,0,dz),40);AU.sfx('crash');shake=.6;feed('RAM '+ch.n+'/3',300,'#ff2d95');hitPop(ch.n>=3?'🚨 THIEF CAUGHT!':'💥 RAM '+ch.n+'/3',ch.n>=3?'#5dffb0':'#ffd400');if(ch.n>=3){burst(FIRE,at,40,30,.9,new THREE.Color(2,1,.3));return chEnd(ch.t)}}}
  else if(QK.has(ch.kind)){qStep(ch,dt);if(!RO.ch)return}
  if(ch.t>ch.limit&&!(ch.kind==='longjump'&&RO.takeoff))chEnd(null)}
function roamLanded(){const at=RO.airT||0;RO.airT=0;if(at>1&&pl){pl.bm=Math.min(100,pl.bm+at*12);feed('AIR '+at.toFixed(1)+' s',Math.round(at*200),'#c46bff');comboAdd(2)}const ch=RO.ch,t=RO.takeoff;RO.takeoff=null;if(!t)return;const d=Math.hypot(RO.x-t.x,RO.z-t.z);if(d>25)feed(`JUMP ${Math.round(d)} m`,Math.round(d*5),'#4ceaff');if(ch&&ch.v2)qvLand(ch,d);else if(ch&&ch.kind==='stunt'&&d>45){ch.n++;RO.wp=null;feed('STUNT '+ch.n+'/3 · '+Math.round(d)+' m',400,'#ff2d95');AU.sfx('style')}if(ch&&ch.kind==='longjump'&&t.r===ch.m.rampAt)chEnd(d)}
function chAbort(){const ch=RO.ch;RO.ch=null;if(!ch)return;RO.wp=null;qvClean(ch);for(const o of ch.objs||[])if(o&&o.m)(o.own||RO.grp).remove(o.m)}
function chResult(md,best,fresh,cr,v,e,isQ){const el=$('#chRes');if(!el)return;const val=v==null?'TIME UP':(OTG_HI[e.kind]?Math.round(v)+OTG_U[e.kind]:v.toFixed(1)+' s');
  el.innerHTML=`<b>${(isQ?e.name:e.name).toUpperCase()}</b><div class="st">${'★'.repeat(md)}<i>${'★'.repeat(3-md)}</i></div><span>${val}</span><small>${fresh?`⭐ ${fresh} NEW STAR${fresh>1?'S':''}!`:best>=3?'Already mastered ★★★ · replay pays studs only':md?`Your best is still ${'★'.repeat(best)}`:'No stars this time · try again'}${cr?` · +${cr.toLocaleString('de-DE')} studs`:''}</small>`;
  el.hidden=false;el.classList.remove('on');void el.offsetWidth;el.classList.add('on');clearTimeout(chResult.t);chResult.t=setTimeout(()=>el.hidden=true,4200)}
function chEnd(v){const ch=RO.ch;RO.ch=null;RO.wp=null;for(const o of ch.objs)(o.own||RO.grp).remove(o.m);const e=ch.m.ev,g=ch.g||OTG_GOAL[e.kind],HI=ch.hi??OTG_HI[e.kind];let md=0;
  if(v!=null)md=HI?(v>=g[0]?3:v>=g[1]?2:v>=g[2]?1:0):(v<=g[0]?3:v<=g[1]?2:v<=g[2]?1:0);if(ch.cap!=null)md=Math.min(md,ch.cap);
  const o=roamSave(),prev=o.otg[e.id]||0;if(md>prev){o.otg[e.id]=md;roamStore(o)}const isQ=ch.m.kind==='quest';
  const all=store.get('mho_stars',{}),key='otg:'+e.id,best=Math.max(all[key]||0,0),pay=ch.pay||(isQ?1000:550),fresh=Math.max(0,md-best),mastered=best>=3,cr=Math.round(pay*fresh+pay*(mastered?.2:.3)*Math.min(md,best));if(md)addXP(Math.round((isQ?120:40)*(fresh+(mastered?.1:.25)*Math.min(md,best))),e.name);chResult(md,best,fresh,cr,v,e,isQ);if(md>best||prev>(all[key]||0)){all[key]=Math.max(md,prev);store.set('mho_stars',all)}if(cr){const S2=season();S2.cr+=cr;saveSeason(S2)}const gift=md===3&&best<3?rewardItem():'';logDone(key,isQ?e.npc+' · '+e.name:e.name,isQ?'quest':'otg',md,v==null?'':(OTG_HI[e.kind]?Math.round(v)+OTG_U[e.kind]:v.toFixed(1)+' s'));
  void(md?'★'.repeat(md)+'☆'.repeat(3-md):'NO STARS',(v==null?'TIME UP':(OTG_HI[e.kind]?Math.round(v)+OTG_U[e.kind]:v.toFixed(1)+' s'))+(cr?` · +${cr.toLocaleString('de-DE')} studs`:'')+(fresh?` · ${fresh} new ★`:md?' · replay (30%)':'')+(gift?` · 🎁 ${gift}`:''),3);AU.sfx(md?'finish':'crash');RO.cool=3;if(isQ){clearTimeout(chEnd.q);chEnd.q=setTimeout(()=>{if(state==='roam')npcSay(e,md?e.win:e.lose)},900)}qvAfter(ch,md,v,cr)}
function roamPose(s,dt){const ud=s.mesh.userData,fw=V3(Math.sin(RO.h),0,Math.cos(RO.h)),us=V3(0,1,0),rs=V3().crossVectors(fw,us);
  s.bob=(s.bob||0)+dt*7;const bk=s.boatK=(s.boatK||0)+((s.boatMode?1:0)-(s.boatK||0))*Math.min(1,dt*14),dk=s.dirtK=(s.dirtK||0)+((s.dirtMode?1:0)-(s.dirtK||0))*Math.min(1,dt*14);
  let wH=0,wP=0,wR=0;if(bk>.02&&!s.air){const t=T,h0=waveH(RO.x,RO.z,t),fx=Math.sin(RO.h),fz=Math.cos(RO.h);wH=h0*bk;wP=Math.atan((waveH(RO.x+fx*3,RO.z+fz*3,t)-h0)/3)*1.6*bk;wR=Math.atan((waveH(RO.x+fz*2,RO.z-fx*2,t)-h0)/2)*1.6*bk}
  const hover=(s.air?0:1.6-1.05*bk-.25*dk+Math.sin(s.bob)*.14*SHIP_K+Math.sin(s.bob*.55)*.12*bk+wH)-(RO.landK||0)*.9;
  RO.landK=Math.max(0,(RO.landK||0)-dt*3);const acc=(RO.v-(s.pv??RO.v))/Math.max(dt,1e-3);s.pv=RO.v;s.pitch=(s.pitch||0)+((C26.on&&bk<.5?0:clamp(acc*.0045,-.06,.045))+wP-(s.pitch||0))*Math.min(1,dt*5);RO.c26aL=(RO.c26aL??acc)+(clamp(acc,-60,60)-(RO.c26aL??acc))*Math.min(1,dt*20);
  const target=clamp(bk*(-CTL.steer*.32*Math.min(1,s.v/30)+(RO.dDir?RO.dDir*.22:0))+(1-bk)*(C26.on?0:CR_roll())+wR,-.6,.6);s.roll=(s.roll||0)+(target-(s.roll||0))*Math.min(1,dt*6);const cr=Math.cos(s.roll),sr=Math.sin(s.roll);
  let r2=rs.clone().multiplyScalar(cr).addScaledVector(us,sr),u2=us.clone().multiplyScalar(cr).addScaledVector(rs,-sr),f2=fw.clone();if(s.air){const pa=clamp(Math.atan2(RO.vy,Math.max(10,s.v))*.7,-.45,.45);const f3=f2.clone().multiplyScalar(Math.cos(pa)).addScaledVector(u2,Math.sin(pa));u2=u2.multiplyScalar(Math.cos(pa)).addScaledVector(f2,-Math.sin(pa));f2=f3}
  if(!s.air&&s.pitch){const pc=Math.cos(s.pitch),ps=Math.sin(s.pitch),f3=f2.clone().multiplyScalar(pc).addScaledVector(u2,ps);u2=u2.clone().multiplyScalar(pc).addScaledVector(f2,-ps);f2=f3}
  ud.m.quaternion.setFromRotationMatrix(_m.makeBasis(r2,u2,f2.clone().negate()));
  {const thr=Math.max(.25,CTL.thr||0),hot=s.nitro,len=Math.min(22,(3+thr*6+Math.abs(RO.v)/Math.max(30,RO.top||60)*9)*(hot?1.6:1));for(const rb of ud.ribbons){rb.scale.z=len;rb.material.uniforms.uT.value=T;rb.material.uniforms.uCol.value.set(hot?'#7fe8ff':s.team.trail);rb.material.uniforms.uA.value=.55+thr*.45}for(const f of ud.flares){const k=(1.7+thr*.5+(hot?1.2:0))*(1+Math.random()*.08);f.scale.set(k,k,1)}}
  if(!s.air&&(RO.dDir||(CTL.brk&&Math.abs(RO.v)>25))){if(!RO.skid){const g=new THREE.PlaneGeometry(.9,2.8);g.rotateX(-Math.PI/2);const im=new THREE.InstancedMesh(g,new THREE.MeshBasicMaterial({color:0x101014,transparent:true,opacity:.5,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}),700);_m.makeScale(0,0,0);for(let i=0;i<700;i++)im.setMatrixAt(i,_m);im.frustumCulled=false;HUB.grp.add(im);RO.skid={im,i:0,t:0}}
    const K=RO.skid;K.t+=dt;if(K.t>.035){K.t=0;const q=new THREE.Quaternion().setFromAxisAngle(V3(0,1,0),RO.h);for(const sd of[-1,1]){const at=V3(RO.x,groundAt(RO.x,RO.z,RO.y+.3)+.07,RO.z).addScaledVector(fw,SC_S&&SC_S.on?-SC_K.skid[1]:-2.6).addScaledVector(rs,sd*(SC_S&&SC_S.on?SC_K.skid[0]:2.1));_m.compose(at,q,_ts.set(1,1,1));K.im.setMatrixAt(K.i++%700,_m)}K.im.instanceMatrix.needsUpdate=true;
      if(R()<.7)puff(s.mesh.position.clone().addScaledVector(fw,-3.2).addScaledVector(rs,(R()<.5?-1:1)*2),1,_tipC.setRGB(.85,.85,.88),1.4,5,.9,.32,1,2.5)}}
  s.mesh.position.set(RO.x,RO.y,RO.z);s.mesh.quaternion.identity();ud.m.position.set(0,hover,0);s._fw=fw;
  vehMode(s,dt);if(ud.wheels&&ud.wheels.visible)for(const w of ud.wheels.children)if(w.geometry===WHEEL)w.rotation.x-=RO.v*dt/1.05;
  if(bk>.5&&s.v>12&&R()<.35)emit(WATER,s.mesh.position.clone().addScaledVector(fw,-3.5).add(V3(rr(-2.5,2.5),-.4,0)),V3(rr(-3,3),rr(4,9),rr(-3,3)).addScaledVector(fw,-s.v*.15),.6,_tipC.setRGB(.3,.5,.85));
  if(dk>.5&&s.v>12&&R()<.5)puff(s.mesh.position.clone().addScaledVector(fw,-4),1,_tipC.setRGB(.42,.3,.18),2,7,1.1,.5,1.6,2)}
let camSnap=false;
const RCAM={chase:{b:8.5,bk:-1.2,h:2.8,hk:-.3,l:14,lk:8,ly:1.5,n:'CHASE'},close:{b:9,bk:3,h:3.2,hk:.8,l:10,lk:6,ly:1.8,n:'CLOSE'},far:{b:22,bk:6,h:7.5,hk:2,l:16,lk:10,ly:2,n:'FAR'},high:{b:16,bk:4,h:26,hk:4,l:10,lk:8,ly:0,n:'HIGH'},low:{b:10,bk:3,h:1.9,hk:.4,l:24,lk:10,ly:3,n:'LOW'}};
function roamCamCycle(){const k=Object.keys(RCAM),i=(k.indexOf(SET.rcam||'chase')+1)%k.length;SET.rcam=k[i];saveSet();camSnap=true;feed('CAMERA · '+RCAM[k[i]].n,0,'#4ceaff')}
function roamCam(dt){const C=RCAM[SET.rcam]||RCAM.chase;const sn=camSnap;camSnap=false;const k1=clamp(Math.abs(RO.v)/Math.max(30,RO.top||60),0,1.4);
  RO.camH=sn||RO.camH==null?RO.h:RO.camH+angDiff(RO.h,RO.camH)*Math.min(1,dt*(RO.dDir?3:TUNE.camK));const fw=V3(Math.sin(RO.camH),0,Math.cos(RO.camH)),p=V3(RO.x,RO.y,RO.z);
  const bmax=C.b+C.bk*k1;let back=bmax;for(let d=2;d<=bmax;d+=.5)if(roamHit(RO.x-fw.x*d,RO.z-fw.z*d,1.5,RO.y+2.5)){back=Math.max(CR_minBack(),d-1);break}
  RO.camB=sn||RO.camB==null||back<RO.camB?back:RO.camB+(back-RO.camB)*Math.min(1,dt*3);RO.camY=sn||RO.camY==null?RO.y:RO.camY+(RO.y-RO.camY)*Math.min(1,dt*TUNE.camY);
  camera.position.set(RO.x-fw.x*RO.camB,RO.camY+C.h+C.hk*k1+(pl&&pl.air?2:0)+Math.max(0,bmax-RO.camB)*.35,RO.z-fw.z*RO.camB);if(camera.position.y<RO.y+2)camera.position.y=RO.y+2;
  {const vt=RO.vh??RO.h;RO.camL=sn||RO.camL==null?vt:RO.camL+angDiff(vt,RO.camL)*Math.min(1,dt*TUNE.camK);RO.camR=sn?0:(RO.camR||0)+((RO.yr||0)-(RO.camR||0))*Math.min(1,dt*3)}const vf=V3(Math.sin(RO.camL),0,Math.cos(RO.camL));camera.lookAt(p.clone().addScaledVector(vf,C.l+C.lk*k1).add(V3(0,C.ly,0)));camera.rotateZ(clamp(-RO.camR*.02,-.035,.035));if(shake>0){camera.position.x+=rr(-1,1)*shake*.5;camera.position.y+=rr(-1,1)*shake*.35}
  if(RO.shadowOn){const d=V3(...MOOD.key[2]).normalize();moonL.position.set(RO.x,RO.y,RO.z).addScaledVector(d,400);moonL.target.position.set(RO.x,RO.y,RO.z);moonL.target.updateMatrixWorld()}fovKick*=Math.exp(-6*dt);const W13k=clamp(Math.abs(RO.v)/Math.max(30,RO.top||60),0,1.4),fv=TUNE.fov+({narrow:-6,normal:0,wide:8}[SET.fov]||0)+Math.min(24,TUNE.fovSpd*W13k+7*W13k*W13k)+(pl&&pl.nitro?6:0)+fovKick*.6;camera.fov+=(pFov(fv)-camera.fov)*Math.min(1,dt*4);camera.updateProjectionMatrix()}
let CB={n:0,t:0,best:0};const comboMult=()=>CB.n>=50?5:CB.n>=25?3:CB.n>=10?2:1;
function comboAdd(k){if(state!=='roam')return;const m0=comboMult();CB.n+=k;CB.t=2.8;const m1=comboMult();if(m1>m0){feed('CHAIN ×'+m1,0,'#ff2d95');AU.sfx('style');fovKick=Math.max(fovKick,4)}}
const POPS=[{k:'smash',name:'SMASH SPREE',goal:25,lim:25,u:'smashed'},{k:'drift',name:'DRIFT KING',goal:6,lim:25,u:'s of drift'},{k:'air',name:'AIR TIME',goal:3.5,lim:30,u:'s in the air'},{k:'speed',name:'SPEED DEMON',goal:3,lim:30,u:'s above 160 km/h'},{k:'chain',name:'CHAIN REACTION',goal:30,lim:30,u:'chain'}];
function popStep(dt,busy){RO.popCd=(RO.popCd??25)-dt;const P=RO.pop;
  if(!P){if(RO.popCd<=0&&!busy&&!RO.ch&&!RO.card&&!RO.sp&&roamSave().tut){const d=POPS[Math.floor(R()*POPS.length)];RO.pop=Object.assign({},d,{t:0,v:0,s0:HUB.smashed,txt(){return `${this.k==='smash'||this.k==='chain'?Math.floor(this.v):this.v.toFixed(1)} / ${this.goal} ${this.u}`}});AU.sfx('go');say(d.name,'POP-UP CHALLENGE · '+d.lim+' s',1.6)}return}
  if(P.done){P.t+=dt;if(P.t>2.2){RO.pop=null;RO.popCd=60+R()*30}return}
  P.t+=dt;if(P.k==='smash')P.v=HUB.smashed-P.s0;else if(P.k==='drift'){if(RO.dDir)P.v+=dt}else if(P.k==='air'){if(pl&&pl.air)P.v+=dt}else if(P.k==='speed'){if(Math.abs(RO.v)*3.6>160)P.v+=dt}else if(P.k==='chain')P.v=Math.max(P.v,CB.n);
  if(P.v>=P.goal){P.done=true;P.t=0;const S2=season();S2.cr+=300;saveSeason(S2);addXP(80,P.name.toLowerCase());AU.sfx('finish');say('CHALLENGE COMPLETE','+300 studs',1.8);return}
  if(P.t>=P.lim){RO.pop=null;RO.popCd=50+R()*30;say('','CHALLENGE MISSED',1)}}
function packInit(grp){const got=packs(),bl=HUB.blocks.filter(b=>b.t==='park'||b.t==='plaza'||b.t==='site'||b.t==='yard'),sp=CID!=='fra'?[WP(1530,610),WP(115,-455)]:[[TAU_SUM.x-35,TAU_SUM.z+45],[TAU_CAS.x-15,TAU_CAS.z+15]];
  for(const B of bl.slice(6)){const x=(B.x0+B.x1)/2-((B.x1-B.x0)*.25),z=(B.z0+B.z1)/2;if(sp.every(p=>Math.hypot(p[0]-x,p[1]-z)>420)&&!roamHit(x,z,5)&&!inRiver(x,z,-5))sp.push([x,z]);if(sp.length>=12)break}
  for(let i=0;sp.length<12&&i<HUB.nodes.length;i+=7){const n=HUB.nodes[i];if(sp.every(p=>Math.hypot(p[0]-n.x,p[1]-n.z)>300)&&!roamHit(n.x-12,n.z+12,5)&&!inRiver(n.x-12,n.z+12,-5))sp.push([n.x-12,n.z+12])}
  const box=mergeG([cbox(4.2,3.4,4.2,0,0,0,'#2f7bff'),cbox(4.3,.5,4.3,0,1.2,0,'#ffd12c'),...[-1,1].flatMap(x=>[-1,1].map(z=>ccyl(.6,.6,.45,x*1.05,1.9,z*1.05,'#2f7bff',10)))]),mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.4,emissive:new THREE.Color('#1a3aa0'),emissiveIntensity:.35}),bm=new THREE.MeshBasicMaterial({color:glowCol('#4c8bff',1.2),transparent:true,opacity:.3,blending:THREE.AdditiveBlending,depthWrite:false});
  RO.packs=sp.slice(0,12).map(([x,z],i)=>{const y=groundAt(x,z,40)+2.4,m=new THREE.Mesh(box,mat);m.position.set(x,y,z);m.visible=!got.includes(i);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.9,2.6,90,10,1,true),bm);beam.position.y=45;m.add(beam);grp.add(m);return{i,x,z,y,m,beam}})}
function packStep(dt){if(!RO.packs)return;for(const p of RO.packs){if(!p.m.visible)continue;p.m.rotation.y+=dt*1.2;p.m.position.y=p.y+Math.sin(T*1.6+p.i)*.5;const d=Math.hypot(p.x-RO.x,p.z-RO.z);p.beam.visible=d<300;
    if(d<7&&Math.abs(p.m.position.y-(RO.y+1.5))<6){p.m.visible=false;const o=packs();if(o.includes(p.i))continue;o.push(p.i);store.set('mho_packs',o);const un=[];for(const c in GB_PARTS)for(const q of GB_PARTS[c])if(q[2]&&q[2].pack===p.i)un.push(q[1]);for(const q of GB_PATS)if(q[2]&&q[2].pack===p.i)un.push(q[1]+' livery');for(const q of GB_HORNS)if(q[2]&&q[2].pack===p.i)un.push(q[1]+' horn');
      AU.sfx('finish');burst(SPARK,V3(p.x,p.m.position.y,p.z),40,20,.8,new THREE.Color(.8,1.4,2.8));addXP(80,'brick pack');studGain(150,1);say('BRICK PACK '+o.length+'/12',('NEW IN GARAGE: '+un.join(' · ')).toUpperCase(),2.6);comboAdd(5)}}}
function gbStep(dt){packStep(dt);if(!RO.gbs)return;for(const g of RO.gbs){if(!g.m.visible)continue;g.m.rotation.y+=dt*2;g.m.position.y=g.y+Math.sin(T*2+g.i)*.4;const d=Math.hypot(g.x-RO.x,g.z-RO.z);g.beam.visible=d<220;
    if(d<6&&Math.abs(g.m.position.y-(RO.y+1.5))<5){g.m.visible=false;const o=roamSave();o.gb=o.gb||[];if(o.gb.includes(g.i))continue;o.gb.push(g.i);roamStore(o);studGain(250,1);roamHeal(30);addXP(60,'golden brick');AU.sfx('finish');burst(SPARK,V3(g.x,g.m.position.y,g.z),40,20,.8,new THREE.Color(2.6,2,.6));say('GOLDEN BRICK',`${o.gb.length} / ${RO.gbs.length} found`,2);comboAdd(5)}}}
function comboStep(dt){if(CB.n<=0)return;CB.t-=dt;if(CB.t<=0){const n=CB.n,m=comboMult();CB.n=0;if(n>=5){const bonus=Math.round(n*2*m*streetMul());const S2=season();S2.cr+=bonus;saveSeason(S2);addXP(Math.round(n/2));feed(`CHAIN ${n} · +${bonus} studs`,bonus,'#ffd12c');if(n>CB.best){CB.best=n;const o=roamSave();if(n>(o.bestChain||0)){o.bestChain=n;roamStore(o);say('','NEW BEST CHAIN · '+n,1.6)}}}}}
function huQ(s){const M=huQ.m||(huQ.m=new Map());let e=M.get(s);if(!e||!e.isConnected){e=document.querySelector(s);if(e)M.set(s,e)}return e}
function huT(el,v){v=''+v;if(el.textContent!==v)el.textContent=v}function huS(el,p,v){const k='_hu'+p;if(el[k]!==v){el[k]=v;el.style[p]=v}}function huH(el,v){if(el.hidden!==v)el.hidden=v}function huTop(v){const el=huQ('#roamTop');if(el._h!==v){el._h=v;el.innerHTML=v}}
function roamGauge(){{const el=huQ('#roamCombo');if(CB.n>0){huH(el,false);huT(huQ('#roamCombo b'),CB.n);huT(huQ('#roamCombo em'),'×'+comboMult());huS(huQ('#roamCombo i'),'width',Math.round(CB.t/2.8*100)+'%');const cn='m'+comboMult();if(el.className!==cn)el.className=cn}else huH(el,true)}
  {const P=RO.pop,el=huQ('#roamPop');if(P){huH(el,false);huT(huQ('#roamPop h5'),P.name);huT(huQ('#roamPop span'),P.txt());huS(huQ('#roamPop i'),'width',Math.min(100,Math.round(P.v/P.goal*100))+'%');huT(huQ('#roamPop small'),P.done?'COMPLETE!':Math.max(0,P.lim-P.t).toFixed(1)+' s')}else huH(el,true)}
  huT(huQ('#rgGb'),'🧱 '+((store.peek('mho_roam',{}).gb||[]).length)+'/'+(RO.gbs?RO.gbs.length:30));const s=pl;if(!s)return;const g=huQ('#roamGauge');huT(huQ('#rgSpd'),Math.round(Math.abs(RO.v)*3.6));huS(huQ('#rgBar i'),'width',Math.round(s.bm)+'%');{const hp=RO.hp??100,el=huQ('#rgHull');huS(el.firstChild,'width',Math.round(hp)+'%');huS(el.firstChild,'background',hp>60?'#5dffb0':hp>30?'#ffd12c':'#ff2d55');el.classList.toggle('low',hp<30)}g.classList.toggle('on',!!s.nitro)}
function markBadges(){HUB.mbT=(HUB.mbT||0)+1;if(HUB.mbT%45)return;for(const m of RO.marks){if(!m.g)continue;const d=Math.hypot(m.x-RO.x,m.z-RO.z);if(d>420){if(m.sb)m.sb.visible=false;continue}const st=markStars(m);if(!st){if(m.sb)m.sb.visible=false;continue}if(!m.sb||m.sbN!==st){if(!m.sb){const[c,g]=cv(256,96),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));sp.scale.set(12,4.5,1);sp.position.y=16;sp.renderOrder=4;m.g.add(sp);m.sb=sp;m.sbC=[c,g]}const[c,g]=m.sbC;g.clearRect(0,0,256,96);g.fillStyle='rgba(20,20,19,.85)';g.beginPath();g.roundRect(8,10,240,76,38);g.fill();g.lineWidth=6;g.strokeStyle='#ffd400';g.stroke();g.font='900 54px system-ui';g.textAlign='center';g.textBaseline='middle';for(let i=0;i<3;i++){g.fillStyle=i<st?'#ffd400':'rgba(255,255,255,.28)';g.fillText('★',68+i*60,50)}m.sb.material.map.needsUpdate=true;m.sbN=st}m.sb.visible=m.g.visible}}
function roamHud(){roamGauge();markBadges();raceHud();{const fx=huQ('#speedFx'),k=RO.boosting?clamp(Math.abs(RO.v)/40,0,1):0,o=+fx.style.opacity||0,n=Math.abs(k-o)<.004?k:Math.round((o+(k-o)*.15)*1000)/1000;if(n!==o)fx.style.opacity=n}const F=flagsR(),nf=RIVAL_EV.filter(e=>F[e.p]).length,ch=RO.ch,done=RO.marks.filter(markDone).length;
  if(!(RO.sp&&RO.sp.hud))huTop(ch&&ch.v2?'':ch?`<b>${ch.m.ev.name.toUpperCase()}</b>${OTG_GOAL[ch.kind]?`<em class="lst">${liveStars(ch)}</em><small class="tgt">${(()=>{const g=OTG_GOAL[ch.kind],u=OTG_HI[ch.kind]?OTG_U[ch.kind]:' s';return`★ ${g[2]}${u} · ★★ ${g[1]}${u} · ★★★ ${g[0]}${u}`})()}</small>`:''}<span>${ch.kind==='longjump'?'Ramp ahead · hold BOOST in the air':ch.kind==='drift'?`${Math.round(ch.n)} pts · ${Math.max(0,ch.limit-ch.t).toFixed(1)} s left · steer + hold BRAKE`:ch.kind==='speed'?`Radar ${Math.round(Math.hypot(ch.objs[0].x-RO.x,ch.objs[0].z-RO.z))} m · ${Math.round(Math.abs(RO.v)*3.6)} km/h`:QK.has(ch.kind)?qHud(ch):ch.kind==='chase'?`Rams ${ch.n}/3 · ${ch.t.toFixed(1)} s · target ${Math.round(Math.hypot(ch.tg.x-RO.x,ch.tg.z-RO.z))} m`:`${ch.n}/${ch.objs.length} · ${ch.t.toFixed(1)} s`} · Esc cancel</span>`:(RO.fit<.9?`<span><b style="color:#ff7a3c;display:inline">WRONG VEHICLE FOR ${RO.terr==='water'?'WATER':RO.terr==='dirt'?'DIRT':'ROAD'} · ⟳</b></span>`:''));
  const a=huQ('#roamArrow'),tg=ch?(chNext(ch)||(ch.kind==='longjump'?ch.m.rampAt:null)):RO.near;if(tg){const dx=tg.x-RO.x,dz=tg.z-RO.z,cue=ch?D24_cue():null,ang=cue?cue.ang:Math.atan2(dx,dz)-RO.h;huH(a,false);huS(huQ('#roamArrow i'),'transform',`rotate(${(-ang).toFixed(3)}rad)`);a.classList.toggle('d24soon',!!(cue&&cue.soon&&cue.t));
    /* D24: on a GPS route the arrow is turn-by-turn (next turn + distance, ≥ TUNE.tcLead s ahead); without one it points at the target */huT(huQ('#roamArrow span'),cue?`${v85Verb(ch)} · ${cue.txt}`:`${ch?v85Verb(ch):tg.ev||tg.name?markTitle(tg):''} → ${Math.round(Math.hypot(dx,dz))} m`)}else huH(a,true);qvHud()}
