// ===== M1 "the first 30 minutes are a game": scene beats + radio, Schattenwerk goons + mission HP, free-roam item boxes + FIRE,
// authored story missions on the qv2 stage engine (landmark anchors, enter hooks, phase checkpoints), NEXT guidance, chapter-1 reveal.
// Self-contained: every global is prefixed M1_; existing functions are extended by re-binding (fn=(f=>...)(fn)), no edits inside them.
CK.push('mho_m1');CITYK.push('mho_m1');for(const k in CITYCFG){CITYCFG[k].ch='Chapter';CITYCFG[k].edgeT='EDGE OF THE MAP'}
const M1={s:null,init:0,mk:0,cs:null,goons:[],hp:100,hpT:9,cp:null,boxes:[],inv:null,spin:0,proj:[],mines:[],ghost:0,idle:0,hintT:45,log:{ram:0,td:0,hit:0,fire:0,pick:0},act:[],ramps:[],rv:null,sup:0,fs:0,taps:0,skips:0,next:null,pillH:'',noScene:0,restoring:null,tdc:null,gid:0};
const M1_WHO={HILDE:{n:'Oma Hilde',col:'#ff9a3c',em:'🔧'},KAISER:{n:'Vex Kaiser',col:'#ffd12c',em:'👑'},ROSSI:{n:'Luca Rossi',col:'#ff2d55',em:'🏎'},BRIX:{n:'BRIX',col:'#4ceaff',em:'🤖'},KLAUS:{n:'Wirt Klaus',col:'#36d17a',em:'🍎'},BRECHER:{n:'Brecher',col:'#c9a227',em:'🔨'}};
function M1_av(w){if(PD[w])return avatar(w);const q=M1_WHO[w]||M1_WHO.BRIX;return npcAvatar({id:'m1_'+w,col:q.col,em:q.em})}
function M1_radio(w,txt){const q=M1_WHO[w]||M1_WHO.HILDE;QAV['m1r_'+w]=M1_av(w);M1.fs=1;try{npcSay({id:'m1r_'+w,npc:q.n,col:q.col},txt)}finally{M1.fs=0}M1.lastRadio=w}
const M1_snd=n=>{try{AU.sfx(n)}catch(e){}};
// ---------- persistent state (per slot, per city via CK/CITYK)
function M1_st(){if(M1.slot!==SLOT){M1.slot=SLOT;M1.s=null;M1.isInit=0;M1.init=0;M1.mk=0}if(!M1.s)M1.s=store.get('mho_m1',null)||{v:1,step:0,fresh:0,done:{},wpn:0};return M1.s}
function M1_save(){store.set('mho_m1',M1.s)}
function M1_initState(){M1_st();if(M1.isInit||CID!=='fra')return;M1.isInit=1;if(!store.get('mho_m1',null)){const sv=roamSave();M1.s.fresh=!sv.tut&&!sv.pos&&nFlags()===0?1:0;M1_save()}}
function M1_rep(){const d=M1_st().done;return['hotdrop','heist','toll','hunt','rampage'].filter(k=>d[k]).length}
const M1_gated=()=>CID==='fra'&&!!M1.s&&!!M1.s.fresh&&M1.s.step<4;
const M1_wpn=()=>!!(M1.s&&M1.s.wpn)||(RO.ch&&RO.ch.m.m1&&RO.ch.m.ev.items);
// ---------- geometry helpers
function M1_P(x,z,R=320){const G=qvGraph();if(!G)return{x,z};const i=qvNear(x,z,R);return i<0?{x,z}:{x:G.X[i],z:G.Z[i],i}}
function M1_path(pts){let P=[];for(let k=1;k<pts.length;k++){const q=qvPath(pts[k-1].x,pts[k-1].z,pts[k].x,pts[k].z);P=P.concat(k>1?q.slice(1):q)}const C=qvCum(P);return{P,C,L:C[C.length-1]}}
function M1_car(geo,col,sc,trim){if(!/boat/.test(geo))try{const g=CR_npcVeh(geo,col);RO.grp.add(g);return g}catch(e){console.warn('CR npc',e)}const mat=kmMat('car').clone();mat.color=new THREE.Color(col);const g=new THREE.Group(),b=new THREE.Mesh(kmGeo(geo,sc),mat);g.add(b);if(trim){const s=new THREE.Mesh(new THREE.BoxGeometry(sc*.95,.25,sc*1.9),neonMat(trim,2.4));s.position.y=sc*.62;g.add(s)}RO.grp.add(g);return g}
function M1_put(m,x,z,h){m.position.set(x,groundAt(x,z,(m.position.y||0)+4),z);if(h!=null)m.rotation.y=h}
function M1_obj(o){M1.act.push(o);return o}
// ---------- scenes: letterbox + 2-shot/orbit camera + speaker lines; tap = next line, SKIP / Esc = skip all; mission time pauses
function M1_ui(){if($('#m1Cs'))return;const st=document.createElement('style');st.textContent=M1_CSS;document.head.appendChild(st);const r=$('#roam');
  const cs=document.createElement('div');cs.id='m1Cs';cs.hidden=true;cs.innerHTML='<div class="m1lb m1lt"></div><div class="m1lb m1lbb"></div><div class="tk"><img alt=""><div><b></b><p></p><small>TAP TO CONTINUE</small></div></div><button id="m1Skip">SKIP ▸▸</button>';document.body.appendChild(cs);
  const go=e=>{e.preventDefault();e.stopPropagation();if(e.target&&e.target.id==='m1Skip'){M1.skips++;M1_csEnd();return}M1.taps++;M1_csNext()};cs.addEventListener('click',go);cs.addEventListener('touchstart',go,{passive:false});
  const nx=document.createElement('button');nx.id='m1Next';nx.hidden=true;nx.innerHTML='<i></i><div><b>NEXT</b><span></span><small></small></div>';r.appendChild(nx);nx.addEventListener('click',e=>{e.stopPropagation();M1_nextGo()});
  const hp=document.createElement('div');hp.id='m1Hp';hp.hidden=true;hp.innerHTML='<b>❤</b><i><u></u></i><small></small>';r.appendChild(hp);
  const it=document.createElement('div');it.id='m1Item';it.hidden=true;it.innerHTML='<img alt=""><b></b><small>F</small>';r.appendChild(it);it.addEventListener('click',e=>{e.stopPropagation();M1_fire()});
  const tw=document.createElement('button');tw.className='tbtn';tw.id='tW';tw.textContent='ITEM';$('#touch').appendChild(tw);tb('#tW',()=>M1_fire(),()=>{});
  addEventListener('resize',()=>setTimeout(M1_tw,60))}
function M1_tw(){const w=$('#tW');if(!w)return;const show=state==='roam'&&TOUCH.on&&!$('#touch').hidden&&(M1_wpn()||!!M1.inv)&&!M1.cs;w.style.display=show?'grid':'none';if(!show)return;const L=['#tB','#tD','#tN','#tF','#tG'].map(s=>$(s)).filter(e=>e&&e.offsetParent!==null).map(e=>e.getBoundingClientRect()).filter(r=>r.width>4);if(!L.length)return;
  const top=Math.min(...L.map(r=>r.top)),right=Math.max(...L.map(r=>r.right)),sz=Math.round(clamp(Math.min(innerWidth,innerHeight)*.15,48,64));w.style.width=w.style.height=sz+'px';w.style.left=Math.round(right-sz-6)+'px';w.style.top=Math.round(Math.max(56,top-sz-14))+'px';w.style.right='auto';w.style.bottom='auto';
  if(M1.inv){w.style.backgroundImage=M1.inv==='ghost'?'none':`url(${itemIcon(M1.inv==='mines'?'mines':'missile')})`;w.textContent=M1.inv==='ghost'?'👻':''}else{w.style.backgroundImage='none';w.textContent='ITEM'}w.classList.toggle('dim',!M1.inv)}
// BG23: every deliberate jump (scene camera cut, scene end, checkpoint respawn, story warp) cuts through black, so it never reads as a teleport
function BG23_cut(){const f=$('#warpFade');if(!f)return;f.style.transition='none';f.classList.add('on');void f.offsetWidth;clearTimeout(BG23_cut.t);BG23_cut.t=setTimeout(()=>{f.style.transition='opacity .35s';f.classList.remove('on')},120)}
function M1_scene(D){if(M1.noScene){if(D.end)D.end();return}M1_ui();if(M1.cs)M1_csEnd();M1.cs={D,i:-1,t:0,lt:0,cam:null};BG23_cut();RO.frozen=true;RO.v=0;document.body.classList.add('m1cs');$('#m1Cs').hidden=false;$('#npcSay').hidden=true;if(D.start)D.start();M1_csNext();camSnap=true}
function M1_csNext(){const C=M1.cs;if(!C)return;C.i++;C.lt=0;const L=C.D.lines;if(C.i>=L.length)return M1_csEnd();const[w,txt]=L[C.i],el=$('#m1Cs');el.querySelector('img').src=M1_av(w);el.querySelector('b').textContent=(M1_WHO[w]||{n:w}).n;el.querySelector('p').innerHTML=txt;el.querySelector('.tk').style.borderColor=(M1_WHO[w]||{}).col||'#ffd400';M1_snd('pick')}
function M1_csEnd(){const C=M1.cs;if(!C)return;M1.cs=null;pressed.fire=false;$('#m1Cs').hidden=true;document.body.classList.remove('m1cs');RO.frozen=false;camSnap=true;BG23_cut();if(C.D.end)C.D.end();M1_tw()}
function M1_csTick(dt){const C=M1.cs;if(!C)return;C.t+=dt;C.lt+=dt;if(C.D.tick)C.D.tick(dt,C.t);if(C.lt>(C.D.dur||4.6)&&!M1.csHold)M1_csNext()}
function M1_csCam(dt){const C=M1.cs;if(!C)return;const cam=C.D.cam||{};let a=cam.a?cam.a():{x:RO.x,z:RO.z},b=cam.b?cam.b():a,mx=(a.x+b.x)/2,mz=(a.z+b.z)/2,my=groundY(mx,mz);let want;
  if(cam.mode==='orbit'){const an=(cam.a0||0)+C.t*.22,r=cam.r||60;want=V3(mx+Math.sin(an)*r,my+(cam.h||30),mz+Math.cos(an)*r)}
  else{if(!C.cam||C.t-(C.camT||0)>1.2){C.camT=C.t;const dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz)||1,ux=dx/d,uz=dz/d,px=-uz,pz=ux;const los=(cx,cy,cz,tx,tz)=>{const ty=groundY(tx,tz)+2;if(roamHit(cx,cz,1.5,cy-1))return false;for(let s=.1;s<.97;s+=.08)if(roamHit(cx+(tx-cx)*s,cz+(tz-cz)*s,.8,cy+(ty-cy)*s))return false;return true};
    const C0=[];for(const[e,sg]of[[b,1],[a,-1]])for(const back of[22,30,16])for(const side of[5,-5,9,-9]){C0.push([e.x+ux*sg*back+px*side,e.z+uz*sg*back+pz*side,5.5+back*.12])}for(const sd of[1,-1])for(const k of[1,1.4]){const r=Math.max(16,d*.9)*k;C0.push([mx+px*sd*r-ux*r*.35,mz+pz*sd*r-uz*r*.35,5+r*.18])}
    let best=null;for(const[cx,cz,h]of C0){const cy=groundY(cx,cz)+h;if(los(cx,cy,cz,a.x,a.z)&&los(cx,cy,cz,b.x,b.z)){best=[cx,cy,cz];break}}if(!best&&C.cam)best=C.cam;C.cam=best||[mx+px*8,my+48,mz+pz*8]}want=V3(C.cam[0],C.cam[1],C.cam[2])}
  camera.position.lerp(want,camSnap?1:Math.min(1,dt*2.5));camSnap=false;camera.lookAt(mx,my+2.5,mz);camera.fov+=(62-camera.fov)*Math.min(1,dt*3);camera.updateProjectionMatrix()}
// ---------- goons: Schattenwerk cars with an aggressor brain (hunt the player along the GPS graph, ram, flee at 1 HP, takedown on a hard ram)
const M1_GK={rammer:{geo:'sedan-sports',sc:2.7,hp:2,dmg:8,v:1,col:'#18181d'},heavy:{geo:'truck',sc:3.4,hp:4,dmg:13,v:.82,col:'#2a2a31',shield:1},shield:{geo:'suv',sc:2.9,hp:2,dmg:14,v:.95,col:'#23232b',shield:1},lt:{geo:'sedan-sports',sc:3,hp:4,dmg:12,v:1.12,col:'#0e0e12',mines:1},thief:{geo:'van',sc:3,hp:2,dmg:10,v:1,col:'#20242c'}};
function M1_goon(kind,x,z,o={}){const K=M1_GK[kind]||M1_GK.rammer,m=M1_car(o.geo||K.geo,o.col||K.col,K.sc,'#ffd12c');const bar=new THREE.Mesh(new THREE.BoxGeometry(K.sc*.8,.35,.6),neonMat(kind==='thief'?'#ff9a3c':'#ff2d55',3));bar.position.y=K.sc*1.25;m.add(bar);
  const g={id:++M1.gid,kind,K,x,z,y:groundY(x,z),h:0,m,hp:o.hp||K.hp,hp0:o.hp||K.hp,cd:1.2,rt:Math.random()*1.2,s:0,P:null,C:null,st:'hunt',ft:0,S:o.S||null,dead:0,P0:o.P||null,stall:0,bst:0,drop:o.drop||0,dropT:3,mt:5};M1_put(m,x,z);M1.goons.push(g);return g}
function M1_spawn(S,kind,n,at,r0=160,r1=260){const G=qvGraph();const out=[];for(let k=0;k<n;k++){let p=null;for(let t=0;t<12&&!p;t++){const a=(at&&at.a!=null?at.a:Math.random()*6.28)+(Math.random()-.5)*1.6,d=r0+Math.random()*(r1-r0),cx=(at?at.x:RO.x)+Math.sin(a)*d,cz=(at?at.z:RO.z)+Math.cos(a)*d,i=qvNear(cx,cz,200);if(i>=0&&Math.hypot(G.X[i]-RO.x,G.Z[i]-RO.z)>60&&!M1.goons.some(q=>!q.dead&&Math.hypot(q.x-G.X[i],q.z-G.Z[i])<14))p={x:G.X[i],z:G.Z[i]}}if(!p)p={x:RO.x+Math.sin(k)*r0,z:RO.z+Math.cos(k)*r0};out.push(M1_goon(kind,p.x,p.z,{S}))}return out}
function M1_hitGoon(g,dmg,why){if(g.dead)return;g.hp-=dmg;const at=g.m.position.clone().add(V3(0,2,0));debris(at,V3(0,6,0),7,[new THREE.Color('#18181d'),new THREE.Color('#ffd12c')],.5,at.y-2);M1_snd('crash');shake=Math.max(shake,.45);if(g.hp<=0)return M1_takedown(g);g.stall=.7;if(g.kind==='thief'){g.bst=2;g.inv=3}else if(g.kind==='lt'){g.bst=2.4}else if(g.hp===1&&g.kind==='rammer'){g.st='flee';g.ft=2.6}hitPop((why||'💥 HIT')+` · ${g.hp}/${g.hp0}`,'#ffd400')}
function M1_takedown(g){g.dead=1;g.dt=0;g.vy=8;g.spin=(Math.random()-.5)*9;const at=g.m.position.clone().add(V3(0,2,0));debris(at,V3(Math.sin(RO.h)*12,7,Math.cos(RO.h)*12),12,[new THREE.Color('#18181d'),new THREE.Color('#ffd12c'),new THREE.Color('#ff2d55')],.6,at.y-2);burst(FIRE,at,camera.position.distanceTo(at)<14?6:16,20,.6,new THREE.Color(1.6,.8,.25));for(let k=0;k<3;k++)studBurst(at,V3(Math.sin(g.h),0,Math.cos(g.h)),36);
  M1_snd('takedown');slowmo=Math.max(slowmo,.45);fovKick=Math.max(fovKick,12);shake=.5;hitPop(g.kind==='thief'?'🚨 GOT HIM!':'💥 TAKEDOWN!','#5dffb0');studGain(120,1);M1.log.td++;M1.hp=Math.min(100,M1.hp+10);if(M1.tok===g.id)M1.tokT=0;M1.tdc={x:g.x,z:g.z,t:.9};if(g.S)g.S.kill=(g.S.kill||0)+1;const ch=RO.ch;if(ch&&ch.v2&&ch.v2.L.st[ch.v2.si]&&ch.v2.L.st[ch.v2.si].bonus)ch.v2.left+=ch.v2.L.st[ch.v2.si].bonus}
// BG23: ram knockback is a short slide (was an instant 10-14 m jump; a path-locked van then snapped back on the next frame), and a
// re-route starts where the goon is (was the nearest road node, a 6-9 m snap every 1.3 s)
function BG23_knock(g,dt){if(g.kx||g.kz){const kx=g.kx*dt,kz=g.kz*dt;if(g.kind==='thief'){g.ox=(g.ox||0)+kx;g.oz=(g.oz||0)+kz}else if(!roamHit(g.x+kx,g.z+kz,2.2,g.y+1)){g.x+=kx;g.z+=kz}const f=Math.exp(-5*dt);g.kx*=f;g.kz*=f;if(Math.abs(g.kx)+Math.abs(g.kz)<.3)g.kx=g.kz=0}
 if(g.ox||g.oz){const f=Math.exp(-2.5*dt);g.ox*=f;g.oz*=f;if(Math.abs(g.ox)+Math.abs(g.oz)<.05)g.ox=g.oz=0}}
function BG23_rp(g,P){if(!P||!P.length)return[[g.x,g.z]];if(P.length>1&&Math.hypot(P[1][0]-g.x,P[1][1]-g.z)<Math.hypot(P[1][0]-P[0][0],P[1][1]-P[0][1]))P=P.slice(1);return[[g.x,g.z],...P]}
function M1_goonStep(dt){const ch=RO.ch;let rp=0;M1.iv=Math.max(0,(M1.iv||0)-dt);M1.tokT=(M1.tokT||0)-dt;{let a=M1.goons.find(g=>g.id===M1.tok&&!g.dead&&!g.leave&&g.kind!=='thief');if(!a||M1.tokT<=0){const c=M1.goons.filter(g=>!g.dead&&!g.leave&&g.kind!=='thief'&&g.st!=='flee'&&g!==a).sort((p,q)=>Math.hypot(p.x-RO.x,p.z-RO.z)-Math.hypot(q.x-RO.x,q.z-RO.z));a=c[0]||a;M1.tok=a?a.id:0;M1.tokT=6}}for(const g of M1.goons){if(g.dead){g.dt+=dt;g.vy-=30*dt;g.m.position.y+=g.vy*dt;g.m.rotation.z+=g.spin*dt;g.m.rotation.x+=g.spin*.5*dt;if(g.m.position.y<groundY(g.x,g.z)-1)g.vy=Math.abs(g.vy)*.3;if(g.dt>1.4&&g.m.parent){g.m.parent.remove(g.m)}continue}
    g.cd-=dt;g.stall=Math.max(0,g.stall-dt);if(g.inv>0){g.inv-=dt;g.m.visible=g.inv<=0||Math.floor(g.inv*8)%2===0}g.bst=Math.max(0,g.bst-dt);const dx=RO.x-g.x,dz=RO.z-g.z,d=Math.hypot(dx,dz);let v,tx,tz;
    if(g.kind==='thief'){if(!g.C){g.C=qvCum(g.P0);g.s=0}const L=g.C[g.C.length-1];v=(d>220?0:d>120?Math.min(16,Math.max(8,Math.abs(RO.v)*.5)):Math.min(d<40?40:34,Math.max(12,Math.abs(RO.v)*(d<40?.8:.7))))*(g.bst>0?1.15:1)*(g.stall>0?.3:1)*(L-g.s<300?.55:1);g.s+=v*dt;const a=qvAt(g.P0,g.C,g.s);g.x=a.x;g.z=a.z;g.h=a.h;if(g.s>=L-2){if(g.noEsc||d<300)g.s=L-2;else g.esc=1}
      if(g.drop){g.dropT-=dt;if(g.dropT<=0&&d<220){g.dropT=3.4;M1_crate(g.x,g.z)}}}
    else{const sp=Math.abs(RO.v);if(g.kind==='lt'&&g.st!=='flee'&&g.hp<g.hp0&&g.mt<=0){g.st='flee';g.ft=4;g.mt=5}g.mt-=dt;
      if(g.leave){g.lt=(g.lt||0)+dt;if(g.lt>6||d>170){g.dead=1;g.dt=9;if(g.m.parent)g.m.parent.remove(g.m);puff(g.m.position.clone().add(V3(0,2,0)),6,new THREE.Color(.5,.5,.55),2,8,1,.5,2,3);continue}}if(g.st==='flee'){g.ft-=dt;if(g.ft<=0&&!g.leave)g.st='hunt'}const far=d>600;if(far){const b=qvNear(RO.x-Math.sin(RO.h)*230,RO.z-Math.cos(RO.h)*230,250);if(b>=0){const G=qvGraph();g.x=G.X[b];g.z=G.Z[b];g.P=null}continue}
      v=clamp(sp+(g.st==='flee'?14:7),24,60)*g.K.v*(g.stall>0?.25:1)*(g.cd>0?.55:1);if(g.st==='flee'){tx=g.x-dx/(d||1)*60;tz=g.z-dz/(d||1)*60;if(g.K.mines){g.dropT-=dt;if(g.dropT<=0){g.dropT=1.6;M1.mines.push(M1_mine(g.x,g.z,'enemy'))}}}
      const atk=g.id===M1.tok||g.K.mines;if(g.st!=='flee'&&!atk&&d<55){if(d>30){const an=Math.atan2(g.x-RO.x,g.z-RO.z)+dt*.6;tx=RO.x+Math.sin(an)*36;tz=RO.z+Math.cos(an)*36;v=Math.min(v,Math.max(18,Math.abs(RO.v)+4))}else{const an=Math.atan2(g.x-RO.x,g.z-RO.z)+1.2;tx=g.x+Math.sin(an)*10;tz=g.z+Math.cos(an)*10;v=7}}else if(g.st!=='flee'&&d<38){const lead=Math.min(.5,d/60);tx=RO.x+Math.sin(RO.vh)*RO.v*lead;tz=RO.z+Math.cos(RO.vh)*RO.v*lead}
      if(tx!=null){const ex=tx-g.x,ez=tz-g.z,ed=Math.hypot(ex,ez)||1,st=Math.min(ed,v*dt),nx=g.x+ex/ed*st,nz=g.z+ez/ed*st;if(!roamHit(nx,nz,2.2,g.y+1)){g.x=nx;g.z=nz;g.h=Math.atan2(ex,ez)}else g.P=null}
      else{g.rt-=dt;if((g.rt<=0||!g.P)&&rp<1){rp++;g.P=BG23_rp(g,qvPath(g.x,g.z,RO.x,RO.z));g.C=qvCum(g.P);g.s=0;g.rt=1.3}if(g.P){g.s+=v*dt;const a=qvAt(g.P,g.C,g.s);g.x=a.x;g.z=a.z;g.h=a.h}}}
    BG23_knock(g,dt);g.y=groundAt(g.x,g.z,g.y+4);g.m.position.set(g.x+(g.ox||0),g.y,g.z+(g.oz||0));g.m.rotation.y=g.h;
    // contact
    g.hcd=Math.max(0,(g.hcd||0)-dt);if(d<(g.kind==='thief'?8.5:6.6)&&!g.leave&&Math.abs(RO.y-g.y)<5&&!RO.wk){const pv=d<2.5?Math.abs(RO.v):RO.v*(Math.sin(RO.vh)*(-dx)+Math.cos(RO.vh)*(-dz))/(d||1),hard=RO.boosting||pv>30;if(M1.dbg)M1.dbg.push([+pv.toFixed(1),+d.toFixed(1),g.kind,+RO.v.toFixed(1)]);
      if((pv>(g.kind==='thief'?8:13)||(RO.boosting&&pv>5))&&g.hcd<=0){g.hcd=.7;g.cd=Math.max(g.cd,g.kind==='thief'?1.6:1.5);if(g.inv>0){M1_snd('bump');RO.v*=.7;continue}if(g.K.shield&&!hard){hitPop('🛡 SHIELD · BOOST-RAM IT!','#ff9a3c');M1_snd('bump');RO.v*=.6;g.kx=-dx/(d||1)*30;g.kz=-dz/(d||1)*30;continue}M1_hitGoon(g,hard&&g.kind!=='thief'?2:1,hard?'💥 HARD RAM':'💥 RAM');g.kx=-dx/(d||1)*50;g.kz=-dz/(d||1)*50;RO.v*=.82;g.P=null}
      else if(g.cd<=0&&pv<=13&&g.kind!=='thief'&&!(M1.ghost>0)&&!(M1.iv>0)&&ch&&ch.m.m1){M1.iv=1.5;M1.hp=Math.max(0,M1.hp-g.K.dmg);M1.hpT=0;M1.log.ram++;g.cd=3.5;M1.tokT=Math.min(M1.tokT,.8);RO.v*=.55;const sx=dx/(d||1),sz=dz/(d||1);RO.x+=sx*2.2;RO.z+=sz*2.2;g.kx=-sx*70;g.kz=-sz*70;g.P=null;shake=.4;M1_snd('hit');buzz(30);hitPop(`💢 RAMMED! ❤ ${Math.round(M1.hp)}`,'#ff4d6d');M1_loseCrate()}}}
  if(M1.goons.length>24)M1.goons=M1.goons.filter(g=>!g.dead||g.m.parent)}
function M1_loseCrate(){const ch=RO.ch;if(!ch||!ch.crates||!(ch.n>0))return;ch.bh=(ch.bh||0)+1;if(ch.bh%2){feed('🛢 BARRELS SHAKEN · next hit loses one',0,'#ffb000');return}ch.n--;const c=ch.crates.children[ch.crates.children.length-1];if(c){debris(c.getWorldPosition(V3()),V3(0,6,0),10,[new THREE.Color('#9a6a3a'),new THREE.Color('#ffd84a')],.8,RO.y);ch.crates.remove(c)}feed('🛢 BARREL LOST · '+ch.n+' left',0,'#ff5a2d')}
function M1_crate(x,z){const o=new THREE.Mesh(QV.cg||(QV.cg=new THREE.BoxGeometry(1.6,1,1.6)),QV.cm||(QV.cm=new THREE.MeshStandardMaterial({color:0x9a6a3a,roughness:.7})));o.scale.setScalar(2.2);o.position.set(x,groundY(x,z)+1.1,z);RO.grp.add(o);M1_obj({t:'crate',x,z,m:o,life:25})}
function M1_clear(){for(const g of M1.goons)if(g.m.parent)g.m.parent.remove(g.m);M1.goons=[];for(const o of M1.act)if(o.m&&o.m.parent)o.m.parent.remove(o.m);M1.act=[];for(const r of M1.ramps){const i=RO.ramps.indexOf(r.r);if(i>=0)RO.ramps.splice(i,1);for(const m of r.ms)if(m.parent)m.parent.remove(m)}M1.ramps=[];
  if(M1.rv){if(M1.rv.m.parent)M1.rv.m.parent.remove(M1.rv.m);M1.rv=null}M1.mines=M1.mines.filter(q=>{if(q.mis){if(q.m.parent)q.m.parent.remove(q.m);return false}return true});M1.boxes=M1.boxes.filter(b=>{if(b.mis){if(b.m.parent)b.m.parent.remove(b.m);return false}return true});M1.tdc=null;const h=$('#m1Hp');if(h)h.hidden=true}
function M1_ramp(x,z,h,len,hgt,w,y0){const n0=RO.grp.children.length;addRamp(x,z,h,len,hgt,w,0xff2d55,y0);const r=RO.ramps[RO.ramps.length-1],ms=RO.grp.children.slice(n0);M1.ramps.push({r,ms});return r}
// ---------- free-roam items: boxes on the road graph, Missile (homing), Mines, Ghost; F/E key or the touch ITEM button
let M1_BOXG=null,M1_BOXM=null;function M1_box(x,z,mis){if(!M1_BOXG){const[c,g]=cv(64,64);const gr=g.createLinearGradient(0,0,64,64);gr.addColorStop(0,'#ff2d95');gr.addColorStop(.5,'#ffd400');gr.addColorStop(1,'#4ceaff');g.fillStyle=gr;g.fillRect(0,0,64,64);g.fillStyle='#141413';g.font='900 46px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText('?',32,35);const t=tex(c);KEEP_TEX.add(t);M1_BOXG=new THREE.BoxGeometry(3,3,3);M1_BOXM=new THREE.MeshStandardMaterial({map:t,emissive:new THREE.Color('#ffffff'),emissiveMap:t,emissiveIntensity:.55,roughness:.4})}
  const m=new THREE.Mesh(M1_BOXG,M1_BOXM);const y=groundY(x,z)+2.6;m.position.set(x,y,z);RO.grp.add(m);const b={x,z,y,m,t:0,mis:!!mis};M1.boxes.push(b);return b}
function M1_boxesCity(){if(M1.boxCity||CID!=='fra')return;const G=qvGraph();if(!G)return;M1.boxCity=1;const rnd=mul(4242),P=[];for(let t=0;t<900&&P.length<44;t++){const i=G.list[Math.floor(rnd()*G.list.length)],x=G.X[i],z=G.Z[i];if(Math.abs(x)>2600||z<-1700||z>2400||inRiver(x,z,-3)||roamHit(x,z,3))continue;if(P.some(p=>Math.hypot(p[0]-x,p[1]-z)<230))continue;P.push([x,z])}for(const[x,z]of P)M1_box(x,z,0)}
function M1_itemStep(dt){const can=M1_wpn();for(const b of M1.boxes){const d=Math.hypot(b.x-RO.x,b.z-RO.z);if(b.t>0){b.t-=dt;b.m.visible=false;continue}b.m.visible=(b.mis||can)&&d<500;if(!b.m.visible)continue;b.m.rotation.y+=dt*1.6;b.m.rotation.x=Math.sin(T*1.3+b.x)*.3;b.m.position.y=b.y+Math.sin(T*2.2+b.z)*.4;
    if(d<6.8&&Math.abs(RO.y-b.y)<6&&!M1.inv&&!(M1.spin>0)){b.t=18;M1.spin=.7;M1.log.pick++;M1_snd('pick');burst(SPARK,V3(b.x,b.y,b.z),24,16,.6,new THREE.Color(2.4,1.8,.6));const W=RO.ch&&RO.ch.m.m1?[['missile',5],['mines',3],['ghost',2]]:[['missile',4],['mines',3],['ghost',3]];let r=Math.random()*W.reduce((a,w)=>a+w[1],0),k='missile';for(const w of W){r-=w[1];if(r<=0){k=w[0];break}}M1.spinK=k}}
  if(M1.spin>0){M1.spin-=dt;if(M1.spin<=0){M1.inv=M1.spinK;feed(`🎁 ${M1_IN[M1.inv]} · press ${TOUCH.on?'ITEM':'F'}`,0,'#ff2d95');M1_tw()}}
  if(M1.ghost>0){M1.ghost-=dt;RO.inv=Math.max(RO.inv||0,.05);if(pl)pl.mesh.visible=Math.floor(M1.ghost*12)%3!==0;if(M1.ghost<=0&&pl){pl.mesh.visible=true;feed('👻 GHOST OVER',0,'#9fb0c0')}}
  for(const p of M1.proj){if(p.dead)continue;p.t+=dt;let tg=p.tg;if(tg&&(tg.dead||tg.esc))tg=p.tg=null;if(!tg){let bd=260;for(const g of M1.goons){if(g.dead)continue;const ax=g.x-p.x,az=g.z-p.z,dd=Math.hypot(ax,az);if(dd<bd&&Math.abs(angDiff(Math.atan2(ax,az),p.h))<1.1){bd=dd;tg=p.tg=g}}if(!tg&&M1.rv&&Math.hypot(M1.rv.x-p.x,M1.rv.z-p.z)<260)tg=p.tg=M1.rv}
    if(tg){const w=Math.atan2(tg.x-p.x,tg.z-p.z);p.h+=clamp(angDiff(w,p.h),-3.2*dt,3.2*dt)}p.x+=Math.sin(p.h)*p.v*dt;p.z+=Math.cos(p.h)*p.v*dt;const gy=groundY(p.x,p.z)+1.6;p.m.position.set(p.x,Math.max(gy,p.m.position.y+(gy-p.m.position.y)*Math.min(1,dt*6)),p.z);p.m.rotation.y=p.h;if(Math.random()<.8)emit(SPARK,p.m.position.clone(),V3(rr(-2,2),rr(0,2),rr(-2,2)),.3,new THREE.Color(2.4,1.2,.4));
    let hit=null;for(const g of M1.goons)if(!g.dead&&Math.hypot(g.x-p.x,g.z-p.z)<5){hit=g;break}if(!hit&&M1.rv&&Math.hypot(M1.rv.x-p.x,M1.rv.z-p.z)<6)hit=M1.rv;
    if(hit||p.t>3.5||roamHit(p.x,p.z,1,gy)){p.dead=1;if(p.m.parent)p.m.parent.remove(p.m);const at=V3(p.x,gy+1,p.z);burst(FIRE,at,30,24,.7,new THREE.Color(2.2,1,.3));M1_snd('boom');if(hit&&hit===M1.rv){M1.rv.stall=2.4;hitPop('🚀 ROSSI HIT!','#5dffb0');M1.log.hit++}else if(hit){M1.log.hit++;M1_hitGoon(hit,2,'🚀 MISSILE')}}}
  M1.proj=M1.proj.filter(p=>!p.dead);
  for(const q of M1.mines){if(q.dead)continue;q.t-=dt;q.m.rotation.y+=dt*2;if(q.t<=0){q.dead=1;if(q.m.parent)q.m.parent.remove(q.m);continue}q.arm-=dt;if(q.arm>0)continue;let hit=null;
    if(q.own==='enemy'){if(Math.hypot(RO.x-q.x,RO.z-q.z)<4.2&&!(M1.ghost>0))hit='pl'}else{for(const g of M1.goons)if(!g.dead&&Math.hypot(g.x-q.x,g.z-q.z)<4.8){hit=g;break}if(!hit&&M1.rv&&Math.hypot(M1.rv.x-q.x,M1.rv.z-q.z)<5)hit=M1.rv}
    if(hit){q.dead=1;if(q.m.parent)q.m.parent.remove(q.m);burst(FIRE,V3(q.x,groundY(q.x,q.z)+1.5,q.z),34,24,.8,new THREE.Color(2.2,1,.3));M1_snd('boom');shake=Math.max(shake,.4);if(hit==='pl'){RO.v*=.4;if(RO.ch&&RO.ch.m.m1){M1.hp=Math.max(0,M1.hp-10);M1.hpT=0}hitPop('💥 MINE!','#ff4d6d')}else if(hit===M1.rv){M1.rv.stall=2.4;hitPop('💣 ROSSI SPINS OUT!','#5dffb0');M1.log.hit++}else{M1.log.hit++;M1_hitGoon(hit,2,'💣 MINE')}}}
  M1.mines=M1.mines.filter(q=>!q.dead)}
const M1_IN={missile:'MISSILE',mines:'MINES',ghost:'GHOST'};
function M1_mine(x,z,own,mis){const m=new THREE.Group(),b=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.4,.7,10),new THREE.MeshStandardMaterial({color:0x222228,roughness:.5}));m.add(b);const l=new THREE.Mesh(new THREE.SphereGeometry(.35,8,6),neonMat(own==='enemy'?'#ff2d55':'#5dffb0',3));l.position.y=.6;m.add(l);m.position.set(x,groundY(x,z)+.4,z);RO.grp.add(m);return{x,z,m,t:40,arm:.5,own,mis:mis!=null?mis:!!(RO.ch&&RO.ch.m.m1)}}
function M1_fire(){if(state!=='roam'||!RO.on||M1.cs||RO.card||RO.mapOpen)return false;const k=M1.inv;if(!k){if(M1_wpn())hitPop('NO ITEM · DRIVE THROUGH A ? BOX','#9fb0c0');return false}M1.inv=null;M1.log.fire++;M1.lastFire=k;
  if(k==='missile'){const m=new THREE.Mesh(new THREE.ConeGeometry(.5,2.4,8).rotateX(Math.PI/2),neonMat('#ff9a3c',2.6));const x=RO.x+Math.sin(RO.h)*5,z=RO.z+Math.cos(RO.h)*5;m.position.set(x,RO.y+1.6,z);RO.grp.add(m);M1.proj.push({x,z,h:RO.h,v:Math.max(120,Math.abs(RO.v)+70),t:0,m,tg:null});M1_snd('missile');feed('🚀 MISSILE',0,'#ff9a3c')}
  else if(k==='mines'){for(let i=0;i<3;i++){const d=7+i*5,x=RO.x-Math.sin(RO.h)*d+Math.cos(RO.h)*(i-1)*3,z=RO.z-Math.cos(RO.h)*d-Math.sin(RO.h)*(i-1)*3;M1.mines.push(M1_mine(x,z,'pl'))}M1_snd('mine');feed('💣 MINES DROPPED',0,'#5dffb0')}
  else if(k==='ghost'){M1.ghost=6;M1_snd('shield');feed('👻 GHOST · 6 s · goons pass through you',0,'#c46bff')}
  M1_tw();return true}
addEventListener('keyup',e=>{if(state==='roam'&&M1.cs&&e.code==='Escape'){e.preventDefault();M1.skips++;M1_csEnd();if(!$('#settings').hidden)closeSettings();if(RO.pOpen)roamPauseClose()}},true);
addEventListener('keydown',e=>{if(state!=='roam'||e.repeat)return;if(M1.cs){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();M1.skips++;M1_csEnd()}else if(e.code==='Enter'||e.code==='Space'){e.preventDefault();e.stopImmediatePropagation();M1.taps++;M1_csNext()}return}if(e.code==='KeyF'||e.code==='KeyE'){if(!$('#settings').hidden||RO.jOpen)return;e.preventDefault();M1_fire()}else if(e.code==='KeyN'&&!RO.ch&&!RO.card){M1_nextGo()}},true);
// ---------- duel rival (point-to-point through the city, rubber band, items hit him)
function M1_rivalStep(ch,dt){const R2=M1.rv;if(!R2||R2.done)return;R2.stall=Math.max(0,(R2.stall||0)-dt);const P=R2.P,C=R2.C,L=C[C.length-1];let bi=R2.pi||0,bd=1e18;for(let i=Math.max(0,bi-3);i<Math.min(P.length,bi+40);i++){const d=(P[i][0]-RO.x)**2+(P[i][1]-RO.z)**2;if(d<bd){bd=d;bi=i}}R2.pi=bi;const ps=C[bi];R2.gap=R2.s-ps;
  let v=R2.base*(R2.gap>140?.8:R2.gap<-140?1.12:1);if(R2.s>L*.86)v=R2.base;if(R2.stall>0)v*=.25;R2.bt=(R2.bt||9)-dt;if(R2.bt<=0){R2.bt=14+Math.random()*8;R2.boost=1.6}if(R2.boost>0){R2.boost-=dt;v*=1.35}R2.s+=v*dt;const a=qvAt(P,C,R2.s);R2.x=a.x;R2.z=a.z;R2.m.position.set(a.x,groundAt(a.x,a.z,(R2.m.position.y||0)+4),a.z);R2.m.rotation.y=a.h;
  R2.lt=(R2.lt||0)-dt;if(R2.lt<=0&&Math.random()<.02){R2.lt=22;M1_radio('ROSSI',R2.gap>0?['Ciao, rookie! See you at the Hauptwache!','Is that an Ebbelwoi engine?','Too slow, too slow!'][Math.floor(Math.random()*3)]:['Hey! Nobody passes Luca Rossi!','Fortuna, nothing more!'][Math.floor(Math.random()*2)])}
  if(R2.s>=L-3){R2.done=1;qvFail(ch,'LUCA ROSSI WON THE DUEL')}}
// ---------- authored missions (stage lists built from landmark anchors at layout time)
const M1_LM={drop:[2060,110],hildeA:[1650,40],hildeB:[1080,-220],hildeC:[470,-345],gooA:[150,-940],gooB:[-520,-820],romer:[75,-5],garage:[-444,455],market:[-330,-475],hide1:[160,-1020],hide2:[-1120,-430],hide3:[-760,-1420],henn:[-828,-1481],tollN:[-400,-115],romerW:[110,30],zeil:[-120,430],hunt:[160,-640],hauptw:[200,354]};
const M1_L=k=>M1_P(M1_LM[k][0],M1_LM[k][1]);
function M1_bridge(id){return ALL_DECKS.find(b=>b.id===id)}
const M1_DEF={
 hotdrop:{name:'Hot Drop',npc:'Oma Hilde',who:'HILDE',em:'🪂',col:'#ff9a3c',g:[270,330,420],story:1,
  hi:'Late for your own job interview, rookie! Cargo flight 7 drops you over the Messe.',win:'Keys back! Now come to the garage, rookie.',lose:'Kaiser’s boys are tougher than they look. Again!',
  d:'The opening: drop over the Messe, follow Hilde, meet Vex Kaiser, wreck his goons and drift home.',
  ph:['Hot Drop','Kaiser’s Goons','Tail Kaiser','Römer Brawl','Drift Home'],
  build(c){const D=M1_L('drop'),A=M1_L('hildeA'),B=M1_L('hildeB'),C=M1_L('hildeC'),R=M1_L('romer'),Gr=M1_L('garage');
   c.st.push({t:'follow',ph:1,cp:1,pts:[D,A,B,C],txt:'Follow Hilde’s tow truck to the river',ic:'🚚',T:200,scene:'open',x2:20},
    {t:'thieves',ph:2,cp:1,txt:'Kaiser’s goons have Hilde’s keys · ram them!',ic:'🔑',T:200,scene:'kaiser',list:[{from:C,to:M1_L('gooA'),rams:3,drop:0},{from:{x:C.x+20,z:C.z-10},to:M1_L('gooB'),rams:3,drop:1}],hunter:1,x2:70},
    {t:'tail',ph:3,cp:1,via:[M1_P(-150,-560),M1_P(-700,-560),M1_P(-1050,-420),M1_P(-404,-345),M1_P(-300,40)],to:R,txt:'Tail Kaiser over the river · stay within 180 m',ic:'👑',T:170,max:180,x2:40},
    {t:'survive',ph:4,cp:1,dur:72,max:3,at:'romer',txt:'Römer brawl: hold out until Kaiser shows himself',ic:'💥',T:150,x2:50},
    {t:'driftzone',ph:5,cp:1,win:24,p:420,txt:'Drift home: 420 drift points in 24 s (hold DRIFT)',ic:'🌀',T:40,x2:20},
    {t:'go',ph:5,ring:1,x:M1_P(-150,-185).x,z:M1_P(-150,-185).z,r:13,txt:'Down the Mainkai: gate 1/3',ic:'⭕',T:60},
    {t:'go',ph:5,ring:1,x:M1_P(-470,-190).x,z:M1_P(-470,-190).z,r:13,txt:'Mainkai gate 2/3',ic:'⭕',T:60},
    {t:'go',ph:5,ring:1,x:M1_P(-780,-225).x,z:M1_P(-780,-225).z,r:13,txt:'Mainkai gate 3/3',ic:'⭕',T:60},
    {t:'go',ph:5,x:Gr.x,z:Gr.z,stop:1,txt:'Park at Hilde’s garage, Konstablerwache',ic:'🔧',T:120})}},
 heist:{name:'Ebbelwoi Heist',npc:'Wirt Klaus',who:'KLAUS',em:'🍎',col:'#36d17a',g:[300,370,450],story:1,
  hi:'Help! Kaiser’s goons stole my cider truck! The whole Ebbelwoi for the festival!',win:'My Ebbelwoi! Free Äppler for you, forever. Well... for tonight.',lose:'Oh no! The barrels! Try again, please!',
  d:'Kaiser’s goons stole the cider truck. It splits into three vans, the street turns slick, then bring the barrels home under fire.',
  ph:['Cider Truck','Split!','Slick Street','Barrels Home','Defend the Market'],
  build(c){const M=c.O,H=M1_L('henn');
   const A=M1_P(160,-660),B=M1_P(700,-300),B2=M1_P(330,-380);c.st.push({t:'chase',ph:1,cp:1,x:H.x,z:H.z,rams:4,txt:'Ram the cider truck 4× before it reaches the Henninger Turm',ic:'🚚',T:150,scene:'heist',x2:40},
    {t:'thieves',ph:2,cp:1,split:1,txt:'It split! Ram all 3 vans (3× each)',ic:'🚐',T:200,list:[{to:M1_L('hide1'),rams:3},{to:M1_L('hide2'),rams:3,drop:1},{to:M1_L('hide3'),rams:3}],x2:70},
    {t:'driftzone',ph:3,cp:1,win:32,p:600,spill:1,txt:'Cider everywhere! Drift 600 points in 32 s on the slick street',ic:'🍏',T:40,x2:30},
    {t:'go',ph:4,cp:1,ring:1,x:A.x,z:A.z,r:14,carry:1,load:3,hunt:2,txt:'Barrels loaded! Detour via Schweizer Platz · goons hunt you',ic:'🛢',T:120,x2:20},
    {t:'go',ph:4,ring:1,x:B.x,z:B.z,r:14,carry:1,txt:'West along the Museumsufer · keep the barrels',ic:'🛢',T:100},{t:'go',ph:4,ring:1,x:B2.x,z:B2.z,r:14,carry:1,txt:'Back east under the bridges',ic:'🛢',T:100},
    {t:'go',ph:4,x:M.x,z:M.z,stop:1,carry:1,heavy:1,txt:'Bring the barrels to Klaus’ market',ic:'🍎',T:120,x2:10},
    {t:'survive',ph:5,cp:1,dur:80,max:3,txt:'Defend the market: Kaiser wants his cider back',ic:'🛡',T:120,x2:50})}},
 toll:{name:'Bridge Toll',npc:'Oma Hilde',who:'HILDE',em:'🌉',col:'#ff9a3c',g:[290,360,440],story:1,
  hi:'The Schattenwerk barricaded the Alte Brücke and charges a toll. My bridge!',win:'The Alte Brücke is free again. Luca Rossi heard about you...',lose:'Brecher hits hard. Use your boost on him!',
  d:'Smash the toll booths on the Alte Brücke, survive the rammer waves, beat Brecher and jump the rising bridge.',
  ph:['Toll Booths','Rammer Wave','Brecher','Drawbridge','Kaiser’s Revenge'],
  build(c){const b=M1_bridge('alte');let bo=[];if(b){for(const a of[-46,-16,14,44]){const[x,z]=deckPt(b,a);bo.push([x,z,Math.atan2(b.ux,b.uz)])}}else bo=[[c.O.x,c.O.z-40,0],[c.O.x,c.O.z-80,0],[c.O.x,c.O.z-120,0],[c.O.x,c.O.z-160,0]];
   const s0=b?deckPt(b,-b.half-70):[c.O.x,c.O.z-300],S0=M1_P(s0[0],s0[1],200),R=M1_L('romer');
   const b2=M1_bridge('bubis');if(b2)for(const a of[-30,30]){const[x,z]=deckPt(b2,a);bo.push([x,z,Math.atan2(b2.ux,b2.uz)])}
   c.st.push({t:'booths',ph:1,cp:1,items:bo,guards:2,txt:`Smash the ${bo.length} toll booths at 80+ km/h`,ic:'🚧',T:150,scene:'toll',x:bo[0][0],z:bo[0][1],x2:50},
    {t:'survive',ph:2,cp:1,dur:75,max:3,txt:'Rammer wave! Survive 75 s, wreck what you can',ic:'💥',T:120,x2:50},
    {t:'survive',ph:3,cp:1,dur:70,max:4,boss:'heavy',txt:'Second wave, then wreck Brecher (BOOST-ram his truck)',ic:'🔨',T:170,x2:70},
    {t:'jumpR',ph:4,cp:1,steg:1,bridge:'alte',ax:S0.x,az:S0.z,d:30,txt:'Kaiser raises the Eiserner Steg! Jump it (30 m+)',ic:'🛫',T:80,x2:20},
    {t:'go',ph:5,cp:1,ring:1,x:M1_P(-330,300).x,z:M1_P(-330,300).z,r:14,hunt:3,txt:'Kaiser’s revenge! Escape to the Römer · via Konstablerwache',ic:'🚨',T:90,x2:10},{t:'go',ph:5,ring:1,x:M1_P(-440,520).x,z:M1_P(-440,520).z,r:14,txt:'Through the Konstablerwache',ic:'🚨',T:80},{t:'go',ph:5,ring:1,x:M1_P(185,675).x,z:M1_P(185,675).z,r:14,txt:'Past the Eschenheimer Turm',ic:'🚨',T:80},
    {t:'go',ph:5,ring:1,x:M1_P(200,354).x,z:M1_P(200,354).z,r:14,txt:'Through the Hauptwache',ic:'🚨',T:80},
    {t:'go',ph:5,x:R.x,z:R.z,stop:1,txt:'Meet Hilde at the Römer',ic:'🏛',T:90})}},
 duel:{name:'Street Duel: Luca Rossi',npc:'Luca Rossi',who:'ROSSI',em:'🏎',col:'#ff2d55',g:[250,300,360],story:1,items:1,
  hi:'Show me what you have, rookie! Römer to the Hauptwache, the long way. Items on.',win:'Bravissimo, rookie. Take my flag... and the Fulmine Rosso.',lose:'Ha! Come back when your car is ready.',
  d:'Point-to-point street race against Luca Rossi through the whole city with item boxes on. Kaiser’s crew crashes the race halfway.',
  ph:['Römer → Alte Oper','Crash the Party','Final Sprint'],
  build(c){const W=[[75,-5],[200,354],[-300,470],[-950,320],[-600,700],[185,675],[790,700],[1300,1100],[1400,420],[2100,200],[2350,-250],[1392,-380],[383,-400],[160,-700],[-500,-800],[-150,-330],[-404,-150],[75,40],[200,354]].map(p=>M1_P(p[0],p[1]));W[0]={x:c.O.x,z:c.O.z};const R=M1_path(W),L=R.L;c.L.rp=R;const n=clamp(Math.round(L/380),12,30);let lj=-1;
   for(let k=1;k<=n;k++){const a=qvSnap(R.P,R.C,L*k/n);if(a.j===lj&&k<n)continue;lj=a.j;const f=k/n,ph=f<=.36?1:f<=.72?2:3;c.st.push({t:'go',ring:1,x:a.x,z:a.z,h:a.h,r:12,ph,cp:0,txt:k<n?`Gate ${k}/${n} · beat Rossi to the Hauptwache`:'Finish at the Hauptwache!',ic:k<n?'🏁':'🏆',T:0,q:k>1&&k<n})}
   let last=0;for(const S of c.st){if(S.ph!==last){S.cp=1;last=S.ph}}const s2=c.st.find(S=>S.ph===2);if(s2)s2.hunt=3;const s3=c.st.find(S=>S.ph===3);if(s3)s3.hunt2=2}},
 hunt:{name:'Takedown Hunt',npc:'BRIX',who:'BRIX',em:'💥',col:'#ff2d55',g:[110,140,180],act:1,
  hi:'Bzzt! Schattenwerk cars are taxing Sachsenhausen. Wreck them all. Each takedown buys +10 s.',win:'Bzzt! Sachsenhausen is quiet again.',lose:'Bzzt... recalculating. Ram harder!',
  d:'Road Rage: two waves of goon cars, a shield car that only a boost-ram can hurt, then the lieutenant who drops mines.',
  ph:['Wave 1','Wave 2 + Shield','Lieutenant'],
  build(c){c.st.push({t:'goons',ph:1,cp:1,wave:[['rammer',4]],need:4,txt:'Wave 1: take down 4 goons',ic:'💥',T:70,bonus:10,x2:40},{t:'goons',ph:2,cp:1,wave:[['rammer',3],['shield',1]],need:4,txt:'Wave 2: 3 goons + a shield car (BOOST-ram it)',ic:'🛡',T:70,bonus:10,x2:45},{t:'goons',ph:3,cp:1,wave:[['lt',1]],need:1,txt:'Lieutenant: 4 HP, flees and drops mines',ic:'😈',T:60,bonus:0,x2:30})}},
 rampage:{name:'Smash Rampage',npc:'BRIX',who:'BRIX',em:'🧱',col:'#ff9a3c',g:[130,170,220],act:1,
  hi:'Bzzt! Kaiser built a brick tower on the Zeil. Smash everything, bowl the giant brick into the pins, then flatten the tower.',win:'Bzzt! Nothing left standing. Perfect.',lose:'Bzzt... the bricks won this time.',
  d:'Chain Rampage: a 15-smash chain, the giant brick bowled into 10 brick pins, then a regrowing tower you must hit 3× at 150+ km/h.',
  ph:['Chain','Bowling','Brick Tower'],
  build(c){const O=c.O;let B=M1_P(O.x+60,O.z+20,200),Gl=M1_P(O.x+260,O.z-40,250);{let best=null;for(const L of[230,190,150])for(let k=0;k<24&&!best;k++){const a=k/24*6.283,sx=Math.sin(a),sz=Math.cos(a);let ok=true;for(let d=15;d<=L+20;d+=5){const x=O.x+sx*d,z=O.z+sz*d;if(roamHit(x,z,6)||inRiver(x,z,-4)){ok=false;break}}if(ok)best={B:{x:O.x+sx*30,z:O.z+sz*30},Gl:{x:O.x+sx*L,z:O.z+sz*L}}}if(best){B=best.B;Gl=best.Gl}}const Tw=M1_P(O.x-200,O.z+60,250);c.st.push({t:'chain',ph:1,cp:1,need:15,txt:'Smash 15 things in one CHAIN',ic:'💥',T:60,x2:30},{t:'push',ph:2,cp:1,bx:B.x,bz:B.z,x:Gl.x,z:Gl.z,r:15,pins:1,txt:'Bowl the giant brick into the 10 pins',ic:'🎳',T:80,x2:40,d0:Math.hypot(Gl.x-B.x,Gl.z-B.z)},{t:'tower',ph:3,cp:1,x:Tw.x,z:Tw.z,hp:3,txt:'Brick tower: hit it 3× at 150+ km/h',ic:'🗼',T:70,x2:30})}}};
QV_GEN.m1=c=>{const D=M1_DEF[c.e.mid];D.build(c);c.L.g=D.g.slice();c.L.ph=D.ph.length};
QV_D.m1='An authored story mission.';
const M1_STORY=['hotdrop','heist','toll','duel'];
// ---------- scenes (≤4 lines each)
function M1_hilde(){if(!M1.hilde){M1.hilde=M1_car('truck','#ff9a3c',3.1,'#ffffff')}return M1.hilde}
const M1_SC={
 open:(ch,S)=>{const D=M1_L('drop');let plane=null,chute=null;M1_scene({cam:{mode:'orbit',a:()=>({x:D.x,z:D.z}),r:70,h:34,a0:2.2},dur:4.4,lines:[['HILDE','Late for your own job interview, rookie! That’s cargo flight 7 out of Fraport, and <b>you</b> are the cargo.'],['HILDE','Pop the chute over the Messe, then follow my tow truck to the river. Gas, <b>BOOST</b>, and don’t scratch my paint.']],
   start(){plane=new THREE.Group();const M=new THREE.MeshStandardMaterial({color:0xdfe4ea,roughness:.5});box(plane,M,6,6,44,0,0,0);box(plane,M,46,1,9,0,0,2);box(plane,M,14,1,5,0,4,-19);plane.position.set(D.x+260,120,D.z);RO.grp.add(plane);chute=new THREE.Mesh(new THREE.SphereGeometry(6,12,6,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0xff2d55,roughness:.6}));RO.grp.add(chute);M1_warp(D.x,D.z,S.h0||0);pl.mesh.position.y=groundY(D.x,D.z)+80},
   tick(dt,t){if(plane){plane.position.x-=dt*90;plane.position.y=120}const y0=groundY(RO.x,RO.z),y=Math.max(y0,y0+80-t*17);pl.mesh.position.set(RO.x,y,RO.z);chute.position.set(RO.x,y+9,RO.z);chute.visible=y>y0+1},
   end(){if(plane&&plane.parent)plane.parent.remove(plane);if(chute&&chute.parent)chute.parent.remove(chute);RO.y=groundAt(RO.x,RO.z,99);RO.v=12;M1_radio('HILDE','Hold <b>GAS</b> and follow my orange truck. Hold <b>BOOST</b> on the straights!')}})},
 kaiser:(ch,S)=>{const H=M1_hilde(),K=M1_car('sedan-sports','#101014',3,'#ffd12c');M1_obj({m:K});M1.kaiser=K;const hx=H.position.x,hz=H.position.z,hh=H.rotation.y;let k0=null;M1_scene({cam:{a:()=>({x:K.position.x,z:K.position.z}),b:()=>({x:H.position.x,z:H.position.z})},dur:4.6,lines:[['KAISER','Cute tow truck, Oma. Cute garage too. <b>Mine now.</b>'],['HILDE','Vex Kaiser! Rookie, his goons just grabbed my garage keys. <b>Get them back!</b>'],['KAISER','Boys, teach the rookie some manners. Schattenwerk collects at midnight.']],
   start(){k0={x:hx-Math.sin(hh)*90,z:hz-Math.cos(hh)*90};M1_put(K,k0.x,k0.z,hh)},
   tick(dt,t){const u=Math.min(1,t/1.4),x=k0.x+(hx-k0.x)*u,z=k0.z+(hz-k0.z)*u;M1_put(K,x,z,hh);if(u>=1&&!M1.kHit){M1.kHit=1;M1_snd('crash');shake=.8;burst(SPARK,V3(hx,groundY(hx,hz)+2,hz),50,30,.8,new THREE.Color(2.4,1.6,.5))}if(M1.kHit){H.rotation.y=hh+Math.min(2.4,(t-1.4)*3);const o=Math.min(14,(t-1.4)*12);M1_put(H,hx+Math.cos(hh)*o,hz-Math.sin(hh)*o)}},
   end(){M1.kHit=0;M1_radio('KAISER','Ha! Catch my boys if you can, rookie.')}})},
 heist:(ch,S)=>{M1_scene({cam:{a:()=>({x:RO.x,z:RO.z}),b:()=>({x:ch.O.x+Math.sin(RO.h)*40,z:ch.O.z+Math.cos(RO.h)*40})},lines:[['KLAUS','Help! Kaiser’s goons took my cider truck! The whole Ebbelwoi for the festival!'],['HILDE','Ram it until it gives up, rookie. Klaus, keep the glasses cold.']],end(){}})},
 toll:(ch,S)=>{const b=M1_bridge('alte'),c=b?{x:b.cx,z:b.cz}:{x:ch.O.x,z:ch.O.z-80};const T2=M1_car('truck','#2a2a31',3.4,'#ffd12c');M1_put(T2,c.x,c.z,Math.PI);M1_obj({m:T2});M1_scene({cam:{a:()=>({x:RO.x,z:RO.z}),b:()=>c},lines:[['BRECHER','Alte Brücke is a <b>toll bridge</b> now. Ten thousand studs, or you swim.'],['HILDE','Brecher, Kaiser’s lieutenant. Smash his booths, rookie. Nobody charges for my bridge!']],end(){if(T2.parent)T2.parent.remove(T2)}})}};
function M1_warp(x,z,h){BG23_cut();const c=RO.ch,s=RO.sp;RO.ch=null;RO.sp=null;const ok=roamWarp(x,z,h);RO.ch=c;RO.sp=s;if(!ok){RO.x=x;RO.z=z;RO.y=groundAt(x,z,99);if(h!=null)RO.h=RO.vh=h;RO.v=0;camSnap=true}}
// ---------- stage setup / step for the M1 stage types
const M1_STD=new Set(['go','dpts','chain','push','chase']);
// FX19: Hilde's tow truck waits 40 m up the route (S.s used to start at 0, so on the first tick it snapped back onto the player, around the chase camera)
// and parked 3.5 m to the right of the lane; it pulls back onto the route over its first 30 m
function FX19_side(S,a){const k=clamp(1-(S.s-(S.s0||0))/30,0,1);if(k<=0)return;const o=3.5*k,x=a.x-Math.cos(a.h)*o,z=a.z+Math.sin(a.h)*o;M1_put(S.m,x,z,a.h)}
function M1_setup(ch,S,i){const V=ch.v2;
  if(S.t==='follow'||S.t==='tail'){const pts=S.t==='follow'?S.pts:[{x:RO.x+Math.sin(RO.h)*70,z:RO.z+Math.cos(RO.h)*70},...(S.via||[]),S.to];const R=M1_path(pts.map(p=>M1_P(p.x,p.z)));S.R=R;S.s=0;S.cv=0;S.away=0;S.m=S.t==='follow'?M1_hilde():(M1.kaiser&&M1.kaiser.parent?M1.kaiser:M1_obj({m:M1_car('sedan-sports','#101014',3,'#ffd12c')}).m);if(S.t==='tail')M1.kaiser=S.m;const a=qvAt(R.P,R.C,S.t==='follow'?40:0);M1_put(S.m,a.x,a.z,a.h);S.vx=a.x;S.vz=a.z;if(S.t==='follow'){S.s=S.s0=40;FX19_side(S,a);const p0=qvAt(R.P,R.C,0);M1_warp(p0.x,p0.z,p0.h);S.h0=p0.h}}
  else if(S.t==='thieves'){S.th=[];const from0=S.split&&ch.vanAt?ch.vanAt:null,a0=Math.random()*6.28;S.list.forEach((q,k)=>{const f=from0||q.from||{x:RO.x,z:RO.z};let to=q.to,P=null;{const G=qvGraph();for(let tr=0;tr<14;tr++){if(tr>0||from0){const an=a0+k*2.09+(tr?(tr%2?1:-1)*Math.ceil(tr/2)*.35:0),r=[1100,900,1300,700][tr%4],i=qvNear(f.x+Math.sin(an)*r,f.z+Math.cos(an)*r,300);if(i<0)continue;to={x:G.X[i],z:G.Z[i]}}const Q=qvPath(f.x,f.z,to.x,to.z),Cq=qvCum(Q);if(Q.length>2&&Cq[Cq.length-1]>=650){P=Q;break}if(!P||Cq[Cq.length-1]>qvCum(P).slice(-1)[0])P=Q}}const Cp=qvCum(P),s0=Math.min(k*14,Cp[Cp.length-1]*.5),a0p=qvAt(P,Cp,s0);const g=M1_goon('thief',a0p.x,a0p.z,{S,hp:q.rams,P,drop:q.drop});g.C=Cp;g.s=s0;{const Cg=qvCum(P);if(Cg[Cg.length-1]<650)g.noEsc=1}S.th.push(g)});if(S.split){slowmo=Math.max(slowmo,.5);say('SPLIT!','THREE VANS · RAM THEM ALL',1.8)}}
  else if(S.t==='booths'){S.it=S.items.map(([x,z,h])=>{const g=new THREE.Group(),Mb=new THREE.MeshStandardMaterial({color:0x22232a,roughness:.6}),Mg=new THREE.MeshStandardMaterial({color:0xffd12c,roughness:.5,emissive:new THREE.Color('#5a4300')});box(g,Mb,5,5,4,0,2.5,0);box(g,Mg,5.4,.8,4.4,0,5.4,0);box(g,Mg,9,.6,.6,5,2.6,0);g.position.set(x,groundAt(x,z,40),z);g.rotation.y=h;RO.grp.add(g);M1_obj({m:g});return{x,z,m:g,done:false}});S.n=0;S.x=S.it[0].x;S.z=S.it[0].z;M1_spawn(S,'rammer',S.guards||0,{x:S.x,z:S.z},90,160)}
  else if(S.t==='goons'){S.kill=0;for(const[k,n]of S.wave){const at=S.at==='romer'?M1_L('romer'):null;M1_spawn(S,k,n,at,at?40:150,at?120:240)}say(S.wave.some(w=>w[0]==='lt')?'LIEUTENANT!':'GOONS!',S.txt.toUpperCase(),1.6)}
  else if(S.t==='survive'){S.el=0;S.kill=0;S.spT=0;S.bossOn=0;const at=S.at==='romer'?M1_L('romer'):null;M1_spawn(S,'rammer',Math.min(2,S.max),at,at?50:150,at?130:230);say('GOONS!',S.txt.toUpperCase(),1.6)}
  else if(S.t==='driftzone'){S.n=0;S.el=0}
  else if(S.t==='tower'){const g=new THREE.Group();for(let k=0;k<6;k++){const M=vmat(TEAMS[k%TEAMS.length]);box(g,M.a,7-k*.6,3,7-k*.6,0,1.5+k*3,0)}g.position.set(S.x,groundY(S.x,S.z),S.z);RO.grp.add(g);M1_obj({m:g});S.m=g;S.hp0=S.hp;S.cd=0}
  else if(S.t==='jumpR'&&S.steg&&RO.marks.some(q=>q.kind==='otg'&&q.ev.id==='lj1'&&q.rampAt)){const m=RO.marks.find(q=>q.kind==='otg'&&q.ev.id==='lj1'&&q.rampAt),r=m.rampAt;S.r=r;S.rh=r.h;let ax=m.x,az=m.z;const dx=ax-r.x,dz=az-r.z,dd=Math.hypot(dx,dz)||1;for(const L of[120,100,80]){const x=r.x+dx/dd*L,z=r.z+dz/dd*L;let ok=true;for(let k=10;k<L;k+=6)if(roamHit(r.x+dx/dd*k,r.z+dz/dd*k,2.5,deckY(M1_bridge('steg')||{half:0},0)||0)){ok=false;break}if(ok){ax=x;az=z;break}}S.x=S.ax=ax;S.z=S.az=az;S.rh=Math.atan2(r.x-ax,r.z-az);const b=M1_bridge('steg');if(b){for(const sd of[-1,1]){const[x,z]=deckPt(b,sd*30);const pn=new THREE.Mesh(new THREE.BoxGeometry(b.w,1.2,16),new THREE.MeshStandardMaterial({color:0x6b6f78,roughness:.6}));pn.position.set(x,deckY(b,sd*30)+4,z);pn.rotation.set(-sd*.35,Math.atan2(b.ux,b.uz),0,'YXZ');RO.grp.add(pn);M1_obj({m:pn})}}}
  else if(S.t==='jumpR'){const b=M1_bridge(S.bridge);let rx,rz,rh;if(b){const[x,z]=deckPt(b,-b.half-24);rx=x;rz=z;rh=Math.atan2(b.ux,b.uz)}else{rx=S.ax;rz=S.az+60;rh=0}S.r=M1_ramp(rx,rz,rh,20,5.5,12,null);S.rh=rh;S.x=rx-Math.sin(rh)*90;S.z=rz-Math.cos(rh)*90;S.ax=S.x;S.az=S.z;
    if(b){for(const sd of[-1,1]){const[x,z]=deckPt(b,-8*sd);const pn=new THREE.Mesh(new THREE.BoxGeometry(b.w-4,1.2,22),new THREE.MeshStandardMaterial({color:0x6b6f78,roughness:.6}));pn.position.set(x,deckY(b,0)+7,z);pn.rotation.set(sd*.5,Math.atan2(b.ux,b.uz),0,'YXZ');RO.grp.add(pn);M1_obj({m:pn})}}}}
function M1_stage(ch,S,dt){const V=ch.v2,kmh=Math.abs(RO.v)*3.6;
  if(S.t==='follow'||S.t==='tail'){const R=S.R,L=R.L,dP=Math.hypot(S.vx-RO.x,S.vz-RO.z);let v;if(S.t==='follow')v=dP<35?26:dP<80?22:dP<150?14:6;else v=dP<50?30:dP<120?27:dP<170?23:18;S.cv=(S.cv||0)+clamp(v-(S.cv||0),-8*dt,5*dt);S.s+=S.cv*dt;const a=qvAt(R.P,R.C,S.s);S.vx=a.x;S.vz=a.z;M1_put(S.m,a.x,a.z,a.h);if(S.t==='follow')FX19_side(S,a);
    if(S.t==='tail'){if(dP>S.max){S.away+=dt;if(S.away>8)return qvFail(ch,'KAISER GOT AWAY')}else S.away=0}
    if(S.t==='follow'){S.lt=(S.lt||0)+dt;const tips=[[8,'Hold <b>BOOST</b> (SHIFT) on the straight. Smashing bins refills it!'],[20,'Corner coming! Hold <b>DRIFT</b> (X) and steer, release for a mini-turbo.'],[34,'Traffic? <b>HOP</b> over it (SPACE). Show-off.']];for(const[t,txt]of tips)if(S.lt>=t&&(S.tip||0)<t){S.tip=t;M1_radio('HILDE',txt)}if(S.s>=L-3||S.lt>Math.max(75,L/18+15))return qvNext(ch)}else if(S.s>=L-3)return qvNext(ch);return}
  if(S.t==='thieves'){for(const g of S.th)if(!g.dead&&g.esc)return qvFail(ch,'A GETAWAY CAR ESCAPED');if(S.hunter&&!S.hOn&&S.th.some(g=>g.dead)){S.hOn=1;M1_spawn(S,'rammer',1,null,120,200);M1_radio('HILDE','Another goon behind you! He rams, you lose ❤. Ram him back!')}if(S.th.every(g=>g.dead))return qvNext(ch);return}
  if(S.t==='goons'){if((S.kill||0)>=S.need)return qvNext(ch);if(!M1.goons.some(g=>!g.dead&&g.S===S))M1_spawn(S,'rammer',S.need-(S.kill||0));return}
  if(S.t==='survive'){S.el+=dt;S.spT-=dt;const al=M1.goons.filter(g=>!g.dead&&g.S===S&&g.kind!=='heavy');if(S.el<S.dur){if(S.spT<=0&&al.length<S.max){S.spT=4;M1_spawn(S,'rammer',1,S.at==='romer'?M1_L('romer'):null,S.at==='romer'?60:150,S.at==='romer'?140:230)}return}if(!S.boss)return qvNext(ch);if(!S.bossOn){S.bossOn=1;S.bg=M1_spawn(S,S.boss,1,null,120,180)[0];S.bg.hp=S.bg.hp0=6;say('BRECHER!','BOOST-RAM HIS TRUCK · 6 HP',2);M1_radio('BRECHER','You smashed my booths? Now I smash <b>you</b>.')}if(S.bg&&S.bg.dead)return qvNext(ch);return}
  if(S.t==='driftzone'){S.el+=dt;if(RO.dDir){const tr=RO.dT>2?3:RO.dT>1.1?2:RO.dT>.5?1:0;S.n+=dt*Math.abs(RO.v)*1.2*(1+.5*tr)}if(S.n>=S.p&&!S.ok){S.ok=1;feed(`🌀 ${Math.round(S.n)} DRIFT POINTS!`,300,'#4ceaff')}if(S.el>=S.win){if(S.n>=S.p)return qvNext(ch);return qvFail(ch,'NOT ENOUGH DRIFT · '+Math.round(S.n)+'/'+S.p)}return}
  if(S.t==='booths'){for(const o of S.it){if(o.done)continue;if(Math.hypot(o.x-RO.x,o.z-RO.z)<6&&Math.abs(RO.y-o.m.position.y)<6&&(S.cd||0)<=0){if(kmh>=80){o.done=true;o.m.visible=false;S.n++;debris(V3(o.x,3,o.z),V3(Math.sin(RO.vh)*RO.v*.4,10,Math.cos(RO.vh)*RO.v*.4),26,[new THREE.Color('#22232a'),new THREE.Color('#ffd12c')],1.3,0);for(let q=0;q<6;q++)studBurst(V3(o.x,3,o.z),V3(0,0,0),30);M1_snd('crash');shake=.6;hitPop(`🚧 BOOTH ${S.n}/${S.it.length}`,'#5dffb0');studGain(80,1)}else{S.cd=1;RO.v=-Math.max(6,Math.abs(RO.v)*.3);M1_snd('bump');say('','TOO SLOW · '+Math.round(kmh)+' km/h · need 80',1.2)}}}S.cd=(S.cd||0)-dt;const nx=S.it.find(o=>!o.done);if(nx){S.x=nx.x;S.z=nx.z}if(S.n>=S.it.length)return qvNext(ch);return}
  if(S.t==='tower'){const d=Math.hypot(S.x-RO.x,S.z-RO.z);S.cd-=dt;if(d<9&&S.cd<=0&&RO.y<groundY(S.x,S.z)+14){S.cd=1.4;if(kmh>=150){S.hp--;const k=S.hp0-S.hp;debris(V3(S.x,6,S.z),V3(Math.sin(RO.vh)*RO.v*.4,12,Math.cos(RO.vh)*RO.v*.4),30,[new THREE.Color('#ff2d55'),new THREE.Color('#ffd400'),new THREE.Color('#4ceaff')],1.5,0);M1_snd('takedown');shake=.9;slowmo=Math.max(slowmo,.4);S.m.scale.y=Math.max(.15,1-k*.3);hitPop(S.hp>0?`🗼 HIT ${k}/${S.hp0} · it regrows!`:'🗼 TOWER DOWN!','#5dffb0');if(S.hp<=0){S.m.visible=false;return qvNext(ch)}RO.v=-Math.max(8,Math.abs(RO.v)*.3)}else{RO.v=-Math.max(6,Math.abs(RO.v)*.3);M1_snd('bump');say('','TOO SLOW · '+Math.round(kmh)+' km/h · need 150',1.2)}}if(S.hp<S.hp0&&S.m.scale.y<1)S.m.scale.y=Math.min(1-(S.hp0-S.hp)*.3+.15,S.m.scale.y+dt*.02);return}
  if(S.t==='jumpR'){if(!S.warn&&V.left<15){S.warn=1;say('','THE BRIDGE IS ALMOST UP!',1.2)}return}}
// ---------- re-bound engine functions (originals keep working for every non-M1 event)
qvEnter=(f=>function(ch,i){if(!ch||!ch.m||!ch.m.m1)return f(ch,i);const V=ch.v2;if(M1.restoring&&i===0){const cp=M1.restoring;M1.restoring=null;return M1_restore(ch,cp)}const S=V.L.st[i];if(!S){V.si=i;return}
  if(M1_STD.has(S.t))f(ch,i);else{V.si=i;S.hold=0;QV.nav=null;M1_setup(ch,S,i)}V.left=S.T||(V.left>0?V.left:60);M1_hooks(ch,S,i)})(qvEnter);
function M1_hooks(ch,S,i){const e=ch.m.ev,V=ch.v2;for(const g of M1.goons)if(!g.dead&&g.S&&g.S!==S&&!g.leave&&!(g.S.hunt&&g.S.ph===S.ph)){g.leave=1;g.st='flee';g.ft=99}if(S.load){qvCrates(ch,S.load)}if(S.spill&&ch.vanAt){for(let k=0;k<5;k++){const x=ch.vanAt.x+(Math.random()-.5)*50,z=ch.vanAt.z+(Math.random()-.5)*50,m=new THREE.Mesh(new THREE.CircleGeometry(9,18).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0xc8e86a,transparent:true,opacity:.55,depthWrite:false}));m.position.set(x,groundY(x,z)+.08,z);RO.grp.add(m);M1_obj({m})}}
  if(S.hunt){M1_spawn(S,'rammer',S.hunt,null,140,230);if(e.mid==='duel')M1_radio('KAISER','A race without me? My boys will join in. <b>Wreck them both!</b>')}
  if(S.hunt2){M1_radio('ROSSI','Final sprint! Andiamo!');if(M1.rv)M1.rv.base*=1.04}
  if(S.cp&&!M1.restoring)M1.cp={mid:e.mid,si:i,x:RO.x,z:RO.z,h:RO.h,left:V.left,t:ch.t,hp:Math.max(60,M1.hp),vanAt:ch.vanAt?{...ch.vanAt}:null,rv:M1.rv?M1.rv.s:null,ph:S.ph};
  if(S.cp&&S.ph>1&&!M1.noScene)setTimeout(()=>{if(RO.ch===ch)hitPop(`PHASE ${S.ph}/${V.L.ph} · ${(M1_DEF[e.mid].ph[S.ph-1]||'').toUpperCase()}`,'#ffd400')},300);
  const sc=S.scene&&M1_SC[S.scene];if(sc&&!M1.noScene)sc(ch,S);
  const R1=M1_RADIO[e.mid]&&M1_RADIO[e.mid][i];if(R1&&!M1.noScene)setTimeout(()=>{if(RO.ch===ch&&!M1.cs)M1_radio(R1[0],R1[1])},sc?200:600)}
const M1_RADIO={hotdrop:{3:['HILDE','Kaiser parks at the Römer like he owns it. <b>Wreck his boys there!</b>'],4:['HILDE','Kaiser’s gone. Show me some style on the way home: <b>DRIFT!</b>']},
 heist:{2:['HILDE','Ha! Cider everywhere. The street is a skating rink: <b>drift it!</b>'],3:['KLAUS','Three barrels saved! Bring them home, the goons want them back!']},
 toll:{1:['BRIX','Bzzt! Four goons inbound from Sachsenhausen. Ram first, ask later.'],3:['HILDE','Kaiser is raising the Eiserner Steg to trap you! Hit that ramp at full <b>BOOST</b>!']},
 duel:{0:['ROSSI','Ready, rookie? Gates on the road, items in the ? boxes. <b>Andiamo!</b>']},
 hunt:{1:['BRIX','Bzzt! Shield car: only a <b>BOOST</b>-ram cracks it.'],2:['BRIX','Lieutenant spotted! He drops mines when he runs.']},
 rampage:{1:['BRIX','Bzzt! Push the giant brick into the pins. Strike!'],2:['BRIX','The tower regrows. Hit it fast, three times, 150+ km/h!']}};
function M1_restore(ch,cp){M1_clear();M1.noScene=1;M1.restoring=null;try{M1_warp(cp.x,cp.z,cp.h);ch.vanAt=cp.vanAt;if(ch.m.ev.mid==='duel')M1_rivalInit(ch,cp.rv);qvEnter(ch,cp.si)}finally{M1.noScene=0}const V=ch.v2;V.left=Math.max(cp.left,30);ch.t=cp.t;M1.hp=cp.hp;M1.cp=cp;ch.cd=1.2;ch.cdN=2;M1.restT=performance.now();say('↺ CHECKPOINT',`PHASE ${cp.ph} · ${(M1_DEF[cp.mid].ph[cp.ph-1]||'').toUpperCase()}`,1.4)}
function M1_rivalInit(ch,s){const rp=ch.v2.L.rp;if(!rp)return;const m=M1_car('sedan-sports','#e8302a',2.9,'#ffffff');M1.rv={P:rp.P,C:rp.C,s:s!=null?s:-12,base:39,m,x:rp.P[0][0],z:rp.P[0][1],pi:0,gap:0,stall:0};const a=qvAt(rp.P,rp.C,Math.max(0,M1.rv.s));M1_put(m,a.x+3,a.z+3,a.h)}
qvStep=(f=>function(ch,dt){if(!ch.m.m1)return f(ch,dt);const V=ch.v2,S=V.L.st[V.si];if(!S)return;M1_goonStep(dt);M1_rivalStep(ch,dt);if(RO.ch!==ch)return;if(M1.hp<=0)return qvFail(ch,'WRECKED · KAISER’S CREW GOT YOU');M1.hpT+=dt;M1.hp=Math.min(100,M1.hp+(M1.hpT>3?5:1.5)*dt);
  if(S.carry&&ch.n<=0)return qvFail(ch,'ALL BARRELS LOST');if(S.heavy&&!S.hvOn&&S.d&&Math.hypot(S.x-RO.x,S.z-RO.z)<S.d*.55){S.hvOn=1;M1_spawn(S,'heavy',1,{x:S.x,z:S.z,a:Math.atan2(RO.x-S.x,RO.z-S.z)},150,220);M1_radio('HILDE','A goon truck is blocking the way! Go around or BOOST-ram it!')}
  if(M1_STD.has(S.t)){if(S.T===0)V.left=Math.max(V.left,99);const h0=S.hit||0;const r=f(ch,dt);if(S.t==='chase'&&(S.hit||0)>h0&&RO.ch===ch){S.cd=4;S.bst=3.6}return r}V.left-=dt;if(V.left<=0)return qvFail(ch,S.t==='jumpR'?'THE BRIDGE IS UP':'TIME UP');M1_stage(ch,S,dt)})(qvStep);
chStep=(f=>function(dt){if(M1.cs&&RO.ch&&RO.ch.m.m1){M1_csTick(dt);RO.v=0;return}return f(dt)})(chStep);
qvTgt=(f=>function(ch){if(!ch.m.m1)return f(ch);const V=ch.v2,S=V.L.st[V.si],tg=V.tg;if(!S)return null;
  if(S.t==='follow'||S.t==='tail'){tg.x=S.vx;tg.z=S.vz;return tg}if(S.t==='thieves'||S.t==='goons'||S.t==='survive'){let b=null,bd=1e18;for(const g of M1.goons){if(g.dead||(g.S&&g.S!==S))continue;const d=Math.hypot(g.x-RO.x,g.z-RO.z);if(d<bd){bd=d;b=g}}if(!b)return null;tg.x=b.x;tg.z=b.z;return tg}
  if(S.t==='booths'||S.t==='tower'){tg.x=S.x;tg.z=S.z;return tg}if(S.t==='jumpR'){const near=Math.hypot(S.ax-RO.x,S.az-RO.z)<30||S.passed;if(near)S.passed=1;tg.x=near?S.r.x:S.ax;tg.z=near?S.r.z:S.az;return tg}return f(ch)})(qvTgt);
qvLand=(f=>function(ch,d){const V=ch.v2,S=V&&V.L.st[V.si];if(ch.m.m1&&S&&S.t==='jumpR'){if(d>=S.d){feed(`🛫 BRIDGE JUMP ${Math.round(d)} m`,500,'#ff2d95');M1_snd('style');slowmo=Math.max(slowmo,.5);return qvNext(ch)}if(d>12){say('',`${Math.round(d)} m · need ${S.d} m · go round again`,1.4);S.passed=0}return}return f(ch,d)})(qvLand);
qvMove=(f=>function(m){if(m&&m.m1)return;return f(m)})(qvMove);
qvSpawn=(f=>function(){if(M1_gated())return false;return f()})(qvSpawn);
npcSay=(f=>function(q,t){if(!M1.fs&&RO.ch&&RO.ch.m.m1&&(q===RO.ch.m.ev||q===QV_COACH))return;if(M1.cs&&!M1.fs)return;return f(q,t)})(npcSay);
qvBrief=(f=>function(m){if(!m.m1)return f(m);const D=M1_DEF[m.ev.mid],L=qvPreview(m),lk=M1_locked(m);return`<div class="brief qvb"><div><i>🎯</i><b>GOAL</b><span>${D.d}</span></div><div><i>📍</i><b>WHERE</b><span>${districtAt(m.x,m.z)} · starts right here.</span></div><div><i>🎬</i><b>PHASES · ${D.ph.length}</b><span>${D.ph.join(' → ')}</span></div><div><i>⭐</i><b>★★★</b><span>finish in ${fmt(L.g[0])} · phase checkpoints: a fail restarts the phase, not the mission.</span></div>${lk?`<div><i>🔒</i><b>LOCKED</b><span>${lk}</span></div>`:''}</div>`})(qvBrief);
markLocked=(f=>function(m){if(m&&m.m1)return !!M1_locked(m);if(M1_gated()&&m&&!M1_allow(m))return true;return f(m)})(markLocked);
markKnown=(f=>function(m){if(m&&m.m1)return true;if(M1_gated()&&m&&!M1_allow(m))return false;return f(m)})(markKnown);
function M1_allow(m){return m.kind==='garage'||m.kind==='flight'||!!m.m1||(m.kind==='otg'&&m.ev&&(m.ev.id==='sp1'||m.ev.id==='cl1'))}
storyCheck=(f=>function(){if(CID==='fra'){M1_initState();if(M1.s.fresh&&M1.s.step<4){const st=store.get('mho_story',{seen:0,end:0});if((st.seen||0)<1){st.seen=1;store.set('mho_story',st)}if(chapter()<=1)return false}}return f()})(storyCheck);
chAbort=(f=>function(){const was=RO.ch&&RO.ch.m&&RO.ch.m.m1;f();if(was){M1_clear()}})(chAbort);
chEnd=(f=>function(v){const ch=RO.ch,m1=ch&&ch.m.m1;if(m1)M1.lastEnd={mid:ch.m.ev.mid,ok:v!=null,t:ch.t,why:ch.why||null,si:ch.v2.si};f(v);if(m1){M1_clear();if(v!=null)M1_done(ch.m.ev.mid,ch)}})(chEnd);
qvAfter=(f=>function(ch,md,v,cr){f(ch,md,v,cr);const el=$('#chRes');if(!el)return;const row=el.querySelector('.qrb');if(!row)return;const ok=v!=null&&md>0,m=ch.m;const B=(t,fn,c,id)=>{const x=document.createElement('button');x.className='go'+(c?' alt':'');x.textContent=t;if(id)x.id=id;x.onclick=ev=>{ev.stopPropagation();el.hidden=true;el.classList.remove('qbtn');fn()};return x};
  if(m.m1&&!ok){row.innerHTML='';if(M1.cp&&M1.cp.mid===m.ev.mid)row.appendChild(B(`↺ RETRY PHASE ${M1.cp.ph} · ${(M1_DEF[m.ev.mid].ph[M1.cp.ph-1]||'').toUpperCase()}`,()=>M1_retryCp(),0,'m1Retry'));row.appendChild(B('↺ WHOLE MISSION',()=>qvRetry(0),1));row.appendChild(B('✕ QUIT',()=>{},1));clearTimeout(chResult.t);chResult.t=setTimeout(()=>{el.hidden=true;el.classList.remove('qbtn')},M1.resHold?1e9:30000)}
  else if(ok){if(m.m1)[...row.children].forEach(x=>{if(/NEW ROUTE/.test(x.textContent))x.remove()});setTimeout(()=>{const n=M1_next();if(!n)return;const nb=B(`NEXT ▸ ${n.t}`,()=>M1_nextGo(),0,'m1ResNext');row.prepend(nb)},m.m1?60:0);clearTimeout(chResult.t);chResult.t=setTimeout(()=>{el.hidden=true;el.classList.remove('qbtn')},M1.resHold?1e9:m.m1?10000:20000)}})(qvAfter);
qvHud=(f=>function(){f();const ch=RO.ch,hp=$('#m1Hp');if(!ch||!ch.m.m1||!ch.v2){if(hp)hp.hidden=true;return}const V=ch.v2,S=V.L.st[V.si];if(!S)return;const se=huQ('#qTrk .qs');if(se){huH(se,false);huT(se,`P${S.ph}/${V.L.ph}`)}
  const fight=M1.goons.some(g=>!g.dead&&g.kind!=='thief')||M1.hp<100;huH(hp,!fight||RO.mapOpen);if(fight){huS(hp.querySelector('u'),'width',Math.round(M1.hp)+'%');huS(hp.querySelector('u'),'background',M1.hp>60?'#5dffb0':M1.hp>30?'#ffd12c':'#ff2d55');huT(hp.querySelector('small'),Math.round(M1.hp)+' · '+M1.goons.filter(g=>!g.dead).length+' goons')}
  const p=huQ('#qTrk p');if(p){let x='';if(S.t==='goons')x=` · ${S.kill||0}/${S.need}`;else if(S.t==='thieves')x=` · ${S.th.filter(g=>g.dead).length}/${S.th.length}`;else if(S.t==='booths')x=` · ${S.n}/${S.it.length}`;else if(S.t==='survive')x=S.el<S.dur?` · hold ${Math.ceil(S.dur-S.el)} s`:' · BRECHER!';else if(S.t==='driftzone')x=` · ${Math.round(S.n)}/${S.p} · ${Math.max(0,Math.ceil(S.win-S.el))} s`;else if(S.t==='tower')x=` · ${S.hp0-S.hp}/${S.hp0}`;else if(S.t==='tail'&&S.away>0)x=` · ⚠ ${Math.ceil(8-S.away)} s`;if(M1.rv)x+=` · 🏎 Rossi ${M1.rv.gap>20?'AHEAD '+Math.round(M1.rv.gap)+' m':M1.rv.gap<-20?'behind':'level'}`;if(x&&!p.textContent.endsWith(x))huT(p,S.txt+x)}})(qvHud);
qvMiniQ=(f=>function(pin,R0,s){f(pin,R0,s);for(const g of M1.goons)if(!g.dead&&Math.hypot(g.x-RO.x,g.z-RO.z)<R0/s+20)pin(g.x,g.z,g.kind==='thief'?'#ff9a3c':'#ff2d55','!',false);if(M1.rv)pin(M1.rv.x,M1.rv.z,'#ff2d55','🏎',false)})(qvMiniQ);
roamCam=(f=>function(dt){if(M1.cs){if(RO.frozen)M1_csTick(dt);if(M1.cs){M1_csCam(dt);return}}f(dt);const t=M1.tdc;if(t&&t.t>0){t.t-=dt;const k=Math.min(.3,t.t);const l=V3(RO.x+(t.x-RO.x)*k,RO.y+2,RO.z+(t.z-RO.z)*k);camera.lookAt(l)}M1_camGuard()})(roamCam);
function M1_camGuard(){const c=camera.position;if(typeof DEB!=='undefined'&&DEB)for(const d of DEB.list){if(d.life>0&&Math.abs(d.p.x-c.x)<4&&Math.abs(d.p.z-c.z)<4&&Math.abs(d.p.y-c.y)<4)d.life=0}for(const g of M1.goons){if(!g.m.parent)continue;const near=Math.hypot(g.x-c.x,g.z-c.z)<9&&Math.abs(g.y+2-c.y)<7;if(near)g.m.visible=false;else if(!(g.inv>0))g.m.visible=true}
 if(RO.ch&&RO.ch.m.m1){FX.uniforms.uBoost.value=Math.min(FX.uniforms.uBoost.value,.15);FX.uniforms.uSpeed.value=Math.min(FX.uniforms.uSpeed.value,.25);hitFx=Math.min(hitFx,.3);flash=Math.min(flash,.25);const fx=huQ('#speedFx');if(fx&&+fx.style.opacity>.3)fx.style.opacity=.3}}
function M1_camInside(){const c=camera.position;let deb=0,goon=0;if(DEB)for(const d of DEB.list)if(d.life>0&&d.p.distanceTo(c)<2.2)deb++;for(const g of M1.goons)if(g.m.parent&&g.m.visible){const b=new THREE.Box3().setFromObject(g.m);if(b.containsPoint(c))goon++}const bld=!!roamHit(c.x,c.z,.3,c.y);return{deb,goon,bld}}
qvTick=(f=>function(dt){f(dt);try{M1_tick(dt)}catch(e){if(!M1.err){M1.err=1;console.warn('M1',e)}throw e}})(qvTick);
// ---------- progression, marks, guidance
function M1_locked(m){const id=m.ev&&m.ev.mid;if(id==='duel'&&M1_rep()<4)return`Earn street rep first: ${M1_rep()}/4 (story missions + Takedown Hunt or Smash Rampage).`;return''}
function M1_mkMark(id){const D=M1_DEF[id],a=id==='hotdrop'?M1_L('drop'):id==='heist'?M1_L('market'):id==='toll'?M1_L('tollN'):id==='duel'?M1_L('romerW'):id==='hunt'?M1_L('hunt'):M1_L('zeil');const ev={id:'m1_'+id,mid:id,kind:'m1',npc:D.npc,name:D.name,em:D.em,col:D.col,hi:D.hi,win:D.win,lose:D.lose,d:D.d,items:D.items};QAV[ev.id]=M1_av(D.who);
  const m=qvMk({kind:'quest',m1:1,ev,x:a.x,z:a.z,h:0,icon:D.em,col:D.col});if(D.story){const ring2=new THREE.Mesh(new THREE.TorusGeometry(12,.5,8,48),neonMat('#ffd400',2.6));ring2.rotation.x=Math.PI/2;ring2.position.y=.6;m.g.add(ring2)}return m}
function M1_marks(){if(CID!=='fra'||!qvGraph())return;M1_st();for(const m of RO.marks.filter(q=>q.m1)){const i=RO.marks.indexOf(m);RO.marks.splice(i,1);RO.grp.remove(m.g)}const s=M1.s,want=[];const sid=M1_STORY[s.step];if(sid)want.push(sid);if(s.step>=1)want.push('hunt');if(s.step>=2)want.push('rampage');M1.mk=1;for(const id of want){const m=M1_mkMark(id);if(RO.ch||RO.sp)m.g.visible=false}}
const M1_mark=id=>RO.marks.find(m=>m.m1&&m.ev.mid===id);
function M1_done(id,ch){const s=M1_st(),first=!s.done[id];s.done[id]=Math.max(s.done[id]||0,1);const si=M1_STORY.indexOf(id);if(si>=0&&si===s.step){s.step++;if(id==='duel'){s.wpn=1;const F=flags();if(!F.ROSSI){F.ROSSI=1;store.set('mho_flags',F)}}}M1_save();M1.cp=null;M1.pT=0;M1.pillH='';try{M1_marks()}catch(e){}
  if(first&&!M1_DEF[id].story)feed(`⭐ STREET REP ${M1_rep()}/4`,0,'#ffd400');setTimeout(()=>{if(state!=='roam')return;M1_marks();const end=M1_END[id];if(end&&first)M1.pend=end;else M1_autoRoute()},1500)}
function M1_autoRoute(){if(PIN_S.cur)return;const n=M1_next();if(n&&n.m&&!RO.ch){RO.wp=n.m;pickAdd(n.m)}}
const M1_END={hotdrop:()=>{const H=M1_hilde();const Gr=M1_L('garage');M1_put(H,Gr.x+10,Gr.z+6,0);M1_scene({cam:{a:()=>({x:RO.x,z:RO.z}),b:()=>({x:H.position.x,z:H.position.z})},lines:[['HILDE','Keys back, garage saved... for tonight. Kaiser’s <b>Schattenwerk</b> “taxes” every street in Sachsenhausen.'],['BRIX','Bzzt! BRIX online, Hilde’s radio drone. Your next job is always on the <b>NEXT</b> bar at the top.'],['HILDE','First job: Klaus at the Apfelwein market. Go, before Kaiser’s boys drink it all!']],end(){M1_autoRoute()}})},
 toll:()=>{const r=M1_mark('duel')||{x:RO.x,z:RO.z},K=M1_obj({m:M1_car('sedan-sports','#e8302a',2.9,'#ffffff')}).m;M1_put(K,RO.x+Math.sin(RO.h)*14,RO.z+Math.cos(RO.h)*14,RO.h+Math.PI);M1_scene({cam:{a:()=>({x:RO.x,z:RO.z}),b:()=>({x:K.position.x,z:K.position.z})},lines:[['ROSSI','So <b>you</b> are the rookie who embarrassed Kaiser’s crew? Cute. <b>Show me what you have, rookie!</b>'],['ROSSI','Street duel: Römer, Zeil, Alte Oper, Messe, Hauptbahnhof, back over the river to the Hauptwache. Items on.'],['HILDE','Earn a bit more street rep first: <b>Takedown Hunt</b> or <b>Smash Rampage</b>. Then beat Luca.']],end(){if(K.parent)K.parent.remove(K);M1.act=M1.act.filter(o=>o.m!==K);M1_autoRoute()}})},
 duel:()=>{M1_boxesCity();M1_scene({cam:{mode:'orbit',a:()=>({x:RO.x,z:RO.z}),r:26,h:9},lines:[['ROSSI','Bravissimo... Take the <b>Fulmine Rosso</b>, you earned it. And my flag.'],['HILDE','And I bolted an <b>ITEM SLOT</b> on your car. Item boxes are all over Mainhattan now: missiles, mines, ghost.'],['BRIX',`Bzzt! Drive through a <b>?</b> box, then press <b>${TOUCH.on?'ITEM':'F'}</b> to fire. Chapter 2 unlocked!`]],end(){const show=()=>storyShow({who:'HILDE',title:'Chapter 2 · The Harbour Gang',txt:'Chapter 1 complete! Item boxes are live across the city, and the map now shows every race, sprint and side job. <b>Jana Weber</b> and the harbour crew are next: find her flag on the map.'});if(RO.ch||RO.sp)M1.pend=show;else show();M1_tw();M1_autoRoute()}})}};
function M1_next(){if(CID!=='fra'){const F=flagsR(),nx=ATH_TRK_EV.find(e=>!F[e.p]);if(nx)return{ic:'🚩',t:`Race ${PD[nx.p].full}`,sub:`Athens flags ${athNF(F)}/6 · tap to open 🏁 EVENTS`,act:'events'};const m=RO.marks.find(q=>q.dyn);return m?{ic:'❓',t:markTitle(m),sub:'Encounter nearby',m,act:'route'}:{ic:'🏆',t:'Akropolis Cup',sub:'Open 🏁 EVENTS',act:'events'}}
  const s=M1_st();if(s.step===0)return{ic:'🪂',t:'STORY · Hot Drop',sub:'The opening · tap to start',act:'start',id:'hotdrop'};const sid=M1_STORY[s.step];
  if(sid){const m=M1_mark(sid);if(sid==='duel'&&M1_rep()<4){const a=[M1_mark('hunt'),M1_mark('rampage')].filter(q=>q&&!s.done[q.ev.mid]).sort((p,q)=>Math.hypot(p.x-RO.x,p.z-RO.z)-Math.hypot(q.x-RO.x,q.z-RO.z))[0];return{ic:'⭐',t:`Street rep ${M1_rep()}/4 · ${a?a.ev.name:'any activity'}`,sub:'Then: Street Duel vs Luca Rossi',m:a||m,act:'route'}}return{ic:M1_DEF[sid].em,t:'STORY · '+M1_DEF[sid].name,sub:m?districtAt(m.x,m.z):'',m,act:'route'}}
  const F=flagsR(),ch=chapter();const rv=RO.marks.filter(m=>m.kind==='rival'&&!F[m.ev.p]&&!markLocked(m)).sort((a,b)=>(RCH[a.ev.p]-RCH[b.ev.p])||Math.hypot(a.x-RO.x,a.z-RO.z)-Math.hypot(b.x-RO.x,b.z-RO.z))[0];if(rv)return{ic:'🚩',t:'Rival duel · '+PD[rv.ev.p].full,sub:`Chapter ${ch} · ${districtAt(rv.x,rv.z)}`,m:rv,act:'route'};
  const bs=RO.marks.find(m=>m.kind==='boss'&&!markLocked(m)&&!F.SKYCUP);if(bs)return{ic:'👑',t:'Boss · Vex Kaiser',sub:'Grand Arena',m:bs,act:'route'};const q=RO.marks.filter(m=>(m.kind==='quest'||m.kind==='otg')&&!markDone(m)&&!markLocked(m)&&markKnown(m)).sort((a,b)=>Math.hypot(a.x-RO.x,a.z-RO.z)-Math.hypot(b.x-RO.x,b.z-RO.z))[0];if(q)return{ic:mapIcon(q),t:markTitle(q),sub:districtAt(q.x,q.z),m:q,act:'route'};return{ic:'🧱',t:'Find golden bricks',sub:'Look for golden light beams',act:'none'}}
function M1_nextGo(){if(PIN_pillGo())return;const n=M1_next();if(!n||state!=='roam')return;M1.lastNextGo=n;if(n.act==='start'&&n.id==='hotdrop'){M1_startHotDrop();return}if(n.act==='events'){if(typeof openCareerMap==='function'&&CID==='fra')openCareerMap();else{exitRoam();menuTab='world';buildMenu&&buildMenu()}return}if(n.m){RO.wp=n.m;pickAdd(n.m);say('',('ROUTE SET · '+n.t).toUpperCase(),1.6);M1_snd('pick');if(Math.hypot(n.m.x-RO.x,n.m.z-RO.z)<40&&!RO.ch)roamOpen(n.m)}}
function M1_startHotDrop(){if(RO.ch)chAbort();if(RO.sp)sprintEnd();if(RO.card){RO.card=null;$('#roamCard').hidden=true}let m=M1_mark('hotdrop');if(!m){M1_marks();m=M1_mark('hotdrop')}if(!m)return false;const o=roamSave();if(!o.tut){o.tut=1;roamStore(o);$('#roamTut').hidden=true}M1.hp=100;chStart(m,{});return true}
function M1_pill(){const el=$('#m1Next');if(!el)return;const hide=!RO.on||!!RO.ch||!!RO.sp||RO.mapOpen||RO.jOpen||!!RO.card||!!M1.cs||RO.story||CM.on;huH(el,hide);if(hide)return;M1.pT=(M1.pT||0)-1;if(M1.pT>0&&M1.next)return;M1.pT=20;const n=M1.next=PIN_pill()||M1_next();if(!n)return;const d=n.m?' · '+qvKm(Math.hypot(n.m.x-RO.x,n.m.z-RO.z)):'';const h=n.ic+'|'+n.t+'|'+n.sub+d;if(h===M1.pillH)return;M1.pillH=h;el.querySelector('i').textContent=n.ic;el.querySelector('span').textContent=n.t;el.querySelector('small').textContent=(n.sub||'')+d}
function M1_tick(dt){if(!RO.on)return;M1_ui();M1_st();if(!M1.init&&CID==='fra'){M1.init=1;M1_initState();if(M1.s.fresh&&M1.s.step===0){const o=roamSave();o.tut=1;roamStore(o);$('#roamTut').hidden=true;M1.auto=1}}
  if(CID==='fra'&&!M1.mk&&QV.g&&QV.g.N===HUB.nodes){M1_marks();if(M1.s.wpn)M1_boxesCity()}
  if(M1.auto&&M1.mk&&!RO.ch&&!RO.card&&!RO.story){M1.auto=0;setTimeout(()=>{if(state==='roam'&&!RO.ch)M1_startHotDrop()},400)}
  if(M1.pend&&!RO.ch&&!RO.sp&&!RO.card&&!M1.cs&&!RO.story&&!qvResOpen()){const f=M1.pend;M1.pend=null;f()}
  if(M1.cs&&!(RO.ch&&RO.ch.m.m1))M1_csTick(dt);
  M1_itemStep(dt);if(!(RO.ch&&RO.ch.m.m1)&&M1.goons.length)M1_goonStep(dt);for(const o of M1.act)if(o.t==='crate'){o.life-=dt;if(o.life<=0&&o.m.parent){o.m.parent.remove(o.m)}else if(o.m.parent&&Math.hypot(o.x-RO.x,o.z-RO.z)<4.2&&Math.abs(RO.y-o.m.position.y)<4){o.m.parent.remove(o.m);RO.v*=.55;shake=.45;M1_snd('crash');hitPop('💥 CRATE HIT','#ff9a3c')}}
  // duel rival spawns with the mission
  if(RO.ch&&RO.ch.m.m1&&RO.ch.m.ev.mid==='duel'&&!M1.rv&&RO.ch.v2){M1_rivalInit(RO.ch,null);const rp=RO.ch.v2.L.rp;if(rp&&!M1.boxes.some(b=>b.mis))for(let s=500;s<rp.L-300;s+=650){const a=qvAt(rp.P,rp.C,s);M1_box(a.x,a.z,1)}}
  M1_pill();{const it=$('#m1Item');if(it){const on=!!M1.inv||M1.spin>0;huH(it,!on||TOUCH.on||!!M1.cs);if(on){const k=M1.inv||M1.spinK;const src=M1.spin>0?'':k==='ghost'?'':itemIcon(k==='mines'?'mines':'missile');const img=it.querySelector('img');if(img._s!==src){img._s=src;img.src=src||'data:,';img.style.visibility=src?'visible':'hidden'}huT(it.querySelector('b'),M1.spin>0?'…':k==='ghost'?'👻 GHOST':M1_IN[k])}}}
  if((M1.twT=(M1.twT||0)-dt)<=0){M1.twT=.5;M1_tw()}
  // BRIX: one hint per idle minute, always pointing at the next story beat
  if(!RO.ch&&!RO.sp&&!RO.card&&!M1.cs&&CID==='fra'){M1.hintT-=dt;if(M1.hintT<=0){M1.hintT=60;const n=M1_next();if(n&&n.act!=='none'){M1.hints=(M1.hints||0)+1;M1_radio('BRIX',`Bzzt! Next: <b>${n.t}</b>${n.m?' · '+qvKm(Math.hypot(n.m.x-RO.x,n.m.z-RO.z)):''}. Tap the NEXT bar for the route${n.act==='start'?' (or press N)':''}.`)}}}else M1.hintT=Math.max(M1.hintT,20)}
function M1_retryCp(){const cp=M1.cp,L=RO.qLast;if(!cp||!L||state!=='roam')return false;const t0=performance.now();const el=$('#chRes');if(el){el.hidden=true;el.classList.remove('qbtn')}if(RO.ch)chAbort();if(RO.card){RO.card=null;$('#roamCard').hidden=true}M1.restoring=cp;chStart(L.m,{seed:L.seed,O:L.O});M1.restoring=null;M1.retryMs=performance.now()-t0;return true}
// bot hint for tests: where to go and how to behave in the current stage
function M1_hint(){const ch=RO.ch;if(!ch||!ch.v2)return null;const V=ch.v2,S=V.L.st[V.si];if(!S)return null;const t=qvTgt(ch);const o={t:S.t,x:t?t.x:null,z:t?t.z:null,mode:'drive',si:V.si,ph:S.ph};
  if(S.t==='go')o.mode=S.stop?'stop':'drive';else if(S.t==='dpts'||S.t==='driftzone')o.mode='drift';else if(S.t==='chain')o.mode='chain';else if(S.t==='push'){o.mode='push';o.ball=S.b&&{x:S.b.x,z:S.b.z}}else if(S.t==='chase'||S.t==='thieves')o.mode='ram';else if(S.t==='goons'||S.t==='survive'){o.mode='ram';o.v=M1.goons.some(g=>!g.dead&&g.K.shield&&t&&Math.hypot(g.x-t.x,g.z-t.z)<1)?38:28}else if(S.t==='booths')o.mode='smash',o.v=32;else if(S.t==='tower')o.mode='smash',o.v=48;else if(S.t==='follow'||S.t==='tail')o.mode='follow';else if(S.t==='jumpR'){o.mode='jump';o.ramp={x:S.r.x,z:S.r.z,h:S.rh,len:S.r.len};o.ax=S.ax;o.az=S.az}return o}
window.__m1={M1,st:()=>M1_st(),next:()=>M1_next(),nextGo:()=>M1_nextGo(),start:id=>{if(id==='hotdrop')return M1_startHotDrop();const m=M1_mark(id)||M1_mkMark(id);M1.hp=100;chStart(m,{});return !!RO.ch},hint:()=>M1_hint(),retry:()=>M1_retryCp(),fire:()=>M1_fire(),give:k=>{M1.inv=k;M1_tw()},skip:()=>M1_csEnd(),tap:()=>M1_csNext(),cs:()=>M1.cs&&{i:M1.cs.i,n:M1.cs.D.lines.length,who:M1.cs.D.lines[Math.max(0,M1.cs.i)][0]},goons:()=>M1.goons.filter(g=>!g.dead).map(g=>({id:g.id,k:g.kind,x:g.x,z:g.z,hp:g.hp})),marks:()=>RO.marks.filter(m=>m.m1).map(m=>({id:m.ev.mid,x:m.x,z:m.z})),def:id=>{const D=M1_DEF[id];return D&&{ph:D.ph.slice(),g:D.g}},stages:()=>RO.ch&&RO.ch.v2&&RO.ch.v2.L.st.map(S=>({t:S.t,ph:S.ph,cp:!!S.cp})),boxes:()=>M1.boxes.map(b=>({x:b.x,z:b.z,on:b.t<=0,mis:b.mis})),spawn:(k,n)=>M1_spawn(null,k||'rammer',n||1,null,40,80).map(g=>g.id),clear:()=>M1_clear(),warp:(x,z,h)=>M1_warp(x,z,h),done:id=>M1_done(id,null),marksBuild:()=>M1_marks(),boxCity:()=>M1_boxesCity(),gated:()=>M1_gated(),rep:()=>M1_rep(),allow:m=>M1_allow(m),chain:n=>{CB.n=n;CB.t=2.8},camInside:()=>M1_camInside(),rv:()=>M1.rv&&{s:M1.rv.s,gap:M1.rv.gap,base:M1.rv.base}};
queueMicrotask(()=>{if(window.__mho)window.__mho.m1=window.__m1});
const M1_CSS=`#m1Cs{position:fixed;inset:0;z-index:60;pointer-events:auto;cursor:pointer;font-family:system-ui}#m1Cs .m1lb{position:absolute;left:0;right:0;height:11vh;background:#000;z-index:1}#m1Cs .m1lt{top:0}#m1Cs .m1lbb{bottom:0}@keyframes m1lb{from{height:0}}
#m1Cs .tk{position:absolute;left:50%;transform:translateX(-50%);bottom:calc(11vh + 12px + env(safe-area-inset-bottom,0px));width:min(640px,92vw);box-sizing:border-box;display:flex;gap:12px;align-items:center;background:rgba(20,20,19,.92);border:3px solid #ffd400;border-radius:16px;padding:10px 14px;color:#fff;box-shadow:0 6px 0 rgba(0,0,0,.3)}
#m1Cs .tk img{width:64px;height:64px;border-radius:50%;flex:none;background:#222}#m1Cs .tk b{display:inline-block;background:#ffd400;color:#141413;font-weight:900;font-size:13px;letter-spacing:.06em;padding:2px 9px;border-radius:6px;text-transform:uppercase}#m1Cs .tk p{margin:5px 0 2px;font-size:clamp(14px,2.2vw,18px);line-height:1.3}#m1Cs .tk small{opacity:.55;font-size:10px;letter-spacing:.12em}
#m1Skip{position:absolute;right:calc(14px + env(safe-area-inset-right,0px));top:calc(11vh + 10px);background:rgba(20,20,19,.85);color:#fff;border:2px solid #fff;border-radius:10px;padding:7px 14px;font:900 13px system-ui;letter-spacing:.08em;cursor:pointer}
body.m1cs #roam>*:not(#warpFade),body.m1cs #touch,body.m1cs #npcSay{visibility:hidden!important}
#m1Next{position:absolute;left:50%;transform:translateX(-50%);top:calc(86px + env(safe-area-inset-top,0px));display:flex;gap:8px;align-items:center;max-width:min(440px,74vw);padding:5px 12px 5px 8px;border-radius:12px;background:rgba(20,20,19,.86);border:2px solid #ffd400;color:#fff;font-family:system-ui;text-align:left;cursor:pointer;z-index:3;pointer-events:auto;box-shadow:0 4px 0 rgba(0,0,0,.25)}
#m1Next i{font-style:normal;font-size:22px}#m1Next b{display:block;font-size:9px;letter-spacing:.16em;color:#ffd400}#m1Next span{display:block;font-weight:900;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:min(360px,60vw)}#m1Next small{display:block;font-size:10px;opacity:.75;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:min(360px,60vw)}
#m1Hp{position:absolute;left:50%;transform:translateX(-50%);top:calc(40px + env(safe-area-inset-top,0px));display:flex;gap:6px;align-items:center;background:rgba(20,20,19,.8);border-radius:10px;padding:3px 9px;color:#ff4d6d;font:900 13px system-ui;z-index:3;pointer-events:none}#m1Hp i{display:block;width:120px;height:8px;background:#333;border-radius:4px;overflow:hidden}#m1Hp u{display:block;height:100%;background:#5dffb0;text-decoration:none}#m1Hp small{color:#fff;font-size:10px}
#m1Item{position:absolute;right:calc(64px + env(safe-area-inset-right,0px));bottom:calc(90px + env(safe-area-inset-bottom,0px));display:flex;gap:6px;align-items:center;background:rgba(20,20,19,.88);border:3px solid #ff2d95;border-radius:14px;padding:4px 10px 4px 4px;color:#fff;font:900 13px system-ui;z-index:3;cursor:pointer;pointer-events:auto}#m1Item img{width:40px;height:40px}#m1Item small{background:#fff;color:#141413;border-radius:5px;padding:1px 6px;font-size:11px}
#tW{position:absolute;display:none;place-items:center;border-radius:50%;border:3px solid #ff2d95;color:#ff2d95;background-color:rgba(20,20,19,.55);background-size:62%;background-position:center;background-repeat:no-repeat;font:900 11px system-ui;z-index:5}#tW.dim{opacity:.55}
@media (max-width:560px){#m1Next{top:calc(178px + env(safe-area-inset-top,0px));max-width:62vw}#m1Hp{top:calc(48px + env(safe-area-inset-top,0px))}#m1Hp i{width:80px}}
@media (max-height:500px){#m1Next{top:calc(56px + env(safe-area-inset-top,0px));padding:3px 10px 3px 6px}#m1Next i{font-size:17px}#m1Hp{top:calc(8px + env(safe-area-inset-top,0px));left:auto;right:calc(160px + env(safe-area-inset-right,0px));transform:none}#m1Cs .tk img{width:44px;height:44px}#m1Cs .m1lb{height:9vh}}`;

// ---- BA (Athens + touch play-test fixes). Self-contained: CSS only, injected at load. Prefix BA_.
const BA_CSS=`
@media (orientation:portrait){body.touch[data-thr=pedal] #roamGauge{bottom:calc(52px + clamp(50px,16vh,66px) + 2*clamp(48px,15vh,62px) + env(safe-area-inset-bottom,0px))}
 #athDP{display:grid!important;grid-template-columns:1fr 1fr;left:8px!important;right:64px;transform:none!important;bottom:10px!important;gap:5px!important}
 #athDP button{font-size:11px!important;line-height:1.15;padding:5px 6px!important;white-space:normal;text-align:center}}
@media (orientation:portrait){body #roamPark{top:calc(238px + env(safe-area-inset-top,0px));max-width:calc(100vw - 130px);white-space:normal;text-align:center;line-height:1.25}}
@media (max-height:500px){body #roamPark{top:calc(110px + env(safe-area-inset-top,0px))}}
html body.touch #roamPlate{padding-left:34px}
#roamMap .mh{right:64px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background:rgba(5,11,24,.82);color:#d8ecf6;padding:3px 8px;border-radius:6px;z-index:2;pointer-events:none}`;
(()=>{const st=document.createElement('style');st.id='baCss';st.textContent=BA_CSS;document.head.appendChild(st)})();
// ITEM button (#tW) is placed above the right-hand button cluster; in landscape that spot is under the AUTO/vehicle button (#roamVeh).
// After M1_tw places it, nudge it down below any top-right HUD button it hits, as long as it stays clear of the touch buttons.
M1_tw=(f=>function(){f();const w=$('#tW');if(!w||w.style.display==='none')return;const vis=e=>e&&e.offsetParent!==null&&!e.hidden&&e.getBoundingClientRect().width>4;
  const hit=(a,b)=>Math.min(a.right,b.right)-Math.max(a.left,b.left)>2&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>2;
  const tops=['#roamVeh','#roamHorn','#roamExit','#roamMapBtn'].map(s=>$(s)).filter(vis),btns=['#tB','#tD','#tN','#tF','#tG'].map(s=>$(s)).filter(vis).map(e=>e.getBoundingClientRect());
  for(let k=0;k<4;k++){const r=w.getBoundingClientRect(),o=tops.map(e=>e.getBoundingClientRect()).find(q=>hit(q,r));if(!o)return;const t=Math.round(o.bottom+8);
    const nr={left:r.left,right:r.right,top:t,bottom:t+r.height};if(btns.some(q=>hit(q,nr))||nr.bottom>innerHeight)return;w.style.top=t+'px'}})(M1_tw);

// ===== BF: play-test bug fixes (Frankfurt). Self-contained; every global is prefixed BF_. Existing functions are wrapped, never edited.
// BF1: the world keeps running behind full-screen overlays (map, garage builder, settings, story scenes) -> event timers tick, goons hit, held keys drive.
const BF_hold=()=>state==='roam'&&!!(RO.mapOpen||!$('#gbx').hidden||!$('#settings').hidden||RO.jOpen||RO.pOpen);
roamStep=(f=>function(dt){if(BF_hold()){if(pl){AU.engine(pl,0,false);AU.scrape(false)}return}return f(dt)})(roamStep);
// BF2: GARAGE from the pause menu during an event: saving re-enters roam, which silently aborts the running mission. Hide it while an event runs.
roamPauseOpen=(f=>function(){f();const b=document.querySelector('#roamPause [data-p="garage"]');if(b)b.hidden=!!(RO.ch||RO.sp)})(roamPauseOpen);
// BF3: a car that ends up inside a building collider (bad warp/landing) is pinned forever: the anti-stuck turn finds no free spot within 7 m
// and there is no reset. After 2 s inside a collider, put it back on the nearest street.
let BF_inT=0;
roamStep=(f=>function(dt){const r=f(dt);if(state!=='roam'||CID!=='fra'||!RO.on||RO.wk||BF_hold()||(pl&&pl.air)){BF_inT=0;return r}
  if(roamHit(RO.x,RO.z,1,RO.y)){BF_inT+=dt;if(BF_inT>2){BF_inT=0;BF_rescue()}}else BF_inT=0;return r})(roamStep);
function BF_rescue(){let best=null;for(const rr of [60,150,400]){for(let k=0;k<12&&!best;k++){const a=k/12*Math.PI*2,q=rfSnap(RO.x+Math.sin(a)*rr*.5,RO.z+Math.cos(a)*rr*.5,rr);if(!roamHit(q[0],q[1],3))best=q}if(best)break}
  if(!best)return;RO.x=best[0];RO.z=best[1];RO.y=groundAt(RO.x,RO.z,99);RO.h=RO.vh=best[2];RO.v=0;RO.vy=0;RO.yr=0;camSnap=true;say('','↺ BACK ON THE ROAD',1.2);AU.sfx('pick')}
// BF4: Escape on the results of a race started from free roam threw the player to the title menu (losing their place); go back to roam instead.
addEventListener('keydown',e=>{if(state==='results'&&e.code==='Escape'&&!$('#roamBack').hidden&&!$('#results').hidden){e.preventDefault();e.stopImmediatePropagation();enterRoam(RO.lastMark)}},true);
// BF5: chase camera clipped into buildings next to walls (occlusion test only looks straight back and keeps >=4 m; the lerp cuts corners).
// After the camera is placed, pull it toward the car until it is outside every building, else lift it above the car.
roamCam=(f=>function(dt){f(dt);if(state!=='roam'||CID!=='fra')return;const c=camera.position;if(!roamHit(c.x,c.z,.3,c.y))return;
  const x0=c.x,z0=c.z;let ok=0;for(let k=1;k<=7&&!ok;k++){const u=k/8,x=x0+(RO.x-x0)*u,z=z0+(RO.z-z0)*u;if(!roamHit(x,z,.3,c.y)){c.x=x;c.z=z;ok=1}}
  if(!ok){c.x=RO.x-Math.sin(RO.h)*2;c.z=RO.z-Math.cos(RO.h)*2;c.y=Math.max(c.y,RO.y+9)}camera.lookAt(RO.x+Math.sin(RO.h)*6,RO.y+1.5,RO.z+Math.cos(RO.h)*6)})(roamCam);
// BF6: phone landscape: the mission HP bar sat on top of the stage timer/stars panel (#raceW), and the district plate's first letters were hidden
// under the minimap ("nnenstadt"). Move the HP bar just below #raceW and the plate right of the minimap.
{const st=document.createElement('style');st.textContent=`@media (max-height:500px){html body #m1Hp{top:calc(46px + env(safe-area-inset-top,0px));left:50%;right:auto;transform:translateX(-50%)}}
@media (max-height:520px){html body.touch #roamPlate{left:calc(102px + env(safe-area-inset-left,0px))}}`;document.head.appendChild(st)}

/* ============================================================ LK · looks + phone performance
   lighting (warm low sun, cool sky fill, sky sun follows the key light, horizon haze, fog = horizon colour),
   materials (world-space colour variation + plastic sheen on every MeshStandardMaterial via one prototype hook: no new programs per material),
   water (sun glints), car paint, FX (boost flames, hotter drift sparks, wreck smoke), HUD polish (CSS only, no layout changes),
   auto quality (frame-time ladder high→med→low→min on top of the dynamic resolution), distance culling + fog/far per level. */
const LK={drop:0,userQ:null,effQ:null,acc:{t:0,n:0,sum:0,sq:0},last:0,since:0,log:[],plM:null,
  U:{uLkOn:{value:1},uLkSheen:{value:new THREE.Color(0,0,0)},uLkSunV:{value:new THREE.Vector3(0,1,0)},uLkT:{value:0}}};
const LK_LV=['high','med','low','min'];
// ---- 1 · day moods: warm, slightly lower sun (46° instead of 54°: longer shadows), cool sky fill + warm ground bounce, warm horizon, slightly lower exposure (no white-out)
(function(){const day={brick:{key:['#ffe9c8',2.3,[560,680,340]],hemi:['#fff3e4','#8c7450',.7],hor:[1.0,.88,.74],mid:[.36,.6,.98],sun:[2.8,2.15,1.4],exp:.97,env:.3},
  athens:{key:['#ffe2b4',2.4,[540,660,-320]],hemi:['#fff0dc','#9a8058',.7],hor:[1.02,.86,.66],sun:[3,2.3,1.4],exp:.96,env:.3},
  athnoon:{key:['#fff1dc',2.4,[260,980,180]],hemi:['#fff3e4','#a49272',.8],exp:.97},
  day:{key:['#ffe9c8',2.3,[560,680,340]],hemi:['#fff3e4','#8a7652',.7],exp:.98}};
 for(const L of [MOODS,typeof ATHM!=='undefined'?ATHM:[]])for(const m of L){const d=day[m.id];if(d)Object.assign(m,d,{lk:1})}})();
// sky: the sun glow follows the key light, plus a soft warm horizon haze on the sun side
function LK_sky(mat){if(!mat||mat.userData.lk)return;mat.userData.lk=1;mat.fragmentShader=mat.fragmentShader.replace('uniform vec3 uTop','uniform vec3 uSunD;uniform vec3 uTop')
  .replace('vec3 sn=normalize(vec3(.6,.06,-.8));','vec3 sn=normalize(uSunD);')
  .replace('c+=vec3(.45,.5,.8)*uLit','{float hz=exp(-max(h,0.)*11.);vec2 sh=normalize(sn.xz+1e-4),dh=normalize(d.xz+1e-4);c=mix(c,hor*1.04,hz*.4);c+=uSun*.05*hz*pow(max(dot(sh,dh),0.),3.);}c+=vec3(.45,.5,.8)*uLit');mat.needsUpdate=true}
SKYU.uSunD={value:new THREE.Vector3(.6,.06,-.8)};LK_sky(skyMat);ENVSC.traverse(o=>{if(o.material&&o.material.uniforms===SKYU)LK_sky(o.material)});
{const _am=applyMood;applyMood=id=>{_am(id);const m=MOOD,k=m.key[2];if(m.sun[0]+m.sun[1]>.5)SKYU.uSunD.value.set(k[0],Math.max(k[1]*.35,40),k[2]).normalize();else SKYU.uSunD.value.set(.6,.06,-.8);
  if(m.lk){const h=m.hor;FOGC.setRGB(h[0]*.92,h[1]*.92,h[2]*.94);scene.fog.color.copy(FOGC)}
  const s=hemi.intensity*(m.sun[0]>.5?.07:.03);LK.U.uLkSheen.value.copy(hemi.color).multiplyScalar(s)}}
// ---- 2 · materials: one prototype hook for every MeshStandard/Physical material without its own onBeforeCompile
const LK_VS='varying vec3 vLkW;\n',LK_VP='\n{vec4 lkP=vec4(transformed,1.);\n#ifdef USE_INSTANCING\nlkP=instanceMatrix*lkP;\n#endif\nvLkW=(modelMatrix*lkP).xyz;}';
const LK_FS='uniform float uLkOn,uLkT;uniform vec3 uLkSheen,uLkSunV;varying vec3 vLkW;\nfloat lkH(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float lkN(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(lkH(i),lkH(i+vec2(1,0)),f.x),mix(lkH(i+vec2(0,1)),lkH(i+vec2(1,1)),f.x),f.y);}\n';
function LK_inject(sh,water){if(sh.fragmentShader.includes('uLkOn'))return;Object.assign(sh.uniforms,LK.U);
  sh.vertexShader=LK_VS+sh.vertexShader.replace('#include <project_vertex>','#include <project_vertex>'+LK_VP);
  let f=LK_FS+sh.fragmentShader;
  // macro patches (~30 m) + fine grain (~1.5 m): breaks up flat plastic colour without a texture fetch; albedo capped at .8 so white paving no longer blows out
  if(!water)f=f.replace('#include <color_fragment>','#include <color_fragment>\nif(uLkOn>.5){float m1=lkN(vLkW.xz*.033+vLkW.y*.012),m2=lkN(vLkW.xz*.68+vec2(vLkW.y*.68,-vLkW.y*.4));diffuseColor.rgb=min(diffuseColor.rgb*(1.+(m1-.5)*.13+(m2-.5)*.05),vec3(.8));}');
  // LEGO plastic sheen: a sky-coloured fresnel rim; water also gets sparkling sun glints (HDR, picked up by bloom)
  f=f.replace('#include <opaque_fragment>','if(uLkOn>.5){vec3 lkV=normalize(vViewPosition);float fr=pow(1.-clamp(dot(normal,lkV),0.,1.),4.);outgoingLight+=uLkSheen*fr'+(water?'*3.;vec3 hH=normalize(lkV+uLkSunV);float sp=pow(max(dot(normal,hH),0.),600.)*step(.55,lkN(vLkW.xz*1.7+uLkT*vec2(.9,.6)));outgoingLight+=vec3(3.2,2.8,2.2)*sp*max(uLkSunV.y+.2,0.)':'')+';}\n#include <opaque_fragment>');
  sh.fragmentShader=f}
THREE.MeshStandardMaterial.prototype.onBeforeCompile=function(sh){LK_inject(sh,false)};
{const _wm=waterMat;waterMat=(...a)=>{const m=_wm(...a),o=m.onBeforeCompile,k=m.customProgramCacheKey();m.onBeforeCompile=(sh,r)=>{o(sh,r);LK_inject(sh,true)};m.customProgramCacheKey=()=>k+'|lkw';return m}}
// ---- 3 · car paint: glossier, slightly metallic body colours on the player craft (re-run when the craft changes)
function LK_paint(){if(!pl||!pl.mesh||LK.plM===pl.mesh)return;LK.plM=pl.mesh;const hsl={};pl.mesh.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material]){
  if(!m.isMeshStandardMaterial||m.userData.lkP||m.map||m.transparent||m.metalness>.6)continue;m.color.getHSL(hsl);if(hsl.s<.25||hsl.l<.12)continue;m.userData.lkP=1;m.roughness=Math.min(m.roughness,.34);m.envMapIntensity=Math.max(m.envMapIntensity??1,1.15)}})}
// ---- 4 · FX: hotter sparks (HDR, bloom), boost flames, dark smoke on wrecks. Fixed-size pools: no new draw calls
{const _em=emit;emit=(pool,p,v,life,c)=>{if(pool===SPARK&&c&&c.isColor&&fxK()>0){c=c.clone().multiplyScalar(1.35);if(GLOWP&&!CR_noGlow&&CR_glowFar(p)&&Math.random()<.25)_em(GLOWP,p,v.clone().multiplyScalar(.5),life*.7,new THREE.Color(2.4,1.3,.4))}return _em(pool,p,v,life,c)}}
{const _db=debris;debris=(at,vel,n,...r)=>{_db(at,vel,n,...r);if(n>=12&&fxK()>0&&typeof SMOKE!=='undefined'&&SMOKE)puff(at,4,new THREE.Color(.16,.15,.17),2.2,7,1.6,.5,1.5,5)}}
{const _ex=explode;explode=(s,...r)=>{const o=_ex(s,...r);try{if(fxK()>0&&s&&s.mesh){const at=s.mesh.position.clone();puff(at,6,new THREE.Color(.1,.09,.1),3,10,2.4,.55,2,6);fireball(at,4,4,.6)}}catch(e){}return o}}
const _lkF=new THREE.Vector3();function LK_boost(){return;if(state!=='roam'||!pl||!pl.nitro||!RO.on||fxK()===0||!FIREB)return;if((LK.bf=(LK.bf||0)+1)%2)return;const fx=Math.sin(RO.h),fz=Math.cos(RO.h);
  for(const sd of[-1,1])emitS(FIREB,_lkF.set(RO.x-fx*3.2+fz*sd*1.1,RO.y+.9,RO.z-fz*3.2-fx*sd*1.1),V3(-fx*14+rr(-1,1),rr(0,1.5),-fz*14+rr(-1,1)),rr(.12,.22),new THREE.Color(.6,1.4,3.2),.9,.25,.6,false)}
// ---- 5 · HUD polish (paint only: no sizes/positions change, so phone layouts are untouched)
{const st=document.createElement('style');st.id='lkHud';st.textContent=`#roamGauge b{text-shadow:0 2px 0 rgba(0,0,0,.35),0 0 14px rgba(90,200,255,.35)}
#rgBar,#rgHull{position:relative;box-shadow:inset 0 1px 2px rgba(0,0,0,.5)}#rgBar::after,#rgHull::after{content:'';position:absolute;inset:0;border-radius:inherit;background:linear-gradient(180deg,rgba(255,255,255,.38),rgba(255,255,255,0) 60%);pointer-events:none}
#roamGauge.on #rgBar{box-shadow:0 0 10px rgba(196,107,255,.8),inset 0 1px 2px rgba(0,0,0,.5)}#roamMini::after{content:'';position:absolute;inset:0;border-radius:50%;box-shadow:inset 0 0 16px rgba(0,0,0,.5),inset 0 0 0 1px rgba(255,255,255,.25);pointer-events:none}
#roamStuds{background:linear-gradient(180deg,#25a64a,#16772f)}#spdbar{box-shadow:inset 0 1px 2px rgba(0,0,0,.5)}`;document.head.appendChild(st)}
// ---- 6 · auto quality. Ladder high→med→low→min, never above the player's own Graphics choice; the player's choice is what gets saved
function LK_shadow(on){if(on&&!RO.shadowOn&&HUB.grp&&HUB.grp.visible){renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;moonL.castShadow=true;moonL.shadow.mapSize.set(2048,2048);const sc=moonL.shadow.camera;sc.left=-90;sc.right=90;sc.top=90;sc.bottom=-90;sc.near=50;sc.far=900;sc.updateProjectionMatrix();moonL.shadow.bias=-.0006;moonL.shadow.normalBias=.6;if(!moonL.target.parent)scene.add(moonL.target);RO.shadowOn=true;if(pl)pl.mesh.traverse(o=>{if(o.isMesh)o.castShadow=true})}
  if(!on&&RO.shadowOn){moonL.castShadow=false;RO.shadowOn=false;renderer.shadowMap.enabled=false}}
function LK_lvl(){return LK_LV[Math.min(3,LK_LV.indexOf(LK.userQ||SET.q)+LK.drop)]}
function LK_roamLook(){if(!HUB.grp||!HUB.grp.visible)return;const L=LK_lvl();scene.fog.density={high:.00016,med:.00024,low:.00032,min:.00045}[L];camera.far={high:3400,med:2600,low:2000,min:1500}[L];camera.updateProjectionMatrix();
  LK.U.uLkOn.value=L==='min'?0:1;LK_shadow(L==='high'&&SET.q==='high');if(RO.shadowOn){const sc=moonL.shadow.camera;if(sc.right!==90){sc.left=sc.bottom=-90;sc.right=sc.top=90;sc.updateProjectionMatrix()}}HUB.cpos=null}
function LK_apply(){const L=LK_lvl(),q=L==='min'?'low':L;LK.effQ=q;if(SET.q!==q){SET.q=q;_lkAQ()}LK_roamLook()}
const _lkAQ=applyQuality;applyQuality=(...a)=>{if(LK.effQ!==null&&SET.q!==LK.effQ){LK.userQ=SET.q;LK.drop=0}else if(LK.userQ===null)LK.userQ=SET.q;LK.effQ=SET.q;const r=_lkAQ(...a);LK_roamLook();return r};
{const _set=store.set;store.set=function(k,v){if(k==='mho_set'&&v&&LK.userQ&&LK.drop>0&&v.q===LK.effQ)v=Object.assign({},v,{q:LK.userQ});return _set.call(this,k,v)}}
{const _ht=hubTrafficStep;hubTrafficStep=dt=>{_ht(dt);LK_paint();LK_boost()}}
{const _he=hubEnter;hubEnter=(...a)=>{const r=_he(...a);LK_roamLook();LK_paint();return r}}
// extra distance culling on low/min (base: 2100/1600 m, small things 750 m)
{const _hc=hubCullStep;hubCullStep=()=>{const p=HUB.cpos;_hc();const L=LK_lvl();if(HUB.cpos!==p&&HUB.cull&&(L==='low'||L==='min')){const cx=camera.position.x,cz=camera.position.z,R2=L==='min'?1050:1350,Rs=L==='min'?420:520;for(const c of HUB.cull)if(c.o.visible&&Math.hypot(c.x-cx,c.z-cz)-c.r>(c.small?Rs:Math.min(R2,c.o.userData.cd||R2)))c.o.visible=false}}}
function LK_feed(ms){if(SET.lkAuto==='off'||paused||document.hidden||!(state==='roam'||state==='race'||state==='countdown')||ms>150||ms<=0){LK.acc={t:0,n:0,sum:0,sq:0};return}
  const A=LK.acc;A.t+=ms;A.n++;A.sum+=ms;A.sq+=ms*ms;LK.since+=ms;if(A.t<3000)return;const a=A.sum/A.n,sd=Math.sqrt(Math.max(0,A.sq/A.n-a*a));LK.acc={t:0,n:0,sum:0,sq:0};
  if(Math.abs(a-33.3)<3&&sd<4)return; // steady 30 fps = iOS low-power cap, not the GPU
  const resFloor=SET.dres!=='on'||DRES.s<=.65,top=LK_LV.indexOf(LK.userQ||SET.q);
  if(a>26&&resFloor&&top+LK.drop<3&&LK.since>4000){LK.drop++;LK.since=0;LK.log.push(['down',Math.round(a),LK_lvl()]);LK_apply()}
  else if(a<13.5&&LK.drop>0&&LK.since>12000){LK.drop--;LK.since=0;LK.log.push(['up',Math.round(a),LK_lvl()]);LK_apply()}}
{const _ds=dresStep;dresStep=ms=>{_ds(ms);LK_feed(ms);LK.U.uLkT.value=T;if(MOOD){const k=MOOD.key[2];LK.U.uLkSunV.value.set(k[0],k[1],k[2]).normalize().transformDirection(camera.matrixWorldInverse)}}}
window.__lk={LK,lvl:()=>LK_lvl(),feed:(ms,n)=>{for(let i=0;i<n;i++)LK_feed(ms)},apply:()=>LK_apply(),reset:()=>{LK.drop=0;LK.since=0;LK_apply()},save:()=>saveSet(),pools:()=>({fireb:FIREB?FIREB.list.length:0,smoke:SMOKE?SMOKE.list.length:0,spark:SPARK?SPARK.list.length:0,glow:GLOWP?GLOWP.list.length:0}),boom:()=>debris(V3(RO.x,RO.y+1,RO.z),V3(0,9,0),18,[new THREE.Color('#888')],1.1,RO.y)};

