// ---------- builder scene
function GB_hullMeshes(){const U=GB.mesh.userData,out=[];(U.carG||U.m).traverse(o=>{if(o.isMesh&&!o.userData.gb&&!o.userData.gbG&&o.visible&&o.material&&!o.material.transparent&&!o.material.isShaderMaterial)out.push(o)});return out}
function GB_scanBase(){GB.mesh.updateMatrixWorld(true);if(GB.d.bp){GB_.hull=[];const B={};for(let i=-4;i<=3;i++)for(let j=-6;j<=5;j++)B[i+','+j]=0;GB_.base=B;return}const m=GB.mesh.userData.m,H=GB_hullMeshes(),rc=GB_.rc,B={};GB_.hull=H;
 for(let i=GB_N0;i<=GB_N1;i++)for(let j=GB_N0;j<=GB_N1;j++){const x=(i+.5)*GB_U,z=(j+.5)*GB_U;if(Math.abs(x)<.95&&z>-3.1&&z<-.2)continue;
  let best=null;for(const[ox,oz]of[[0,0],[-.2,-.2],[.2,.2],[-.2,.2],[.2,-.2]]){const o=m.localToWorld(V3(x+ox,30,z+oz));rc.set(o,V3(0,-1,0));const h=rc.intersectObjects(H,false)[0];if(h){const y=m.worldToLocal(h.point.clone()).y;best=best==null?y:Math.max(best,y)}}
  if(best!=null&&best>-.5)B[i+','+j]=Math.round(best/GB_PH)}
 GB_.base=B}
function GB_gridMesh(){const U=GB.mesh.userData,host=U.carG||U.m;if(GB_.grid){host.remove(GB_.grid);GB_.grid.geometry.dispose()}const A=[];for(const k in GB_.base){const[i,j]=k.split(',').map(Number);A.push(GB_cyl(.16,.07,(i+.5)*GB_U,GB_.base[k]*GB_PH,(j+.5)*GB_U,'#9fefff',8))}
 if(!A.length)return;GB_.grid=new THREE.Mesh(mergeGeometries(A),new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.45,depthWrite:false}));GB_.grid.userData.gbG=1;host.add(GB_.grid)}
function GB_refresh(){if(!GB.mesh)return;GB_attach(GB.mesh,GB_list(),GB_figGet(),false,!!GB.d.bp);GB_ghostSet(null);GB_ui()}
function GB_ghostSet(b){const U=GB.mesh&&GB.mesh.userData;if(!U)return;const host=U.carG||U.m;if(GB_.ghost){host.remove(GB_.ghost);GB_.ghost.geometry.dispose();GB_.ghost=null}GB_.hov=b;if(!b)return;
 const M=[],L=[];GB_brickGeo(b,M,L);const g=mergeGeometries(M.concat(L).map(x=>x));GB_.ghost=new THREE.Mesh(g,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:b.bad?.3:.6,depthWrite:false,color:b.bad?0xff4040:0x7dffa0}));GB_.ghost.userData.gbG=1;host.add(GB_.ghost)}
// pointer -> what is under it: a brick (index) or a chassis cell
function GB_pick(cx,cy){const cvs=$('#gbC'),r=cvs.getBoundingClientRect(),rc=GB_.rc;GB_cam();rc.setFromCamera(new THREE.Vector2((cx-r.left)/r.width*2-1,-((cy-r.top)/r.height)*2+1),GB.cam);
 const U=GB.mesh.userData,m=U.m,objs=(U.gbM||[]).concat(GB_.hull);const h=rc.intersectObjects(objs,false)[0];if(!h)return null;const p=m.worldToLocal(h.point.clone());let bi=-1;
 if(h.object.userData.gb&&h.object.geometry.userData.bid)bi=h.object.geometry.userData.bid[h.faceIndex];const n=h.face?h.face.normal.clone():V3(0,1,0);if(!h.object.userData.gb)n.transformDirection(h.object.matrixWorld).transformDirection(m.matrixWorld.clone().invert());
 const q=p.clone().addScaledVector(n,GB_U*.35);return{brick:bi>=0?GB_list()[bi]:null,i:Math.floor(q.x/GB_U),j:Math.floor(q.z/GB_U)}}
function GB_cand(hit){if(!hit)return null;const P=GB_PC[GB_.pc],r=GB_.rot,[fw,fd]=r%2?[P.d,P.w]:[P.w,P.d];const b={t:GB_.pc,x:hit.i-Math.floor((fw-1)/2),z:hit.j-Math.floor((fd-1)/2),y:0,r,m:0,c:GB_.col},y=GB_fit(b,GB_list());if(y==null)return null;b.y=y;b.bad=GB_list().length>=GB_MAX;return b}
function GB_act(cx,cy,del){const h=GB_pick(cx,cy);let n=0;if(del||GB_.tool==='del'){if(h&&h.brick)n=GB_del(h.brick);if(n)AU.sfx('bump')}else if(GB_.tool==='paint'){if(h&&h.brick)n=GB_paint(h.brick);if(n)AU.sfx('pick')}
 else{const b=GB_cand(h);if(b)n=GB_add(b.t,b.x,b.z,b.r,b.c);if(n)AU.sfx('brick')}if(n)GB_refresh();return n}
function GB_msg(t){const e=$('#gbBkN');if(!e)return;e.textContent=t;clearTimeout(GB_msg.t);GB_msg.t=setTimeout(GB_ui,1400)}
// ---------- UI
{const st=document.createElement('style');st.textContent=`#gbx .gbTabs{flex-wrap:wrap}#gbx .gbTabs button{min-width:56px}
#gbx.gbBk .gbw{width:100%;height:100%;grid-template-columns:1fr;grid-template-rows:100%;gap:0}#gbx.gbBk .gbv{border-radius:0;border:0;min-height:0}#gbx.gbBk #gbC{position:absolute;inset:0}#gbx.gbBk .gbp,#gbx.gbBk #gbStats,#gbx.gbBk .gbHint{display:none}
#gbBkT,#gbBkP{display:none}#gbx.gbBk #gbBkT{display:flex}#gbx.gbBk #gbBkP{display:grid}
#gbBkT{position:absolute;left:8px;right:8px;top:calc(8px + env(safe-area-inset-top,0px));flex-wrap:wrap;gap:6px;align-items:center;pointer-events:none}
#gbBkT>*{pointer-events:auto}#gbBkS{position:fixed;right:8px;top:calc(96px + env(safe-area-inset-top,0px));display:grid;grid-template-columns:auto auto;gap:5px}#gbBkS button{height:30px!important;padding:0 8px!important;font-size:12px!important;letter-spacing:0!important;white-space:nowrap}#crSt{position:fixed;left:8px;top:calc(56px + env(safe-area-inset-top,0px));width:196px;padding:8px 10px;border-radius:12px;background:rgba(6,18,31,.88);border:1px solid rgba(76,234,255,.35);color:#fff;font:700 12px system-ui;pointer-events:none}#crSt>b{display:block;margin-bottom:4px;color:#ffd12c}#crSt div{display:flex;align-items:center;gap:6px;margin:2px 0}#crSt span{width:84px;opacity:.85}#crSt i{flex:1;height:6px;border-radius:3px;background:rgba(255,255,255,.15)}#crSt i b{display:block;height:100%;border-radius:3px;background:linear-gradient(90deg,#22c5e4,#7dffa0)}#crSt em{font-style:normal;color:#7dffa0}#crSt .crPk{display:block;margin-top:5px;color:#ffd12c}#crSt .crPk small{display:block;color:#cfe;font-weight:600}#gbBkT button{height:36px;min-width:38px;padding:0 9px;border-radius:10px;border:1px solid rgba(76,234,255,.45);background:rgba(6,18,31,.9);color:#fff;font:800 11px system-ui;letter-spacing:.04em;cursor:pointer}
#gbBkT button.on{background:linear-gradient(90deg,#22c5e4,#8c55ff);color:#05030f}#gbBkT .gbDone{background:linear-gradient(90deg,#ffd12c,#ff7a1c);color:#141413;border:0}
#gbBkN{font:900 12px system-ui;color:#ffd12c;background:rgba(6,18,31,.9);border-radius:10px;padding:0 10px;height:36px;display:flex;align-items:center;white-space:nowrap}
#gbBkP{position:absolute;left:0;right:0;bottom:0;gap:6px;padding:10px 8px calc(8px + env(safe-area-inset-bottom,0px));background:linear-gradient(rgba(3,10,20,0),rgba(3,10,20,.94) 26%)}
.gbBkR{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;padding:2px}#gbBkCt .gbCt{height:28px;padding:0 11px;border-radius:14px;border:1px solid rgba(76,234,255,.45);background:rgba(6,18,31,.9);color:#fff;font:800 12px system-ui;white-space:nowrap;flex:none}#gbBkCt .gbCt.on{background:linear-gradient(90deg,#22c5e4,#8c55ff);color:#05030f}.gbBkR::-webkit-scrollbar{display:none}
.gbPc{flex:none;width:56px;height:50px;border-radius:10px;border:1px solid rgba(76,234,255,.35);background:rgba(6,18,31,.92);color:#fff;font:800 10px system-ui;display:grid;place-items:center;padding:2px;cursor:pointer;line-height:1.05}.gbPc i{font-style:normal;font-size:17px}
.gbPc.on{border-color:#5dffb0;box-shadow:0 0 10px rgba(93,255,176,.6)}.gbCl{flex:none;width:32px;height:32px;border-radius:50%;border:2px solid rgba(255,255,255,.3);background:var(--c);cursor:pointer}.gbCl.on{border-color:#fff;box-shadow:0 0 0 2px #22e4ff}
.gbFig{display:flex;gap:10px;align-items:center;margin:4px 0}.gbFig img{width:72px;height:72px;border-radius:14px;border:2px solid rgba(76,234,255,.45)}.gbFig p{margin:0;font-size:11px;color:#8fb3c7}
#m1Cs .tk .gbMe{flex:none;display:grid;justify-items:center;gap:1px;margin-left:auto}#m1Cs .tk .gbMe img{width:48px;height:48px;border-radius:12px;background:#222;border:2px solid #22e4ff}#m1Cs .tk .gbMe small{opacity:.8;font-size:9px}
@media (max-width:760px),(max-height:500px){#gbBkT button{height:34px;padding:0 7px;font-size:10px}#gbBkN{height:34px;font-size:11px}.gbPc{width:50px;height:44px}.gbPc i{font-size:15px}.gbCl{width:28px;height:28px}}`;document.head.appendChild(st)}
{const tabs=$('#gbx .gbTabs');for(const[t,n]of[['bricks','BRICKS'],['driver','DRIVER']]){const b=document.createElement('button');b.dataset.t=t;b.textContent=n;b.onclick=()=>{if(t==='bricks')return GB_enter();GB.tab=t;gbRender()};tabs.appendChild(b)}
 const v=$('#gbx .gbv'),T=document.createElement('div');T.id='gbBkT';T.innerHTML=`<span id="gbBkN"></span><button data-a="undo" title="Undo (Ctrl+Z)">↶</button><button data-a="rot" title="Rotate (R)">⟳</button><button data-a="mir" title="Symmetric mode (M)">⇋ MIRROR</button><button data-a="add" title="Place">✚</button><button data-a="paint" title="Recolour one part">🖌</button><button data-a="pbody" title="Paint the whole body">🎨 BODY</button><button data-a="del" title="Delete (right-click)">🗑</button><button data-a="bp" title="Blank baseplate or jet chassis">⬛ BASE</button><button data-a="clr">CLEAR</button><div id="gbBkS">${GB_PRE.map((p,i)=>`<button data-a="pre${i}">${p[0]}</button>`).join('')}</div><div id="crSt" hidden></div><button data-a="done" class="gbDone">✔ DONE</button>`;
 const P=document.createElement('div');P.id='gbBkP';P.innerHTML=`<div class="gbBkR" id="gbBkCt">${CR_CATS.map(c=>`<button class="gbCt" data-ct="${c}">${c}</button>`).join('')}</div><div class="gbBkR" id="gbBkPc">${Object.entries(GB_PC).filter(e=>!e[1].hide).map(([k,p])=>`<button class="gbPc" data-p="${k}" data-ct="${p.cat||'Deco'}"><i>${p.ic}</i>${p.n}</button>`).join('')}</div><div class="gbBkR" id="gbBkCl">${GB_BC.map((c,i)=>`<button class="gbCl" data-c="${i}" style="--c:${c}" title="colour ${i+1}"></button>`).join('')}</div>`;v.appendChild(T);v.appendChild(P);P.addEventListener('click',e=>{const b=e.target.closest('.gbCt');if(b)CR_cat(b.dataset.ct)});CR_cat(GB_.ct||'Bricks');
 T.onclick=e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.a;AU.sfx('pick');if(a==='undo')GB_undo();else if(a==='rot'){GB_.rot=(GB_.rot+1)%4;GB_hover()}else if(a==='mir')GB_.mir=GB_.mir?0:1;else if(a==='add'||a==='paint'||a==='del')GB_.tool=a;else if(a.startsWith('pre'))GB_preset(+a[3]);else if(a==='clr'){GB_clear()}else if(a==='bp'){GB_snap();GB.d.bricks=[];GB.d.bp=GB.d.bp?0:1;GB_scanBase();GB_gridMesh();GB_refresh()}else if(a==='pbody')CR_paintBody();else if(a==='done')GB_exit();GB_ui()};
 P.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.p){GB_.pc=b.dataset.p;GB_.tool='add'}else if(b.dataset.c!=null){GB_.col=+b.dataset.c;if(GB_.tool==='del')GB_.tool='paint'}AU.sfx('pick');GB_ui();GB_hover()};
 // pointer: tap = act, drag = orbit, two fingers = orbit + pinch zoom, wheel = zoom, right click = delete
 const cvs=$('#gbC'),pt=e=>({x:e.clientX,y:e.clientY});
 v.addEventListener('pointerdown',e=>{if(!GB_.bk||e.target!==cvs)return;e.stopPropagation();cvs.setPointerCapture(e.pointerId);const p=pt(e);GB_.ptr.set(e.pointerId,{...p,x0:p.x,y0:p.y,t:performance.now(),b:e.button});if(GB_.ptr.size>1)GB_.multi=1;else GB_.multi=0;GB_.drag=0},true);
 v.addEventListener('pointermove',e=>{if(!GB_.bk||e.target!==cvs)return;e.stopPropagation();const q=GB_.ptr.get(e.pointerId),p=pt(e);
  if(!q){if(e.pointerType==='mouse'){GB_.mx=p;GB_hover()}return}
  if(GB_.ptr.size===1){if(Math.hypot(p.x-q.x0,p.y-q.y0)>(e.pointerType==='mouse'?8:14))GB_.drag=1;if(GB_.drag){GB_.yaw-=(p.x-q.x)*.01;GB_.pit=clamp(GB_.pit+(p.y-q.y)*.008,.12,1.4)}q.x=p.x;q.y=p.y;if(e.pointerType==='mouse'){GB_.mx=p;if(!GB_.drag)GB_hover()}return}
  const A=[...GB_.ptr.values()],d0=Math.hypot(A[0].x-A[1].x,A[0].y-A[1].y),mx0=(A[0].x+A[1].x)/2,my0=(A[0].y+A[1].y)/2;q.x=p.x;q.y=p.y;const d1=Math.hypot(A[0].x-A[1].x,A[0].y-A[1].y),mx1=(A[0].x+A[1].x)/2,my1=(A[0].y+A[1].y)/2;
  GB_.yaw-=(mx1-mx0)*.012;GB_.pit=clamp(GB_.pit+(my1-my0)*.01,.12,1.4);if(d0>10&&d1>10)GB_.dist=clamp(GB_.dist*d0/d1,7,26)},true);
 const up=e=>{if(!GB_.bk)return;const q=GB_.ptr.get(e.pointerId);if(!q)return;e.stopPropagation();GB_.ptr.delete(e.pointerId);if(e.type==='pointerup'&&!GB_.multi&&!GB_.drag&&performance.now()-q.t<(e.pointerType==='mouse'?900:1500))GB_act(q.x0,q.y0,q.b===2);if(!GB_.ptr.size)GB_.multi=0};
 v.addEventListener('pointerup',up,true);v.addEventListener('pointercancel',up,true);v.addEventListener('wheel',e=>{if(!GB_.bk)return;e.preventDefault();GB_.dist=clamp(GB_.dist*(1+e.deltaY*.001),7,26)},{passive:false});
 v.addEventListener('contextmenu',e=>{if(GB_.bk)e.preventDefault()});
 addEventListener('keydown',e=>{if(!GB_.bk||$('#gbx').hidden||(e.target&&e.target.tagName==='INPUT'))return;const k=e.code;if(k==='Escape'){e.preventDefault();e.stopImmediatePropagation();GB_exit();return}
  if(typeof G13_keys==='function'&&G13_keys(e))return;
  if(k==='KeyZ'&&(e.ctrlKey||e.metaKey))GB_undo();else if(k==='KeyR'){GB_.rot=(GB_.rot+1)%4;GB_hover()}else if(k==='KeyM')GB_.mir=GB_.mir?0:1;else if(k==='Delete'||k==='Backspace')GB_.tool=GB_.tool==='del'?'add':'del';else return;e.preventDefault();GB_ui()},true)}
function GB_hover(){if(!GB_.bk||!GB_.mx||GB_.tool!=='add')return GB_ghostSet(null);const b=GB_cand(GB_pick(GB_.mx.x,GB_.mx.y));const o=GB_.hov;if(o&&b&&GB_same(o,b)&&o.r===b.r&&o.c===b.c)return;GB_ghostSet(b)}
function GB_ui(){if(!GB.d)return;const L=GB_list(),md=GB_mods(L),fx=md?Object.entries(md).filter(([k,v])=>Math.abs(v-1)>.004).map(([k,v])=>`${{top:'top',acc:'acc',han:'grip',hull:'hull'}[k]} ${v>1?'+':''}${Math.round((v-1)*100)}%`).join(' · '):'';
 const n=$('#gbBkN');if(n)n.textContent=`🧱 ${L.length}/${GB_MAX}${fx?' · '+fx:''}`;document.querySelectorAll('#gbBkT button').forEach(b=>{const a=b.dataset.a;b.classList.toggle('on',a==='mir'?!!GB_.mir:a===GB_.tool)});
 document.querySelectorAll('#gbBkPc .gbPc').forEach(b=>b.classList.toggle('on',b.dataset.p===GB_.pc));document.querySelectorAll('#gbBkCl .gbCl').forEach(b=>b.classList.toggle('on',+b.dataset.c===GB_.col))}
function GB_enter(){if(!GB.mesh||!GB.d)return;GB.tab='bricks';document.querySelectorAll('#gbx .gbTabs button').forEach(b=>b.classList.toggle('on',b.dataset.t==='bricks'));GB_.bk=1;$('#gbx').classList.add('gbBk');GB_.undo=[];GB_.ptr.clear();
 if(GB.d.bp==null&&!GB_list().length)GB.d.bp=1;GB_.yaw=Math.PI*.78;GB_.pit=Math.max(GB_.pit||0,.3);GB_scanBase();GB_gridMesh();GB_refresh();GB_ui()}
function GB_exit(){if(!GB_.bk)return;GB_.bk=0;GB_ghostSet(null);if(GB_.grid&&GB.mesh){(GB.mesh.userData.carG||GB.mesh.userData.m).remove(GB_.grid);GB_.grid=null}$('#gbx').classList.remove('gbBk');GB.rot=GB_.yaw;GB.tab='parts';if(!$('#gbx').hidden)gbRender()}
function GB_cam(){const cvs=$('#gbC'),w=cvs.clientWidth,h=cvs.clientHeight;if(cvs.width!==Math.round(w*DPR2())||GB_.cw!==w+'x'+h){GB_.cw=w+'x'+h;GB.r.setPixelRatio(DPR2());GB.r.setSize(w,h,false);GB.cam.aspect=w/h;GB.cam.updateProjectionMatrix()}
 const d=GB_.dist*clamp(.95/GB.cam.aspect,1,2.2),ty=.5;GB.cam.position.set(Math.sin(GB_.yaw)*Math.cos(GB_.pit)*d,ty+Math.sin(GB_.pit)*d,Math.cos(GB_.yaw)*Math.cos(GB_.pit)*d);GB.cam.lookAt(0,ty,0);GB.cam.updateMatrixWorld()}
gbLoop=(f=>function(){if(!GB_.bk||$('#gbx').hidden)return f();GB_cam();if(!GB_.noDraw)GB.r.render(GB.sc,GB.cam);GB.raf=requestAnimationFrame(gbLoop)})(gbLoop);
gbRender=(f=>function(){f();if(GB.tab==='bricks'&&!GB_.bk)GB.tab='parts';if(GB_.stand){GB.sc.remove(GB_.stand);GB_.stand=null}document.querySelectorAll('#gbx .gbTabs button').forEach(b=>b.classList.toggle('on',b.dataset.t===GB.tab));if(GB.tab!=='driver')return;
 const fig=GB_figGet(),M=[],L=[];GB_figGeo(fig,M,L,false);GB_.stand=new THREE.Group();GB_.stand.add(new THREE.Mesh(mergeGeometries(M),GB_MAT));if(L.length)GB_.stand.add(new THREE.Mesh(mergeGeometries(L),GB_LMAT));GB_.stand.scale.setScalar(2.6);GB_.stand.position.set(5.2,-.25,3.2);GB_.stand.rotation.y=.5;GB.sc.add(GB_.stand);
 let h=`<div class="gbFig"><img id="gbFigImg" src="${GB_portrait(fig)}"><p>Your driver rides in the cockpit and appears in story scenes. Locked parts unlock through the story and Brick Packs.</p></div>`;
 for(const cat in GB_FIG){h+=`<h5>${GB_FCAT[cat]}</h5><div class="gbRow">`;for(const[id,nm,req]of GB_FIG[cat]){const ok=gbReq(req,'fig_'+id),sw=cat==='l'||cat==='c';h+=`<button class="gbP ${fig[cat]===id?'on':''}" ${ok?'':'disabled'} data-fc="${cat}" data-fv="${id}">${sw?`<b><span style="display:inline-block;width:10px;height:10px;border-radius:3px;background:${id};margin-right:5px"></span>${ok?'':'🔒 '}${nm}</b>`:`<b>${ok?'':'🔒 '}${nm}</b>`}${ok?'':`<small>${gbReqTxt(req)}</small>`}</button>`}h+='</div>'}
 const B=$('#gbBody');B.innerHTML=h;B.querySelectorAll('button[data-fc]').forEach(b=>b.onclick=()=>{const F=GB_figGet();if(!GB_figOk(b.dataset.fc,b.dataset.fv))return;F[b.dataset.fc]=b.dataset.fv;store.set('mho_gbfig',F);AU.sfx('pick');const sc=B.scrollTop;gbRender();$('#gbBody').scrollTop=sc})})(gbRender);
gbClose=(f=>function(save){if(GB_.bk){GB_.bk=0;GB_ghostSet(null);$('#gbx').classList.remove('gbBk');GB.tab='parts'}if(GB_.stand&&GB.sc){GB.sc.remove(GB_.stand);GB_.stand=null}return f(save)})(gbClose);
// garage stays blocked while an event / race-in-the-city runs (BF2 hides the pause button; this also covers every other entry point)
gbOpen=(f=>function(){if(state==='roam'&&(RO.ch||RO.sp)){try{say('GARAGE CLOSED','FINISH THE EVENT FIRST')}catch(e){}AU.sfx('bump');return}return f()})(gbOpen);
roamPauseOpen=(f=>function(){f();const b=document.querySelector('#roamPause [data-p="garage"]');if(b)b.hidden=!!(RO.ch||RO.sp)})(roamPauseOpen);{const e=$('#roamExit');if(e)e.onclick=()=>roamPauseOpen()}
// cutscenes: the player's minifig portrait listens in on every line
M1_csNext=(f=>function(){f();const tk=document.querySelector('#m1Cs .tk');if(!tk||!M1.cs)return;let me=tk.querySelector('.gbMe');if(!me){me=document.createElement('div');me.className='gbMe';me.innerHTML='<img alt=""><small>YOU</small>';tk.appendChild(me)}me.querySelector('img').src=GB_portrait()})(M1_csNext);
M1_av=(f=>function(w){return w==='YOU'?GB_portrait():f(w)})(M1_av);M1_WHO.YOU={n:'You',col:'#22e4ff',em:'🧑'};
window.__cr={RIVS:CR_RIVS,rivB:CR_rivB};window.__gb={mesh:()=>GB.mesh,refresh:()=>GB_refresh(),GB_,d:()=>GB.d,render:()=>gbRender(),PC:GB_PC,FIG:GB_FIG,enter:()=>GB_enter(),exit:()=>GB_exit(),list:()=>GB.d?GB_list():null,cells:GB_cells,undo:GB_undo,preset:GB_preset,add:GB_add,mods:GB_mods,fig:GB_figGet,portrait:()=>GB_portrait(),
 scene:()=>M1_scene({lines:[['HILDE','Nice driver. Now show me that car.'],['YOU','Ready when you are.']]}),
 // screen point of the top of chassis cell (i,j) at the current stack height (for real-input tests)
 scr:(i,j)=>{const t=GB_top(i,j,GB_list());if(t<-1e8)return null;const m=GB.mesh.userData.m;GB.mesh.updateMatrixWorld(true);GB_cam();const p=m.localToWorld(V3((i+.5)*GB_U,t*GB_PH+.02,(j+.5)*GB_U)).project(GB.cam),r=$('#gbC').getBoundingClientRect();return{x:r.left+(p.x+1)/2*r.width,y:r.top+(1-p.y)/2*r.height}},
 calls:()=>{const o=pl&&pl.mesh;if(!o)return null;let n=0,list=[];o.traverse(x=>{if(x.userData&&x.userData.gb){list.push(x);if(x.visible)n++}});return{n,tris:list.map(x=>x.geometry.attributes.position.count/3)}}};

// FX19: the "drag to rotate" hint sat on the GARAGE sign of the 3D hall. It now sits mid-right on the hall floor (the stats card covers the bottom), shows
// until the player's first real drag of the view (>20 px), then fades out and never comes back.
(()=>{const st=document.createElement('style');st.textContent='#gbx .gbHint{top:46%!important;right:10px!important;opacity:.85;transition:opacity .6s;background:rgba(3,14,26,.55);border-radius:8px;padding:2px 8px;pointer-events:none}#gbx .gbHint.fxOff{opacity:0!important}';document.head.appendChild(st);
 const box=document.getElementById('gbx'),h=box&&box.querySelector('.gbHint'),c=document.getElementById('gbC');if(!box||!h)return;let tm=0;
 const off=()=>{h.classList.add('fxOff');clearTimeout(tm)},show=()=>{if(store.get('fx19_drag',0)){off();return}h.classList.remove('fxOff')};
 let d0=null;if(c){c.addEventListener('pointerdown',e=>{d0=[e.clientX,e.clientY]},{passive:true});c.addEventListener('pointermove',e=>{if(d0&&Math.hypot(e.clientX-d0[0],e.clientY-d0[1])>20){d0=null;store.set('fx19_drag',1);off()}},{passive:true});addEventListener('pointerup',()=>{d0=null},{passive:true})}
 new MutationObserver(()=>{if(!box.hidden)show()}).observe(box,{attributes:true,attributeFilter:['hidden']});if(!box.hidden)show()})();
