// ---- GNB: 2K-style "build your own from a chassis" (slice 4). A 5th vehicle "My Build" (Neat) whose street car starts as a bare chassis frame:
// a black frame plate, 4 tyres on axles, the seat with its driver and steering wheel, taken 1:1 from a real set (true 8-wide proportions, tyres already on the road).
// NEW BUILD (builder toolbar or RIDES) → pick a chassis → snap parts on it. The part counter doubles as a build-limit bar plus the 2K weight class.
const GNB_K='#1b2a34',GNB_fr=b=>!!CR_WH[b.t]||/^(drv|drvL|stw|diff)$/.test(b.t)||(String(b.c).toLowerCase()===GNB_K&&/^T\d/.test(b.t));
const GNB_CH=[{id:'sc8',ic:'🏎',n:'SPEED CHAMPION',d:'8 wide · low · 4 sport tyres',src:()=>GAR_set('posei').car()},{id:'rod',ic:'🛣',n:'HOT ROD',d:'open frame · big rear tyres',src:()=>GAR_set('rod').car()}];
const GNB_frame=id=>GAR_arr((GNB_CH.find(c=>c.id===id)||GNB_CH[0]).src()).filter(GNB_fr).map(b=>({...b}));
{const R=GAR_set('rod');GAR_SETS.push({id:'mine',n:'My Build',tier:'c',req:null,car:()=>GNB_frame('sc8').map(b=>[b.t,b.x,b.z,b.r,b.c,b.y]),off:R.off,boat:R.boat,
 load:Object.assign(JSON.parse(JSON.stringify(R.load)),{car:Object.assign({},R.load.car,{name:'MY BUILD',k:'Street'})})});try{GPK_GRP.mine='Built by you'}catch(e){}}
// snap: parts never stack on a tyre (a mudguard wraps its wheel like on the real sets), and a blank base covers the whole floor plate of the chassis
GB_top=(f=>function(i,j,list){return f(i,j,list.filter(b=>!CR_WH[b.t]))})(GB_top);
GB_scanBase=(f=>function(){f();if(!GB.d||!GB.d.bp||!GB_.base)return;for(const b of GB_list()){if(CR_WH[b.t]||b.y>1||!/^T\d/.test(b.t))continue;const[fw,fd]=GB_dims(b);for(let i=b.x;i<b.x+fw;i++)for(let j=b.z;j<b.z+fd;j++){const k=i+','+j;if(GB_.base[k]==null&&i>=GB_N0&&i<=GB_N1&&j>=GB_N0&&j<=GB_N1)GB_.base[k]=0}}})(GB_scanBase);
// a mudguard tapped on or next to a tyre wraps that tyre (the tap ray hits the tyre's outer edge, one stud off)
GB_cand=(f=>function(hit){if(!hit||!/^(arch|fender)$/.test(GB_.pc))return f(hit);const L=GB_list(),P=GB_PC[GB_.pc],r=GB_.rot,[fw,fd]=r%2?[P.d,P.w]:[P.w,P.d];
 const w=L.find(b=>{if(!CR_WH[b.t])return false;const[ww,wd]=GB_dims(b);return hit.i>=b.x-1&&hit.i<=b.x+ww&&hit.j>=b.z-1&&hit.j<=b.z+wd});if(!w)return f(hit);
 const[ww,wd]=GB_dims(w),b={t:GB_.pc,x:w.x<0?w.x:w.x+ww-fw,z:w.z+Math.round((wd-fd)/2),y:0,r,m:0,c:GB_.col},y=GB_fit(b,L);if(y==null)return f(hit);b.y=y;b.bad=L.length>=GB_MAX;return b})(GB_cand);
// mirror: a centred part's twin would overlap the part itself (a doubled windscreen) → skip the twin
GB_fit=(f=>function(b,list){const o=list[list.length-1];if(o&&o!==b&&o.t===b.t&&o.y!=null){const[fw,fd]=GB_dims(b),[ow,od]=GB_dims(o);if(b.x===-o.x-ow&&b.z===o.z&&b.x<o.x+ow&&o.x<b.x+fw)return null}return f(b,list)})(GB_fit);
// builder view: the parts panel covers the bottom third, so the car's nose sat on its buttons and a tap there hit a button. Lift the view by 12 % of the height.
GB_cam=(f=>function(){f();const C=GB.cam,v=C.view,h=$('#gbC').clientHeight,w=$('#gbC').clientWidth,oy=GB_.bk?Math.round(h*.12):0;if(oy){if(!v||!v.enabled||v.offsetY!==oy||v.fullWidth!==w||v.fullHeight!==h)C.setViewOffset(w,h,0,oy,w,h)}else if(v&&v.enabled)C.clearViewOffset();C.updateMatrixWorld()})(GB_cam);
const GNB_W=n=>n<20?'Super Light':n<40?'Light':n<60?'Medium':n<80?'Heavy':n<100?'Super Heavy':'Massive';
GB_ui=(f=>function(){f();const n=$('#gbBkN');if(!n||!GB.d)return;const k=GB_list().length,p=Math.round(100*Math.min(1,k/GB_MAX));n.textContent=`🧱 BUILD LIMIT ${k}/${GB_MAX} · ${GNB_W(k)}`;n.style.background=`linear-gradient(90deg,rgba(255,209,44,.38) ${p}%,rgba(6,18,31,.9) ${p}%)`})(GB_ui);
function GNB_pick(){let P=$('#gnbP');if(!P){P=document.createElement('div');P.id='gnbP';$('#gbx .gbv').appendChild(P)}
 P.innerHTML=`<div class="gnbB"><b>NEW BUILD · pick a chassis</b><small>Your build becomes the vehicle "My Build" in RIDES.</small><div class="gnbR">${GNB_CH.map(c=>`<button data-ch="${c.id}"><i>${c.ic}</i><b>${c.n}</b><small>${c.d}</small></button>`).join('')}</div><button class="gnbX">CANCEL</button></div>`;P.hidden=false;
 P.onclick=e=>{const b=e.target.closest('button');if(!b)return;try{AU.sfx('pick')}catch(_){}P.hidden=true;if(b.dataset.ch)GNB_new(b.dataset.ch)}}
function GNB_new(id){if(GAR_get().sel!=='mine')GAR_select('mine');if(!GB_.bk)GB_enter();GB_snap();GB.d.bricks=GNB_frame(id);GB.d.bp=1;GB_scanBase();GB_gridMesh();GB_refresh();GB_.mir=1;GB_.tool='add';GB_.dist=11;GB_.pit=.95;GB_.yaw=Math.PI*.72;GB_ui();try{GB_msg('Bare chassis · tap to add parts')}catch(e){}}
GB_enter=(f=>function(){const r=f.apply(this,arguments);const T=$('#gbBkT');if(T&&!T.querySelector('[data-a="gnb"]')){const b=document.createElement('button');b.dataset.a='gnb';b.textContent='🆕 NEW BUILD';b.title='Start from a bare chassis';b.addEventListener('click',e=>{e.stopPropagation();GNB_pick()});T.insertBefore(b,T.querySelector('[data-a="bp"]'))}return r})(GB_enter);
GAR_tab=(f=>function(){f();const B=$('#gbBody'),gs=B.querySelector('.garSets');if(!gs)return;const b=document.createElement('button');b.className='gbP gnbGo';b.innerHTML='<b>🆕 BUILD YOUR OWN</b><small>start from a bare chassis</small>';b.onclick=()=>{try{AU.sfx('pick')}catch(e){}GB_enter();GNB_pick()};gs.appendChild(b)})(GAR_tab);
{const st=document.createElement('style');st.textContent=`#gnbP{position:absolute;inset:0;z-index:5;display:grid;place-items:center;background:rgba(3,8,20,.6)}#gnbP[hidden]{display:none}
.gnbB{background:#0b1626;border:2px solid #4ceaff;border-radius:16px;padding:12px 14px;max-width:96%;color:#fff;font:700 12px system-ui;display:grid;gap:8px;justify-items:center}.gnbB>b{font:900 italic 16px system-ui;color:#ffd12c}
.gnbR{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}.gnbR button{width:150px;display:grid;gap:2px;justify-items:center;padding:8px;border-radius:12px;border:2px solid rgba(76,234,255,.5);background:#12304a;color:#fff;cursor:pointer}
.gnbR i{font-style:normal;font-size:24px}.gnbR b{font:900 13px system-ui}.gnbR small,.gnbB small{font:600 12px system-ui;color:#cfe6f5}.gnbX{border:0;background:transparent;color:#8fb3c7;font:800 12px system-ui;min-height:32px;cursor:pointer}
#gbx .gnbGo{border-color:#ffd12c!important;min-width:118px}
#gbx.gbBk #gbBkP{pointer-events:none}#gbx.gbBk #gbBkP button{pointer-events:auto}`;document.head.appendChild(st)}
window.__gnb={dbg:(x,y)=>{const h=GB_pick(x,y),c=GB_cand(h);return JSON.stringify({h:h&&{i:h.i,j:h.j,b:h.brick&&h.brick.t},c,base:GB_.base[(h&&h.i)+","+(h&&h.j)]})},gap:()=>{const m=(typeof RO!=='undefined'&&RO&&RO.mesh)||(pl&&pl.mesh);if(!m)return null;m.updateMatrixWorld(true);const out=[],P=new THREE.Vector3(),S=new THREE.Vector3();m.traverse(o=>{if(o.userData&&o.userData.r&&o.userData.gb&&o.visible){o.getWorldPosition(P);o.getWorldScale(S);out.push(+(P.y-o.userData.r*S.y-groundAt(P.x,P.z,P.y+1)).toFixed(3))}});return out},saved:()=>({sel:GAR_get().sel,saved:(store.get('mho_build',{}).bricks||[]).length,live:GB.d?GB_list().length:null}),fit:(t,x,z,r)=>GB_fit({t,x,z,r:r||0,y:0},GB_list()),set:id=>GAR_arr(GAR_set(id).car()),frame:GNB_frame,pick:GNB_pick,nw:GNB_new,W:GNB_W};
