// ---------- UI part 3: drawers, start and result screens, settings, story mode, boot ----------
function pChip(p){return `<span class="pc" style="--pc:${PCOL[p.i]}"><i></i>${esc(p.nm)}</span>`}
function mdot(c,big){return `<span class="md ${big?'big':''}" style="--mc:${MCSS[c]}" title="${MNAME[c]}"></span>`}
function statusHtml(p){const s=scoreOf(p);const L=(ic,n,lab,t)=>`<span class="st" title="${t||lab}">${ic} <b>${n}</b><small>${lab}</small></span>`;
  return `<div class="stat" style="--pc:${PCOL[p.i]}"><b class="nm">${esc(p.nm)}${online()&&p.i===NET.mySeat?' <small>(you)</small>':''}${p.human?'':p.away?' <small>(left · cpu)</small>':' <small>(cpu)</small>'}</b><span class="tot" title="points so far">★ ${shownTotal(p)}</span>
   <div class="sts">${L('🪙',p.coins,'coins')}${L('🐪',p.camels,'camels')}${p.tent?L('⛺',1,'tent'):''}${L(mdot('vizier'),p.vz,'Advisors')}${L(mdot('elder'),p.el,'Sages')}${G.ex.artisans?L(mdot('artisan'),p.art,'Crafters'):''}${L('🔮',p.fk,'Mystics','Mystic cards: add power to Masons or Shadows, or stand in for a Sage')}${L('🧺',p.res.length,'goods · set '+goodsBest(p),'goods cards; the set is worth '+goodsBest(p)+' points now')}${p.dj.length?L('🧞',p.dj.length,'djinns'):''}</div></div>`}
function scoreTable(){const rows=G.over.scores;const keys=['coins','advisors','sages','crafters','djinns','tiles','palms','palaces','goods','items','cities','total'];const nm={coins:'🪙 Coins',advisors:'Advisors',sages:'Sages',crafters:'Crafters',djinns:'Djinns',tiles:'Tiles',palms:'Palms',palaces:'Palaces',goods:'Goods',items:'Items',cities:'Cities',total:'★ Total'};
  const epi=rows.map(r=>{const best=keys.filter(k=>k!=='total').sort((a,b)=>r.s[b]-r.s[a])[0];return `<li>${pChip(P(r.p))}: most of the points came from <b>${nm[best]}</b> (${r.s[best]}).</li>`}).join('');
  return `<div class="prompt"><h3>🏆 ${esc(G.winText)}</h3><ul class="story">${epi}</ul><div class="tw"><table><tr><th></th>${rows.map(r=>`<th>${pChip(P(r.p))}</th>`).join('')}</tr>${keys.filter(k=>k==='total'||rows.some(r=>r.s[k])).map(k=>`<tr class="${k==='total'?'tot':''}"><td>${nm[k]}</td>${rows.map(r=>`<td>${r.s[k]}</td>`).join('')}</tr>`).join('')}</table></div></div>`}
function renderPopups(){if(GX.open==='logd'){const lb=$('#logbody');lb.innerHTML=`<ol class="log">${G.log.slice(0,300).reverse().map(l=>`<li class="${l.c}"><small>R${l.r}</small> ${esc(l.t)}</li>`).join('')}</ol>`;lb.scrollTop=lb.scrollHeight}
  if(GX.open==='plrd')$('#plrbody').innerHTML=G.pl.map(p=>playerSheet(p)).join('');
  if(GX.open==='djd'&&$('#djbody').dataset.v!==String(G.logN))renderDjPop()}
function playerSheet(p){const s=scoreOf(p);const hid=online()&&!G.over&&p.i!==NET.mySeat;return `<section class="sheet" style="--pc:${PCOL[p.i]}"><h3>${pChip(p)} ${online()&&p.i===NET.mySeat?'<small>(you)</small>':''}${p.human?'':'<small>(computer)</small>'} <span class="tot">★ ${shownTotal(p)}</span></h3>${statusHtml(p)}
  <div><b>Goods:</b> ${p.res.length?p.res.slice().sort().map(r=>RICON[r]).join(' '):'none'} ${p.fk?`· ${p.fk} Mystic${p.fk>1?'s':''}`:''}</div>
  <div><b>Djinns:</b> ${p.dj.length?p.dj.map(k=>`<span class="tag" title="${esc(DJ[k].x)}">${esc(DJ[k].n)} ${DJ[k].vp}</span>`).join(' '):'none'}</div>
  ${G.ex.artisans?`<div><b>Items:</b> ${hid&&p.items.length?`${p.items.length} face down`:p.items.length?p.items.map(k=>`<span class="tag" title="${esc(ITEMS[k].x)}">${esc(ITEMS[k].n)}</span>`).join(' '):'none'}</div>`:''}
  ${G.ex.thieves?`<div><b>Cutpurses:</b> ${p.thieves.length?p.thieves.map(t=>esc(THIEVES[t.k].n)).join(', '):'none'}</div>`:''}
  <div><b>Tiles held:</b> ${G.board.filter(t=>owner(t)===p.i).map(t=>`${esc(tileName(t))}${t.palm?' 🌴'+t.palm:''}${t.pal?' 🏰'+t.pal:''}`).join(', ')||'none'}</div>
  <div class="small muted">So far: ${Object.entries(s).filter(([k,v])=>v&&k!=='total'&&!(hid&&k==='items')).map(([k,v])=>k+' '+v).join(' · ')}</div></section>`}
function renderDjPop(){const b=$('#djbody');b.dataset.v=String(G.logN);const inGame=DJINNS_FOR(G.ex);const where=k=>{if(G.djRow.includes(k))return 'on offer';for(const p of G.pl)if(p.dj.includes(k))return 'owned by '+p.nm;if(G.djDisc.includes(k))return 'discarded';return 'in the deck'};
  b.innerHTML=`<p class="muted small">Summon djinns at a Shrine: 2 Sages, or 1 Sage and 1 Mystic. Powers with a cost can be used once per turn, paying each time.</p><div class="cgrid">${inGame.map(d=>`<div class="card dj"><h4>${esc(d.n)} <small>${d.vp} pts</small></h4>${cardArt('djinn',d.n)}<div class="tag">${d.cost?{EF:'power: 1 Sage or 1 Mystic',EEF:'power: 1 Sage + 1 Sage-or-Mystic',F:'power: 1 Mystic','F+':'power: Mystics when bidding'}[d.cost]:'always on'} · ${where(d.k)}</div><p>${esc(d.x)}</p></div>`).join('')}</div>`}
function refHtml(){const sec=(t,items)=>`<h3>${t}</h3><div class="cgrid">${items.map(i=>`<div class="card"><h4>${i.n}${i.c>1?` <small>×${i.c}</small>`:''}</h4>${i.art||(/^[^\x00-\x7f]/.test(i.n)?cardArt('good',i.n,{glyph:i.n.split(' ')[0],hue:30}):'')}${i.tag?`<div class="tag">${esc(i.tag)}</div>`:''}<p>${esc(i.x)}</p></div>`).join('')}</div>`;
  const tiles=[];for(const [k,v,n,col] of TILESET.concat(TILESET_ART,TILESET_WHIM)){const d=TILEDEF[k];tiles.push({art:cardArt('tile',d.n+v,{blue:col?col==='blue':d.blue,v,hue:30}),n:d.n,c:n,tag:`${v?v+' points · ':''}${(col?col==='blue':d.blue)?'blue':'red'}${TILESET_ART.some(x=>x[0]===k)?' · Crafters':TILESET_WHIM.some(x=>x[0]===k)?' · Wonder Cities':''}`,x:d.x})}
  return sec('The tribes (and the Crafters)',Object.keys(MNAME).map(c=>({art:cardArt('tribe',c,{col:MCSS[c]||'#888',hue:35}),n:`${MNAME[c]} (${c==='vizier'?'yellow':c==='elder'?'white':c==='merchant'?'green':c==='builder'?'blue':c==='assassin'?'red':'purple'})`,c:c==='artisan'?15:MEEPLE_COUNT[c],tag:c==='artisan'?'Crafters expansion':'meeples',x:MHELP[c]})))+
   sec('Tiles',tiles)+sec('Goods cards',Object.keys(RESOURCE_COUNT).map(r=>({art:cardArt('good',r,{glyph:RICON[r]}),n:`${RICON[r]} ${RNAME[r]}`,c:RESOURCE_COUNT[r],tag:r==='fakir'?'special':'goods',x:r==='fakir'?'Adds 1 Mason or 1 Shadow range, pays for a Sage when summoning, pays djinn powers. Never part of a set.':'Collect sets of different kinds: 1, 3, 7, 13, 21, 30, 40, 50 or 60 points for 1–9 different kinds.'})))+
   sec('Djinns',DJINNS.map(d=>({n:d.n,tag:`${d.vp} points · ${d.cost?'power':'always on'}${d.set?' · '+{promos:'promo',artisans:'Crafters',thieves:'Cutpurses'}[d.set]:''}${d.assumed?' · '+d.assumed+' assumed':''}`,x:d.x})))+
   sec('Items (Crafters)',Object.values(ITEMS).map(i=>({n:i.n,c:i.cp,tag:i.kind,x:i.x})))+sec('Cutpurses',Object.values(THIEVES).map(t=>({n:t.n,tag:'Cutpurses expansion',x:t.x})))+
   sec('Tokens and pieces',[{n:'🐪 Camels',tag:'11 each with 2 players, 8 with 3–5',x:'Mark the tiles you control. Placing your last camel ends the game at the end of the round.'},{n:'⛺ Tent',tag:'Crafters · 1 each',x:'Claim a tile with it instead of a camel: it scores the tile plus 1 for each red tile around it.'},{n:'🌴 Palm tree',x:'3 points to whoever holds the tile (5 with Nakhla; doubled next to the Great Lake).'},{n:'🏰 Palace',x:'5 points to whoever holds the tile (doubled next to the Great Lake).'},{n:'⛰ Mountains',tag:'Crafters',x:'Block moving between two tiles (not Shadow range).'},{n:'🪙 Coins',x:'1 point each at the end; pay for turn order and bazaar goods.'},{n:'Turn-order track',x:'Costs 0, 0, 0, 1, 3, 5, 8, 12, 18 (5 players: 0, 0, 0, 1, 1, 3, 3, 5, 5, 8, 12, 18).'}])}
// ---------- inline SVG icons (consistent line icons instead of emoji in the chrome) ----------
const ICONS={bulb:'<path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10.5c.8.8 1 1.6 1 2.5h6c0-.9.2-1.7 1-2.5A6 6 0 0 0 12 3z"/>',
 camel:'<path d="M3 19v-5.5C3 11.6 4 10.6 5.6 10.6 6.6 7.8 7.6 7 9 7s2.3 1.6 3.2 3.6h1.6l1.3-3.2c.4-1 1.1-1.4 2-1.4h1.4l1.5 1.7-1.6.6-1 3.9v3.3M6.5 14v5M16.5 14v5M10.5 14.4V19"/>',
 lamp:'<path d="M2.5 14c2 2.2 5 3.3 9 3.3 3.6 0 5.7-1.3 6.8-3l3.2-2.1h-3.2C17.2 10.3 14.8 9.5 12 9.5c-3.3 0-6.9 1.3-9.5 4.5zM12 9.5V7.8M9 20.5h7M12.5 17.3v3.2"/><path d="M12 7.8c-1.3-1 0-2 .8-2.8s.2-2-.8-2.5"/>',
 scroll:'<path d="M7 4h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V6a2 2 0 0 0-2-2h3M4 4a2 2 0 0 0-2 2v2h4M10 9h6M10 13h6M10 17h3"/>',
 cards:'<rect x="3" y="6" width="11" height="15" rx="2"/><path d="M9.5 3.4l8.7 2.3a2 2 0 0 1 1.4 2.5L17 18"/><path d="M8.5 11l1.2 2.3 2.3.3-1.7 1.6.4 2.3-2.2-1.1-2.2 1.1.4-2.3-1.7-1.6 2.3-.3z"/>',
 book:'<path d="M12 6c-2-1.5-5-2-8-1.5v14c3-.5 6 0 8 1.5 2-1.5 5-2 8-1.5v-14c-3-.5-6 0-8 1.5zM12 6v14"/>',
 snd:'<path d="M4 9h4l5-4v14l-5-4H4z"/><path d="M16.5 9a4 4 0 0 1 0 6M19 6.5a7.5 7.5 0 0 1 0 11"/>',sndoff:'<path d="M4 9h4l5-4v14l-5-4H4z"/><path d="M17 9.5l5 5M22 9.5l-5 5"/>',
 mus:'<path d="M9 18V5.5l11-2v12.5"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/>',musoff:'<path d="M9 18V5.5l11-2v12.5"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/><path d="M3 3l18 18"/>',
 fast:'<path d="M3.5 6.5l7.5 5.5-7.5 5.5zM12 6.5l7.5 5.5L12 17.5z"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="M7 5l12 7-12 7z"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',plus:'<path d="M12 5v14M5 12h14"/>',
 gear:'<circle cx="12" cy="12" r="3.2"/><path d="M12 2.5v3M12 18.5v3M2.5 12h3M18.5 12h3M5.3 5.3l2.1 2.1M16.6 16.6l2.1 2.1M5.3 18.7l2.1-2.1M16.6 7.4l2.1-2.1"/>',
 gem:'<path d="M6 3h12l3 6-9 12L3 9zM3 9h18M9 3l-1 6 4 12 4-12-1-6"/>'};
function ICON(k){return `<svg class="ic" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${ICONS[k]||''}</svg>`}
function paintIcons(root){for(const e of (root||document).querySelectorAll('[data-ic]'))if(!e.firstChild)e.innerHTML=ICON(e.dataset.ic)}
function soundBtns(){const a=document.getElementById('sndbtn'),b=document.getElementById('musbtn');const on=typeof SND==='undefined'||SND.on,mu=typeof SND!=='undefined'&&SND.music;
  if(a){a.innerHTML=ICON(on?'snd':'sndoff');a.setAttribute('aria-pressed',on?'true':'false')}if(b){b.innerHTML=ICON(mu?'mus':'musoff');b.setAttribute('aria-pressed',mu?'true':'false')}if(GX.open==='setd')renderSettings()}
function hueOf(s){let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))%360;return h}
function cardArt(kind,name,o){o=o||{};const h=o.hue!=null?o.hue:hueOf(name);const id='ca'+Math.abs(hueOf(name+kind))+kind.length;let fg='';
  if(kind==='djinn')fg=`<path d="M22 58c6 5 16 7 28 7 11 0 17-4 20-9l9-6h-9c-3-6-10-8-19-8-9 0-20 3-29 16z" fill="#e9b24a" stroke="#6b3d10" stroke-width="1.5"/><path d="M50 42c-6-5 3-9 0-15-3-6 6-10 3-16" fill="none" stroke="hsl(${h},70%,85%)" stroke-width="4" stroke-linecap="round" opacity=".9"/><circle cx="53" cy="12" r="6" fill="hsl(${h},70%,80%)"/>`;
  else if(kind==='tribe')fg=`<path d="M40 70h20l-2-4c-3-2-4-8-4-16l4-2-3-2c4-2 6-6 6-10a11 11 0 0 0-22 0c0 4 2 8 6 10l-3 2 4 2c0 8-1 14-4 16z" fill="${o.col}" stroke="rgba(0,0,0,.45)" stroke-width="1.5"/><ellipse cx="46" cy="30" rx="3" ry="4" fill="rgba(255,255,255,.4)"/>`;
  else if(kind==='tile')fg=`<rect x="26" y="22" width="48" height="48" rx="6" fill="${o.blue?'#2d5f9f':'#b34a2a'}"/><rect x="31" y="27" width="38" height="38" rx="4" fill="#ecc996"/><rect x="33" y="54" width="34" height="8" rx="4" fill="#f6e7c6"/>${o.v?`<circle cx="36" cy="58" r="6" fill="${o.blue?'#1b3a66':'#7a2d17'}"/>`:''}`;
  else fg=`<text x="50" y="58" font-size="30" text-anchor="middle">${o.glyph||''}</text>`;
  return `<svg class="ca" viewBox="0 0 100 76" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="hsl(${h},55%,${kind==='djinn'?30:62}%)"/><stop offset="1" stop-color="hsl(${(h+30)%360},60%,${kind==='djinn'?14:40}%)"/></linearGradient></defs><rect width="100" height="76" fill="url(#${id})"/><path d="M0 76V40q50-30 100 0v36z" fill="rgba(255,255,255,.08)"/>${fg}</svg>`}
// ---------- the screens in front of the board ----------
function renderModal(){const m=$('#modal');if(!m)return;const h=UI.modal==='start'?startHtml():UI.modal==='over'&&G&&G.over?overHtml():UI.modal==='lobby'&&online()?lobbyHtml():'';m.hidden=!h;if(m.dataset.h!==h){
  const a=document.activeElement,id=a&&m.contains(a)&&a.id,sel=id&&a.selectionStart!=null?[a.selectionStart,a.selectionEnd]:null;const det=[...m.querySelectorAll('details')].map(d=>d.open);
  m.innerHTML=h;m.dataset.h=h;if(UI.modal==='start')paintOpening();[...m.querySelectorAll('details')].forEach((d,i)=>{if(det[i]!=null)d.open=det[i]});if(id){const e=document.getElementById(id);if(e){e.focus({preventScroll:true});if(sel)try{e.setSelectionRange(sel[0],sel[1])}catch(x){}}}}}
UI.setup={np:2,seats:['human','ai','ai','ai','ai'],lv:['normal','normal','normal','normal','normal'],ex:{artisans:false,sultan:false,thieves:false,promos:false}};
function startHtml(){const o=UI.setup;let saved=null;try{saved=localStorage.getItem(SAVE)}catch(e){}
  return `<div class="mbox start"><canvas id="opencv" width="640" height="220" aria-hidden="true"></canvas><h2>Sands of Qamar</h2><p class="lede">Lead the tribes. Rule the bazaar.</p>
   <div class="acts big">${online()?'':'<button class="btn go big" data-ui="quick">▶ Play vs computer</button>'}${window.CAMPAIGN&&typeof GXC!=='undefined'?'<button class="btn big" data-ui="story">📜 Story mode</button>':''}${saved&&!online()?'<button class="btn big" data-ui="continue">Continue saved game</button>':''}</div>
   <details class="exd"><summary><b>More ways to play</b></summary><div class="more"><div class="seg">${[2,3,4,5].map(n=>`<button class="${o.np===n?'on':''}" data-np="${n}">${n} players</button>`).join('')}</div>
   <div class="seats">${Array.from({length:o.np},(_,i)=>`<div class="seatrow" style="--pc:${PCOL[i]}"><i></i><b>${PNAMES[i]}</b><button class="btn sm" data-seatset="${i}">${o.seats[i]==='human'?'🙂 person':'🤖 computer'}</button>${o.seats[i]==='ai'?`<button class="btn sm ghost" data-lv="${i}">${o.lv[i]}</button>`:''}</div>`).join('')}</div>
   <div class="exs">${[['artisans','The Crafters'],['sultan','Wonder Cities'],['thieves','Cutpurses'],['promos','Promo djinns']].map(([k,n])=>`<label class="chk"><input type="checkbox" data-ex="${k}" ${o.ex[k]||(k==='sultan'&&o.np===5)?'checked':''} ${k==='sultan'&&o.np===5?'disabled':''}> <b>${n}</b></label>`).join('')}</div>
   <div class="acts">${online()?'':'<button class="btn go" data-ui="start">Begin ▶</button>'}<button class="btn" data-gx="rulesd">How to play</button><button class="btn" data-gx="refd">Card list</button></div>${typeof onlineBlock==='function'?onlineBlock():''}</div></details></div>`}
function overHtml(){const mp=viewP();const win=G.over.win;const won=mp&&win.includes(mp.i);
  return `<div class="mbox over"><h2>${mp?(won?(win.length>1?'You share the win':'You win!'):'You lose'):esc(G.winText)}</h2>${scoreTable()}<div class="acts"><button class="btn go" data-ui="again">Play again</button><button class="btn" data-ui="closeover">View the board</button></div></div>`}
function renderSettings(){const el=$('#setbody');if(!el)return;const seg=(attr,cur,opts)=>`<div class="seg">${opts.map(([v,l])=>`<button ${attr}="${v}" class="${String(cur)===String(v)?'on':''}">${l}</button>`).join('')}</div>`;
  el.innerHTML=`<div class="setrow"><h4>Sound</h4><div class="seg"><button data-a="snd" class="${typeof SND==='undefined'||SND.on?'on':''}">${ICON('snd')} Effects</button><button data-a="mus" class="${typeof SND!=='undefined'&&SND.music?'on':''}">${ICON('mus')} Music</button></div></div>
   <div class="setrow"><h4>Computer speed</h4>${seg('data-spd',UI.speed||1,[[.5,'Slow'],[1,'Normal'],[3,'Fast']])}</div>`+(typeof GXH!=='undefined'?`<div class="setrow"><h4>Help</h4>${GXH.settingsHTML({rowClass:'',btnClass:''})}</div>`:'')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-spd]');if(!b)return;UI.speed=+b.dataset.spd;if(G)render();renderSettings()});
// ---------- story mode (the shared campaign kit): ten chapters in three acts, bosses with a rule of their own ----------
function campStart(def){const s=def.setup||{},op=def.opponent||{};const np=s.np||s.players||(s.seats?s.seats.length:2);const seats=(s.seats||['human','ai']).slice(0,np);
  const lv=seats.map((x,i)=>i===0?'normal':(op.aiLevel||(s.lv&&s.lv[i])||'normal'));const ex=Object.assign({artisans:false,sultan:false,thieves:false,promos:false},s.ex||{});
  UI.fx.length=0;UI.fxSeen=0;resetScene();UI.modal=null;UI.camp=def;if(s.seed!=null)setSeed(s.seed);
  newGame({np,seats,lv,names:s.names,ex,mode:'x'});applyTwist(def);
  UI.setup.np=np;refresh()}
function campMetrics(g){const p=g.pl[0],s=scoreOf(p);const rivals=g.pl.slice(1).map(q=>scoreOf(q).total);const best=Math.max(...rivals);const won=!!g.over&&g.over.win.includes(0);
  return {won,score:s.total,margin:s.total-best,coins:p.coins,goods:s.goods,tiles:g.board.filter(t=>owner(t)===0).length,djinns:p.dj.length,advisors:p.vz,cities:g.board.filter(t=>t.k==='city'&&owner(t)===0).length,palaces:s.palaces,rounds:g.round}}
function campIsWon(g,def){const m=campMetrics(g);if(!m.won)return false;const gl=def.goal||{};switch(gl.type){case 'score':return m.score>=gl.value;case 'margin':return m.margin>=gl.value;case 'before-round':return m.rounds<gl.value;case 'custom':return gl.test?GXC.testStar(gl.test,m):true}return true}
function campInit(){if(typeof GXC==='undefined'||!window.CAMPAIGN)return;GXC.init({game:'sands',data:window.CAMPAIGN,startChapter:campStart,isWon:campIsWon,metrics:campMetrics,onExit:()=>{UI.camp=null;UI.modal='start';render()},
  scores:g=>g.pl.map(p=>scoreOf(p).total),seats:g=>g.pl.map((p,i)=>({name:p.nm,me:i===0,ai:p.human?undefined:p.lv}))})}
// ---------- start ----------
function boot(){GX.init({key:'soq'});paintIcons();GX.onShow=id=>{if(id==='setd')renderSettings();if(id==='rulesd')$('#rulesbody').innerHTML=RULES_HTML;if(id==='refd')$('#refbody').innerHTML=refHtml();if(id==='djd'&&G)renderDjPop();if(G)render()};
  campInit();soundBtns();UI.modal='start';render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
