#!/usr/bin/env python3
"""Per-bar loudness of every Nightrun song -> parts/songs.js (embedded in the page).
Run: python3 games-src/nightrun/analysis/song-energy.py   (needs ffmpeg). Bars are counted from the first beat (offsetMs) at the track's bpm.
Energy digit 0-9 per bar: RMS in dB, mapped between the 8th and 97th percentile of that song, smoothed over 3 bars."""
import json, subprocess, struct, math, os, sys
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
M = os.path.join(R, 'games', 'mainhattan-nightrun', 'music')
tracks = json.load(open(os.path.join(M, 'tracks.json')))['tracks']
SR = 8000
out = {}
for t in tracks:
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', os.path.join(M, t['file']), '-ac', '1', '-ar', str(SR), '-f', 's16le', '-'], capture_output=True, check=True).stdout
    n = len(raw) // 2
    s = struct.unpack('<%dh' % n, raw)
    dur = n / SR
    bar = 4 * 60.0 / t['bpm']
    off = t['offsetMs'] / 1000.0
    bars = int((dur - off) // bar)
    db = []
    for b in range(bars):
        a = int((off + b * bar) * SR); z = int((off + (b + 1) * bar) * SR)
        seg = s[a:z]
        ms = sum(x * x for x in seg) / max(1, len(seg))
        db.append(10 * math.log10(ms + 1e-3))
    srt = sorted(db); lo = srt[int(.08 * (len(srt) - 1))]; hi = srt[int(.97 * (len(srt) - 1))]
    e = [min(1, max(0, (d - lo) / max(1, hi - lo))) for d in db]
    sm = [sum(e[max(0, i - 1):i + 2]) / len(e[max(0, i - 1):i + 2]) for i in range(len(e))]
    out[t['stage']] = {'dur': round(dur, 2), 'bpm': t['bpm'], 'off': t['offsetMs'], 'bars': bars, 'e': ''.join(str(min(9, int(x * 10))) for x in sm)}
    print(t['stage'], 'dur %.1f' % dur, 'bpm', t['bpm'], 'bars', bars, 'avg e %.2f' % (sum(sm) / len(sm)))
js = '/* generated by analysis/song-energy.py: length in bars and loudness per bar (0-9) of every song, used by the district director */\nconst SONGM=' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(R, 'games-src', 'nightrun', 'parts', 'songs.js'), 'w').write(js)
