// ath/v88w/close.js <url> fra|ath <outdir> : close-up shots for the 2x brick review at 3 street spots:
//   <c>_<f>_fac.png  = street-level view (2 m up) 40° off the street axis, facades at ~10-30 m
//   <c>_<f>_car.png  = low side view (1 m up, 6 m away) of the nearest traffic car (frozen)
//   + draws/tris of the normal chase view per spot. SPOTS=0.2,0.5,0.8
const enter=require('../../bc/enter.js');const fs=require('fs');const URL=process.argv[2],CITY=process.argv[3]||'fra',OUT=process.argv[4];fs.mkdirSync(OUT,{recursive:true});
(async()=>{const seed=CITY==='ath'?`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}));localStorage.setItem('mho_city@1','ath');localStorage.setItem('mho_athd@1','A');localStorage.setItem('mho_roam.ath@1','{"otg":{},"tut":1}');localStorage.setItem('mho_story.ath@1','{"seen":1}')`:`localStorage.setItem('mho_slot','1');localStorage.setItem('mho_roam@1',JSON.stringify({tut:1,otg:{}}))`;
 const E=await enter(URL,{gfx:'normal',seed});const {p,errs}=E;p.setDefaultTimeout(900000);await E.roamApi();await p.evaluate(()=>{window.__wb&&window.__wb.fast&&window.__wb.fast();__tick&&__tick(1);window.__bw&&window.__bw.fast()});
 const F=(process.env.SPOTS||'0.2,0.5,0.8').split(',').map(Number);
 const SF=`ath/v88w/spots_${CITY}.json`;let spots=fs.existsSync(SF)?JSON.parse(fs.readFileSync(SF,'utf8')):null;if(!spots){spots=await p.evaluate(K=>{const H=__mho.HUB,N=H.nodes,B=H.bld||[],sc=[];for(let i=0;i<N.length;i++){const a=N[i];if(!a||!a.nb||a.nb.length<2||a.ab||!N[a.nb[0]])continue;let n=0;for(const b of B)if(b.h>5&&Math.abs(b.x-a.x)<35&&Math.abs(b.z-a.z)<35)n++;sc.push([n,i])}sc.sort((a,b)=>b[0]-a[0]);const pick=[];for(const [n,i] of sc){const a=N[i];if(pick.every(j=>Math.hypot(N[j].x-a.x,N[j].z-a.z)>400))pick.push(i);if(pick.length>=K)break}return pick.map(i=>{const a=N[i],b=N[a.nb[0]];return[a.x,a.z,Math.atan2(b.x-a.x,b.z-a.z)]})},F.length);fs.writeFileSync(SF,JSON.stringify(spots))}const out=[];
 const hide=()=>p.evaluate(()=>{const cv=document.querySelector('canvas');for(const e of document.body.children)if(!e.contains(cv))e.style.visibility='hidden';else for(const c of e.children)if(!c.contains(cv)&&c!==cv)c.style.visibility='hidden'});
 const info=()=>p.evaluate(()=>{const r=__g9ev('renderer');r.info.autoReset=false;r.info.reset();__tick(1);const o={calls:r.info.render.calls,tris:r.info.render.triangles};r.info.autoReset=true;return o});
 for(let i=0;i<spots.length;i++){const [x,z,h]=spots[i];await p.evaluate(([x,z,h])=>{const M=__mho,R=M.RO;M.warp(x,z,h,performance.now());R.x=x;R.z=z;R.y=M.gnd(x,z,R.y+60);R.v=0;R.vh=h;R.h=h},[x,z,h]);await p.waitForTimeout(7000);await p.evaluate(()=>window.__bw&&__bw.fast());
  const n=await info();out.push(['chase',F[i],n.calls,n.tris]);
  await p.evaluate(()=>{const M=__mho,R=M.RO,g=M.gnd(R.x,R.z,R.y+.3),a=R.h+0.7;__gnb.cam([R.x-Math.sin(R.h)*4,g+2,R.z-Math.cos(R.h)*4,R.x+Math.sin(a)*40,g+7,R.z+Math.cos(a)*40])});await p.waitForTimeout(2500);await hide();
  const n2=await info();let f=`${OUT}/${CITY}_${F[i]}_fac.png`;await p.screenshot({path:f});out.push([f,n2.calls,n2.tris]);
  const r=await p.evaluate(()=>{const M=__mho,R=M.RO,H=M.HUB,N=H.nodes;let c=null,bd=250,hh=0;for(const o of(H.cars||[])){if(o.dead>0||o.tr)continue;const A=N[o.a],B=N[o.b];if(!A||!B||A.ab||B.ab)continue;const L=Math.hypot(B.x-A.x,B.z-A.z);if(L<16)continue;const d=Math.hypot(o.x-R.x,o.z-R.z);if(d<bd&&d>3){bd=d;c=o;hh=Math.atan2((B.x-A.x)/L,(B.z-A.z)/L)}}if(!c)return null;c.v=0;c.cv=0;c.hv=.01;c.route=[];c.hitT=99;
   const g=M.gnd(c.x,c.z,R.y+.3),sx=Math.cos(hh),sz=-Math.sin(hh);__gnb.cam([c.x+sx*6.5,g+1.1,c.z+sz*6.5,c.x,g+.8,c.z]);return{d:+bd.toFixed(1),k:c.k}});await p.waitForTimeout(2500);
  f=`${OUT}/${CITY}_${F[i]}_car.png`;await p.screenshot({path:f});out.push([f,JSON.stringify(r)]);
  const w=await p.evaluate(()=>{const M=__mho,R=M.RO;let b=null,bd=80;for(const q of(M.HUB.bld||[])){if(!(q.h>5)||q.hw<3||q.hd<3)continue;const d=Math.hypot(q.x-R.x,q.z-R.z);if(d<bd){bd=d;b=q}}if(!b)return null;const dx=R.x-b.x,dz=R.z-b.z,L=Math.hypot(dx,dz)||1,k=Math.max(b.hw,b.hd)+11,g=M.gnd(b.x+dx/L*k,b.z+dz/L*k,R.y+.3);__gnb.cam([b.x+dx/L*k,g+2.5,b.z+dz/L*k,b.x,g+4,b.z]);return{d:+bd.toFixed(1),h:b.h}});await p.waitForTimeout(2500);
  f=`${OUT}/${CITY}_${F[i]}_wall.png`;await p.screenshot({path:f});out.push([f,JSON.stringify(w)]);
  await p.evaluate(()=>{const M=__mho,R=M.RO,g=M.gnd(R.x,R.z,R.y+.3);__gnb.cam([R.x-Math.sin(R.h)*20,g+28,R.z-Math.cos(R.h)*20,R.x+Math.sin(R.h)*35,g,R.z+Math.cos(R.h)*35])});await p.waitForTimeout(2500);const n3=await info();
  f=`${OUT}/${CITY}_${F[i]}_roof.png`;await p.screenshot({path:f});out.push([f,n3.calls,n3.tris]);await p.evaluate(()=>__gnb.cam(null))}
 console.log(JSON.stringify(out));console.log('errors',errs.length,errs.slice(0,2).join('|').slice(0,200));await E.b.close()})();
