"""Write audio-data.js, MAP.md, credits.html, ASSETS.md for Lantern Dive from build_ld.py's output.
Usage: python3 bundle_ld.py <workdir>"""
import os, sys, json, base64
HERE = os.path.dirname(os.path.abspath(__file__))
W = os.path.abspath(sys.argv[1]); R = json.load(open(os.path.join(W, 'report.json')))
DATE = '2026-10-04'; CC0U = 'https://creativecommons.org/publicdomain/zero/1.0/'
b64 = lambda p: base64.b64encode(open(p, 'rb').read()).decode()
KEN = {'casino-audio': 'Casino Audio', 'interface-sounds': 'Interface Sounds', 'impact-sounds': 'Impact Sounds', 'rpg-audio': 'RPG Audio', 'ui-audio': 'UI Audio', 'music-jingles': 'Music Jingles'}
DESC = {'click': 'UI click', 'play': 'a card is laid on the table', 'slide': 'a card glides across (job card moved, card to the trick)', 'pass': 'cards are passed or the hand moves on (quiet)',
        'take': 'a job card is taken', 'ping': 'a diver shows a card with the ping (bong + glass tap)', 'trick': 'a trick is swept to its winner (chips handled)',
        'done': 'a job is done (soft confirmation + pluck)', 'fail': 'a job fails (low bell, pitched down)', 'deal': 'the deal (shuffle, cut to 1.2 s)', 'tick': 'counting tick, replay with a rising rate',
        'win': 'dive won (steel chimes + plucked jingle)', 'lose': 'dive lost (one sax jingle)', 'error': 'illegal move'}
USE = {'click': 'buttons', 'play': 'a card lands on the table', 'slide': 'a card or job card moves', 'pass': 'device passed / cards given', 'take': 'job taken', 'ping': 'a ping is shown',
       'trick': 'trick swept to the winner', 'done': 'job tick', 'fail': 'job cross', 'deal': 'new deal', 'tick': 'counting', 'win': 'result card, success', 'lose': 'result card, failure', 'error': 'refused move'}
MUS = {'main': ('Underwater Theme', 'Spring Spring', 'underwater-theme-1', 'https://opengameart.org/sites/default/files/underwater%20theme%202nd%20variation%20%28my%20preferred%29_1.ogg', 'underwater theme 2nd variation (my preferred)_1.ogg', 'music bed: calm underwater theme, loop'),
       'sea': ('Underwater Ambient Pad', 'isaiah658', 'underwater-ambient-pad', 'https://opengameart.org/sites/default/files/Underwater-Ambient-Pad-isaiah658_0.ogg', 'Underwater-Ambient-Pad-isaiah658_0.ogg', 'soft water pad, low-passed, loop under the music')}
srcs = lambda sp: [sp['src']] + [m[0] for m in sp.get('mix', [])]
parts = ['/* audio-data.js for Lantern Dive - generated by audio/lantern-dive/bundle_ld.py. Licences: ASSETS.md in this folder */', 'const GA_DATA={sfx:{']
sb = mb = 0
for n in DESC: p = os.path.join(W, 'sfx', n + '.mp3'); sb += os.path.getsize(p); parts.append('"%s":"%s",' % (n, b64(p)))
p = os.path.join(W, 'music', 'sea.mp3'); mb += os.path.getsize(p); parts.append('"sea":"%s",' % b64(p))
parts.append('},music:{')
p = os.path.join(W, 'music', 'main.mp3'); mb += os.path.getsize(p); parts.append('"main":"%s",' % b64(p))
parts.append('}};'); js = '\n'.join(parts) + '\n'; open(os.path.join(HERE, 'audio-data.js'), 'w').write(js)
L = ['# Lantern Dive: audio assets\n', 'All sounds are real CC0 recordings (Kenney packs, OpenGameArt), cut/layered/normalised by `build_ld.py` and bundled by `bundle_ld.py` (they import `../tools/dsp.py`, `sfx.py`). Checked %s. Licence snapshots: `licence-snapshots/` here (Kenney `License.txt` files and the two OpenGameArt pages). No synthesis; the game falls back to its built-in quiet synth only when `GA` or a sample is missing.\n' % DATE,
     '## Sound effects (mono MP3 48 kbps)\n', '| sample | source file(s) | pack | licence | length | size | use |', '|---|---|---|---|---|---|---|']
for n, v in R['sfx'].items():
    f = srcs(v['spec']); pk = sorted({KEN[x.split('/')[0]] for x in f})
    L.append('| `%s` | %s | Kenney %s | CC0 1.0 | %.2f s | %d B | %s |' % (n, ', '.join('`%s`' % os.path.basename(x) for x in f), ', '.join(pk), v['dur'], v['bytes'], DESC[n]))
L += ['', '## Music and ambience (mono MP3, seamless loop)\n', '| name | track | author | source page | download | licence | loop cut | length | size |', '|---|---|---|---|---|---|---|---|---|']
for n, m in R['music'].items():
    t, a, ps, dl, fn, d = MUS[n]
    cut = ('%.2f s-%.2f s, 1.5 s cross-fade (similarity %.3f)' % (m['a'], m['b'], m['sim'])) if m['sim'] else 'whole clip, low-passed 1.6 kHz, 2 s circular cross-fade'
    L.append('| `%s` | "%s" | %s | https://opengameart.org/content/%s | %s | CC0 1.0 | %s | %.1f s | %d B (%d kbps) |' % (n, t, a, ps, dl, cut, m['dur'], m['bytes'], m['kbps']))
L.append('\nTotals: SFX %d KB + music/ambience %d KB MP3 = %d KB; `audio-data.js` %d KB (base64). Licence: CC0 1.0 %s\n' % (sb // 1024, mb // 1024, (sb + mb) // 1024, len(js) // 1024, CC0U))
L.append('Rebuild: `python3 build_ld.py <raw> <work> && python3 bundle_ld.py <work>` (raw = Kenney zips unpacked + `mus/` with `uw_theme.ogg` and `uw_pad.ogg` downloaded from the URLs above).\n')
L.append('The shared `audio/ASSETS.md` has no rows for this game yet: append the rows from this table when merging (they were not added here because that file is shared).\n')
open(os.path.join(HERE, 'ASSETS.md'), 'w').write('\n'.join(L))
M = ["# Lantern Dive: sound map\n", "Load order: `gameaudio.js`, this `audio-data.js`, then the game. `GA.init({sfx:GA_DATA.sfx, music:GA_DATA.music, key:'ld'})`; every call is guarded with `window.GA && GA.has(name)` in `snd()` (ui6.js).\n", '| sample | length | used for |', '|---|---|---|']
for n in DESC: M.append('| `%s` | %.2f s | %s |' % (n, R['sfx'][n]['dur'], USE[n]))
M += ['', '## Music / ambience', '', '| name | length | track |', '|---|---|---|']
for n in MUS: M.append('| `%s` | %.1f s | %s: "%s" by %s |' % (n, R['music'][n]['dur'], MUS[n][5], MUS[n][0], MUS[n][1]))
M += ['', '```js', "GA.music('main',{vol:.3});            // after the first user gesture; seamless loop", "GA.loop('sea',{vol:.14,fade:1.5});     // 'sea' ships in GA_DATA.sfx so GA.loop works; GA.stopLoop('sea') at game end", '```', '', 'Not auditioned by ear (no speakers here): levels are in `SND_MAP` / `sndMusic()` in `ui6.js`.']
open(os.path.join(HERE, 'MAP.md'), 'w').write('\n'.join(M) + '\n')
mus = ''.join('<li>%s: &ldquo;%s&rdquo; by %s (<a href="https://opengameart.org/content/%s">OpenGameArt</a>, CC0)</li>\n' % ('Music' if n == 'main' else 'Ambience', MUS[n][0], MUS[n][1], MUS[n][2]) for n in MUS)
packs = sorted({KEN[x.split('/')[0]] for v in R['sfx'].values() for x in srcs(v['spec'])})
open(os.path.join(HERE, 'credits.html'), 'w').write('<!-- Credits snippet for Lantern Dive. Paste into the in-game Credits / Rules popup. Generated %s. -->\n<section class="credits-audio">\n<h3>Audio</h3>\n<p>With thanks to these public-domain (CC0) creators:</p>\n<ul>\n%s<li>Sound effects: %s by <a href="https://kenney.nl">Kenney</a> (CC0)</li>\n</ul>\n<p><small>All sounds were trimmed, loudness-normalised and converted to MP3 for this game. Names, card text and art are original.</small></p>\n</section>\n' % (DATE, mus, ', '.join(packs)))
print('ok', sb // 1024, mb // 1024, len(js) // 1024)
